const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const deck=window.SX_DECK.cards, questions=window.SX_QUESTIONS.questions, pbqs=window.SX_PBQS.drills, bp=window.SX_BLUEPRINT.entries, sources=window.SX_SOURCES;
const REVIEW_KEY='sx_review_state_v4_1';
const INTERVALS=[0,1,3,7,14,30,60,120];
let reviewState=JSON.parse(localStorage.getItem(REVIEW_KEY)||'{}');
const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const isoToday=()=>localISO(new Date());
const addDays=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return localISO(d)};
const saveReview=()=>localStorage.setItem(REVIEW_KEY,JSON.stringify(reviewState));
const stateOf=id=>reviewState[id]||null;
const isDue=id=>{const s=stateOf(id);return !!s && s.due<=isoToday()};
const isMature=id=>{const s=stateOf(id);return !!s && (s.stage||0)>=4};
const reviewLabel=id=>{const s=stateOf(id);if(!s)return'new';if(isMature(id))return`mature · due ${s.due}`;return`${isDue(id)?'due':'learning'} · stage ${s.stage||0} · due ${s.due}`};
function gradeCard(id,g){let s=stateOf(id)||{stage:0,reviews:0,lapses:0};let stage=s.stage||0;if(g===0){stage=0;s.lapses=(s.lapses||0)+1}else if(g===1){stage=Math.max(1,stage)}else if(g===2){stage=Math.min(stage+1,INTERVALS.length-1)}else if(g===3){stage=Math.min(stage+2,INTERVALS.length-1)}s.stage=stage;s.due=addDays(INTERVALS[stage]);s.reviews=(s.reviews||0)+1;s.last_grade=g;s.last_review=isoToday();reviewState[id]=s;saveReview();renderStats();}
function show(v){$$('.view').forEach(x=>x.classList.add('hidden'));$('#'+v).classList.remove('hidden');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));}
$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
function renderStats(){const due=deck.filter(c=>isDue(c.id)).length,newc=deck.filter(c=>!stateOf(c.id)).length,mature=deck.filter(c=>isMature(c.id)).length;$('#stats').innerHTML=[['Layered cards',deck.length],['Published topics','618 / 618'],['Hard questions',questions.length],['PBQ drills',pbqs.length],['Due now',due],['New',newc],['Mature',mature]].map(([a,b])=>`<div class="stat"><span class="muted">${a}</span><b>${b}</b></div>`).join('');}
renderStats();
const domains=[...new Set(deck.map(c=>c.domain))].sort();domains.forEach(d=>$('#domainFilter').insertAdjacentHTML('beforeend',`<option>${d}</option>`));
const objs=[...new Set(deck.map(c=>c.objective).filter(x=>x!=='Acronyms'))].sort((a,b)=>parseFloat(a)-parseFloat(b));objs.forEach(o=>{$('#objFilter').insertAdjacentHTML('beforeend',`<option>${o}</option>`);$('#bpObj').insertAdjacentHTML('beforeend',`<option>${o}</option>`) });
let filtered=deck.slice(),ci=0,layer=-1;
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function safeRich(s){return esc(s).replace(/&lt;b&gt;/gi,'<b>').replace(/&lt;\/b&gt;/gi,'</b>').replace(/&lt;br\s*\/?&gt;/gi,'<br>');}
function reviewMatches(c,f){if(!f)return true;const s=stateOf(c.id);if(f==='new')return !s;if(f==='due')return isDue(c.id);if(f==='mature')return isMature(c.id);if(f==='learning')return !!s&&!isMature(c.id);return true;}
function filterCards(){let s=$('#cardSearch').value.toLowerCase(),d=$('#domainFilter').value,o=$('#objFilter').value,r=$('#reviewFilter').value;filtered=deck.filter(c=>(!s||(c.front+' '+c.topic+' '+c.pages.map(p=>p.content).join(' ')).toLowerCase().includes(s))&&(!d||c.domain===d)&&(!o||c.objective===o)&&reviewMatches(c,r));ci=0;layer=-1;renderCard();}
['cardSearch','domainFilter','objFilter','reviewFilter'].forEach(id=>$('#'+id).addEventListener('input',filterCards));
function sourceLayer(c){return `<strong>8 · Sources</strong><p class="muted">Primary scope authority is CompTIA CAS-005; supporting standards are listed where relevant.</p>${c.source_ids.map(id=>{const s=sources[id];return s?`<div class="source"><strong>${esc(id)}</strong> — ${esc(s.title)}<br><span class="muted">${esc(s.role)}</span><br><a href="${esc(s.url)}" target="_blank" rel="noopener">Open source</a></div>`:''}).join('')}`;}
function renderCard(){if(!filtered.length){$('#cardCount').textContent='0 cards';$('#flashcard').innerHTML='<p>No matching cards.</p>';return}let c=filtered[ci%filtered.length],rs=stateOf(c.id);$('#cardCount').textContent=`${ci+1} / ${filtered.length} · ${reviewLabel(c.id)}`;let head=`<div><span class="pill">${esc(c.objective)}</span><span class="pill">${esc(c.card_type)}</span><span class="pill">content: ${esc(c.stage)}</span></div><div class="front">${esc(c.front)}</div>`;
if(layer<0){$('#flashcard').innerHTML=head+`<div class="retrieval-gate"><p><strong>Retrieve first.</strong> Commit to your answer aloud or in writing before revealing the back.</p><button class="btn primary" id="revealAnswer">Reveal Layer 1 · Direct Answer</button></div>`;$('#revealAnswer').onclick=()=>{layer=0;renderCard()};return;}
let tabs=c.pages.map((p,i)=>`<button data-i="${i}" class="${i===layer?'active':''}" title="${esc(p.title)}">${i+1}</button>`).join('');let body=layer===7?sourceLayer(c):`<strong>${esc(c.pages[layer].title)}</strong><p>${safeRich(c.pages[layer].content)}</p>`;let rating=`<div class="rating"><span class="muted">Grade retrieval:</span><button data-g="0" class="btn">Wrong</button><button data-g="1" class="btn">Hard</button><button data-g="2" class="btn">Good</button><button data-g="3" class="btn">Easy</button></div>`;$('#flashcard').innerHTML=head+`<div class="layer-tabs">${tabs}</div><div class="layer">${body}</div>${rating}`;$$('#flashcard .layer-tabs button').forEach(b=>b.onclick=()=>{layer=+b.dataset.i;renderCard()});$$('#flashcard .rating button').forEach(b=>b.onclick=()=>{gradeCard(c.id,+b.dataset.g);layer=-1;if($('#reviewFilter').value)filterCards();else{ci=(ci+1)%filtered.length;renderCard()}});}
$('#nextCard').onclick=()=>{if(filtered.length){ci=(ci+1)%filtered.length;layer=-1;renderCard()}};$('#prevCard').onclick=()=>{if(filtered.length){ci=(ci-1+filtered.length)%filtered.length;layer=-1;renderCard()}};$('#shuffleCard').onclick=()=>{for(let i=filtered.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[filtered[i],filtered[j]]=[filtered[j],filtered[i]]}ci=0;layer=-1;renderCard()};$('#markMastered').onclick=()=>{if(!filtered.length)return;let id=filtered[ci].id;if(reviewState[id]&&confirm('Reset spaced-review history for this card?')){delete reviewState[id];saveReview();renderStats();filterCards()}};filterCards();
let quiz=[];let qi=0;let score=0;function startQuiz(){let n=Math.min(+$('#quizCount').value,questions.length);quiz=questions.slice().sort(()=>Math.random()-.5).slice(0,n);qi=0;score=0;renderQ()}$('#startQuiz').onclick=startQuiz;function renderQ(){if(qi>=quiz.length){$('#quizBox').innerHTML=`<h3>Finished</h3><p>Score: <strong>${score}/${quiz.length}</strong> (${Math.round(score/quiz.length*100)}%)</p><p class="muted">Review reasoning, not answer letters. Re-test misses after a delay.</p>`;return}let q=quiz[qi];$('#quizBox').innerHTML=`<div class="muted">${qi+1}/${quiz.length} · ${esc(q.domain)} · ${esc(q.objective)}</div><h3>${esc(q.stem)}</h3><div id="opts">${q.options.map(o=>`<button class="qopt" data-a="${o[0]}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div>`;$$('#opts .qopt').forEach(b=>b.onclick=()=>{let ok=b.dataset.a===q.correct_answer;if(ok)score++;$$('#opts .qopt').forEach(x=>{x.disabled=true;if(x.dataset.a===q.correct_answer)x.classList.add('correct');else if(x===b&&!ok)x.classList.add('wrong')});$('#feedback').innerHTML=`<p><strong>${ok?'Correct':'Incorrect'}</strong></p><p>${esc(q.explanation)}</p><button class="btn primary" id="qnext">Next</button>`;$('#qnext').onclick=()=>{qi++;renderQ()}})}
$('#pbqList').innerHTML=pbqs.map(p=>`<div class="panel" style="margin:12px 0"><span class="pill">${esc(p.objective)}</span><h3>${esc(p.id)}</h3><p>${esc(p.prompt)}</p><details><summary>Scoring points</summary><ul>${p.scoring_points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></div>`).join('');
function openMappedCard(id){const c=deck.find(x=>x.id===id);if(!c)return;$('#cardSearch').value=id;$('#domainFilter').value='';$('#objFilter').value='';$('#reviewFilter').value='';filterCards();show('cards');}
function renderBP(){let s=$('#bpSearch').value.toLowerCase(),o=$('#bpObj').value;let rows=bp.filter(x=>(!s||x.topic.toLowerCase().includes(s))&&(!o||x.objective===o));$('#bpList').innerHTML=`<p class="muted">${rows.length} topics shown</p>`+rows.map(x=>`<div class="bp-row"><span>${esc(x.objective)}</span><span>${esc(x.topic)}</span><button class="map-card btn" data-card="${esc(x.card_id)}">${esc(x.card_id)}</button></div>`).join('');$$('.map-card').forEach(b=>b.onclick=()=>openMappedCard(b.dataset.card));}['bpSearch','bpObj'].forEach(id=>$('#'+id).addEventListener('input',renderBP));renderBP();
$('#sourceList').innerHTML=Object.entries(sources).map(([id,s])=>`<div class="source"><strong>${esc(id)}</strong> — ${esc(s.title)}<br><span class="muted">${esc(s.role)}</span><br><a href="${esc(s.url)}" target="_blank" rel="noopener">Open primary/reference source</a></div>`).join('');
