(()=>{'use strict';
const D={...window.CISSP_META,objectives:window.CISSP_CHUNKS.flatMap(x=>x.objectives),high:window.CISSP_CHUNKS.flatMap(x=>x.high),questions:window.CISSP_CHUNKS.flatMap(x=>x.questions)},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function layersFor(c){return [
 {title:'1 · Direct Answer',content:c.direct},
 {title:'2 · Concept Expansion',content:`${c.topic||c.label} is best treated as a decision problem: identify the business/security objective, accountable party, trust boundary or lifecycle stage, and the evidence that the chosen control reduces risk.`},
 {title:'3 · Worked Scenario',content:`Apply ${String(c.topic||c.label).toLowerCase()} to a new scenario by identifying the asset and requirement first, then selecting the control or process that addresses the root problem before optimizing technology.`},
 {title:'4 · Boundaries & Misconceptions',content:c.trap},
 {title:'5 · Connections & Memory',content:`Connect this to objective ${c.objective||c.id}, governance, risk ownership, lifecycle thinking, least privilege, defense in depth, and verifiable evidence.`},
 {title:'6 · Transfer Prompt',content:'How would the decision change if the system moved to a cloud/third-party model or a higher-impact regulatory context? State what stays accountable to the organization.'},
 {title:'7 · Mastery Evidence',content:'Explain the rule without notes, distinguish it from the nearest confusable concept, give a failure mode, and solve a fresh scenario with a one-sentence justification.'},
 {title:'8 · Sources',content:'See linked primary/reference sources.'}
]}
D.cards=[...D.objectives.map(o=>({id:`OBJ-${o.id}`,objective:o.id,domain:o.domain,domain_num:o.domain_num,kind:'Objective',front:`${o.id} · What is the key CISSP decision rule for ${o.label.toLowerCase()}?`,topic:o.label,direct:o.direct,trap:o.trap,pages:[],source_ids:o.source_ids})),...D.high.map(h=>({...h,kind:'High-yield',pages:[]}))];D.cards.forEach(c=>c.pages=layersFor(c));
const KEY='cissp_atlas_progress_v1', SETTINGS='cissp_atlas_settings_v1';
const INTERVALS=[0,1,3,7,14,30,60,120];
let state=safeParse(localStorage.getItem(KEY),{cards:{},quiz:{attempts:0,correct:0,byDomain:{}}});
let settings=safeParse(localStorage.getItem(SETTINGS),{});
let activeView='today', filtered=[], cardIndex=0, layer=-1, session={graded:0,correctish:0};
function safeParse(x,f){try{return x?JSON.parse(x):f}catch{return f}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function saveSettings(){localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function dayISO(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return dayISO(d)}
function cardState(id){return state.cards[id]||null}
function due(id){const s=cardState(id);return !!s&&s.due<=dayISO()}
function mature(id){const s=cardState(id);return !!s&&(s.stage||0)>=4}
function status(id){const s=cardState(id);if(!s)return'new';if(mature(id))return'mature';return due(id)?'due':'learning'}
function grade(id,g){let s=cardState(id)||{stage:0,reviews:0,lapses:0};let st=s.stage||0;if(g===0){st=0;s.lapses=(s.lapses||0)+1}else if(g===1){st=Math.max(1,st)}else if(g===2){st=Math.min(st+1,INTERVALS.length-1)}else{st=Math.min(st+2,INTERVALS.length-1)}s.stage=st;s.due=addDays(INTERVALS[st]);s.reviews=(s.reviews||0)+1;s.last_grade=g;s.last_review=dayISO();state.cards[id]=s;save();session.graded++;if(g>=2)session.correctish++;renderAllProgress()}
function objectiveCards(oid){return D.cards.filter(c=>c.objective===oid)}
function objectiveScore(oid){const cs=objectiveCards(oid);if(!cs.length)return 0;return cs.reduce((sum,c)=>sum+Math.min(4,(cardState(c.id)?.stage||0)),0)/(cs.length*4)}
function domainScore(n){const ids=D.objectives.filter(o=>o.domain_num===n).map(o=>o.id);return ids.length?ids.reduce((s,id)=>s+objectiveScore(id),0)/ids.length:0}
function overall(){let total=0;D.domains.forEach(d=>total+=domainScore(d.num)*d.weight);return total/100}
function show(view){activeView=view;$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+view).classList.remove('hidden');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo(0,0);if(view==='learn')filterCards();if(view==='blueprint')renderBlueprint();if(view==='progress')renderProgress();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.jump)));
D.domains.forEach(d=>{['domainFilter','bpDomain'].forEach(id=>$('#'+id)?.insertAdjacentHTML('beforeend',`<option value="${d.num}">D${d.num} · ${esc(d.name)}</option>`));$('#quizDomain')?.insertAdjacentHTML('beforeend',`<option value="${d.num}">D${d.num} · ${esc(d.name)}</option>`)});
D.objectives.forEach(o=>$('#objectiveFilter')?.insertAdjacentHTML('beforeend',`<option value="${o.id}">${o.id} · ${esc(o.label)}</option>`));
function renderToday(){const dueN=D.cards.filter(c=>due(c.id)).length,newN=D.cards.filter(c=>!cardState(c.id)).length,weak=weakestDomain(),pct=Math.round(overall()*100);$('#todayDate').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('#readinessCard').innerHTML=`<div class="ready-ring" style="--p:${pct}%"><strong>${pct}%</strong></div><div class="ready-copy"><b>Retrieval readiness</b><span>Based on spaced-review mastery, not page views.</span></div>`;$('#queueGrid').innerHTML=`<div class="queue-card" data-go="due"><div class="q-icon">↻</div><b>${dueN}</b><span>Due reviews</span><small>${dueN?'Best place to begin.':'Nothing overdue — keep momentum.'}</small></div><div class="queue-card" data-go="weak"><div class="q-icon">⌁</div><b>D${weak.num}</b><span>Weakest domain</span><small>${esc(weak.name)} · ${Math.round(weak.score*100)}% mastery</small></div><div class="queue-card" data-go="new"><div class="q-icon">＋</div><b>${newN}</b><span>Unseen cards</span><small>Introduce new material after due review.</small></div>`;$$('.queue-card').forEach(x=>x.onclick=()=>{if(x.dataset.go==='due'){$('#reviewFilter').value='due';show('learn')}else if(x.dataset.go==='new'){$('#reviewFilter').value='new';show('learn')}else{$('#domainFilter').value=String(weak.num);$('#reviewFilter').value='';show('learn')}});$('#domainMini').innerHTML=D.domains.map(d=>`<div class="domain-mini"><span class="domain-num">D${d.num}</span><span>${esc(d.name)}</span><div class="mini-bar"><i style="width:${Math.round(domainScore(d.num)*100)}%"></i></div><small>${d.weight}%</small></div>`).join('')}
function weakestDomain(){return D.domains.map(d=>({...d,score:domainScore(d.num)})).sort((a,b)=>a.score-b.score||b.weight-a.weight)[0]}
$('#continueBtn').onclick=()=>{const hasDue=D.cards.some(c=>due(c.id));$('#reviewFilter').value=hasDue?'due':'new';show('learn')};
function filterCards(){const s=($('#cardSearch')?.value||'').toLowerCase(),dn=+($('#domainFilter')?.value||0),oid=$('#objectiveFilter')?.value||'',rf=$('#reviewFilter')?.value||'';filtered=D.cards.filter(c=>(!s||`${c.id} ${c.front} ${c.topic} ${c.pages.map(p=>p.content).join(' ')}`.toLowerCase().includes(s))&&(!dn||c.domain_num===dn)&&(!oid||c.objective===oid)&&(!rf||(rf==='new'&&!cardState(c.id))||(rf==='mature'&&mature(c.id))||(rf==='due'&&due(c.id))||(rf==='learning'&&cardState(c.id)&&!mature(c.id))));if(rf==='due'&&!filtered.length){filtered=D.cards.filter(c=>!cardState(c.id)).slice(0,20)}cardIndex=Math.min(cardIndex,Math.max(0,filtered.length-1));layer=-1;renderCard()}
['cardSearch','domainFilter','objectiveFilter','reviewFilter'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{cardIndex=0;filterCards()}));
function sourceLayer(c){return `<h3>8 · Sources</h3>${c.source_ids.map(id=>{const s=D.sources[id];return s?`<p><b>${esc(s.title)}</b><br><span class="muted">${esc(s.role)}</span><br><a href="${esc(s.url)}" target="_blank" rel="noopener">Open source ↗</a></p>`:''}).join('')}`}
function renderCard(){if(!filtered.length){$('#flashcard').innerHTML='<div class="flash-front">No cards match this filter.</div>';$('#cardMeta').textContent='';$('#cardPosition').textContent='';return}const c=filtered[cardIndex],st=status(c.id);$('#cardMeta').innerHTML=`<span>${esc(c.id)} · ${esc(c.domain)}</span><span>${st}${cardState(c.id)?.due?` · due ${cardState(c.id).due}`:''}</span>`;$('#cardPosition').textContent=`${cardIndex+1} / ${filtered.length}`;const head=`<div class="pills"><span class="pill">${esc(c.objective)}</span><span class="pill">${esc(c.kind)}</span></div><div class="flash-front">${esc(c.front)}</div>`;if(layer<0){$('#flashcard').innerHTML=head+`<div class="retrieval-gate"><p><b>Retrieve before reveal.</b> Say or write the answer. Your first retrieval matters more than rereading.</p><button class="btn primary" id="revealBtn">Reveal direct answer</button></div>`;$('#revealBtn').onclick=()=>{layer=0;renderCard()};renderSession();return}const tabs=c.pages.map((p,i)=>`<button data-layer="${i}" class="${i===layer?'active':''}" aria-label="Layer ${i+1}" title="${esc(p.title)}">${i+1}</button>`).join('');const body=layer===7?sourceLayer(c):`<h3>${esc(c.pages[layer].title)}</h3><p>${esc(c.pages[layer].content)}</p>`;$('#flashcard').innerHTML=head+`<div class="layer-tabs">${tabs}</div><div class="layer-content">${body}</div><div class="rating"><span>Grade first retrieval</span><button data-grade="0" title="1">1 · Wrong</button><button data-grade="1" title="2">2 · Hard</button><button data-grade="2" title="3">3 · Good</button><button data-grade="3" title="4">4 · Easy</button></div>`;$$('[data-layer]').forEach(b=>b.onclick=()=>{layer=+b.dataset.layer;renderCard()});$$('[data-grade]').forEach(b=>b.onclick=()=>{grade(c.id,+b.dataset.grade);cardIndex=(cardIndex+1)%filtered.length;layer=-1;if($('#reviewFilter').value)filterCards();else renderCard()});renderSession()}
function renderSession(){const dueN=D.cards.filter(c=>due(c.id)).length;$('#sessionPanel').innerHTML=`<h3>Current session</h3><div class="session-metric"><b>${session.graded}</b><span>cards graded</span></div><div class="session-metric"><b>${session.graded?Math.round(session.correctish/session.graded*100):'—'}${session.graded?'%':''}</b><span>good/easy retrieval</span></div><div class="session-metric"><b>${dueN}</b><span>still due</span></div><div class="session-metric"><b>${Math.round(overall()*100)}%</b><span>weighted mastery</span></div>`}
$('#prevBtn').onclick=()=>{if(filtered.length){cardIndex=(cardIndex-1+filtered.length)%filtered.length;layer=-1;renderCard()}};$('#nextBtn').onclick=()=>{if(filtered.length){cardIndex=(cardIndex+1)%filtered.length;layer=-1;renderCard()}};$('#shuffleBtn').onclick=()=>{filtered.sort(()=>Math.random()-.5);cardIndex=0;layer=-1;renderCard()};
let quiz=[],qi=0,qscore=0,qanswered=[];
function makeQuiz(){const n=Math.min(+( $('#quizCount').value||10),D.questions.length),scope=$('#quizDomain').value;let pool=D.questions.slice();if(scope==='weak'){const order=D.domains.map(d=>({...d,score:domainScore(d.num)})).sort((a,b)=>a.score-b.score).map(x=>x.num);pool.sort((a,b)=>order.indexOf(a.domain_num)-order.indexOf(b.domain_num)||Math.random()-.5)}else if(scope){pool=pool.filter(q=>q.domain_num===+scope)}else{pool.sort(()=>Math.random()-.5)}quiz=pool.slice(0,Math.min(n,pool.length));qi=0;qscore=0;qanswered=[];$('#practiceSetup').classList.add('hidden');$('#quizBox').classList.remove('hidden');renderQuestion()}
$('#startQuiz').onclick=makeQuiz;
function renderQuestion(){if(qi>=quiz.length){renderQuizSummary();return}const q=quiz[qi];$('#quizBox').innerHTML=`<div class="quiz-card"><div class="quiz-top"><span>${qi+1} / ${quiz.length}</span><span>D${q.domain_num} · ${esc(q.objective)}</span></div><div class="mini-bar" style="margin-top:12px"><i style="width:${Math.round(qi/quiz.length*100)}%"></i></div><h2>${esc(q.stem)}</h2><div>${q.options.map((o,i)=>`<button class="qopt" data-opt="${i}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div></div>`;$$('[data-opt]').forEach(b=>b.onclick=()=>answerQuestion(+b.dataset.opt))}
function answerQuestion(choice){const q=quiz[qi],ok=choice===q.answer;qanswered.push({id:q.id,ok,domain_num:q.domain_num});if(ok)qscore++;state.quiz.attempts=(state.quiz.attempts||0)+1;state.quiz.correct=(state.quiz.correct||0)+(ok?1:0);const bd=state.quiz.byDomain[q.domain_num]||(state.quiz.byDomain[q.domain_num]={attempts:0,correct:0});bd.attempts++;bd.correct+=ok?1:0;save();$$('[data-opt]').forEach(b=>{b.disabled=true;const i=+b.dataset.opt;if(i===q.answer)b.classList.add('correct');else if(i===choice&&!ok)b.classList.add('wrong')});$('#feedback').innerHTML=`<div class="feedback"><p><b>${ok?'Correct':'Not quite.'}</b> ${esc(q.explanation)}</p><button class="btn primary" id="nextQ">${qi+1===quiz.length?'See results':'Next question'} →</button></div>`;$('#nextQ').onclick=()=>{qi++;renderQuestion()}}
function renderQuizSummary(){const pct=quiz.length?Math.round(qscore/quiz.length*100):0;const misses=qanswered.filter(x=>!x.ok);$('#quizBox').innerHTML=`<div class="quiz-card"><span class="kicker">SET COMPLETE</span><h2>${qscore}/${quiz.length} · ${pct}%</h2><p class="muted">Treat the score as feedback, not proof of readiness. Review why distractors were wrong and re-test after spacing.</p><div class="feedback"><b>${misses.length?`${misses.length} misses to repair`:'No misses in this set'}</b><p>${misses.length?'Use “Weakest domains first” next or return to Learn and filter the affected objectives.':'Choose a new mixed set so recall is not tied to this question order.'}</p></div><button class="btn primary" id="againBtn">New practice set</button></div>`;$('#againBtn').onclick=()=>{$('#practiceSetup').classList.remove('hidden');$('#quizBox').classList.add('hidden')};renderAllProgress()}
function bpState(o){const s=objectiveScore(o.id);return s>=.65?'mastered':s>0?'started':'untouched'}
function renderBlueprint(){const search=($('#bpSearch').value||'').toLowerCase(),dn=+($('#bpDomain').value||0),fs=$('#bpState').value||'';const groups=D.domains.filter(d=>!dn||d.num===dn).map(d=>({d,rows:D.objectives.filter(o=>o.domain_num===d.num&&(!search||`${o.id} ${o.label} ${o.summary}`.toLowerCase().includes(search))&&(!fs||bpState(o)===fs))})).filter(g=>g.rows.length);$('#blueprintList').innerHTML=groups.map(g=>`<div class="blueprint-domain"><div class="bp-domain-head"><b>D${g.d.num} · ${esc(g.d.name)}</b><span>${g.d.weight}% · ${g.rows.length} objectives shown</span></div>${g.rows.map(o=>`<div class="bp-row"><span class="oid">${o.id}</span><span class="bp-title">${esc(o.label)}</span><span class="state ${bpState(o)}">${bpState(o)}</span><button class="btn" data-open-obj="${o.id}">Study</button></div>`).join('')}</div>`).join('')||'<div class="panel">No objectives match.</div>';$$('[data-open-obj]').forEach(b=>b.onclick=()=>{$('#objectiveFilter').value=b.dataset.openObj;$('#domainFilter').value='';$('#reviewFilter').value='';$('#cardSearch').value='';show('learn')});$('#auditBadge').className='audit-badge good';$('#auditBadge').textContent=`✓ ${D.meta.objective_count}/${D.meta.objective_count} objective IDs mapped`}
['bpSearch','bpDomain','bpState'].forEach(id=>$('#'+id).addEventListener('input',renderBlueprint));
function renderProgress(){const reviewed=Object.keys(state.cards).length,matureN=D.cards.filter(c=>mature(c.id)).length,acc=state.quiz.attempts?Math.round(state.quiz.correct/state.quiz.attempts*100):0;$('#progressStats').innerHTML=[['Weighted mastery',`${Math.round(overall()*100)}%`],['Cards reviewed',`${reviewed}/${D.cards.length}`],['Mature cards',matureN],['Practice accuracy',state.quiz.attempts?`${acc}%`:'—']].map(([a,b])=>`<div class="stat-card"><small>${a}</small><b>${b}</b></div>`).join('');$('#domainProgress').innerHTML=D.domains.map(d=>{const p=Math.round(domainScore(d.num)*100);return `<div class="domain-row"><span class="domain-num">D${d.num}</span><span>${esc(d.name)}</span><div class="bar"><i style="width:${p}%"></i></div><small>${p}%</small></div>`}).join('');const weak=D.objectives.map(o=>({...o,score:objectiveScore(o.id)})).sort((a,b)=>a.score-b.score||a.domain_num-b.domain_num).slice(0,8);$('#weakList').innerHTML=weak.map(o=>`<div class="weak-item"><div><b>${o.id} · ${esc(o.label)}</b><br><span>D${o.domain_num} · ${Math.round(o.score*100)}% mastery</span></div><button class="btn" data-weak="${o.id}">Study</button></div>`).join('');$$('[data-weak]').forEach(b=>b.onclick=()=>{$('#objectiveFilter').value=b.dataset.weak;$('#reviewFilter').value='';show('learn')})}
function renderSources(){$('#sourceList').innerHTML=Object.entries(D.sources).map(([id,s])=>`<div class="source-card"><span class="pill">${esc(id)}</span><b>${esc(s.title)}</b><p>${esc(s.role)}</p><a href="${esc(s.url)}" target="_blank" rel="noopener">Open primary/reference source ↗</a></div>`).join('')}
function renderAllProgress(){renderToday();renderSession();if(activeView==='progress')renderProgress();if(activeView==='blueprint')renderBlueprint()}
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({exported:new Date().toISOString(),app:D.meta,state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cissp-atlas-progress-${dayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#resetBtn').onclick=()=>{if(confirm('Reset all CISSP Atlas local progress on this browser?')){state={cards:{},quiz:{attempts:0,correct:0,byDomain:{}}};save();session={graded:0,correctish:0};renderAllProgress();renderProgress()}};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('lightish');settings.contrast=document.body.classList.contains('lightish');saveSettings()};if(settings.contrast)document.body.classList.add('lightish');
function globalSearch(v){document.querySelector('.global-results')?.remove();v=v.trim().toLowerCase();if(v.length<2)return;const hits=[...D.objectives.filter(o=>`${o.id} ${o.label} ${o.summary}`.toLowerCase().includes(v)).slice(0,6).map(o=>({type:'objective',id:o.id,title:`${o.id} · ${o.label}`,sub:`D${o.domain_num} · objective`})),...D.cards.filter(c=>`${c.front} ${c.topic}`.toLowerCase().includes(v)).slice(0,6).map(c=>({type:'card',id:c.id,oid:c.objective,title:c.topic,sub:`${c.objective} · ${c.kind}`}))].slice(0,10);if(!hits.length)return;const box=document.createElement('div');box.className='global-results';box.innerHTML=hits.map((h,i)=>`<button class="global-hit" data-hit="${i}"><b>${esc(h.title)}</b><small>${esc(h.sub)}</small></button>`).join('');document.body.appendChild(box);$$('[data-hit]').forEach((b,i)=>b.onclick=()=>{const h=hits[i];$('#objectiveFilter').value=h.type==='objective'?h.id:(h.oid||'');$('#cardSearch').value=h.type==='card'?h.id:'';$('#reviewFilter').value='';box.remove();$('#globalSearch').value='';show('learn')})}
$('#globalSearch').addEventListener('input',e=>globalSearch(e.target.value));document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap')&&!e.target.closest('.global-results'))document.querySelector('.global-results')?.remove()});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#globalSearch').focus()}if(activeView==='learn'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){if(e.key===' '){e.preventDefault();if(layer<0){layer=0;renderCard()}}if(e.key==='ArrowRight')$('#nextBtn').click();if(e.key==='ArrowLeft')$('#prevBtn').click();if(layer>=0&&['1','2','3','4'].includes(e.key)){grade(filtered[cardIndex].id,+e.key-1);cardIndex=(cardIndex+1)%filtered.length;layer=-1;renderCard()}}});
renderSources();renderAllProgress();filterCards();renderBlueprint();renderProgress();
})();