(()=>{'use strict';
const coverage=window.CISSP_COVERAGE||{}, ai=window.CISSP_AI_COVERAGE||{}, chunks=window.CISSP_CHUNKS||[], questions=chunks.flatMap(x=>x.questions||[]), objectives=chunks.flatMap(x=>x.objectives||[]), domains=window.CISSP_META?.domains||[], bellringers=window.CISSP_BELLRINGERS||[];
const objectiveById=Object.fromEntries(objectives.map(o=>[o.id,o]));
const DKEY='cissp_atlas_diagnostic_v1',PKEY='cissp_atlas_progress_v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const subtopicCount=Object.values(coverage).reduce((n,a)=>n+a.length,0);
const primaryBtn=document.querySelector('#continueBtn'),baseContinue=primaryBtn?.onclick;
const tierName={F:'Foundation+',E:'Exam-calibrated',S:'Stretch',B:'Bellringer'};
function navigate(view){const b=document.querySelector(`#nav [data-view="${view}"]`)||document.querySelector(`.mobile-nav [data-view="${view}"]`);b?.click()}
function readProgress(){try{return JSON.parse(localStorage.getItem(PKEY)||'{"cards":{},"quiz":{"attempts":0,"correct":0,"byDomain":{}}}') }catch{return {cards:{},quiz:{attempts:0,correct:0,byDomain:{}}}}}
function writeProgress(s){localStorage.setItem(PKEY,JSON.stringify(s))}
function domainMastery(n){const st=readProgress(),objs=objectives.filter(o=>o.domain_num===n);if(!objs.length)return 0;return objs.reduce((sum,o)=>{const cards=[`OBJ-${o.id}`,...chunks.flatMap(x=>x.high||[]).filter(h=>h.objective===o.id).map(h=>h.id)];const sc=cards.length?cards.reduce((z,id)=>z+Math.min(4,st.cards?.[id]?.stage||0),0)/(cards.length*4):0;return sum+sc},0)/objs.length}
function decorateBlueprint(){document.querySelectorAll('.bp-row').forEach(row=>{if(row.querySelector('.coverage-details'))return;const oid=row.querySelector('.oid')?.textContent.trim(),items=coverage[oid];if(!items)return;const d=document.createElement('details');d.className='coverage-details';d.innerHTML=`<summary>${items.length} mapped subtopic${items.length===1?'':'s'}</summary><div class="coverage-chips">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;row.appendChild(d)});document.querySelectorAll('.bp-domain-head').forEach(head=>{if(head.dataset.coverageDecorated)return;const m=head.querySelector('b')?.textContent.match(/^D(\d+)/);if(!m)return;const dn=+m[1],n=Object.entries(coverage).filter(([k])=>+k.split('.')[0]===dn).reduce((s,[,v])=>s+v.length,0),a=(ai[dn]||[]).length;const span=head.querySelector('span');if(span)span.textContent+=` · ${n} mapped subtopics${a?` · ${a} AI areas`:''}`;head.dataset.coverageDecorated='1'});const badge=document.querySelector('#auditBadge');if(badge){badge.title=`${subtopicCount} paraphrased public-outline subtopic checks plus current cross-domain AI coverage`;badge.textContent=`62 objectives · ${subtopicCount} subtopics · ${questions.length} MCQs · ${bellringers.length} Bellringer`}}
let bpTimer;const bp=document.querySelector('#blueprintList');if(bp)new MutationObserver(()=>{clearTimeout(bpTimer);bpTimer=setTimeout(decorateBlueprint,0)}).observe(bp,{childList:true,subtree:true});decorateBlueprint();
function addPracticeLens(){const setup=document.querySelector('#practiceSetup');if(!setup||document.querySelector('.decision-lens'))return;const panel=document.createElement('div');panel.className='decision-lens panel';panel.innerHTML='<span class="kicker">CISSP DECISION LENS</span><div class="lens-grid"><span><b>1</b> Protect people, ethics, law</span><span><b>2</b> Clarify business need and owner</span><span><b>3</b> Assess risk before tooling</span><span><b>4</b> Prefer policy/process before implementation detail</span><span><b>5</b> Use least privilege and defense in depth</span><span><b>6</b> Preserve evidence and verify outcomes</span></div><p class="muted lens-note">Not an answer-key shortcut: use these as tie-breakers only when the scenario supports them.</p>';setup.parentNode.insertBefore(panel,setup)}
addPracticeLens();
if(window.CISSP_RELEASE_LOAD_ERROR){const p=document.querySelector('#practice');p?.insertAdjacentHTML('afterbegin',`<div class="notice"><b>Released-bank load warning:</b> ${esc(window.CISSP_RELEASE_LOAD_ERROR)}. Base questions remain usable, but the promoted batch may be unavailable until this page is served over HTTP.</div>`)}
function getDiagnostic(){try{return JSON.parse(localStorage.getItem(DKEY)||'null')}catch{return null}}
function syncPrimaryCTA(){if(!primaryBtn)return;const saved=getDiagnostic();if(saved){primaryBtn.textContent='Continue today’s session';primaryBtn.onclick=baseContinue}else{primaryBtn.textContent='Run baseline diagnostic';primaryBtn.onclick=startDiagnostic}}
function renderDiagnosticStatus(){document.querySelector('.diagnostic-banner')?.remove();const hero=document.querySelector('#today .hero');if(!hero)return;const saved=getDiagnostic(),box=document.createElement('div');box.className='diagnostic-banner';if(saved){const low=Object.entries(saved.byDomain).sort((a,b)=>a[1].correct-b[1].correct)[0];const name=domains.find(d=>String(d.num)===low?.[0])?.name||'weakest domain';box.innerHTML=`<div><span class="kicker">BASELINE SAVED</span><b>${saved.correct}/16 diagnostic</b><small>Lowest result: D${esc(low?.[0])} · ${esc(name)}. Re-run after a meaningful review cycle, not immediately.</small></div><button class="btn" id="diagAgain">Re-run diagnostic</button>`}else{box.innerHTML='<div><span class="kicker">FIRST-RUN BASELINE</span><b>Start with a 16-question diagnostic</b><small>Two original scenarios per domain. It routes your first study block without pretending 16 questions prove exam readiness.</small></div><button class="btn primary" id="diagStart">Run diagnostic</button>'}hero.insertAdjacentElement('afterend',box);document.querySelector('#diagStart')?.addEventListener('click',startDiagnostic);document.querySelector('#diagAgain')?.addEventListener('click',startDiagnostic);syncPrimaryCTA()}
function diagnosticSet(){const out=[];domains.forEach(d=>{const pool=questions.filter(q=>q.domain_num===d.num).slice().sort(()=>Math.random()-.5);out.push(...pool.slice(0,2))});return out.sort(()=>Math.random()-.5)}
let dq=[],di=0,dcorrect=0,dres={};
function startDiagnostic(){navigate('practice');const setup=document.querySelector('#practiceSetup'),box=document.querySelector('#quizBox');setup?.classList.add('hidden');box?.classList.remove('hidden');dq=diagnosticSet();di=0;dcorrect=0;dres={};domains.forEach(d=>dres[d.num]={correct:0,total:0});renderDiagnosticQuestion()}
function renderDiagnosticQuestion(){const box=document.querySelector('#quizBox');if(!box)return;if(di>=dq.length){finishDiagnostic();return}const q=dq[di];box.innerHTML=`<div class="quiz-card diagnostic-card"><div class="quiz-top"><span>Diagnostic · ${di+1}/16</span><span>D${q.domain_num} · ${esc(q.objective)}</span></div><div class="mini-bar" style="margin-top:12px"><i style="width:${Math.round(di/16*100)}%"></i></div><h2>${esc(q.stem)}</h2><div>${q.options.map((o,i)=>`<button class="qopt" data-diag-opt="${i}">${esc(o)}</button>`).join('')}</div><div id="diagFeedback"></div></div>`;box.querySelectorAll('[data-diag-opt]').forEach(b=>b.onclick=()=>answerDiagnostic(+b.dataset.diagOpt))}
function answerDiagnostic(choice){const q=dq[di],ok=choice===q.answer;dres[q.domain_num].total++;if(ok){dcorrect++;dres[q.domain_num].correct++}document.querySelectorAll('[data-diag-opt]').forEach(b=>{b.disabled=true;const i=+b.dataset.diagOpt;if(i===q.answer)b.classList.add('correct');else if(i===choice&&!ok)b.classList.add('wrong')});document.querySelector('#diagFeedback').innerHTML=`<div class="feedback"><p><b>${ok?'Correct':'Incorrect.'}</b> ${esc(q.explanation)}</p><button class="btn primary" id="diagNext">${di===15?'See baseline':'Next'} →</button></div>`;document.querySelector('#diagNext').onclick=()=>{di++;renderDiagnosticQuestion()}}
function finishDiagnostic(){const result={date:new Date().toISOString(),correct:dcorrect,total:16,byDomain:dres};localStorage.setItem(DKEY,JSON.stringify(result));const sorted=domains.map(d=>({...d,score:dres[d.num].correct})).sort((a,b)=>a.score-b.score||b.weight-a.weight),weak=sorted[0];const box=document.querySelector('#quizBox');box.innerHTML=`<div class="quiz-card"><span class="kicker">DIAGNOSTIC COMPLETE</span><h2>${dcorrect}/16 baseline</h2><p class="muted">This is a routing signal, not an exam-readiness score. Two questions per domain are intentionally too small to support a pass prediction.</p><div class="diag-domain-grid">${domains.map(d=>`<div><b>D${d.num}</b><span>${dres[d.num].correct}/2</span><small>${esc(d.name)}</small></div>`).join('')}</div><div class="feedback"><b>Start with D${weak.num} · ${esc(weak.name)}</b><p>Review this domain, then interleave it with stronger domains instead of drilling it in isolation indefinitely.</p></div><div class="diag-actions"><button class="btn primary" id="diagWeak">Study weakest domain</button><button class="btn" id="diagPractice">Return to practice setup</button></div></div>`;document.querySelector('#diagWeak').onclick=()=>{navigate('learn');const f=document.querySelector('#domainFilter');if(f){f.value=String(weak.num);f.dispatchEvent(new Event('input',{bubbles:true}))}const r=document.querySelector('#reviewFilter');if(r){r.value='';r.dispatchEvent(new Event('input',{bubbles:true}))}};document.querySelector('#diagPractice').onclick=returnPracticeSetup;renderDiagnosticStatus()}
renderDiagnosticStatus();
const practiceButton=document.createElement('button');practiceButton.className='btn';practiceButton.id='diagnosticPracticeBtn';practiceButton.textContent='Run 16-question diagnostic';document.querySelector('#practiceSetup')?.appendChild(practiceButton);practiceButton.onclick=startDiagnostic;

// Calibrated standard-question engine. It intentionally intercepts the legacy Start button.
let pq=[],pi=0,pscore=0,panswered=[],pconfidence=null;
function choosePool(){const diff=document.querySelector('#quizDifficulty')?.value||'',scope=document.querySelector('#quizDomain')?.value||'';let pool=questions.slice();if(diff==='ES')pool=pool.filter(q=>['E','S'].includes(q.difficulty_tier));else if(diff)pool=pool.filter(q=>q.difficulty_tier===diff);if(scope==='weak'){const order=domains.map(d=>({...d,score:domainMastery(d.num)})).sort((a,b)=>a.score-b.score||b.weight-a.weight).map(d=>d.num);pool.sort((a,b)=>order.indexOf(a.domain_num)-order.indexOf(b.domain_num)||Math.random()-.5)}else if(scope){pool=pool.filter(q=>q.domain_num===+scope).sort(()=>Math.random()-.5)}else pool.sort(()=>Math.random()-.5);return pool}
function startCalibratedQuiz(){const count=+(document.querySelector('#quizCount')?.value||10),pool=choosePool();if(!pool.length){document.querySelector('#quizBox').classList.remove('hidden');document.querySelector('#quizBox').innerHTML='<div class="quiz-card"><h2>No questions match those filters.</h2><button class="btn" id="practiceBack">Back to setup</button></div>';document.querySelector('#practiceBack').onclick=returnPracticeSetup;document.querySelector('#practiceSetup').classList.add('hidden');return}pq=pool.slice(0,Math.min(count,pool.length));pi=0;pscore=0;panswered=[];pconfidence=null;document.querySelector('#practiceSetup').classList.add('hidden');document.querySelector('#quizBox').classList.remove('hidden');renderCalibratedQuestion()}
function tierPill(q){const t=q.difficulty_tier||'?';return `<span class="difficulty-pill tier-${esc(t)}">${esc(tierName[t]||'Uncalibrated')}${q.difficulty_score?` · ${q.difficulty_score}`:''}</span>`}
function renderCalibratedQuestion(){const box=document.querySelector('#quizBox');if(pi>=pq.length){renderCalibratedSummary();return}const q=pq[pi];pconfidence=null;box.innerHTML=`<div class="quiz-card"><div class="quiz-top"><span>${pi+1} / ${pq.length}</span><span>D${q.domain_num} · ${esc(q.objective)} ${tierPill(q)}</span></div><div class="mini-bar" style="margin-top:12px"><i style="width:${Math.round(pi/pq.length*100)}%"></i></div><h2>${esc(q.stem)}</h2><div class="confidence-box"><b>Commit confidence before answering</b><div><button data-conf="low">Low</button><button data-conf="medium">Medium</button><button data-conf="high">High</button></div></div><div class="practice-options">${q.options.map((o,i)=>`<button class="qopt" data-cal-opt="${i}" disabled>${esc(o)}</button>`).join('')}</div><div id="calFeedback"></div></div>`;box.querySelectorAll('[data-conf]').forEach(b=>b.onclick=()=>{pconfidence=b.dataset.conf;box.querySelectorAll('[data-conf]').forEach(x=>x.classList.toggle('selected',x===b));box.querySelectorAll('[data-cal-opt]').forEach(x=>x.disabled=false)});box.querySelectorAll('[data-cal-opt]').forEach(b=>b.onclick=()=>answerCalibrated(+b.dataset.calOpt))}
function optionRationales(q){if(Array.isArray(q.distractor_rationales)&&q.distractor_rationales.length===4)return q.distractor_rationales;return q.options.map((_,i)=>i===q.answer?q.explanation:'This legacy baseline distractor does not best satisfy the stated decision point; compare it against the keyed rule and scenario evidence.')}
function recordPractice(q,choice,ok){const st=readProgress();st.quiz=st.quiz||{attempts:0,correct:0,byDomain:{}};st.quiz.attempts=(st.quiz.attempts||0)+1;st.quiz.correct=(st.quiz.correct||0)+(ok?1:0);st.quiz.byDomain=st.quiz.byDomain||{};const d=st.quiz.byDomain[q.domain_num]||(st.quiz.byDomain[q.domain_num]={attempts:0,correct:0});d.attempts++;d.correct+=ok?1:0;st.quiz.history=st.quiz.history||[];st.quiz.history.push({id:q.id,date:new Date().toISOString(),ok,choice,answer:q.answer,confidence:pconfidence,difficulty_tier:q.difficulty_tier||null,difficulty_score:q.difficulty_score||null,objective:q.objective});if(st.quiz.history.length>500)st.quiz.history=st.quiz.history.slice(-500);writeProgress(st)}
function answerCalibrated(choice){const q=pq[pi],ok=choice===q.answer,rs=optionRationales(q);if(ok)pscore++;panswered.push({id:q.id,ok,domain_num:q.domain_num,confidence:pconfidence,tier:q.difficulty_tier});recordPractice(q,choice,ok);document.querySelectorAll('[data-cal-opt]').forEach(b=>{b.disabled=true;const i=+b.dataset.calOpt;if(i===q.answer)b.classList.add('correct');else if(i===choice&&!ok)b.classList.add('wrong')});document.querySelectorAll('[data-conf]').forEach(b=>b.disabled=true);const confidentWrong=!ok&&pconfidence==='high';document.querySelector('#calFeedback').innerHTML=`<div class="feedback"><p><b>${ok?'Correct.':'Incorrect.'}</b> ${esc(q.explanation)}</p>${confidentWrong?'<p class="cal-alert"><b>High-confidence miss:</b> prioritize this misconception for repair.</p>':''}<div class="rationale-grid">${q.options.map((o,i)=>`<div class="rationale-item ${i===q.answer?'winner':''}"><b>${i===q.answer?'✓ Best answer':'Why this loses'}</b><span>${esc(o)}</span><small>${esc(rs[i])}</small></div>`).join('')}</div><button class="btn primary" id="calNext">${pi+1===pq.length?'See results':'Next question'} →</button></div>`;document.querySelector('#calNext').onclick=()=>{pi++;renderCalibratedQuestion()}}
function renderCalibratedSummary(){const pct=pq.length?Math.round(pscore/pq.length*100):0,misses=panswered.filter(x=>!x.ok),hc=misses.filter(x=>x.confidence==='high');const tierCounts=panswered.reduce((a,x)=>(a[x.tier]=(a[x.tier]||0)+1,a),{});document.querySelector('#quizBox').innerHTML=`<div class="quiz-card"><span class="kicker">CALIBRATED SET COMPLETE</span><h2>${pscore}/${pq.length} · ${pct}%</h2><p class="muted">Use this as feedback, not a pass prediction. High-confidence misses are especially valuable because they expose durable misconceptions.</p><div class="summary-strip"><span><b>${misses.length}</b> misses</span><span><b>${hc.length}</b> high-confidence misses</span><span><b>${tierCounts.E||0}</b> exam-calibrated</span><span><b>${tierCounts.S||0}</b> stretch</span></div><div class="diag-actions"><button class="btn primary" id="calAgain">New set</button><button class="btn" id="calLearn">Repair in Learn</button></div></div>`;document.querySelector('#calAgain').onclick=returnPracticeSetup;document.querySelector('#calLearn').onclick=()=>navigate('learn')}
const startBtn=document.querySelector('#startQuiz');if(startBtn)startBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();startCalibratedQuiz()},{capture:true});
function returnPracticeSetup(){document.querySelector('#practiceSetup')?.classList.remove('hidden');document.querySelector('#quizBox')?.classList.add('hidden');document.querySelector('#quizBox').innerHTML=''}

// Bellringers are deliberately non-exam-representative integrative case drills.
function startBellringer(){if(!bellringers.length){document.querySelector('#practiceSetup').classList.add('hidden');const box=document.querySelector('#quizBox');box.classList.remove('hidden');box.innerHTML='<div class="quiz-card"><h2>No released Bellringer is available.</h2><button class="btn" id="practiceBack">Back</button></div>';document.querySelector('#practiceBack').onclick=returnPracticeSetup;return}const b=bellringers[Math.floor(Math.random()*bellringers.length)];document.querySelector('#practiceSetup').classList.add('hidden');const box=document.querySelector('#quizBox');box.classList.remove('hidden');box.innerHTML=`<div class="quiz-card bellringer-card"><div class="bell-warning">NON-EXAM-REPRESENTATIVE INTEGRATIVE DRILL</div><div class="quiz-top"><span>${esc(b.id)}</span>${tierPill(b)}</div><h2>${esc(b.stem)}</h2><p class="muted">Work each prompt before revealing the rubric. Aim to name owners, sequence decisions, justify tradeoffs, and connect domains.</p><div class="bell-prompts">${b.prompts.map((p,i)=>`<label><b>${i+1}. ${esc(p)}</b><textarea data-bell-answer="${i}" rows="4" placeholder="Construct your answer before revealing the rubric…"></textarea></label>`).join('')}</div><button class="btn primary" id="revealBell">Reveal teaching rubric</button><button class="btn" id="bellBack">Exit case</button><div id="bellRubric"></div></div>`;document.querySelector('#bellBack').onclick=returnPracticeSetup;document.querySelector('#revealBell').onclick=()=>revealBellringer(b)}
function revealBellringer(b){const box=document.querySelector('#bellRubric'),sc=b.rubric?.scoring||[],max=b.rubric?.max_points||sc.reduce((n,x)=>n+(x.points||0),0);box.innerHTML=`<div class="bell-rubric"><span class="kicker">TEACHING RUBRIC</span>${sc.map(x=>`<div><b>Prompt ${x.prompt} · ${x.points} points</b><ul>${(x.expects||[]).map(e=>`<li>${esc(e)}</li>`).join('')}</ul></div>`).join('')}<label class="self-score"><b>Self-score</b><input id="bellScore" type="number" min="0" max="${max}" value="0"> / ${max}</label><button class="btn primary" id="saveBell">Complete Bellringer</button></div>`;document.querySelector('#revealBell').disabled=true;document.querySelector('#saveBell').onclick=()=>{const score=Math.max(0,Math.min(max,+(document.querySelector('#bellScore').value||0))),st=readProgress();st.bellringers=st.bellringers||{attempts:0,history:[]};st.bellringers.attempts++;st.bellringers.history.push({id:b.id,date:new Date().toISOString(),score,max});if(st.bellringers.history.length>100)st.bellringers.history=st.bellringers.history.slice(-100);writeProgress(st);document.querySelector('#quizBox').innerHTML=`<div class="quiz-card"><span class="kicker">BELLRINGER COMPLETE</span><h2>${score}/${max}</h2><p class="muted">Use the missed rubric points as retrieval targets. Bellringer scores are integrative drill feedback, not CISSP score predictions.</p><button class="btn primary" id="bellDone">Return to practice</button></div>`;document.querySelector('#bellDone').onclick=returnPracticeSetup}}
document.querySelector('#startBellringer')?.addEventListener('click',startBellringer);

function addSubtopicSearch(){const input=document.querySelector('#globalSearch');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(q.length<2)return;setTimeout(()=>{const hits=[];for(const [oid,items] of Object.entries(coverage)){const matched=items.filter(x=>x.toLowerCase().includes(q));if(matched.length)hits.push({oid,matched:matched.slice(0,2),o:objectiveById[oid]})}for(const [dn,items] of Object.entries(ai)){const matched=items.filter(x=>x.toLowerCase().includes(q));if(matched.length){const o=objectives.find(x=>x.domain_num===+dn);if(o&&!hits.some(h=>h.oid===o.id))hits.push({oid:o.id,matched:matched.slice(0,2),o,ai:true})}}if(!hits.length)return;let box=document.querySelector('.global-results');if(!box){box=document.createElement('div');box.className='global-results';document.body.appendChild(box)}const existing=new Set([...box.querySelectorAll('[data-coverage-hit]')].map(x=>x.dataset.coverageHit));hits.slice(0,6).forEach(h=>{if(existing.has(h.oid))return;const b=document.createElement('button');b.className='global-hit';b.dataset.coverageHit=h.oid;b.innerHTML=`<b>${esc(h.oid)} · ${esc(h.o?.label||'Mapped objective')}</b><small>${h.ai?'AI coverage':'Subtopic'} · ${esc(h.matched.join(' · '))}</small>`;b.onclick=()=>{input.value='';box.remove();navigate('blueprint');const s=document.querySelector('#bpSearch');if(s){s.value=h.oid;s.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>document.querySelector('.coverage-details')?.setAttribute('open',''),20)}};box.appendChild(b)})},0)})}
addSubtopicSearch();
const aria={globalSearch:'Search CISSP objectives, cards, and subtopics',cardSearch:'Filter study cards',domainFilter:'Filter cards by domain',objectiveFilter:'Filter cards by objective',reviewFilter:'Filter cards by review state',bpSearch:'Search blueprint objectives',bpDomain:'Filter blueprint by domain',bpState:'Filter blueprint by mastery state',quizCount:'Practice question count',quizDomain:'Practice domain scope',quizDifficulty:'Practice difficulty',startBellringer:'Start a non-exam-representative Bellringer case',themeBtn:'Toggle visual contrast'};Object.entries(aria).forEach(([id,label])=>document.getElementById(id)?.setAttribute('aria-label',label));
})();
