(()=>{'use strict';
const coverage=window.CISSP_COVERAGE||{}, ai=window.CISSP_AI_COVERAGE||{}, chunks=window.CISSP_CHUNKS||[], questions=chunks.flatMap(x=>x.questions||[]), objectives=chunks.flatMap(x=>x.objectives||[]), domains=window.CISSP_META?.domains||[];
const objectiveById=Object.fromEntries(objectives.map(o=>[o.id,o]));
const DKEY='cissp_atlas_diagnostic_v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
const subtopicCount=Object.values(coverage).reduce((n,a)=>n+a.length,0);
const primaryBtn=document.querySelector('#continueBtn'),baseContinue=primaryBtn?.onclick;
function navigate(view){const b=document.querySelector(`#nav [data-view="${view}"]`)||document.querySelector(`.mobile-nav [data-view="${view}"]`);b?.click()}
function decorateBlueprint(){document.querySelectorAll('.bp-row').forEach(row=>{if(row.querySelector('.coverage-details'))return;const oid=row.querySelector('.oid')?.textContent.trim(),items=coverage[oid];if(!items)return;const d=document.createElement('details');d.className='coverage-details';d.innerHTML=`<summary>${items.length} mapped subtopic${items.length===1?'':'s'}</summary><div class="coverage-chips">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;row.appendChild(d)});document.querySelectorAll('.bp-domain-head').forEach(head=>{if(head.dataset.coverageDecorated)return;const m=head.querySelector('b')?.textContent.match(/^D(\d+)/);if(!m)return;const dn=+m[1],n=Object.entries(coverage).filter(([k])=>+k.split('.')[0]===dn).reduce((s,[,v])=>s+v.length,0),a=(ai[dn]||[]).length;const span=head.querySelector('span');if(span)span.textContent+=` · ${n} mapped subtopics${a?` · ${a} AI areas`:''}`;head.dataset.coverageDecorated='1'});const badge=document.querySelector('#auditBadge');if(badge)badge.title=`${subtopicCount} paraphrased public-outline subtopic checks plus current cross-domain AI coverage`}
let bpTimer;const bp=document.querySelector('#blueprintList');if(bp)new MutationObserver(()=>{clearTimeout(bpTimer);bpTimer=setTimeout(decorateBlueprint,0)}).observe(bp,{childList:true,subtree:true});decorateBlueprint();
function addPracticeLens(){const setup=document.querySelector('#practiceSetup');if(!setup||document.querySelector('.decision-lens'))return;const panel=document.createElement('div');panel.className='decision-lens panel';panel.innerHTML='<span class="kicker">CISSP DECISION LENS</span><div class="lens-grid"><span><b>1</b> Protect people, ethics, law</span><span><b>2</b> Clarify business need and owner</span><span><b>3</b> Assess risk before tooling</span><span><b>4</b> Prefer policy/process before implementation detail</span><span><b>5</b> Use least privilege and defense in depth</span><span><b>6</b> Preserve evidence and verify outcomes</span></div><p class="muted lens-note">Not an answer-key shortcut: use these as tie-breakers only when the scenario supports them.</p>';setup.parentNode.insertBefore(panel,setup)}
addPracticeLens();
function getDiagnostic(){try{return JSON.parse(localStorage.getItem(DKEY)||'null')}catch{return null}}
function syncPrimaryCTA(){if(!primaryBtn)return;const saved=getDiagnostic();if(saved){primaryBtn.textContent='Continue today’s session';primaryBtn.onclick=baseContinue}else{primaryBtn.textContent='Run baseline diagnostic';primaryBtn.onclick=startDiagnostic}}
function renderDiagnosticStatus(){document.querySelector('.diagnostic-banner')?.remove();const hero=document.querySelector('#today .hero');if(!hero)return;const saved=getDiagnostic(),box=document.createElement('div');box.className='diagnostic-banner';if(saved){const low=Object.entries(saved.byDomain).sort((a,b)=>a[1].correct-b[1].correct)[0];const name=domains.find(d=>String(d.num)===low?.[0])?.name||'weakest domain';box.innerHTML=`<div><span class="kicker">BASELINE SAVED</span><b>${saved.correct}/16 diagnostic</b><small>Lowest result: D${esc(low?.[0])} · ${esc(name)}. Re-run after a meaningful review cycle, not immediately.</small></div><button class="btn" id="diagAgain">Re-run diagnostic</button>`}else{box.innerHTML='<div><span class="kicker">FIRST-RUN BASELINE</span><b>Start with a 16-question diagnostic</b><small>Two original scenarios per domain. It routes your first study block without pretending 16 questions prove exam readiness.</small></div><button class="btn primary" id="diagStart">Run diagnostic</button>'}hero.insertAdjacentElement('afterend',box);document.querySelector('#diagStart')?.addEventListener('click',startDiagnostic);document.querySelector('#diagAgain')?.addEventListener('click',startDiagnostic);syncPrimaryCTA()}
function diagnosticSet(){const out=[];domains.forEach(d=>{const pool=questions.filter(q=>q.domain_num===d.num).slice().sort(()=>Math.random()-.5);out.push(...pool.slice(0,2))});return out.sort(()=>Math.random()-.5)}
let dq=[],di=0,dcorrect=0,dres={};
function startDiagnostic(){navigate('practice');const setup=document.querySelector('#practiceSetup'),box=document.querySelector('#quizBox');setup?.classList.add('hidden');box?.classList.remove('hidden');dq=diagnosticSet();di=0;dcorrect=0;dres={};domains.forEach(d=>dres[d.num]={correct:0,total:0});renderDiagnosticQuestion()}
function renderDiagnosticQuestion(){const box=document.querySelector('#quizBox');if(!box)return;if(di>=dq.length){finishDiagnostic();return}const q=dq[di];box.innerHTML=`<div class="quiz-card diagnostic-card"><div class="quiz-top"><span>Diagnostic · ${di+1}/16</span><span>D${q.domain_num} · ${esc(q.objective)}</span></div><div class="mini-bar" style="margin-top:12px"><i style="width:${Math.round(di/16*100)}%"></i></div><h2>${esc(q.stem)}</h2><div>${q.options.map((o,i)=>`<button class="qopt" data-diag-opt="${i}">${esc(o)}</button>`).join('')}</div><div id="diagFeedback"></div></div>`;box.querySelectorAll('[data-diag-opt]').forEach(b=>b.onclick=()=>answerDiagnostic(+b.dataset.diagOpt))}
function answerDiagnostic(choice){const q=dq[di],ok=choice===q.answer;dres[q.domain_num].total++;if(ok){dcorrect++;dres[q.domain_num].correct++}document.querySelectorAll('[data-diag-opt]').forEach(b=>{b.disabled=true;const i=+b.dataset.diagOpt;if(i===q.answer)b.classList.add('correct');else if(i===choice&&!ok)b.classList.add('wrong')});document.querySelector('#diagFeedback').innerHTML=`<div class="feedback"><p><b>${ok?'Correct':'Incorrect.'}</b> ${esc(q.explanation)}</p><button class="btn primary" id="diagNext">${di===15?'See baseline':'Next'} →</button></div>`;document.querySelector('#diagNext').onclick=()=>{di++;renderDiagnosticQuestion()}}
function finishDiagnostic(){const result={date:new Date().toISOString(),correct:dcorrect,total:16,byDomain:dres};localStorage.setItem(DKEY,JSON.stringify(result));const sorted=domains.map(d=>({...d,score:dres[d.num].correct})).sort((a,b)=>a.score-b.score||b.weight-a.weight),weak=sorted[0];const box=document.querySelector('#quizBox');box.innerHTML=`<div class="quiz-card"><span class="kicker">DIAGNOSTIC COMPLETE</span><h2>${dcorrect}/16 baseline</h2><p class="muted">This is a routing signal, not an exam-readiness score. Two questions per domain are intentionally too small to support a pass prediction.</p><div class="diag-domain-grid">${domains.map(d=>`<div><b>D${d.num}</b><span>${dres[d.num].correct}/2</span><small>${esc(d.name)}</small></div>`).join('')}</div><div class="feedback"><b>Start with D${weak.num} · ${esc(weak.name)}</b><p>Review this domain, then interleave it with stronger domains instead of drilling it in isolation indefinitely.</p></div><div class="diag-actions"><button class="btn primary" id="diagWeak">Study weakest domain</button><button class="btn" id="diagPractice">Return to practice setup</button></div></div>`;document.querySelector('#diagWeak').onclick=()=>{navigate('learn');const f=document.querySelector('#domainFilter');if(f){f.value=String(weak.num);f.dispatchEvent(new Event('input',{bubbles:true}))}const r=document.querySelector('#reviewFilter');if(r){r.value='';r.dispatchEvent(new Event('input',{bubbles:true}))}};document.querySelector('#diagPractice').onclick=()=>{document.querySelector('#practiceSetup')?.classList.remove('hidden');box.classList.add('hidden')};renderDiagnosticStatus()}
renderDiagnosticStatus();
const practiceButton=document.createElement('button');practiceButton.className='btn';practiceButton.id='diagnosticPracticeBtn';practiceButton.textContent='Run 16-question diagnostic';document.querySelector('#practiceSetup')?.appendChild(practiceButton);practiceButton.onclick=startDiagnostic;
function addSubtopicSearch(){const input=document.querySelector('#globalSearch');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(q.length<2)return;setTimeout(()=>{const hits=[];for(const [oid,items] of Object.entries(coverage)){const matched=items.filter(x=>x.toLowerCase().includes(q));if(matched.length)hits.push({oid,matched:matched.slice(0,2),o:objectiveById[oid]})}for(const [dn,items] of Object.entries(ai)){const matched=items.filter(x=>x.toLowerCase().includes(q));if(matched.length){const o=objectives.find(x=>x.domain_num===+dn);if(o&&!hits.some(h=>h.oid===o.id))hits.push({oid:o.id,matched:matched.slice(0,2),o,ai:true})}}if(!hits.length)return;let box=document.querySelector('.global-results');if(!box){box=document.createElement('div');box.className='global-results';document.body.appendChild(box)}const existing=new Set([...box.querySelectorAll('[data-coverage-hit]')].map(x=>x.dataset.coverageHit));hits.slice(0,6).forEach(h=>{if(existing.has(h.oid))return;const b=document.createElement('button');b.className='global-hit';b.dataset.coverageHit=h.oid;b.innerHTML=`<b>${esc(h.oid)} · ${esc(h.o?.label||'Mapped objective')}</b><small>${h.ai?'AI coverage':'Subtopic'} · ${esc(h.matched.join(' · '))}</small>`;b.onclick=()=>{input.value='';box.remove();navigate('blueprint');const s=document.querySelector('#bpSearch');if(s){s.value=h.oid;s.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>document.querySelector('.coverage-details')?.setAttribute('open',''),20)}};box.appendChild(b)})},0)})}
addSubtopicSearch();
const aria={globalSearch:'Search CISSP objectives, cards, and subtopics',cardSearch:'Filter study cards',domainFilter:'Filter cards by domain',objectiveFilter:'Filter cards by objective',reviewFilter:'Filter cards by review state',bpSearch:'Search blueprint objectives',bpDomain:'Filter blueprint by domain',bpState:'Filter blueprint by mastery state',quizCount:'Practice question count',quizDomain:'Practice domain scope',themeBtn:'Toggle visual contrast'};Object.entries(aria).forEach(([id,label])=>document.getElementById(id)?.setAttribute('aria-label',label));
})();