#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'subjects/cissp/2024-outline/study-site'
QB=SITE/'question-bank'
DATE='2026-09-01'
PR=131
HEAD='d4441b8085fc70f3079e0362b2d96e5eb71e9db2'
PR_AUDIT=33523200238
MERGE='ac8b14d7850dadc36f13e78d358793161136570e'
MAIN_AUDIT=33523736219
PAGES=33523736180
FP={'version':'1.28.0','standard_questions':543,'manifest_released_records':488,'bellringers':1,'released_only':True}
OBJ=['7.6','3.7','4.2','1.3','5.1','5.3','7.1','1.5','7.2','5.4','7.10','1.8','5.2','6.3','6.5','3.8']
DOM={'1':3,'2':0,'3':2,'4':1,'5':4,'6':2,'7':4,'8':0}

def load(p): return json.loads(p.read_text())
def dump(p,x): p.write_text(json.dumps(x,separators=(',',':'))+'\n')

# Batch review
p=QB/'BATCH_030_REVIEW.json'; x=load(p); x['schema_version']=11; x['status']='SEMANTIC_REVIEWED_RELEASED_V1_28_VERIFIED'
rp=x['release_promotion']; rp.update({'status':'VERIFIED','release_pr_number':PR,'release_pr_final_head_sha':HEAD,'release_pr_exact_head_audit_workflow_run_id':PR_AUDIT,'release_merge_commit_sha':MERGE,'post_promotion_exact_main_audit_workflow_run_id':MAIN_AUDIT,'public_pages_workflow_run_id':PAGES,'verified_live_fingerprint':FP,'required_before_authoritative':[]})
x['authoritative_next_planner']={'basis_workflow_run_id':MAIN_AUDIT,'basis_scope':'verified-released-only-v1.28.0','size':16,'difficulty_target':{'E':12,'S':4},'primary_domain_distribution':DOM,'objective_targets':OBJ,'boundary':'Authoritative Batch 031 planning slate generated from the verified released-only v1.28.0 corpus.'}
x['notes']=[n for n in x.get('notes',[]) if 'not authoritative' not in n.lower()]
x['notes'].append('v1.28.0 release PR #131, exact-head audit 33523200238, merge ac8b14d7850dadc36f13e78d358793161136570e, exact-main audit 33523736219, and live Pages verification 33523736180 all passed; v1.28.0 is verified public production.')
x['notes'].append('Batch 031 is unblocked from authoritative released-only planner run 33523736219.')
dump(p,x)

# Bank status
p=QB/'STATUS.json'; x=load(p); x['schema_version']=53; x['updated']=DATE
x['latest_released_batch']['status']='RELEASED_V1_28_0_VERIFIED'; x['latest_released_batch']['release_pr_state']='VERIFIED'; x['latest_released_batch']['public_runtime']='PASS'
rv=x['release_verification']; rv.update({'status':'VERIFIED','release_pr_number':PR,'release_pr_final_head_sha':HEAD,'release_pr_audit_workflow_run_id':PR_AUDIT,'release_merge_sha':MERGE,'exact_main_audit_workflow_run_id':MAIN_AUDIT,'pages_workflow_run_id':PAGES,'verified_live_fingerprint':FP,'last_confirmed_public_release':'1.28.0','last_confirmed_public_standard_questions':543,'last_confirmed_public_manifest_released_records':488,'last_confirmed_public_bellringers':1,'last_confirmed_public_released_only':True})
x.pop('provisional_next_planned_batch',None)
x['next_planned_batch']={'batch_id':'031','basis_workflow_run_id':MAIN_AUDIT,'basis_scope':'verified-released-only-v1.28.0','size':16,'difficulty_target':{'E':12,'S':4},'primary_domain_distribution':DOM,'objective_targets':OBJ,'boundary':'Authoritative released-only Batch 031 slate after v1.28 public verification.'}
x['next_priority']=['Begin Batch 031 on an isolated candidate branch using exact released-only planner run 33523736219.','Preserve verified v1.28.0 production while Batch 031 is authored and validated.']
dump(p,x)

# Release status
p=SITE/'RELEASE_STATUS.json'; x=load(p); x['prepared_on']=DATE
x['scope']['explicit_enriched_subtopic_exposure_status']='RELEASED_306'
rc=x['release_change']; rc.update({'release_pr_state':'VERIFIED','public_pages_runtime':'PASS','release_pr_number':PR,'release_pr_final_head_sha':HEAD,'release_pr_exact_head_audit_workflow_run_id':PR_AUDIT,'release_merge_commit_sha':MERGE,'post_release_exact_main_audit_workflow_run_id':MAIN_AUDIT,'public_pages_workflow_run_id':PAGES,'verified_live_fingerprint':FP})
q=x['question_bank_expansion_target']; q['next_bias']='Begin Batch 031 from verified released-only v1.28.0 while preserving stable production.'; q['provisional_next_planner_basis_workflow_run_id']=MAIN_AUDIT; q['provisional_next_planner_scope']='verified-released-only-v1.28.0'; q['provisional_next_planner_objectives']=OBJ; q['provisional_next_planner_primary_domain_distribution']=DOM; q['provisional_next_planner_difficulty_distribution']={'E':12,'S':4}
d=x['deployment']; d.update({'repository_release':'1.28.0','repository_release_candidate':None,'last_confirmed_public_pages_release':'1.28.0','last_verified_release_runtime_evidence':{'pages_workflow_run_id':PAGES,'release_content_sha':MERGE,**FP},'latest_verified_site_health':{'main_sha':MERGE,'main_audit_workflow_run_id':MAIN_AUDIT,'pages_workflow_run_id':PAGES,'keyboard_shortcut_bundle':'v4',**FP},'last_verified_release_main_audit_workflow_run_id':MAIN_AUDIT,'release_pr_exact_head_audit_workflow_run_id':PR_AUDIT,'activation_status':'v1.28.0 is the verified public production release.','public_v1_28_verification_pending':False,'public_runtime_verified_for_v1_28':True})
x['precision_boundary']='The verified v1.28.0 release contains 543 standard scenario questions, 1 Bellringer, 544 released bank records, and 684 semantically reviewed learner-facing item IDs with zero known keyed-answer reversals and no known remaining material factual error within the documented review boundary. This does not guarantee passing the live adaptive CISSP exam.'
dump(p,x)

# Router
p=ROOT/'PROJECT_TRACKS.json'; x=load(p); x['updated']=DATE; c=x['tracks']['CISSP-ATLAS']['current_scope']; c.update({'next_action':'Begin Batch 031 on an isolated candidate branch while preserving verified v1.28.0 production.','next_batch':'031','next_batch_scope':'authoritative-verified-released-only-v1.28.0','next_batch_basis_workflow_run_id':MAIN_AUDIT,'next_batch_target_difficulty':{'E':12,'S':4},'next_batch_primary_domain_distribution':DOM,'next_batch_objective_targets':OBJ,'public_release_verified':True,'verified_release_merge_sha':MERGE,'verified_release_pr_number':PR,'verified_release_pr_audit_workflow_run_id':PR_AUDIT,'verified_release_main_audit_workflow_run_id':MAIN_AUDIT,'verified_release_pages_workflow_run_id':PAGES,'current_candidate_bookkeeping_branch':None,'current_candidate_bookkeeping_status':'COMPLETED','latest_completed_candidate_bookkeeping_pr_number':130,'latest_completed_candidate_bookkeeping_main_audit_workflow_run_id':33443994068,'latest_completed_candidate_bookkeeping_pages_workflow_run_id':33443994077})
dump(p,x)

# Docs
(SITE/'README.md').write_text('''# CISSP Atlas — Current Outline Study Workflow\n\nUnofficial, original study site mapped to the current public ISC2 CISSP exam outline (effective 2024-04-15).\n\n## Current verified release — v1.28.0\n\n- 8 domains; official weights total **100%**.\n- **62** numbered objectives and **344** paraphrased subtopic checks.\n- **306/344** checks with explicit enriched-subtopic practice exposure.\n- **33** AI-security coverage areas and **140** layered retrieval cards.\n- **543 released standard scenario questions + 1 Bellringer = 544 released bank records**.\n- Author-difficulty mix: **F41 / E381 / S121 / B1**.\n- **543/543** standard questions have four-option teaching rationales.\n- **684 learner-facing item IDs** in the combined semantic-audit ledger.\n- **20** primary/reference sources.\n\nBatch 030 was promoted through release PR #131. Exact-head audit **33523200238**, release merge `ac8b14d7850dadc36f13e78d358793161136570e`, exact-main audit **33523736219**, and Pages run **33523736180** all passed. The live runtime verified **v1.28.0 / 543 standard / 488 manifest-released / 1 Bellringer / released_only=true**.\n\n## Study workflow\nUse **diagnose → retrieve → apply → repair → re-test later**. Run the diagnostic once for routing, retrieve before revealing, use Exam + Stretch for standard practice, commit confidence before answering, review all four rationales, repair high-confidence misses first, and use Bellringers separately as non-exam-representative integrative drills.\n\n## Expansion state\nThe 800-record target leaves **F79 / E99 / S39 / B39**, or **256 records**. Batch 031 is now authoritative and unblocked from verified released-only planner run **33523736219**.\n\n## Accuracy boundary\nNo known material factual errors or incorrect keyed answers are recorded as remaining within the documented review boundary; **684 learner-facing item IDs** have explicit semantic status. This is not an infallibility or exam-pass guarantee.\n''')
(SITE/'TOMORROW_START.md').write_text('''# CISSP Atlas — Start Here\n\n1. Run the diagnostic once if you do not already have a baseline.\n2. Retrieve before revealing in the weakest domain.\n3. Use the misconception layer on misses or hesitation.\n4. Run 10–20 standard scenarios with **Exam + Stretch** selected.\n5. Commit confidence before choosing an answer; repair high-confidence misses first.\n6. Read all four option rationales.\n7. Use a Bellringer only after a normal study block; it is non-exam-representative.\n8. Re-test later rather than repeating immediately to recognition.\n\n## Current verified v1.28.0 scope\n- **543 released standard scenario questions + 1 Bellringer = 544 question-bank records**.\n- Difficulty mix **F41 / E381 / S121 / B1**.\n- **684 semantically reviewed learner-facing item IDs**.\n- **306/344** explicit enriched-subtopic practice exposure.\n- Live Pages fingerprint verified by run **33523736180** on release merge `ac8b14d7850dadc36f13e78d358793161136570e`.\n\n## Next authoring batch — 031\nAuthoritative released-only planner basis: **33523736219**. Target: **16 questions, E12/S4**, primary domains **D1=3 / D3=2 / D4=1 / D5=4 / D6=2 / D7=4**, objectives: `7.6, 3.7, 4.2, 1.3, 5.1, 5.3, 7.1, 1.5, 7.2, 5.4, 7.10, 1.8, 5.2, 6.3, 6.5, 3.8`. Author Batch 031 only in an isolated candidate branch; preserve verified v1.28.0 production.\n''')
(SITE/'PRECISION_AUDIT.md').write_text('''# CISSP Atlas Precision Audit — v1.28.0 Verified Release\n\n## Result\n**Published-scope mapping: PASS. Batch 030 semantic/originality validation, release promotion, exact-main validation, and live Pages verification: PASS within the documented audit boundary.**\n\n## Verified v1.28.0 scope\n- 8/8 domains; official weights total 100%.\n- 62/62 numbered public objectives.\n- 344 paraphrased subtopic checks; **306/344** explicitly exposed by enriched-subtopic practice metadata.\n- 33 AI-security coverage areas and 140 layered retrieval cards.\n- **543 released standard scenario questions**.\n- **1 released Bellringer**, explicitly non-exam-representative.\n- **544 total released question-bank records**.\n- 543/543 standard questions have four-option teaching rationales.\n- **684 learner-facing item IDs** in the combined semantic ledgers.\n- Author-difficulty distribution **F41 / E381 / S121 / B1**.\n\n## Batch 030 and release evidence\nCandidate PR #129 head `c194be4b23b23c2dbc500d18a3380dc456b989d1` passed audit **33426305066**. Candidate merge `c9d10cff98b296135767cc577622ab7fa97aaac0` passed exact-main audit **33442608747** and Pages isolation **33442608732**. Bookkeeping PR #130 head `97b12a18fb86e6ce14f6842e984bc95cf98f95f1` passed audit **33443706809**; merge `774e30f21ae8f2d0f80c2647f673b78ab98d44e9` passed exact-main **33443994068** and Pages isolation **33443994077**. Release PR #131 head `d4441b8085fc70f3079e0362b2d96e5eb71e9db2` passed exact-head audit **33523200238**; release merge `ac8b14d7850dadc36f13e78d358793161136570e` passed exact-main audit **33523736219** and Pages run **33523736180**, whose live fingerprint was **v1.28.0 / 543 standard / 488 manifest-released / 1 Bellringer / released_only=true**.\n\n## Accuracy boundary\nNo known material factual errors or incorrect keyed answers are recorded as remaining within this documented review boundary. **684 learner-facing item IDs** have explicit semantic status and the release records zero known keyed-answer reversals. This does not guarantee passing the live adaptive CISSP exam.\n''')
print('Prepared seven-file v1.28 evidence closure')
