#!/usr/bin/env python3
"""Second-pass learner-safe semantic rebuild for Arabic Top-1000.

Key rule: CALIMA raw `gloss` is never learner-facing. For ordinary lexical items,
we use compatible exact-spelling CALIMA analyses only to obtain clean `stemgloss`
values and validated roots. High-risk function words, homographs, and source-POS
exceptions are resolved explicitly by rank.

The existing 1,000 ranks/front inventory is preserved exactly.
"""
from __future__ import annotations

import csv
import re
from collections import Counter
from pathlib import Path

import build_arabic_top1000_precision as base
import finalize_arabic_top1000_precision as final
import rebuild_arabic_top1000_learner_safe as v1

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "audit" / "al_said_2023_msa1000.csv"
CANDIDATE = ROOT / "audit" / "arabic_top1000_precision_candidate.csv"
REPORT = ROOT / "audit" / "arabic_top1000_learner_safety_report.txt"


def clean(text: str) -> str:
    x = (text or "").replace("_", " ").strip()
    x = re.sub(r"\s+", " ", x)
    x = re.sub(r"\s*;\s*", "; ", x)
    return x.strip(" ;")


# Start with the reviewed function-word/high-risk meanings from the first safety pass.
MANUAL = dict(v1.OVERRIDE)
MANUAL[299] = "from/of what; from/of which (a contraction of مِن and ما)"

# Additional same-spelling/same-POS and common learner ambiguities. These are ordinary
# MSA meanings, intentionally concise and ordered with the most useful sense first.
MANUAL.update({
    30: "thing; something",
    35: "said; told",
    36: "can; is possible; may be possible",
    39: "knows; recognizes; defines/introduces (depending on vocalization)",
    46: "president; head; chief",
    47: "year; general; public (depending on use)",
    49: "day",
    50: "Mr.; gentleman; master",
    53: "some; part of",
    57: "matter; affair; order/command; ordered/commanded",
    58: "work; action; worked; functioned",
    59: "must; should; is necessary",
    60: "one; someone; anyone",
    61: "time",
    63: "accepted; received; approved",
    65: "self; same; soul; breath (depending on vocalization)",
    66: "does; performs",
    67: "believes; thinks",
    68: "can; is able to",
    70: "man; leg/foot (depending on vocalization)",
    75: "good; well",
    76: "says; tells",
    77: "sees; considers",
    79: "one; single",
    80: "new",
    82: "like; similar to; example; proverb",
    86: "big; large; great",
    87: "team; group",
    91: "council; board; assembly",
    94: "did; acted",
    95: "number; count",
    96: "goes",
    97: "other; another (feminine)",
    99: "person",
    100: "time; occasion; once",
    103: "life",
    107: "all; everyone; entire",
    108: "place; location",
    111: "seems; appears",
    113: "reason; cause; caused",
    114: "son",
    117: "was completed; took place; became complete",
    118: "state; country",
    119: "knows; teaches (depending on vocalization)",
    120: "world; scholar; scientist (depending on vocalization)",
    121: "past; previous",
    122: "father",
    124: "loves; likes",
    125: "means; signifies; concerns",
    126: "stands; gets up; carries out; performs",
    128: "works; operates",
    129: "good; goodness; better/best in some expressions",
    132: "company; firm",
    134: "told; informed; tell!/inform!",
    135: "road; way; path",
    137: "condition; state; situation",
    138: "ratio; percentage; proportion",
    139: "confirmed; affirmed",
    140: "then; afterwards",
    141: "date; history",
    144: "region; area; zone",
    145: "situation; status; position; placed/put",
    146: "shape; form; appearance; formed/shaped",
    147: "correct; true; valid",
    149: "government",
    150: "needs; requires",
    152: "name",
    153: "last; final; recent",
    154: "wonderful; excellent; great",
    155: "international",
    156: "people",
    157: "administration; management",
    158: "publication; publishing; spreading; published/spread",
    159: "second; a second (unit of time); feminine ordinal 'second'",
    162: "right; truth; entitlement",
    163: "city",
    164: "absence; nonexistence; lack",
    165: "happened; occurred",
    166: "union; federation",
    168: "night",
    169: "director; manager",
    170: "car; automobile",
    171: "added",
    173: "minister",
    174: "club",
    175: "killing; murder; killed",
    176: "role; turn; function",
    177: "began; started",
    178: "matter; affair; concern",
    179: "stood; got up; carried out",
    180: "match; game",
    181: "comes; arrives",
    183: "house; home; residence",
    184: "exists; is present; there is",
    185: "center; centre",
    186: "committee; commission",
    187: "politician; political figure",
    189: "antiquity/oldness; presented/offered (depending on vocalization)",
    190: "year; Sunnah/tradition (depending on vocalization)",
    191: "is completed; takes place; is carried out",
    192: "secured; ensured; made safe",
    193: "police",
    195: "Arabic; Arab (feminine adjective/noun use)",
    196: "speaks; talks",
    197: "next; coming; forthcoming",
    199: "happens; occurs; updates/tells (depending on vocalization)",
    200: "ball; sphere",
    201: "returns; goes back",
    202: "saw",
    203: "truth; fact; reality",
    205: "happy; pleased",
    206: "thinks; supposes",
    207: "period; interval",
    208: "men",
    209: "women",
    210: "works; businesses; actions",
    211: "problem; issue",
    212: "state; condition; case",
    213: "party; political party; group",
    214: "million",
    215: "happened/occurred; obtained/got; collected (depending on form)",
    216: "feels; senses",
    217: "request; demand; order; requested/asked",
    218: "investigation; achievement/realization (context-dependent)",
    220: "house; home",
    221: "concern; worry (هَمّ); note: unvocalized spelling can also represent the pronoun 'they'",
    222: "ministry",
    223: "decision; resolution",
    225: "hour; watch; clock",
    226: "came; arrived",
    227: "earth; land; ground",
    228: "tries; attempts",
    229: "eye; spring; individual/notable; appointed/designated (depending on vocalization)",
    232: "days",
    233: "became; came to be",
    234: "calculated; counted; considered/thought (depending on vocalization)",
    237: "way; method; manner",
    239: "friend",
    240: "presented; offered; displayed",
    242: "goal; target; objective",
    243: "counts; is considered; prepares (depending on vocalization)",
    244: "existence; presence",
    245: "end; ending; conclusion",
    246: "group; collection; set",
    247: "countries; states",
    250: "authored; composed; compiled",
    251: "deputy; vice-president; representative",
    252: "week",
    253: "law",
    254: "level; standard",
    255: "sector",
    256: "system; regime",
    257: "still was/is; continued to be (ما زال)",
    258: "help; assistance",
    259: "gets; obtains; happens; collects/achieves (depending on form)",
    260: "month",
    261: "technician; technical/specialized (depending on use)",
    262: "page",
    263: "general; public; in general",
    265: "when; while; time",
    266: "little; few; small amount",
    268: "children",
    271: "team; national/select team; elected/selected (context-dependent)",
    272: "sheikh; elder; senior man",
    273: "project; plan",
    274: "things",
    275: "only; lone; unique; lonely",
    277: "people; nation; populace",
    278: "takes; receives",
    279: "finds",
    280: "stopped; halted; stop!",
    282: "championship; tournament",
    283: "body; authority; commission; organization",
    284: "process; operation",
    285: "long; tall",
    286: "rather; but; instead",
    287: "confirmation; emphasis",
    289: "matters; affairs; things",
    290: "victory; winning",
    291: "less; least; fewer",
    293: "youth; young people",
    294: "real; genuine; true",
    295: "complete; full; entire",
    296: "player",
    297: "waited; wait!",
    298: "companies",
    300: "previous; former; preceding; competed/raced (depending on vocalization)",
    301: "room; chamber",
    302: "money; wealth; leaned/inclined (depending on vocalization)",
    303: "makes; renders; causes",
    304: "participation; sharing",
    305: "dear; precious; respected",
    306: "god; deity",
    307: "vision; seeing; view",
    308: "face; direction; aspect; directed",
    309: "against; opposite",
    310: "special; private; particular",
    311: "remains; stays",
    312: "meeting; encounter",
    313: "return; comeback",
    315: "forces; troops",
    316: "transfer; transport; transmission; transferred/moved",
    317: "arrives; reaches",
    318: "addition; adding",
    319: "head; top; headed/presided",
    320: "goodness; beauty; became good (depending on vocalization)",
    321: "idea; thought",
    322: "taking; took",
    323: "indicated; pointed out; referred to",
    324: "girl; young woman",
    325: "movement; motion",
    327: "strength; force; power",
    328: "program; programme",
    329: "occurrence; obtaining; acquisition",
    330: "gold; went (depending on vocalization)",
    331: "begins; starts",
    332: "self/same; possessing (in constructions such as ذات)",
    333: "speaking; conversation; spoke/talked",
    334: "arrived; reached; connected",
    335: "knowledge; science; flag; taught/instructed (depending on vocalization)",
    337: "announced; declared",
    340: "opportunity; chance",
    341: "research; search; searched/researched",
    342: "goes out; exits; leaves",
    343: "judgment; ruling; government; ruled/judged",
    344: "child",
    345: "case; issue; cause",
    348: "support; backing; supported",
    349: "need; necessity",
    350: "come!",
    351: "mere; simply; abstract/bare",
    352: "ministers",
    354: "held; concluded; contracted; tied",
    355: "minute; precise/fine (context-dependent)",
    356: "printing; nature/character; printed",
    357: "picture; image; form",
    358: "progress; advance; advanced/progressed",
    359: "university",
    360: "crossed; passed through; expressed (context-dependent)",
    362: "found",
    363: "coming; next",
    364: "runs; proceeds; takes place",
    365: "prices",
    366: "war",
    367: "point; dot",
    368: "elections",
    369: "market",
    370: "building; construction",
    371: "learning; learned",
    372: "becomes",
    374: "half",
    375: "going; departure",
    376: "opinion; view",
    377: "thinks; considers",
    378: "national; patriotic",
    379: "meeting; assembly",
    380: "value; worth",
    381: "lands; countries",
    382: "beginning; start",
    384: "school; female teacher (depending on vocalization)",
    385: "speed; rapidity",
    387: "members",
    388: "age; lifetime",
    390: "stage; phase",
    391: "far; distant",
    392: "tells; informs",
    393: "clarified; explained; made clear",
    394: "love",
    395: "financial; fiscal",
    396: "relationship; relation",
    397: "hand",
    398: "looks; considers; examines",
    399: "future",
    400: "wife",
    401: "army",
    402: "duration; period",
    403: "family; people; inhabitants; أهل",
    404: "lives; resides",
    405: "saying; speech; statement",
    406: "number; figure",
    407: "book",
    408: "economic",
    409: "office; desk",
    410: "view; consideration; looked/considered",
    411: "increase; addition",
    412: "solution; solving; solved",
    413: "country; town; land",
    414: "family",
    415: "return; repetition; redoing",
    416: "limit; boundary; extent",
    418: "conference",
    419: "door; gate",
    420: "understands",
    421: "subject; topic",
    422: "reality; actual situation; occurring/present",
    424: "court; tribunal",
    425: "word",
    426: "wishes; hopes",
    427: "device; apparatus",
    428: "hearing; heard/listened",
    430: "leaving; abandonment; left",
    431: "Arab; Arabic",
    432: "leadership; driving",
    433: "merit; virtue; favor; preferred",
    434: "ended; finished",
    435: "student; seeker; demanded/claimed",
    436: "rejection; refusal; refused",
    437: "companion; owner; accompanied",
    438: "reached; amounted to; informed/notified (depending on form)",
    439: "arrival; access",
    440: "entry; entrance",
    441: "global; international (feminine)",
    444: "presidency; chairmanship",
    445: "society; community",
    446: "turned; overturned; reversed",
    447: "waits",
    448: "cooperation; collaborated/cooperated",
    449: "servant; slave; worshipped",
    450: "part; portion",
    451: "season",
    452: "voice; sound; vote",
    453: "would like; wants",
    454: "standing; undertaking; carrying out",
    456: "mention; remembrance",
    461: "moment",
    462: "dialogue; conversation",
    463: "rise; increase; elevation",
    464: "fire",
    465: "tried; attempted; try!",
    466: "religion; debt (depending on vocalization)",
    468: "searches; researches; looks for",
    469: "gives",
    470: "goal; purpose; utmost extent",
    471: "presentation; submission; provision",
    472: "payment; pushing; paid/pushed",
    473: "called; invited; prayed",
    474: "position; stance; situation",
    476: "implementation; execution",
    477: "means; intends; aims",
    478: "mentions; remembers",
    479: "peace; safety; Salim/Salam as proper-name reading in context",
    480: "friends",
    481: "unit; unity",
    482: "old; ancient",
    483: "crisis",
    484: "report",
    485: "information",
    486: "possibility; potential",
    487: "result; outcome",
    488: "site; location; position",
    490: "field; domain; area",
    491: "middle; center; among",
    493: "death",
    494: "poetry; hair (depending on vocalization)",
    495: "defense; defence",
    496: "degree; grade; level",
    497: "contact; communication",
    498: "ten; one tenth (depending on vocalization)",
    499: "question",
    501: "cup; trophy",
    502: "made; rendered; caused",
    504: "plan",
    506: "control; ضبط; ضبط = controlled/adjusted",
    508: "national (feminine); nationality/national character in noun use",
    509: "knowledge; knowing",
    510: "statement; declaration; data/itemization (context-dependent)",
    511: "decided; determined",
    512: "holiday; feast; festival",
    513: "spouse; pair; married off",
    514: "education; teaching",
    515: "error; mistake",
    516: "development; improvement",
    517: "several; a number of; waiting period; equipment/gear (depending on vocalization)",
    518: "member; organ",
    519: "opening; conquest; opened",
    520: "died",
    522: "great; magnificent; enormous",
    523: "discovery; exposure; revealed/uncovered",
    524: "energy; capacity",
    525: "is considered; regards/considers",
    526: "returned; came back",
    527: "succeeded/followed; came after",
    528: "east",
    529: "internal; domestic; interior (feminine)",
    530: "within; among; included/guaranteed (depending on vocalization)",
    531: "agreement; accord",
    532: "water; waters",
    533: "hospital",
    534: "human being; person",
    535: "gave",
    537: "organization; organisation",
    538: "books; wrote",
    539: "attendance; presence",
    540: "raising; lifting; raised",
    541: "play; playing; played",
    542: "exit; departure",
    543: "side; direction; entity/party",
    544: "message; letter",
    545: "use; usage",
    546: "authority; power; government; salad (different vocalization)",
    547: "necessity; need",
    548: "enters",
    549: "possible; feasible",
    551: "coach; trainer",
    552: "leaves; abandons",
    553: "understood",
    554: "basic; fundamental",
    555: "people; persons",
    556: "south",
    557: "hears; listens",
    558: "prison; imprisonment",
    559: "determination; specification; identification",
    560: "homeland; nation; country",
    561: "shade; shadow; remained/continued",
    562: "boy; son; gave birth",
    563: "announcement; advertisement",
    564: "street",
    565: "tour; round; trip",
    566: "ends; finishes",
    567: "change; alteration",
    569: "fate; destiny; amount; ability; estimated",
    570: "carries; bears; loads/imposes (depending on form)",
    571: "plays",
    572: "puts; places",
    573: "helps; assists",
    574: "dies",
    575: "line; route",
    576: "telephone; phone; telephoned",
    577: "relations; relationships",
    578: "knew; recognized",
    579: "brother",
    580: "confrontation; facing",
    581: "bank",
    582: "freedom; liberty",
    583: "service",
    584: "borders; limits",
    585: "extent; range",
    586: "night",
    587: "owns; possesses",
    588: "media; information/publicity",
    590: "visit",
    591: "woman",
    592: "health; correctness",
    593: "occasion; event; suitable/appropriate (feminine)",
    594: "section; department; oath; divided (depending on vocalization)",
    595: "list; menu",
    596: "problems",
    597: "strange; foreign; odd",
    598: "rights",
    599: "association; society; organization",
    600: "sale; selling",
    602: "request; hope; please (as a polite formula)",
    603: "brought; prepared/presented (depending on form)",
    605: "weapon; arms",
    606: "asks for; requests; demands",
    607: "regions; areas",
    608: "personality; character",
    609: "sporting; athletic",
    610: "remembers",
    611: "performance; execution",
    612: "institution; organization",
    613: "price; priced",
    614: "decline; retreat; retreated/declined",
    615: "importance",
    616: "clear; obvious",
    617: "times; occasions (commonly in أحيانًا = sometimes)",
    618: "crime",
    619: "confirmed; certain; confirming/emphasizing (context-dependent)",
    620: "came; arrived",
    621: "current; present",
    622: "pays; pushes",
    623: "next; following",
    624: "residence; establishment; holding",
    625: "production; output",
    627: "launched; released; fired; set free",
    628: "you (masculine plural)",
    629: "protection",
    630: "pictures; images; photographed",
    631: "speaks; talks",
    635: "record; register; recorded/registered",
    636: "alone; by himself/itself",
    637: "women",
    638: "story",
    639: "take!",
    640: "doctor; physician",
    641: "directly; direct; immediate",
    642: "republic",
    643: "harm; hardship; بأس; often in لا بأس = no problem/not bad",
    644: "months; more famous/most famous (depending on vocalization)",
    645: "angel (مَلَك); unvocalized spelling can also represent king/possession in other contexts",
    646: "judiciary; القضاء; القضاء = القضاء/ القضاء as context determines: judgment, القضاء district, القضاء القضاء",
    647: "study",
    649: "politics; policy",
    650: "was difficult; became hard",
    651: "income; revenue; entered",
    652: "kills; is killed (voice depends on vocalization/context)",
    653: "global; worldwide; international",
    654: "nations; peoples",
    655: "hope",
    656: "consideration; regard",
    657: "final; definitive",
    658: "one hundred; hundred",
    659: "organization; regulation; organizing",
    661: "course; cycle; round; session",
    662: "game; toy",
    663: "reply; response; return; replied/returned",
    664: "development; growth",
    665: "interest; attention; concern",
    666: "framework; frame",
    667: "wish; desire",
    668: "official; person responsible; responsible person",
    669: "leader; commander; driver",
    670: "sources",
    671: "happened; occurred; fell; was located",
    672: "matches; games",
    674: "contacted; connected; call!/contact!",
    675: "attempt; try",
    676: "being; existence; formed/created",
    677: "wanted; desired; intended",
    678: "injury; casualty",
    679: "ten; companionship/association (depending on vocalization)",
    681: "represents; constitutes; acts/portrays",
    682: "choice; selection",
    683: "witnessed; observed",
    684: "procedure; measure; action; carrying out",
    685: "newspaper; journal",
    686: "continuation; persistence",
    687: "north; left side (depending on vocalization)",
    688: "thought; thinking; thought/considered",
    689: "purchase; buying",
    690: "prosecution; representation; deputyship (context-dependent)",
    691: "appointment; date; scheduled time",
    692: "water",
    693: "relates to; concerns; is connected with",
    694: "social",
    696: "shares; stocks; contributed/participated",
    697: "devices; equipment",
    698: "beginning; start",
    699: "session; meeting",
    701: "official; formal",
    702: "effect; influence; impact",
    703: "title; nickname; titled/nicknamed",
    704: "teams/groups; differences",
    705: "attack; assault",
    706: "daughter",
    707: "continues; persists",
    708: "nice; kind; gentle; pleasant",
    709: "cares about; is interested in",
    711: "sons; children",
    712: "west",
    713: "insurance; securing; guarantee",
    714: "presents; displays; offers; exposes (depending on form)",
    715: "Arabs",
    716: "valid; suitable; righteous; good",
    717: "clothes; clothing",
    718: "movement; activity; moved",
    719: "substitute; instead of; changed/replaced",
    720: "airplane; aircraft",
    721: "group; community",
    722: "source",
    723: "most; majority of",
    725: "pieces; parts; cut",
    726: "approval; agreement; agreeing/suitable (feminine adjective use)",
    727: "news; reports",
    728: "governorate/province; conservative/preserving (feminine adjective use)",
    729: "danger; risk",
    730: "box; fund",
    731: "island",
    732: "believes; confirms; tells the truth (depending on vocalization)",
    733: "forces; powers; strengths",
    734: "blood",
    735: "prize; award",
    736: "governmental; government",
    737: "appears; shows; demonstrates (depending on form)",
    739: "incident; accident; event; spoke/conversed with (verb reading)",
    740: "points; dots",
    741: "waiting; expectation",
    742: "rule; base; foundation",
    743: "luck; fortune",
    744: "important",
    745: "dealing; interaction; dealt/interacted",
    746: "culture",
    747: "procedures; measures; actions",
    748: "issues; cases; causes",
    749: "food",
    751: "allows; permits",
    752: "goals; objectives",
    753: "asks; questions",
    754: "stadium; playing field",
    755: "minutes",
    757: "military",
    758: "exhibition; display; fair",
    759: "remaining; survival; staying",
    760: "communications; contacts",
    761: "ceremony; party; event",
    762: "affairs; matters",
    763: "size; volume",
    764: "wants; desires; wishes",
    765: "time; era",
    766: "safety; well-being",
    767: "neighborhood; district; living/alive (depending on vocalization)",
    769: "roads; ways; knocked",
    771: "provision; saving; availability",
    772: "owners; companions; people of",
    773: "investment",
    774: "responsibility",
    775: "all; entire; all of",
    776: "led to; performed; fulfilled",
    777: "Muslims",
    778: "race; competition",
    779: "marriage; wedding",
    780: "confirms; affirms",
    781: "trust; confidence",
    782: "experience; experiment",
    783: "spirit; soul",
    784: "considered; regarded",
    787: "establishment; creation; construction; composition",
    788: "worries; becomes anxious; causes worry (depending on vocalization)",
    789: "contacts; connects; calls",
    790: "journey; trip",
    791: "Miss; young lady",
    792: "continued; continue!",
    794: "learns; studies",
    795: "weather; atmosphere; air",
    796: "weapons; arms",
    797: "was issued; was published; came from",
    799: "industry; manufacture",
    800: "liberation; editing",
    801: "students",
    803: "young man; boy",
    804: "strong; powerful",
    805: "care; sponsorship; protection",
    806: "training; practice",
    807: "delegation; arrived/came as a delegate",
    808: "direction; trend; orientation",
    809: "handling; تناول = eating/taking; ate/took/dealt with",
    810: "endowment (waqf); stopped; stood",
    811: "sent",
    812: "includes; comprises",
    813: "passing; traffic; passage",
    814: "young man; youth; mixed/adulterated (rare verb reading)",
    815: "went out; left; exited",
    816: "expects; anticipates",
    817: "presents; offers; submits",
    818: "growth; development",
    819: "revolution; uprising",
    820: "money; funds; wealth",
    821: "is enough; suffices",
    822: "capital city",
    823: "matters; concerns; is important to",
    825: "campaign; group of carriers/bearers (depending on vocalization)",
    826: "economy; economics",
    827: "language",
    828: "address; title; headline",
    829: "college/faculty; kidney; entirety/totality (depending on vocalization/context)",
    830: "paternal uncle; became widespread/general",
    831: "summit; peak",
    832: "follower/subordinate; followed; continued",
    833: "circle; department; district",
    834: "events",
    835: "sea",
    836: "suitable; appropriate",
    837: "village",
    838: "reaches; amounts to; informs/notifies (depending on form)",
    839: "ending; completion",
    840: "meaning; sense",
    841: "suffers",
    843: "materials; substances",
    844: "issue; matter; question",
    845: "anxiety; concern; worried/anxious",
    846: "invitation; call; الدعوة = advocacy/mission in some contexts",
    847: "inhabitants; population",
    848: "reasons; causes",
    849: "stops; depends on",
    850: "description; described",
    851: "town; small town",
    853: "papers; leaves; documents",
    855: "means; methods; media/devices",
    856: "festival",
    857: "trade; commerce",
    858: "hitting; strike; ضرب = hit/struck",
    859: "resistance; opposition",
    860: "uses; is used (voice depends on vocalization)",
    861: "interest; benefit; public service/agency (context-dependent)",
    862: "markets",
    863: "calls; invites; advocates",
    864: "control; domination",
    866: "basis; foundation",
    867: "look; view; glance",
    869: "material; substance; article",
    870: "type; kind; sex/gender",
    871: "selves; souls",
    872: "registration; recording",
    874: "achieved; realized; investigated/verified (depending on form)",
    875: "speech; address; discourse",
    876: "succeeded",
    877: "formation; composition; shaping",
    879: "hero; champion",
    880: "stands; stops",
    881: "faces; confronts",
    882: "approached; came near",
    883: "ruler; governor; judged/prosecuted",
    885: "thought; belief; assumption; thought/believed",
    886: "bitter (مُرّ); passed/went by (مَرَّ)",
    888: "preparation; setup",
    889: "hotel",
    890: "leads to; performs; results in",
    891: "attends; is present; prepares/brings (depending on form)",
    892: "transformation; change; changed/transformed",
    893: "fast; quick",
    894: "witnesses; observes",
    895: "secret",
    896: "circumstances; conditions",
    897: "won",
    899: "effect; trace; impact; affected/influenced",
    900: "light",
    901: "workers",
    902: "ability; capacity",
    903: "knows; is aware",
    904: "prevention; prohibition; prevented",
    905: "main; principal; primary",
    906: "birth; birthday",
    908: "competition; contest",
    909: "evidence; guide; proof",
    910: "travel; journey",
    911: "load; burden; حمل = carrying",
    912: "photography; filming",
    913: "aviation; flying",
    914: "station; stop",
    915: "individuals; persons",
    916: "badness; سوء = poor/bad state",
    917: "respect",
    918: "account; calculation",
    919: "application; implementation",
    920: "deserves; is worth; is entitled to",
    921: "environment",
    922: "headquarters; seat; location",
    923: "failure; failed",
    925: "senior people; elders; major/important people",
    926: "gets to know; becomes acquainted with; recognizes",
    928: "competition; rivalry",
    929: "seeks; strives",
    930: "hates; dislikes",
    931: "citizen",
    932: "boys; sons; children",
    933: "natural; normal",
    934: "step",
    935: "projects",
    936: "watched; saw; witnessed",
    937: "origin; root; basis",
    938: "schools",
    939: "price; value",
    940: "finding; creation/bringing into existence (إيجاد)",
    941: "deal; transaction",
    942: "launches; releases; fires; calls/names (depending on form)",
    943: "approaches/comes forward; accepts (depending on vocalization)",
    944: "collects; gathers",
    945: "severe; strong; intense",
    946: "questions",
    947: "age; tooth (depending on vocalization)",
    948: "thinking; thought",
    949: "names",
    950: "advisor; consultant",
    951: "leads; drives",
    952: "manages to; is able to",
    953: "efforts",
    954: "precedence; lead; preceded",
    955: "pressure; pressing; pressed",
    956: "signal; sign; indication",
    957: "follow-up; monitoring",
    958: "hit; affected; injured",
    959: "sister",
    960: "caution; warning; cautious",
    961: "gulf",
    962: "family; household",
    963: "reform; repair; correction",
    964: "guard; goalkeeper",
    966: "illness; disease; fell ill",
    967: "separated; dismissed; فصل = divided/separated",
    968: "change; alteration; changed",
    970: "victory; support; helped/supported",
    972: "worse; worst",
    973: "dream; forbearance/patience; dreamed",
    974: "clubs",
    975: "audience; public; fans",
    976: "hunting; fishing",
    977: "habit; custom; usually (in adverbial use)",
    978: "drugs; narcotics",
    979: "agreed; came to an agreement",
    980: "theater; theatre; stage",
    981: "ability; mastery; managed/was able",
    982: "should; ought to; it is appropriate/necessary",
    983: "games",
    984: "laws",
    985: "increases; adds",
    986: "sport; exercise",
    987: "amount; sum of money",
    988: "writing",
    989: "fear",
    990: "sun",
    991: "helped; assisted",
    992: "decreases; becomes less",
    993: "taking; adoption; making (as in اتخاذ قرار = making a decision)",
    994: "party; celebration",
    995: "feeling; sensation",
    996: "prefers; is superior/better (depending on vocalization)",
    997: "was able to; could",
    998: "nature; character",
    999: "interview; meeting; مقابلة = مقابلة/confrontation depending on context",
    1000: "moved away; kept away; move away!",
})

POS_OVERRIDE = {
    22: "negative copular verb",
    23: "conjunction / particle",
    32: "discourse adverb / response expression",
    45: "response particle",
    83: "adverb",
    89: "adverb",
    112: "thanks expression / verbal noun",
    127: "greeting expression",
    148: "adjective / apology expression",
    187: "noun",
    221: "noun",
    267: "adverb / preposition",
    269: "fixed modal expression",
    292: "particle",
    299: "relative/prepositional contraction",
    326: "adverbial demonstrative expression",
    347: "exclamative particle",
    353: "demonstrative pronoun",
    383: "possessive noun / relational word",
    489: "noun",
    492: "adverb",
    503: "adverb",
    626: "adverb",
    641: "adverb / adjective",
    700: "negative-continuative verb expression",
    710: "adverb / conjunction",
    724: "greeting expression",
    738: "adverb / preposition",
    750: "adverb / conjunction / adjective",
    756: "adverb",
    768: "adverb / preposition",
    786: "adverb",
    802: "adverb",
    842: "adjective",
    865: "adverb",
    868: "adverb",
    887: "noun",
    927: "adverbial expression",
    965: "noun / adverbial expression",
    969: "adjective",
    971: "adjective / participle",
    977: "noun / adverbial use",
}

ANALYZER_POS_LABEL = {
    "noun": "noun", "noun_num": "numeral noun", "noun_quant": "quantifier",
    "adj": "adjective", "adj_comp": "comparative adjective", "adj_num": "numeral adjective",
    "verb": "verb", "prep": "preposition", "adv": "adverb", "adv_interrog": "interrogative adverb",
    "adv_rel": "relative adverb", "conj": "conjunction", "conj_sub": "subordinating conjunction",
    "pron": "pronoun", "pron_dem": "demonstrative pronoun", "pron_rel": "relative pronoun",
    "pron_interrog": "interrogative pronoun", "part": "particle", "part_neg": "negative particle",
    "part_verb": "verbal particle", "part_interrog": "interrogative particle", "part_fut": "future particle",
    "part_voc": "vocative particle", "part_focus": "focus particle", "part_restrict": "restrictive particle",
    "interj": "interjection",
}

FORBIDDEN = ["+", "[", "]", "<", ">", "_", "[def.", "[indef.", "<verb>"]


def automatic_senses(front: str, codes: list[str], analyzer, bw2ar) -> list[dict]:
    analyses = [a for a in analyzer.analyze(front) if base.exact_lexical_match(front, a)]
    out = []
    seen = set()
    for code in codes:
        matches = [a for a in analyses if base.compatible(code, str(a.get("pos", "")))]
        matches.sort(key=base.score, reverse=True)
        picked = None
        for a in matches:
            stemgloss = clean(str(a.get("stemgloss", "")))
            if not stemgloss or any(x in stemgloss for x in FORBIDDEN):
                continue
            pos = str(a.get("pos", ""))
            root = base.root_to_arabic(str(a.get("root", "")), pos, bw2ar)
            key = (code, pos, stemgloss.casefold(), root)
            if key in seen:
                continue
            seen.add(key)
            picked = {"meaning": stemgloss, "pos": ANALYZER_POS_LABEL.get(pos, pos), "root": root}
            break
        if picked:
            out.append(picked)
    return out


def main() -> None:
    from camel_tools.morphology.analyzer import Analyzer
    from camel_tools.morphology.database import MorphologyDB
    from camel_tools.utils.charmap import CharMapper

    analyzer = Analyzer(MorphologyDB.builtin_db("calima-msa-r13", flags="a"), backoff="NONE", cache_size=10000)
    bw2ar = CharMapper.builtin_mapper("bw2ar")

    with SOURCE.open(encoding="utf-8", newline="") as f:
        src = list(csv.DictReader(f))

    rows = []
    problems = []
    manual_count = 0
    automatic_count = 0
    fronts = []

    for r in src:
        rank = int(r["rank"])
        front = final.FINAL_REPAIRS.get(rank, base.undiac(r["front"]).strip())
        codes = base.paper_codes(r["pos_codes"])
        fronts.append(front)

        if rank in MANUAL:
            meaning = clean(MANUAL[rank])
            pos = POS_OVERRIDE.get(rank, " / ".join(base.PAPER_POS_LABELS.get(c, c) for c in codes))
            root = ""
            manual_count += 1
        else:
            senses = automatic_senses(front, codes, analyzer, bw2ar)
            if not senses:
                problems.append(f"rank {rank} {front}: no safe exact-spelling stemgloss analysis")
                meaning = ""
                pos = " / ".join(base.PAPER_POS_LABELS.get(c, c) for c in codes)
                root = ""
            else:
                meaning = "; ".join(dict.fromkeys(s["meaning"] for s in senses))
                pos = " / ".join(dict.fromkeys(s["pos"] for s in senses))
                roots = list(dict.fromkeys(s["root"] for s in senses if s["root"]))
                root = roots[0] if len(roots) == 1 else ""
                automatic_count += 1

        if not meaning:
            problems.append(f"rank {rank} {front}: empty meaning")
        if any(x in meaning for x in FORBIDDEN):
            problems.append(f"rank {rank} {front}: machine morphology markup in meaning {meaning!r}")
        for required in v1.CRITICAL.get(rank, []):
            if required.casefold() not in meaning.casefold():
                problems.append(f"rank {rank} {front}: critical learner meaning missing {required!r}: {meaning!r}")

        lines = [f"Rank: {rank}", "", f"Meaning: {meaning}", "", f"Part of speech: {pos}"]
        if root:
            lines += ["", f"Root: {root}"]
        lines += [
            "", "Sources:",
            f"- Al-Said (2023), Table 4 — existing rank {rank}; rank/order preserved",
            "- CALIMA-MSA r13 via CAMeL Tools — morphology/root validation; stem-level semantics only",
            "- Learner-safety review — high-risk function words/homographs resolved explicitly; raw analyzer gloss hidden",
        ]
        rows.append({"Front": front, "Back": "\n".join(lines)})

    counts = Counter(fronts)
    dupes = {w: [i for i, f in enumerate(fronts, 1) if f == w] for w, n in counts.items() if n > 1}
    if dupes != {"ما": [10, 347]}:
        problems.append(f"unexpected duplicate fronts {dupes!r}")
    if len(rows) != 1000:
        problems.append(f"row count {len(rows)} != 1000")

    CANDIDATE.parent.mkdir(parents=True, exist_ok=True)
    with CANDIDATE.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["Front", "Back"], lineterminator="\n")
        w.writeheader(); w.writerows(rows)

    report = [
        f"rows={len(rows)}",
        f"manual_reviewed_meanings={manual_count}",
        f"safe_stemgloss_meanings={automatic_count}",
        f"problems={len(problems)}",
        "candidate_fallbacks_to_raw_gloss=0",
        "raw_CALIMA_gloss_exposed=0",
        "ranking_policy=existing 1000 ranks preserved exactly",
        *problems,
    ]
    REPORT.write_text("\n".join(report) + "\n", encoding="utf-8")
    print(REPORT.read_text(encoding="utf-8"))
    if problems:
        raise SystemExit("Second-pass learner-safe rebuild failed")


if __name__ == "__main__":
    main()
