#!/usr/bin/env python3
"""Explicitly reviewed semantic overrides for French/Urdu core candidates.

This layer is applied only to rows isolated by the independent multi-source audit
as ambiguous, archaic, overly morphological, or susceptible to a wrong homograph.
The mappings below are learner-facing modern meanings; rank/frequency is unchanged.
"""
import refine_french_urdu_candidate_meanings as base

base.FRENCH_SAFE.update({
    "cette": "this; that (feminine singular)",
    "des": "of the; from the; some (plural partitive/indefinite article)",
    "ses": "his; her; its (before a plural noun)",
    "mieux": "better",
    "tes": "your (informal singular possessor; before a plural noun)",
    "fait": "fact; deed; event; done; made",
    "cet": "this; that (masculine singular before a vowel or mute h)",
    "désoler": "to sadden; distress; upset",
    "désolé": "sorry; saddened; desolate",
    "eh": "eh; hey; huh (interjection)",
    "quelle": "which; what (feminine singular)",
    "hé": "hey!; ho! (interjection)",
    "pendant": "during; for (a duration); while",
    "hein": "huh?; right?; isn't it?",
    "rappeler": "to remind; recall; call back",
    "ni": "neither; nor",
    "aucune": "no; none; not any (feminine)",
    "euh": "um; uh (hesitation)",
    "super": "great; super; fantastic",
    "boulot": "job; work (informal)",
    "celui": "the one; that one (masculine singular)",
    "tour": "turn; round; tour; tower",
    "l'un": "one; one of them",
    "tiens": "here; look; hey; hold! (form of tenir)",
    "dès": "from; as early as; as soon as",
    "toute": "all; every; whole (feminine singular)",
    "sinon": "otherwise; if not; except",
    "pote": "friend; buddy; mate (informal)",
    "rejoindre": "to join; rejoin; reach; catch up with",
    "sympa": "nice; friendly; pleasant (informal)",
    "ficher": "to file; put/stick; not care (se ficher de, informal)",
    "virer": "to fire/dismiss; turn; remove; transfer (informal senses vary)",
    "censé": "supposed to; meant to",
    "tueur": "killer; murderer",
    "arrière": "rear; back; behind",
    "gosse": "kid; child (informal)",
    "laquelle": "which one; which (feminine singular)",
    "doucement": "gently; softly; slowly; quietly",
    "travers": "fault; defect; crosswise; through/across (in à travers)",
    "moi-même": "myself",
    "horrible": "horrible; awful",
    "excellent": "excellent; great",
    "bosser": "to work (informal); emboss/dent",
    "connerie": "bullshit; stupidity; stupid thing (vulgar)",
    "filer": "to spin/thread; slip away; give/pass; tail/follow",
    "là-dedans": "in there; in that",
    "forcer": "to force; compel; make",
    "hum": "hmm; um",
    "lequel": "which one; which (masculine singular)",
    "nulle": "no; none (feminine); lousy/terrible (informal adjective)",
    "soit": "either; be (subjunctive of être); namely/that is; okay/agreed",
})

base.URDU_SAFE.update({
    "تھا": "was (masculine singular)",
    "تھے": "were (masculine plural/honorific)",
    "تھی": "was (feminine singular)",
    "یا": "or; O!/oh! (vocative in some contexts)",
    "دی": "gave (feminine singular form of دینا)",
    "ہوتا": "is/becomes/happens habitually; would be (masculine singular)",
    "سی": "like/as (feminine comparative particle); the letter C in acronyms",
    "انہیں": "them; to them",
    "وجہ": "reason; cause",
    "اسے": "him; her; it; to him/her/it",
    "لیے": "for; for the sake of",
    "جن": "who; which; those who (plural oblique)",
    "آ": "come; come! (stem/imperative of آنا); long ā/A in letter contexts",
    "لے": "take; take! (form/stem of لینا)",
    "میل": "mile; inclination/affinity; dirt/grime (different senses)",
    "روپے": "rupees; rupee (oblique/vocative singular)",
    "اے": "O!; hey! (vocative particle)",
    "آئی": "came (feminine singular); I in letter/acronym contexts",
    "ہمارے": "our (masculine plural/oblique)",
    "دوران": "during; duration; course/period",
    "ایسے": "such; like this; in this way",
    "ممالک": "countries",
    "میرے": "my; mine (masculine plural/oblique)",
    "بڑے": "big; large; great (masculine plural/oblique)",
    "ایسا": "such; like this; of this kind",
    "خیال": "thought; idea; opinion; care/attention",
    "ہماری": "our (feminine)",
    "دوسری": "second; other (feminine)",
    "بہتر": "better; improved",
    "میری": "my; mine (feminine)",
    "نئی": "new (feminine)",
    "تاکہ": "so that; in order that",
    "تھیں": "were (feminine plural)",
    "پہلی": "first (feminine)",
    "یعنی": "that is; namely; i.e.; meaning",
    "وی": "the letter V (especially in acronyms)",
    "او": "O!; oh!; the letter O in some contexts",
    "کس": "who; which (singular oblique interrogative)",
    "بڑھ": "increase; grow (stem of بڑھنا)",
    "علم": "knowledge; science; flag (different vocalization/sense)",
    "زمین": "land; earth; ground; soil",
    "ثابت": "fixed; established; proven; stable",
    "سر": "head; top; sir (title/loan)",
    "انتخابات": "elections",
    "رہ": "remain; stay; live (stem of رہنا)",
    "زر": "gold; money; wealth",
    "سمیت": "including; together with",
    "فی": "per; each",
    "کون": "who?",
    "طاقت": "strength; power; ability",
    "ذمہ": "responsibility; obligation; charge",
    "ذرائع": "sources; means; resources",
    "دورہ": "visit; tour; round; attack/fit (different senses)",
    "جسے": "whom; which; to whom/which",
    "گفتگو": "conversation; discussion; dialogue",
    "تیل": "oil",
    "آر": "the letter R (especially in acronyms)",
    "مذاکرات": "negotiations; talks",
    "اچھے": "good (masculine plural/oblique)",
    "لگے": "seemed; began; were attached (form of لگنا, context-dependent)",
    "مستقبل": "future",
    "ون": "one (English loan, especially in compounds such as ون ڈے); forest/wood (literary)",
    "تحصیل": "acquisition; attainment; tahsil/subdistrict",
    "داری": "possession; holding; practice/state (often in compounds)",
    "کن": "which; whom (plural/oblique interrogative)",
    "یقین": "certainty; belief; confidence",
    "روڈ": "road",
    "تصور": "concept; idea; conception",
    "چنانچہ": "therefore; consequently; accordingly",
    "سوچ": "thought; thinking; think (stem/imperative)",
    "دین": "religion; faith",
    "سکا": "could; was able to (masculine singular)",
    "ملی": "received; got; met (feminine singular); national (different sense)",
    "دباؤ": "pressure; stress; influence",
    "ساری": "all; whole (feminine)",
    "محکمہ": "department; bureau; office",
    "محض": "merely; only; purely",
    "رن": "run (especially in cricket/sports)",
    "اپ": "up (English loan/transliteration); a learned prefix in some compounds",
    "چونکہ": "because; since",
    "درد": "pain; ache; sorrow",
    "روشنی": "light; brightness",
    "واقعہ": "event; incident; occurrence",
    "لگ": "attach; seem; begin (stem of لگنا)",
    "جیسا": "like; as; such as",
    "اگلے": "next (masculine plural/oblique)",
    "بیٹے": "sons; son (oblique/vocative singular)",
    "امور": "affairs; matters",
    "معروف": "well-known; famous; known",
    "جنہیں": "whom; which; to whom/which (plural)",
    "مخصوص": "specific; particular; reserved",
    "تیسرے": "third (masculine plural/oblique)",
    "روک": "stop; prevention; restraint",
    "آہستہ": "slowly; gently; softly; slow",
    "امراض": "diseases; illnesses",
    "شاندار": "splendid; magnificent; excellent",
    "دیش": "country; land",
    "ادائیگی": "payment; fulfillment; performance",
    "اکبر": "greater; greatest; Akbar (name)",
    "تیسری": "third (feminine)",
    "بلا": "without; calamity/disaster (different senses)",
    "عزت": "honor; respect; esteem",
    "پس": "therefore; then; after/behind (different senses)",
    "کرا": "caused/made someone do; had done (causative form of کرنا)",
    "غم": "grief; sorrow",
    "خوب": "very; well; good; beautiful",
    "مری": "died (feminine singular); Murree (place name)",
    "سود": "interest (on money); profit",
    "داد": "praise; appreciation; applause; justice/redress",
    "عدد": "number; numeral",
    "دم": "breath; moment; tail (different senses)",
    "چلی": "went; left; moved (feminine singular); Chile (country)",
})

if __name__ == "__main__":
    base.main()
