(() => {
'use strict';

const retrievalCards = (window.CISSP_CHUNKS||[]).flatMap(c=>Array.isArray(c.high)?c.high:[]);
const baseQuestions = (window.CISSP_CHUNKS||[]).flatMap(c=>Array.isArray(c.questions)?c.questions:[]);
const cardsByObjective = retrievalCards.reduce((m,c)=>((m[c.objective]??=[]).push(c),m),{});
let releasedQuestions=[...baseQuestions], bankReady=false, bankError=null;
let parentSubtopicId=null, parentSubtopicLabel=null, currentFacet=null, currentPage=0;
const PAGE_SIZE=16;

const style=document.createElement('style');
style.textContent='.node.facet{width:170px;min-height:86px}.node.card,.node.scenario{width:132px;min-height:62px;padding:9px 10px}.node.pager{width:124px;min-height:50px}@media(max-width:800px){.node.facet{width:128px}.node.card,.node.scenario{width:104px;min-height:54px}}';
document.head.appendChild(style);
const input=document.getElementById('searchInput'); if(input) input.placeholder='Search domains, objectives, subtopics, cards, or released scenarios…';

function qObjectives(q){return Array.isArray(q.objectives)?q.objectives:(q.objective?[q.objective]:[])}
function qForObjective(id){return releasedQuestions.filter(q=>qObjectives(q).includes(id))}
function qForSubtopic(id,label){return qForObjective(id).filter(q=>Array.isArray(q.subtopics)&&q.subtopics.includes(label))}
function cardForObjective(id){return cardsByObjective[id]||[]}
function makeObjectiveRoot(o,extra=[]){const d=domainById['d'+o.domain_num];return{id:o.id,title:`${o.id} · ${o.label}`,summary:o.summary,kind:'objective-root',x:.5,y:.5,labels:[o.id,d?.title||o.domain,...extra],details:{rule:o.direct||o.summary,why:'This objective hub uses only released Atlas objective IDs and explicit child mappings.',traps:[o.trap||'Keep the objective tied to its stated business and security context.'],sources:(o.source_ids||[]).map(sourceTitle),practice:'Choose Subtopics, Retrieval cards, or Released scenarios.'}}}
function addPager(centerId,page,totalPages){if(totalPages<=1)return;if(page>0){nodes.push({id:'page:prev',title:'Previous page',summary:`Page ${page} of ${totalPages}`,kind:'pager',x:.18,y:.88,action:'prev'});links.push([centerId,'page:prev'])}if(page<totalPages-1){nodes.push({id:'page:next',title:'Next page',summary:`Page ${page+2} of ${totalPages}`,kind:'pager',x:.82,y:.88,action:'next'});links.push([centerId,'page:next'])}}
function detailForCard(c){return{rule:c.front,why:c.direct||'Retrieve the answer before revealing this layer.',traps:[c.trap||'Distinguish the nearest confusable concept.'],sources:(c.source_ids||[]).map(sourceTitle),practice:'Explain the answer without notes, then state one limitation, tradeoff, or confusable alternative.'}}
function detailForScenario(q){const opts=(q.options||[]).map((x,i)=>`${String.fromCharCode(65+i)}. ${x}`).join(' · '),ai=Number.isInteger(q.answer)?q.answer:null,correct=ai!==null&&q.options?.[ai]?`${String.fromCharCode(65+ai)}. ${q.options[ai]}`:'See released rationale';return{rule:`${q.stem||''}${opts?` Options: ${opts}`:''}`,why:`${q.decision_point?`Decision focus: ${q.decision_point}. `:''}${q.difficulty_tier?`Difficulty ${q.difficulty_tier}. `:''}Commit an answer before revealing layer 4.`,traps:q.misconceptions?.length?q.misconceptions:['Match the stated risk and decision point rather than choosing the strongest-sounding option.'],sources:(q.source_ids||[]).map(sourceTitle),practice:`Correct answer: ${correct}. ${q.explanation||''}`}}

window.objectiveHubLayout=function(objectiveId,returnTo=null,focus=false){const o=objectiveById[objectiveId];if(!o){domainLayout('root',focus);return}const subs=coverage[objectiveId]||[],cards=cardForObjective(objectiveId),qs=qForObjective(objectiveId);nodes=[makeObjectiveRoot(o,[`${subs.length} subtopics`,`${cards.length} cards`])];links=[];[
 {id:`facet:${objectiveId}:subtopics`,facet:'subtopics',title:'Subtopics',summary:`${subs.length} enriched mappings`,x:.5,y:.18},
 {id:`facet:${objectiveId}:cards`,facet:'cards',title:'Retrieval cards',summary:`${cards.length} reviewed cards`,x:.2,y:.7},
 {id:`facet:${objectiveId}:scenarios`,facet:'scenarios',title:'Released scenarios',summary:bankReady?`${qs.length} released scenarios`:`${qs.length} base scenarios · bank loading`,x:.8,y:.7}
].forEach(f=>{nodes.push({...f,kind:'facet',labels:[objectiveId,'explicit mapping']});links.push([objectiveId,f.id])});level='objective-hub';parentDomain='d'+o.domain_num;parentObjective=objectiveId;parentSubtopicId=null;parentSubtopicLabel=null;currentFacet=null;active=returnTo&&nodes.some(n=>n.id===returnTo)?returnTo:objectiveId;depth=0;render(focus)};

window.cardLayout=function(objectiveId,returnTo=null,focus=false,page=null){const o=objectiveById[objectiveId],records=cardForObjective(objectiveId);if(!o){domainLayout('root',focus);return}const idx=returnTo?records.findIndex(x=>x.id===returnTo):-1,p=page??(idx>=0?Math.floor(idx/PAGE_SIZE):0),pages=Math.max(1,Math.ceil(records.length/PAGE_SIZE)),slice=records.slice(p*PAGE_SIZE,(p+1)*PAGE_SIZE);nodes=[makeObjectiveRoot(o,[`${records.length} cards`])];links=[];if(slice.length){slice.forEach((c,i)=>{const pos=radialPosition(i,slice.length,.39,.24);nodes.push({id:c.id,title:`${c.id} · ${c.topic}`,summary:c.front,kind:'card',x:pos.x,y:pos.y,labels:[objectiveId,'retrieval card','semantic reviewed'],details:detailForCard(c)});links.push([objectiveId,c.id])});addPager(objectiveId,p,pages)}else addUnavailable(objectiveId,'No retrieval cards mapped',`No released Atlas retrieval cards are explicitly mapped to objective ${objectiveId}.`);level='cards';parentDomain='d'+o.domain_num;parentObjective=objectiveId;parentSubtopicId=null;parentSubtopicLabel=null;currentFacet='cards';currentPage=p;active=returnTo&&nodes.some(n=>n.id===returnTo)?returnTo:objectiveId;depth=0;render(focus)};

window.scenarioLayout=function(objectiveId,returnTo=null,focus=false,filter=null,page=null){const o=objectiveById[objectiveId];if(!o){domainLayout('root',focus);return}const all=filter?.label?qForSubtopic(objectiveId,filter.label):qForObjective(objectiveId),idx=returnTo?all.findIndex(x=>x.id===returnTo):-1,p=page??(idx>=0?Math.floor(idx/PAGE_SIZE):0),pages=Math.max(1,Math.ceil(all.length/PAGE_SIZE)),slice=all.slice(p*PAGE_SIZE,(p+1)*PAGE_SIZE);let center;if(filter?.id)center={id:filter.id,title:filter.label,summary:`Subtopic under ${objectiveId}`,kind:'subtopic-root',x:.5,y:.5,labels:[objectiveId,`${all.length} scenarios`],details:{rule:filter.label,why:`These scenarios include this exact released subtopic tag under objective ${objectiveId}.`,traps:['This is an explicit tag match, not a similarity-based inference.'],sources:['Released scenario subtopic tags'],practice:'Use scenarios to apply the subtopic in context.'}};else center=makeObjectiveRoot(o,[`${all.length} scenarios`]);nodes=[center];links=[];if(slice.length){slice.forEach((q,i)=>{const pos=radialPosition(i,slice.length,.39,.24);nodes.push({id:q.id,title:`${q.id} · ${q.decision_verb||'Scenario'}`,summary:q.stem,kind:'scenario',x:pos.x,y:pos.y,labels:[objectiveId,q.difficulty_tier||'scenario','released'],details:detailForScenario(q)});links.push([center.id,q.id])});addPager(center.id,p,pages)}else addUnavailable(center.id,bankReady?'No released scenarios mapped':'Released scenarios loading',bankReady?`No released standard scenario is explicitly mapped to ${filter?.label||objectiveId}.`:'The released-only manifest is still loading; candidate-only files remain excluded.');level='scenarios';parentDomain='d'+o.domain_num;parentObjective=objectiveId;parentSubtopicId=filter?.id||null;parentSubtopicLabel=filter?.label||null;currentFacet='scenarios';currentPage=p;active=returnTo&&nodes.some(n=>n.id===returnTo)?returnTo:center.id;depth=0;render(focus)};

const baseCrumb=crumbText;
window.crumbText=function(){if(level==='domains'||level==='objectives')return baseCrumb();const d=domainById[parentDomain],o=objectiveById[parentObjective],base=`SecX › ${d?.title||''} › ${o?`${o.id} ${o.label}`:''}`;if(level==='objective-hub')return base;if(level==='subtopics')return`${base} › Subtopics`;if(level==='cards')return`${base} › Retrieval cards`;if(level==='scenarios')return parentSubtopicLabel?`${base} › ${parentSubtopicLabel} › Scenarios`:`${base} › Released scenarios`;return base};

const baseDescend=descend;
window.descend=function(){const n=current();if(!n)return;if(n.kind==='pager'){if(level==='cards')cardLayout(parentObjective,null,true,currentPage+(n.action==='next'?1:-1));else if(level==='scenarios')scenarioLayout(parentObjective,null,true,parentSubtopicId?{id:parentSubtopicId,label:parentSubtopicLabel}:null,currentPage+(n.action==='next'?1:-1));return}if(level==='domains')return baseDescend();if(level==='objectives'&&n.kind==='objective')return objectiveHubLayout(n.id,null,true);if(level==='objective-hub'&&n.kind==='facet'){if(n.facet==='subtopics')return subtopicLayout(parentObjective,null,true);if(n.facet==='cards')return cardLayout(parentObjective,null,true);if(n.facet==='scenarios')return scenarioLayout(parentObjective,null,true)}if(level==='subtopics'&&n.kind==='subtopic'){const count=qForSubtopic(parentObjective,n.title).length;if(count)return scenarioLayout(parentObjective,null,true,{id:n.id,label:n.title});depth=Math.max(depth,2);return showDetail()}if(['cards','scenarios'].includes(level)){depth=Math.max(depth,2);showDetail()}};

const baseAscend=ascend;
window.ascend=function(){if(depth>0)return baseAscend();if(level==='scenarios'){if(parentSubtopicId)return subtopicLayout(parentObjective,parentSubtopicId,true);return objectiveHubLayout(parentObjective,`facet:${parentObjective}:scenarios`,true)}if(level==='cards')return objectiveHubLayout(parentObjective,`facet:${parentObjective}:cards`,true);if(level==='subtopics')return objectiveHubLayout(parentObjective,`facet:${parentObjective}:subtopics`,true);if(level==='objective-hub')return objectiveLayout(parentDomain,parentObjective,true);return baseAscend()};

function addSearchEntries(items){const seen=new Set(searchIndex.map(x=>`${x.kind}:${x.title}`));for(const x of items){const k=`${x.kind}:${x.title}`;if(!seen.has(k)){searchIndex.push(x);seen.add(k)}}}
function rebuildExtraSearch(){addSearchEntries(retrievalCards.map(c=>({kind:'card',title:`${c.id} · ${c.topic}`,path:`Objective ${c.objective} › Retrieval cards`,text:`${c.id} ${c.topic} ${c.front||''} ${c.direct||''} ${c.trap||''}`,domainId:'d'+c.domain_num,objectiveId:c.objective,cardId:c.id})));addSearchEntries(releasedQuestions.map(q=>{const objectiveId=qObjectives(q)[0]||'',o=objectiveById[objectiveId];return{kind:'scenario',title:`${q.id} · ${q.decision_verb||'Scenario'}`,path:`Objective ${objectiveId} › Released scenarios`,text:`${q.id} ${q.stem||''} ${(q.subtopics||[]).join(' ')} ${(q.knowledge_atoms||[]).join(' ')} ${q.decision_point||''}`,domainId:o?'d'+o.domain_num:'d'+(q.domain_primary||q.domain_num||1),objectiveId,scenarioId:q.id}}))}
const baseNavigate=navigateSearch;
window.navigateSearch=function(item){if(!item)return;if(item.kind==='card'){closeSearch();return cardLayout(item.objectiveId,item.cardId,true)}if(item.kind==='scenario'){closeSearch();return scenarioLayout(item.objectiveId,item.scenarioId,true)}return baseNavigate(item)};

function updateScope(){root.summary=`Atlas ${atlasMeta.version||'prototype'} · ${releasedObjectives.length} objectives · ${Object.values(coverage).reduce((n,x)=>n+x.length,0)} subtopics · ${retrievalCards.length} cards · ${bankReady?releasedQuestions.length:'loading scenarios'}`;const el=document.getElementById('scope');if(el)el.textContent=`Atlas ${atlasMeta.version||''} · ${releasedObjectives.length} objectives · ${retrievalCards.length} cards · ${bankReady?`${releasedQuestions.length} released scenarios`:(bankError?'released bank unavailable':'released scenarios loading')}`}
async function loadBank(){try{const manifest=await fetch('../study-site/question-bank/RELEASED_BATCHES.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`release manifest ${r.status}`);return r.json()}),files=manifest.released_batches.flatMap(b=>b.files||[]),texts=await Promise.all(files.map(p=>fetch(`../study-site/${p}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${p} ${r.status}`);return r.text()}))),rows=texts.flatMap(t=>t.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line)));releasedQuestions=[...baseQuestions,...rows.filter(r=>r.format==='mcq')];bankReady=true;bankError=null;rebuildExtraSearch();updateScope();if(level==='objective-hub')objectiveHubLayout(parentObjective,active,false)}catch(err){bankError=String(err);bankReady=false;console.error('SecX released bank load failed',err);updateScope()}}
rebuildExtraSearch();updateScope();domainLayout(active,false);loadBank();
})();
