#!/usr/bin/env python3
"""Append French A2 Unit 02 (sequences 7-12) as one guarded batch."""
from __future__ import annotations
import csv,json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[2]
CANON=ROOT/'reading/french/a2/passages.jsonl'; SCHEMA=ROOT/'reading/schema/passage.schema.json'; LEX=ROOT/'french_top1000.csv'
EXPECTED_BLOB='26b18ab417f19597cf12d7d45b8932c5654292fd'
FORMS=('raison','résultat','décision','information','important','différent','habitude','expérience','choix','idée')

def deck():
 out={}
 with LEX.open(encoding='utf-8',newline='') as f:
  for row in csv.DictReader(f):
   form=(row.get('Front') or '').strip(); b=row.get('Back') or ''
   mr=re.search(r'Rank:\s*(\d+)',b); mm=re.search(r'Meaning:\s*(.+)',b); mp=re.search(r'Part of speech:\s*(.+)',b)
   if form and mr and mm and mp: out[form]={'rank':int(mr.group(1)),'sense':mm.group(1).strip(),'pos':mp.group(1).strip()}
 return out
def tid(r):return f'fr-rank-{r:04d}'
def count(text,f):return len(re.findall(rf'(?<!\w){re.escape(f)}(?!\w)',text,flags=re.I|re.UNICODE))
def prior(rows):
 d={}
 for r in rows:
  for t in r.get('new_lexical_targets',[]):
   if isinstance(t,dict) and t.get('form'):d.setdefault(t['form'],[]).append(t)
 return d
def nt(f,text,D):
 s=D[f];n=count(text,f)
 if n<1:raise AssertionError(f'{f}: no exact running-text exposure')
 return {'id':tid(s['rank']),'form':f,'lemma':f,'intended_sense':s['sense'],'part_of_speech':s['pos'],'register':'contemporary standard','variety':None,'context_strategy':['scenario_resolution'],'first_introduced':True,'exposures_in_text':n,'source_lexicon':'french_top1000.csv','source_rank':s['rank'],'beyond_base':False}
def rev(f,P,stage='R1',rep='running_text'):
 h=P.get(f,[])
 if len(h)!=1:raise AssertionError(f'{f}: expected exactly one prior deliberate introduction, got {len(h)}')
 return {'id':h[0]['id'],'form':f,'review_stage':stage,'representation':rep,'expected_exposure_number':None}
def cur(f,D):return {'id':tid(D[f]['rank']),'form':f,'review_stage':'R1','representation':'summary','expected_exposure_number':None}
def qa(items):
 q=[];a=[]
 for i,(typ,prompt,answer,ids) in enumerate(items,1):
  qi=f'q{i}';ai=f'a{i}';x={'id':qi,'type':typ,'prompt':prompt,'answer_id':ai}
  if ids:x['target_ids']=ids
  q.append(x);a.append({'id':ai,'question_id':qi,'answer':answer,'explanation':''})
 return q,a
def mk(pid,seq,ptype,title,genre,domains,topics,text,new,reviews,grammar,discourse,items,speed=False):
 q,a=qa(items)
 return {'id':pid,'language':'fr','cefr':'A2','unit':2,'sequence':seq,'revision':1,'title':title,'passage_type':ptype,'genre':genre,'domains':domains,'topics':topics,'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':grammar,'discourse_targets':discourse,'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'Generation-stage French A2 Unit 02; full multi-pass French audit deferred.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French A2 Unit 02 generation batch.','A2 word band, source identity, prior-target review visibility, local target declaration, linkage, continuity and checkpoint invariants are enforced.']},'paired_text_group':None,'prerequisites':['French A2 Unit 01 canonical corpus'],'difficulty_notes_internal':'A2 Unit 02: reasons/results, decisions/information, importance/difference, habits/experience, and choices/ideas.','reader_tags':['unit_role:'+ptype,'generation_batch','french_a2_u02']}
def build(rows,D):
 P=prior(rows)
 for f in FORMS:
  if f not in D:raise AssertionError(f'{f}: missing from validated french_top1000.csv')
  if P.get(f):raise AssertionError(f'{f}: already deliberately introduced in A2')
 out=[]
 text='''Après un retard de bus la semaine précédente, Camille décide de partir plus tôt pour son prochain rendez-vous. Elle explique à Sami la raison de ce changement : elle ne veut pas arriver stressée ni prévenir l’école au dernier moment. Sami lui conseille de comparer deux trajets. Camille choisit une ligne un peu plus longue mais plus régulière. Le résultat est simple : elle arrive dix minutes avant l’heure prévue. Pourtant, elle ne conclut pas qu’un trajet plus long est toujours meilleur. Elle comprend seulement que, dans cette situation, sa raison était claire et que le résultat correspondait à son objectif pratique. Elle note le trajet dans son téléphone pour pouvoir le comparer avec d’autres jours où la circulation sera peut-être différente.'''
 a,b=nt('raison',text,D),nt('résultat',text,D)
 out.append(mk('fr-a2-u02-p01',7,'instructional','Une raison et un résultat','transport comparison narrative',['public','educational'],['transport','reason','outcome'],text,[a,b],[rev('retard',P),rev('conseil',P)],[{'id':'fr-a2-parce-que-resultat','role':'new','description':'connect a reason to a result without overgeneralizing'}],[{'id':'fr-a2-reason-result-chain','role':'new','description':'distinguish motive/reason from observed outcome'}],[('gist','Pourquoi Camille part-elle plus tôt ?','Parce qu’elle veut éviter le stress et arriver à l’heure.',[]),('literal_detail','Quand arrive-t-elle ?','Dix minutes avant l’heure prévue.',[]),('sequence','Que fait-elle avant de choisir son trajet ?','Elle compare deux trajets avec le conseil de Sami.',[]),('inference','Pourquoi Camille ne dit-elle pas que le trajet plus long est toujours meilleur ?','Parce qu’elle n’a observé qu’une situation et que les conditions peuvent changer.',[]),('vocabulary_in_context','Que signifie « raison » ici ?','Ce qui explique pourquoi Camille change son trajet.',[a['id']]),('vocabulary_in_context','Que signifie « résultat » ?','Ce qui se produit après son choix : elle arrive en avance.',[b['id']]),('grammar_in_context','Dans « la raison de ce changement », que complète « de ce changement » ?','Le nom « raison ».',[]),('grammar_choice','Choisis : « Le résultat est qu’elle arrive tôt » ou « Le résultat est elle arrive tôt » ?','« Le résultat est qu’elle arrive tôt. »',[]),('cloze_transfer','Complète : Je change de route pour une _____ précise, puis j’observe le _____.','raison ; résultat',[a['id'],b['id']]),('paraphrase','Reformule la conclusion prudente de Camille.','Ce trajet a bien fonctionné cette fois, mais cela ne prouve pas qu’il sera toujours le meilleur.',[])]))
 text='''À l’école, Camille découvre une erreur dans l’heure d’une réunion. Avant de prendre une décision, elle cherche une information fiable. Un premier message dit que la réunion commence à seize heures, mais une affiche récente indique seize heures trente. Camille demande alors au secrétariat quelle information est correcte. La responsable confirme l’horaire de l’affiche. Camille prend la décision de prévenir son groupe et explique la différence entre les deux annonces. Elle ne supprime pas l’ancien message : elle écrit plutôt qu’il n’est plus à jour. Ainsi, les autres élèves peuvent comprendre d’où venait la confusion. Camille retient qu’une décision devient plus facile quand l’information utilisée est claire, récente et vérifiée, surtout lorsqu’une erreur peut affecter plusieurs personnes.'''
 a,b=nt('décision',text,D),nt('information',text,D)
 out.append(mk('fr-a2-u02-p02',8,'reinforcement','Vérifier avant de décider','school-information narrative',['educational'],['schedule','information','decision'],text,[a,b],[rev('erreur',P),rev('expliquer',P)],[{'id':'fr-a2-avant-de-decision','role':'new','description':'use avant de to order verification before action'}],[{'id':'fr-a2-source-check','role':'new','description':'compare conflicting information before deciding'}],[('gist','Quel problème Camille doit-elle résoudre ?','Deux horaires différents sont annoncés pour la même réunion.',[]),('literal_detail','Quel horaire le secrétariat confirme-t-il ?','Seize heures trente.',[]),('reference_resolution','À quoi renvoie « il » dans « il n’est plus à jour » ?','À l’ancien message.',[]),('inference','Pourquoi Camille garde-t-elle l’ancien message ?','Pour que les autres comprennent l’origine de la confusion.',[]),('vocabulary_in_context','Que signifie « décision » ici ?','Le choix d’une action après vérification.',[a['id']]),('vocabulary_in_context','Que signifie « information » ?','Un renseignement utilisé pour comprendre ou décider.',[b['id']]),('grammar_in_context','Dans « avant de prendre une décision », quelle forme suit « de » ?','Un infinitif : « prendre ».',[]),('grammar_choice','Choisis : « l’information est correcte » ou « l’information sont correcte » ?','« l’information est correcte. »',[]),('cloze_transfer','Complète : Avant ma _____, je vérifie l’_____.','décision ; information',[a['id'],b['id']]),('paraphrase','Explique la méthode de Camille.','Elle compare les sources, demande confirmation, puis décide et explique clairement la correction.',[])]))
 text='''Camille veut essayer une nouvelle méthode pour réviser son français. Elle pense qu’il est important de pratiquer régulièrement, mais elle sait que chaque élève est différent. Sami préfère relire longtemps ses notes, tandis que Camille aime faire de courtes questions puis vérifier ses réponses. Pendant une semaine, elle essaie sa méthode vingt minutes par jour. À la fin, elle se souvient mieux de certains mots, mais pas de tous. Elle trouve ce résultat intéressant sans dire que sa méthode est parfaite. Pour elle, le point important est de comparer ce qu’elle faisait avant avec ce qu’elle fait maintenant. Comme Sami est différent, il peut obtenir un autre résultat. Ils décident donc d’échanger leurs observations plutôt que de chercher une seule méthode obligatoire pour tout le monde.'''
 a,b=nt('important',text,D),nt('différent',text,D)
 out.append(mk('fr-a2-u02-p03',9,'interleaved','Une méthode différente','study-method narrative',['educational','personal'],['study','comparison','individual differences'],text,[a,b],[rev('essayer',P),rev('possible',P)],[{'id':'fr-a2-il-est-important-de','role':'new','description':'use il est important de + infinitive'}],[{'id':'fr-a2-individual-comparison','role':'new','description':'compare methods without assuming one result applies to everyone'}],[('gist','Quelle méthode Camille essaie-t-elle ?','De courtes questions suivies d’une vérification des réponses.',[]),('literal_detail','Combien de temps pratique-t-elle par jour ?','Vingt minutes.',[]),('sequence','Que fait-elle après une semaine ?','Elle compare ce qu’elle retient avec sa façon de travailler avant.',[]),('inference','Pourquoi Camille ne dit-elle pas que sa méthode est parfaite ?','Parce qu’elle n’améliore pas tous les mots et qu’une autre personne peut réagir différemment.',[]),('vocabulary_in_context','Que signifie « important » ici ?','Qui mérite une attention particulière dans son apprentissage.',[a['id']]),('vocabulary_in_context','Que signifie « différent » ?','Qui n’est pas identique à une autre personne ou situation.',[b['id']]),('grammar_in_context','Dans « il est important de pratiquer », quelle forme vient après « de » ?','Un infinitif.',[]),('grammar_choice','Choisis : « chaque élève est différent » ou « chaque élève sont différents » ?','« chaque élève est différent. »',[]),('cloze_transfer','Complète : Il est _____ de vérifier, car chaque situation peut être _____.','important ; différente',[a['id'],b['id']]),('paraphrase','Résume leur conclusion.','Ils comparent leurs méthodes et acceptent qu’une méthode puisse fonctionner différemment selon la personne.',[])]))
 text='''Depuis quelques semaines, Camille essaie de préparer son sac le soir plutôt que le matin. Cette habitude lui fait gagner du temps, mais elle veut savoir si elle est vraiment utile. Elle transforme donc la situation en petite expérience personnelle. Pendant cinq jours, elle note l’heure de son départ et vérifie si elle oublie quelque chose. Les trois premiers jours, tout se passe bien. Le quatrième, elle oublie une feuille malgré sa nouvelle habitude. Camille comprend alors qu’une expérience courte peut donner des indications sans garantir un résultat parfait. Elle garde l’habitude, mais ajoute une liste près de la porte. Son expérience lui montre surtout qu’une routine peut aider tout en ayant des limites. Elle préfère améliorer progressivement son système plutôt que l’abandonner après une seule erreur.'''
 a,b=nt('habitude',text,D),nt('expérience',text,D)
 out.append(mk('fr-a2-u02-p04',10,'transfer','Tester une habitude','self-observation narrative',['personal','educational'],['routine','self-observation','planning'],text,[a,b],[rev('réparer',P),rev('éviter',P)],[{'id':'fr-a2-depuis-duree','role':'new','description':'use depuis with an ongoing period'}],[{'id':'fr-a2-small-experiment','role':'new','description':'evaluate a routine through a short personal observation'}],[('gist','Quelle habitude Camille teste-t-elle ?','Préparer son sac le soir.',[]),('literal_detail','Pendant combien de jours note-t-elle ses départs ?','Pendant cinq jours.',[]),('sequence','Que fait-elle après avoir oublié une feuille ?','Elle garde l’habitude et ajoute une liste près de la porte.',[]),('inference','Pourquoi ne supprime-t-elle pas son habitude après une erreur ?','Parce que l’habitude l’aide généralement et qu’une seule erreur ne suffit pas à la juger inutile.',[]),('vocabulary_in_context','Que signifie « habitude » ici ?','Une action qu’elle répète régulièrement.',[a['id']]),('vocabulary_in_context','Que signifie « expérience » ?','Un essai organisé pour observer ce qui se passe.',[b['id']]),('grammar_in_context','Dans « depuis quelques semaines », que montre « depuis » ?','Le début d’une situation qui continue jusqu’au présent.',[]),('grammar_choice','Choisis : « Depuis lundi, elle prépare son sac le soir » ou « Depuis lundi, elle a arrêté hier » ?','« Depuis lundi, elle prépare son sac le soir. »',[]),('cloze_transfer','Complète : Cette _____ quotidienne devient une petite _____ personnelle.','habitude ; expérience',[a['id'],b['id']]),('paraphrase','Explique ce qu’elle apprend.','Une habitude peut être utile sans être parfaite, et on peut l’améliorer après avoir observé ses limites.',[])]))
 text='''Camille a un rendez-vous avec le club de lecture pour préparer une activité. En arrivant, elle découvre que deux salles sont possibles. Le premier choix est une grande salle près de l’entrée ; le second est une petite salle plus calme. Sami propose une idée : commencer dans la petite salle pour préparer le matériel, puis aller dans la grande quand le public arrive. Camille aime cette idée, mais elle demande combien de personnes sont attendues. Après avoir reçu l’information, le groupe garde ce choix. Ils écrivent aussi une autre idée au cas où la grande salle serait occupée. Camille remarque qu’un bon choix dépend souvent des contraintes réelles, et qu’une idée devient plus utile quand on vérifie si elle peut fonctionner dans la situation présente.'''
 a,b=nt('choix',text,D),nt('idée',text,D)
 out.append(mk('fr-a2-u02-p05',11,'integration','Un choix pour le club','club-planning narrative',['educational','public'],['club','planning','options'],text,[a,b],[rev('rendez-vous',P),rev('découvrir',P)],[{'id':'fr-a2-apres-avoir','role':'new','description':'use après avoir + past participle for completed prior action'}],[{'id':'fr-a2-idea-constraint','role':'new','description':'evaluate an idea against practical constraints before choosing'}],[('gist','Quel choix le groupe fait-il ?','Préparer le matériel dans la petite salle puis utiliser la grande salle quand le public arrive.',[]),('literal_detail','Pourquoi la petite salle est-elle intéressante ?','Parce qu’elle est plus calme.',[]),('reference_resolution','À quoi renvoie « ce choix » ?','Au plan d’utiliser d’abord la petite salle puis la grande.',[]),('inference','Pourquoi demandent-ils combien de personnes sont attendues ?','Pour vérifier si leur idée correspond aux besoins réels de l’activité.',[]),('vocabulary_in_context','Que signifie « choix » ici ?','L’option retenue parmi plusieurs possibilités.',[a['id']]),('vocabulary_in_context','Que signifie « idée » ?','Une proposition ou pensée sur ce qu’on pourrait faire.',[b['id']]),('grammar_in_context','Dans « après avoir reçu l’information », quelle action se produit d’abord ?','Ils reçoivent l’information.',[]),('grammar_choice','Choisis : « après avoir reçu » ou « après avoir recevoir » ?','« après avoir reçu »',[]),('cloze_transfer','Complète : J’ai deux options ; mon _____ dépend de l’_____ qui fonctionne le mieux.','choix ; idée',[a['id'],b['id']]),('paraphrase','Résume leur méthode de décision.','Ils proposent une idée, vérifient les contraintes, puis gardent le choix qui convient à la situation.',[])]))
 text='''Dans cette unité, Camille apprend à regarder plus précisément ce qui guide une action. Une raison explique pourquoi elle agit, tandis qu’un résultat montre ce qui se produit ensuite. Avant une décision, elle cherche une information fiable. Elle sait qu’un détail important peut être différent selon la situation ou la personne. Elle observe aussi une habitude comme une petite expérience afin de voir ce qui fonctionne vraiment. Enfin, lorsqu’elle a plusieurs options, elle distingue l’idée proposée du choix finalement retenu. Ces distinctions ne rendent pas toutes les décisions faciles, mais elles l’aident à expliquer son raisonnement avec plus de précision. Camille utilise encore les mots de l’unité précédente pour essayer, éviter des erreurs, expliquer un problème et découvrir de nouvelles informations sans oublier que les résultats peuvent varier.'''
 reviews=[cur(f,D) for f in FORMS]
 out.append(mk('fr-a2-u02-p06',12,'checkpoint','Comprendre ce qui guide un choix','A2 cumulative reasoning summary',['personal','educational','public'],['reasoning','decisions','evaluation'],text,[],reviews,[{'id':'fr-a2-u02-cumulative-grammar','role':'integration','description':'integrate infinitive and temporal structures from Unit 02'}],[{'id':'fr-a2-u02-cumulative-reasoning','role':'integration','description':'distinguish reasons, evidence, options, ideas, choices and results'}],[('gist','Quelle est l’idée principale du texte ?','Camille apprend à expliquer plus précisément comment elle observe, compare et décide.',[]),('literal_detail','Que cherche-t-elle avant une décision ?','Une information fiable.',[]),('reference_resolution','À quoi renvoie « ces distinctions » ?','Aux différences entre raison/résultat, information/décision, important/différent, habitude/expérience et idée/choix.',[]),('inference','Pourquoi ces distinctions n’assurent-elles pas une décision facile ?','Parce que les situations peuvent rester complexes même quand les termes et les informations sont plus clairs.',[]),('vocabulary_in_context','Que signifie « résultat » ?','Ce qui se produit après une action ou un choix.',[tid(D['résultat']['rank'])]),('vocabulary_in_context','Que signifie « expérience » ici ?','Un essai ou une observation organisée pour voir ce qui se passe.',[tid(D['expérience']['rank'])]),('grammar_in_context','Dans « afin de voir », que présente « afin de » ?','Le but de l’observation.',[]),('grammar_choice','Choisis : « avant de décider » ou « avant décider » ?','« avant de décider »',[]),('cloze_transfer','Complète : Une _____ propose une possibilité ; le _____ est l’option finalement retenue.','idée ; choix',[tid(D['idée']['rank']),tid(D['choix']['rank'])]),('summary','Résume la stratégie de Camille en une phrase.','Elle cherche des informations, distingue raisons et résultats, compare les options et explique pourquoi elle retient un choix.',[])],speed=True))
 return out

def main():
 blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if blob!=EXPECTED_BLOB:raise AssertionError(f'A2 canonical blob drift: {blob} != {EXPECTED_BLOB}')
 rows=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(rows)!=6 or [r['sequence'] for r in rows]!=list(range(1,7)) or rows[-1]['id']!='fr-a2-u01-p06':raise AssertionError('expected exact A2 Unit 01 frontier')
 D=deck();unit=build(rows,D);V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));old={t['id'] for r in rows for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 if [r['sequence'] for r in unit]!=list(range(7,13)) or len({r['id'] for r in rows+unit})!=12:raise AssertionError('A2 Unit02 continuity failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:5]]}")
  if not 140<=r['word_count']<=220:raise AssertionError(f"{r['id']}: A2 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   s=D.get(t['form'])
   if t['id'] in old or not s or t['source_rank']!=s['rank'] or t['id']!=tid(s['rank']) or count(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: source/exposure/reintroduction drift {t}")
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and count(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible Unit01 review {t['form']}")
 if sum(len(r['new_lexical_targets']) for r in unit[:5])!=10 or unit[-1]['new_lexical_targets']!=[]:raise AssertionError('A2 Unit02 lexical-cycle invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in rows+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','level':'A2','unit':2,'appended_passages':6,'a2_passages':12,'word_counts':{r['id']:r['word_count'] for r in unit},'new_targets':[{'form':f,'rank':D[f]['rank'],'id':tid(D[f]['rank'])} for f in FORMS],'questions':60,'answers':60,'p06_new_targets':0},ensure_ascii=False))
if __name__=='__main__':main()
