#!/usr/bin/env python3
"""Append French B2 Unit05 (seq25-30): climate and uncertainty."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
R=Path(__file__).resolve().parents[2];A1=R/'reading/french/a1/passages.jsonl';A2=R/'reading/french/a2/passages.jsonl';B1=R/'reading/french/b1/passages.jsonl';CANON=R/'reading/french/b2/passages.jsonl';SCHEMA=R/'reading/schema/passage.schema.json';LOCK=R/'reading/audit/french_b2_unit04_frontier_lock.json';PROBE=R/'reading/audit/french_b2_unit05_target_probe.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca','B2':'125d8c87641ee5a0fbd958a415ede82f95c40eff'}
FORMS=('été','année','mois','nuit','passé','long','changer','continuer','rester','devenir','compter','montrer','croire','penser','sembler','comprendre','préparer','action','mer','terre')
SPECS=[
{'id':'fr-b2-u05-p01','sequence':25,'ptype':'instructional','title':'Un été très chaud ne suffit pas à décrire une tendance','genre':'evidence summary','domains':['public','educational'],'topics':['climate and uncertainty','time windows','evidence interpretation'],'forms':['été','année','mois','nuit'],'reviews':['coin','côté','arbre','air'],'paragraphs':[
"Dans un exemple fictif, une station locale compare ses relevés de température sur plusieurs décennies. Une journaliste remarque qu’un été récent a compté davantage de journées très chaudes que l’été précédent. Le résumé scientifique refuse pourtant de transformer immédiatement cette observation en conclusion générale. Une année peut être inhabituelle pour de nombreuses raisons, et un seul mois peut peser fortement sur une moyenne saisonnière. Pour comprendre un changement durable, l’équipe compare plusieurs périodes et regarde aussi ce qui se passe la nuit, lorsque les conditions d’une ville peuvent rester différentes de celles des zones voisines.",
"Le premier graphique montre des valeurs annuelles. Le second sépare chaque mois, tandis qu’un troisième distingue le jour et la nuit. Cette organisation évite qu’une seule moyenne cache des formes différentes de variation. Par exemple, deux années pourraient afficher une moyenne comparable si l’une connaît des journées plus chaudes mais des nuits plus fraîches. Le résumé demande donc de ne pas chercher un unique chiffre spectaculaire. Comme dans l’analyse d’un coin de place, il faut examiner plusieurs côtés du phénomène : durée, fréquence, saison et contexte local. Un arbre ou la circulation de l’air peuvent modifier une mesure près du sol sans expliquer à eux seuls l’évolution d’une région entière.",
"L’équipe formule ensuite trois niveaux de conclusion. Elle peut décrire avec confiance ce qui a été mesuré pendant un été précis. Elle peut comparer cette année aux années disponibles. Elle est plus prudente lorsqu’elle discute de ce qui pourrait se produire dans les prochaines décennies. Plus la question s’éloigne de l’observation directe, plus les hypothèses deviennent importantes. Cette prudence ne signifie pas que toute conclusion est impossible. Elle signifie que la force d’une affirmation doit correspondre à la quantité et à la qualité des données qui la soutiennent.",
"La synthèse recommande donc de présenter ensemble la tendance centrale et les variations. Si plusieurs années montrent une évolution similaire pendant plus d’un mois ou d’une seule nuit exceptionnelle, l’argument devient plus solide. Si le résultat dépend presque entièrement d’un été isolé, il faut le dire. Le texte défend une règle simple : l’incertitude n’efface pas les données, mais elle oblige à préciser leur portée. Observer l’air, un arbre ou un coin particulier aide à comprendre un mécanisme local; comparer chaque côté du temps disponible aide à savoir jusqu’où on peut généraliser."
],
'grammar':[{'id':'fr-b2-u05-time-scope','role':'new','description':'contrast one event with longer evidence windows using année, mois, été and nuit'}],
'discourse':[{'id':'fr-b2-u05-evidence-scope','role':'new','description':'separate observation, comparison and projection by strength and temporal scope'}],
'items':[
('main_claim','Pourquoi un seul été ne suffit-il pas à établir une tendance durable ?','Parce qu’un événement isolé peut être atypique et doit être comparé à plusieurs années et plusieurs dimensions des données.',['été','année']),
('literal_detail','Quels trois découpages sont comparés ?','Les valeurs annuelles, les mois, puis le jour et la nuit.',['mois','nuit']),
('argument_relation','Pourquoi le résumé sépare-t-il jour et nuit ?','Pour éviter qu’une moyenne unique masque des évolutions différentes selon le moment.',['nuit']),
('vocabulary_in_context','Que signifie « année » dans l’analyse ?','Une unité temporelle de comparaison qui contient plusieurs saisons et mois.',['année']),
('vocabulary_in_context','Quel rôle joue « mois » ?','Il permet de voir si une moyenne saisonnière dépend surtout d’une partie limitée de la période.',['mois']),
('assumption','Quelle hypothèse soutient l’idée qu’une série plus longue renforce une conclusion ?','Que des observations répétées dans le temps réduisent le risque de confondre un événement exceptionnel avec une évolution durable.',['long','année']),
('inference','Pourquoi les observations locales ne suffisent-elles pas à décrire une région entière ?','Parce qu’un arbre, un coin ou la circulation de l’air peuvent produire des conditions particulières à petite échelle.',['arbre','coin','air']),
('reference_resolution','Dans « elle peut comparer cette année », à quoi renvoie « elle » ?','À l’équipe qui résume et interprète les relevés.',['année']),
('stance','Quelle position le texte adopte-t-il envers l’incertitude ?','Elle doit limiter la portée des affirmations sans conduire à ignorer les données disponibles.',['été','nuit']),
('summary','Résume la méthode.','Comparer un été, une année, chaque mois et la nuit sur une période plus longue, tout en distinguant l’effet local d’un coin, d’un côté, d’un arbre ou de l’air, permet d’ajuster la force de la conclusion aux données.',['été','année','mois','nuit','coin','côté','arbre','air'])]},
{'id':'fr-b2-u05-p02','sequence':26,'ptype':'reinforcement','title':'Ce qui a changé dans le passé ne dit pas exactement comment demain continuera','genre':'news analysis','domains':['public'],'topics':['climate and uncertainty','trend reporting','projection limits'],'forms':['passé','long','changer','continuer'],'reviews':['voiture','proche','besoin','simple'],'paragraphs':[
"Un article d’analyse fictif examine une série de relevés d’un bassin urbain. Le titre initial affirme que « la tendance va continuer au même rythme ». L’éditrice demande de le modifier. Les observations montrent bien que certaines valeurs ont changé dans le passé, mais elles ne démontrent pas que le futur suivra exactement la même ligne. Une série longue permet de voir si une variation persiste, pas de supprimer toutes les causes possibles de changement. L’article doit donc expliquer ce que les données soutiennent, puis séparer cette conclusion de ce qui reste hypothétique.",
"Le journaliste compare deux périodes. Dans la première, les résultats varient fortement d’une année à l’autre. Dans la seconde, le mouvement général devient plus visible. Il serait simple de prolonger la ligne sur un graphique et d’appeler cela une prévision. Pourtant, la ville peut changer, les usages du territoire peuvent changer et les méthodes de mesure peuvent aussi évoluer. Même une série longue doit être lue avec son contexte. L’analyse insiste donc sur une distinction : montrer une évolution passée est une tâche descriptive; dire qu’elle va continuer exige des hypothèses supplémentaires.",
"Une interview ajoute une controverse. Un responsable veut annoncer rapidement une mesure coûteuse parce qu’il pense que l’évolution va continuer. Une chercheuse répond qu’attendre une certitude parfaite n’est pas nécessaire, mais qu’il faut préciser le niveau de risque auquel la décision répond. Elle compare ce choix à une rue où la voiture est limitée près d’une école : la règle peut répondre à un besoin réel même si l’on ne connaît pas chaque événement futur. L’essentiel est d’indiquer ce qui pourrait faire changer l’évaluation et à quel moment la décision sera révisée.",
"L’article final remplace donc le titre catégorique par une formule conditionnelle. Il dit que la tendance observée dans le passé pourrait continuer si plusieurs facteurs restent comparables, tout en signalant les limites. Cette formulation paraît moins spectaculaire, mais elle est plus informative. Une analyse longue n’est pas une promesse. Elle sert à repérer ce qui a déjà changé, à examiner ce qui pourrait changer encore et à définir les observations nécessaires pour continuer à tester l’hypothèse. Le texte défend ainsi une communication où la prudence ne cache ni le risque ni le besoin d’action."
],
'grammar':[{'id':'fr-b2-u05-past-projection','role':'new','description':'distinguish observed past change from conditional continuation with passé, changer, continuer and si'}],
'discourse':[{'id':'fr-b2-u05-projection-limit','role':'new','description':'critique categorical projection and replace it with conditional, revisable analysis'}],
'items':[
('main_claim','Pourquoi le titre initial est-il rejeté ?','Parce qu’il transforme une évolution observée dans le passé en certitude sur la manière dont elle va continuer.',['passé','continuer']),
('literal_detail','Quels types de facteurs peuvent modifier la projection ?','Les changements de la ville, des usages du territoire et des méthodes de mesure.',['changer']),
('argument_relation','Pourquoi une série longue reste-t-elle insuffisante pour une prévision certaine ?','Parce qu’elle décrit mieux le passé sans garantir que les conditions explicatives resteront identiques.',['long','passé']),
('vocabulary_in_context','Que signifie « changer » dans le texte ?','Évoluer de manière à modifier les valeurs observées ou l’interprétation de la tendance.',['changer']),
('vocabulary_in_context','Que signifie « continuer » ?','Se poursuivre dans le temps selon une direction ou un rythme comparable.',['continuer']),
('assumption','Quelle hypothèse est nécessaire pour prolonger une tendance ?','Que les facteurs importants restent suffisamment comparables pour que le mécanisme observé continue.',['continuer']),
('inference','Pourquoi l’article compare-t-il la décision à une règle de voiture près d’une école ?','Pour montrer qu’une action peut répondre à un besoin avant la certitude parfaite si ses conditions de révision sont claires.',['voiture','proche','besoin']),
('reference_resolution','Dans « elle sert à repérer », à quoi renvoie « elle » ?','À une analyse longue de la série de données.',['long']),
('stance','Quelle position le texte adopte-t-il envers une formule conditionnelle ?','Il la préfère à une annonce simple et catégorique parce qu’elle rend visibles les hypothèses.',['simple','continuer']),
('summary','Résume l’analyse.','Une série longue montre ce qui a changer dans le passé mais ne prouve pas comment cela va continuer; comme une règle simple sur la voiture proche d’un besoin, la décision doit rester révisable selon les nouvelles observations.',['long','passé','changer','continuer','simple','voiture','proche','besoin'])]},
{'id':'fr-b2-u05-p03','sequence':27,'ptype':'interleaved','title':'Compter davantage de cas peut montrer un signal sans expliquer sa cause','genre':'evidence summary','domains':['educational','public'],'topics':['climate and uncertainty','counts','causal caution'],'forms':['rester','devenir','compter','montrer'],'reviews':['construire','ouvrir','fermer','utiliser'],'paragraphs':[
"Une équipe fictive étudie des épisodes de chaleur dans plusieurs secteurs d’une ville. Son premier tableau consiste à compter le nombre de jours qui dépassent un seuil défini. Ce choix permet de montrer si ces épisodes deviennent plus fréquents dans les relevés disponibles. Mais le document précise immédiatement une limite : compter davantage de cas ne suffit pas à expliquer pourquoi ils apparaissent. Une partie du signal peut venir d’un changement réel des conditions, une autre d’un réseau de mesure devenu plus dense. L’incertitude doit donc rester visible pendant l’interprétation.",
"Pour tester cette possibilité, les analystes reconstruisent les séries avec seulement les stations présentes depuis le début. Le signal devient un peu plus faible mais reste visible. Ils essaient ensuite une autre définition du seuil et obtiennent une tendance comparable. Ces contrôles ne ferment pas la discussion; ils permettent d’ouvrir des explications concurrentes et de voir lesquelles résistent. Construire un argument à partir des données exige donc de montrer ce qui change lorsque la méthode change, pas seulement de choisir la version qui produit le résultat le plus fort.",
"Le rapport distingue alors trois questions. Premièrement, combien de cas faut-il compter ? Deuxièmement, le phénomène semble-t-il devenir plus fréquent dans plusieurs sous-groupes ? Troisièmement, quelles explications peuvent rester compatibles avec les observations ? La première question est descriptive, la seconde comparative et la troisième causale. Utiliser la même réponse pour les trois conduirait à une conclusion trop large. Les auteurs préfèrent expliquer où les données sont solides et où une interprétation doit encore être testée.",
"La conclusion affirme donc que les observations peuvent montrer un changement robuste sans identifier une cause unique. Cette position n’est pas une faiblesse méthodologique; elle empêche de fermer trop tôt l’enquête. Une bonne synthèse peut compter les événements, montrer qu’un résultat reste présent sous plusieurs choix raisonnables et dire ce qui pourrait devenir plus clair avec de nouvelles données. Elle peut aussi reconnaître que certaines explications vont rester possibles tant qu’une comparaison supplémentaire n’aura pas été faite. L’objectif est de construire une conclusion proportionnée, puis d’utiliser l’incertitude pour définir le prochain test plutôt que pour nier le signal."
],
'grammar':[{'id':'fr-b2-u05-count-signal','role':'new','description':'separate counting, showing persistence and becoming more frequent from causal explanation'}],
'discourse':[{'id':'fr-b2-u05-robustness-check','role':'new','description':'use alternate definitions/subsets to test whether an observed signal remains robust'}],
'items':[
('main_claim','Quelle distinction centrale organise le rapport ?','Compter et montrer un signal décrit sa robustesse sans suffire à expliquer sa cause.',['compter','montrer']),
('literal_detail','Quel premier contrôle est effectué ?','Les séries sont recalculées avec seulement les stations présentes depuis le début.',['rester']),
('argument_relation','Pourquoi tester une autre définition du seuil ?','Pour vérifier si le résultat reste visible sous un choix raisonnable différent.',['rester','montrer']),
('vocabulary_in_context','Que signifie « compter » dans le passage ?','Déterminer combien d’événements répondent au seuil choisi.',['compter']),
('vocabulary_in_context','Que signifie « devenir » dans « devenir plus fréquent » ?','Évoluer vers une fréquence plus élevée au fil du temps.',['devenir']),
('assumption','Quelle hypothèse soutient les tests de robustesse ?','Qu’un signal moins dépendant d’un seul choix méthodologique mérite davantage de confiance.',['rester']),
('inference','Pourquoi garder plusieurs explications ouvertes ?','Parce que le même signal descriptif peut être compatible avec plusieurs mécanismes tant qu’ils ne sont pas distingués par d’autres tests.',['ouvrir','fermer']),
('reference_resolution','Dans « ils permettent d’ouvrir », qui est « ils » ?','Les contrôles qui utilisent d’autres stations ou une autre définition du seuil.',['ouvrir']),
('stance','Quelle position le rapport adopte-t-il envers une cause unique ?','Il refuse de la déclarer avant que les données permettent de distinguer les explications concurrentes.',['construire','utiliser']),
('summary','Résume la méthode.','L’équipe choisit quoi compter pour montrer si un signal reste visible et semble devenir plus fréquent; elle utilise plusieurs tests pour construire l’argument sans fermer trop tôt les explications qu’il faut encore ouvrir et examiner.',['compter','montrer','rester','devenir','utiliser','construire','fermer','ouvrir'])]},
{'id':'fr-b2-u05-p04','sequence':28,'ptype':'transfer','title':'Croire une prévision, penser un scénario ou comprendre une marge d’erreur','genre':'news analysis','domains':['public','educational'],'topics':['climate and uncertainty','forecast communication','belief and evidence'],'forms':['croire','penser','sembler','comprendre'],'reviews':['haut','bas','monter','descendre'],'paragraphs':[
"Un média fictif prépare un article à partir de trois scénarios produits par une équipe de recherche. Le premier titre proposé dit : « Les scientifiques savent exactement ce qui va arriver ». L’éditrice le refuse parce qu’il confond la fonction d’un scénario avec une certitude. Croire une prévision n’est pas la même chose que comprendre ce qu’elle représente. Un scénario décrit ce qui pourrait se produire sous certaines conditions. Il peut sembler précis parce qu’il contient des nombres, mais cette précision visuelle ne supprime pas l’incertitude sur les hypothèses qui se trouvent derrière le calcul.",
"L’article explique ensuite pourquoi deux lecteurs peuvent penser différemment devant le même graphique. L’un regarde surtout la valeur centrale; l’autre observe l’intervalle autour de cette valeur. Si l’intervalle monte ou descend avec la tendance centrale, l’ensemble raconte une histoire différente de celle d’une seule ligne. De même, une valeur moyenne plus haut sur le graphique ne signifie pas que chaque année sera au même niveau, et une valeur plus bas ne signifie pas que le risque disparaît. Comprendre le graphique exige de séparer la direction générale de la variation possible.",
"Une scientifique interrogée propose une règle de communication : ne pas demander au public de croire un nombre isolé, mais expliquer quelles observations pourraient faire changer l’évaluation. Elle ajoute qu’une marge large ne rend pas automatiquement le modèle inutile. Parfois, l’information importante est justement que plusieurs résultats restent plausibles. Le journaliste demande alors s’il faut attendre que l’incertitude descende avant d’agir. La réponse est non : la décision dépend aussi du coût d’une erreur et de la possibilité de réviser l’action plus tard.",
"Le texte conclut qu’un bon article doit aider le lecteur à penser en scénarios plutôt qu’en promesses. Il doit montrer ce qui semble robuste, ce qui dépend d’une hypothèse et ce qui reste mal connu. Cette approche peut paraître moins simple qu’un chiffre unique, mais elle rend la décision plus intelligible. Comprendre une prévision signifie donc savoir pourquoi une estimation peut monter ou descendre, quelles conditions la déplacent du haut vers le bas d’une plage possible et pourquoi croire ou ne pas croire une conclusion ne devrait pas dépendre uniquement de la confiance dans une autorité."
],
'grammar':[{'id':'fr-b2-u05-epistemic-verbs','role':'new','description':'differentiate croire, penser, sembler and comprendre when reporting uncertain claims'}],
'discourse':[{'id':'fr-b2-u05-scenario-communication','role':'new','description':'explain central estimate, uncertainty range, assumptions and decision relevance without false certainty'}],
'items':[
('main_claim','Quelle erreur de communication le texte veut-il éviter ?','Présenter un scénario chiffré comme une certitude exacte sur l’avenir.',['croire','comprendre']),
('literal_detail','Quels éléments du graphique sont distingués ?','La valeur centrale et l’intervalle autour de cette valeur.',['haut','bas']),
('argument_relation','Pourquoi une marge large ne rend-elle pas forcément un modèle inutile ?','Parce qu’elle peut indiquer honnêtement que plusieurs résultats restent plausibles tout en donnant une information utile à la décision.',['comprendre']),
('vocabulary_in_context','Que signifie « sembler » dans ce passage ?','Donner une impression qui peut être plus forte que ce que les hypothèses permettent réellement d’affirmer.',['sembler']),
('vocabulary_in_context','Quelle différence le texte fait-il entre « croire » et « comprendre » ?','Croire renvoie à l’acceptation d’une affirmation; comprendre exige de connaître son sens, ses hypothèses et ses limites.',['croire','comprendre']),
('assumption','Quelle hypothèse soutient l’usage de plusieurs scénarios ?','Que l’avenir dépend de conditions incertaines qui peuvent conduire à des résultats différents.',['penser']),
('inference','Pourquoi agir peut-il être raisonnable avant que l’incertitude descende ?','Parce que le coût de l’inaction et la possibilité de réviser la décision comptent aussi.',['descendre']),
('reference_resolution','Dans « elle rend la décision plus intelligible », à quoi renvoie « elle » ?','À l’approche qui montre les hypothèses et les limites au lieu d’un chiffre unique.',['comprendre']),
('stance','Quelle position le texte adopte-t-il envers l’autorité scientifique ?','Il recommande d’expliquer le raisonnement et les conditions plutôt que de demander au public de croire une autorité seule.',['croire','penser']),
('summary','Résume l’analyse.','Pour comprendre plutôt que simplement croire, le lecteur doit penser aux scénarios, voir ce qui peut sembler précis sans l’être totalement et suivre comment une estimation peut monter ou descendre, du haut vers le bas de sa plage possible.',['comprendre','croire','penser','sembler','monter','descendre','haut','bas'])]},
{'id':'fr-b2-u05-p05','sequence':29,'ptype':'integration','title':'Se préparer sans prétendre connaître exactement ce que feront la mer et la terre','genre':'argument','domains':['public'],'topics':['climate and uncertainty','adaptation planning','robust action'],'forms':['préparer','action','mer','terre'],'reviews':['entrer','sortir','servir','nouveau'],'paragraphs':[
"Une commune côtière fictive discute d’un plan pour plusieurs quartiers bas. Les projections disponibles ne donnent pas une hauteur future unique de la mer. Certains élus en concluent qu’il faut attendre; d’autres veulent construire immédiatement la protection la plus coûteuse. Le document soumis au conseil défend une troisième voie : préparer des décisions qui restent utiles sous plusieurs scénarios. Une action robuste n’exige pas de connaître exactement l’avenir. Elle doit plutôt servir un besoin actuel, réduire une vulnérabilité identifiable et laisser la possibilité d’ajouter ou de modifier une mesure lorsque de nouvelles informations deviennent disponibles.",
"Le plan commence par des interventions réversibles sur la terre : améliorer les chemins d’évacuation, protéger certains équipements et éviter de placer de nouveaux services essentiels dans les zones les plus exposées. Il réserve aussi des couloirs pour une protection future si la mer atteint certains seuils. L’idée est de ne pas entrer trop tôt dans une solution irréversible, tout en évitant de sortir du débat sans rien faire. Chaque action possède donc une condition de révision : quelles observations la rendraient insuffisante, à quel moment faudrait-il passer à l’étape suivante et quel coût resterait récupérable ?",
"Un opposant affirme que cette stratégie manque d’ambition. Selon lui, un nouveau mur construit immédiatement donnerait une protection plus claire. Le rapport reconnaît cet avantage, mais répond qu’une structure fixe peut servir un scénario et être mal adaptée à un autre. La terre disponible, les accès au rivage et les usages du quartier peuvent eux aussi changer. Le choix dépend donc de la capacité à apprendre. Préparer plusieurs étapes n’est pas reporter toute décision; c’est organiser les décisions pour que les informations futures puissent encore modifier le parcours.",
"La conclusion distingue enfin prudence et passivité. La prudence demande de préciser ce que l’on sait et ce que l’on ne sait pas. La passivité utilise l’incertitude comme raison de ne rien faire. Le texte défend une action progressive : commencer par ce qui sert dans plusieurs cas, surveiller les indicateurs liés à la mer et à la terre, puis déclencher une mesure plus lourde lorsque les conditions définies sont atteintes. Un plan nouveau n’est pas meilleur parce qu’il paraît définitif. Il est meilleur s’il aide la communauté à entrer dans l’action maintenant sans l’empêcher d’en sortir ou de la transformer lorsqu’une autre réponse devient nécessaire."
],
'grammar':[{'id':'fr-b2-u05-robust-action','role':'new','description':'express staged preparation and conditional action under uncertainty with préparer, action and threshold clauses'}],
'discourse':[{'id':'fr-b2-u05-adaptive-planning','role':'new','description':'argue for staged, revisable adaptation by separating robust first steps from later thresholds'}],
'items':[
('main_claim','Quelle stratégie le texte défend-il ?','Une action progressive qui prépare plusieurs étapes utiles sous différents scénarios et définit quand les réviser.',['préparer','action']),
('literal_detail','Quelles interventions sont proposées en premier ?','Améliorer les chemins d’évacuation, protéger certains équipements et éviter de placer de nouveaux services essentiels dans les zones les plus exposées.',['terre']),
('argument_relation','Pourquoi le mur immédiat n’est-il pas automatiquement préféré ?','Parce qu’une structure fixe peut servir un scénario mais devenir mal adaptée si les conditions futures diffèrent.',['servir','mer']),
('vocabulary_in_context','Que signifie « préparer » ici ?','Organiser à l’avance des choix, seuils et étapes sans prétendre connaître exactement le futur.',['préparer']),
('vocabulary_in_context','Quel rôle joue « action » dans l’argument ?','Elle désigne une mesure concrète qui peut commencer maintenant et être révisée plus tard.',['action']),
('assumption','Quelle hypothèse soutient la stratégie progressive ?','Que de nouvelles informations arriveront et qu’il est utile de conserver la capacité de modifier la réponse.',['préparer']),
('inference','Pourquoi réserver des couloirs dès maintenant ?','Pour garder une option future sans devoir construire immédiatement la protection la plus lourde.',['terre']),
('reference_resolution','Dans « elle doit plutôt servir un besoin actuel », à quoi renvoie « elle » ?','À une action robuste.',['action','servir']),
('stance','Quelle position le texte adopte-t-il envers l’incertitude ?','Il refuse qu’elle serve d’excuse à l’inaction et l’utilise pour structurer une réponse révisable.',['action','préparer']),
('summary','Résume le plan.','La commune veut préparer une action progressive autour de la mer et de la terre : entrer dans des mesures utiles maintenant, faire servir chaque étape à plusieurs scénarios, puis sortir ou modifier un choix lorsque de nouvelles conditions rendent nécessaire un plan nouveau.',['préparer','action','mer','terre','entrer','servir','sortir','nouveau'])]}
]
CHECKPOINT={'id':'fr-b2-u05-p06','sequence':30,'ptype':'checkpoint','title':'De l’observation à l’action : raisonner quand le futur reste incertain','genre':'B2 cumulative uncertainty checkpoint','domains':['public','educational'],'topics':['climate and uncertainty','evidence','synthesis'],'paragraphs':[
"L’unité commence par une règle de temps. Un été, une année, un mois ou une nuit peuvent fournir une observation utile sans suffire à décrire une évolution durable. Il faut comparer plusieurs périodes et expliquer jusqu’où les données portent. Une série longue peut mieux décrire le passé, mais ce qui a changer ne garantit pas que la même évolution va continuer. Le raisonnement doit donc distinguer observation, comparaison et projection. Cette distinction permet de parler d’incertitude sans transformer chaque limite en argument pour ignorer le signal.",
"Le deuxième principe concerne l’interprétation. Compter des événements peut montrer qu’un phénomène devient plus fréquent, mais la cause peut rester ouverte. Tester plusieurs choix méthodologiques aide à voir ce qui reste robuste. De même, croire un scénario n’est pas la même chose que le comprendre. Un résultat peut sembler très précis parce qu’il contient des nombres. Pour penser correctement l’incertitude, il faut demander quelles hypothèses sont utilisées, quelles observations pourraient faire changer l’estimation et pourquoi plusieurs résultats restent plausibles.",
"La troisième étape concerne la décision. Se préparer ne signifie pas attendre une certitude parfaite. Une action peut être utile si elle répond à plusieurs scénarios et garde des possibilités de révision. Dans un cas côtier fictif, la mer et la terre ne sont pas traitées comme des données parfaitement prévisibles. Elles servent à définir des seuils, des étapes et des choix réversibles. L’objectif est de commencer par une mesure qui aide maintenant tout en laissant la décision future bénéficier de nouvelles informations.",
"Ainsi, le raisonnement sous incertitude ne cherche ni la certitude absolue ni l’ignorance confortable. Il demande ce qui a été observé, ce qui pourrait continuer, ce qui semble seulement plausible et ce qu’une action doit accomplir malgré les limites. Un bon résumé précise le temps étudié, ce qu’il faut compter, ce que les données peuvent montrer, ce qui peut devenir plus clair, ce qu’il est raisonnable de croire ou penser, et ce qu’il reste à comprendre. Il relie enfin la connaissance à la capacité de préparer une réponse proportionnée plutôt qu’une promesse impossible sur l’avenir."
],
'grammar':[{'id':'fr-b2-u05-uncertainty-synthesis','role':'review','description':'synthesize temporal scope, epistemic verbs, conditional continuation and staged action'}],
'discourse':[{'id':'fr-b2-u05-evidence-action-synthesis','role':'review','description':'connect observation, robustness, uncertainty communication and adaptive decision-making'}],
'items':[
('main_claim','Quelle démarche générale la synthèse défend-elle ?','Séparer observation, interprétation, projection et décision, puis ajuster chaque affirmation ou action au niveau d’incertitude.',['comprendre','action']),
('argument_relation','Quel lien unit la série longue et les tests de robustesse ?','Tous deux cherchent à vérifier qu’une conclusion ne dépend pas d’une seule période ou d’un seul choix méthodologique.',['long','rester']),
('cross_text_synthesis','Comment croire, sembler et montrer se distinguent-ils ?','Montrer renvoie à ce que les données soutiennent; sembler à une impression; croire à l’acceptation d’une conclusion qui doit encore être comprise.',['croire','sembler','montrer','comprendre']),
('assumption','Pourquoi une action révisable peut-elle commencer avant la certitude ?','Parce qu’elle peut être utile dans plusieurs scénarios tout en laissant de nouvelles informations modifier l’étape suivante.',['préparer','action']),
('inference','Pourquoi le texte insiste-t-il sur plusieurs unités de temps ?','Pour empêcher qu’un événement court soit confondu avec une tendance durable.',['été','année','mois','nuit']),
('reference_resolution','Dans « Elles servent à définir des seuils », que désigne « Elles » ?','La mer et la terre dans le scénario côtier fictif.',['mer','terre']),
('stance','Quelle position la synthèse adopte-t-elle envers l’incertitude ?','Elle la traite comme une propriété à décrire et gérer, non comme une preuve que tout est inconnaissable.',['penser','comprendre']),
('vocabulary_in_context','Pourquoi « continuer » est-il conditionnel dans l’unité ?','Parce qu’une tendance passée peut se poursuivre seulement si les facteurs importants restent suffisamment comparables.',['continuer','passé']),
('synthesis','Comment compter et préparer appartiennent-ils à la même chaîne de raisonnement ?','Compter aide à caractériser les observations; préparer transforme ensuite cette information imparfaite en options d’action révisables.',['compter','préparer']),
('summary','Résume l’unité en une phrase.','Un été, une année, un mois ou une nuit s’inscrivent dans un passé plus long qui peut changer ou continuer; pour voir ce qui va rester ou devenir important, il faut compter et montrer les données, distinguer croire, penser, sembler et comprendre, puis préparer une action proportionnée autour de la mer et de la terre.',['été','année','mois','nuit','passé','long','changer','continuer','rester','devenir','compter','montrer','croire','penser','sembler','comprendre','préparer','action','mer','terre'])]}
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);text=text_of(s)
 return {'id':s['id'],'language':'fr','cefr':'B2','unit':5,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 05 guarded production batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 05: climate and uncertainty.','Accepted B2 default four fresh targets per P01-P05; P06 zero new.','All datasets and civic scenarios are fictional/generic.']},'paired_text_group':None,'prerequisites':['French B2 Units 01-04 canonical and Unit04 frontier lock PASS'],'difficulty_notes_internal':'B2 uncertainty reasoning: evidence scope, robustness, projection limits, epistemic language and adaptive decisions.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b2_u05']}
def main():
 for lab,p in [('A1',A1),('A2',A2),('B1',B1),('B2',CANON)]:
  got=subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
  if got!=EXPECTED[lab]:raise AssertionError(f'{lab} blob drift: {got}')
 lock=json.loads(LOCK.read_text(encoding='utf-8'));probe=json.loads(PROBE.read_text(encoding='utf-8'))
 if lock.get('status')!='PASS' or lock.get('canonical_blob')!=EXPECTED['B2'] or lock.get('last_sequence')!=24:raise AssertionError('Unit04 lock mismatch')
 if probe.get('status')!='PASS' or probe.get('b2_source_blob')!=EXPECTED['B2']:raise AssertionError('Unit05 probe stale')
 fresh={x['form'] for x in probe.get('fresh',[])}
 if any(f not in fresh for f in FORMS):raise AssertionError('selected target absent from fresh Unit05 probe')
 load=lambda p:[json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()];a1,a2,b1,b2=map(load,(A1,A2,B1,CANON));deck=base.deck();prior=base.prior(a1+a2+b1+b2);pid={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};pf={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 if len(b2)!=24 or b2[-1]['id']!='fr-b2-u04-p06':raise AssertionError('unexpected B2 frontier')
 unit=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,deck) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};unit.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,deck) for f in FORMS];ids={t['form']:t['id'] for t in reviews};unit.append(mk(CHECKPOINT,[],reviews,ids,True));V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));newids=[];newforms=[]
 if [r['sequence'] for r in unit]!=list(range(25,31)):raise AssertionError('Unit05 sequence failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
  if not 350<=r['word_count']<=550:raise AssertionError(f"{r['id']}: word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  if r['sequence']<=29 and len(r['new_lexical_targets'])!=4:raise AssertionError(f"{r['id']}: expected four new")
  if r['sequence']==30 and r['new_lexical_targets']:raise AssertionError('P06 must have zero new')
  local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[])};amap={a['question_id']:a['id'] for a in r['answer_key']}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in local for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage failure")
  for t in r['new_lexical_targets']:
   src=deck.get(t['form'])
   if t['id'] in pid or t['form'] in pf or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: new target drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20:raise AssertionError('Unit05 target uniqueness failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b2+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':5,'theme':'climate and uncertainty','b2_passages':30,'questions':60,'answers':60,'new_targets':20,'word_counts':{r['id']:r['word_count'] for r in unit}},ensure_ascii=False))
if __name__=='__main__':main()
