#!/usr/bin/env python3
"""Append French B2 Unit07 (seq37-42): arts and interpretation."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
R=Path(__file__).resolve().parents[2];A1=R/'reading/french/a1/passages.jsonl';A2=R/'reading/french/a2/passages.jsonl';B1=R/'reading/french/b1/passages.jsonl';CANON=R/'reading/french/b2/passages.jsonl';SCHEMA=R/'reading/schema/passage.schema.json';LOCK=R/'reading/audit/french_b2_unit06_frontier_lock.json';PROBE=R/'reading/audit/french_b2_unit07_target_probe.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca','B2':'939ec4d433c8b5a8893093eca6f8e8a90ff2c1d4'}
FORMS=('film','musique','chanson','jouer','histoire','lire','écrire','mot','ton','sens','sujet','imaginer','avis','aimer','beau','drôle','vie','présent','société','politique')
SPECS=[
{'id':'fr-b2-u07-p01','sequence':37,'ptype':'instructional','title':'Critiquer un film en séparant ce que la musique fait de ce que le récit affirme','genre':'review','domains':['educational','public'],'topics':['arts and interpretation','film review','sound and narrative'],'forms':['film','musique','chanson','jouer'],'reviews':['téléphone','compte','message','adresse'],'paragraphs':[
"Une revue fictive analyse un film dans lequel deux amis traversent une ville pendant une nuit de panne générale. Le critique refuse de résumer l’expérience par l’intrigue seule. La musique change la manière dont certaines scènes sont perçues : une chanson légère accompagne parfois une situation tendue, tandis qu’un long silence rend un geste ordinaire plus inquiétant. Le texte demande donc ce que la bande sonore fait au spectateur. Elle ne prouve pas ce que les personnages pensent, mais elle peut jouer avec leurs paroles et créer une distance entre ce qui est montré et ce que l’on ressent.",
"La revue prend un exemple précis. Dans une scène, l’un des personnages reçoit sur son téléphone un message contenant une adresse. Le film ne montre pas immédiatement qui l’a envoyé. Au même moment, une chanson joyeuse commence. Certains spectateurs peuvent y entendre une promesse de sécurité; d’autres y voient une ironie, car l’image reste sombre. Le critique insiste sur cette différence : la musique ne possède pas un compte secret de la vérité du récit. Elle oriente l’attention, mais son effet dépend de la relation entre image, parole, rythme et attente.",
"Un autre passage montre les deux amis qui essaient de jouer quelques notes sur un vieux piano dans un hall vide. La scène pourrait sembler inutile si l’on cherche seulement les événements qui font avancer l’action. Pourtant, la revue soutient qu’elle ralentit volontairement le film pour montrer leur relation. Le spectateur apprend moins par une explication que par la durée, les hésitations et la manière dont chacun écoute la musique de l’autre. La chanson entendue plus tôt revient ensuite sans paroles, ce qui transforme son effet sans changer sa mélodie principale.",
"La conclusion adopte une position mesurée. Une critique peut proposer une interprétation de la musique, mais elle doit distinguer les indices du film de ce qu’elle imagine. Dire que la chanson produit un contraste est défendable si l’on décrit les scènes; dire qu’elle signifie nécessairement une seule chose serait plus fragile. Le critique conseille donc de citer le moment, le geste ou le son qui soutient chaque lecture. Comme une adresse ou un message numérique, un détail artistique acquiert sa valeur par le contexte où il apparaît, pas parce qu’il contient seul toute la réponse."
],
'grammar':[{'id':'fr-b2-u07-review-evidence','role':'new','description':'qualify interpretation using peut, pourrait, nécessairement and evidence clauses'}],
'discourse':[{'id':'fr-b2-u07-film-review','role':'new','description':'separate description, formal effect, interpretation and stronger/weaker claims in a review'}],
'items':[
('main_claim','Quelle méthode de critique le texte défend-il ?','Relier l’interprétation à des détails précis du film tout en distinguant l’effet possible d’une signification unique.',['film','musique']),
('literal_detail','Quel élément les personnages reçoivent-ils sur le téléphone ?','Un message contenant une adresse.',['téléphone','message','adresse']),
('argument_relation','Pourquoi la chanson joyeuse ne possède-t-elle pas une signification certaine ?','Parce que son effet dépend du contraste avec l’image, la situation et l’attente du spectateur.',['chanson','musique']),
('vocabulary_in_context','Que signifie « jouer » dans la scène du piano ?','Produire quelques notes avec l’instrument, tout en interagissant avec l’autre personnage.',['jouer']),
('vocabulary_in_context','Quel rôle joue la « musique » selon la revue ?','Elle oriente l’attention et transforme la perception sans prouver à elle seule une lecture.',['musique']),
('assumption','Quelle hypothèse soutient l’analyse du retour de la chanson sans paroles ?','Que la répétition d’un élément dans un autre contexte peut modifier son effet sur le spectateur.',['chanson']),
('inference','Pourquoi la scène du piano peut-elle être importante malgré son faible effet sur l’action ?','Parce qu’elle développe la relation des personnages par le temps, les gestes et l’écoute.',['film','jouer']),
('reference_resolution','Dans « elle oriente l’attention », à quoi renvoie « elle » ?','À la musique ou à la chanson dans la scène.',['musique']),
('stance','Quelle position la revue adopte-t-elle envers une lecture unique ?','Elle la juge trop forte lorsque le film permet plusieurs interprétations soutenues par les mêmes détails.',['film']),
('summary','Résume la critique.','Le film utilise musique, chanson et moments où les personnages vont jouer pour produire des effets interprétables; comme un téléphone, compte, message ou adresse ne suffit pas seul à expliquer une situation, chaque détail doit être replacé dans son contexte.',['film','musique','chanson','jouer','téléphone','compte','message','adresse'])]},
{'id':'fr-b2-u07-p02','sequence':38,'ptype':'reinforcement','title':'Profil d’une romancière fictive : lire sa vie ne suffit pas à expliquer chaque mot','genre':'profile','domains':['educational','public'],'topics':['arts and interpretation','writer profile','biography and text'],'forms':['histoire','lire','écrire','mot'],'reviews':['photo','nom','visage','voix'],'paragraphs':[
"Un magazine fictif présente Nora Delmas, une romancière imaginaire qui a commencé à écrire après plusieurs années de travail dans une gare. Le profil raconte cette histoire parce qu’elle éclaire certains choix de décor et de rythme, mais il refuse de transformer chaque détail de sa vie en clé automatique. Lire un roman après avoir connu une biographie peut changer l’attention du lecteur; cela ne signifie pas que chaque mot correspond directement à une expérience réelle. Le texte distingue donc contexte biographique, choix d’écriture et interprétation du public.",
"Le magazine décrit aussi les archives préparées pour l’entretien : une photo ancienne, un carnet portant son nom, un enregistrement de sa voix et plusieurs brouillons. Son visage sur une image confirme sa présence dans un lieu, mais ne dit pas ce qu’elle pensait. De même, sa voix peut révéler un ton pendant l’entretien sans prouver comment il faut lire une scène inventée. Nora explique qu’elle aime écrire à partir de lieux observés, puis modifier les relations et les événements jusqu’à ce que l’histoire acquière sa propre logique.",
"Le profil suit ensuite un passage réécrit trois fois. Dans le premier brouillon, un personnage dit beaucoup de choses; dans le dernier, plusieurs phrases disparaissent et un seul mot reste au centre de la scène. Le journaliste demande si ce mot vient d’un souvenir personnel. Nora répond qu’il vient surtout du besoin de rendre la scène plus courte et plus tendue. Cet échange montre l’intérêt mais aussi la limite du profil : connaître la vie d’une personne peut aider à poser des questions, sans remplacer l’analyse de ce qu’elle choisit réellement d’écrire.",
"La conclusion conseille donc une lecture à deux niveaux. On peut lire la biographie pour comprendre les conditions d’un travail, puis lire le texte pour observer ses propres structures. Une histoire de vie peut expliquer pourquoi certains sujets sont proches de l’écrivaine; elle ne décide pas du sens de chaque mot. Le profil est utile lorsqu’il ouvre des pistes et indique ses limites. Il devient moins fiable lorsqu’il traite une photo, un nom, un visage ou une voix comme une preuve totale de l’intention artistique."
],
'grammar':[{'id':'fr-b2-u07-biography-limit','role':'new','description':'contrast biography and textual evidence with peut aider sans, ne suffit pas à and de même'}],
'discourse':[{'id':'fr-b2-u07-profile-context','role':'new','description':'use profile evidence to contextualize artistic choices without reducing a text to biography'}],
'items':[
('main_claim','Quelle limite le profil impose-t-il à la biographie ?','La vie de l’écrivaine peut éclairer un contexte sans expliquer automatiquement chaque choix du texte.',['histoire','lire','écrire']),
('literal_detail','Quels documents sont mentionnés pour l’entretien ?','Une photo, un carnet portant son nom, un enregistrement de sa voix et plusieurs brouillons.',['photo','nom','voix']),
('argument_relation','Pourquoi le dernier brouillon est-il important ?','Il montre qu’un mot peut résulter d’un choix de rythme et de tension plutôt que d’un souvenir biographique direct.',['mot','écrire']),
('vocabulary_in_context','Que signifie « lire » dans la conclusion ?','Examiner séparément la biographie puis le texte afin de comprendre leurs apports différents.',['lire']),
('vocabulary_in_context','Quel rôle joue « histoire » ?','Le mot désigne à la fois le parcours biographique évoqué et le récit construit, distinction que le profil doit maintenir.',['histoire']),
('assumption','Quelle hypothèse soutient la lecture à deux niveaux ?','Que le contexte de vie et l’organisation du texte apportent des informations différentes et complémentaires.',['lire']),
('inference','Pourquoi une photo ne suffit-elle pas à établir une intention ?','Parce qu’elle montre une présence ou un contexte sans révéler directement la pensée qui a produit une scène.',['photo','visage']),
('reference_resolution','Dans « elle ne décide pas du sens », à quoi renvoie « elle » ?','À l’histoire de vie ou à la biographie.',['histoire']),
('stance','Quelle position le profil adopte-t-il envers les archives personnelles ?','Il les juge utiles pour poser des questions, mais insuffisantes pour déterminer seules l’interprétation.',['nom','voix']),
('summary','Résume le profil.','Pour comprendre une histoire, il faut lire ce qui est écrit et observer comment un mot fonctionne; photo, nom, visage et voix peuvent contextualiser la vie d’une personne, mais ne disent pas automatiquement pourquoi elle choisit d’écrire ainsi.',['histoire','lire','écrire','mot','photo','nom','visage','voix'])]},
{'id':'fr-b2-u07-p03','sequence':39,'ptype':'interleaved','title':'Le ton change-t-il le sens, ou le lecteur imagine-t-il ce que le texte ne dit pas ?','genre':'critical reading','domains':['educational'],'topics':['arts and interpretation','tone','interpretive inference'],'forms':['ton','sens','sujet','imaginer'],'reviews':['contrôler','suivre','connaître','cacher'],'paragraphs':[
"Un atelier fictif compare deux lectures d’un court récit. Dans la dernière scène, une sœur dit seulement : « Tu es enfin arrivé. » Aucun mot ne précise si elle est soulagée, fâchée ou amusée. Le premier lecteur affirme que le ton est froid parce que la scène précédente décrit une longue attente. Le second entend au contraire une forme de tendresse. L’exercice demande alors où se trouve le sens : dans les mots eux-mêmes, dans les indices autour d’eux ou dans ce que chaque lecteur vient imaginer à partir de son expérience.",
"L’enseignante ne cherche pas à contrôler une réponse unique. Elle demande aux étudiants de suivre les références présentes dans le récit : gestes, pauses, descriptions et événements antérieurs. Il faut connaître ce que le texte donne avant d’ajouter une hypothèse. Un lecteur peut proposer que la sœur veut cacher sa colère, mais cette lecture devient plus forte s’il existe un geste ou une phrase qui la soutient. Le sujet de l’exercice n’est donc pas de supprimer l’imagination; il est de distinguer une possibilité intéressante d’une affirmation présentée comme certaine.",
"Les étudiants testent ensuite le même dialogue avec trois manières de le lire à voix haute. Le ton transforme fortement l’impression, alors que les mots restent identiques. Cela montre qu’une performance peut ajouter de l’information. Mais l’atelier rappelle qu’un lecteur silencieux ne reçoit pas nécessairement ce ton précis. Pour imaginer la scène, il doit combiner les indices disponibles. Le sens est donc construit sous contrainte : plusieurs lectures peuvent être possibles, sans que toutes soient également soutenues par le récit.",
"La conclusion propose une méthode. D’abord, dire ce qui est explicitement présent. Ensuite, suivre les indices qui relient la scène au reste du texte. Puis présenter l’interprétation comme une hypothèse et expliquer ce qui pourrait la contredire. Cette démarche empêche de cacher une préférence personnelle derrière une certitude. Elle ne donne pas au lecteur le pouvoir de contrôler tout le sens, mais elle l’aide à connaître la différence entre ce que le récit affirme, ce qu’il suggère et ce qu’il faut encore imaginer."
],
'grammar':[{'id':'fr-b2-u07-interpretive-modality','role':'new','description':'mark degrees of interpretation with peut, pourrait, nécessairement and supported-by clauses'}],
'discourse':[{'id':'fr-b2-u07-tone-meaning','role':'new','description':'distinguish explicit content, contextual clues, performance additions and reader inference'}],
'items':[
('main_claim','Quelle conception du sens l’atelier défend-il ?','Le sens se construit à partir du texte et des inférences du lecteur, mais ces inférences doivent rester contraintes par des indices.',['sens','imaginer']),
('literal_detail','Quelle phrase les étudiants interprètent-ils ?','« Tu es enfin arrivé. »',['ton']),
('argument_relation','Pourquoi les lectures à voix haute sont-elles comparées ?','Pour montrer que le ton peut ajouter de l’information même lorsque les mots restent identiques.',['ton','sens']),
('vocabulary_in_context','Que signifie « sujet » dans l’exercice ?','La question centrale étudiée : comment distinguer une interprétation possible d’une affirmation certaine.',['sujet']),
('vocabulary_in_context','Que signifie « imaginer » ici ?','Construire une représentation ou hypothèse qui dépasse ce qui est explicitement dit.',['imaginer']),
('assumption','Quelle hypothèse soutient l’usage des indices ?','Que les éléments du récit limitent et hiérarchisent les interprétations possibles.',['suivre','connaître']),
('inference','Pourquoi l’enseignante refuse-t-elle de contrôler une réponse unique ?','Parce que plusieurs tons et lectures peuvent rester compatibles avec les indices disponibles.',['contrôler','ton']),
('reference_resolution','Dans « elle doit combiner les indices », à qui renvoie « elle » ?','À la personne qui lit silencieusement et doit imaginer la scène.',['imaginer']),
('stance','Quelle position le texte adopte-t-il envers la préférence personnelle ?','Elle peut lancer une hypothèse, mais ne doit pas être cachée derrière une prétendue certitude.',['cacher']),
('summary','Résume la méthode.','Pour étudier ton, sens et sujet, le lecteur peut imaginer plusieurs lectures, mais il doit suivre les indices, connaître ce qui est explicite, éviter de cacher sa préférence et renoncer à contrôler artificiellement une réponse unique.',['ton','sens','sujet','imaginer','suivre','connaître','cacher','contrôler'])]},
{'id':'fr-b2-u07-p04','sequence':40,'ptype':'transfer','title':'Deux critiques, deux avis : faut-il aimer ce qui est beau ou ce qui est drôle ?','genre':'critical comparison','domains':['public','educational'],'topics':['arts and interpretation','critical comparison','evaluation criteria'],'forms':['avis','aimer','beau','drôle'],'reviews':['client','bureau','demander','répondre'],'paragraphs':[
"Deux critiques fictifs évaluent la même exposition de dessins humoristiques. Le premier avis insiste sur la précision des compositions et décrit plusieurs images comme très belles. La seconde critique dit qu’elle ne cherche pas surtout le beau : elle veut savoir si l’exposition est drôle, surprenante et capable de modifier le regard sur des situations ordinaires. Les deux textes aiment certaines pièces, mais ils ne les aiment pas pour les mêmes raisons. La comparaison doit donc identifier les critères avant de décider quel jugement paraît le mieux soutenu.",
"Le premier critique travaille pour un magazine dont le client principal est un réseau de galeries. Il n’est pas obligé d’adopter leur opinion, mais le contexte peut conduire le lecteur à demander comment les pièces ont été choisies. La seconde travaille dans un bureau culturel universitaire et répond surtout à un public étudiant. Là encore, l’institution ne détermine pas son avis. Le texte recommande simplement de connaître le contexte de publication, puis de vérifier si chaque critique répond réellement aux caractéristiques observables des images.",
"Un exemple montre la différence. Une image représente une salle extrêmement ordonnée où un seul objet est placé de travers. Le premier critique admire l’équilibre visuel et la trouve belle. La seconde la trouve drôle parce que le petit désordre devient exagérément important dans un cadre si contrôlé. Ces lectures ne s’annulent pas. On peut aimer la composition et rire de son idée en même temps. La question critique consiste à demander quelles propriétés servent de preuve à chaque jugement et si le texte explique suffisamment le passage de l’observation à l’évaluation.",
"La conclusion refuse de choisir un vainqueur uniquement selon le goût. Un avis devient plus utile lorsqu’il précise ce qu’il valorise et répond aux objections possibles. Dire « c’est beau » ou « c’est drôle » peut exprimer une réaction sincère; une critique B2 doit aller plus loin et montrer pourquoi. Le lecteur peut alors demander si le critère est cohérent, comparer les exemples et décider s’il veut aimer l’exposition pour les mêmes raisons. Le contexte du client ou du bureau reste pertinent, mais l’argument doit finalement répondre aux détails qu’il prétend évaluer."
],
'grammar':[{'id':'fr-b2-u07-evaluation-criteria','role':'new','description':'compare evaluative criteria using beau, drôle, aimer, selon and reason clauses'}],
'discourse':[{'id':'fr-b2-u07-critical-comparison','role':'new','description':'compare two critics by criteria, evidence, institutional context and response to objections'}],
'items':[
('main_claim','Que doit faire une bonne comparaison critique selon le texte ?','Identifier les critères de chaque avis, vérifier leurs exemples et distinguer contexte institutionnel et force de l’argument.',['avis']),
('literal_detail','Quels critères principaux opposent les deux critiques ?','Le premier insiste sur le beau et la composition; la seconde sur le caractère drôle et le changement de regard.',['beau','drôle']),
('argument_relation','Pourquoi le client ou le bureau sont-ils mentionnés ?','Pour contextualiser la publication sans supposer qu’ils déterminent automatiquement le jugement.',['client','bureau']),
('vocabulary_in_context','Que signifie « aimer » dans la comparaison ?','Évaluer positivement une pièce ou l’exposition, éventuellement pour des raisons différentes.',['aimer']),
('vocabulary_in_context','Que signifie « avis » ici ?','Un jugement critique accompagné de critères et, idéalement, de raisons.',['avis']),
('assumption','Quelle hypothèse soutient la comparaison des exemples ?','Qu’un jugement critique devient plus évaluables lorsque ses raisons peuvent être reliées à des détails précis.',['beau','drôle']),
('inference','Pourquoi les deux lectures de l’image ne s’annulent-elles pas ?','Parce qu’une même composition peut être appréciée pour sa beauté et son effet humoristique.',['aimer','beau','drôle']),
('reference_resolution','Dans « il précise ce qu’il valorise », à quoi renvoie « il » ?','À un avis critique devenu plus explicite et utile.',['avis']),
('stance','Quelle position le texte adopte-t-il envers le goût personnel ?','Il reconnaît sa présence mais demande de répondre par des raisons lorsqu’on formule une critique.',['demander','répondre']),
('summary','Résume la comparaison.','Deux avis peuvent aimer différemment ce qui est beau ou drôle; le lecteur doit demander quelles raisons soutiennent chaque jugement, voir comment client et bureau contextualisent les textes et vérifier si les critiques répondent réellement aux exemples.',['avis','aimer','beau','drôle','demander','client','bureau','répondre'])]},
{'id':'fr-b2-u07-p05','sequence':41,'ptype':'integration','title':'Une création dans la vie publique : le présent transforme-t-il une lecture sociale en lecture politique ?','genre':'profile and critical context','domains':['public','educational'],'topics':['arts and interpretation','social context','political interpretation'],'forms':['vie','présent','société','politique'],'reviews':['vendre','chercher','trouver','monde'],'paragraphs':[
"Un dossier fictif présente une installation composée de centaines de tickets de transport récupérés. La créatrice explique qu’elle voulait parler de la vie quotidienne : attendre, se déplacer, perdre du temps, rencontrer des inconnus. Au présent, cependant, plusieurs critiques lisent aussi l’installation comme un commentaire sur les inégalités de mobilité dans la société. Certains vont plus loin et la qualifient de politique. Le dossier ne cherche pas à interdire ce vocabulaire; il demande quelles étapes permettent de passer d’un objet ordinaire à une interprétation sociale, puis d’une lecture sociale à une lecture politique.",
"Le profil de la créatrice apporte un contexte sans résoudre la question. Elle a travaillé longtemps dans différents quartiers et dit avoir commencé par chercher des traces de trajets ordinaires. Elle ne voulait pas vendre un programme politique ni trouver une réponse unique sur le monde. Pourtant, l’absence d’une intention déclarée n’empêche pas une création d’être discutée dans la société. Une interprétation peut s’appuyer sur des effets, des choix de lieu ou des contrastes que la créatrice n’avait pas formulés explicitement.",
"Le dossier compare alors deux arguments. Le premier dit que l’installation devient politique dès qu’elle montre une différence de ressources ou d’accès. Le second réserve ce terme aux situations où la création intervient dans un débat sur des décisions collectives. Les deux lectures observent les mêmes tickets, mais elles définissent différemment le seuil. Pour trouver un terrain commun, le dossier propose de distinguer sujet, effet et position : une création peut traiter la vie sociale, produire un effet politique dans le présent et ne pas défendre pour autant une politique précise.",
"La conclusion insiste sur cette précision. Le monde de l’art n’est pas séparé du reste de la société, mais toute référence à la vie commune ne devient pas automatiquement un programme politique. Une critique doit chercher les indices qui soutiennent le mot choisi et indiquer le niveau de sa conclusion. Elle peut trouver des dimensions politiques là où la créatrice parlait d’abord du quotidien, à condition d’expliquer le chemin interprétatif. Même lorsqu’une installation peut se vendre, sa valeur critique ne se réduit pas au marché; elle dépend aussi de ce qu’elle rend visible dans le présent."
],
'grammar':[{'id':'fr-b2-u07-social-political','role':'new','description':'qualify movement from social observation to political interpretation with peut, dès que, ne...pas automatiquement'}],
'discourse':[{'id':'fr-b2-u07-context-interpretation','role':'new','description':'separate creator intention, social effect, political label and market context'}],
'items':[
('main_claim','Quelle distinction centrale le dossier propose-t-il ?','Une création peut parler de la vie sociale ou produire un effet politique sans défendre nécessairement une politique précise.',['vie','société','politique']),
('literal_detail','De quoi l’installation fictive est-elle composée ?','De centaines de tickets de transport récupérés.',['vie']),
('argument_relation','Pourquoi l’intention de la créatrice ne ferme-t-elle pas l’interprétation ?','Parce que le contexte, les effets et les contrastes peuvent soutenir des lectures qu’elle n’avait pas formulées.',['présent','société']),
('vocabulary_in_context','Que signifie « politique » dans le débat ?','Un rapport possible aux décisions collectives, aux ressources ou aux rapports sociaux, selon le seuil retenu.',['politique']),
('vocabulary_in_context','Quel rôle joue « présent » ?','Il désigne le contexte actuel dans lequel l’installation est reçue et peut acquérir de nouvelles significations.',['présent']),
('assumption','Quelle hypothèse soutient une lecture sociale non prévue par la créatrice ?','Qu’une création peut produire des effets interprétatifs au-delà de l’intention explicitement déclarée.',['société']),
('inference','Pourquoi le marché est-il mentionné à la fin ?','Pour distinguer la possibilité de vendre une création de la manière dont sa valeur critique est interprétée.',['vendre']),
('reference_resolution','Dans « elles définissent différemment le seuil », à quoi renvoie « elles » ?','Aux deux lectures ou aux deux lignes d’argument sur ce qui rend une création politique.',['politique']),
('stance','Quelle position le dossier adopte-t-il envers l’étiquette politique ?','Il l’accepte lorsqu’elle est argumentée, mais refuse de l’appliquer automatiquement à toute référence à la vie sociale.',['politique','vie']),
('summary','Résume le dossier.','Dans le présent, une création sur la vie peut être lue à travers la société ou la politique; le critique doit chercher et trouver les indices plutôt que prétendre connaître tout le monde, et distinguer cette lecture de la question de vendre l’objet.',['présent','vie','société','politique','chercher','trouver','monde','vendre'])]}
]
CHECKPOINT={'id':'fr-b2-u07-p06','sequence':42,'ptype':'checkpoint','title':'Interpréter sans inventer la preuve : cinq chemins entre forme, contexte et jugement','genre':'B2 cumulative interpretation checkpoint','domains':['educational','public'],'topics':['arts and interpretation','synthesis','critical method'],'paragraphs':[
"Les cinq textes montrent qu’interpréter ne signifie ni répéter une description ni inventer librement une réponse. Dans le film, la musique et une chanson peuvent modifier la perception d’une scène, tandis qu’un personnage peut jouer quelques notes sans que ce geste possède une signification unique. Dans le profil de la romancière, une histoire de vie aide à poser des questions, mais il faut encore lire le texte, voir comment elle choisit d’écrire et comprendre pourquoi un mot a été gardé. Le contexte ouvre des pistes; il ne décide pas seul.",
"L’exercice sur le dialogue ajoute la question du ton. Le sens d’une phrase dépend en partie de ce qui est dit, du sujet, des indices autour de la scène et de ce que le lecteur vient imaginer. Une interprétation devient plus forte lorsqu’elle distingue ces niveaux. La comparaison de deux critiques ajoute un autre problème : un avis peut aimer une image parce qu’elle paraît belle, tandis qu’un autre la trouve surtout drôle. Le désaccord devient analysable lorsque chaque jugement explique son critère et répond aux exemples.",
"Le dernier dossier élargit l’échelle. La vie quotidienne peut être représentée dans le présent puis discutée comme un phénomène de société ou comme une question politique. Le critique doit alors préciser le passage d’un niveau à l’autre. Il peut chercher un indice, trouver un contraste et proposer une lecture du monde sans prétendre que l’intention de la créatrice contient déjà toute la réponse. De même, la possibilité de vendre une création ne fixe ni sa valeur esthétique ni sa portée sociale.",
"La synthèse propose donc une procédure. D’abord décrire ce qui est présent. Ensuite distinguer forme, contexte et effet. Puis formuler le jugement avec un degré de certitude proportionné aux indices. Enfin, comparer les lectures en demandant ce qu’elles expliquent mieux ou moins bien. Cette méthode permet de lire, écrire et discuter avec précision sans réduire l’interprétation à un mot de goût. Elle aide à voir pourquoi un film, une musique, une chanson, un ton ou un avis peut produire plusieurs sens, tout en exigeant que l’on puisse raconter le chemin qui mène de l’observation à l’argument."
],
'grammar':[{'id':'fr-b2-u07-interpretation-synthesis','role':'review','description':'synthesize modal interpretation, evaluative comparison and context-to-claim qualification'}],
'discourse':[{'id':'fr-b2-u07-critical-method-synthesis','role':'review','description':'integrate formal evidence, biography, inference, evaluative criteria and social/political context'}],
'items':[
('main_claim','Quelle procédure générale la synthèse défend-elle ?','Décrire, distinguer forme/contexte/effet, formuler une interprétation proportionnée aux indices puis comparer les lectures.',['sens','avis']),
('argument_relation','Quel lien unit le film et le profil de la romancière ?','Tous deux montrent qu’un contexte ou un détail oriente l’interprétation sans fournir automatiquement une signification unique.',['film','histoire']),
('cross_text_synthesis','Comment ton, beau et politique illustrent-ils le même problème critique ?','Ce sont des catégories interprétatives qui exigent des critères et des indices plutôt qu’une simple affirmation.',['ton','beau','politique']),
('assumption','Pourquoi plusieurs lectures peuvent-elles rester acceptables ?','Parce que les mêmes éléments peuvent soutenir des effets différents tant que chaque lecture respecte les contraintes du texte ou de l’objet.',['imaginer','sens']),
('inference','Pourquoi le fait de vendre une création ne décide-t-il pas de sa valeur critique ?','Parce que le marché est un contexte parmi d’autres et ne remplace pas l’analyse de la forme, du sujet ou de l’effet.',['vendre','sujet']),
('reference_resolution','Dans « elles expliquent mieux ou moins bien », à quoi renvoie « elles » ?','Aux différentes lectures ou interprétations comparées.',['lire']),
('stance','Quelle position la synthèse adopte-t-elle envers le goût personnel ?','Elle l’accepte comme point de départ possible mais exige un avis argumenté lorsque le jugement devient critique.',['aimer','avis']),
('vocabulary_in_context','Pourquoi « imaginer » n’est-il pas opposé à la rigueur ?','Parce qu’une hypothèse imaginative peut être rigoureuse si elle reste liée aux indices et reconnaît son degré de certitude.',['imaginer']),
('synthesis','Comment vie, présent et société peuvent-ils conduire à une lecture politique ?','Un contexte de réception actuel peut relier une expérience de vie à des questions collectives, mais le passage doit être explicitement argumenté.',['vie','présent','société','politique']),
('summary','Résume l’unité en une phrase.','Film, musique, chanson et action de jouer ouvrent une histoire qu’il faut lire, écrire et examiner mot par mot; ton, sens, sujet et capacité d’imaginer conduisent à un avis que l’on peut aimer, trouver beau ou drôle, tandis que vie, présent, société et politique élargissent l’interprétation au monde sans que chercher, trouver ou vendre remplace l’argument.',['film','musique','chanson','jouer','histoire','lire','écrire','mot','ton','sens','sujet','imaginer','avis','aimer','beau','drôle','vie','présent','société','politique'])]}
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);text=text_of(s)
 return {'id':s['id'],'language':'fr','cefr':'B2','unit':7,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 07 guarded production batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 07: arts and interpretation.','Accepted B2 default four fresh targets per P01-P05; P06 zero new.','All creators, works, reviews and institutions are fictional/generic.']},'paired_text_group':None,'prerequisites':['French B2 Units 01-06 canonical and Unit06 frontier lock PASS'],'difficulty_notes_internal':'B2 interpretation: evidence vs inference, biography limits, tone, evaluative criteria, social/political context and synthesis.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b2_u07']}
def main():
 for lab,p in [('A1',A1),('A2',A2),('B1',B1),('B2',CANON)]:
  got=subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
  if got!=EXPECTED[lab]:raise AssertionError(f'{lab} blob drift: {got} != {EXPECTED[lab]}')
 lock=json.loads(LOCK.read_text(encoding='utf-8'));probe=json.loads(PROBE.read_text(encoding='utf-8'))
 if lock.get('status')!='PASS' or lock.get('canonical_blob')!=EXPECTED['B2'] or lock.get('last_sequence')!=36:raise AssertionError('Unit06 lock mismatch')
 if probe.get('status')!='PASS' or probe.get('b2_source_blob')!=EXPECTED['B2']:raise AssertionError('Unit07 probe stale')
 fresh={x['form'] for x in probe.get('fresh',[])}
 if any(f not in fresh for f in FORMS):raise AssertionError('selected target absent from fresh Unit07 probe')
 load=lambda p:[json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()];a1,a2,b1,b2=map(load,(A1,A2,B1,CANON));deck=base.deck();prior=base.prior(a1+a2+b1+b2);pid={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};pf={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 if len(b2)!=36 or b2[-1]['id']!='fr-b2-u06-p06':raise AssertionError('unexpected B2 frontier')
 unit=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,deck) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};unit.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,deck) for f in FORMS];ids={t['form']:t['id'] for t in reviews};unit.append(mk(CHECKPOINT,[],reviews,ids,True));V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));newids=[];newforms=[]
 if [r['sequence'] for r in unit]!=list(range(37,43)) or [r['id'] for r in unit]!=[f'fr-b2-u07-p{i:02d}' for i in range(1,7)]:raise AssertionError('Unit07 sequence/id failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
  if not 350<=r['word_count']<=550:raise AssertionError(f"{r['id']}: word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  if r['sequence']<=41 and len(r['new_lexical_targets'])!=4:raise AssertionError(f"{r['id']}: expected four new")
  if r['sequence']==42 and r['new_lexical_targets']:raise AssertionError('P06 must have zero new')
  local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[])};amap={a['question_id']:a['id'] for a in r['answer_key']}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage failure")
  for t in r['new_lexical_targets']:
   src=deck.get(t['form'])
   if t['id'] in pid or t['form'] in pf or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: new target drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20:raise AssertionError('Unit07 target uniqueness failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b2+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':7,'theme':'arts and interpretation','b2_passages':42,'questions':60,'answers':60,'new_targets':20,'word_counts':{r['id']:r['word_count'] for r in unit}},ensure_ascii=False))
if __name__=='__main__':main()
