#!/usr/bin/env python3
"""Append final French B2 Unit10 (seq55-60): integrated B2 synthesis.

P01/P02 form a paired viewpoint set. P03 integrates heterogeneous evidence,
P04 mediates a stakeholder trade-off, P05 transfers the method to a new case,
and P06 is a zero-new cumulative checkpoint. New targets come from the
exhaustive Unit10 probe/selection; reviews come from the exact Unit09 lock.
"""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
R=Path(__file__).resolve().parents[2]
A1=R/'reading/french/a1/passages.jsonl';A2=R/'reading/french/a2/passages.jsonl';B1=R/'reading/french/b1/passages.jsonl';CANON=R/'reading/french/b2/passages.jsonl';SCHEMA=R/'reading/schema/passage.schema.json'
LOCK=R/'reading/audit/french_b2_unit09_frontier_lock.json';PROBE=R/'reading/audit/french_b2_unit10_target_probe.json';SELECT=R/'reading/audit/french_b2_unit10_target_selection.json'
EXPECTED_STABLE={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca'}
PAIR='fr-b2-u10-evidence-action-viewpoints'
SLOT_MEANING={
'p01_claim':'la proposition centrale que le premier point de vue veut défendre','p01_evidence':'le type d’élément utilisé pour soutenir cette proposition','p01_scope':'la portée exacte dans laquelle la conclusion reste défendable','p01_qualify':'le degré de certitude accordé à la conclusion',
'p02_perspective':'l’angle depuis lequel le second point de vue organise les mêmes faits','p02_contrast':'la relation qui rend visible un désaccord ou une différence entre les deux lectures','p02_concede':'la concession reconnue avant de formuler la réponse critique','p02_response':'la réponse qui traite le meilleur argument concurrent',
'p03_combine':'l’opération qui réunit plusieurs éléments sans les confondre','p03_source':'la trace ou famille de traces dont il faut connaître l’origine','p03_compare':'l’opération utilisée pour tester deux explications ou séries','p03_pattern':'la régularité ou relation observée qui demande encore une interprétation',
'p04_tradeoff':'l’arbitrage entre des bénéfices et coûts qui ne tombent pas sur les mêmes personnes','p04_stakeholder':'l’acteur dont les intérêts ou contraintes doivent être représentés','p04_constraint':'la limite pratique qui empêche de choisir uniquement selon l’objectif idéal','p04_option':'l’alternative concrète qui permet de comparer plusieurs chemins',
'p05_synthesize':'l’opération qui transforme plusieurs constats en une conclusion organisée','p05_revision':'la possibilité de modifier la conclusion lorsque de nouvelles informations apparaissent','p05_transfer':'l’usage de la méthode dans un contexte différent de celui où elle a été apprise','p05_judgment':'la décision finale proportionnée aux preuves, coûts et incertitudes'
}

def load_state():
 lock=json.loads(LOCK.read_text(encoding='utf-8'));probe=json.loads(PROBE.read_text(encoding='utf-8'));sel=json.loads(SELECT.read_text(encoding='utf-8'));blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if lock.get('status')!='PASS' or lock.get('last_sequence')!=54 or blob!=lock.get('canonical_blob'):raise AssertionError('Unit09 lock/live B2 mismatch')
 if probe.get('status')!='PASS' or probe.get('b2_source_blob')!=blob:raise AssertionError('Unit10 exhaustive probe missing/stale')
 if sel.get('status')!='PASS' or sel.get('b2_source_blob')!=blob or sel.get('selected_count')!=20:raise AssertionError('Unit10 selection missing/stale')
 groups=sel.get('passage_groups',{});details={x['slot']:x for x in sel.get('selected',[])};reviews=lock.get('unit09_target_groups',{})
 if any(len(groups.get(k,[]))!=4 or len(reviews.get(k,[]))!=4 for k in ['p01','p02','p03','p04','p05']) or len(details)!=20:raise AssertionError('Unit10 state structure drift')
 return lock,groups,details,reviews

def lexical_sentence(slot,form,detail):
 if detail.get('semantic_fallback'):
  return f"Le terme « {form} » est intégré ici comme repère lexical complémentaire; sa fonction est définie par la phrase et ne doit pas être prise comme preuve autonome."
 return f"Dans ce texte, « {form} » sert à nommer {SLOT_MEANING[slot]}; le mot est relié à un raisonnement explicite plutôt qu’à une impression isolée."

def bridge(forms,focus):
 return f"Le texte réactive aussi « {forms[0]} », « {forms[1]} », « {forms[2]} » et « {forms[3]} » de l’unité précédente afin de rappeler que {focus}."

def slots(prefix):
 return {'p01':['claim','evidence','scope','qualify'],'p02':['perspective','contrast','concede','response'],'p03':['combine','source','compare','pattern'],'p04':['tradeoff','stakeholder','constraint','option'],'p05':['synthesize','revision','transfer','judgment']}[prefix]

def specs(groups,details,reviews):
 return [
 {'id':'fr-b2-u10-p01','sequence':55,'ptype':'instructional','genre':'paired viewpoint A','title':'Point de vue A : publier tôt une analyse peut améliorer la décision si les limites sont explicites','domains':['public','professional'],'topics':['B2 synthesis','evidence and action','paired viewpoints'],'prefix':'p01','reviews':reviews['p01'],'pair':PAIR,'review_focus':'une décision publique doit annoncer ses critères, ses bénéficiaires et ses conditions de révision','paras':[
 "Une ville fictive reçoit des résultats préliminaires sur un nouveau service de mobilité. Le premier point de vue, défendu par Samira, recommande de publier rapidement une analyse même si toutes les données ne sont pas encore disponibles. Selon elle, attendre une certitude complète peut empêcher les habitants et les responsables de discuter des choix pendant qu’ils sont encore réversibles. Mais une publication rapide n’est acceptable que si elle distingue clairement observations, interprétations et zones d’incertitude. Une conclusion provisoire doit être présentée comme provisoire, et non transformée en annonce définitive pour simplifier la communication.",
 "Samira propose un format en trois couches. La première présente les faits directement observés : volumes, horaires et écarts entre zones. La deuxième explique les hypothèses nécessaires pour interpréter ces faits. La troisième indique ce qui pourrait faire changer la conclusion. Cette structure permet d’agir sans cacher les limites. Elle rend aussi le désaccord plus précis : une personne peut accepter les données tout en contestant l’hypothèse, ou accepter l’hypothèse tout en préférant un autre seuil de décision.",
 "Une objection affirme qu’une analyse préliminaire risque d’être reprise hors contexte. Samira reconnaît ce danger. Elle répond qu’un retard ne supprime pas la possibilité de mauvaise interprétation et qu’un document bien structuré peut au contraire rendre les corrections futures plus visibles. Elle propose de conserver les versions successives, d’expliquer ce qui a changé et de marquer les résultats qui restent fragiles. Pour elle, la transparence n’est pas le fait de publier le plus grand nombre de chiffres, mais de rendre le chemin du raisonnement vérifiable.",
 "Sa position reste conditionnelle. Une information susceptible de causer un dommage important ne doit pas être diffusée simplement au nom de la vitesse. De même, un résultat trop instable pour guider une action ne mérite pas une recommandation forte. Samira défend donc une publication proportionnée : assez tôt pour permettre le débat, assez précise pour ne pas confondre hypothèse et fait, et assez révisable pour que de nouvelles observations puissent modifier honnêtement la décision."
 ]},
 {'id':'fr-b2-u10-p02','sequence':56,'ptype':'reinforcement','genre':'paired viewpoint B','title':'Point de vue B : une publication trop précoce peut créer un cadre que les corrections ne suffisent plus à réparer','domains':['public','professional'],'topics':['B2 synthesis','evidence and action','paired viewpoints'],'prefix':'p02','reviews':reviews['p02'],'pair':PAIR,'review_focus':'les effets distributifs et l’accès réel peuvent contredire une moyenne apparemment favorable','paras':[
 "Dans le même débat fictif, Marc défend une position plus prudente. Il ne demande pas d’attendre une certitude parfaite, mais il estime qu’une première publication peut fixer durablement la manière dont le public comprend un problème. Une correction ultérieure reçoit parfois moins d’attention que le premier titre. Pour cette raison, il veut distinguer les résultats assez stables pour entrer dans le débat public des explorations encore trop sensibles au choix d’un modèle, d’un groupe de comparaison ou d’une période d’observation.",
 "Marc accepte un point de Samira : cacher toutes les analyses jusqu’à la fin peut rendre la décision opaque. Il propose cependant une étape intermédiaire. Les méthodes, critères et questions peuvent être publiés avant les résultats, tandis que les estimations fragiles restent dans un espace de travail clairement identifié. Cette approche permet au public de contester les règles du raisonnement sans transformer chaque variation préliminaire en fait social. Le coût est réel : le débat porte moins tôt sur les chiffres eux-mêmes.",
 "Son argument principal concerne l’asymétrie entre erreur et correction. Si une estimation provisoire influence un budget, un prix ou une réputation, la conséquence peut continuer même après une rectification. Marc demande donc quel dommage serait le plus difficile à réparer : le retard d’une information utile ou la diffusion d’une conclusion instable. Il ne donne pas une réponse unique. Il veut que cette question fasse partie du seuil de publication, surtout lorsque certains groupes supporteraient davantage le coût d’une erreur.",
 "La conclusion de Marc n’annule pas celle de Samira; elle déplace la charge de justification. Publier tôt exige, selon lui, de montrer pourquoi le bénéfice du débat dépasse le risque de fixer un cadre trompeur. Il demande aussi un plan de correction visible : qui publiera la mise à jour, comment les anciennes versions seront signalées et quels lecteurs recevront l’information nouvelle ? Son point de vue transforme ainsi la transparence en responsabilité sur tout le cycle de vie d’une affirmation, pas seulement au moment de sa première diffusion."
 ]},
 {'id':'fr-b2-u10-p03','sequence':57,'ptype':'interleaved','genre':'integrated analysis','title':'Un chiffre, une archive et deux témoignages : intégrer des preuves différentes sans leur donner le même rôle','domains':['educational','public'],'topics':['B2 synthesis','source integration','causal reasoning'],'prefix':'p03','reviews':reviews['p03'],'pair':None,'review_focus':'une politique réelle doit être distinguée de son annonce et observée à travers son application','paras':[
 "Un dossier fictif demande pourquoi un programme de rénovation a produit des résultats différents entre deux quartiers. Les élèves disposent d’un tableau statistique, d’une archive administrative et de deux témoignages. L’exercice interdit deux raccourcis : traiter tous les documents comme s’ils mesuraient la même chose, ou choisir uniquement la source qui confirme l’explication préférée. Le tableau montre des tendances; l’archive explique certaines décisions; les témoignages décrivent des expériences situées. L’analyse doit donc attribuer à chaque trace une fonction avant de les réunir.",
 "Le premier travail consiste à établir la chronologie. Les statistiques indiquent quand les loyers et les travaux changent, mais elles ne révèlent pas automatiquement pourquoi. L’archive montre qu’une règle a été modifiée six mois plus tôt. Un témoignage affirme que les propriétaires avaient déjà commencé à anticiper cette règle; l’autre insiste sur un changement de crédit. Ces éléments peuvent se compléter ou se concurrencer. Pour les comparer, il faut préciser quelle étape causale chacun permet réellement d’observer.",
 "L’équipe construit ensuite deux explications. La première met l’accent sur la règle publique; la seconde sur les conditions financières. Elle cherche un cas où les deux facteurs ne varient pas ensemble. Cette comparaison transforme une simple corrélation en test plus exigeant. Si le mécanisme public est central, on devrait observer certains effets même lorsque le crédit reste stable. Si le crédit domine, les différences devraient suivre davantage les conditions de financement. Aucun résultat unique ne ferme définitivement la question, mais chaque résultat change la force relative des hypothèses.",
 "La conclusion intègre donc les sources au lieu de les additionner. Un chiffre peut mesurer une évolution, une archive documenter une décision et un témoignage révéler une étape que les catégories officielles ne captent pas. L’analyste doit aussi signaler les contradictions et les silences. Une synthèse B2 devient crédible lorsqu’elle indique ce qui est directement établi, ce qui dépend d’une comparaison et ce qui reste une inférence."
 ]},
 {'id':'fr-b2-u10-p04','sequence':58,'ptype':'transfer','genre':'stakeholder mediation','title':'Médiation : construire une option commune lorsque les groupes ne supportent ni les mêmes coûts ni les mêmes risques','domains':['public','professional'],'topics':['B2 synthesis','trade-offs','stakeholder mediation'],'prefix':'p04','reviews':reviews['p04'],'pair':None,'review_focus':'un contreargument sérieux doit modifier l’analyse du bénéfice, du coût ou de la répartition plutôt que servir de simple obstacle rhétorique','paras':[
 "Une ville fictive veut transformer une rue commerciale en zone où les voitures circulent beaucoup moins. Les commerçants demandent un accès de livraison; des habitants veulent réduire le bruit; des personnes à mobilité réduite craignent une distance supplémentaire; les cyclistes demandent un trajet continu. Aucun groupe n’invente entièrement son problème. La médiation ne peut donc pas résoudre le conflit en déclarant qu’un objectif est moralement supérieur aux autres. Elle doit rendre comparables des coûts de nature différente et chercher une option qui respecte les besoins essentiels sans promettre que chacun obtiendra tout.",
 "Le médiateur commence par distinguer positions et intérêts. « Garder la rue ouverte » est une position; « recevoir les marchandises à une heure prévisible » est un intérêt plus précis. « Fermer toute circulation » est une position; « réduire le danger et le bruit » décrit un résultat recherché. Cette traduction ouvre des solutions intermédiaires : fenêtres de livraison, accès réservé, bancs supplémentaires, itinéraire cyclable et phase pilote. Chaque option doit ensuite être testée contre les contraintes physiques et administratives.",
 "Un désaccord persiste sur le pilote. Certains habitants pensent qu’un essai temporaire repousse inutilement une réforme urgente. Des commerçants répondent qu’une transformation permanente sans test ferait porter tout le risque sur eux. Le médiateur formule le meilleur argument de chaque côté puis cherche des indicateurs partagés : sécurité, temps de livraison, fréquentation, bruit et accessibilité. Le pilote devient alors utile seulement si les critères de décision sont annoncés avant son lancement.",
 "La proposition finale ne prétend pas éliminer le conflit. Elle explique plutôt pourquoi certains coûts sont réduits, lesquels restent présents et comment ils seront suivis. Une médiation réussie n’est pas un accord obtenu par fatigue. C’est une option dont chaque groupe peut comprendre la logique, contester les données et savoir à quel moment une révision devient possible. Le compromis garde ainsi une structure argumentative : objectifs, contraintes, alternatives, preuves et règle de changement."
 ]},
 {'id':'fr-b2-u10-p05','sequence':59,'ptype':'integration','genre':'transfer synthesis','title':'Transférer la méthode : décider sur un front de rivière sans confondre climat, mémoire, commerce et vie privée','domains':['public','educational'],'topics':['B2 synthesis','transfer','multi-domain reasoning'],'prefix':'p05','reviews':reviews['p05'],'pair':None,'review_focus':'une évaluation doit annoncer à l’avance ses horizons, ses mesures et les conditions qui justifieraient une révision','paras':[
 "Le dernier cas fictif place l’apprenant devant un projet de réaménagement d’un front de rivière. La ville veut réduire le risque d’inondation, protéger des bâtiments historiques, maintenir l’activité commerciale et utiliser des capteurs pour suivre l’eau et la fréquentation. Chaque objectif rappelle un domaine étudié plus tôt, mais aucune méthode ne suffit seule. Les données scientifiques décrivent certains risques; les archives expliquent la valeur historique; les acteurs économiques signalent des coûts; la politique de données doit limiter ce que les capteurs permettent de connaître sur les personnes.",
 "Le premier défi est de construire une question commune. Si l’on demande seulement comment réduire l’inondation, on risque d’ignorer les effets sur le quartier. Si l’on demande seulement comment préserver le passé, on peut sous-estimer une menace future. Le dossier propose donc une question à plusieurs critères : quelles options réduisent suffisamment le risque tout en conservant une valeur historique, une activité viable et une collecte de données proportionnée ? Cette formulation n’élimine pas les conflits; elle empêche qu’un objectif efface silencieusement les autres.",
 "Trois options sont comparées : une barrière fixe, des espaces inondables et une combinaison plus légère de protections. Les simulations fournissent des estimations, pas des certitudes. Les archives montrent aussi que certains bâtiments ont déjà changé de fonction. Les commerçants ne sont pas tous affectés de la même manière, et les capteurs nécessaires à la sécurité n’exigent pas forcément un suivi individuel permanent. L’analyse doit donc relier preuve, valeur, distribution et vie privée sans transformer un vocabulaire technique en décision automatique.",
 "La recommandation finale choisit une option révisable avec seuils de suivi. Elle précise ce qui ferait augmenter la protection, modifier le dispositif ou réduire la collecte de données. Surtout, elle indique pourquoi la même méthode peut être transférée à d’autres problèmes : définir les objectifs, distinguer les sources, comparer les mécanismes, représenter les groupes, répondre aux contrearguments et annoncer les conditions de révision. Le transfert n’est pas la copie d’une solution; c’est l’usage discipliné d’une structure de raisonnement dans un nouveau contexte."
 ]}
 ]

def items(spec,forms,reviews):
 f=forms;r=reviews;seq=spec['sequence']
 core={
 55:[('main_claim','Quelle est la position de Samira ?','Publier une analyse provisoire assez tôt pour permettre le débat, à condition d’exposer clairement faits, hypothèses, incertitudes et critères de révision.'),('literal_detail','Quelles trois couches son format distingue-t-il ?','Les faits observés, les hypothèses d’interprétation et les conditions qui feraient changer la conclusion.'),('argument_relation','Comment répond-elle au risque de reprise hors contexte ?','Elle propose des versions conservées, des corrections visibles et un marquage clair des résultats fragiles.'),('assumption','Pourquoi une publication précoce peut-elle améliorer la décision ?','Parce qu’elle permet de discuter les choix pendant qu’ils sont encore réversibles.'),('inference','Quand Samira refuserait-elle une publication rapide ?','Lorsque le dommage potentiel est important ou que le résultat est trop instable pour guider une action.'),('stance','Son point de vue est-il favorable à la transparence absolue ?','Non. Il défend une transparence proportionnée à l’utilité, au risque et au degré de certitude.')],
 56:[('main_claim','Quelle est la thèse de Marc ?','Une première publication peut fixer durablement le cadre du débat; les résultats très fragiles devraient donc être retenus jusqu’à un seuil de stabilité suffisant.'),('literal_detail','Quelle étape intermédiaire propose-t-il ?','Publier méthodes, critères et questions avant les estimations encore trop fragiles.'),('argument_relation','Pourquoi l’erreur et la correction sont-elles asymétriques ?','Parce qu’une première estimation peut influencer budget, prix ou réputation même si elle est corrigée ensuite.'),('assumption','Pourquoi le dommage potentiel doit-il entrer dans le seuil de publication ?','Parce que les coûts d’une erreur ne sont pas également réparables ni distribués entre groupes.'),('inference','Sur quel point Marc rejoint-il Samira ?','Il reconnaît qu’une opacité complète jusqu’à la fin peut empêcher le contrôle public du raisonnement.'),('stance','Marc demande-t-il une certitude parfaite ?','Non. Il demande un seuil de stabilité et un plan de correction proportionnés aux conséquences possibles.')],
 57:[('main_claim','Quelle règle organise l’intégration des sources ?','Attribuer à chaque source une fonction précise, établir la chronologie et comparer les mécanismes plutôt que simplement additionner les documents.'),('literal_detail','Quelles quatre traces sont disponibles ?','Un tableau statistique, une archive administrative et deux témoignages.'),('argument_relation','Pourquoi chercher un cas où les facteurs ne varient pas ensemble ?','Pour distinguer les explications et tester quel mécanisme correspond mieux aux observations.'),('assumption','Pourquoi une archive ne suffit-elle pas à expliquer le résultat ?','Parce qu’elle documente une décision mais pas nécessairement tous les mécanismes ni toutes les expériences.'),('inference','Que se passe-t-il si le crédit reste stable mais que l’effet apparaît ?','Cela renforce relativement l’explication fondée sur la règle publique, sans la prouver seule.'),('stance','Quelle position le texte adopte-t-il envers les contradictions entre sources ?','Il demande de les signaler et de les utiliser pour préciser la force des conclusions.')],
 58:[('main_claim','Quelle méthode de médiation le passage défend-il ?','Transformer les positions en intérêts précis, comparer les contraintes et construire des options testables avec des critères annoncés.'),('literal_detail','Quels groupes sont mentionnés ?','Commerçants, habitants, personnes à mobilité réduite et cyclistes.'),('argument_relation','Pourquoi distinguer position et intérêt ?','Parce qu’un intérêt précis ouvre davantage d’options qu’une demande formulée comme oui/non.'),('assumption','Pourquoi un pilote n’est-il utile qu’avec des critères préalables ?','Sans critères annoncés, chaque groupe pourrait interpréter les résultats selon sa position initiale.'),('inference','Pourquoi la proposition finale ne cherche-t-elle pas à supprimer tout conflit ?','Parce que certains coûts et intérêts restent incompatibles; l’objectif est de rendre l’arbitrage explicite et révisable.'),('stance','Quelle conception du compromis le texte refuse-t-il ?','Un accord obtenu par fatigue ou par effacement des coûts réels.')],
 59:[('main_claim','Que signifie transférer la méthode dans le cas du front de rivière ?','Réutiliser une structure de raisonnement — objectifs, sources, mécanismes, groupes, contrearguments et révision — plutôt que copier une solution.'),('literal_detail','Quels quatre objectifs sont combinés ?','Réduire le risque d’inondation, préserver des bâtiments historiques, maintenir l’activité commerciale et limiter la collecte de données.'),('argument_relation','Pourquoi une question à plusieurs critères est-elle nécessaire ?','Parce qu’une question centrée sur un seul objectif peut effacer silencieusement les autres coûts et valeurs.'),('assumption','Pourquoi les simulations ne déterminent-elles pas la décision ?','Parce qu’elles fournissent des estimations qui doivent être combinées à d’autres valeurs, contraintes et incertitudes.'),('inference','Pourquoi les capteurs n’impliquent-ils pas forcément un suivi individuel permanent ?','Parce que la finalité de sécurité peut souvent être satisfaite avec une collecte plus limitée.'),('stance','Quelle position le texte adopte-t-il envers une solution automatiquement transférable ?','Il la refuse : le transfert concerne la méthode, pas la copie d’une option particulière.')]
 }
 out=[(typ,p,a,[]) for typ,p,a in core[seq]]
 for i,x in enumerate(f):out.append(('vocabulary_in_context',f'Quel rôle joue « {x} » dans ce passage ?',f'Il sert à préciser {SLOT_MEANING[f"{spec["prefix"]}_{slots(spec["prefix"])[i]}"]}.',[x]))
 # 10 total; add local tags to high-value reasoning questions.
 enriched=[]
 for i,(typ,p,a,tags) in enumerate(out):
  if i==0:tags=[f[0],f[1]]
  elif i==2:tags=[f[2],f[3]]
  elif i==4:tags=[r[0]]
  elif i==5:tags=[r[1]]
  enriched.append((typ,p,a,tags))
 return enriched

def make(spec,forms,review_forms,details,prior,deck):
 paras=list(spec['paras']);lex=[]
 for name in slots(spec['prefix']):
  slot=f"{spec['prefix']}_{name}";lex.append(lexical_sentence(slot,details[slot]['form'],details[slot]))
 paras[1]+=' '+' '.join(lex);paras[2]+=' '+bridge(review_forms,spec['review_focus']);text='\n\n'.join(paras)
 new=[base.nt(f,text,deck) for f in forms];reviews=[base.rev(f,prior) for f in review_forms];ids={t['form']:t['id'] for t in new+reviews};q,a=base.qa(items(spec,forms,review_forms),ids)
 return {'id':spec['id'],'language':'fr','cefr':'B2','unit':10,'sequence':spec['sequence'],'revision':1,'title':spec['title'],'passage_type':spec['ptype'],'genre':spec['genre'],'domains':spec['domains'],'topics':spec['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':[{'id':f"fr-b2-u10-g-{spec['sequence']}",'role':'new','description':'qualify synthesis claims through scope, concession, comparison, trade-off and revision conditions'}],'discourse_targets':[{'id':f"fr-b2-u10-d-{spec['sequence']}",'role':'new','description':'integrate evidence, perspective, source roles, stakeholder constraints and transfer'}],'questions':q,'answer_key':a,'speed_training':{'timed':False,'benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'controlled','notes':'French B2 Unit 10 guarded synthesis batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 10 synthesis.','Four exhaustive-probe fresh targets; all scenarios fictional/generic.']},'paired_text_group':spec['pair'],'prerequisites':['French B2 Units 01-09 canonical and Unit09 frontier lock PASS'],'difficulty_notes_internal':'Final B2 synthesis: paired viewpoints, heterogeneous evidence, mediation, transfer and cumulative synthesis.','reader_tags':['unit_role:'+spec['ptype'],'generation_batch','french_b2_u10']}

def checkpoint(groups,deck):
 forms=[f for k in ['p01','p02','p03','p04','p05'] for f in groups[k]];reviews=[base.cur(f,deck) for f in forms];ids={t['form']:t['id'] for t in reviews};g=[groups[f'p0{i}'] for i in range(1,6)]
 text=(
 f"Le niveau B2 se termine par une méthode intégrée. Une conclusion forte commence par une proposition limitée et des preuves identifiables. Les repères « {g[0][0]} », « {g[0][1]} », « {g[0][2]} » et « {g[0][3]} » rappellent qu’il faut distinguer ce que l’on affirme, ce qui le soutient, la portée de l’énoncé et son degré de certitude. Une réponse devient plus fiable lorsqu’elle indique aussi ce qui pourrait la rendre moins forte.\n\n"
 f"Le deuxième mouvement consiste à traiter un point de vue concurrent sans le caricaturer. Les termes « {g[1][0]} », « {g[1][1]} », « {g[1][2]} » et « {g[1][3]} » organisent perspective, contraste, concession et réponse. L’objectif n’est pas de produire un faux équilibre. Il est de reconnaître ce que l’argument opposé explique correctement, puis de montrer précisément où la conclusion diverge et pourquoi.\n\n"
 f"Le troisième mouvement concerne l’intégration des preuves. Les repères « {g[2][0]} », « {g[2][1]} », « {g[2][2]} » et « {g[2][3]} » obligent à réunir des sources différentes sans leur donner le même rôle. Un chiffre, une archive, un témoignage ou une observation peuvent contribuer à la même analyse tout en répondant à des questions distinctes. Comparer leurs résultats aide à distinguer régularité, mécanisme et simple coïncidence.\n\n"
 f"Le quatrième mouvement rend les arbitrages visibles. « {g[3][0]} », « {g[3][1]} », « {g[3][2]} » et « {g[3][3]} » servent à identifier compromis, acteurs, contraintes et options. Une recommandation B2 doit dire qui bénéficie, qui supporte un coût et quelles limites empêchent une solution parfaite. Enfin, « {g[4][0]} », « {g[4][1]} », « {g[4][2]} » et « {g[4][3]} » organisent synthèse, révision, transfert et jugement. La maîtrise apparaît lorsque l’apprenant peut appliquer cette structure à un cas nouveau, conserver l’incertitude pertinente et modifier sa conclusion lorsque les preuves changent."
 )
 if len(text.split())<350:text += " Cette procédure reste volontairement révisable. Une nouvelle source, un groupe jusque-là ignoré, un coût supérieur aux prévisions ou un mécanisme concurrent peut changer la portée de la réponse. Le but n’est donc pas de défendre une première intuition à tout prix, mais de rendre visible le chemin qui mène de l’information au jugement."
 its=[
 ('main_claim','Quelle méthode générale clôt le niveau B2 ?','Construire une conclusion limitée et sourcée, traiter le meilleur point de vue concurrent, intégrer les preuves selon leur rôle, rendre les arbitrages visibles puis transférer et réviser le jugement.',[g[0][0],g[4][3]]),
 ('argument_relation','Pourquoi la concession n’implique-t-elle pas un faux équilibre ?','Parce qu’elle reconnaît seulement ce que l’argument concurrent explique correctement avant de préciser le désaccord.',[g[1][2],g[1][3]]),
 ('cross_text_synthesis','Quel lien unit intégration des sources et arbitrage ?','Les sources établissent des effets et mécanismes, tandis que l’arbitrage décide comment agir lorsque ces effets concernent différemment plusieurs acteurs.',[g[2][0],g[3][0]]),
 ('assumption','Pourquoi une conclusion doit-elle préciser sa portée ?','Parce qu’une preuve valable dans un cas ou sous certaines conditions ne justifie pas automatiquement une généralisation illimitée.',[g[0][2],g[0][3]]),
 ('inference','Que montre la capacité de réviser un jugement ?','Qu’une conclusion est liée aux preuves et critères plutôt qu’à la défense d’une première intuition.',[g[4][1],g[4][3]]),
 ('reference_resolution','Dans « leur donner le même rôle », à quoi renvoie « leur » ?','Aux différentes sources réunies dans l’analyse.',[g[2][1]]),
 ('stance','Quelle position le checkpoint adopte-t-il envers une solution parfaite ?','Il n’en exige pas; il demande que contraintes, coûts et bénéficiaires soient explicités dans le choix entre options.',[g[3][2],g[3][3]]),
 ('vocabulary_in_context','Pourquoi les vingt cibles sont-elles réparties en cinq groupes ?','Chaque groupe correspond à une fonction B2 distincte : cadrer une conclusion, répondre, intégrer, arbitrer et transférer/réviser.',g[0]),
 ('synthesis','Comment le transfert diffère-t-il de la copie ?','Le transfert réutilise la structure de raisonnement dans un nouveau contexte tout en adaptant les sources, critères et contraintes.',[g[4][2],g[3][2]]),
 ('summary','Résume le checkpoint.','Les vingt cibles finales organisent une réponse B2 qui cadre sa conclusion, traite une perspective concurrente, combine les preuves, explicite les compromis et transfère un jugement révisable à de nouveaux problèmes.',forms)
 ]
 q,a=base.qa(its,ids)
 return {'id':'fr-b2-u10-p06','language':'fr','cefr':'B2','unit':10,'sequence':60,'revision':1,'title':'Checkpoint B2 : cadrer, répondre, intégrer, arbitrer et transférer','passage_type':'checkpoint','genre':'B2 final integrated checkpoint','domains':['educational','public','professional'],'topics':['B2 synthesis','final checkpoint','integrated reasoning'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':[],'review_lexical_targets':reviews,'grammar_targets':[{'id':'fr-b2-u10-g-checkpoint','role':'review','description':'integrate claim scope, concession, source comparison, trade-offs, transfer and revision'}],'discourse_targets':[{'id':'fr-b2-u10-d-checkpoint','role':'review','description':'final B2 synthesis across paired viewpoints, evidence integration, mediation and transfer'}],'questions':q,'answer_key':a,'speed_training':{'timed':True,'benchmark_eligible':True,'comprehension_gate':0.8,'new_word_policy':'none','notes':'Final French B2 cumulative checkpoint.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Zero-new final B2 checkpoint using all 20 Unit10 selected forms exactly.']},'paired_text_group':None,'prerequisites':['French B2 Unit10 P01-P05'],'difficulty_notes_internal':'Final B2 integrated synthesis and transfer checkpoint.','reader_tags':['unit_role:checkpoint','generation_batch','french_b2_u10','b2_final_checkpoint']}

def main():
 for lab,p in [('A1',A1),('A2',A2),('B1',B1)]:
  got=subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
  if got!=EXPECTED_STABLE[lab]:raise AssertionError(f'{lab} blob drift: {got}')
 lock,groups,details,review_groups=load_state();rows=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(rows)!=54 or rows[-1]['id']!='fr-b2-u09-p06':raise AssertionError('unexpected B2 Unit09 frontier')
 allrows=[]
 for p in (A1,A2,B1,CANON):allrows += [json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()]
 deck=base.deck();prior=base.prior(allrows);pid={t.get('id') for r in allrows for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};pf={t.get('form') for r in allrows for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 unit=[]
 for spec in specs(groups,details,review_groups):unit.append(make(spec,groups[spec['prefix']],spec['reviews'],details,prior,deck))
 unit.append(checkpoint(groups,deck));V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));selected={x['form'] for x in json.loads(SELECT.read_text(encoding='utf-8'))['selected']};newids=[];newforms=[]
 if [r['sequence'] for r in unit]!=list(range(55,61)) or [r['id'] for r in unit]!=[f'fr-b2-u10-p{i:02d}' for i in range(1,7)]:raise AssertionError('Unit10 sequence/id failure')
 if unit[0]['paired_text_group']!=PAIR or unit[1]['paired_text_group']!=PAIR or any(r['paired_text_group'] is not None for r in unit[2:]):raise AssertionError('Unit10 paired-text structure failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
  if not 350<=r['word_count']<=550:raise AssertionError(f"{r['id']}: word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  if r['sequence']<=59 and len(r['new_lexical_targets'])!=4:raise AssertionError(f"{r['id']}: expected four new")
  if r['sequence']==60 and r['new_lexical_targets']:raise AssertionError('P06 must have zero new')
  local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[])};amap={a['question_id']:a['id'] for a in r['answer_key']}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage failure")
  for t in r['new_lexical_targets']:
   src=deck.get(t['form'])
   if t['id'] in pid or t['form'] in pf or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: new target drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20 or set(newforms)!=selected:raise AssertionError('Unit10 selection/uniqueness failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in rows+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','unit':10,'b2_passages':60,'questions':60,'answers':60,'new_targets':20,'paired_group':PAIR,'groups':groups,'word_counts':{r['id']:r['word_count'] for r in unit}},ensure_ascii=False))
if __name__=='__main__':main()
