#!/usr/bin/env python3
from __future__ import annotations
import csv,json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[2]; CANON=ROOT/'reading/french/a1/passages.jsonl'; SCHEMA=ROOT/'reading/schema/passage.schema.json'; LEX=ROOT/'french_top1000.csv'; EXPECT='046ee90a188be7788e1beb3b1485369b162dd8af'
T={
'fr-rank-0074':dict(lemma='très',form='très',rank=74,sense='very',pos='adverb'),
'fr-rank-0082':dict(lemma='autre',form='autre',rank=82,sense='other; another',pos='adjective / pronoun'),
'fr-rank-0091':dict(lemma='temps',form='temps',rank=91,sense='time (in general)',pos='noun'),
'fr-rank-0094':dict(lemma='toujours',form='toujours',rank=94,sense='always; still',pos='adverb'),
'fr-rank-0098':dict(lemma='encore',form='encore',rank=98,sense='again; still; more',pos='adverb'),
'fr-rank-0108':dict(lemma='personne',form='personne',rank=108,sense='person',pos='noun / pronoun'),
'fr-rank-0117':dict(lemma='jour',form='jour',rank=117,sense='day',pos='noun'),
'fr-rank-0126':dict(lemma='avant',form='avant',rank=126,sense='before',pos='adverb / noun / preposition'),
'fr-rank-0133':dict(lemma='après',form='après',rank=133,sense='after; afterwards',pos='adverb / preposition'),
'fr-rank-0153':dict(lemma='maison',form='maison',rank=153,sense='house; home',pos='noun')}
def qa(xs):
 q=[];a=[]
 for i,(ty,p,ans,tids) in enumerate(xs,1):
  qi=f'q{i}';ai=f'a{i}';x={'id':qi,'type':ty,'prompt':p,'answer_id':ai};
  if tids:x['target_ids']=tids
  q.append(x);a.append({'id':ai,'question_id':qi,'answer':ans,'explanation':''})
 return q,a
def r(tid,f,stage,rep):return {'id':tid,'form':f,'review_stage':stage,'representation':rep,'expected_exposure_number':None}
def n(tid,c,strategies):
 s=T[tid];return {'id':tid,'form':s['form'],'lemma':s['lemma'],'intended_sense':s['sense'],'part_of_speech':s['pos'],'register':'contemporary standard','variety':None,'context_strategy':strategies,'first_introduced':True,'exposures_in_text':c,'source_lexicon':'french_top1000.csv','source_rank':s['rank'],'beyond_base':False}
def mk(pid,seq,ptype,title,genre,domains,topics,text,new,reviews,grammar,discourse,items,speed=False):
 qs,ans=qa(items);return {'id':pid,'language':'fr','cefr':'A1','unit':4,'sequence':seq,'revision':1,'title':title,'passage_type':ptype,'genre':genre,'domains':domains,'topics':topics,'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”\"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':grammar,'discourse_targets':discourse,'questions':qs,'answer_key':ans,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'Generation-stage French A1 Unit 04; full multi-pass audit deferred.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French A1 Unit 04 generation batch under the active ten-question contract.','Schema, source rank, word band, local target declaration, linkage, continuity, and checkpoint invariants are enforced during generation.']},'paired_text_group':None,'prerequisites':['French A1 Units 01-03 canonical corpus'],'difficulty_notes_internal':'A1 continuation: comparison, time/routine, people, before/after sequencing, home, and cumulative daily organization.','reader_tags':['unit_role:'+ptype,'generation_batch','french_a1_u04']}
def build():
 o=[]
 text='''Mercredi après-midi, Camille entre dans une petite papeterie près de l’école. Elle cherche un cahier pour son prochain projet. Le premier cahier est très grand et ne rentre pas bien dans son sac. Elle en regarde un autre, plus petit, avec une couverture bleue. Celui-ci est très léger. Camille hésite entre les deux, puis choisit le petit modèle. Avant de payer, elle demande au vendeur s’il existe une autre couleur. Il lui montre un cahier vert. Camille sourit : le vert lui plaît beaucoup. Elle prend le cahier vert et un stylo noir. En sortant, elle pense que le magasin est très pratique parce qu’elle peut comparer plusieurs options au même endroit.'''
 o.append(mk('fr-a1-u04-p01',19,'instructional','Un autre cahier','shopping comparison narrative',['personal','public'],['shopping','school supplies','comparison'],text,[n('fr-rank-0074',3,['contrast']),n('fr-rank-0082',2,['scenario_resolution'])],[r('fr-rank-0019','ce','R2','reference'),r('fr-rank-0020','pour','R2','running_text')],[{'id':'fr-a1-tres-degree','role':'new','description':'très + adjective for high degree'},{'id':'fr-a1-autre-choice','role':'new','description':'autre for a different item or option'}],[{'id':'fr-a1-compare-options','role':'new','description':'compare two simple purchase options'}],[('gist','Que cherche Camille dans la papeterie ?','Un cahier pour son prochain projet.',[]),('literal_detail','Quelle couleur choisit-elle finalement ?','Le vert.',[]),('vocabulary_in_context','Que signifie « très » dans « très grand » ?','Il augmente le degré : vraiment grand.',['fr-rank-0074']),('vocabulary_in_context','Que signifie « un autre » dans « un autre, plus petit » ?','Un cahier différent du premier.',['fr-rank-0082']),('cause_effect','Pourquoi Camille choisit-elle le petit modèle ?','Parce qu’il est plus léger et convient mieux à son sac.',[]),('single_word_definition','Que signifie « autre » ici ?','Différent du premier ; un autre choix.',['fr-rank-0082']),('grammar_function','Quel rôle joue « très » devant un adjectif ?','Il augmente son intensité.',['fr-rank-0074']),('contrast','Pour demander un choix différent, lequel convient : « autre » ou « toujours » ?','autre',['fr-rank-0082']),('cloze_transfer','Complète : Ce sac est _____ lourd.','très',['fr-rank-0074']),('cloze_transfer','Complète : Je n’aime pas ce stylo ; je veux un _____ stylo.','autre',['fr-rank-0082'])]))
 text='''Jeudi, Camille doit terminer un exercice avant le dîner. Elle regarde l’horloge et voit qu’elle a encore assez de temps. Elle commence à six heures. Elle travaille toujours à la table du salon quand elle doit se concentrer. Après vingt minutes, son frère lui demande de jouer. Camille répond qu’elle veut finir d’abord. Elle prend encore dix minutes pour relire ses réponses. À six heures trente, elle ferme son cahier. Elle a utilisé son temps sans se dépêcher. Sa mère lui demande comment elle organise ses devoirs. Camille explique qu’elle commence toujours par le travail le plus court, puis qu’elle regarde combien de temps il lui reste pour les autres tâches.'''
 o.append(mk('fr-a1-u04-p02',20,'reinforcement','Assez de temps','homework routine narrative',['personal','educational'],['homework','time','routine'],text,[n('fr-rank-0091',3,['scenario_resolution']),n('fr-rank-0094',2,['behavior_interpretation'])],[r('fr-rank-0024','qui','R2','other'),r('fr-rank-0025','mais','R2','other')],[{'id':'fr-a1-time-quantity','role':'new','description':'temps as available time'},{'id':'fr-a1-toujours-habit','role':'new','description':'toujours for a repeated routine'}],[{'id':'fr-a1-routine-order','role':'new','description':'follow a simple recurring study routine'}],[('gist','Que veut terminer Camille avant le dîner ?','Un exercice.',[]),('literal_detail','À quelle heure ferme-t-elle son cahier ?','À six heures trente.',[]),('vocabulary_in_context','Que signifie « temps » dans « assez de temps » ?','La durée disponible pour faire quelque chose.',['fr-rank-0091']),('vocabulary_in_context','Que signifie « toujours » dans « elle travaille toujours à la table » ?','Elle le fait habituellement, chaque fois ou presque.',['fr-rank-0094']),('sequence','Que fait Camille après les vingt premières minutes ?','Elle continue encore dix minutes pour relire ses réponses.',[]),('single_word_definition','Que signifie « temps » dans cette unité ?','La durée disponible.',['fr-rank-0091']),('grammar_function','Quel rôle joue « toujours » dans la phrase ?','Il indique une habitude répétée.',['fr-rank-0094']),('contrast','Pour une habitude régulière, lequel convient : « toujours » ou « autre » ?','toujours',['fr-rank-0094']),('cloze_transfer','Complète : J’ai dix minutes de _____ avant le bus.','temps',['fr-rank-0091']),('cloze_transfer','Complète : Il met _____ ses clés au même endroit.','toujours',['fr-rank-0094'])]))
 text='''Samedi, Camille arrive tôt à la bibliothèque. Elle pense être la première, mais une personne attend déjà devant la porte. Quelques minutes plus tard, deux autres élèves arrivent. La bibliothèque n’est pas encore ouverte. Camille regarde l’heure et dit qu’il reste cinq minutes. Une personne demande si le club de lecture se réunit aujourd’hui. Camille répond oui. Quand la porte ouvre, tout le monde entre calmement. Dans la salle du club, il manque encore une chaise. Sami va en chercher une. Personne ne veut commencer sans lui. Quand il revient, le groupe s’assoit et ouvre les livres. Camille remarque qu’attendre quelques minutes n’est pas difficile quand personne n’est pressé.'''
 o.append(mk('fr-a1-u04-p03',21,'interleaved','Encore cinq minutes','library waiting narrative',['public','educational'],['library','waiting','people'],text,[n('fr-rank-0098',2,['scenario_resolution']),n('fr-rank-0108',4,['category_relation'])],[r('fr-rank-0027','nous','R2','other'),r('fr-rank-0028','dans','R2','running_text')],[{'id':'fr-a1-encore-continuation','role':'new','description':'encore for a state/action continuing or remaining'},{'id':'fr-a1-personne-human','role':'new','description':'personne as an individual person in affirmative context'}],[{'id':'fr-a1-waiting-sequence','role':'new','description':'follow a short wait before an event begins'}],[('gist','Pourquoi le groupe attend-il au début ?','Parce que la bibliothèque n’est pas encore ouverte.',[]),('literal_detail','Combien de minutes reste-t-il avant l’ouverture ?','Cinq minutes.',[]),('vocabulary_in_context','Que signifie « encore » dans « pas encore ouverte » ?','L’ouverture n’a pas eu lieu jusque-là ; la situation continue.',['fr-rank-0098']),('vocabulary_in_context','Que signifie « une personne » devant la porte ?','Un individu, quelqu’un.',['fr-rank-0108']),('sequence','Que fait Sami quand il manque une chaise ?','Il va en chercher une.',[]),('single_word_definition','Quel sens de « personne » est travaillé ici ?','Un individu humain.',['fr-rank-0108']),('grammar_function','Dans « encore cinq minutes », que montre « encore » ?','Qu’il reste une durée supplémentaire.',['fr-rank-0098']),('contrast','Pour parler d’un individu, lequel convient : « personne » ou « temps » ?','personne',['fr-rank-0108']),('cloze_transfer','Complète : Le magasin n’est pas _____ ouvert.','encore',['fr-rank-0098']),('cloze_transfer','Complète : Une _____ attend devant la porte.','personne',['fr-rank-0108'])]))
 text='''Chaque jour d’école, Camille prépare ses affaires le soir. Avant de dormir, elle met son cahier, son livre et sa trousse dans le sac. Le lendemain, elle gagne du temps parce qu’elle ne cherche rien au dernier moment. Un jour, elle oublie pourtant sa bouteille d’eau. Avant le cours de sport, elle ouvre son sac et comprend le problème. Sami lui propose un peu d’eau, mais Camille préfère acheter une petite bouteille après le cours. Elle note alors une nouvelle règle sur son carnet : vérifier aussi la bouteille avant de fermer le sac. Le soir, elle relit sa liste. Camille sait qu’un jour peut être plus simple quand elle prépare les petites choses avant de partir.'''
 o.append(mk('fr-a1-u04-p04',22,'transfer','Avant de fermer le sac','daily preparation narrative',['personal','educational'],['school day','preparation','sequence'],text,[n('fr-rank-0117',3,['scenario_resolution']),n('fr-rank-0126',4,['form_function'])],[r('fr-rank-0030','bien','R2','other'),r('fr-rank-0041','moi','R2','other')],[{'id':'fr-a1-jour-time-unit','role':'new','description':'jour as a day'},{'id':'fr-a1-avant-sequence','role':'new','description':'avant for earlier position in time'}],[{'id':'fr-a1-before-action','role':'new','description':'connect preparation to a later action'}],[('gist','Quelle habitude Camille essaie-t-elle d’améliorer ?','La préparation de son sac avant l’école.',[]),('literal_detail','Quel objet oublie-t-elle un jour ?','Sa bouteille d’eau.',[]),('vocabulary_in_context','Que signifie « jour » dans « un jour » ?','Une journée, un moment d’une journée particulière.',['fr-rank-0117']),('vocabulary_in_context','Que signifie « avant » dans « avant de dormir » ?','Plus tôt que l’action de dormir.',['fr-rank-0126']),('cause_effect','Pourquoi Camille ajoute-t-elle la bouteille à sa liste ?','Parce qu’elle l’a oubliée une fois.',[]),('single_word_definition','Que signifie « avant » ici ?','Plus tôt dans le temps.',['fr-rank-0126']),('grammar_function','Dans « avant de partir », quelle relation exprime « avant » ?','Une action se produit plus tôt qu’une autre.',['fr-rank-0126']),('contrast','Lequel désigne une unité de temps : « jour » ou « personne » ?','jour',['fr-rank-0117']),('cloze_transfer','Complète : Chaque _____, je prépare mon sac.','jour',['fr-rank-0117']),('cloze_transfer','Complète : Je ferme la fenêtre _____ de sortir.','avant',['fr-rank-0126'])]))
 text='''Dimanche matin, Camille reste à la maison avec sa famille. Après le petit-déjeuner, elle aide sa mère à ranger la cuisine. Son frère veut sortir, mais il doit d’abord finir un dessin. Camille ouvre la fenêtre et lit un peu dans sa chambre. Après vingt minutes, elle entend son frère appeler : il est prêt. Ils quittent la maison et vont au parc. Là, ils retrouvent Sami. Les trois amis jouent au ballon, puis s’assoient sous un arbre. En fin d’après-midi, Camille rentre à la maison. Après la promenade, elle prépare son sac pour lundi et pose son cahier sur la table. Elle aime ce moment calme avant une nouvelle semaine.'''
 o.append(mk('fr-a1-u04-p05',23,'integration','Après le petit-déjeuner','weekend routine narrative',['personal'],['home','weekend','sequence'],text,[n('fr-rank-0133',4,['form_function']),n('fr-rank-0153',3,['scenario_resolution'])],[r('fr-rank-0042','oui','R2','other'),r('fr-rank-0045','ils','R2','running_text')],[{'id':'fr-a1-apres-sequence','role':'new','description':'après for later position in time'},{'id':'fr-a1-maison-home','role':'new','description':'maison as house/home'}],[{'id':'fr-a1-weekend-sequence','role':'integration','description':'integrate a simple sequence of home and outdoor activities'}],[('gist','Que fait Camille pendant cette matinée de dimanche ?','Elle reste d’abord à la maison, aide sa mère, puis va au parc avec son frère.',[]),('literal_detail','Que doit finir son frère avant de sortir ?','Un dessin.',[]),('vocabulary_in_context','Que signifie « après » dans « Après le petit-déjeuner » ?','Plus tard que le petit-déjeuner.',['fr-rank-0133']),('vocabulary_in_context','Que signifie « maison » dans « Camille reste à la maison » ?','Le lieu où elle habite avec sa famille.',['fr-rank-0153']),('sequence','Que fait Camille après la promenade ?','Elle prépare son sac pour lundi.',[]),('single_word_definition','Que signifie « maison » ici ?','Le logement ou le foyer où une personne habite.',['fr-rank-0153']),('grammar_function','Quelle relation temporelle exprime « après » ?','Une action arrive plus tard qu’une autre.',['fr-rank-0133']),('contrast','Lequel signifie plus tard dans le temps : « après » ou « avant » ?','après',['fr-rank-0133']),('cloze_transfer','Complète : Je rentre à la _____ après l’école.','maison',['fr-rank-0153']),('cloze_transfer','Complète : _____ le cours, je vais à la bibliothèque.','Après',['fr-rank-0133'])]))
 text='''Camille remarque qu’elle organise mieux ses journées. Dans un magasin, elle peut choisir un autre objet quand le premier ne convient pas, et elle compare très simplement les options. Pour ses devoirs, elle regarde le temps disponible et travaille toujours dans un endroit calme. À la bibliothèque, elle peut attendre encore quelques minutes avec les autres personnes. Chaque jour, elle prépare son sac avant de partir, puis elle vérifie ce qu’il contient. Après ses activités, elle rentre à la maison et prépare la suite. Ces habitudes ne rendent pas chaque journée parfaite, mais elles l’aident à perdre moins de temps. Camille se sent plus calme parce qu’elle sait quoi faire avant et après les moments importants.'''
 o.append(mk('fr-a1-u04-p06',24,'checkpoint','Avant et après','fluency checkpoint summary',['personal','educational','public'],['time','routine','review'],text,[],[r('fr-rank-0074','très','R2','summary'),r('fr-rank-0082','autre','R2','summary'),r('fr-rank-0091','temps','R2','running_text'),r('fr-rank-0094','toujours','R2','running_text'),r('fr-rank-0098','encore','R1','running_text'),r('fr-rank-0108','personne','R1','running_text'),r('fr-rank-0117','jour','R1','running_text'),r('fr-rank-0126','avant','R1','contrast'),r('fr-rank-0133','après','R1','contrast'),r('fr-rank-0153','maison','R1','running_text')],[{'id':'fr-a1-u04-time-integration','role':'integration','description':'review degree, alternatives, time, habituality, continuation, people, days, before/after, and home'}],[{'id':'fr-a1-u04-routine-summary','role':'integration','description':'integrate shopping, study, waiting, preparation, and home routines'}],[('gist','Quelle est l’idée principale du texte ?','Camille utilise plusieurs habitudes pour mieux organiser ses journées.',[]),('literal_detail','Où Camille travaille-t-elle toujours pour ses devoirs ?','Dans un endroit calme.',['fr-rank-0094']),('vocabulary_in_context','Que signifie « encore » dans « attendre encore quelques minutes » ?','Attendre quelques minutes supplémentaires.',['fr-rank-0098']),('reference_resolution','Dans « les autres personnes », que signifie « personnes » ?','Les individus présents à la bibliothèque.',['fr-rank-0108']),('cause_effect','Pourquoi Camille se sent-elle plus calme ?','Parce qu’elle sait mieux quoi faire avant et après les moments importants.',[]),('single_word_definition','Que signifie « temps » ici ?','La durée disponible.',['fr-rank-0091']),('grammar_choice','Pour une action plus tôt, choisis « avant » ou « après ».','avant',['fr-rank-0126','fr-rank-0133']),('contrast','Pour une action plus tard, lequel convient : « après » ou « avant » ?','après',['fr-rank-0133','fr-rank-0126']),('cloze_transfer','Complète : Je rentre à la _____ le soir.','maison',['fr-rank-0153']),('cloze_transfer','Complète : Chaque _____, je vérifie mon sac.','jour',['fr-rank-0117'])],True))
 return o
def rows():return [json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
def declared(x):return {str(t['id']) for f in ('new_lexical_targets','review_lexical_targets') for t in x.get(f,[]) if isinstance(t,dict) and t.get('id')}
def src():
 by={}
 with LEX.open(encoding='utf-8',newline='') as f:
  for x in csv.DictReader(f):by[x['Front']]=x['Back']
 for tid,s in T.items():
  m=re.search(r'Rank:\s*(\d+)',by.get(s['lemma'],'') or '')
  if not m or int(m.group(1))!=s['rank']:raise AssertionError(f'source rank drift {tid}/{s["lemma"]}')
def val(x,v):
 es=sorted(v.iter_errors(x),key=lambda e:list(e.path))
 if es:raise AssertionError(f'schema {x["id"]}: {es[0].message} @ {list(es[0].path)}')
 if not 90<=x['word_count']<=140:raise AssertionError(f'band {x["id"]}: {x["word_count"]}')
 if len(x['questions'])!=10 or len(x['answer_key'])!=10:raise AssertionError(f'10Q {x["id"]}')
 amap={a['question_id']:a['id'] for a in x['answer_key']};local=declared(x)
 if len(amap)!=10:raise AssertionError(f'answer count {x["id"]}')
 for q in x['questions']:
  if amap.get(q['id'])!=q['answer_id']:raise AssertionError(f'link {x["id"]}/{q["id"]}')
  for tid in q.get('target_ids',[]):
   if tid not in local:raise AssertionError(f'undeclared {x["id"]}/{q["id"]}/{tid}')
 if x['id'].endswith('-p06') and x['new_lexical_targets']:raise AssertionError(f'checkpoint new target {x["id"]}')
def main():
 blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if blob!=EXPECT:raise AssertionError(f'French A1 source drift {blob} != {EXPECT}')
 old=rows()
 if len(old)!=18 or [x['sequence'] for x in old]!=list(range(1,19)):raise AssertionError('expected 18 rows before Unit04')
 existing={t.get('id') for x in old for t in x.get('new_lexical_targets',[]) if isinstance(t,dict)}
 if set(T)&existing:raise AssertionError(f'reintroduced IDs {sorted(set(T)&existing)}')
 src();new=build();v=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')))
 if [x['sequence'] for x in new]!=list(range(19,25)):raise AssertionError('Unit04 sequence failure')
 for x in old+new:val(x,v)
 for x in new:
  for t in x['new_lexical_targets']:
   c=len(re.findall(rf'(?<!\w){re.escape(t["form"])}(?!\w)',x['text'],flags=re.I))
   if c!=t['exposures_in_text']:raise AssertionError(f'exposure {x["id"]}/{t["id"]}: {c}!={t["exposures_in_text"]}')
 original=CANON.read_text(encoding='utf-8');original+= '' if original.endswith('\n') else '\n';CANON.write_text(original+''.join(json.dumps(x,ensure_ascii=False,sort_keys=True)+'\n' for x in new),encoding='utf-8')
 final=rows()
 if len(final)!=24 or [x['sequence'] for x in final]!=list(range(1,25)):raise AssertionError('post continuity failure')
 for x in final:val(x,v)
 print(json.dumps({'status':'PASS','unit':4,'appended_passages':6,'french_a1_total':24,'word_counts':{x['id']:x['word_count'] for x in new},'new_targets':10,'questions':60,'answers':60,'checkpoint_new_targets':0},ensure_ascii=False))
if __name__=='__main__':main()
