#!/usr/bin/env python3
"""Append French B1 Unit 09 (sequences 49-54) with full fail-closed guards."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit08 as prev
base=prev.base
REPO=Path(__file__).resolve().parents[2];A1=REPO/'reading/french/a1/passages.jsonl';A2=REPO/'reading/french/a2/passages.jsonl';CANON=REPO/'reading/french/b1/passages.jsonl';SCHEMA=REPO/'reading/schema/passage.schema.json'
EXPECTED_A1_BLOB='0493a2fa13e51b5997db05e91cdea4d8dc5e647b';EXPECTED_A2_BLOB='d0a80b8866071f426019aa0ad143e1d270dba4de';EXPECTED_B1_BLOB='0dd67add09436dfe96282bebb2cd35a6355acd34'
FORMS=('nettoyer','niveau','atteindre','forcer','coincer','remonter','quartier','magasin','silence','exemple','tort','intéressant','merveilleux','surprendre','radio')

def qa(forms,reviews,label):
 a,b,c=forms;x,y,z=reviews
 return [('gist',f'Quelle méthode guide le travail dans cette situation de {label} ?',f'Observer précisément avant d’utiliser {a}, {b} et {c}.',[a,b,c]),('literal_detail','Quel détail est vérifié avant la décision ?','Un élément observable est mesuré ou comparé avant la modification. ',[b]),('cause_effect','Pourquoi l’équipe évite-t-elle une solution immédiate ?','Parce qu’elle veut distinguer la cause du symptôme avant de modifier le système. ',[c]),('vocabulary_in_context',f'Que signifie « {a} » ici ?',f'Le mot « {a} » décrit l’action précise réalisée dans ce contexte.',[a]),('vocabulary_in_context',f'Que signifie « {b} » ici ?',f'Le mot « {b} » est interprété selon les indices du passage.',[b]),('inference','Que montre la comparaison entre les deux options ?','Une solution vérifiable est préférable à une correction rapide qui masque les informations. ',[c]),('motive','Pourquoi Camille note-t-elle le résultat ?','Pour garder une trace qui permet de vérifier ou reproduire la décision. ',[x]),('grammar_in_context',f'Quel rôle joue « {c} » dans le raisonnement ?','Il exprime une action, un état ou une conséquence liée à la décision. ',[c]),('cloze_transfer',f'Complète avec le premier mot cible : _____.',a,[a]),('summary','Résume le passage. ',f'Camille relie {a}, {b} et {c} aux acquis {x}, {y} et {z} afin de décider à partir de preuves.',[a,b,c,x,y,z])]
DATA=[
('fr-b1-u09-p01',49,'instructional','Nettoyer jusqu’au bon niveau sans chercher à tout atteindre','water-system maintenance narrative',['professional','public'],['maintenance','water'],['nettoyer','niveau','atteindre'],['régler','contrôle','capable'],[
"Dans un jardin pédagogique, un petit réservoir recueille l’eau de pluie. Après plusieurs semaines, des feuilles s’accumulent près du filtre. Camille doit nettoyer le système avant une nouvelle séance, mais elle commence par un contrôle du niveau d’eau. Le réservoir est encore capable d’alimenter l’arrosage, et il n’est donc pas nécessaire de tout vider. L’équipe décide de régler le débit afin que le niveau baisse seulement assez pour accéder au filtre.",
"Pour nettoyer correctement, Camille retire d’abord les débris visibles puis rince le panier filtrant dans un bac séparé. Elle veut atteindre la zone bouchée sans faire entrer de saleté plus loin dans la conduite. Le niveau est marqué sur une règle avant et après l’intervention. Ce contrôle permet de vérifier que la baisse vient bien du réglage choisi et non d’une fuite. Être capable d’atteindre le fond du réservoir n’est pas un objectif en soi : ce qui compte est d’atteindre la partie qui empêche le filtre de fonctionner.",
"Après le nettoyage, l’eau circule normalement. Camille remet le débit initial et observe le niveau pendant dix minutes. Elle comprend que nettoyer ne signifie pas enlever chaque trace visible dans le réservoir, mais retirer ce qui gêne sa fonction. De même, atteindre une zone n’a de sens que si cette zone est liée au problème. Le dernier contrôle montre que l’installation est capable de reprendre son service. L’équipe note donc le niveau observé, le réglage effectué et la partie nettoyée afin que la prochaine inspection puisse comparer les mêmes éléments au lieu de recommencer toute l’analyse."
]),
('fr-b1-u09-p02',50,'reinforcement','Ne pas forcer quand une pièce commence à coincer','mechanical diagnosis narrative',['professional','educational'],['mechanics','diagnosis'],['forcer','coincer','remonter'],['diriger','traverser','selon'],[
"Une porte coulissante utilisée pour déplacer du matériel devient difficile à fermer. Un élève propose de forcer la poignée, mais Camille l’arrête. Selon la notice, une résistance inhabituelle peut indiquer qu’un petit objet bloque le rail. Elle dirige le groupe vers une inspection visuelle avant toute nouvelle tentative. Pour traverser l’ouverture, les autres personnes utilisent temporairement une seconde porte afin que personne ne pousse la porte défectueuse.",
"Camille fait glisser la porte doucement jusqu’au point où elle commence à coincer. Une petite vis est tombée dans le rail. Elle la retire, puis essaie de remonter légèrement le panneau pour vérifier si les roulettes sont bien placées. Forcer aurait pu coincer la vis plus profondément ou endommager une roulette. Selon la position du blocage, la bonne action n’est donc pas la même. Le groupe apprend à diriger son attention vers le point précis où le mouvement change.",
"Après le retrait de la vis, la porte se déplace normalement. Camille ne cherche pas à remonter tout le mécanisme puisque rien ne le justifie. Elle explique que remonter peut signifier déplacer une pièce vers le haut ou remettre un mécanisme en état selon le contexte, mais ici seul un petit ajustement est nécessaire. Une pièce qui commence à coincer donne une information ; elle n’est pas une invitation à forcer davantage. En utilisant une autre porte pour traverser pendant le diagnostic et en suivant les indications selon la notice, l’équipe maintient le service tout en protégeant le matériel."
]),
('fr-b1-u09-p03',51,'interleaved','Le silence d’un magasin au milieu du quartier','neighborhood operations narrative',['public','professional'],['neighborhood','retail operations'],['quartier','magasin','silence'],['crier','sentiment','remarquer'],[
"Un petit magasin de réparation ouvre tôt dans un quartier résidentiel. Après plusieurs plaintes, la responsable invite Camille à observer l’arrivée des livraisons. Personne ne vient crier devant la porte ; le problème est plus subtil. À six heures trente, les chariots métalliques produisent des chocs répétés. Camille remarque que le sentiment exprimé dans les messages des voisins n’est pas une opposition au magasin lui-même, mais une demande de silence pendant une partie de la matinée.",
"L’équipe mesure alors les étapes les plus bruyantes. Le magasin peut conserver son horaire tout en déplaçant certaines opérations à l’intérieur. Des protections en caoutchouc réduisent les chocs des chariots, et le fournisseur accepte de couper le moteur du camion pendant le déchargement. Camille remarque qu’un silence complet est impossible dans une activité réelle, mais qu’un quartier peut raisonnablement attendre une réduction des bruits évitables. Le sentiment de gêne devient ainsi un ensemble de situations observables plutôt qu’un conflit vague.",
"Deux semaines plus tard, les voisins signalent une amélioration. Le magasin garde un registre des livraisons et des incidents afin d’identifier rapidement un retour du problème. Camille retient qu’il faut parfois entendre ce qui n’est pas crié. Le mot silence décrit ici un objectif relatif : limiter les bruits inutiles aux heures sensibles. Le quartier et le magasin ne défendent pas des intérêts forcément incompatibles. En choisissant de remarquer les moments précis qui provoquent le sentiment de gêne, l’équipe peut modifier ses pratiques sans fermer le service ni demander aux habitants d’ignorer complètement le bruit."
]),
('fr-b1-u09-p04',52,'transfer','Un exemple intéressant peut aussi montrer qu’on a tort','classroom reasoning narrative',['educational'],['reasoning','examples'],['exemple','tort','intéressant'],['couvrir','trou','forme'],[
"Dans un cours de sciences, une classe compare plusieurs matériaux utilisés pour couvrir un petit trou dans une boîte expérimentale. Un élève affirme que le matériau le plus épais sera forcément le meilleur. Camille demande un exemple qui permettrait de tester cette idée. Le premier essai donne un résultat intéressant : une plaque épaisse couvre bien l’ouverture, mais sa forme empêche la boîte de se fermer. L’exemple montre donc que l’épaisseur seule ne suffit pas.",
"L’élève reconnaît qu’il avait tort de traiter un seul critère comme une conclusion complète. Le groupe prépare alors un second exemple avec un matériau plus fin dont la forme correspond mieux au trou. Il couvre l’ouverture et permet à la boîte de fonctionner normalement. Camille insiste sur une nuance : avoir tort sur une hypothèse ne signifie pas que tout le raisonnement précédent était inutile. Le résultat intéressant indique précisément quelle partie de l’idée doit être corrigée.",
"Les élèves écrivent ensuite une règle de travail : chaque exemple doit tester une proposition identifiable. Si le résultat contredit cette proposition, on explique où elle avait tort au lieu de changer discrètement la question. Camille trouve cette méthode intéressante parce qu’elle transforme l’erreur en information. La forme du matériau, le trou à couvrir et la fonction finale restent visibles dans le raisonnement. Un exemple devient ainsi plus qu’une illustration ; il sert à vérifier une idée. Reconnaître qu’on a tort peut être une étape productive lorsque la correction est reliée à un résultat observé."
]),
('fr-b1-u09-p05',53,'transfer','Une radio peut surprendre sans rendre tout merveilleux','community audio-event evaluation narrative',['public','educational'],['audio','event evaluation'],['merveilleux','surprendre','radio'],['échapper','souffrir','compris'],[
"Pour une journée communautaire, des élèves installent une petite radio temporaire qui diffuse des entrevues et des annonces locales. Le premier essai semble merveilleux : la musique est claire et les invités parlent avec énergie. Pourtant, Camille veut vérifier ce qui a pu échapper à l’équipe. Dans un coin du bâtiment, le signal disparaît presque complètement. Le projet pourrait souffrir si les organisateurs supposaient que la radio fonctionne partout simplement parce que le studio reçoit bien le son.",
"Un second test va surprendre l’équipe : la zone la plus proche de l’émetteur n’est pas celle où la réception est la meilleure. Après quelques mesures, les élèves comprennent qu’un mur épais bloque une partie du signal. Camille demande à chacun ce qu’il avait compris du fonctionnement avant le test. Plusieurs pensaient que la distance était le seul facteur. Cette hypothèse avait laissé échapper la forme du bâtiment et les obstacles entre l’émetteur et les auditeurs.",
"L’équipe déplace finalement l’antenne et ajoute un plan des zones de réception. Le résultat est bon, mais Camille évite de le qualifier de merveilleux sans précision. Une radio utile doit rester compréhensible dans les espaces où le public en a besoin. Un résultat qui peut surprendre est surtout une occasion de comparer l’hypothèse aux mesures. Le projet ne souffre plus du même problème parce que l’équipe a identifié ce qui lui avait échappé et expliqué ce qu’elle avait compris de travers. L’enthousiasme reste présent, mais il accompagne désormais une évaluation concrète plutôt qu’une impression générale."
])]
SPECS=[]
for pid,seq,ptype,title,genre,domains,topics,forms,reviews,pars in DATA:
 s={'id':pid,'sequence':seq,'ptype':ptype,'title':title,'genre':genre,'domains':domains,'topics':topics,'forms':forms,'reviews':reviews,'paragraphs':pars,'grammar':[{'id':pid+'-grammar','role':'new','description':'B1 contrast and causal clause linking'}],'discourse':[{'id':pid+'-discourse','role':'new','description':'test a claim against observable evidence and revise the decision'}]};s['items']=qa(forms,reviews,topics[0]);SPECS.append(s)
CHECKPOINT={'id':'fr-b1-u09-p06','sequence':54,'ptype':'checkpoint','title':'Observer ce qui bloque, dérange ou contredit','genre':'B1 cumulative diagnostic summary','domains':['educational','public','professional'],'topics':['maintenance','mechanics','neighborhood','reasoning','audio'],'paragraphs':[
"Camille apprend à chercher le détail qui change réellement une décision. Pour nettoyer un système, elle vérifie le niveau et cherche à atteindre seulement la zone utile. Quand une pièce commence à coincer, elle évite de forcer et décide s’il faut remonter ou simplement ajuster un élément. Dans un quartier, le silence attendu autour d’un magasin peut être défini par des moments et des bruits précis.",
"La même méthode améliore le raisonnement. Un exemple intéressant peut montrer qu’une hypothèse avait tort sans rendre tout le travail inutile. Une radio peut surprendre l’équipe et produire un résultat merveilleux à certains endroits tout en révélant une faiblesse ailleurs. Chaque cas demande donc de séparer la première impression du résultat mesuré.",
"Les acquis de l’unité précédente restent actifs : régler après un contrôle, vérifier qu’un système est capable de tenir, diriger un groupe pour traverser selon les conditions, remarquer le sentiment derrière une personne qui peut crier, examiner la forme avant de couvrir un trou, puis étudier ce qui a pu échapper au plan, faire souffrir le projet ou être mal compris. Camille relie maintenant ces habitudes à cinq nouveaux gestes : nettoyer jusqu’au bon niveau, atteindre la partie pertinente, ne pas forcer ce qui commence à coincer, remonter seulement ce qui le demande, comprendre le silence d’un quartier et d’un magasin, utiliser un exemple pour reconnaître qu’on a tort, et laisser une radio surprendre sans appeler automatiquement tout résultat merveilleux."
],'grammar':[{'id':'fr-b1-u09-cumulative','role':'integration','description':'integrate causal, contrastive and evaluative structures across diagnostic contexts'}],'discourse':[{'id':'fr-b1-u09-diagnose-before-fix','role':'integration','description':'synthesize diagnosis, measurement and correction across five domains'}]}
CHECKPOINT['items']=[('gist','Quelle habitude générale relie l’unité ?','Identifier le détail pertinent, le mesurer et corriger seulement ce que les preuves justifient.',['niveau','exemple']),('literal_detail','Quels mots décrivent le nettoyage ?','nettoyer, niveau et atteindre',['nettoyer','niveau','atteindre']),('cause_effect','Pourquoi ne faut-il pas forcer une pièce ?','Parce qu’elle peut coincer davantage et ne pas nécessiter de tout remonter.',['forcer','coincer','remonter']),('vocabulary_in_context','Quels mots décrivent l’environnement commercial ?','quartier, magasin et silence',['quartier','magasin','silence']),('vocabulary_in_context','Quels mots décrivent le raisonnement en classe ?','exemple, tort et intéressant',['exemple','tort','intéressant']),('inference','Pourquoi la radio ne rend-elle pas automatiquement le résultat merveilleux ?','Parce qu’elle peut surprendre en révélant aussi des zones de mauvaise réception.',['radio','surprendre','merveilleux']),('motive','Pourquoi garder les mesures après une correction ?','Pour comparer la prochaine situation avec un état observé.',[]),('reference_resolution','Dans « elle peut coincer davantage », à quoi renvoie « elle » ?','À la pièce mécanique.',['coincer']),('cloze_transfer','Complète : Un bon test peut montrer qu’une hypothèse avait _____.','tort',['tort']),('summary','Résume l’unité.','Camille apprend à nettoyer selon le niveau à atteindre, éviter de forcer ce qui peut coincer ou demander de remonter, définir le silence entre quartier et magasin, utiliser un exemple intéressant pour voir où elle avait tort et laisser une radio surprendre sans appeler tout résultat merveilleux.',['nettoyer','niveau','atteindre','forcer','coincer','remonter','quartier','magasin','silence','exemple','tort','intéressant','radio','surprendre','merveilleux'])]
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);t=text_of(s);return {'id':s['id'],'language':'fr','cefr':'B1','unit':9,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':t,'word_count':len(t.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',t))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B1 Unit 09 guarded batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B1 Unit 09 batch.']},'paired_text_group':None,'prerequisites':['French B1 Units 01-08 canonical corpus'],'difficulty_notes_internal':'B1 diagnostic transfer.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b1_u09']}
def build(a1,a2,b1,D):
 prior=base.prior(a1+a2+b1);ids0={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};forms0={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};bad=[]
 for f in FORMS:
  if f not in D:bad.append(f+':missing_lexicon')
  elif base.tid(D[f]['rank']) in ids0 or f in forms0 or prior.get(f):bad.append(f+':already_deliberate')
 if bad:raise AssertionError('B1 Unit09 candidate failures: '+', '.join(bad))
 out=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,D) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,D) for f in FORMS];ids={t['form']:t['id'] for t in reviews};out.append(mk(CHECKPOINT,[],reviews,ids,True));return out
def main():
 for path,exp,label in [(A1,EXPECTED_A1_BLOB,'A1'),(A2,EXPECTED_A2_BLOB,'A2'),(CANON,EXPECTED_B1_BLOB,'B1')]:
  h=subprocess.check_output(['git','hash-object',str(path)],text=True).strip();
  if h!=exp:raise AssertionError(f'{label} blob drift: {h} != {exp}')
 a1=[json.loads(x) for x in A1.read_text().splitlines() if x.strip()];a2=[json.loads(x) for x in A2.read_text().splitlines() if x.strip()];b1=[json.loads(x) for x in CANON.read_text().splitlines() if x.strip()]
 if len(b1)!=48 or b1[-1]['id']!='fr-b1-u08-p06':raise AssertionError('unexpected frontier')
 D=base.deck();unit=build(a1,a2,b1,D);V=Draft202012Validator(json.loads(SCHEMA.read_text()));prior_ids={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};prior_forms={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};ni=[];nf=[]
 for r in unit:
  es=sorted(V.iter_errors(r),key=lambda e:list(e.path));
  if es:raise AssertionError(f"{r['id']}: schema {[e.message for e in es[:4]]}")
  if not 220<=r['word_count']<=350:raise AssertionError(f"{r['id']}: B1 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(r['id']+': assessment count')
  if r['sequence']<=53 and len(r['new_lexical_targets'])!=3:raise AssertionError(r['id']+': target load')
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[])}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage")
  for t in r['new_lexical_targets']:
   s=D.get(t['form']);
   if t['id'] in prior_ids or t['form'] in prior_forms or not s or t['source_rank']!=s['rank'] or t['id']!=base.tid(s['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: target drift {t}")
   ni.append(t['id']);nf.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(ni)!=15 or len(set(ni))!=15 or len(set(nf))!=15 or unit[-1]['new_lexical_targets']:raise AssertionError('Unit09 lexical invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b1+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':9,'b1_passages':54,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':FORMS},ensure_ascii=False))
if __name__=='__main__':main()
