#!/usr/bin/env python3
"""Generate Arabic A1 Unit 07: weather, clothes, and plans."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; P=ROOT/"reading"/"arabic"/"a1"/"passages.jsonl"; L=ROOT/"reading"/"lexicons"/"arabic.jsonl"
T={489:("سماء","sky",["scenario_resolution"]),451:("موسم","season",["example_instance"]),496:("درجة","degree; temperature degree in context",["example_instance"]),111:("يبدو","seems; appears",["behavior_interpretation"]),363:("قادم","coming; next",["contrast"]),105:("ربما","perhaps; maybe",["scenario_resolution"]),276:("صباح","morning",["scenario_resolution"]),232:("أيام","days",["example_instance"]),225:("ساعة","hour; clock/watch",["scenario_resolution"]),252:("أسبوع","week",["category_relation"])}
def qa(items):
 qs=[];ans=[]
 for i,(t,p,a,ids) in enumerate(items,1):
  q={"id":f"q{i}","type":t,"prompt":p,"answer_id":f"a{i}"};
  if ids:q["target_ids"]=ids
  qs.append(q);ans.append({"id":f"a{i}","question_id":f"q{i}","answer":a,"explanation":""})
 return qs,ans
R=[
{"id":"ar-a1-u07-p01","sequence":37,"title":"السماء هذا الصباح","passage_type":"instructional","genre":"forecast-like morning note","domains":["personal"],"topics":["weather","morning","clothes"],"text":"تفتح ليلى النافذة في الصباح وتنظر إلى السماء. السماء رمادية، والهواء بارد قليلًا. تقول أمها: في هذا الموسم تتغير الأيام بسرعة؛ قد يكون الصباح باردًا ثم يصبح الظهر أدفأ. تنظر ليلى إلى معطفها الخفيف وتسأل: هل ألبسه؟ تقول الأم: نعم، خذيه معك، ويمكنك أن تخلعيه إذا أصبح الجو دافئًا. قبل الخروج تنظر ليلى إلى السماء مرة أخرى. لا ترى المطر، لكنها ترى غيومًا كثيرة. تقول: الآن أفهم لماذا نختار الملابس حسب السماء والموسم، لا حسب اليوم فقط.","new":[489,451],"reviews":[{"id":"ar-r276","form":"صباح","review_stage":"R3","representation":"running_text"},{"id":"ar-r72","form":"كيف","review_stage":"R3","representation":"other"}],"grammar":[{"id":"ar-a1-sky-weather","role":"new","description":"سماء in simple weather observation"},{"id":"ar-a1-season","role":"new","description":"موسم for a recurring part of the year"}],"discourse":[{"id":"a1-weather-choice","role":"new","description":"connect visible weather to clothing choice"}],"qa":[("gist","ما الذي تقرره ليلى قبل الخروج؟","أن تأخذ معها معطفًا خفيفًا بسبب الجو.",None),("literal_detail","كيف تبدو السماء؟","رمادية وفيها غيوم كثيرة.",["ar-r489"]),("vocabulary_in_context","ماذا تعني «السماء» في النص؟","الجزء الذي تنظر إليه ليلى فوقها لترى الغيوم والجو.",["ar-r489"]),("vocabulary_in_context","ماذا يعني «الموسم»؟","فترة من السنة يكون لها جو متكرر أو مميز.",["ar-r451"]),("cause_effect","لماذا تأخذ ليلى المعطف؟","لأن الجو بارد وقد يتغير خلال اليوم.",None),("single_word_definition","ما معنى «سماء»؟","ما نراه فوق الأرض من فضاء وغيوم.",["ar-r489"]),("single_word_definition","ما معنى «موسم»؟","فترة متكررة من السنة لها صفات أو أحداث معينة.",["ar-r451"]),("contrast","أيهما يتغير كل يوم أسرع عادة: حالة السماء أم الموسم؟","حالة السماء.",["ar-r489","ar-r451"]),("cloze_transfer","أكمل: في _____ غيوم كثيرة اليوم.","السماء",["ar-r489"]),("cloze_transfer","أكمل: الشتاء _____ بارد في بلاد كثيرة.","موسم",["ar-r451"])]},
{"id":"ar-a1-u07-p02","sequence":38,"title":"كم درجة؟","passage_type":"reinforcement","genre":"simple weather conversation","domains":["personal","public"],"topics":["temperature","weather","school"],"text":"قبل المدرسة تنظر أم ليلى إلى تطبيق الطقس وتقول: درجة الحرارة اليوم منخفضة. تسأل ليلى: كم درجة؟ تقول الأم: عشر درجات الآن، وستصبح خمس عشرة بعد الظهر. تنظر ليلى إلى الخارج وتقول: يبدو الجو أبرد مما توقعت. تلبس معطفها وتضع قبعة في الحقيبة. في الطريق ترى الشمس قليلًا، لكن الهواء ما زال باردًا. عند المدرسة تقول مريم: يبدو أن الجميع يلبسون ملابس دافئة اليوم. تقول ليلى: نعم، معرفة درجة الحرارة تساعدني، لكنني أنظر إلى الجو أيضًا قبل أن أقرر ماذا ألبس.","new":[496,111],"reviews":[{"id":"ar-r489","form":"سماء","review_stage":"R1","representation":"other"},{"id":"ar-r451","form":"موسم","review_stage":"R1","representation":"other"}],"grammar":[{"id":"ar-a1-temperature-degree","role":"new","description":"درجة in a simple temperature expression"},{"id":"ar-a1-seems","role":"new","description":"يبدو + adjective/clause"}],"discourse":[{"id":"a1-weather-evidence","role":"new","description":"combine temperature information with observation"}],"qa":[("literal_detail","كم درجة الحرارة في الصباح؟","عشر درجات.",["ar-r496"]),("literal_detail","ماذا تضع ليلى في حقيبتها؟","قبعة.",None),("vocabulary_in_context","ماذا تعني «درجة» في «عشر درجات»؟","وحدة لقياس درجة الحرارة.",["ar-r496"]),("vocabulary_in_context","ماذا يعني «يبدو الجو أبرد»؟","أن الجو يظهر أو يُشعر ليلى بأنه أبرد.",["ar-r111"]),("cause_effect","لماذا تلبس ليلى معطفها؟","لأن درجة الحرارة منخفضة والجو بارد.",None),("single_word_definition","ما معنى «درجة» في الطقس؟","وحدة لقياس الحرارة أو البرودة.",["ar-r496"]),("single_word_definition","ما معنى «يبدو»؟","يظهر أو يعطي انطباعًا معينًا.",["ar-r111"]),("contrast","أيهما قياس للحرارة: «درجة» أم «موسم»؟","درجة.",["ar-r496","ar-r451"]),("cloze_transfer","أكمل: الحرارة اليوم عشرون _____.","درجة",["ar-r496"]),("cloze_transfer","أكمل: من الغيوم _____ أن المطر قريب.","يبدو",["ar-r111"])]},
{"id":"ar-a1-u07-p03","sequence":39,"title":"خطة لليوم القادم","passage_type":"interleaved","genre":"planning dialogue","domains":["personal"],"topics":["plans","weather","future"],"text":"تريد ليلى ومريم الذهاب إلى الحديقة في اليوم القادم. تنظران إلى توقع الطقس. تقول مريم: غدًا قادم بجو أدفأ، لكن ربما يكون هناك مطر في المساء. تقول ليلى: إذن نذهب بعد الظهر ولا نبقى حتى وقت متأخر. تسأل مريم: هل نأخذ مظلة؟ تقول ليلى: ربما، من الأفضل أن تكون معنا إذا تغيرت السماء. تكتبان رسالة إلى هدى وتخبرانهـا بالوقت. ترد هدى: سأأتي إذا لم يكن المطر قويًا. تقول ليلى: الخطة بسيطة؛ ننظر إلى الجو القادم، ونترك مكانًا للتغيير لأن الطقس ليس ثابتًا دائمًا.","new":[363,105],"reviews":[{"id":"ar-r496","form":"درجة","review_stage":"R1","representation":"other"},{"id":"ar-r111","form":"يبدو","review_stage":"R1","representation":"running_text"},{"id":"ar-r85","form":"سوف","review_stage":"R3","representation":"running_text"}],"grammar":[{"id":"ar-a1-coming","role":"new","description":"قادم for the next/coming day or event"},{"id":"ar-a1-maybe","role":"new","description":"ربما for simple possibility"}],"discourse":[{"id":"a1-weather-plan","role":"new","description":"make a simple plan that can change with weather"}],"qa":[("gist","ما الخطة الأساسية؟","الذهاب إلى الحديقة بعد الظهر مع الاستعداد لاحتمال المطر.",None),("literal_detail","متى قد يكون المطر؟","في المساء.",None),("vocabulary_in_context","ماذا يعني «قادم» في «اليوم القادم»؟","اليوم الذي سيأتي بعد اليوم الحالي.",["ar-r363"]),("vocabulary_in_context","ماذا تعني «ربما»؟","أن الأمر ممكن لكنه غير مؤكد.",["ar-r105"]),("cause_effect","لماذا تفكران في أخذ مظلة؟","لأن المطر ممكن وقد تتغير السماء.",None),("single_word_definition","ما معنى «قادم»؟","آتٍ أو سيأتي.",["ar-r363"]),("single_word_definition","ما معنى «ربما»؟","قد يحدث؛ على سبيل الاحتمال.",["ar-r105"]),("contrast","أيهما يدل على اليقين الأقل: «ربما» أم «يجب»؟","ربما.",["ar-r105"]),("cloze_transfer","أكمل: في الأسبوع _____ عندنا نشاط جديد.","القادم",["ar-r363"]),("cloze_transfer","أكمل: _____ أزور صديقي مساءً إذا انتهيت مبكرًا.","ربما",["ar-r105"])]},
{"id":"ar-a1-u07-p04","sequence":40,"title":"صباحات مختلفة","passage_type":"transfer","genre":"short descriptive note","domains":["personal"],"topics":["morning","days","clothes"],"text":"تلاحظ ليلى أن الصباح لا يكون مثل نفسه في كل أيام الأسبوع. في بعض الأيام يكون صباح المدرسة مشمسًا، وفي أيام أخرى يكون باردًا أو كثير الغيوم. يوم الاثنين خرجت بمعطف، ويوم الثلاثاء لم تحتج إليه بعد الظهر. تقول أمها: لا تنظري إلى ملابس أمس فقط؛ انظري إلى صباح اليوم. تضع ليلى ملابسها في مكان واضح مساءً، ثم تغير ما تحتاج إليه في الصباح إذا تغير الجو. خلال أيام قليلة أصبحت تعرف أن اختيار الملابس ليس قرارًا واحدًا لكل الأسبوع. كل صباح له جوه، وكل يوم يمكن أن يحتاج إلى شيء مختلف.","new":[276,232],"reviews":[{"id":"ar-r363","form":"قادم","review_stage":"R1","representation":"other"},{"id":"ar-r105","form":"ربما","review_stage":"R1","representation":"other"},{"id":"ar-r482","form":"قديم","review_stage":"R3","representation":"contrast"}],"grammar":[{"id":"ar-a1-morning","role":"new","description":"صباح as a time-of-day noun/adverbial"},{"id":"ar-a1-days-plural","role":"new","description":"أيام as plural of day"}],"discourse":[{"id":"a1-day-comparison","role":"new","description":"compare simple weather across several days"}],"qa":[("gist","ماذا تعلمت ليلى عن الملابس والطقس؟","أنها تختار الملابس حسب جو كل صباح ويوم.",None),("literal_detail","في أي يوم خرجت بمعطف؟","يوم الاثنين.",None),("vocabulary_in_context","ماذا يعني «صباح»؟","الجزء الأول من اليوم بعد الاستيقاظ.",["ar-r276"]),("vocabulary_in_context","ماذا تعني «أيام»؟","أكثر من يوم واحد.",["ar-r232"]),("cause_effect","لماذا لا تعتمد ليلى على ملابس أمس؟","لأن الجو قد يختلف من يوم إلى آخر.",None),("single_word_definition","ما معنى «صباح»؟","أول جزء من النهار.",["ar-r276"]),("single_word_definition","ما معنى «أيام»؟","جمع يوم.",["ar-r232"]),("contrast","أيهما مدة أطول: يوم واحد أم عدة أيام؟","عدة أيام.",["ar-r232"]),("cloze_transfer","أكمل: أذهب إلى المدرسة في _____ الباكر.","الصباح",["ar-r276"]),("cloze_transfer","أكمل: بقيت هناك ثلاثة _____.","أيام",["ar-r232"])]},
{"id":"ar-a1-u07-p05","sequence":41,"title":"ساعة وأسبوع","passage_type":"checkpoint","genre":"schedule and plan narrative","domains":["personal","public"],"topics":["time","weekly plan","weather"],"text":"تكتب ليلى خطة صغيرة للأسبوع لأنها تريد المشي أكثر عندما يكون الجو مناسبًا. في أعلى الورقة تكتب أيام الأسبوع. بجانب كل يوم تكتب ساعة الخروج المقترحة. يوم الأحد تريد المشي ساعة بعد الظهر. يوم الاثنين لديها واجب كثير، فتختار نصف ساعة فقط. تقول أمها: لا تنسي أن الخطة يمكن أن تتغير إذا كان الجو سيئًا. تنظر ليلى إلى توقعات الأسبوع وتضع علامة بجانب الأيام التي قد تمطر فيها السماء. تقول: لا أريد أن تكون الخطة صعبة؛ أريد فقط أن أعرف متى عندي ساعة حرة، ومتى أحتاج إلى تغيير الوقت خلال الأسبوع.","new":[225,252],"reviews":[{"id":"ar-r276","form":"صباح","review_stage":"R1","representation":"other"},{"id":"ar-r232","form":"أيام","review_stage":"R1","representation":"running_text"},{"id":"ar-r105","form":"ربما","review_stage":"R2","representation":"other"}],"grammar":[{"id":"ar-a1-hour","role":"new","description":"ساعة as one hour / clock time context"},{"id":"ar-a1-week","role":"new","description":"أسبوع as a seven-day period"}],"discourse":[{"id":"a1-week-plan","role":"integration","description":"read a simple weekly plan affected by weather"}],"qa":[("literal_detail","كم تريد ليلى أن تمشي يوم الأحد؟","ساعة.",["ar-r225"]),("literal_detail","لماذا تختار نصف ساعة يوم الاثنين؟","لأن لديها واجبًا كثيرًا.",None),("vocabulary_in_context","ماذا تعني «ساعة» في «المشي ساعة»؟","مدة زمنية مقدارها ستين دقيقة.",["ar-r225"]),("vocabulary_in_context","ماذا يعني «الأسبوع»؟","مجموعة الأيام السبعة التي تنظم فيها ليلى خطتها.",["ar-r252"]),("cause_effect","متى قد تغير ليلى الخطة؟","إذا كان الجو سيئًا أو احتاجت إلى وقت مختلف.",None),("single_word_definition","ما معنى «ساعة» كمدة؟","ستون دقيقة.",["ar-r225"]),("single_word_definition","ما معنى «أسبوع»؟","مدة من سبعة أيام.",["ar-r252"]),("contrast","أيهما أطول: ساعة أم أسبوع؟","أسبوع.",["ar-r225","ar-r252"]),("cloze_transfer","أكمل: بقيت في المكتبة _____ واحدة.","ساعة",["ar-r225"]),("cloze_transfer","أكمل: في هذا _____ عندنا خمسة أيام مدرسة.","الأسبوع",["ar-r252"])]},
{"id":"ar-a1-u07-p06","sequence":42,"title":"الجو والخطة","passage_type":"fluency","genre":"connected weather-and-plan narrative","domains":["personal"],"topics":["weather","clothes","plans","review"],"text":"عندما تستيقظ ليلى في الصباح تنظر إلى السماء وتفكر في يومها. تعرف أن الموسم يؤثر في الجو، لكنها تعرف أيضًا أن الأيام تختلف. تنظر إلى درجة الحرارة، وإذا بدا الجو باردًا تأخذ معطفًا. وإذا كانت السماء كثيرة الغيوم تقول: ربما أحتاج إلى مظلة. عندما يكون عندها نشاط في اليوم القادم لا تفترض أن الطقس سيبقى كما هو، بل تنظر مرة أخرى قبل الخروج. وفي كل أسبوع تعرف متى عندها ساعة حرة للمشي أو الذهاب إلى الحديقة. بهذه الطريقة لا تتحكم حالة الجو في كل خططها، لكنها تساعدها على اختيار الملابس والوقت المناسبين.","new":[],"reviews":[{"id":"ar-r489","form":"سماء","review_stage":"R2","representation":"running_text"},{"id":"ar-r451","form":"موسم","review_stage":"R2","representation":"running_text"},{"id":"ar-r496","form":"درجة","review_stage":"R2","representation":"running_text"},{"id":"ar-r111","form":"يبدو","review_stage":"R2","representation":"running_text"},{"id":"ar-r363","form":"قادم","review_stage":"R2","representation":"running_text"},{"id":"ar-r105","form":"ربما","review_stage":"R2","representation":"running_text"},{"id":"ar-r276","form":"صباح","review_stage":"R2","representation":"running_text"},{"id":"ar-r232","form":"أيام","review_stage":"R2","representation":"running_text"},{"id":"ar-r225","form":"ساعة","review_stage":"R1","representation":"running_text"},{"id":"ar-r252","form":"أسبوع","review_stage":"R1","representation":"running_text"}],"grammar":[{"id":"ar-a1-u07-cumulative","role":"integration","description":"recycle weather observation, possibility, time periods, and simple planning"}],"discourse":[{"id":"a1-weather-fluency","role":"integration","description":"high-coverage weather-and-plan reading"}],"qa":[("gist","ما الفكرة الرئيسية في النص؟","ليلى تستخدم معلومات الطقس لتنظيم الملابس والوقت والخطط.",None),("literal_detail","ماذا تفعل إذا بدا الجو باردًا؟","تأخذ معطفًا.",["ar-r111"]),("literal_detail","ماذا قد تأخذ إذا كانت السماء كثيرة الغيوم؟","مظلة.",["ar-r489","ar-r105"]),("cause_effect","لماذا تنظر إلى الطقس مرة أخرى قبل نشاط قادم؟","لأن الجو قد يتغير.",["ar-r363"]),("summary","لخص طريقة ليلى في التخطيط حسب الطقس.","تنظر إلى السماء والحرارة، تضع احتمال التغير، ثم تختار الملابس والوقت المناسبين.",None),("single_word_definition","ما معنى «موسم»؟","فترة من السنة لها صفات متكررة.",["ar-r451"]),("single_word_definition","ما معنى «ربما»؟","قد يحدث؛ غير مؤكد.",["ar-r105"]),("contrast","أيهما مدة أطول: صباح أم أسبوع؟","أسبوع.",["ar-r276","ar-r252"]),("grammar_function","ماذا تدل «درجة» في سياق الطقس؟","مقدار الحرارة أو البرودة.",["ar-r496"]),("contrast","أيهما يصف وقتًا من اليوم: «صباح» أم «سماء»؟","صباح.",["ar-r276","ar-r489"])]}
]
def lex():
 d={}
 for x in L.read_text(encoding="utf-8").splitlines():
  if x.strip():r=json.loads(x);d[r["rank"]]=r
 return d
def tar(n,text,d):
 f,s,c=T[n];r=d[n];return {"id":f"ar-r{n}","form":f,"lemma":f,"part_of_speech":r.get("part_of_speech_source"),"intended_sense":s,"register":"contemporary standard","variety":"MSA","context_strategy":c,"first_introduced":True,"exposures_in_text":max(1,text.count(f)),"source_lexicon":r.get("source_file"),"source_rank":n,"beyond_base":False}
def build(x,d):
 qs,ans=qa(x["qa"]);text=x["text"];return {"id":x["id"],"language":"ar","cefr":"A1","unit":7,"sequence":x["sequence"],"revision":1,"title":x["title"],"passage_type":x["passage_type"],"genre":x["genre"],"domains":x["domains"],"topics":x["topics"],"text":text,"word_count":len(text.split()),"sentence_count":max(1,len(re.findall(r"[.!؟](?:\s|$)",text))),"estimated_known_token_coverage":0,"new_lexical_targets":[tar(n,text,d) for n in x["new"]],"review_lexical_targets":x["reviews"],"grammar_targets":x["grammar"],"discourse_targets":x["discourse"],"questions":qs,"answer_key":ans,"speed_training":{"timed":x["passage_type"]=="fluency","benchmark_eligible":False,"comprehension_gate":0.8,"new_word_policy":"none" if x["passage_type"]=="fluency" else "controlled","notes":"Generation-stage passage; formal fluency/coverage decision deferred to final audit."},"quality":{"status":"draft","linguistic_review":"pending","pedagogical_review":"pending","coverage_check":"pending","answer_key_check":"pending","schema_check":"pending","fact_check":"not_required","notes":["High-quality generation-stage draft; formal audits deferred to the final multi-pass review phase."]},"paired_text_group":None,"prerequisites":[],"difficulty_notes_internal":None,"reader_tags":["unit_role:"+x["passage_type"],"generation_batch"],"complexity_profile":{"mean_sentence_length":None,"median_sentence_length":None,"clause_count":None,"subordination_count":None,"coordination_count":None,"connective_diversity":None,"lexical_diversity":None,"reference_chain_max_distance":None,"multiword_expression_count":None,"morphology_notes":"A1 generation-stage draft; transparent contemporary MSA.","inference_depth":"local"}}
def main():
 old=[json.loads(z) for z in P.read_text(encoding="utf-8").splitlines() if z.strip()];old=[x for x in old if x.get("unit")!=7];d=lex();new=[build(x,d) for x in R]
 if len(new)!=6 or any(len(x["questions"])!=10 or len(x["answer_key"])!=10 for x in new):raise SystemExit("Unit07 generation contract failed")
 rows=sorted(old+new,key=lambda x:(x.get("unit",0),x.get("sequence",0)));P.write_text("".join(json.dumps(x,ensure_ascii=False,sort_keys=True)+"\n" for x in rows),encoding="utf-8")
 print("generated Arabic A1 Unit 07: six passages, sixty questions, sixty answers")
if __name__=="__main__":main()
