#!/usr/bin/env python3
"""Generate Arabic A1 Unit 05: school and basic work."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
PASSAGES=ROOT/"reading"/"arabic"/"a1"/"passages.jsonl"
LEXICON=ROOT/"reading"/"lexicons"/"arabic.jsonl"
TARGETS={
177:("بدأ","began; started",["scenario_resolution"]),181:("يأتي","comes; arrives",["scenario_resolution"]),
169:("مدير","director; manager; school principal in context",["category_relation"]),184:("يوجد","there is; exists; is present",["scenario_resolution"]),
176:("دور","role; turn; function",["category_relation","example_instance"]),188:("داخل","inside; within",["contrast","scenario_resolution"]),
196:("يتحدث","speaks; talks",["behavior_interpretation"]),128:("يعمل","works; operates",["behavior_interpretation"]),
197:("مقبل","next; coming",["contrast","scenario_resolution"]),201:("يعود","returns; goes back",["scenario_resolution"]),
}
def qa(items):
 qs=[];ans=[]
 for i,(t,p,a,ids) in enumerate(items,1):
  q={"id":f"q{i}","type":t,"prompt":p,"answer_id":f"a{i}"}
  if ids:q["target_ids"]=ids
  qs.append(q);ans.append({"id":f"a{i}","question_id":f"q{i}","answer":a,"explanation":""})
 if len(qs)!=10:raise ValueError
 return qs,ans
RAW=[
{"id":"ar-a1-u05-p01","sequence":25,"title":"بداية اليوم الدراسي","passage_type":"instructional","genre":"day-in-the-life narrative","domains":["educational"],"topics":["school","arrival","class"],
"text":"تصل ليلى إلى المدرسة قبل الثامنة بقليل. بعض الطلاب في الساحة، وبعضهم داخل الصف. عندما يأتي المعلم يدخل الجميع ويجلسون. ينظر المعلم إلى الساعة ويقول: الآن يبدأ الدرس. بدأ اليوم بقراءة قصيرة، ثم كتب الطلاب جملًا في دفاترهم. بعد ذلك يأتي طالب كان عند المدير ويدخل بهدوء. يقول المعلم: مرحبًا، اجلس هنا. في وقت الاستراحة تخرج ليلى مع مريم. تقول مريم: أحب أن يأتي المعلم في الوقت، لأن الدرس يبدأ منظمًا. تقول ليلى: وأنا أيضًا. بعد الاستراحة يعود الطلاب ويبدأ درس آخر. تعرف ليلى أن لكل جزء من اليوم وقتًا واضحًا.",
"new_ranks":[177,181],"reviews":[{"id":"ar-r61","form":"وقت","review_stage":"R3","representation":"running_text"},{"id":"ar-r127","form":"مرحبا","review_stage":"R3","representation":"running_text"}],
"grammar":[{"id":"ar-a1-start","role":"new","description":"بدأ/يبدأ for beginning an activity"},{"id":"ar-a1-come","role":"new","description":"يأتي for arrival/coming"}],"discourse":[{"id":"a1-school-sequence","role":"new","description":"follow the start of a school day"}],
"qa":[("gist","ما الفكرة الرئيسية في النص؟","بداية يوم ليلى الدراسي وترتيب الدروس.",None),("literal_detail","ماذا يحدث عندما يأتي المعلم؟","يدخل الجميع ويجلسون ويبدأ الدرس.",None),("vocabulary_in_context","ماذا يعني «بدأ» في «بدأ اليوم بقراءة قصيرة»؟","أن القراءة كانت أول نشاط في اليوم.",["ar-r177"]),("vocabulary_in_context","ماذا يعني «يأتي» في «يأتي المعلم»؟","يصل المعلم إلى المكان.",["ar-r181"]),("sequence","ماذا يحدث بعد الاستراحة؟","يعود الطلاب ويبدأ درس آخر.",None),("single_word_definition","ما معنى «بدأ»؟","شرع في الشيء أو جعله يبدأ.",["ar-r177"]),("single_word_definition","ما معنى «يأتي»؟","يصل أو يحضر إلى المكان.",["ar-r181"]),("contrast","أيهما يدل على الوصول: «يأتي» أم «يعود»؟","يأتي يدل على المجيء أو الوصول، أما يعود فيدل على الرجوع.",["ar-r181"]),("cloze_transfer","أكمل: _____ الدرس في الثامنة.","بدأ",["ar-r177"]),("cloze_transfer","أكمل: المعلم _____ إلى الصف الآن.","يأتي",["ar-r181"]) ]},
{"id":"ar-a1-u05-p02","sequence":26,"title":"في مكتب المدرسة","passage_type":"reinforcement","genre":"simple office scene","domains":["educational","public"],"topics":["school","office","people"],
"text":"بعد الدرس تقول المعلمة لليلى: خذي هذه الورقة إلى مكتب المدير. تذهب ليلى إلى آخر الممر. يوجد باب عليه اسم المدير. تطرق الباب، ثم تدخل. المدير يجلس عند مكتبه ويتحدث مع موظفة. عندما ينتهي الحديث يقول: مرحبًا يا ليلى، ماذا عندك؟ تعطيه الورقة. يسألها: هل يوجد شيء آخر؟ تقول: لا، هذه فقط. يشكرها المدير ويضع الورقة على الطاولة. تنظر ليلى حولها. يوجد في المكتب كرسيان وخزانة صغيرة وكتب. قبل أن تخرج تقول: شكرًا. تعود إلى صفها وتخبر المعلمة أن الورقة عند المدير الآن.",
"new_ranks":[169,184],"reviews":[{"id":"ar-r177","form":"بدأ","review_stage":"R1","representation":"other"},{"id":"ar-r181","form":"يأتي","review_stage":"R1","representation":"other"},{"id":"ar-r152","form":"اسم","review_stage":"R3","representation":"running_text"}],
"grammar":[{"id":"ar-a1-school-manager","role":"new","description":"مدير as the person responsible for a school/office"},{"id":"ar-a1-there-is","role":"new","description":"يوجد for stating presence/existence"}],"discourse":[{"id":"a1-office-task","role":"new","description":"follow a simple errand in a school office"}],
"qa":[("literal_detail","لماذا تذهب ليلى إلى مكتب المدير؟","لتعطيه ورقة من المعلمة.",None),("literal_detail","ماذا يوجد في المكتب؟","كرسيان وخزانة صغيرة وكتب.",["ar-r184"]),("vocabulary_in_context","من هو «المدير» في هذا السياق؟","الشخص المسؤول عن المدرسة أو إدارتها.",["ar-r169"]),("vocabulary_in_context","ماذا تعني «يوجد» في «يوجد باب»؟","أن الباب حاضر أو موجود في المكان.",["ar-r184"]),("sequence","ماذا تفعل ليلى بعد إعطاء الورقة؟","تنتظر، ثم تشكر المدير وتعود إلى صفها.",None),("single_word_definition","ما معنى «مدير»؟","شخص يدير مكانًا أو عملًا.",["ar-r169"]),("single_word_definition","ما معنى «يوجد»؟","يكون حاضرًا أو موجودًا.",["ar-r184"]),("contrast","أيهما شخص: «مدير» أم «مكتب»؟","مدير.",["ar-r169"]),("cloze_transfer","أكمل: _____ كتاب على الطاولة.","يوجد",["ar-r184"]),("cloze_transfer","أكمل: _____ المدرسة يتحدث مع المعلمين.","مدير",["ar-r169"]) ]},
{"id":"ar-a1-u05-p03","sequence":27,"title":"دور كل طالب","passage_type":"interleaved","genre":"simple explanation with activity","domains":["educational"],"topics":["classroom","roles","inside outside"],
"text":"في حصة صغيرة يقسم المعلم الطلاب إلى مجموعات. يقول: لكل شخص دور. دور ليلى أن تقرأ السؤال، ودور مريم أن تكتب الجواب، ودور سامر أن يعرض النتيجة. يعمل الطلاب داخل الصف لأن الجو خارج المدرسة بارد. عندما تنتهي المجموعة من السؤال الأول يبدلون الأدوار. تقول مريم: الآن دوري أن أقرأ. يقول المعلم: جيد، المهم أن يعرف كل طالب دوره. بعد قليل يخرج بعض الطلاب إلى الساحة، لكن مجموعة ليلى تبقى داخل الصف حتى تنهي العمل. تسأل ليلى: هل يمكن أن نخرج بعد ذلك؟ يقول المعلم: نعم، عندما ينتهي دوركم في النشاط.",
"new_ranks":[176,188],"reviews":[{"id":"ar-r169","form":"مدير","review_stage":"R1","representation":"other"},{"id":"ar-r184","form":"يوجد","review_stage":"R1","representation":"other"},{"id":"ar-r99","form":"شخص","review_stage":"R3","representation":"running_text"},{"id":"ar-r182","form":"خارج","review_stage":"R3","representation":"contrast"}],
"grammar":[{"id":"ar-a1-role","role":"new","description":"دور for a simple assigned task/turn"},{"id":"ar-a1-inside","role":"new","description":"داخل as spatial adverb/preposition"}],"discourse":[{"id":"a1-group-task","role":"new","description":"track roles in a simple collaborative task"}],
"qa":[("literal_detail","ما دور ليلى في البداية؟","أن تقرأ السؤال.",["ar-r176"]),("cause_effect","لماذا يعمل الطلاب داخل الصف؟","لأن الجو خارج المدرسة بارد.",["ar-r188"]),("vocabulary_in_context","ماذا يعني «دور» في «لكل شخص دور»؟","المهمة أو الجزء الذي يقوم به كل شخص.",["ar-r176"]),("vocabulary_in_context","ماذا يعني «داخل» في «داخل الصف»؟","في الجهة الداخلية من الصف.",["ar-r188"]),("sequence","ماذا يحدث عندما تنتهي المجموعة من السؤال الأول؟","يبدلون الأدوار.",None),("single_word_definition","ما معنى «دور» هنا؟","المهمة أو الجزء الذي على الشخص القيام به.",["ar-r176"]),("single_word_definition","ما معنى «داخل»؟","في باطن المكان أو في جهته الداخلية.",["ar-r188"]),("contrast","أيهما عكس «خارج» في المكان: «داخل» أم «أمام»؟","داخل.",["ar-r188"]),("cloze_transfer","أكمل: دوري أن أكتب، و_____ أخي أن يقرأ.","دور",["ar-r176"]),("cloze_transfer","أكمل: الطلاب _____ الصف الآن.","داخل",["ar-r188"]) ]},
{"id":"ar-a1-u05-p04","sequence":28,"title":"نادي القراءة","passage_type":"transfer","genre":"club scene","domains":["educational","public"],"topics":["school club","speaking","work"],
"text":"بعد المدرسة تذهب ليلى إلى نادي القراءة. يعمل النادي في غرفة صغيرة داخل المدرسة مرتين في الأسبوع. في البداية يتحدث المعلم عن كتاب قصير. ثم يعمل الطلاب في أزواج. تقرأ ليلى صفحة، ويتحدث سامر عن الفكرة الرئيسية. تقول ليلى: أنا أحب أن أقرأ، لكنني أريد أن أتحدث أكثر أيضًا. يقول المعلم: هذا جيد؛ من يتحدث عن النص يفهمه بطريقة أخرى. في جزء آخر من النشاط يعمل كل طالب وحده لخمس دقائق ويكتب سؤالًا. بعد ذلك يتحدث الجميع عن أسئلتهم. عندما ينتهي النادي تعود ليلى إلى المنزل وتخبر أمها: اليوم قرأت وعملت وتحدثت كثيرًا، وكان النشاط مفيدًا.",
"new_ranks":[196,128],"reviews":[{"id":"ar-r176","form":"دور","review_stage":"R1","representation":"other"},{"id":"ar-r188","form":"داخل","review_stage":"R1","representation":"running_text"},{"id":"ar-r76","form":"يقول","review_stage":"R3","representation":"running_text"}],
"grammar":[{"id":"ar-a1-speak","role":"new","description":"يتحدث عن + topic"},{"id":"ar-a1-work","role":"new","description":"يعمل for doing work/activity"}],"discourse":[{"id":"a1-club-activity","role":"new","description":"follow alternating reading, speaking, and work tasks"}],
"qa":[("gist","ما الذي يفعله الطلاب في نادي القراءة؟","يقرؤون ويتحدثون ويكتبون أسئلة عن النصوص.",None),("literal_detail","كم مرة يعمل النادي في الأسبوع؟","مرتين.",None),("vocabulary_in_context","ماذا يعني «يتحدث» في «يتحدث المعلم عن كتاب»؟","يتكلم عن الكتاب ويشرح أفكاره.",["ar-r196"]),("vocabulary_in_context","ماذا يعني «يعمل» في «يعمل الطلاب في أزواج»؟","يقومون بنشاط أو مهمة معًا.",["ar-r128"]),("cause_effect","لماذا يقول المعلم إن الحديث عن النص جيد؟","لأنه يساعد على فهم النص بطريقة أخرى.",None),("single_word_definition","ما معنى «يتحدث»؟","يتكلم أو يجري حديثًا.",["ar-r196"]),("single_word_definition","ما معنى «يعمل»؟","يقوم بعمل أو مهمة.",["ar-r128"]),("contrast","أيهما يتعلق بالكلام مباشرة: «يتحدث» أم «يعمل»؟","يتحدث.",["ar-r196","ar-r128"]),("cloze_transfer","أكمل: الطالب _____ عن كتابه أمام الصف.","يتحدث",["ar-r196"]),("cloze_transfer","أكمل: أبي _____ في مكتب قريب.","يعمل",["ar-r128"]) ]},
{"id":"ar-a1-u05-p05","sequence":29,"title":"الأسبوع المقبل","passage_type":"checkpoint","genre":"school notice and narrative","domains":["educational"],"topics":["school","next week","return"],
"text":"في آخر اليوم يقرأ المعلم إعلانًا قصيرًا: «في الأسبوع المقبل سيكون عندنا يوم للقراءة. يأتي الطلاب بكتاب يحبونه، ويعملون في مجموعات صغيرة.» تسأل ليلى: هل سيكون النادي في اليوم نفسه؟ يقول المعلم: لا، سيعود النادي إلى موعده العادي بعد يوم القراءة. تكتب ليلى الموعد في دفترها حتى لا تنساه. في البيت تخبر أمها: الأسبوع المقبل عندنا نشاط جديد، وسوف آخذ كتاب المكتبة. تقول أمها: ومتى يعود الكتاب إلى المكتبة؟ تنظر ليلى إلى الورقة وتقول: يعود بعد النشاط بيوم. في اليوم المقبل تبدأ ليلى في اختيار الكتاب الذي ستأخذه، وتعرف أنها ستعود إلى المدرسة مستعدة.",
"new_ranks":[197,201],"reviews":[{"id":"ar-r196","form":"يتحدث","review_stage":"R1","representation":"other"},{"id":"ar-r128","form":"يعمل","review_stage":"R1","representation":"running_text"},{"id":"ar-r85","form":"سوف","review_stage":"R3","representation":"running_text"}],
"grammar":[{"id":"ar-a1-next","role":"new","description":"مقبل for the next/coming time period"},{"id":"ar-a1-return","role":"new","description":"يعود for returning to a place/state"}],"discourse":[{"id":"a1-notice-plan","role":"integration","description":"extract a simple future plan from a notice"}],
"qa":[("literal_detail","ما النشاط الذي سيحدث في الأسبوع المقبل؟","يوم للقراءة.",["ar-r197"]),("literal_detail","متى يعود الكتاب إلى المكتبة؟","بعد النشاط بيوم.",["ar-r201"]),("vocabulary_in_context","ماذا يعني «المقبل» في «الأسبوع المقبل»؟","الأسبوع الذي سيأتي بعد الأسبوع الحالي.",["ar-r197"]),("vocabulary_in_context","ماذا يعني «يعود» في «يعود الكتاب إلى المكتبة»؟","يرجع إلى المكتبة بعد أن كان خارجها.",["ar-r201"]),("sequence","ماذا تفعل ليلى قبل يوم القراءة؟","تكتب الموعد وتختار الكتاب الذي ستأخذه.",None),("single_word_definition","ما معنى «مقبل»؟","قادِم أو آتٍ بعد الوقت الحالي.",["ar-r197"]),("single_word_definition","ما معنى «يعود»؟","يرجع إلى المكان أو الحالة السابقة.",["ar-r201"]),("contrast","أيهما يدل على الرجوع: «يأتي» أم «يعود»؟","يعود.",["ar-r181","ar-r201"]),("cloze_transfer","أكمل: في الشهر _____ سأزور صديقي.","المقبل",["ar-r197"]),("cloze_transfer","أكمل: بعد المدرسة _____ الطالب إلى المنزل.","يعود",["ar-r201"]) ]},
{"id":"ar-a1-u05-p06","sequence":30,"title":"يوم في المدرسة","passage_type":"fluency","genre":"connected school-day narrative","domains":["educational"],"topics":["school","work","review"],
"text":"في يوم المدرسة يأتي الطلاب قبل بدء الدرس بقليل. عندما يدخل المعلم يبدأ العمل. يوجد في المدرسة أشخاص كثيرون، ولكل شخص دور. المدير يعمل في مكتبه، والمعلمون يعملون داخل الصفوف، والطلاب يقرؤون ويكتبون ويتحدثون عن الدروس. أحيانًا تعمل ليلى مع مجموعة، وأحيانًا يكون دورها أن تقرأ وحدها. إذا كان عندها سؤال يمكن أن تذهب إلى المعلم أو إلى المدير. بعد الدروس قد تذهب إلى نادي القراءة، حيث يتحدث الطلاب عن الكتب ويعملون على أسئلة قصيرة. في الأسبوع المقبل يوجد نشاط جديد، وبعده يعود كل شيء إلى الموعد العادي. في نهاية اليوم تعود ليلى إلى المنزل وهي تعرف ماذا بدأت، وماذا أنجزت، ومتى ستعود إلى المدرسة.",
"new_ranks":[],"reviews":[{"id":"ar-r177","form":"بدأ","review_stage":"R2","representation":"running_text"},{"id":"ar-r181","form":"يأتي","review_stage":"R2","representation":"running_text"},{"id":"ar-r169","form":"مدير","review_stage":"R2","representation":"running_text"},{"id":"ar-r184","form":"يوجد","review_stage":"R2","representation":"running_text"},{"id":"ar-r176","form":"دور","review_stage":"R2","representation":"running_text"},{"id":"ar-r188","form":"داخل","review_stage":"R2","representation":"running_text"},{"id":"ar-r196","form":"يتحدث","review_stage":"R2","representation":"running_text"},{"id":"ar-r128","form":"يعمل","review_stage":"R2","representation":"running_text"},{"id":"ar-r197","form":"مقبل","review_stage":"R1","representation":"running_text"},{"id":"ar-r201","form":"يعود","review_stage":"R1","representation":"running_text"}],
"grammar":[{"id":"ar-a1-u05-cumulative","role":"integration","description":"recycle school roles, presence, location, work, speech, future and return"}],"discourse":[{"id":"a1-school-fluency","role":"integration","description":"high-coverage cumulative school/work reading"}],
"qa":[("gist","ما الفكرة الرئيسية في النص؟","كيف يعمل يوم المدرسة وما أدوار الأشخاص فيه.",None),("literal_detail","أين يعمل المدير؟","في مكتبه.",["ar-r169"]),("literal_detail","ماذا يفعل الطلاب في نادي القراءة؟","يتحدثون عن الكتب ويعملون على أسئلة قصيرة.",["ar-r196","ar-r128"]),("reference_resolution","إلى ماذا تشير «داخـل الصفوف»؟","إلى المكان الموجود في الجهة الداخلية من الصفوف.",["ar-r188"]),("summary","لخص يوم المدرسة في جملة واحدة.","يأتي الطلاب، يبدأ الدرس، يعمل الجميع حسب دوره، ثم تعود ليلى إلى المنزل.",None),("single_word_definition","ما معنى «يوجد»؟","يكون حاضرًا أو موجودًا.",["ar-r184"]),("single_word_definition","ما معنى «دور» في المدرسة؟","المهمة أو الجزء الذي يقوم به الشخص.",["ar-r176"]),("contrast","أيهما يدل على الكلام: «يتحدث» أم «يعود»؟","يتحدث.",["ar-r196","ar-r201"]),("grammar_function","ماذا يدل «المقبل» في «الأسبوع المقبل»؟","على الأسبوع الآتي بعد الحالي.",["ar-r197"]),("contrast","أيهما يدل على الرجوع إلى المكان: «يأتي» أم «يعود»؟","يعود.",["ar-r181","ar-r201"]) ]}
]
def lex_by_rank():
 out={}
 for l in LEXICON.read_text(encoding="utf-8").splitlines():
  if l.strip():
   r=json.loads(l);out[r["rank"]]=r
 return out
def target(rank,text,lex):
 form,sense,strat=TARGETS[rank];src=lex[rank]
 return {"id":f"ar-r{rank}","form":form,"lemma":form,"part_of_speech":src.get("part_of_speech_source"),"intended_sense":sense,"register":"contemporary standard","variety":"MSA","context_strategy":strat,"first_introduced":True,"exposures_in_text":max(1,text.count(form)),"source_lexicon":src.get("source_file"),"source_rank":rank,"beyond_base":False}
def build(raw,lex):
 qs,ans=qa(raw["qa"]);text=raw["text"]
 return {"id":raw["id"],"language":"ar","cefr":"A1","unit":5,"sequence":raw["sequence"],"revision":1,"title":raw["title"],"passage_type":raw["passage_type"],"genre":raw["genre"],"domains":raw["domains"],"topics":raw["topics"],"text":text,"word_count":len(text.split()),"sentence_count":max(1,len(re.findall(r"[.!؟](?:\s|$)",text))),"estimated_known_token_coverage":0,"new_lexical_targets":[target(r,text,lex) for r in raw["new_ranks"]],"review_lexical_targets":raw["reviews"],"grammar_targets":raw["grammar"],"discourse_targets":raw["discourse"],"questions":qs,"answer_key":ans,"speed_training":{"timed":raw["passage_type"]=="fluency","benchmark_eligible":False,"comprehension_gate":0.8,"new_word_policy":"none" if raw["passage_type"]=="fluency" else "controlled","notes":"Generation-stage passage; formal fluency/coverage decision deferred to final audit."},"quality":{"status":"draft","linguistic_review":"pending","pedagogical_review":"pending","coverage_check":"pending","answer_key_check":"pending","schema_check":"pending","fact_check":"not_required","notes":["High-quality generation-stage draft; formal audits deferred to the final multi-pass review phase."]},"paired_text_group":None,"prerequisites":[],"difficulty_notes_internal":None,"reader_tags":["unit_role:"+raw["passage_type"],"generation_batch"],"complexity_profile":{"mean_sentence_length":None,"median_sentence_length":None,"clause_count":None,"subordination_count":None,"coordination_count":None,"connective_diversity":None,"lexical_diversity":None,"reference_chain_max_distance":None,"multiword_expression_count":None,"morphology_notes":"A1 generation-stage draft; transparent contemporary MSA.","inference_depth":"local"}}
def main():
 existing=[json.loads(x) for x in PASSAGES.read_text(encoding="utf-8").splitlines() if x.strip()];existing=[r for r in existing if r.get("unit")!=5]
 lex=lex_by_rank();new=[build(r,lex) for r in RAW]
 if len(new)!=6 or any(len(r["questions"])!=10 or len(r["answer_key"])!=10 for r in new):raise SystemExit("Unit 05 generation contract failed")
 rows=sorted(existing+new,key=lambda r:(r.get("unit",0),r.get("sequence",0)));PASSAGES.write_text("".join(json.dumps(r,ensure_ascii=False,sort_keys=True)+"\n" for r in rows),encoding="utf-8")
 print("generated Arabic A1 Unit 05: six passages, sixty questions, sixty answers")
if __name__=="__main__":main()
