#!/usr/bin/env python3
"""Append French B2 Unit04 (seq19-24): cities and design.

Requires exact Unit03 lock and Unit04 probe. Four fresh targets in P01-P05,
zero new in P06; schema, source, freshness, linkage, word-band and exact-review
guards remain fail-closed.
"""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
REPO=Path(__file__).resolve().parents[2]
A1=REPO/'reading/french/a1/passages.jsonl';A2=REPO/'reading/french/a2/passages.jsonl';B1=REPO/'reading/french/b1/passages.jsonl';CANON=REPO/'reading/french/b2/passages.jsonl';SCHEMA=REPO/'reading/schema/passage.schema.json';LOCK=REPO/'reading/audit/french_b2_unit03_frontier_lock.json';PROBE=REPO/'reading/audit/french_b2_unit04_target_probe.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca','B2':'e97d0929a5ea7aa09a7306a82f9159194ff954da'}
FORMS=('coin','côté','arbre','air','voiture','proche','besoin','simple','construire','ouvrir','fermer','utiliser','haut','bas','monter','descendre','entrer','sortir','servir','nouveau')
SPECS=[
{'id':'fr-b2-u04-p01','sequence':19,'ptype':'instructional','title':'Un petit coin de place peut changer la manière dont tout un espace fonctionne','genre':'report','domains':['public'],'topics':['cities and design','public space','microclimate'],'forms':['coin','côté','arbre','air'],'reviews':['juste','chance','groupe','réussir'],'paragraphs':[
"Une ville fictive observe une petite place entourée de commerces et d’un arrêt de transport. Le rapport ne demande pas d’abord si la place est belle, mais comment elle est réellement utilisée. À midi, le coin situé près de la boulangerie reste presque vide alors que l’autre côté accueille plusieurs groupes. La différence ne vient pas d’une interdiction : un arbre ancien crée de l’ombre près des bancs, tandis que le coin opposé reçoit le soleil pendant plusieurs heures. Le rapport note aussi que l’air paraît moins immobile du côté ouvert sur une rue secondaire. L’objectif est de comprendre si un changement limité peut rendre l’usage plus juste entre les différentes parties de la place.",
"Les observateurs comptent les personnes à plusieurs moments, mais ils refusent de traiter leurs chiffres comme une preuve parfaite. Un jour froid peut modifier les habitudes, un événement peut attirer un groupe particulier et un commerce peut fermer temporairement. Ils décrivent donc des tendances plutôt qu’une vérité définitive. Malgré ces limites, une régularité apparaît : lorsqu’un arbre ou une structure légère protège du soleil, les gens ont davantage de chance de rester. Le rapport propose de tester d’abord un dispositif temporaire dans le coin le moins utilisé au lieu de refaire toute la place.",
"Le test comprend une toile d’ombre, deux bancs mobiles et quelques plantes en bac. Le côté concerné doit rester accessible aux livraisons le matin, donc rien n’est fixé au sol. Pendant six semaines, l’équipe mesure le temps de présence, interroge les commerçants et observe si la circulation de l’air est bloquée. Le but n’est pas de réussir à remplir chaque siège. Une place publique doit aussi permettre de traverser, d’attendre brièvement ou de rester seul. Le groupe cherche plutôt à savoir si l’aménagement élargit les usages sans déplacer le problème vers un autre côté.",
"La conclusion recommande une décision réversible. Si le coin devient plus fréquenté sans gêner les accès, la ville pourra planter un nouvel arbre ou installer une protection durable. Si l’air circule moins bien ou si les livraisons deviennent difficiles, la solution pourra être modifiée. Le rapport défend ainsi une conception du design fondée sur l’observation : un détail placé au bon endroit peut changer l’équilibre général, mais il faut laisser une chance au test de révéler ses effets avant de déclarer qu’une solution est juste ou qu’elle va nécessairement réussir."
],
'grammar':[{'id':'fr-b2-u04-spatial-comparison','role':'new','description':'compare spatial effects using côté, coin, tandis que and conditional test language'}],
'discourse':[{'id':'fr-b2-u04-observation-to-design','role':'new','description':'move from observed spatial pattern to reversible design test with limitations and evaluation criteria'}],
'items':[
('main_claim','Quelle approche de design le rapport défend-il ?','Tester un changement local et réversible à partir des usages observés avant de transformer durablement toute la place.',['coin','côté']),
('literal_detail','Quels éléments composent le test temporaire ?','Une toile d’ombre, deux bancs mobiles et quelques plantes en bac.',['coin']),
('argument_relation','Pourquoi le rapport ne conclut-il pas qu’un arbre suffit toujours ?','Parce que les usages dépendent aussi de la météo, des accès, des événements et de la circulation de l’air.',['arbre','air']),
('vocabulary_in_context','Que signifie « côté » dans le passage ?','Une partie ou orientation de la place comparée à une autre.',['côté']),
('vocabulary_in_context','Quel rôle joue « air » dans l’évaluation ?','Il désigne la circulation de l’air, qui peut être améliorée ou gênée par l’aménagement.',['air']),
('assumption','Quelle hypothèse justifie le test d’ombre ?','Que le confort thermique contribue réellement à la différence d’usage entre les deux parties.',['arbre','chance']),
('inference','Pourquoi les éléments restent-ils mobiles ?','Pour garder la possibilité de corriger le design si le test produit des effets indésirables.',['coin','juste']),
('reference_resolution','Dans « l’autre côté », à quoi s’oppose cette expression ?','Au coin près de la boulangerie qui reste presque vide à midi.',['côté','coin']),
('stance','Quelle position le rapport adopte-t-il envers une transformation immédiate ?','Il préfère donner une chance à un test limité avant d’engager une transformation durable.',['chance']),
('summary','Résume le rapport.','Le groupe compare chaque côté de la place, teste dans un coin l’effet d’un arbre ou d’une protection sur l’air et les usages, puis demande si cette méthode peut réussir de façon juste avant de rendre le changement permanent.',['groupe','côté','coin','arbre','air','réussir','juste','chance'])]},
{'id':'fr-b2-u04-p02','sequence':20,'ptype':'reinforcement','title':'Une rue devant une école : faut-il une règle simple pour la voiture ?','genre':'proposal','domains':['public','educational'],'topics':['cities and design','school street','access trade-offs'],'forms':['voiture','proche','besoin','simple'],'reviews':['permettre','refuser','accord','obliger'],'paragraphs':[
"Une école fictive se trouve dans une rue étroite où de nombreuses familles arrivent à la même heure. Une proposition municipale veut limiter la voiture devant l’entrée pendant trente minutes le matin et l’après-midi. L’idée paraît simple : réduire les véhicules au moment où les enfants traversent. Pourtant, plusieurs familles expliquent qu’elles ont besoin d’un accès proche parce qu’un enfant marche difficilement, qu’un parent transporte du matériel lourd ou qu’un trajet combine plusieurs obligations. Le projet doit donc permettre une rue plus calme sans obliger chaque famille à utiliser exactement le même moyen de déplacement.",
"La première version prévoit de fermer toute la rue à toute voiture. Un groupe de parents refuse cette règle parce qu’elle ne distingue aucune situation. La seconde version crée une zone de dépose à cent cinquante mètres et maintient quelques autorisations près de l’école pour des besoins définis. L’accord entre l’école et la ville précise que ces exceptions ne sont pas des privilèges personnels : elles répondent à un besoin fonctionnel vérifiable. Une règle simple reste utile pour être comprise rapidement, mais elle peut devenir injuste si elle ignore des différences directement liées à l’accès.",
"Le projet propose alors trois mesures complémentaires. D’abord, la rue devient temporairement réservée aux piétons et aux véhicules autorisés. Ensuite, un point proche mais extérieur à la zone permet aux autres voitures de déposer les enfants sans faire demi-tour devant l’école. Enfin, des bénévoles observent pendant un mois les conflits, les retards et les détours créés. La ville veut savoir si la réduction de la voiture améliore réellement la situation ou si elle déplace simplement la circulation vers une rue voisine. Elle refuse donc de présenter la fermeture comme un résultat déjà acquis.",
"La proposition se termine par une règle de révision. Si trop de demandes d’exception apparaissent, la ville devra vérifier si le critère répond au bon besoin ou s’il est devenu trop large. Si la zone de dépose reste vide, elle devra demander pourquoi. Le texte défend un compromis : une règle simple peut rendre l’espace lisible, mais l’accord doit aussi permettre des exceptions proches de l’objectif, sans obliger des personnes à supporter un coût disproportionné. Le design urbain n’est alors pas seulement la forme de la rue ; c’est aussi la manière dont une règle organise qui peut y arriver, quand et avec quelle voiture."
],
'grammar':[{'id':'fr-b2-u04-rule-exception','role':'new','description':'express general rule, functional need and bounded exception with si and sans obliger'}],
'discourse':[{'id':'fr-b2-u04-access-tradeoff','role':'new','description':'balance traffic reduction, accessibility needs, exceptions and displacement effects in a proposal'}],
'items':[
('main_claim','Quel compromis la proposition défend-elle ?','Limiter les voitures aux heures critiques tout en prévoyant des exceptions fonctionnelles et une zone de dépose proche.',['voiture','proche','besoin']),
('literal_detail','Où se trouve la zone de dépose proposée ?','À environ cent cinquante mètres de l’école, hors de la zone temporairement réservée.',['proche']),
('argument_relation','Pourquoi la fermeture totale est-elle rejetée ?','Parce qu’une règle identique pour tous peut ignorer certains besoins directement liés à l’accès.',['simple','besoin','refuser']),
('vocabulary_in_context','Que signifie « besoin » dans le texte ?','Une nécessité fonctionnelle liée à l’accès, et non une simple préférence personnelle.',['besoin']),
('vocabulary_in_context','Pourquoi la règle est-elle dite « simple » ?','Parce qu’elle doit être comprise et appliquée rapidement, même si des exceptions limitées restent nécessaires.',['simple']),
('assumption','Quelle hypothèse justifie la limitation de la voiture ?','Que la concentration de véhicules aux heures d’entrée contribue aux conflits et aux difficultés de circulation.',['voiture']),
('inference','Pourquoi observer aussi les rues voisines ?','Pour vérifier que la mesure ne déplace pas simplement le problème ailleurs.',['voiture']),
('reference_resolution','Dans « elle devra demander pourquoi », qui est « elle » ?','La ville responsable d’évaluer et de réviser le dispositif.',['besoin']),
('stance','Quelle position le texte adopte-t-il envers les exceptions ?','Il les accepte lorsqu’elles répondent à un besoin défini sans détruire l’objectif commun de la règle.',['permettre','accord','besoin']),
('summary','Résume la proposition.','La ville cherche un accord qui permette de limiter la voiture avec une règle simple, refuse d’obliger tout le monde de la même façon et garde un accès proche lorsque le besoin le justifie.',['accord','permettre','voiture','simple','refuser','obliger','proche','besoin'])]},
{'id':'fr-b2-u04-p03','sequence':21,'ptype':'interleaved','title':'Construire une bibliothèque ouverte ne signifie pas ouvrir chaque espace tout le temps','genre':'critique','domains':['public','educational'],'topics':['cities and design','library design','representation vs use'],'forms':['construire','ouvrir','fermer','utiliser'],'reviews':['vérité','vrai','faux','mentir'],'paragraphs':[
"Un concours fictif présente le projet d’une nouvelle bibliothèque de quartier. Les images montrent un grand rez-de-chaussée transparent et promettent un bâtiment « toujours ouvert sur la ville ». La critique reconnaît la force de cette idée, mais demande ce qu’elle signifie réellement. Construire une façade vitrée ne suffit pas à ouvrir tous les usages. Une bibliothèque doit parfois fermer une salle pour un atelier, protéger une collection ou permettre à un groupe de travailler sans bruit. La question n’est donc pas de savoir si l’image est vraie ou fausse au sens littéral, mais si elle aide le public à comprendre comment il pourra utiliser le bâtiment.",
"Le plan place un café, l’accueil et les espaces de lecture au rez-de-chaussée. Une grande salle polyvalente peut s’ouvrir vers une petite cour. En revanche, les locaux de travail du personnel se trouvent derrière une zone contrôlée. La critique estime cette séparation raisonnable, mais reproche au projet de cacher les transitions dans ses images. Si une porte doit fermer certains soirs, il vaut mieux le montrer que laisser croire que tout restera accessible. Dire la vérité sur un bâtiment ne consiste pas à publier chaque détail technique ; cela consiste à ne pas utiliser une représentation séduisante pour faire croire à un fonctionnement faux.",
"Le jury demande alors aux architectes de produire trois scénarios : journée normale, événement public et fermeture partielle. Cette méthode révèle que certains couloirs deviennent trop chargés lorsque deux activités ont lieu en même temps. Au lieu de construire immédiatement une seconde entrée, l’équipe propose d’abord de changer la position de cloisons mobiles et d’utiliser la cour comme espace d’attente lors des événements. Elle teste aussi la possibilité d’ouvrir une sortie supplémentaire uniquement lorsque la salle polyvalente accueille beaucoup de monde. La flexibilité devient ainsi une propriété du fonctionnement, pas seulement un mot de présentation.",
"La critique finale reste favorable au projet, mais elle refuse son slogan initial. Une bibliothèque peut chercher à ouvrir largement ses services tout en devant fermer certains espaces selon les usages. Mentir serait de cacher volontairement ces limites après les avoir identifiées. Le texte préfère une représentation qui montre plusieurs états du bâtiment et explique comment les habitants pourront utiliser chaque zone. Construire un lieu public crédible exige donc de relier l’image à des situations concrètes : qui entre, qui attend, quelle porte peut ouvrir, quelle salle doit fermer et pourquoi."
],
'grammar':[{'id':'fr-b2-u04-open-close-modality','role':'new','description':'contrast physical openness with conditional opening/closing and use through pouvoir/devoir/selon'}],
'discourse':[{'id':'fr-b2-u04-design-representation','role':'new','description':'critique the gap between architectural representation and operational use through scenarios and counterexamples'}],
'items':[
('main_claim','Quelle critique principale est adressée au projet ?','Son image d’ouverture permanente doit être confrontée aux usages réels et aux moments où certaines zones doivent fermer.',['ouvrir','fermer']),
('literal_detail','Quels trois scénarios le jury demande-t-il ?','Une journée normale, un événement public et une fermeture partielle.',['utiliser']),
('argument_relation','Pourquoi les images séduisantes ne suffisent-elles pas ?','Parce qu’elles peuvent masquer les transitions, les limites d’accès et les conflits d’usage qui apparaissent en fonctionnement.',['vrai','faux']),
('vocabulary_in_context','Que signifie « construire » au-delà du chantier physique ?','Concevoir un lieu dont l’organisation réelle correspond aux usages et aux promesses présentées.',['construire']),
('vocabulary_in_context','Quel sens prend « utiliser » ?','Se servir concrètement des espaces selon différentes activités et situations.',['utiliser']),
('assumption','Pourquoi tester plusieurs scénarios avant de modifier lourdement le plan ?','Parce que certains problèmes peuvent venir de l’organisation des usages plutôt que d’un manque permanent de surface.',['construire']),
('inference','Pourquoi une fermeture partielle n’est-elle pas forcément contraire à l’idée d’ouverture ?','Parce qu’un service largement accessible peut avoir besoin de limites temporaires pour fonctionner correctement.',['ouvrir','fermer']),
('reference_resolution','Dans « il vaut mieux le montrer », que représente « le » ?','Le fait qu’une porte ou une zone devra parfois être fermée.',['fermer']),
('stance','Quelle position la critique adopte-t-elle envers le projet ?','Elle reste favorable mais demande une représentation plus vraie des différents états d’usage.',['vérité','vrai']),
('summary','Résume la critique.','Le projet peut construire un lieu largement ouvert, mais doit montrer quand ouvrir ou fermer certaines zones, expliquer comment les habitants vont les utiliser et éviter de mentir par une image vraie en apparence mais fausse sur le fonctionnement.',['construire','ouvrir','fermer','utiliser','mentir','vrai','faux','vérité'])]},
{'id':'fr-b2-u04-p04','sequence':22,'ptype':'transfer','title':'Monter, descendre, attendre : critiquer une station à partir du parcours réel','genre':'critique','domains':['public'],'topics':['cities and design','station accessibility','vertical circulation'],'forms':['haut','bas','monter','descendre'],'reviews':['victime','dommage','aider','difficile'],'paragraphs':[
"Une équipe examine le plan fictif d’une petite station construite sur deux niveaux. Sur le dessin, l’entrée principale est en haut d’une pente et les quais se trouvent plus bas. Le trajet le plus direct consiste à descendre un escalier central, puis à monter quelques marches vers le quai opposé. Pour une personne sans bagage, le parcours paraît court. Mais la critique demande d’observer aussi quelqu’un qui pousse une poussette, utilise une aide à la mobilité ou porte une valise. Un design peut sembler simple depuis le haut d’un plan et devenir difficile lorsqu’on suit le mouvement réel du corps.",
"La station possède un ascenseur, mais il se trouve au bout d’un couloir. Pour descendre sans escalier, il faut donc passer devant les guichets, tourner, attendre l’ascenseur, puis revenir vers le quai. Une panne transformerait ce détour en obstacle majeur. La critique ne décrit pas ces usagers comme des victimes du bâtiment ; elle demande plutôt quel dommage pratique le plan peut produire : temps supplémentaire, correspondance manquée, fatigue ou impossibilité d’atteindre un service. Aider ne signifie pas ajouter un équipement isolé, mais vérifier si tout le parcours reste cohérent.",
"Les concepteurs proposent de déplacer l’ascenseur au centre. Cette solution réduit certains détours, mais elle prend de la place dans le hall. Une autre option consiste à créer une rampe plus longue entre le niveau haut et le niveau bas. Elle évite une panne mécanique, mais demande davantage de distance. Le texte compare donc plusieurs formes d’accessibilité au lieu de supposer qu’une seule réponse règle tout. Pour monter ou descendre, une personne a besoin d’un chemin continu, compréhensible et disponible au moment où elle l’utilise.",
"La recommandation combine les deux idées : rapprocher l’ascenseur du trajet principal et garder une liaison sans marche comme solution secondaire. La critique reconnaît le coût de cette redondance, mais soutient qu’elle réduit le risque qu’une seule panne bloque complètement le passage. Le problème est difficile parce que chaque mètre donné à un parcours manque à un autre usage. Pourtant, le texte refuse de mesurer l’efficacité uniquement par la distance du voyageur le plus rapide. Concevoir du haut vers le bas exige aussi de demander qui peut réellement monter, qui peut descendre et quel dommage apparaît lorsque le parcours théorique ne correspond pas au parcours possible."
],
'grammar':[{'id':'fr-b2-u04-vertical-route','role':'new','description':'describe vertical movement and alternative routes with haut/bas, monter/descendre and conditional failure'}],
'discourse':[{'id':'fr-b2-u04-whole-journey-critique','role':'new','description':'evaluate accessibility as a complete journey, comparing redundancy, distance, failure and space trade-offs'}],
'items':[
('main_claim','Quel principe de conception la critique défend-elle ?','Évaluer l’accessibilité sur l’ensemble du parcours et prévoir une solution si un élément essentiel devient indisponible.',['monter','descendre']),
('literal_detail','Où se trouvent les quais par rapport à l’entrée ?','Ils se trouvent plus bas que l’entrée principale.',['bas','haut']),
('argument_relation','Pourquoi un ascenseur présent ne suffit-il pas à prouver l’accessibilité ?','Parce que son emplacement, son détour et sa disponibilité déterminent si le parcours reste réellement utilisable.',['difficile']),
('vocabulary_in_context','Que signifie « haut » dans le texte ?','Le niveau supérieur du parcours, près de l’entrée principale.',['haut']),
('vocabulary_in_context','Que signifie « descendre » ici ?','Se déplacer vers le niveau inférieur où se trouvent les quais.',['descendre']),
('assumption','Quelle hypothèse justifie une liaison secondaire sans marche ?','Qu’une panne de l’ascenseur est possible et qu’un seul point de défaillance peut bloquer certains usagers.',['dommage']),
('inference','Pourquoi la rampe n’est-elle pas automatiquement la meilleure solution ?','Parce qu’elle offre une continuité robuste mais consomme plus de distance et d’espace.',['monter','bas']),
('reference_resolution','Dans « elle prend de la place », à quoi renvoie « elle » ?','À la solution qui déplace l’ascenseur vers le centre du hall.',['haut']),
('stance','Quelle position le texte adopte-t-il envers la redondance ?','Il accepte son coût lorsqu’elle aide à éviter qu’une panne unique crée un dommage disproportionné.',['aider','dommage']),
('summary','Résume la critique.','Le parcours du haut vers le bas doit permettre de monter et descendre même quand une option échoue; la station cherche donc à aider sans créer de dommage, malgré un compromis difficile entre espace, distance et redondance.',['haut','bas','monter','descendre','aider','dommage','difficile','victime'])]},
{'id':'fr-b2-u04-p05','sequence':23,'ptype':'integration','title':'Entrer, sortir et rester : un ancien bureau devient un nouveau lieu public','genre':'proposal and critique','domains':['public','professional'],'topics':['cities and design','adaptive reuse','public building use'],'forms':['entrer','sortir','servir','nouveau'],'reviews':['garder','donner','loi','guerre'],'paragraphs':[
"Une ville fictive possède un ancien bureau administratif devenu presque vide. Plutôt que de le démolir, elle étudie un nouveau rôle : transformer le rez-de-chaussée en lieu de services et de réunions. Le bâtiment avait été conçu pour que le personnel puisse entrer avec un badge et que les visiteurs restent près de l’accueil. Ce fonctionnement ne peut pas simplement servir de modèle à un lieu plus ouvert. Si davantage de personnes doivent entrer, rester pour une activité puis sortir à des heures différentes, les circulations et les responsabilités changent.",
"La proposition veut garder la structure principale et donner plusieurs usages aux salles existantes. Une grande pièce pourrait servir de permanence administrative le matin et de salle associative le soir. Une autre accueillerait des ateliers. La loi impose déjà certaines exigences de sécurité, mais le comité rappelle qu’un minimum juridique ne garantit pas un bon usage. Par exemple, une sortie réglementaire peut exister tout en étant difficile à trouver depuis une salle pleine. Le nouveau projet doit donc montrer non seulement où entrer et sortir, mais aussi comment les chemins restent lisibles lorsque plusieurs activités ont lieu en même temps.",
"Un débat concerne la mémoire du bâtiment. Certains souhaitent garder presque tout l’aménagement intérieur parce qu’il représente une période importante de l’administration locale. D’autres répondent que le lieu n’est pas un musée et qu’il doit d’abord servir les habitants actuels. Le comité compare cette discussion à d’autres bâtiments transformés après des périodes de guerre, sans prétendre que les situations sont identiques : conserver une trace peut avoir une valeur publique, mais cette valeur ne décide pas seule de chaque usage futur. Le projet choisit de garder quelques éléments visibles et de modifier le reste.",
"La version finale crée un hall traversant, ajoute une seconde sortie clairement visible et transforme les anciens bureaux fermés en salles de tailles différentes. Le texte soutient que le nouveau lieu réussira seulement si les personnes peuvent comprendre comment entrer, où rester et comment sortir sans dépendre d’un membre du personnel. Les pièces doivent servir des activités réelles plutôt qu’une image abstraite de polyvalence. La loi fixe certaines limites; l’histoire du bâtiment en donne d’autres; mais le design doit encore décider ce qu’il faut garder et ce qu’il faut donner à de nouveaux usages. Transformer n’est donc ni effacer le passé ni conserver tout ce qui existe."
],
'grammar':[{'id':'fr-b2-u04-entry-exit-purpose','role':'new','description':'connect movement and purpose with entrer/sortir/rester and servir à/de'}],
'discourse':[{'id':'fr-b2-u04-adaptive-reuse','role':'new','description':'integrate legal minimum, historical memory, circulation and new public use in an adaptive-reuse proposal'}],
'items':[
('main_claim','Quel principe guide la transformation du bâtiment ?','Conserver ce qui reste utile ou significatif tout en réorganisant le lieu pour ses nouveaux usages publics.',['nouveau','servir','garder']),
('literal_detail','Quelle modification principale est faite au hall ?','Il devient traversant et une seconde sortie clairement visible est ajoutée.',['entrer','sortir']),
('argument_relation','Pourquoi le minimum prévu par la loi n’est-il pas considéré comme suffisant ?','Parce qu’une sortie conforme peut encore être difficile à trouver ou mal intégrée au parcours réel.',['loi','sortir']),
('vocabulary_in_context','Que signifie « servir » dans le texte ?','Remplir une fonction concrète pour les activités et les habitants.',['servir']),
('vocabulary_in_context','Quel sens prend « nouveau » ?','Une fonction et une organisation différentes de celles de l’ancien bureau.',['nouveau']),
('assumption','Pourquoi garder seulement certains éléments historiques ?','Parce que la mémoire peut être préservée sans empêcher le bâtiment de servir ses usages actuels.',['garder','servir']),
('inference','Pourquoi un hall lisible compte-t-il dans un lieu public ?','Parce que les visiteurs doivent pouvoir entrer et sortir sans dépendre constamment du personnel.',['entrer','sortir']),
('reference_resolution','Dans « cette valeur ne décide pas seule », quelle valeur est visée ?','La valeur publique liée à la conservation d’une trace historique.',['garder']),
('stance','Quelle position le texte adopte-t-il envers la conservation intégrale ?','Il refuse de garder tout automatiquement et préfère une sélection compatible avec le nouveau rôle du lieu.',['garder','nouveau']),
('summary','Résume le projet.','La ville transforme un ancien bureau en nouveau lieu public où chacun peut entrer, sortir et utiliser des pièces qui doivent servir des besoins réels; elle choisit quoi garder ou donner à d’autres usages au-delà du minimum de la loi et sans faire de la mémoire de guerre un modèle automatique.',['nouveau','entrer','sortir','servir','garder','donner','loi','guerre'])]}
]
CHECKPOINT={'id':'fr-b2-u04-p06','sequence':24,'ptype':'checkpoint','title':'Du coin de rue au bâtiment : vérifier un design par les parcours et les usages','genre':'B2 cumulative design checkpoint','domains':['public','educational'],'topics':['cities and design','synthesis','trade-offs'],'paragraphs':[
"Les cinq textes montrent que le design urbain se juge moins par une image isolée que par une série de situations. Sur la petite place, un coin vide peut fonctionner autrement que l’autre côté à cause d’un arbre, du soleil ou de la circulation de l’air. Devant l’école, une règle simple sur la voiture peut réduire un problème tout en créant un besoin d’exception pour une personne qui doit rester proche de l’entrée. Dans les deux cas, observer l’usage réel évite de déclarer trop tôt qu’une solution est bonne pour tout le monde.",
"La bibliothèque ajoute la question de la représentation. Construire un lieu présenté comme ouvert ne signifie pas ouvrir chaque pièce à toute heure. Il faut parfois fermer une zone et montrer honnêtement pourquoi. Les habitants doivent savoir comment utiliser le bâtiment dans plusieurs états. La station ajoute le parcours vertical : une personne peut partir du haut, descendre vers un quai, devoir remonter, puis chercher une autre manière de monter si un ascenseur est indisponible. Ce qui paraît direct sur un plan peut devenir beaucoup plus long depuis le bas du parcours réel.",
"Le projet de réemploi ajoute enfin le temps. Un ancien bureau peut recevoir un nouveau rôle si le bâtiment permet aux visiteurs d’entrer, de rester pour une activité puis de sortir clairement. Une salle doit servir un besoin identifiable, pas seulement porter une étiquette flexible. Ces décisions ne sont pas indépendantes : construire, ouvrir, fermer, utiliser, entrer ou sortir produit des effets sur d’autres usages. De même, placer une voiture proche d’une entrée peut aider une personne tout en réduisant l’espace disponible pour un autre groupe.",
"La synthèse propose donc quatre questions. Qui doit pouvoir utiliser le lieu ? Quel parcours relie le haut au bas, un côté à l’autre ou l’extérieur à l’intérieur ? Quel besoin justifie une exception à une règle simple ? Enfin, que se passe-t-il si une porte ferme, si un équipement tombe en panne ou si un nouvel usage attire plus de monde que prévu ? Un design robuste n’essaie pas de rendre chaque espace identique. Il organise des choix visibles, permet de tester certains changements et garde la possibilité de corriger ce qui fonctionne mal. Même un détail comme un arbre dans un coin peut alors servir à poser une question plus large sur la ville."
],
'grammar':[{'id':'fr-b2-u04-design-synthesis','role':'review','description':'synthesize spatial comparison, movement, conditional failure, purpose and bounded exception'}],
'discourse':[{'id':'fr-b2-u04-design-tradeoff-synthesis','role':'review','description':'integrate five design cases through user journey, operational state, need, trade-off and revisability'}],
'items':[
('main_claim','Quelle méthode générale la synthèse recommande-t-elle ?','Évaluer un design par les usages, parcours, besoins, pannes possibles et effets sur d’autres personnes avant de le rendre durable.',['utiliser','besoin']),
('argument_relation','Quel lien existe entre le coin de place et la rue scolaire ?','Les deux montrent qu’un changement local doit être évalué par ses effets réels et par les besoins différents des usagers.',['coin','côté','besoin','proche']),
('cross_text_synthesis','Comment la bibliothèque et la station compliquent-elles une lecture statique du plan ?','Elles montrent qu’un lieu change selon ce qui ouvre ou ferme et selon les mouvements nécessaires pour monter ou descendre.',['ouvrir','fermer','monter','descendre']),
('assumption','Pourquoi prévoir les situations de panne ou de fermeture ?','Parce qu’un design doit rester compréhensible et utilisable lorsque son fonctionnement normal change.',['fermer','utiliser']),
('inference','Pourquoi un détail comme un arbre peut-il avoir une portée générale ?','Parce qu’il révèle comment confort, emplacement et usage interagissent à l’échelle d’un lieu.',['arbre','air']),
('reference_resolution','Dans « Ces décisions ne sont pas indépendantes », quelles décisions sont visées ?','Les choix de construire, ouvrir, fermer, utiliser, entrer et sortir dans les différents projets.',['construire','ouvrir','fermer','utiliser','entrer','sortir']),
('stance','Quelle position le texte adopte-t-il envers les solutions identiques partout ?','Il les refuse lorsque les parcours et besoins sont différents et préfère des choix explicables et révisables.',['simple','besoin']),
('vocabulary_in_context','Pourquoi « servir » apparaît-il dans la conclusion ?','Pour rappeler qu’un élément de design doit remplir une fonction réelle et identifiable.',['servir']),
('synthesis','Comment la voiture et la circulation verticale illustrent-elles un même compromis ?','Toutes deux montrent qu’un accès plus proche ou plus direct pour certains peut consommer de l’espace ou créer un autre coût pour d’autres.',['voiture','proche','haut','bas']),
('summary','Résume l’unité en une phrase.','Du coin et du côté d’une place à un arbre qui modifie l’air, de la voiture proche d’un besoin à une règle simple, puis du choix de construire, ouvrir, fermer et utiliser jusqu’aux parcours du haut vers le bas pour monter ou descendre et au nouveau bâtiment où l’on doit entrer, sortir et faire servir chaque pièce, le design se vérifie par les usages plutôt que par l’image seule.',['coin','côté','arbre','air','voiture','proche','besoin','simple','construire','ouvrir','fermer','utiliser','haut','bas','monter','descendre','entrer','sortir','servir','nouveau'])]}

def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);text=text_of(s)
 return {'id':s['id'],'language':'fr','cefr':'B2','unit':4,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 04 guarded production batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 04: cities and design.','Accepted B2 default of four fresh targets per P01-P05; P06 zero new.','All civic scenarios are fictional/generic.']},'paired_text_group':None,'prerequisites':['French B2 Units 01-03 canonical and Unit03 frontier lock PASS'],'difficulty_notes_internal':'B2 urban design reasoning: user journeys, evidence limits, stakeholder impacts, operational states, counterargument and trade-offs.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b2_u04']}
def build(a1,a2,b1,b2,deck):
 prior=base.prior(a1+a2+b1+b2);ids0={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};forms0={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};bad=[]
 for f in FORMS:
  if f not in deck:bad.append(f+':missing_lexicon')
  elif base.tid(deck[f]['rank']) in ids0 or f in forms0 or prior.get(f):bad.append(f+':already_deliberate')
 if bad:raise AssertionError('Unit04 candidate failures: '+', '.join(bad))
 out=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,deck) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,deck) for f in FORMS];ids={t['form']:t['id'] for t in reviews};out.append(mk(CHECKPOINT,[],reviews,ids,True));return out
def main():
 for lab,p in [('A1',A1),('A2',A2),('B1',B1),('B2',CANON)]:
  got=subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
  if got!=EXPECTED[lab]:raise AssertionError(f'{lab} blob drift: {got} != {EXPECTED[lab]}')
 lock=json.loads(LOCK.read_text(encoding='utf-8'));probe=json.loads(PROBE.read_text(encoding='utf-8'))
 if lock.get('status')!='PASS' or lock.get('canonical_blob')!=EXPECTED['B2'] or lock.get('last_sequence')!=18:raise AssertionError('Unit03 lock mismatch')
 if probe.get('status')!='PASS' or probe.get('b2_source_blob')!=EXPECTED['B2']:raise AssertionError('Unit04 probe stale')
 fresh={x['form'] for x in probe.get('fresh',[])}
 if any(f not in fresh for f in FORMS):raise AssertionError('selected target absent from Unit04 fresh probe')
 load=lambda p:[json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()]
 a1,a2,b1,b2=map(load,(A1,A2,B1,CANON))
 if len(b2)!=18 or b2[-1]['id']!='fr-b2-u03-p06':raise AssertionError('unexpected B2 prerequisite frontier')
 deck=base.deck();unit=build(a1,a2,b1,b2,deck);V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));prior_ids={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};prior_forms={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};newids=[];newforms=[]
 if [r['sequence'] for r in unit]!=list(range(19,25)) or [r['id'] for r in unit]!=[f'fr-b2-u04-p{i:02d}' for i in range(1,7)]:raise AssertionError('Unit04 sequence/id continuity failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
  if not 350<=r['word_count']<=550:raise AssertionError(f"{r['id']}: B2 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  if r['sequence']<=23 and len(r['new_lexical_targets'])!=4:raise AssertionError(f"{r['id']}: expected 4 new targets")
  if r['sequence']==24 and r['new_lexical_targets']:raise AssertionError('Unit04 P06 must have zero new')
  amap={a['question_id']:a['id'] for a in r['answer_key']};local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   src=deck.get(t['form'])
   if t['id'] in prior_ids or t['form'] in prior_forms or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: source/exposure/freshness drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20:raise AssertionError('Unit04 lexical uniqueness failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b2+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','level':'B2','unit':4,'theme':'cities and design','appended_passages':6,'b2_passages':24,'questions':60,'answers':60,'new_targets':20,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':[{'form':f,'rank':deck[f]['rank'],'id':base.tid(deck[f]['rank'])} for f in FORMS]},ensure_ascii=False))
if __name__=='__main__':main()
