#!/usr/bin/env python3
"""Finish French A1 with Units 09-10 (sequences 49-60) in one guarded batch."""
from __future__ import annotations
import csv,json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[2]
CANON=ROOT/'reading/french/a1/passages.jsonl'; SCHEMA=ROOT/'reading/schema/passage.schema.json'; LEXICON=ROOT/'french_top1000.csv'
EXPECTED_BLOB='3da2da2bfe133ed0bfa59c792e15fa251a343b77'
U9_FORMS=('parler','écouter','lire','écrire','appeler','répondre','message','téléphone','ami','famille')
U10_FORMS=('pluie','soleil','froid','chaud','acheter','prix','argent','vêtement','manteau','chaussure')

def lexicon():
 out={}
 with LEXICON.open(encoding='utf-8',newline='') as f:
  for row in csv.DictReader(f):
   x=(row.get('Front') or '').strip(); b=row.get('Back') or ''
   a=re.search(r'Rank:\s*(\d+)',b); m=re.search(r'Meaning:\s*(.+)',b); p=re.search(r'Part of speech:\s*(.+)',b)
   if x and a and m and p: out[x]={'rank':int(a.group(1)),'sense':m.group(1).strip(),'pos':p.group(1).strip()}
 return out
def tid(r):return f'fr-rank-{r:04d}'
def count(text,f):return len(re.findall(rf'(?<!\w){re.escape(f)}(?!\w)',text,flags=re.I|re.UNICODE))
def prior(rows):
 d={}
 for r in rows:
  for t in r.get('new_lexical_targets',[]):
   if isinstance(t,dict) and t.get('form'):d.setdefault(t['form'],[]).append(t)
 return d
def nt(f,text,L):
 s=L[f]; n=count(text,f)
 if n<1:raise AssertionError(f'{f}: invisible new target')
 return {'id':tid(s['rank']),'form':f,'lemma':f,'intended_sense':s['sense'],'part_of_speech':s['pos'],'register':'contemporary standard','variety':None,'context_strategy':['scenario_resolution'],'first_introduced':True,'exposures_in_text':n,'source_lexicon':'french_top1000.csv','source_rank':s['rank'],'beyond_base':False}
def rev(f,stage,rep,P):
 h=P.get(f,[])
 if len(h)!=1:raise AssertionError(f'{f}: expected one earlier deliberate target, got {len(h)}')
 return {'id':h[0]['id'],'form':f,'review_stage':stage,'representation':rep,'expected_exposure_number':None}
def cur(f,L):return {'id':tid(L[f]['rank']),'form':f,'review_stage':'R1','representation':'summary','expected_exposure_number':None}
def qa(items):
 q=[];a=[]
 for i,(ty,p,ans,ids) in enumerate(items,1):
  qi=f'q{i}';ai=f'a{i}';x={'id':qi,'type':ty,'prompt':p,'answer_id':ai}
  if ids:x['target_ids']=ids
  q.append(x);a.append({'id':ai,'question_id':qi,'answer':ans,'explanation':''})
 return q,a
def mk(unit,pid,seq,ptype,title,genre,domains,topics,text,new,reviews,grammar,discourse,items,speed=False):
 q,a=qa(items)
 return {'id':pid,'language':'fr','cefr':'A1','unit':unit,'sequence':seq,'revision':1,'title':title,'passage_type':ptype,'genre':genre,'domains':domains,'topics':topics,'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':grammar,'discourse_targets':discourse,'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':f'Generation-stage French A1 Unit {unit:02d}; full multi-pass audit deferred.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':[f'Guarded French A1 Unit {unit:02d} generation batch.','Schema, source identity, word band, linkage, local target declaration, visible review, continuity, and checkpoint invariants enforced.']},'paired_text_group':None,'prerequisites':[f'French A1 Units 01-{unit-1:02d} canonical corpus'],'difficulty_notes_internal':'A1 practical communication and final everyday-life integration.','reader_tags':['unit_role:'+ptype,'generation_batch',f'french_a1_u{unit:02d}']}

def build_u9(rows,L):
 P=prior(rows);out=[]
 for f in U9_FORMS:
  if f not in L:raise AssertionError(f'U09 {f}: missing from french_top1000.csv')
  if P.get(f):raise AssertionError(f'U09 {f}: already deliberately introduced')
 text='''Après le cours de sport, Camille a encore un peu mal à la tête. Sami veut parler de leur projet, mais Camille lui demande d’abord d’écouter une idée courte. Elle parle lentement et explique qu’elle préfère finir le projet demain. Sami écoute sans l’interrompre. Camille pose une main sur son sac et vérifie l’heure. Elle dit qu’elle doit rentrer bientôt. Avant de partir, Sami parle à son tour et Camille écoute sa réponse. Ils comprennent qu’une bonne conversation ne consiste pas seulement à parler : il faut aussi écouter l’autre personne pour savoir ce qu’elle pense et organiser le travail ensemble.'''
 a,b=nt('parler',text,L),nt('écouter',text,L)
 out.append(mk(9,'fr-a1-u09-p01',49,'instructional','Parler et écouter','school conversation',['educational','personal'],['conversation','listening','school project'],text,[a,b],[rev('tête','R2','running_text',P),rev('main','R2','running_text',P)],[{'id':'fr-a1-parler-communicate','role':'new','description':'parler for speaking'},{'id':'fr-a1-ecouter-attend','role':'new','description':'écouter for listening attentively'}],[{'id':'fr-a1-turn-taking','role':'new','description':'take simple turns in a conversation'}],[('gist','De quoi Camille et Sami parlent-ils ?','De leur projet et du moment où ils vont le finir.',[]),('literal_detail','Pourquoi Camille veut-elle rentrer bientôt ?','Parce qu’elle regarde l’heure et doit partir.',[]),('vocabulary_in_context','Que signifie « parler » ici ?','Dire des mots pour communiquer avec quelqu’un.',[a['id']]),('vocabulary_in_context','Que signifie « écouter » ?','Faire attention à ce qu’une autre personne dit.',[b['id']]),('inference','Pourquoi l’écoute est-elle importante dans leur conversation ?','Parce qu’elle permet de comprendre l’autre et d’organiser le travail ensemble.',[]),('single_word_definition','Que signifie « écouter » ?','Faire attention aux sons ou aux paroles.',[b['id']]),('grammar_category','Quel type de mot est « parler » ?','Un verbe.',[a['id']]),('contrast','Pour faire attention aux paroles de quelqu’un, lequel convient : « écouter » ou « parler » ?','écouter',[a['id'],b['id']]),('cloze_transfer','Complète : Je veux _____ avec le professeur.','parler',[a['id']]),('cloze_transfer','Complète : En classe, il faut _____ les consignes.','écouter',[b['id']])]))
 text='''Le soir, Camille repose son pied et son corps après une journée active. Elle s’installe à son bureau pour lire un petit texte. Après chaque paragraphe, elle écrit une phrase dans son cahier. Lire l’aide à comprendre les idées, tandis qu’écrire l’aide à garder une trace de ce qu’elle retient. Sami lui a donné une courte histoire à lire, alors Camille commence par celle-ci. Elle écrit ensuite trois mots nouveaux qu’elle veut revoir demain. Quand son corps commence à être fatigué, elle ferme le livre. Elle préfère lire un peu et écrire quelques notes utiles plutôt que continuer trop longtemps sans attention.'''
 a,b=nt('lire',text,L),nt('écrire',text,L)
 out.append(mk(9,'fr-a1-u09-p02',50,'reinforcement','Lire puis écrire','study routine',['educational','personal'],['reading','writing','study notes'],text,[a,b],[rev('pied','R2','running_text',P),rev('corps','R2','running_text',P)],[{'id':'fr-a1-lire-text','role':'new','description':'lire for reading written text'},{'id':'fr-a1-ecrire-text','role':'new','description':'écrire for producing written text'}],[{'id':'fr-a1-read-note-cycle','role':'new','description':'read a short text then record a simple note'}],[('gist','Comment Camille étudie-t-elle le texte ?','Elle lit puis écrit de courtes notes.',[]),('literal_detail','Combien de mots nouveaux écrit-elle ?','Trois.',[]),('vocabulary_in_context','Que signifie « lire » ?','Regarder et comprendre un texte écrit.',[a['id']]),('vocabulary_in_context','Que signifie « écrire » ?','Produire des mots ou des phrases par écrit.',[b['id']]),('cause_effect','Pourquoi Camille écrit-elle une phrase après chaque paragraphe ?','Pour garder une trace de ce qu’elle retient.',[]),('single_word_definition','Que signifie « lire » ?','Comprendre des mots écrits.',[a['id']]),('grammar_category','Quel type de mot est « écrire » ?','Un verbe.',[b['id']]),('contrast','Pour produire une phrase dans un cahier, lequel convient : « écrire » ou « lire » ?','écrire',[a['id'],b['id']]),('cloze_transfer','Complète : Je vais _____ ce livre.','lire',[a['id']]),('cloze_transfer','Complète : Je vais _____ une phrase.','écrire',[b['id']])]))
 text='''Après avoir mangé, Camille veut appeler sa mère pour savoir quand elle rentre. Elle prend son téléphone et appelle une première fois, mais personne ne répond. Camille boit un peu d’eau et attend cinq minutes. Elle appelle encore. Cette fois, sa mère répond et explique qu’elle arrive bientôt. Camille lui demande si elle doit préparer le dîner. Sa mère répond oui et lui dit de commencer une salade. Camille est contente d’avoir une réponse claire. Elle comprend qu’appeler sert à contacter quelqu’un à distance, tandis que répondre signifie réagir quand une personne appelle ou pose une question.'''
 a,b=nt('appeler',text,L),nt('répondre',text,L)
 out.append(mk(9,'fr-a1-u09-p03',51,'interleaved','Appeler et répondre','phone-call narrative',['personal'],['phone call','family','response'],text,[a,b],[rev('manger','R2','running_text',P),rev('boire','R2','running_text',P)],[{'id':'fr-a1-appeler-phone','role':'new','description':'appeler for contacting someone by phone'},{'id':'fr-a1-repondre-response','role':'new','description':'répondre for giving a response'}],[{'id':'fr-a1-phone-exchange','role':'new','description':'follow a simple call-response exchange'}],[('gist','Pourquoi Camille appelle-t-elle sa mère ?','Pour savoir quand elle rentre.',[]),('literal_detail','Que doit préparer Camille ?','Une salade.',[]),('vocabulary_in_context','Que signifie « appeler » ici ?','Téléphoner à quelqu’un pour le contacter.',[a['id']]),('vocabulary_in_context','Que signifie « répondre » ?','Donner une réponse ou réagir à un appel.',[b['id']]),('sequence','Que se passe-t-il après le premier appel ?','Personne ne répond, Camille attend, puis elle appelle encore.',[]),('single_word_definition','Que signifie « répondre » ?','Donner une réponse.',[b['id']]),('grammar_category','Quel type de mot est « appeler » ?','Un verbe.',[a['id']]),('contrast','Quand le téléphone sonne et qu’on accepte l’appel, lequel convient : « répondre » ou « appeler » ?','répondre',[a['id'],b['id']]),('cloze_transfer','Complète : Je vais _____ mon ami ce soir.','appeler',[a['id']]),('cloze_transfer','Complète : Le professeur pose une question ; je vais _____.','répondre',[b['id']])]))
 text='''Avant de dormir, Camille sent son téléphone vibrer sur la table. Elle regarde l’écran : Sami a envoyé un message au sujet du projet. Le message est court : il demande quelle heure convient demain matin. Camille ne veut pas utiliser son téléphone trop longtemps le soir. Elle lit le message, répond « neuf heures », puis pose le téléphone loin du lit. Quelques minutes plus tard, un autre message arrive, mais Camille décide de le lire demain. Elle sait que le téléphone est utile pour communiquer rapidement, mais elle préfère aussi garder un moment calme avant de dormir.'''
 a,b=nt('message',text,L),nt('téléphone',text,L)
 out.append(mk(9,'fr-a1-u09-p04',52,'transfer','Un message avant de dormir','digital-message narrative',['personal','educational'],['message','phone','evening'],text,[a,b],[rev('dormir','R2','running_text',P),rev('sentir','R2','running_text',P)],[{'id':'fr-a1-message-written','role':'new','description':'message as a short communication'},{'id':'fr-a1-telephone-device','role':'new','description':'téléphone as a communication device'}],[{'id':'fr-a1-digital-boundary','role':'new','description':'handle a simple message while keeping an evening routine'}],[('gist','Que reçoit Camille ?','Un message de Sami.',[]),('literal_detail','Quelle heure Camille propose-t-elle ?','Neuf heures.',[]),('vocabulary_in_context','Que signifie « message » ici ?','Une courte communication écrite envoyée à quelqu’un.',[a['id']]),('vocabulary_in_context','Que désigne « téléphone » ?','L’appareil qu’elle utilise pour lire et répondre au message.',[b['id']]),('cause_effect','Pourquoi Camille pose-t-elle le téléphone loin du lit ?','Parce qu’elle ne veut pas l’utiliser trop longtemps avant de dormir.',[]),('single_word_definition','Que signifie « message » ?','Une information envoyée à une autre personne.',[a['id']]),('grammar_category','Quel type de mot est « téléphone » ?','Un nom.',[b['id']]),('contrast','Pour l’information envoyée, lequel convient : « message » ou « téléphone » ?','message',[a['id'],b['id']]),('cloze_transfer','Complète : J’envoie un _____ à Sami.','message',[a['id']]),('cloze_transfer','Complète : Mon _____ est dans mon sac.','téléphone',[b['id']])]))
 text='''Dimanche, Camille va mieux et retrouve un ami au parc. Son ami s’appelle Sami, mais d’autres membres de sa famille viennent aussi : sa mère, son petit frère et une cousine. Camille explique à Sami qu’elle aime voir un ami seul pour parler tranquillement, mais qu’elle aime aussi les moments avec toute sa famille. Ils marchent près des arbres pendant que les enfants jouent. Plus tard, la famille de Camille prépare un petit repas sur une table. Sami reste avec eux. Camille remarque qu’un ami peut faire partie d’une activité familiale sans être un membre de la famille.'''
 a,b=nt('ami',text,L),nt('famille',text,L)
 out.append(mk(9,'fr-a1-u09-p05',53,'integration','Un ami avec la famille','social gathering narrative',['personal'],['friends','family','park'],text,[a,b],[rev('malade','R2','running_text',P),rev('mieux','R2','running_text',P)],[{'id':'fr-a1-ami-person','role':'new','description':'ami as a friend'},{'id':'fr-a1-famille-group','role':'new','description':'famille as a family group'}],[{'id':'fr-a1-social-groups','role':'new','description':'distinguish friend and family relationships'}],[('gist','Qui Camille retrouve-t-elle au parc ?','Son ami Sami.',[]),('literal_detail','Quels membres de la famille sont nommés ?','Sa mère, son petit frère et une cousine.',[]),('vocabulary_in_context','Que signifie « ami » ?','Une personne avec qui on a une relation amicale.',[a['id']]),('vocabulary_in_context','Que signifie « famille » ?','Le groupe de personnes liées par des relations familiales.',[b['id']]),('inference','Pourquoi Sami peut-il participer au repas sans être de la famille ?','Parce qu’un ami peut être invité à une activité familiale.',[]),('single_word_definition','Que signifie « famille » ?','Un groupe de personnes liées par des relations familiales.',[b['id']]),('grammar_category','Quel type de mot est « ami » ?','Un nom.',[a['id']]),('contrast','Lequel désigne une relation amicale : « ami » ou « famille » ?','ami',[a['id'],b['id']]),('cloze_transfer','Complète : Sami est mon _____.','ami',[a['id']]),('cloze_transfer','Complète : Je dîne avec ma _____.','famille',[b['id']])]))
 text='''Camille communique maintenant de plusieurs façons. Elle peut parler avec un ami et écouter sa réponse. Pour étudier, elle peut lire un texte et écrire quelques notes. Quand une personne est loin, Camille peut appeler et répondre au téléphone. Elle peut aussi envoyer ou lire un message. Avec un ami ou avec sa famille, elle choisit la façon de communiquer selon la situation. Ces actions sont simples, mais elles l’aident à demander une information, partager une idée, organiser un rendez-vous et garder le contact avec les personnes importantes dans sa vie.'''
 reviews=[cur(f,L) for f in U9_FORMS]
 out.append(mk(9,'fr-a1-u09-p06',54,'checkpoint','Communiquer de plusieurs façons','cumulative communication summary',['personal','educational'],['communication','reading','phone'],text,[],reviews,[{'id':'fr-a1-u09-communication-review','role':'integration','description':'integrate speaking, listening, reading, writing, and phone communication'}],[{'id':'fr-a1-u09-mode-choice','role':'integration','description':'choose a simple communication mode for a situation'}],[('gist','Quelle est l’idée principale du texte ?','Camille sait utiliser plusieurs moyens simples pour communiquer.',[]),('literal_detail','Que peut-elle faire pour étudier ?','Lire un texte et écrire des notes.',[]),('vocabulary_in_context','Que signifie « appeler » dans ce résumé ?','Contacter quelqu’un par téléphone.',[tid(L['appeler']['rank'])]),('vocabulary_in_context','Que signifie « message » ?','Une information envoyée à quelqu’un.',[tid(L['message']['rank'])]),('cause_effect','Pourquoi Camille choisit-elle différentes façons de communiquer ?','Parce que la meilleure façon dépend de la situation.',[]),('single_word_definition','Que signifie « écouter » ?','Faire attention à ce qu’on entend.',[tid(L['écouter']['rank'])]),('grammar_category','Quel type de mot est « famille » ?','Un nom.',[tid(L['famille']['rank'])]),('contrast','Pour produire des mots sur une page, lequel convient : « écrire » ou « lire » ?','écrire',[tid(L['écrire']['rank']),tid(L['lire']['rank'])]),('cloze_transfer','Complète : Je vais _____ Sami avec mon téléphone.','appeler',[tid(L['appeler']['rank'])]),('summary','Résume en une phrase comment Camille communique.','Elle parle, écoute, lit, écrit et utilise son téléphone pour rester en contact et organiser ses activités.',[])],speed=True))
 return out

def build_u10(rows,L):
 P=prior(rows);out=[]
 for f in U10_FORMS:
  if f not in L:raise AssertionError(f'U10 {f}: missing from french_top1000.csv')
  if P.get(f):raise AssertionError(f'U10 {f}: already deliberately introduced')
 text='''Le matin, Camille parle avec Sami avant de sortir. Ils regardent par la fenêtre : la pluie tombe doucement, mais on voit aussi un peu de soleil derrière les nuages. Sami écoute la météo à la radio. Il dit que la pluie va bientôt s’arrêter et que le soleil reviendra dans l’après-midi. Camille décide de prendre un petit parapluie quand même. Sur le chemin de l’école, la pluie devient plus faible. Une heure plus tard, le soleil apparaît vraiment. Camille remarque que la pluie et le soleil peuvent se succéder pendant la même journée.'''
 a,b=nt('pluie',text,L),nt('soleil',text,L)
 out.append(mk(10,'fr-a1-u10-p01',55,'instructional','La pluie puis le soleil','weather narrative',['public','personal'],['weather','rain','sun'],text,[a,b],[rev('parler','R2','running_text',P),rev('écouter','R2','running_text',P)],[{'id':'fr-a1-pluie-weather','role':'new','description':'pluie as rain'},{'id':'fr-a1-soleil-weather','role':'new','description':'soleil as sun'}],[{'id':'fr-a1-weather-change','role':'new','description':'follow a simple change in weather'}],[('gist','Quel temps fait-il d’abord ?','Il pleut.',[]),('literal_detail','Que prend Camille ?','Un petit parapluie.',[]),('vocabulary_in_context','Que signifie « pluie » ?','L’eau qui tombe des nuages.',[a['id']]),('vocabulary_in_context','Que signifie « soleil » ici ?','L’astre lumineux visible dans le ciel et sa lumière.',[b['id']]),('sequence','Quel temps vient après la pluie ?','Le soleil apparaît.',[]),('single_word_definition','Que signifie « pluie » ?','De l’eau qui tombe du ciel en gouttes.',[a['id']]),('grammar_category','Quel type de mot est « soleil » ?','Un nom.',[b['id']]),('contrast','Quand de l’eau tombe des nuages, lequel convient : « pluie » ou « soleil » ?','pluie',[a['id'],b['id']]),('cloze_transfer','Complète : Je prends un parapluie à cause de la _____.','pluie',[a['id']]),('cloze_transfer','Complète : Le _____ brille dans le ciel.','soleil',[b['id']])]))
 text='''Après avoir lu un message de Sami, Camille écrit qu’elle va le retrouver au parc. Dehors, il fait froid le matin. Camille met une veste et marche rapidement. À midi, le soleil est plus fort et il fait chaud. Elle enlève sa veste et la garde dans son sac. Camille trouve intéressant qu’une même journée puisse commencer avec du froid et devenir chaude quelques heures plus tard. Elle écrit dans son téléphone : « froid le matin, chaud à midi ». Elle comprend surtout qu’il faut regarder les conditions réelles au lieu de penser que la température reste la même toute la journée.'''
 a,b=nt('froid',text,L),nt('chaud',text,L)
 out.append(mk(10,'fr-a1-u10-p02',56,'reinforcement','Froid le matin, chaud à midi','temperature narrative',['personal','public'],['temperature','clothing','day'],text,[a,b],[rev('lire','R2','running_text',P),rev('écrire','R2','running_text',P)],[{'id':'fr-a1-froid-temperature','role':'new','description':'froid for low temperature'},{'id':'fr-a1-chaud-temperature','role':'new','description':'chaud for high temperature'}],[{'id':'fr-a1-temperature-change','role':'new','description':'compare morning and midday temperature'}],[('gist','Comment change la température ?','Il fait froid le matin puis chaud à midi.',[]),('literal_detail','Où Camille met-elle sa veste ?','Dans son sac.',[]),('vocabulary_in_context','Que signifie « froid » ici ?','Une température basse.',[a['id']]),('vocabulary_in_context','Que signifie « chaud » ?','Une température élevée.',[b['id']]),('cause_effect','Pourquoi enlève-t-elle sa veste ?','Parce qu’il fait chaud à midi.',[]),('single_word_definition','Que signifie « froid » ?','Qui a une température basse.',[a['id']]),('grammar_category','Quel type de mot est « chaud » dans « il fait chaud » ?','Un adjectif.',[b['id']]),('contrast','Pour une température élevée, lequel convient : « chaud » ou « froid » ?','chaud',[a['id'],b['id']]),('cloze_transfer','Complète : En hiver, il fait souvent _____.','froid',[a['id']]),('cloze_transfer','Complète : Le thé est très _____.','chaud',[b['id']])]))
 text='''Camille appelle sa mère avant d’aller au marché. Elle veut acheter un cahier pour l’école et demande quel prix elle peut accepter. Sa mère répond qu’un cahier simple ne doit pas coûter trop cher. Au marché, Camille regarde trois cahiers. Le premier a un prix bas, le deuxième est plus joli mais plus cher, et le troisième est trop grand. Camille décide d’acheter le premier. Avant de payer, elle demande encore le prix au vendeur pour vérifier. Elle comprend qu’acheter signifie choisir un article et le payer, tandis que le prix indique combien il coûte.'''
 a,b=nt('acheter',text,L),nt('prix',text,L)
 out.append(mk(10,'fr-a1-u10-p03',57,'interleaved','Choisir avant d’acheter','shopping-price narrative',['public','personal'],['shopping','price','choice'],text,[a,b],[rev('appeler','R2','running_text',P),rev('répondre','R2','running_text',P)],[{'id':'fr-a1-acheter-purchase','role':'new','description':'acheter for purchasing'},{'id':'fr-a1-prix-cost','role':'new','description':'prix as the cost of an item'}],[{'id':'fr-a1-price-choice','role':'new','description':'compare simple prices before purchase'}],[('gist','Qu’est-ce que Camille veut acheter ?','Un cahier.',[]),('literal_detail','Quel cahier choisit-elle ?','Le premier.',[]),('vocabulary_in_context','Que signifie « acheter » ?','Obtenir un article en le payant.',[a['id']]),('vocabulary_in_context','Que signifie « prix » ?','La somme demandée pour un article.',[b['id']]),('cause_effect','Pourquoi Camille demande-t-elle encore le prix au vendeur ?','Pour vérifier le coût avant de payer.',[]),('single_word_definition','Que signifie « prix » ?','Le coût d’un produit ou d’un service.',[b['id']]),('grammar_category','Quel type de mot est « acheter » ?','Un verbe.',[a['id']]),('contrast','Pour parler du coût, lequel convient : « prix » ou « acheter » ?','prix',[a['id'],b['id']]),('cloze_transfer','Complète : Je vais _____ un cahier.','acheter',[a['id']]),('cloze_transfer','Complète : Quel est le _____ de ce livre ?','prix',[b['id']])]))
 text='''Sami envoie un message à Camille sur son téléphone : il lui demande combien d’argent il faut pour l’activité de samedi. Camille regarde la feuille de l’école. Chaque élève doit apporter cinq euros. Elle répond à Sami qu’un peu d’argent est nécessaire pour acheter une boisson sur place, mais qu’il ne faut rien payer d’autre. Camille met son argent dans une petite poche de son sac. Elle vérifie deux fois qu’il est là. Elle sait que l’argent sert à payer des choses, mais elle préfère toujours vérifier ce qui est réellement nécessaire avant de le prendre ou de le dépenser.'''
 a,b=nt('argent',text,L),nt('vêtement',text,L)
 # `vêtement` is introduced through a brief packing decision added below so the lexical context stays concrete.
 text += ' Elle ajoute aussi un vêtement léger dans son sac, car la salle peut être froide.'
 # rebuild target after final text
 a,b=nt('argent',text,L),nt('vêtement',text,L)
 out.append(mk(10,'fr-a1-u10-p04',58,'transfer','Préparer l’argent et un vêtement','activity-preparation narrative',['personal','educational'],['money','packing','activity'],text,[a,b],[rev('message','R2','running_text',P),rev('téléphone','R2','running_text',P)],[{'id':'fr-a1-argent-money','role':'new','description':'argent as money'},{'id':'fr-a1-vetement-clothing','role':'new','description':'vêtement as an item of clothing'}],[{'id':'fr-a1-pack-needed-items','role':'new','description':'prepare only needed money and clothing'}],[('gist','Que prépare Camille pour l’activité ?','Cinq euros et un vêtement léger.',[]),('literal_detail','Combien d’argent faut-il apporter ?','Cinq euros.',[]),('vocabulary_in_context','Que signifie « argent » ici ?','La monnaie utilisée pour payer.',[a['id']]),('vocabulary_in_context','Que signifie « vêtement » ?','Une pièce que l’on porte sur le corps.',[b['id']]),('cause_effect','Pourquoi prend-elle un vêtement léger ?','Parce que la salle peut être froide.',[]),('single_word_definition','Que signifie « argent » ?','De la monnaie ou des moyens de paiement.',[a['id']]),('grammar_category','Quel type de mot est « vêtement » ?','Un nom.',[b['id']]),('contrast','Pour quelque chose qu’on porte sur le corps, lequel convient : « vêtement » ou « argent » ?','vêtement',[a['id'],b['id']]),('cloze_transfer','Complète : Je garde mon _____ dans une petite poche.','argent',[a['id']]),('cloze_transfer','Complète : Cette veste est un _____.','vêtement',[b['id']])]))
 text='''Camille retrouve un ami et sa famille devant un magasin. Il commence à pleuvoir et il fait froid. Son petit frère n’a qu’un pull léger. La mère de Camille décide d’acheter un manteau simple pour lui. Dans le magasin, Camille regarde aussi une chaussure de sport, puis l’autre paire. Elle n’a pas besoin de nouvelle chaussure aujourd’hui, donc elle ne l’achète pas. Son frère essaie le manteau et dit qu’il est chaud et confortable. La famille vérifie le prix avant de payer. En sortant, Camille voit que la pluie continue, mais son frère est maintenant mieux protégé du froid.'''
 a,b=nt('manteau',text,L),nt('chaussure',text,L)
 out.append(mk(10,'fr-a1-u10-p05',59,'integration','Un manteau pour la pluie','clothing-shopping narrative',['personal','public'],['clothing','weather','shopping'],text,[a,b],[rev('ami','R2','running_text',P),rev('famille','R2','running_text',P)],[{'id':'fr-a1-manteau-clothing','role':'new','description':'manteau as an outer coat'},{'id':'fr-a1-chaussure-footwear','role':'new','description':'chaussure as footwear'}],[{'id':'fr-a1-weather-clothing-choice','role':'new','description':'choose clothing for simple weather conditions'}],[('gist','Pourquoi la mère achète-t-elle un manteau ?','Parce qu’il pleut, il fait froid et le petit frère n’a qu’un pull léger.',[]),('literal_detail','Camille achète-t-elle une chaussure ?','Non.',[]),('vocabulary_in_context','Que signifie « manteau » ?','Un vêtement extérieur qui protège notamment du froid.',[a['id']]),('vocabulary_in_context','Que signifie « chaussure » ?','Un objet porté au pied.',[b['id']]),('cause_effect','Pourquoi Camille ne prend-elle pas de nouvelles chaussures ?','Parce qu’elle n’en a pas besoin aujourd’hui.',[]),('single_word_definition','Que signifie « chaussure » ?','Un objet que l’on porte au pied pour le protéger.',[b['id']]),('grammar_category','Quel type de mot est « manteau » ?','Un nom.',[a['id']]),('contrast','Pour protéger le haut du corps du froid, lequel convient : « manteau » ou « chaussure » ?','manteau',[a['id'],b['id']]),('cloze_transfer','Complète : Je mets mon _____ quand il fait froid.','manteau',[a['id']]),('cloze_transfer','Complète : Je mets une _____ à chaque pied.','chaussure',[b['id']])]))
 text='''À la fin de son niveau A1, Camille peut gérer de nombreuses situations quotidiennes avec un français simple. Elle regarde la pluie ou le soleil et sait dire s’il fait froid ou chaud. Dans un magasin, elle peut demander un prix, décider d’acheter quelque chose et préparer l’argent nécessaire. Elle sait nommer un vêtement comme un manteau ou une chaussure. Elle peut aussi parler avec un ami, écouter, lire, écrire, appeler sa famille et répondre à un message. Avec les mots des unités précédentes, elle sait décrire son quartier, son corps, ses habitudes, ses déplacements et ses besoins essentiels. Elle ne sait pas encore tout dire, mais elle peut déjà comprendre et communiquer dans beaucoup de situations familières.'''
 reviews=[cur(f,L) for f in U10_FORMS]
 out.append(mk(10,'fr-a1-u10-p06',60,'checkpoint','Ce que Camille sait faire en français','A1 capstone summary',['personal','public','educational'],['A1 capstone','communication','daily life'],text,[],reviews,[{'id':'fr-a1-u10-capstone-language','role':'integration','description':'integrate core A1 everyday vocabulary and simple structures'}],[{'id':'fr-a1-u10-capstone-functions','role':'integration','description':'summarize practical A1 communicative abilities'}],[('gist','Quelle est l’idée principale du texte ?','Camille peut maintenant comprendre et communiquer dans de nombreuses situations familières avec un français simple.',[]),('literal_detail','Quels deux types de temps sont nommés ?','La pluie et le soleil.',[]),('vocabulary_in_context','Que signifie « prix » ici ?','Le coût d’un article.',[tid(L['prix']['rank'])]),('vocabulary_in_context','Que signifie « manteau » ?','Un vêtement extérieur.',[tid(L['manteau']['rank'])]),('inference','Pourquoi le texte dit-il que Camille « ne sait pas encore tout dire » ?','Parce qu’A1 est un niveau de base : elle gère des situations familières mais son français reste limité.',[]),('single_word_definition','Que signifie « argent » ?','De la monnaie ou un moyen de paiement.',[tid(L['argent']['rank'])]),('grammar_category','Quel type de mot est « acheter » ?','Un verbe.',[tid(L['acheter']['rank'])]),('contrast','Pour le pied, lequel convient : « chaussure » ou « manteau » ?','chaussure',[tid(L['chaussure']['rank']),tid(L['manteau']['rank'])]),('cloze_transfer','Complète : Quand il fait _____, je mets un manteau.','froid',[tid(L['froid']['rank'])]),('summary','Résume en une phrase ce que Camille peut faire à la fin du niveau A1.','Elle peut communiquer simplement sur sa vie quotidienne, ses déplacements, sa santé, la météo, les achats et ses relations.',[])],speed=True))
 return out

def validate(unit,rows,L,V,expected_unit):
 old={t['id'] for r in rows for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 for r in unit:
  e=sorted(V.iter_errors(r),key=lambda x:list(x.path))
  if e:raise AssertionError(f"{r['id']}: schema {[x.message for x in e[:5]]}")
  if not 90<=r['word_count']<=140:raise AssertionError(f"{r['id']}: word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   s=L.get(t['form'])
   if t['id'] in old or not s or t['source_rank']!=s['rank'] or t['id']!=tid(s['rank']) or count(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: source/exposure/reintroduction drift {t}")
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and count(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if sum(len(r['new_lexical_targets']) for r in unit[:5])!=10 or unit[-1]['new_lexical_targets']!=[]:raise AssertionError(f'U{expected_unit}: lexical-cycle invariant')

def main():
 blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if blob!=EXPECTED_BLOB:raise AssertionError(f'canonical blob drift: {blob} != {EXPECTED_BLOB}')
 rows=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(rows)!=48 or [r['sequence'] for r in rows]!=list(range(1,49)) or rows[-1]['id']!='fr-a1-u08-p06':raise AssertionError('expected exact 48-passage frontier through Unit 08')
 L=lexicon();V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')))
 u9=build_u9(rows,L)
 if [r['sequence'] for r in u9]!=list(range(49,55)):raise AssertionError('U09 continuity')
 validate(u9,rows,L,V,9)
 interim=rows+u9
 u10=build_u10(interim,L)
 if [r['sequence'] for r in u10]!=list(range(55,61)):raise AssertionError('U10 continuity')
 validate(u10,interim,L,V,10)
 allrows=interim+u10
 if len(allrows)!=60 or [r['sequence'] for r in allrows]!=list(range(1,61)) or len({r['id'] for r in allrows})!=60:raise AssertionError('A1 completion continuity failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in allrows),encoding='utf-8')
 print(json.dumps({'status':'PASS','units':[9,10],'appended_passages':12,'a1_passages':60,'word_counts':{r['id']:r['word_count'] for r in u9+u10},'u09_targets':[{'form':f,'rank':L[f]['rank'],'id':tid(L[f]['rank'])} for f in U9_FORMS],'u10_targets':[{'form':f,'rank':L[f]['rank'],'id':tid(L[f]['rank'])} for f in U10_FORMS],'p06_new_targets':{'u09':len(u9[-1]['new_lexical_targets']),'u10':len(u10[-1]['new_lexical_targets'])},'questions':120,'answers':120},ensure_ascii=False))
if __name__=='__main__':main()
