#!/usr/bin/env python3
"""Generate French C1 Unit04: language, identity, and society.

Requires exact Unit03 C1 lock, canonical Unit04 plan, exhaustive freshness probe
and curated content-word target selection. Produces five standard 500–800 word
passages plus a zero-new checkpoint, 10 linked Q/A each, and a materially
opposed paired-viewpoint set.
"""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
R=Path(__file__).resolve().parents[2];C1=R/'reading/french/c1/passages.jsonl';B2=R/'reading/french/b2/passages.jsonl';SCHEMA=R/'reading/schema/passage.schema.json';LOCK=R/'reading/audit/french_c1_unit03_frontier_lock.json';PLAN=R/'reading/audit/french_c1_unit04_plan.json';SEL=R/'reading/audit/french_c1_unit04_target_selection.json'
PAIR='fr-c1-u04-language-norms-viewpoints'
USE={
'monsieur':'« Monsieur » fonctionne comme une forme d’adresse dont le degré de distance ou de respect dépend du cadre institutionnel et de la relation entre interlocuteurs.',
'madame':'« Madame » peut signaler politesse, statut ou distance; l’analyse doit observer qui l’emploie, envers qui et dans quelle situation plutôt que lui attribuer une valeur sociale fixe.',
'gars':'« Gars » appartient à un registre familier : son emploi peut créer de la proximité dans un groupe et paraître déplacé dans un autre contexte.',
'mec':'« Mec » illustre encore plus clairement la variation de registre; sa signification sociale dépend du ton, du groupe et de la relation, pas seulement de sa définition lexicale.',
'fille':'« Fille » peut désigner l’âge, une relation familiale ou une catégorie sociale selon le contexte; une analyse rigoureuse précise le sens activé avant d’en tirer une conclusion identitaire.',
'garçon':'« Garçon » montre également que les catégories de personne sont interprétées par l’âge, la situation et les normes locales; le mot ne suffit pas à décrire toute l’identité d’un individu.',
'fils':'« Fils » exprime une relation familiale qui peut devenir socialement importante dans certains récits, mais sa pertinence dépend de la question étudiée.',
'frère':'« Frère » peut nommer une parenté réelle ou, dans certains groupes, une proximité symbolique; le lecteur doit distinguer ces usages à partir d’indices contextuels.',
'copain':'« Copain » marque une relation sociale informelle dont le degré d’intimité varie selon les locuteurs; le terme aide à étudier comment une communauté nomme ses liens.',
'copine':'« Copine » peut désigner une amie ou une partenaire selon le contexte; cette ambiguïté montre pourquoi l’interprétation sociale exige plus que la traduction littérale.',
'mari':'« Mari » désigne une relation institutionnalisée, mais le rôle social attribué à cette relation varie entre milieux et ne doit pas être déduit du mot seul.',
'bande':'Une « bande » peut être un groupe d’amis, un collectif ou un groupe perçu négativement; le choix de ce mot peut donc révéler le point de vue du locuteur autant que la composition du groupe.',
'écouter':'« Écouter » ne signifie pas seulement recevoir des mots : dans une interaction sociale, cela implique reconnaître le cadre, les implicites et la position depuis laquelle l’autre parle.',
'anglais':'« Anglais » sert ici d’exemple de langue socialement marquée : le choix d’une langue peut faciliter l’accès pour certains interlocuteurs et créer une distance pour d’autres.',
'pardon':'« Pardon » est à la fois un mot lexical et une ressource interactionnelle : selon l’intonation, il peut réparer une interruption, demander une répétition ou marquer une objection.',
'genre':'« Genre » possède plusieurs usages, dont catégorie, style et identité sociale; une analyse C1 doit établir le sens local au lieu de projeter automatiquement un seul débat sur chaque occurrence.',
'maman':'« Maman » montre comment une forme d’adresse familiale combine relation, affect et registre; son usage public ou privé peut produire des effets sociaux différents.',
'papa':'« Papa » fonctionne de manière comparable : la relation familiale est stable, mais la manière de la nommer varie avec l’âge, la situation et le style du locuteur.',
'lycée':'Le « lycée » constitue un espace de socialisation où des normes de langue, de groupe et de présentation de soi peuvent se rencontrer, se renforcer ou se contester.',
'grandir':'« Grandir » désigne ici un processus social autant que chronologique : les locuteurs apprennent au fil du temps quels registres, catégories et appartenances sont valorisés dans différents milieux.'
}
EXTRA=[
"Une analyse de langue sociale doit séparer fréquence et valeur. Une forme très fréquente n’est pas nécessairement neutre, tandis qu’une forme rare peut être parfaitement appropriée dans un groupe précis. Le corpus est donc comparé par situation, relation et objectif communicatif plutôt que classé selon une seule échelle de correction.",
"Le contreargument consiste à demander si le contraste observé vient vraiment de l’identité du groupe ou d’une autre variable, par exemple l’âge, la profession, le média ou le degré de familiarité. Sans ce test, une différence de registre risque d’être transformée trop vite en caractéristique essentielle des personnes.",
"La portée de la conclusion reste limitée aux interactions documentées. Le texte indique quelles formes pourraient changer de valeur dans une autre région, une autre génération ou un autre cadre institutionnel. Cette limite protège l’analyse contre la tentation de présenter une pratique locale comme règle générale.",
"Enfin, la révision est prévue : si de nouveaux exemples montrent qu’une forme circule entre des groupes auparavant séparés, la catégorie analytique doit être modifiée. L’identité linguistique devient ainsi une hypothèse sur des pratiques observables, non une étiquette figée attribuée aux locuteurs."
]

def h(p):return subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
def bridge(forms):return 'Révision explicite : '+', '.join(f'« {x} »' for x in forms)+'. Ces formes servent à relier ce texte au travail institutionnel précédent sans confondre les deux thèmes.'
def fit(paras,lo,hi):
 p=list(paras);text='\n\n'.join(p);i=0
 while len(text.split())<lo and i<len(EXTRA):p[-1]+=' '+EXTRA[i];i+=1;text='\n\n'.join(p)
 if len(text.split())<lo:raise AssertionError(f'Unit04 below C1 minimum {len(text.split())} < {lo}')
 if len(text.split())>hi:raise AssertionError(f'Unit04 above C1 maximum {len(text.split())} > {hi}')
 return p,text

def items_for(spec,forms):
 return [
 ('main_claim',spec['qclaim'],spec['aclaim'],[forms[0]]),
 ('inference','Quelle inférence le texte refuse-t-il de faire automatiquement ?',spec['ainfer'],[forms[1]]),
 ('assumption','Quelle hypothèse doit être vérifiée avant de généraliser ?',spec['aassume'],[forms[2]]),
 ('argument_relation','Comment le texte traite-t-il une explication concurrente ?',spec['arelation'],[forms[3]]),
 ('scope','Quelle limite de portée est explicitement importante ?',spec['ascope'],[forms[0],forms[3]]),
 ('stance','Quelle position méthodologique l’auteur adopte-t-il ?',spec['astance'],[forms[1]]),
 ]+[( 'vocabulary_in_context',f'Quel rôle joue « {f} » dans ce passage ?',USE[f],[f]) for f in forms]

def make(spec,forms,reviews,prior,deck,lo,hi,theme):
 paras=list(spec['paras']);paras[1]+=' '+' '.join(USE[f] for f in forms);paras[2]+=' '+bridge(reviews);paras,text=fit(paras,lo,hi)
 new=[base.nt(f,text,deck) for f in forms];rev=[base.rev(f,prior) for f in reviews];ids={t['form']:t['id'] for t in new+rev};q,a=base.qa(items_for(spec,forms),ids)
 return {'id':spec['id'],'language':'fr','cefr':'C1','unit':4,'sequence':spec['seq'],'revision':1,'title':spec['title'],'passage_type':'standard','genre':spec['genre'],'domains':spec['domains'],'topics':[theme]+spec['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”\"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':rev,'grammar_targets':[{'id':spec['id']+'-g1','role':'target','description':'qualify social and linguistic categories through context, register and scope'}],'discourse_targets':[{'id':spec['id']+'-d1','role':'target','description':'evaluate social labels, competing explanations and identity claims without essentializing speakers'}],'questions':q,'answer_key':a,'speed_training':{'timed':True,'benchmark_eligible':True,'comprehension_gate':0.8,'new_word_policy':'standard','notes':'C1 Unit04 language/identity analysis.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Generated against exact Unit03 lock; contextual social-label analysis.']},'paired_text_group':spec.get('pair'),'prerequisites':['French C1 Unit03'],'difficulty_notes_internal':'C1 contextual identity/register analysis.','reader_tags':['unit_role:standard','generation_batch','french_c1_u04']}

def specs(theme):
 return [
 {'id':'fr-c1-u04-p01','seq':19,'title':'Dire monsieur, dire mec : le registre comme relation sociale','genre':'analysis','domains':['social','educational'],'topics':['register','forms of address'],'paras':["Deux personnes peuvent désigner le même interlocuteur avec des formes très différentes sans simplement transmettre des degrés opposés de respect. Le choix dépend de l’institution, de l’âge relatif, de la familiarité, du média et de l’objectif de l’échange. Une étude de registre doit donc reconstruire la relation plutôt que classer les mots sur une échelle universelle.","Le premier dossier compare des conversations de service, de classe et de groupe amical. Les chercheurs notent les formes d’adresse, les changements au cours de l’échange et les réactions qui suivent. Ils évitent d’associer automatiquement une forme familière à un manque de respect : dans certains groupes elle manifeste précisément l’inclusion.","Le point difficile concerne l’interprétation du contraste. Une différence entre deux milieux peut venir du statut institutionnel, mais aussi du canal écrit ou oral, du degré de connaissance entre personnes ou d’une stratégie individuelle. L’analyse conserve plusieurs explications jusqu’à ce qu’un changement de contexte permette de les distinguer.","La conclusion défend une norme descriptive exigeante : documenter les conditions d’emploi avant d’évaluer les effets sociaux. Une forme devient alors un indice relationnel dont la portée doit être testée, non une mesure directe du caractère ou de l’identité du locuteur."],'qclaim':'Quelle thèse organise l’analyse du registre ?','aclaim':'Les formes d’adresse signalent des relations contextuelles et ne peuvent être classées correctement sans reconstruire la situation sociale.','ainfer':'Le texte refuse de déduire automatiquement le respect ou l’irrespect d’un seul mot.','aassume':'Il faut vérifier que les groupes comparés diffèrent bien par relation sociale plutôt que seulement par canal, âge ou familiarité.','arelation':'Il conserve plusieurs causes possibles et cherche des changements de contexte qui permettent de les distinguer.','ascope':'La valeur sociale d’une forme est limitée aux situations et communautés où son usage est observé.','astance':'Une approche descriptive, comparative et anti-essentialiste du registre.'},
 {'id':'fr-c1-u04-p02','seq':20,'title':'Catégories familiales et catégories de personne','genre':'essay','domains':['social','educational'],'topics':['social categories','family terms'],'paras':["Les mots qui classent des personnes paraissent souvent transparents parce qu’ils sont appris très tôt. Pourtant, leur rôle dans un argument dépend de la question posée. Une catégorie familiale, une catégorie d’âge ou une catégorie de genre peut être pertinente pour un mécanisme précis et inutile pour un autre.","Le dossier examine des formulaires, des récits biographiques et des échanges scolaires. Une même personne peut être décrite par plusieurs relations simultanées. L’analyse demande donc quelle catégorie produit une différence observable dans la situation étudiée, au lieu de choisir celle qui semble la plus évidente culturellement.","Cette prudence n’interdit pas les comparaisons entre groupes. Elle impose seulement de montrer le mécanisme qui rend une distinction pertinente et de chercher la variation interne. Si deux personnes classées de la même manière vivent des situations opposées, la catégorie ne peut expliquer seule le résultat.","La position finale est double : les catégories sociales structurent réellement certaines institutions, mais leurs effets doivent être établis empiriquement. Reconnaître leur importance ne signifie pas transformer une étiquette en essence complète d’une personne."],'qclaim':'Quelle relation le texte établit-il entre catégories et explication ?','aclaim':'Une catégorie peut être socialement importante sans constituer à elle seule une explication; sa pertinence doit être reliée à un mécanisme observable.','ainfer':'Il refuse de réduire une personne à la catégorie la plus visible ou la plus familière.','aassume':'Toute comparaison suppose que la catégorie retenue corresponde à une différence pertinente dans le mécanisme étudié.','arelation':'La variation interne sert de contrepreuve contre les explications qui attribuent tout le résultat à une seule catégorie.','ascope':'Les conclusions portent sur les institutions et situations où la catégorie modifie effectivement des règles ou des expériences.','astance':'Reconnaître les effets sociaux des catégories tout en refusant leur essentialisation.'},
 {'id':'fr-c1-u04-p03','seq':21,'title':'Point de vue A : laisser les groupes nommer leurs liens','genre':'paired viewpoints','domains':['social','cultural'],'topics':['belonging','community labels'],'pair':PAIR,'paras':["Le premier point de vue soutient qu’une partie importante de l’identité linguistique vient de la capacité d’un groupe à nommer lui-même ses relations. Les termes de proximité ne possèdent pas toujours des frontières stables, mais cette souplesse peut être fonctionnelle : elle permet de signaler une confiance, une histoire commune ou une appartenance que les catégories administratives saisissent mal.","Dans cette perspective, imposer trop rapidement une définition externe risque d’effacer des distinctions locales. L’analyse doit d’abord observer qui adopte un terme, qui le refuse, comment son sens change selon l’interlocuteur et quelles conséquences suivent l’emploi. La variation devient une donnée sur le groupe plutôt qu’une erreur à corriger.","Le point de vue reconnaît néanmoins un problème : les mots d’appartenance peuvent aussi exclure. Une étiquette valorisée à l’intérieur du groupe peut être utilisée différemment par un observateur extérieur. Pour cette raison, l’autonomie locale ne dispense pas de décrire les effets sur les personnes qui contestent le terme ou n’y sont pas reconnues.","La recommandation consiste donc à commencer par l’usage communautaire, puis à documenter les frontières et les désaccords. Une norme commune peut être nécessaire pour comparer des données, mais elle devrait conserver la trace des catégories choisies par les locuteurs lorsque celles-ci changent la signification de l’expérience."],'qclaim':'Quelle priorité défend le point de vue A ?','aclaim':'Commencer par les catégories et termes employés par les groupes eux-mêmes, puis documenter leurs frontières et effets.','ainfer':'Il refuse de considérer toute variation locale comme une erreur terminologique.','aassume':'L’usage local apporte une information sur l’appartenance que les catégories externes peuvent perdre.','arelation':'Il concède le risque d’exclusion et exige d’observer les personnes qui refusent ou subissent l’étiquette.','ascope':'L’autonomie terminologique reste limitée lorsque l’usage affecte d’autres groupes ou empêche la comparaison.','astance':'Privilégier l’auto-désignation documentée avec des garde-fous sur l’exclusion.'},
 {'id':'fr-c1-u04-p04','seq':22,'title':'Point de vue B : une langue partagée exige aussi des repères communs','genre':'paired viewpoints','domains':['social','educational'],'topics':['shared norms','multilingual communication'],'pair':PAIR,'paras':["Le second point de vue part d’un risque différent : lorsque chaque groupe utilise ses propres catégories sans traduction ni repère commun, l’accès aux institutions peut devenir inégal. Une école, un service ou une enquête doit parfois comparer des réponses et rendre ses messages compréhensibles à des personnes qui ne partagent pas les mêmes codes locaux.","Il défend donc un noyau de conventions communes, notamment pour les situations où une ambiguïté peut modifier un droit, une décision ou la compréhension d’une consigne. Cette position ne suppose pas qu’une seule langue ou un seul registre soit supérieur. Elle demande que les équivalences et les divergences soient rendues visibles afin que la communication reste contrôlable.","Le meilleur contreargument vient du point de vue A : toute standardisation peut favoriser le groupe dont les usages ressemblent déjà à la norme. Le point de vue B répond qu’une norme explicite peut justement être critiquée, traduite et adaptée plus facilement qu’une convention implicite détenue par les initiés.","La synthèse proposée est institutionnelle : définir un repère commun minimal, enregistrer les variantes qui changent le sens, et tester qui comprend effectivement les messages. Une norme n’est alors pas une identité obligatoire mais une infrastructure révisable de communication."],'qclaim':'Quelle priorité défend le point de vue B ?','aclaim':'Maintenir des repères communs explicites pour assurer intelligibilité, comparaison et accès institutionnel.','ainfer':'Il refuse d’assimiler norme commune et supériorité d’une identité linguistique.','aassume':'Une convention explicite peut être traduite, testée et révisée plus facilement qu’une convention implicite.','arelation':'Il prend au sérieux le biais de standardisation puis propose d’enregistrer et tester les variantes locales.','ascope':'Le besoin de repères communs est surtout fort lorsque compréhension, droit ou comparaison dépendent du message.','astance':'Défendre un noyau commun minimal, transparent et révisable plutôt qu’une uniformité culturelle.'},
 {'id':'fr-c1-u04-p05','seq':23,'title':'Grandir entre famille, école et plusieurs registres','genre':'analysis','domains':['social','educational'],'topics':['socialization','school language'],'paras':["L’identité linguistique se construit rarement dans un seul espace. Une personne apprend des formes familiales, des pratiques scolaires, des codes de pairs et parfois plusieurs langues ou variétés. Grandir consiste en partie à comprendre que la même intention peut être formulée différemment selon le public et que ces choix produisent des interprétations sociales.","Le dossier suit des situations de passage entre maison et école sans traiter l’un des registres comme version déficiente de l’autre. Il observe quelles ressources sont transférables, quelles formes sont réservées à certains liens et comment les élèves expliquent eux-mêmes leurs choix lorsqu’ils changent de style.","Une explication uniquement familiale serait insuffisante, car les établissements, médias et groupes de pairs créent aussi des attentes. Inversement, attribuer chaque différence à l’école ignorerait les pratiques déjà acquises et les trajectoires individuelles. L’analyse cherche donc des changements de contexte qui révèlent quelle influence devient active.","La recommandation pédagogique n’est pas d’effacer les registres existants, mais de rendre leur fonctionnement visible et d’élargir le répertoire disponible. La compétence avancée consiste alors à choisir, comprendre et parfois contester une norme en sachant quelles conséquences sociales ce choix peut avoir."],'qclaim':'Comment le texte définit-il la socialisation linguistique ?','aclaim':'Comme l’apprentissage progressif de plusieurs registres et des conditions sociales dans lesquelles leurs choix deviennent interprétables.','ainfer':'Il refuse de considérer le registre familial comme une simple version déficiente du registre scolaire.','aassume':'Les changements de style doivent être reliés à des contextes observables pour attribuer une influence à la famille, à l’école ou aux pairs.','arelation':'Le texte oppose les explications monocausales et recherche les situations de transition qui permettent de les départager.','ascope':'La recommandation porte sur l’élargissement du répertoire, pas sur l’abandon obligatoire des pratiques familiales.','astance':'Une pédagogie de répertoire, de conscience du contexte et de choix informé.'}
 ]

def checkpoint(groups,deck,lo,hi,theme):
 forms=[f for k in ['p01','p02','p03','p04','p05'] for f in groups[k]];rev=[base.cur(f,deck) for f in forms];ids={t['form']:t['id'] for t in rev};g=[groups[f'p0{i}'] for i in range(1,6)]
 paras=[f"Le checkpoint de « {theme} » rassemble registre, catégories sociales, appartenance et socialisation. Les formes « {g[0][0]} », « {g[0][1]} », « {g[0][2]} » et « {g[0][3]} » rappellent que la valeur sociale d’une adresse dépend d’une relation et d’un contexte plutôt que d’une hiérarchie universelle.",f"Les catégories « {g[1][0]} », « {g[1][1]} », « {g[1][2]} » et « {g[1][3]} » montrent ensuite qu’un mot peut être socialement pertinent sans résumer une personne. L’analyse exige un mécanisme, une comparaison et une vérification de la variation interne avant de transformer une catégorie en explication.",f"Les relations « {g[2][0]} », « {g[2][1]} », « {g[2][2]} » et « {g[2][3]} » conduisent au débat entre auto-désignation et repères communs. « {g[3][0]} », « {g[3][1]} », « {g[3][2]} » et « {g[3][3]} » rappellent qu’une communication partagée doit rester compréhensible sans effacer les usages locaux. Le compromis est un noyau explicite accompagné de variantes documentées.",f"Enfin, « {g[4][0]} », « {g[4][1]} », « {g[4][2]} » et « {g[4][3]} » replacent ces choix dans la socialisation. La compétence C1 consiste à interpréter les catégories et registres comme des pratiques situées, à comparer les explications concurrentes et à réviser une norme lorsque ses effets d’accès, de compréhension ou d’exclusion ne correspondent plus à l’objectif annoncé."]
 paras,text=fit(paras,lo,hi)
 items=[('main_claim','Quelle règle générale clôt l’unité ?','Interpréter les formes sociales dans leur contexte, tester les mécanismes et maintenir des normes communes seulement lorsqu’elles restent transparentes, accessibles et révisables.',[g[0][0],g[3][1]]),('argument_relation','Quel compromis rapproche les deux points de vue ?','Un repère commun minimal qui conserve et documente les variantes locales lorsqu’elles changent le sens ou l’accès.',[g[2][3],g[3][1]]),('assumption','Pourquoi une catégorie ne suffit-elle pas comme explication ?','Parce qu’il faut montrer par quel mécanisme elle modifie une règle, une expérience ou une interaction et vérifier la variation interne.',[g[1][0],g[1][1]]),('inference','Que signale le passage d’un registre à un autre ?','Une adaptation à un public, une relation ou une institution, dont la signification doit être établie par le contexte.',[g[4][2],g[4][3]]),('stance','Quelle position le checkpoint adopte-t-il sur les normes ?','Des normes explicites mais limitées et révisables, compatibles avec la pluralité des usages sociaux.',[g[3][0],g[3][3]]),('reference_resolution','À quoi renvoie « ces choix » dans le dernier mouvement ?','Aux choix de catégories, de registres, de langue et de conventions communes.',[g[4][0]]),('cross_text_synthesis','Pourquoi les deux points de vue restent-ils utiles ensemble ?','L’un protège l’information locale et l’auto-désignation; l’autre protège l’intelligibilité et l’accès entre groupes.',[g[2][0],g[3][1]]),('vocabulary_in_context','Pourquoi les vingt formes sont-elles regroupées ?','Elles représentent des fonctions de registre, catégorie, relation, communication et socialisation.',g[0]),('synthesis','Quand faut-il réviser une convention linguistique institutionnelle ?','Quand les données montrent qu’elle crée une incompréhension, un biais d’accès ou une perte de sens que des adaptations contrôlées peuvent réduire.',[g[3][2],g[4][3]]),('summary','Résume le checkpoint Unit04.','Le niveau C1 relie usages linguistiques, identité et institutions sans essentialiser les personnes : il contextualise les labels, compare les mécanismes et traite les normes comme des outils révisables.',forms)];q,a=base.qa(items,ids)
 return {'id':'fr-c1-u04-p06','language':'fr','cefr':'C1','unit':4,'sequence':24,'revision':1,'title':f'Checkpoint C1 Unit04 : langage, appartenance et normes — {theme}','passage_type':'checkpoint','genre':'analysis','domains':['social','educational'],'topics':[theme,'C1 Unit04','checkpoint'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”\"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':[],'review_lexical_targets':rev,'grammar_targets':[{'id':'fr-c1-u04-g-checkpoint','role':'review','description':'synthesize register, category, social identity and contextual qualification'}],'discourse_targets':[{'id':'fr-c1-u04-d-checkpoint','role':'review','description':'integrate paired viewpoints on local identity practices and common language norms'}],'questions':q,'answer_key':a,'speed_training':{'timed':True,'benchmark_eligible':True,'comprehension_gate':0.8,'new_word_policy':'none','notes':'C1 Unit04 checkpoint.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Zero-new C1 Unit04 checkpoint.']},'paired_text_group':None,'prerequisites':['French C1 Unit04 P01-P05'],'difficulty_notes_internal':'C1 Unit04 cumulative checkpoint.','reader_tags':['unit_role:checkpoint','generation_batch','french_c1_u04']}

def main():
 lock=json.loads(LOCK.read_text(encoding='utf-8'));plan=json.loads(PLAN.read_text(encoding='utf-8'));sel=json.loads(SEL.read_text(encoding='utf-8'));c1blob=h(C1);b2blob=h(B2)
 if lock.get('status')!='PASS' or lock.get('last_sequence')!=18 or lock.get('c1_canonical_blob')!=c1blob or lock.get('b2_canonical_blob')!=b2blob:raise AssertionError('Unit03 lock/live C1 mismatch')
 if plan.get('status')!='PASS' or plan.get('c1_source_blob')!=c1blob or sel.get('status')!='PASS' or sel.get('c1_source_blob')!=c1blob:raise AssertionError('Unit04 plan/selection stale')
 rows=[json.loads(x) for x in C1.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(rows)!=18:raise AssertionError('Unit04 generator requires exactly 18 prior C1 rows')
 groups=sel['passage_groups'];review=lock['unit03_target_groups'];deck=base.deck();theme=plan['theme'];lo,hi=plan['c1_word_min'],plan['c1_word_max'];unit=[]
 for s in specs(theme):unit.append(make(s,groups[s['id'][-3:]],review[s['id'][-3:]],rows,deck,lo,hi,theme))
 unit.append(checkpoint(groups,deck,lo,hi,theme))
 V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));selected={x['form'] for x in sel['selected']};new=[]
 for r in unit:
  errs=list(V.iter_errors(r))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:6]]}")
  if not lo<=r['word_count']<=hi or r['word_count']!=len(r['text'].split()):raise AssertionError(f"{r['id']}: word band/count failure {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: expected 10 Q/A")
  local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[])};amap={a['question_id']:a['id'] for a in r['answer_key']}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(t not in local for t in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage failure")
  for t in r.get('new_lexical_targets',[]):
   if base.cnt(r['text'],t['form'])!=t['exposures_in_text'] or t['exposures_in_text']<1:raise AssertionError(f"{r['id']}: exposure failure {t['form']}")
   new.append(t)
  for t in r.get('review_lexical_targets',[]):
   if base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: exact review missing {t['form']}")
 if len(new)!=20 or {t['form'] for t in new}!=selected or len({t['id'] for t in new})!=20:raise AssertionError('Unit04 target selection/uniqueness mismatch')
 if unit[-1]['new_lexical_targets']:raise AssertionError('Unit04 checkpoint introduced new targets')
 with C1.open('a',encoding='utf-8') as f:
  for r in unit:f.write(json.dumps(r,ensure_ascii=False)+'\n')
 print(json.dumps({'status':'PASS','c1_passages':24,'unit04_word_counts':[r['word_count'] for r in unit],'unit04_targets':sorted(selected),'paired_group':PAIR},ensure_ascii=False))
if __name__=='__main__':main()
