#!/usr/bin/env python3
"""Append French A2 Unit 10 (sequences 55-60), completing A2 generation."""
from __future__ import annotations
import json,re,subprocess
from jsonschema import Draft202012Validator
import generate_french_a2_unit03 as base
A1=base.A1; CANON=base.CANON; SCHEMA=base.SCHEMA
EXPECTED_A1_BLOB="0493a2fa13e51b5997db05e91cdea4d8dc5e647b"
EXPECTED_BLOB="911235c745a4c5802b6f3433bececa1f9bcd216f"
FORMS=("habiter","milieu","cuisine","fenêtre","vidéo","caméra","retenir","image","proposer","gérer")
SPECS=[
{"id":"fr-a2-u10-p01","sequence":55,"ptype":"instructional","title":"Habiter dans un nouveau milieu","genre":"neighborhood interview narrative","domains":["public","educational","personal"],"topics":["neighborhood","living environment","interview"],"forms":["habiter","milieu"],"reviews":["excuse","surprise"],"text":"""Pour le dernier atelier du niveau A2, la classe prépare un petit projet sur le quartier. Camille doit interviewer une personne qui vient habiter dans la ville depuis quelques mois. La veille, cette personne envoie une excuse parce qu’elle doit déplacer le rendez-vous. Camille pense d’abord que le projet sera retardé, mais une surprise positive arrive ensuite : une autre habitante accepte de participer au même horaire. Elle explique qu’elle aime habiter près du centre tout en restant dans un milieu assez calme. Pour elle, le milieu d’un quartier comprend les rues, les services, les voisins et l’ambiance générale. Camille pose des questions simples sur les avantages et les difficultés de la vie locale. Elle remercie l’habitante et note soigneusement ses réponses. L’excuse du premier participant n’a donc pas bloqué le projet. Camille comprend qu’habiter dans un lieu signifie aussi apprendre à connaître son milieu et s’adapter à ses habitudes.""","grammar":[{"id":"fr-a2-u10-habiter-dans","role":"new","description":"use habiter dans / près de to describe where someone lives"}],"discourse":[{"id":"fr-a2-u10-neighborhood-interview","role":"new","description":"recover from a scheduling change and gather information about a living environment"}],"items":[("gist","Quel est le sujet de l’interview de Camille ?","La vie dans le quartier et le milieu où l’habitante vit.",["habiter","milieu"]),("literal_detail","Pourquoi le premier participant envoie-t-il une excuse ?","Parce qu’il doit déplacer le rendez-vous.",["excuse"]),("sequence","Quelle surprise arrive après l’excuse ?","Une autre habitante accepte de participer au même horaire.",["surprise"]),("cause_effect","Pourquoi le projet n’est-il pas retardé ?","Parce qu’une autre personne accepte l’interview au même horaire.",[]),("vocabulary_in_context","Que signifie « habiter » ici ?","Vivre dans un lieu comme résidence.",["habiter"]),("vocabulary_in_context","Que signifie « milieu » dans ce texte ?","L’environnement et le contexte du quartier.",["milieu"]),("reference_resolution","Dans « elle explique », qui est « elle » ?","La nouvelle habitante.",[]),("inference","Pourquoi Camille pose-t-elle des questions sur les services et les voisins ?","Parce qu’ils font partie du milieu de vie de l’habitante.",["milieu"]),("cloze_transfer","Complète : Je viens _____ dans ce quartier.","habiter",["habiter"]),("cloze_transfer","Complète : Elle préfère un _____ calme.","milieu",["milieu"])]},
{"id":"fr-a2-u10-p02","sequence":56,"ptype":"reinforcement","title":"La cuisine près de la fenêtre","genre":"community-room planning narrative","domains":["public","educational"],"topics":["room setup","kitchen","window"],"forms":["cuisine","fenêtre"],"reviews":["bruit","fonctionner"],"text":"""Le lendemain, le groupe visite une salle communautaire pour préparer une démonstration. Une petite cuisine se trouve au fond, juste à côté d’une grande fenêtre. Sami veut fermer la fenêtre parce qu’un bruit de travaux entre dans la pièce, mais Camille remarque qu’un appareil de ventilation doit fonctionner pendant l’activité. Ils demandent au responsable si la fenêtre peut rester fermée sans gêner l’air. Il explique que la ventilation fonctionne indépendamment et que la cuisine possède aussi une sortie adaptée. Le groupe ferme donc la fenêtre pendant quelques minutes pour réduire le bruit, puis vérifie que la salle reste confortable. Camille observe aussi que la cuisine est séparée de l’espace principal par une porte. Cette organisation facilite la préparation des boissons sans interrompre la démonstration. Elle retient qu’une fenêtre, une cuisine et un appareil qui fonctionne correctement peuvent avoir des rôles différents dans le même espace.""","grammar":[{"id":"fr-a2-u10-pres-de","role":"new","description":"use près de / à côté de to locate parts of a room"}],"discourse":[{"id":"fr-a2-u10-room-tradeoff","role":"new","description":"balance noise reduction, ventilation and room functions during setup"}],"items":[("gist","Pourquoi le groupe discute-t-il de la fenêtre ?","Pour réduire le bruit tout en gardant une ventilation correcte.",["fenêtre","bruit","fonctionner"]),("literal_detail","Où se trouve la cuisine ?","Au fond, près d’une grande fenêtre.",["cuisine","fenêtre"]),("sequence","Que fait le groupe après avoir fermé la fenêtre ?","Il vérifie que la salle reste confortable.",["fenêtre"]),("cause_effect","Pourquoi peuvent-ils fermer la fenêtre ?","Parce que la ventilation fonctionne indépendamment.",["fenêtre","fonctionner"]),("vocabulary_in_context","Que désigne « cuisine » ici ?","La partie de la salle où l’on peut préparer des boissons ou des aliments.",["cuisine"]),("vocabulary_in_context","Que désigne « fenêtre » ?","L’ouverture vitrée donnant sur l’extérieur.",["fenêtre"]),("reference_resolution","Dans « il explique », qui est « il » ?","Le responsable de la salle.",[]),("inference","Pourquoi la porte de la cuisine est-elle utile ?","Parce qu’elle permet de préparer des boissons sans trop interrompre l’activité.",["cuisine"]),("cloze_transfer","Complète : Nous préparons le thé dans la _____.","cuisine",["cuisine"]),("cloze_transfer","Complète : Ouvre la _____ pour regarder dehors.","fenêtre",["fenêtre"])]},
{"id":"fr-a2-u10-p03","sequence":57,"ptype":"interleaved","title":"Une vidéo avec une caméra","genre":"small media-project narrative","domains":["educational","personal"],"topics":["video production","camera","team roles"],"forms":["vidéo","caméra"],"reviews":["moitié","rater"],"text":"""La classe décide ensuite de produire une courte vidéo sur son projet. Une caméra est disponible, mais la moitié du groupe ne l’a jamais utilisée. Camille craint de rater le temps prévu pour le tournage si chacun apprend toutes les fonctions en même temps. La responsable propose donc une organisation simple : deux élèves préparent la caméra, deux autres vérifient le son et le reste du groupe prépare les phrases de la vidéo. Après dix minutes, la moitié des tâches est déjà terminée. Sami appuie trop tôt sur un bouton, mais la caméra n’est pas endommagée et ils recommencent la prise. Personne ne veut rater la dernière navette, alors le groupe limite la vidéo à deux minutes. Camille découvre qu’une caméra peut sembler compliquée au début, mais que répartir le travail permet de finir une vidéo claire sans prolonger inutilement le tournage.""","grammar":[{"id":"fr-a2-u10-si-schedule","role":"review","description":"use si to express a scheduling risk and its consequence"}],"discourse":[{"id":"fr-a2-u10-media-role-split","role":"new","description":"divide media-production roles to protect a fixed deadline"}],"items":[("gist","Comment le groupe évite-t-il de perdre trop de temps ?","Il répartit les tâches nécessaires à la vidéo et à la caméra.",["vidéo","caméra"]),("literal_detail","Quelle partie du groupe n’a jamais utilisé la caméra ?","La moitié.",["moitié","caméra"]),("sequence","Que se passe-t-il après que Sami appuie trop tôt sur un bouton ?","Le groupe recommence la prise.",["caméra"]),("cause_effect","Pourquoi la vidéo est-elle limitée à deux minutes ?","Parce que personne ne veut rater la dernière navette.",["vidéo","rater"]),("vocabulary_in_context","Que signifie « vidéo » ici ?","Un court enregistrement d’images et de son.",["vidéo"]),("vocabulary_in_context","Que désigne « caméra » ?","L’appareil utilisé pour enregistrer la vidéo.",["caméra"]),("reference_resolution","Dans « ils recommencent », qui sont « ils » ?","Les membres du groupe.",[]),("inference","Pourquoi répartir les rôles aide-t-il la classe ?","Parce que plusieurs tâches peuvent avancer sans que chacun apprenne tout en même temps.",[]),("cloze_transfer","Complète : Nous regardons une courte _____.","vidéo",["vidéo"]),("cloze_transfer","Complète : La _____ enregistre les images.","caméra",["caméra"])]},
{"id":"fr-a2-u10-p04","sequence":58,"ptype":"transfer","title":"Retenir une idée grâce à une image","genre":"memory strategy narrative","domains":["educational","personal"],"topics":["memory","image","verification"],"forms":["retenir","image"],"reviews":["cerveau","respirer"],"text":"""Après le tournage, Camille regarde une image extraite de la vidéo et essaie de retenir les trois idées principales de l’interview. Son cerveau retient facilement le visage de l’habitante, mais moins bien l’ordre exact des informations. Au lieu de relire immédiatement toutes ses notes, elle observe l’image, ferme les yeux quelques secondes et essaie de respirer calmement. Ensuite, elle résume de mémoire ce qu’elle veut retenir. Elle compare ce résumé avec ses notes et corrige un détail. Camille comprend qu’une image peut aider la mémoire parce qu’elle rappelle le contexte, mais qu’elle ne contient pas toutes les réponses. Pour retenir une information précise, elle doit encore vérifier les mots importants. Son cerveau fonctionne mieux quand elle alterne rappel et vérification au lieu de relire sans arrêt. Respirer lui donne simplement un moment pour se concentrer avant de reconstruire l’information à partir de l’image.""","grammar":[{"id":"fr-a2-u10-pour-retenir","role":"new","description":"use pour + infinitive to state a memory goal"}],"discourse":[{"id":"fr-a2-u10-recall-verify","role":"new","description":"combine visual recall with note verification instead of passive rereading"}],"items":[("gist","Comment Camille essaie-t-elle de retenir l’interview ?","Elle utilise une image pour rappeler le contexte puis vérifie son résumé avec ses notes.",["retenir","image"]),("literal_detail","Qu’est-ce que son cerveau retient facilement ?","Le visage de l’habitante.",["cerveau","retenir"]),("sequence","Que fait-elle après avoir résumé de mémoire ?","Elle compare son résumé avec ses notes.",[]),("cause_effect","Pourquoi l’image ne suffit-elle pas à elle seule ?","Parce qu’elle rappelle le contexte mais ne contient pas toutes les informations précises.",["image"]),("vocabulary_in_context","Que signifie « retenir » ici ?","Garder une information en mémoire.",["retenir"]),("vocabulary_in_context","Que désigne « image » ?","Une représentation visuelle extraite de la vidéo.",["image"]),("reference_resolution","Dans « elle compare », qui est « elle » ?","Camille.",[]),("inference","Quel rôle joue le fait de respirer ?","Il lui donne un court moment pour se concentrer avant de rappeler l’information.",["respirer"]),("cloze_transfer","Complète : Je veux _____ cette information importante.","retenir",["retenir"]),("cloze_transfer","Complète : Cette _____ me rappelle la scène.","image",["image"])]},
{"id":"fr-a2-u10-p05","sequence":59,"ptype":"integration","title":"Proposer une idée et gérer le temps","genre":"presentation planning narrative","domains":["educational","personal"],"topics":["proposal","time management","shared roles"],"forms":["proposer","gérer"],"reviews":["chacun","pourtant"],"text":"""Pour terminer le projet, la classe doit proposer une façon de présenter son travail aux autres groupes. Chacun écrit une idée sur une fiche. Camille veut montrer la vidéo, Sami préfère une courte discussion, et une autre élève propose d’afficher quelques images. Pourtant, le temps disponible ne permet pas de tout faire. La responsable demande alors comment gérer les quinze minutes de présentation. Camille propose de commencer par la vidéo, puis de garder cinq minutes pour les questions. Sami accepte, à condition que chacun puisse répondre au moins une fois. Le groupe doit aussi gérer l’installation de la caméra et des chaises avant l’arrivée du public. Pourtant, personne n’a besoin de tout contrôler seul. Chacun prend une tâche précise et vérifie son matériel. Camille comprend que proposer une bonne idée est utile, mais savoir gérer le temps, les rôles et les limites transforme cette idée en plan réalisable.""","grammar":[{"id":"fr-a2-u10-proposer-de","role":"new","description":"use proposer de + infinitive to suggest a practical action"}],"discourse":[{"id":"fr-a2-u10-proposal-to-plan","role":"new","description":"turn several proposals into one time-bounded shared plan"}],"items":[("gist","Comment le groupe construit-il son plan final ?","Chacun propose une idée puis le groupe choisit comment gérer le temps et les rôles.",["proposer","gérer","chacun"]),("literal_detail","Combien de temps la présentation dure-t-elle ?","Quinze minutes.",[]),("sequence","Que propose Camille après la question de la responsable ?","De commencer par la vidéo puis de garder cinq minutes pour les questions.",["proposer"]),("cause_effect","Pourquoi le groupe ne fait-il pas toutes les activités proposées ?","Parce que le temps disponible est limité.",[]),("vocabulary_in_context","Que signifie « proposer » ici ?","Présenter une idée ou une action à considérer.",["proposer"]),("vocabulary_in_context","Que signifie « gérer » le temps ?","Organiser et utiliser le temps disponible de façon adaptée.",["gérer"]),("reference_resolution","Dans « personne n’a besoin », à quel groupe renvoie l’idée ?","Aux membres de la classe.",[]),("inference","Pourquoi chacun reçoit-il une tâche précise ?","Pour répartir la préparation et éviter qu’une seule personne doive tout gérer.",["chacun","gérer"]),("cloze_transfer","Complète : Je vais _____ une autre solution.","proposer",["proposer"]),("cloze_transfer","Complète : Il faut _____ notre temps avec soin.","gérer",["gérer"])]}
]
CHECKPOINT={"id":"fr-a2-u10-p06","sequence":60,"ptype":"checkpoint","title":"Fin du parcours A2","genre":"A2 cumulative capstone summary","domains":["educational","public","personal"],"topics":["capstone","planning","adaptation"],"text":"""À la fin du niveau A2, Camille sait mieux organiser une petite tâche du début à la fin. Elle peut interroger une personne sur l’endroit où elle vient habiter et sur le milieu qui l’entoure. Dans une salle, elle observe comment une cuisine, une fenêtre et différents appareils influencent l’activité. Pour présenter un projet, elle peut préparer une vidéo avec une caméra, puis choisir une image utile pour résumer une idée. Elle apprend aussi à retenir les informations importantes en combinant mémoire et vérification. Quand plusieurs options existent, elle peut proposer une solution et gérer le temps ou les rôles sans décider seule. Les unités précédentes lui ont aussi appris à accepter une excuse ou une surprise, vérifier un bruit, éviter de rater un départ, respirer quand son cerveau s’agite et laisser chacun participer même si les avis diffèrent. Camille n’a pas besoin d’une situation parfaite : elle observe, demande, vérifie, s’adapte et termine ce qu’elle a commencé.""","grammar":[{"id":"fr-a2-u10-capstone-summary","role":"integration","description":"integrate infinitives, location phrases and planning language in an A2 capstone"}],"discourse":[{"id":"fr-a2-u10-complete-small-task","role":"integration","description":"summarize planning, environment awareness, media work, memory and shared management"}],"items":[("gist","Quelle compétence générale Camille a-t-elle développée ?","Elle sait mieux organiser et adapter une petite tâche du début à la fin.",[]),("literal_detail","Sur quoi peut-elle interroger une personne ?","Sur l’endroit où elle vient habiter et sur son milieu.",["habiter","milieu"]),("sequence","Que peut-elle utiliser pour présenter le projet ?","Une vidéo, une caméra et une image utile.",["vidéo","caméra","image"]),("cause_effect","Pourquoi combine-t-elle mémoire et vérification ?","Pour mieux retenir les informations importantes.",["retenir"]),("vocabulary_in_context","Quels mots désignent deux parties d’une salle ?","cuisine et fenêtre",["cuisine","fenêtre"]),("vocabulary_in_context","Quels mots décrivent suggérer une solution et organiser les ressources ?","proposer et gérer",["proposer","gérer"]),("reference_resolution","Dans « elle observe », qui est « elle » ?","Camille.",[]),("inference","Pourquoi n’a-t-elle pas besoin d’une situation parfaite ?","Parce qu’elle sait observer, vérifier et adapter son action quand les conditions changent.",[]),("cloze_transfer","Complète : Je veux _____ cette idée importante.","retenir",["retenir"]),("summary","Résume le capstone A2 en une phrase.","Camille sait comprendre son milieu, utiliser des outils simples, retenir l’essentiel, proposer des solutions et gérer une tâche avec les autres.",["milieu","retenir","proposer","gérer"])]}
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids); text=s['text']
 return {'id':s['id'],'language':'fr','cefr':'A2','unit':10,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'Generation-stage French A2 Unit 10; final language-wide audit deferred.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French A2 Unit 10 generation batch.','A1+A2 freshness, source identity, A2 word band, exact review visibility, local target linkage, continuity and zero-new checkpoint are enforced.']},'paired_text_group':None,'prerequisites':['French A2 Units 01-09 canonical corpus'],'difficulty_notes_internal':'A2 capstone project integrating practical planning with Unit 09 recovery vocabulary as explicit review.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_a2_u10']}
def build(a1,a2,D):
 P=base.prior(a1+a2); bad=[]
 for f in FORMS:
  if f not in D: bad.append(f+':missing_lexicon')
  if P.get(f): bad.append(f+':already_deliberate')
 if bad: raise AssertionError('Unit10 candidate failures: '+', '.join(bad))
 out=[]
 for s in SPECS:
  new=[base.nt(f,s['text'],D) for f in s['forms']]; reviews=[base.rev(f,P) for f in s['reviews']]; ids={t['form']:t['id'] for t in new+reviews}; out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,D) for f in FORMS]; ids={t['form']:t['id'] for t in reviews}; out.append(mk(CHECKPOINT,[],reviews,ids,True)); return out
def main():
 a1_blob=subprocess.check_output(['git','hash-object',str(A1)],text=True).strip(); blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if a1_blob!=EXPECTED_A1_BLOB: raise AssertionError(f'A1 blob drift: {a1_blob} != {EXPECTED_A1_BLOB}')
 if blob!=EXPECTED_BLOB: raise AssertionError(f'A2 blob drift: {blob} != {EXPECTED_BLOB}')
 a1=[json.loads(x) for x in A1.read_text(encoding='utf-8').splitlines() if x.strip()]; a2=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(a1)!=60 or a1[-1]['id']!='fr-a1-u10-p06': raise AssertionError('unexpected A1 prerequisite state')
 if len(a2)!=54 or [r['sequence'] for r in a2]!=list(range(1,55)) or a2[-1]['id']!='fr-a2-u09-p06': raise AssertionError('expected exact A2 frontier through Unit09')
 D=base.deck(); unit=build(a1,a2,D); V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8'))); old={t['id'] for r in a1+a2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict) and t.get('id')}
 if [r['sequence'] for r in unit]!=list(range(55,61)) or [r['id'] for r in unit]!=[f'fr-a2-u10-p{i:02d}' for i in range(1,7)]: raise AssertionError('Unit10 continuity failure')
 newids=[]
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs: raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:6]]}")
  if not 140<=r['word_count']<=220: raise AssertionError(f"{r['id']}: A2 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10: raise AssertionError(f"{r['id']}: assessment count")
  amap={a['question_id']:a['id'] for a in r['answer_key']}; decl={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])): raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   s=D.get(t['form'])
   if t['id'] in old or not s or t['source_rank']!=s['rank'] or t['id']!=base.tid(s['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']: raise AssertionError(f"{r['id']}: source/exposure/reintroduction drift {t}")
   newids.append(t['id'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1: raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=10 or len(set(newids))!=10 or unit[-1]['new_lexical_targets']!=[]: raise AssertionError('Unit10 lexical-cycle invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in a2+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','level':'A2','unit':10,'appended_passages':6,'a2_passages':60,'word_counts':{r['id']:r['word_count'] for r in unit},'new_targets':[{'form':f,'rank':D[f]['rank'],'id':base.tid(D[f]['rank'])} for f in FORMS],'questions':60,'answers':60,'p06_new_targets':0},ensure_ascii=False))
if __name__=='__main__': main()
