#!/usr/bin/env python3
"""Generate Arabic C2 Unit 10 capstone: six zero-new-target transfer passages."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'reading/arabic/c2/passages.jsonl'
P=[
('p01','حين تتغير القاعدة بتغير السؤال','instructional','multi-source-style synthesis','اجتمعت لجنة خيالية لدراسة نظام يقرر من يحصل على مساحة تجريبية محدودة. قال تقرير أول إن القاعدة عادلة لأنها تطبق الشرط نفسه على الجميع. وقال تقرير ثان إن الشرط نفسه يعتمد على بيانات لا تستطيع بعض الفرق جمعها إلا بعد دخول المساحة أصلًا. اقترح عضو حلًا تقنيًا يحسب احتمال النجاح، لكن الباحثة سألت: نجاح وفق أي معيار، وعلى أي عينة، ومن يتحمل الخطأ إذا حرم النظام مشروعًا كان يمكن أن ينجح؟ ثم لاحظ المحامي أن القاعدة المكتوبة لم تحدد هل هدفها مكافأة الأداء الماضي أم زيادة فرصة اكتشاف أفكار جديدة. تغير الخلاف عندما صيغت الغاية صراحة؛ فإذا كان الهدف الأول، يصبح السجل السابق دليلًا أقوى، وإذا كان الثاني فقد نحتاج إلى قبول قدر من عدم اليقين. لا يحسم المبدأ المجرد التطبيق قبل تحديد الغرض والقياس والآثار. الحجة المتقدمة تعيد بناء هذه الطبقات بدل أن تختار كلمة مثل «العدالة» وتفترض أن معناها التشغيلي واضح.'),
('p02','النموذج الذي يقنع لأنه منظم','reinforcement','complex paired text','عرض فريقان نموذجين لمستقبل خدمة خيالية. النموذج الأول بسيط، يربط ثلاثة عوامل ويشرح كل انتقال. والثاني أدق تاريخيًا ويحتوي عشرات المتغيرات، لكنه يصعب تفسير سبب تغير مخرجه. فضل المدير الثاني لأنه «أكثر علمية». اعترضت المحللة: زيادة التفاصيل قد تحسن التنبؤ، وقد تخفي أيضًا هشاشة لا يراها المستخدم. قارنت القرارين تحت خطأين مختلفين. إذا أخطأ النموذج البسيط يمكن للفريق معرفة الفرضية التي انهارت بسرعة. وإذا أخطأ المعقد قد يكون أدق في المتوسط لكنه أبطأ في التشخيص. لا يعني ذلك أن البساطة فضيلة مطلقة؛ أحيانًا يحذف النموذج البسيط تفاعلًا جوهريًا. لذلك يجب فصل سؤالين: أي نموذج يتنبأ أفضل ضمن البيانات المتاحة، وأي نموذج يسمح للمؤسسة بفهم الخطأ والتصرف حين يتغير العالم؟ اختيار النموذج جزء من تصميم القرار، لا مسابقة جمال رياضي.'),
('p03','العبارة التي تغير معناها بين مؤسستين','interleaved','paired perspectives','في اتفاق خيالي بين مؤسستين وردت عبارة «استجابة سريعة». في الأولى تعني أن يرسل الموظف تأكيدًا خلال ساعة، وفي الثانية تعني أن تبدأ المعالجة الفعلية خلال يوم. بعد أول حادثة اعتقد كل طرف أن الآخر خالف الاتفاق. عاد المترجم والمستشار المؤسسي إلى المفاوضات القديمة، فوجدوا أن كل فريق كان يستخدم العبارة وفق عاداته الداخلية من دون تعريف مشترك. اقترح أحدهم ترجمة المصطلح إلى أرقام فقط. حذرت الباحثة من أن الرقم يحل غموض الزمن لكنه لا يحل غموض الفعل: هل المطلوب تأكيد الاستلام أم بدء العمل أم إنهاؤه؟ هنا يلتقي تفسير اللغة بتصميم المؤسسة. الكلمة لا تعيش خارج الإجراء، والإجراء قد يحمل افتراضًا ثقافيًا عن المسؤولية والتوقع. الحل الأقوى لم يكن اختيار أي استعمال «أصح»، بل تفكيك العبارة إلى حدث ومدة ونقطة بدء واستثناءات، ثم اختبار هل الصياغة الجديدة تنتج السلوك الذي قصده الطرفان.'),
('p04','الماضي الذي يدخل القرار المستقبلي','transfer','integrated analysis','أرادت مدينة خيالية استخدام سجل تاريخي لتصميم نظام إنذار جديد. أظهر السجل أن حيًا معينًا سجل حوادث أقل، فاقترح الفريق تخصيص موارد أقل له مستقبلًا. سألت المؤرخة كيف جُمعت السجلات القديمة. اتضح أن مركز البلاغات كان بعيدًا عن الحي وأن بعض السنوات مفقودة. قال المهندس إن النموذج يستطيع تعويض النقص إحصائيًا. ردت المؤرخة بأن التعويض يحتاج فرضية عن سبب الغياب؛ إذا كان الغياب عشوائيًا يختلف الأمر عن كون الوصول إلى التسجيل نفسه أصعب. أضافت خبيرة الأخلاق أن القرار الجديد قد يعيد إنتاج نمط التسجيل القديم: موارد أقل تؤدي إلى بلاغات أقل فتبدو الفرضية صحيحة. صار الماضي جزءًا من آلية المستقبل، لا مجرد بيانات عنه. لذلك احتاج الفريق إلى تجربة قابلة للرجوع، وقياس مستقل عن البلاغات، ومراجعة تكشف ما إذا كان القرار يغير المؤشر الذي يستخدمه لتبرير نفسه.'),
('p05','الحجة التي تربح المناظرة وتخسر المسألة','integration','rhetorical-argument synthesis','في مناظرة خيالية حول مشروع عام قدم المتحدث الأول قصة قوية عن شخص استفاد من المشروع، ورد الثاني برقم متوسط يوحي بأن الفائدة محدودة. بدا أن الطرفين يتناقضان، لكن المحررة أعادت بناء الحجة. القصة تثبت إمكان نوع من الفائدة ولا تحدد انتشارها. والمتوسط يصف مجموعة لكنه قد يخفي فئات تربح كثيرًا وأخرى لا تربح. كما أن اختيار قصة مؤثرة أو رقم واحد قرار بلاغي يوجه الانتباه قبل أن يكون تزويرًا. طلبت المحررة ثلاثة أسئلة: ما الادعاء الذي يستطيع كل دليل دعمه فعلًا؟ ما المعلومات التي استبعدت من العرض؟ وهل يتغير الحكم إذا فصلنا حجم الأثر عن توزيعه؟ بعد ذلك لم تعد المسألة «القصة ضد الأرقام». صارت مقارنة بين وظائف الأدلة وحدودها. المتحدث المقنع قد يفوز بالانتباه، لكن الحجة الأقوى هي التي تظل قابلة للفحص عندما نعيد ترتيب العرض ونضيف الأدلة التي لا تخدمها بسهولة.'),
('p06','C2: إعادة بناء الحجة قبل الحكم عليها','fluency','final checkpoint','تجمع القراءة في المستوى الأعلى مهارات تبدو منفصلة لكنها تعمل معًا. المفهوم الفلسفي يحتاج إلى حدود وحالات مضادة، والقاعدة القانونية تحتاج إلى غرض وسياق وتفسير منافس. النموذج العلمي أو الاقتصادي يحتاج إلى معرفة ما الذي يبسطه وما الذي يفشل عند تغير الظروف. والأسلوب البلاغي قد يغير ما يراه القارئ سببًا أو شرطًا حتى إذا لم تتغير الوقائع الصريحة. المؤسسة توزع القرار بين قواعد وموارد وحوافز، والترجمة تنقل وظيفة بين لغات وجماهير ووسائط، والتاريخ يصل عبر مصادر لها تاريخ إنتاج وبقاء. أما التقنية المستقبلية فتضيف سؤال القابلية للرجوع ومن يتحمل الخطأ تحت عدم اليقين. لا تعني هذه التعقيدات أن كل جواب متساوٍ أو أن الحكم مستحيل. العكس: كلما زادت الطبقات، ازدادت الحاجة إلى حجة يمكن تفكيكها. القارئ القوي يحدد الادعاء، يعيد بناء مقدماته، يختبر البدائل، يبحث عن الدليل المضاد، ويفصل ما نعرفه عما نفترضه ثم يبين لماذا يظل حكمه أفضل من المنافسين مع الاعتراف بما لم يحسم.')]
GENRES={'instructional':'multi-source-style synthesis','reinforcement':'complex paired texts','interleaved':'paired perspectives','transfer':'integrated analysis','integration':'argument synthesis','fluency':'final checkpoint'}
def qa(i):
 base=[('gist','ما الفكرة المركزية؟','أن الحكم المتقدم يتطلب إعادة بناء الادعاء ومقدماته وآلياته وحدود الأدلة قبل تقييمه.'),('literal_detail','ما نوعان من الأدلة أو الطبقات اللذان يقارنهما النص؟','يقارن بين مصادر أو قواعد أو نماذج أو آليات مختلفة بحسب passage.'),('inference','لماذا لا يكفي وصف واحد مثل عادل أو دقيق أو مقنع؟','لأن الوصف لا يحدد معيار التطبيق ولا الآلية ولا توزيع الخطأ.'),('argument_relation','ما وظيفة التفسير المنافس؟','اختبار ما إذا كان الدليل يميز الحجة المفضلة عن بديل معقول.'),('main_claim','ما الذي يجعل الحكم أقوى؟','إعلان معاييره وربطه بأدلة تواجه البدائل والآثار غير المرئية.'),('contrast','ما الفرق بين وجود معلومة ووظيفتها في الحجة؟','المعلومة قد تكون صحيحة، لكن قوتها تعتمد على الادعاء الذي تستخدم لدعمه.'),('inference','لماذا تهم قابلية المراجعة؟','لأنها تسمح بكشف الخطأ وتصحيح القرار بدل تثبيته رغم تغير الأدلة.'),('summary','ما المهارة المشتركة بين مجالات النص؟','إعادة بناء العلاقة بين الادعاء والدليل والآلية والبدائل.'),('inference','كيف يتعامل القارئ مع عدم الحسم؟','يحدد ما بقي مجهولًا من دون مساواة كل التفسيرات.'),('inference','ما معيار النجاح في هذا المستوى؟','تفسير أدق وأوسع للأدلة مع افتراضات معلنة وقدرة على مواجهة الاعتراضات.')]
 q=[];a=[]
 for j,(typ,p,x) in enumerate(base,1):q.append({'id':f'q{j}','type':typ,'prompt':p,'answer_id':f'a{j}','target_ids':[]});a.append({'id':f'a{j}','question_id':f'q{j}','answer':x,'explanation':''})
 return q,a
def build(i,p):
 pid,title,role,genre,text=p;q,a=qa(i)
 return {'id':f'ar-c2-u10-{pid}','language':'ar','cefr':'C2','unit':10,'sequence':48+i,'revision':1,'title':title,'text':text,'passage_type':role,'genre':genre,'domains':['C2 synthesis'],'topics':['argument reconstruction','cross-domain transfer'],'new_lexical_targets':[],'review_lexical_targets':[],'grammar_targets':[{'id':f'ar-c2-u10-{pid}-g','role':'integration','description':'إعادة بناء العلاقات بين الادعاء والمقدمات والآليات والبدائل والقيود'}],'discourse_targets':[{'id':f'c2-u10-{pid}-d','role':'integration','description':'cross-domain C2 argument reconstruction with explicit uncertainty and counterevidence'}],'questions':q,'answer_key':a,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!؟](?:\s|$)',text))),'estimated_known_token_coverage':0,'paired_text_group':None,'prerequisites':['Arabic A1-C1 generation corpus','Arabic C2 Units 01-09 generation corpus'],'difficulty_notes_internal':'C2 Unit 10 zero-new-target capstone generation draft.','speed_training':{'timed':role=='fluency','benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'none','notes':'Zero deliberate new lexical targets throughout C2 capstone; formal audit deferred.'},'quality':{'status':'draft','linguistic_review':'pending','pedagogical_review':'pending','coverage_check':'pending','answer_key_check':'pending','schema_check':'pending','fact_check':'not_required','notes':['All cases are fictional or abstract curriculum material; zero new deliberate lexical targets; formal audit battery deferred.']},'reader_tags':['unit_role:'+role,'generation_batch','c2','zero_new_targets'],'complexity_profile':{'mean_sentence_length':None,'median_sentence_length':None,'clause_count':None,'subordination_count':None,'coordination_count':None,'connective_diversity':None,'lexical_diversity':None,'reference_chain_max_distance':None,'multiword_expression_count':None,'morphology_notes':'C2 cross-domain synthesis MSA.','inference_depth':'cross_paragraph_argument_reconstruction'}}
def main():
 rows=[json.loads(l) for l in OUT.read_text(encoding='utf-8').splitlines() if l.strip()] if OUT.exists() else [];rows=[r for r in rows if not(r.get('cefr')=='C2' and r.get('unit')==10)];rows.extend(build(i,p) for i,p in enumerate(P,1));rows.sort(key=lambda r:r.get('sequence',0));OUT.write_text('\n'.join(json.dumps(r,ensure_ascii=False,sort_keys=True) for r in rows)+'\n',encoding='utf-8');print(f'wrote C2 Unit 10 zero-new-target capstone; total C2 rows={len(rows)}')
if __name__=='__main__':main()
