#!/usr/bin/env python3
"""Append French B2 Unit06 (seq31-36): digital life and privacy."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
R=Path(__file__).resolve().parents[2];A1=R/'reading/french/a1/passages.jsonl';A2=R/'reading/french/a2/passages.jsonl';B1=R/'reading/french/b1/passages.jsonl';CANON=R/'reading/french/b2/passages.jsonl';SCHEMA=R/'reading/schema/passage.schema.json';LOCK=R/'reading/audit/french_b2_unit05_frontier_lock.json';PROBE=R/'reading/audit/french_b2_unit06_target_probe.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca','B2':'bada023bdbbe9830ec324ed5924862d5b153e214'}
FORMS=('téléphone','compte','message','adresse','photo','nom','visage','voix','contrôler','suivre','connaître','cacher','client','bureau','demander','répondre','vendre','chercher','trouver','monde')
PAIR='fr-b2-u06-data-control-opinions'
SPECS=[
{'id':'fr-b2-u06-p01','sequence':31,'ptype':'instructional','title':'Récupérer un compte sans transformer chaque preuve en archive permanente','genre':'analysis','domains':['public','professional'],'topics':['digital life and privacy','account recovery','data minimization'],'forms':['téléphone','compte','message','adresse'],'reviews':['été','année','mois','nuit'],'pair':None,'paragraphs':[
"Un service fictif veut améliorer la récupération d’un compte lorsqu’une personne oublie son mot de passe. La procédure actuelle demande un numéro de téléphone, une adresse électronique et parfois un ancien message envoyé depuis le service. Ces éléments peuvent aider à distinguer le titulaire d’un inconnu, mais le rapport pose une question plus large : faut-il conserver chaque preuve aussi longtemps que le compte existe ? Une information utile au moment de la vérification peut devenir un risque inutile si elle reste stockée sans objectif précis. Le texte propose donc de séparer la preuve nécessaire aujourd’hui de l’archive qui serait gardée par simple habitude.",
"Le service compare plusieurs durées. Un code envoyé au téléphone peut disparaître après quelques minutes; un historique d’adresse peut être gardé pendant un mois; certaines informations administratives peuvent être réévaluées chaque année. Une expérience menée pendant un été fictif montre aussi que les demandes reçues la nuit présentent parfois un autre profil d’assistance, mais cela ne justifie pas de conserver davantage de données sur tous les utilisateurs. La durée doit dépendre de la fonction de l’information, pas du fait qu’il est techniquement facile de la garder.",
"Une objection apparaît : supprimer trop vite les preuves pourrait rendre une récupération future plus difficile. Le rapport répond qu’il faut distinguer les couches. Le service peut garder un signal minimal indiquant qu’une adresse a déjà été vérifiée sans conserver le contenu complet de chaque message. Il peut aussi demander une nouvelle preuve lorsque le risque est élevé. Cette solution n’élimine pas tout coût : elle peut obliger certaines personnes à refaire une étape. Mais elle réduit la quantité d’informations disponibles si le système est mal utilisé plus tard.",
"La recommandation finale associe donc chaque donnée à une durée et à une raison. Le téléphone sert à recevoir un code; l’adresse sert à établir un canal; le message sert seulement dans certains cas; le compte réunit ces choix sans exiger que chaque preuve reste visible pour toujours. Le texte défend une règle de proportion : plus une information est sensible ou facile à détourner, plus sa conservation doit être justifiée. Une année, un mois, un été ou même une nuit ne deviennent pas des durées automatiques; ce sont des fenêtres à expliquer et à réviser."
],
'grammar':[{'id':'fr-b2-u06-retention-duration','role':'new','description':'connect purpose and retention duration using pendant, après, chaque and conditional necessity'}],
'discourse':[{'id':'fr-b2-u06-minimization-analysis','role':'new','description':'separate verification purpose, retention duration, future utility and privacy cost'}],
'items':[
('main_claim','Quelle règle de conservation le texte défend-il ?','Conserver chaque preuve seulement aussi longtemps que sa fonction le justifie, plutôt que pendant toute la vie du compte.',['compte','adresse']),
('literal_detail','Quels canaux peuvent servir à la récupération ?','Le téléphone, l’adresse électronique et, dans certains cas, un ancien message.',['téléphone','adresse','message']),
('argument_relation','Pourquoi le rapport distingue-t-il preuve et archive ?','Parce qu’une information utile pour vérifier une personne maintenant peut devenir inutilement risquée si elle est gardée ensuite.',['message','compte']),
('vocabulary_in_context','Que signifie « compte » ici ?','L’espace ou l’accès associé à un utilisateur dans le service fictif.',['compte']),
('vocabulary_in_context','Quel rôle joue « adresse » ?','Elle sert de canal de contact et de signal possible de vérification.',['adresse']),
('assumption','Quelle hypothèse soutient la suppression progressive ?','Que certaines preuves complètes n’apportent plus assez de valeur après la vérification pour justifier leur conservation.',['message']),
('inference','Pourquoi l’observation des demandes la nuit ne justifie-t-elle pas une conservation générale ?','Parce qu’une différence de contexte horaire n’établit pas que davantage de données sont nécessaires pour tous.',['nuit']),
('reference_resolution','Dans « elle peut obliger certaines personnes », à quoi renvoie « elle » ?','À la solution qui conserve moins de preuves et peut demander une nouvelle vérification.',['compte']),
('stance','Quelle position le texte adopte-t-il envers des durées fixes pour tous les types de données ?','Il les refuse et préfère une durée liée à la fonction et au risque de chaque information.',['année','mois']),
('summary','Résume la politique proposée.','Pour récupérer un compte, le service peut utiliser téléphone, adresse et message, mais il doit justifier ce qui reste après une nuit, un mois, un été ou une année au lieu de tout garder automatiquement.',['téléphone','compte','message','adresse','nuit','mois','été','année'])]},
{'id':'fr-b2-u06-p02','sequence':32,'ptype':'reinforcement','title':'Une photo porte un nom, un visage et parfois une voix : lesquels faut-il publier ?','genre':'policy-style summary','domains':['public','educational'],'topics':['digital life and privacy','media publication','identity exposure'],'forms':['photo','nom','visage','voix'],'reviews':['passé','long','changer','continuer'],'pair':None,'paragraphs':[
"Une association fictive prépare un site retraçant son passé. Elle possède des centaines d’images d’événements, ainsi que quelques enregistrements audio. Le premier projet prévoit de publier chaque photo avec le nom des personnes reconnues. Un groupe de membres demande une règle plus précise. Un visage visible dans une foule n’a pas nécessairement besoin d’être accompagné d’un nom complet, et une voix enregistrée lors d’une réunion peut révéler davantage de contexte qu’une simple image. La politique doit donc distinguer ce qui sert réellement l’histoire collective de ce qui expose inutilement une personne.",
"Le comité propose trois catégories. Les documents déjà destinés à une publication officielle peuvent continuer à être accessibles, sauf raison nouvelle de les modifier. Les archives internes passent par une vérification avant publication. Enfin, les contenus particulièrement personnels restent fermés par défaut. Le fait qu’une photo soit ancienne ne suffit pas à conclure que toute sensibilité appartient au passé. Une personne peut changer de situation, de nom ou de préférence; un effet peut aussi continuer longtemps après l’événement original.",
"Une difficulté concerne les légendes. Sans nom, certaines photos perdent une partie de leur valeur historique. Avec trop de détails, elles peuvent rendre un visage facilement identifiable dans un contexte que la personne n’avait jamais prévu de rendre public. Le comité autorise donc plusieurs niveaux : nom complet lorsque le rôle public est pertinent et documenté, prénom ou description générale lorsque l’identification apporte peu, et absence d’identification lorsque la publication pourrait créer un dommage disproportionné. Pour la voix, la même logique s’applique, mais le comité écoute aussi ce qui est dit avant de publier l’enregistrement.",
"La politique insiste enfin sur la possibilité de correction. Une archive est un projet long, mais sa durée ne doit pas empêcher de changer une légende, retirer une photo ou limiter un enregistrement lorsque de nouvelles raisons apparaissent. Le texte refuse deux raccourcis : croire que tout document du passé est automatiquement libre d’usage, ou supposer qu’aucune mémoire collective ne peut être publiée. Le compromis consiste à continuer l’archive en expliquant pourquoi un nom, un visage ou une voix est nécessaire dans chaque cas et comment une personne peut demander une révision."
],
'grammar':[{'id':'fr-b2-u06-identity-publication','role':'new','description':'qualify publication choices with lorsque, sauf, par défaut and purpose-based identification'}],
'discourse':[{'id':'fr-b2-u06-archive-privacy-policy','role':'new','description':'classify materials by publication purpose, identification value, sensitivity and revisability'}],
'items':[
('main_claim','Quel principe guide la politique de publication ?','Publier seulement le niveau d’identification nécessaire à la valeur du document et permettre des corrections ultérieures.',['photo','nom','visage','voix']),
('literal_detail','Quelles trois grandes catégories de documents sont prévues ?','Les contenus déjà publics, les archives internes à vérifier et les contenus personnels fermés par défaut.',['photo']),
('argument_relation','Pourquoi une photo ancienne n’est-elle pas automatiquement libre à publier ?','Parce que le passage du temps ne supprime pas nécessairement les effets actuels d’une identification.',['photo','passé']),
('vocabulary_in_context','Que signifie « visage » dans le problème de publication ?','L’apparence identifiable d’une personne visible sur une image.',['visage']),
('vocabulary_in_context','Pourquoi la « voix » reçoit-elle un examen particulier ?','Parce qu’un enregistrement peut identifier une personne et révéler aussi le contenu de ce qu’elle a dit.',['voix']),
('assumption','Quelle hypothèse justifie plusieurs niveaux de légende ?','Que la valeur d’un nom complet varie selon le rôle de la personne et le contexte du document.',['nom']),
('inference','Pourquoi le comité veut-il pouvoir changer les légendes plus tard ?','Parce que le contexte, les préférences ou les risques peuvent évoluer pendant la longue vie de l’archive.',['changer','long']),
('reference_resolution','Dans « elles peuvent rendre un visage », à quoi renvoie « elles » ?','Aux légendes contenant trop de détails.',['visage']),
('stance','Quelle position le texte adopte-t-il envers la continuité de l’archive ?','Il veut continuer le projet mais avec une politique révisable plutôt qu’une publication irréversible.',['continuer']),
('summary','Résume la règle.','Même pour un document du passé, une archive longue doit pouvoir changer : chaque photo, nom, visage et voix n’est publié que si son utilité justifie l’identification, et le projet peut continuer avec des corrections.',['photo','nom','visage','voix','passé','long','changer','continuer'])]},
{'id':'fr-b2-u06-p03','sequence':33,'ptype':'interleaved','title':'Point de vue A : suivre certains usages peut améliorer un service si chacun peut contrôler la règle','genre':'paired viewpoint A','domains':['professional','public'],'topics':['digital life and privacy','tracking','service improvement'],'forms':['contrôler','suivre','connaître','cacher'],'reviews':['rester','devenir','compter','montrer'],'pair':PAIR,'paragraphs':[
"Dans un débat fictif, Lina défend un suivi limité des usages d’un service numérique. Selon elle, il peut être utile de suivre les étapes où les utilisateurs abandonnent une procédure afin de savoir ce qui fonctionne mal. Si beaucoup de personnes quittent la même page, l’équipe peut chercher pourquoi. Mais Lina pose une condition : les utilisateurs doivent pouvoir contrôler les catégories utilisées pour l’analyse et connaître ce qui est enregistré. Un système qui prétend améliorer le service tout en choisissant de cacher ses propres règles affaiblit la confiance qu’il cherche à construire.",
"Lina distingue aussi mesure et surveillance générale. Compter combien de fois une fonction échoue peut aider à montrer un problème sans conserver l’histoire complète de chaque personne. Les données détaillées peuvent rester locales ou disparaître après l’analyse. Le but n’est pas de devenir capable de reconstruire chaque trajet individuel, mais de comprendre les obstacles communs. Pour elle, suivre un événement précis est acceptable lorsque la finalité est étroite, la durée limitée et le résultat présenté sous une forme qui ne permet pas de reconnaître inutilement quelqu’un.",
"Elle répond ensuite à une objection : même un suivi limité peut grandir avec le temps. Une équipe peut vouloir ajouter une nouvelle mesure, puis une autre, jusqu’à connaître beaucoup plus que ce qui avait été annoncé. Lina accepte ce risque et propose un contrôle périodique. Toute nouvelle catégorie doit expliquer ce qu’elle cherche à montrer; une catégorie devenue inutile doit être retirée. Les utilisateurs doivent aussi pouvoir voir un résumé simple des pratiques et contrôler certains choix lorsque cela ne détruit pas la fonction essentielle du service.",
"Son opinion est donc favorable mais conditionnelle. Elle ne veut ni cacher le suivi ni interdire toute observation. Elle estime qu’un service peut suivre certains usages pour devenir meilleur, à condition de limiter ce qu’il garde, de compter ce qui sert vraiment à l’évaluation, de montrer les objectifs et de permettre aux personnes de connaître les règles. Pour Lina, contrôler le système signifie surtout rendre ses décisions vérifiables : on sait ce qui est mesuré, pourquoi cela doit rester, et à quel moment la pratique doit être revue."
],
'grammar':[{'id':'fr-b2-u06-tracking-condition','role':'new','description':'express conditional support for tracking with à condition de, lorsque and purpose limits'}],
'discourse':[{'id':'fr-b2-u06-view-a','role':'new','description':'argue for limited tracking while conceding expansion risk and requiring user-visible controls'}],
'items':[
('main_claim','Quelle est la position de Lina ?','Elle accepte un suivi limité pour améliorer le service si les objectifs, durées et contrôles sont visibles.',['suivre','contrôler']),
('literal_detail','Quel type de signal peut aider l’équipe ?','Le fait que beaucoup d’utilisateurs abandonnent la même étape ou qu’une fonction échoue souvent.',['compter','montrer']),
('argument_relation','Pourquoi Lina distingue-t-elle mesure et surveillance générale ?','Pour défendre l’analyse de problèmes communs sans reconstruire inutilement l’histoire complète de chaque personne.',['suivre','connaître']),
('vocabulary_in_context','Que signifie « contrôler » ici ?','Pouvoir vérifier ou régler certains choix du système plutôt que tout accepter sans information.',['contrôler']),
('vocabulary_in_context','Que signifie « cacher » dans son argument ?','Ne pas rendre visibles les règles ou catégories qui structurent le suivi.',['cacher']),
('assumption','Quelle hypothèse soutient l’usage de données agrégées ?','Qu’il est possible de montrer des problèmes collectifs sans conserver tous les détails individuels.',['montrer']),
('inference','Pourquoi une nouvelle catégorie doit-elle être justifiée ?','Pour empêcher que le suivi devienne progressivement beaucoup plus large que la finalité annoncée.',['devenir','suivre']),
('reference_resolution','Dans « cela ne détruit pas la fonction essentielle », que désigne « cela » ?','Le fait de donner aux utilisateurs certains contrôles sur les pratiques de suivi.',['contrôler']),
('stance','Quelle concession importante Lina fait-elle ?','Elle reconnaît qu’un suivi limité peut s’étendre avec le temps et demande donc un contrôle périodique.',['suivre']),
('summary','Résume le point de vue A.','Lina veut contrôler un suivi limité : suivre seulement ce qui aide le service, connaître et montrer les règles au lieu de les cacher, compter les signaux utiles, retirer ce qui ne doit plus rester et éviter de devenir capable de reconstruire toute la vie individuelle.',['contrôler','suivre','connaître','cacher','compter','montrer','rester','devenir'])]},
{'id':'fr-b2-u06-p04','sequence':34,'ptype':'transfer','title':'Point de vue B : un client ne devrait pas devoir deviner ce que le bureau mesure','genre':'paired viewpoint B','domains':['professional','public'],'topics':['digital life and privacy','tracking','transparency burden'],'forms':['client','bureau','demander','répondre'],'reviews':['croire','penser','sembler','comprendre'],'pair':PAIR,'paragraphs':[
"Dans le même débat, Marc est plus critique. Il accepte qu’un service mesure certains problèmes techniques, mais il pense que le poids de la transparence ne doit pas reposer sur le client. Une personne ne devrait pas devoir demander à chaque visite quelles informations sont observées ni parcourir un long document pour comprendre une pratique ordinaire. Si le bureau qui conçoit le service connaît ses propres mesures, c’est à lui de répondre clairement aux questions prévisibles avant même qu’elles soient posées. Pour Marc, une permission difficile à comprendre peut sembler volontaire tout en laissant la personne sans choix réel.",
"Il donne un exemple fictif. Un service indique seulement qu’il utilise des informations « pour améliorer l’expérience ». Un client peut croire que cela concerne des erreurs techniques, alors que le bureau mesure aussi le temps passé sur différentes offres. Marc ne dit pas que cette seconde mesure est toujours interdite. Il demande qu’elle soit décrite séparément, avec une raison, une durée et une possibilité de refus lorsque le service peut continuer sans elle. La formulation générale ne doit pas obliger l’utilisateur à deviner ce que l’entreprise veut réellement savoir.",
"Marc répond ensuite à Lina. Selon lui, permettre de contrôler certaines options après l’inscription est utile mais insuffisant si le réglage initial favorise toujours la collecte maximale. Il propose un principe plus exigeant : commencer par ce qui est nécessaire au service, puis demander explicitement avant d’ajouter une analyse secondaire. Le bureau doit aussi répondre à une question simple : qu’est-ce qui ne fonctionnerait plus si cette information n’était pas recueillie ? Si la réponse reste vague, la collecte devrait sembler moins justifiée, pas plus normale.",
"Son point de vue déplace donc la charge de preuve. Il ne demande pas au client de connaître toute la technique. Il demande au concepteur de penser comme une personne extérieure : que croirait-elle en lisant l’explication, que pourrait-elle comprendre sans aide, et à quoi doit-on répondre avant qu’un problème apparaisse ? Marc reconnaît que cette méthode peut réduire certaines données disponibles pour l’analyse. Il estime cependant qu’un service qui paraît plus transparent parce qu’il possède un grand document n’est pas nécessairement facile à comprendre. La transparence doit être utilisable au moment du choix."
],
'grammar':[{'id':'fr-b2-u06-transparency-burden','role':'new','description':'express who bears an obligation using devoir, demander, répondre and conditional necessity'}],
'discourse':[{'id':'fr-b2-u06-view-b','role':'new','description':'counter the pro-tracking view by shifting transparency burden from user to service provider'}],
'items':[
('main_claim','Quelle est la thèse de Marc ?','Le service doit expliquer et justifier ses mesures avant de faire porter au client la charge de découvrir ou régler la collecte.',['client','bureau']),
('literal_detail','Quelle question le bureau doit-il pouvoir répondre ?','Ce qui ne fonctionnerait plus si une information donnée n’était pas recueillie.',['bureau','répondre']),
('argument_relation','Pourquoi Marc critique-t-il une formule générale sur « améliorer l’expérience » ?','Parce qu’elle peut regrouper des usages différents et empêcher le client de comprendre ce qui est réellement mesuré.',['client','comprendre']),
('vocabulary_in_context','Que signifie « demander » dans le passage ?','Poser explicitement une question ou solliciter un accord avant un usage secondaire.',['demander']),
('vocabulary_in_context','Que signifie « répondre » ici ?','Fournir une explication claire à une question sur la nécessité ou la pratique de collecte.',['répondre']),
('assumption','Quelle hypothèse soutient le principe du réglage minimal ?','Que certains usages secondaires ne sont pas nécessaires au fonctionnement de base et peuvent donc faire l’objet d’un choix séparé.',['bureau']),
('inference','Pourquoi un long document ne suffit-il pas à assurer la transparence ?','Parce qu’un client peut ne pas comprendre une information difficile à trouver ou formulée trop généralement.',['client','comprendre']),
('reference_resolution','Dans « c’est à lui de répondre », à qui renvoie « lui » ?','Au bureau ou service qui connaît ses propres pratiques de mesure.',['bureau','répondre']),
('stance','Comment Marc répond-il au point de vue A ?','Il accepte certains contrôles mais pense qu’ils arrivent trop tard si la collecte maximale est le choix initial.',['penser','croire']),
('summary','Résume le point de vue B.','Marc pense qu’un client ne devrait pas devoir demander ce que le bureau mesure : le service doit répondre d’avance, expliquer ce qui peut sembler nécessaire, aider à comprendre plutôt qu’à croire une formule générale, et rendre le choix facile à utiliser.',['client','bureau','demander','répondre','penser','sembler','comprendre','croire'])]},
{'id':'fr-b2-u06-p05','sequence':35,'ptype':'integration','title':'Chercher un service, trouver une aide : quand une plateforme peut-elle vendre les traces laissées en chemin ?','genre':'policy-style analysis','domains':['public','professional'],'topics':['digital life and privacy','data markets','secondary use'],'forms':['vendre','chercher','trouver','monde'],'reviews':['préparer','action','mer','terre'],'pair':None,'paragraphs':[
"Une plateforme fictive aide les habitants à chercher des services locaux et à trouver des itinéraires. Son modèle économique envisage de vendre certaines statistiques à des entreprises. Le comité chargé de la politique de confidentialité refuse de traiter toutes les informations de la même manière. Une liste agrégée des recherches les plus fréquentes dans une grande zone n’expose pas nécessairement une personne, tandis qu’une série détaillée de lieux peut révéler des habitudes. Le fait qu’un service soit utilisé par beaucoup de monde ne transforme pas automatiquement chaque trace individuelle en donnée sans risque.",
"Le comité étudie un scénario concret. Pendant une campagne de préparation aux urgences, la plateforme affiche des informations sur la mer, la terre et les routes d’évacuation. Les habitants peuvent chercher un point d’aide ou trouver un trajet. Cette fonction sert à préparer une action utile; elle ne crée pas pour autant une permission générale de vendre les recherches individuelles à un annonceur. La politique distingue donc finalité principale, analyse interne et usage secondaire. Plus l’usage s’éloigne de la raison pour laquelle la personne a utilisé le service, plus une nouvelle justification devient nécessaire.",
"Une entreprise partenaire affirme qu’elle n’achètera que des statistiques. Le comité demande alors comment elles sont produites : combien de personnes faut-il regrouper, quelles zones sont trop petites, et que se passe-t-il si plusieurs tableaux peuvent être combinés ? Le but n’est pas d’interdire tout échange, mais d’éviter qu’un résultat présenté comme collectif permette de retrouver indirectement une personne ou un petit groupe. Le texte insiste aussi sur la possibilité de chercher une valeur commerciale sans cacher le coût de cette décision aux utilisateurs.",
"La règle finale autorise certaines statistiques suffisamment agrégées, interdit la vente de trajets individuels et exige une information séparée pour tout nouvel usage important. Elle demande aussi une révision périodique, car le monde des services et des méthodes d’analyse peut changer. Une pratique acceptable aujourd’hui peut devenir plus risquée si de nouvelles sources rendent quelqu’un plus facile à trouver. Le texte défend donc une politique de séparation : aider à chercher, trouver et préparer une action n’autorise pas automatiquement à vendre. La mer ou la terre peuvent être le sujet d’une recherche; elles ne changent pas le principe selon lequel la finalité initiale limite l’usage secondaire."
],
'grammar':[{'id':'fr-b2-u06-secondary-use','role':'new','description':'contrast primary and secondary purposes with vendre, chercher, trouver and plus...plus constructions'}],
'discourse':[{'id':'fr-b2-u06-secondary-use-policy','role':'new','description':'separate primary service, internal analysis, aggregation and commercial secondary use'}],
'items':[
('main_claim','Quel principe organise la politique de la plateforme ?','Un usage secondaire comme vendre des statistiques doit être justifié séparément lorsqu’il s’éloigne du but pour lequel la personne a utilisé le service.',['vendre']),
('literal_detail','Que peuvent faire les habitants pendant le scénario d’urgence ?','Chercher un point d’aide et trouver un trajet lié aux informations de préparation.',['chercher','trouver']),
('argument_relation','Pourquoi une fonction d’urgence ne crée-t-elle pas une permission générale de vendre les recherches ?','Parce que préparer une action utile et exploiter commercialement les traces sont des finalités différentes.',['vendre','préparer','action']),
('vocabulary_in_context','Que signifie « chercher » dans le service ?','Lancer une recherche afin d’identifier un lieu, un service ou une information.',['chercher']),
('vocabulary_in_context','Que signifie « trouver » ici ?','Obtenir le résultat recherché, comme un point d’aide ou un itinéraire.',['trouver']),
('assumption','Pourquoi l’agrégation peut-elle réduire certains risques ?','Parce qu’un groupe assez large peut rendre plus difficile l’association d’un résultat à une personne précise.',['monde']),
('inference','Pourquoi le comité examine-t-il la combinaison de plusieurs tableaux ?','Parce que des statistiques séparées peuvent parfois révéler davantage lorsqu’elles sont rapprochées.',['trouver']),
('reference_resolution','Dans « elles ne changent pas le principe », à quoi renvoie « elles » ?','À la mer et à la terre mentionnées comme sujets possibles de recherche.',['mer','terre']),
('stance','Quelle position le texte adopte-t-il envers la vente de données ?','Il autorise certains résultats agrégés mais refuse que la vente soit considérée comme une extension automatique du service initial.',['vendre']),
('summary','Résume la politique.','Dans un monde où une plateforme aide à chercher et trouver des services, elle peut préparer une action liée à la mer ou la terre sans acquérir pour autant le droit de vendre toutes les traces : chaque usage secondaire doit rester distinct et justifié.',['monde','chercher','trouver','vendre','préparer','action','mer','terre'])]}
]
CHECKPOINT={'id':'fr-b2-u06-p06','sequence':36,'ptype':'checkpoint','title':'Contrôle, transparence et finalité : une politique numérique se juge dans le parcours complet','genre':'B2 cumulative privacy checkpoint','domains':['public','professional','educational'],'topics':['digital life and privacy','synthesis','policy scope'],'pair':None,'paragraphs':[
"Les cinq textes montrent qu’une politique de confidentialité ne se résume pas à cacher ou publier une information. Pour un compte, un téléphone, une adresse ou un message peut servir à vérifier une personne sans devoir rester dans une archive permanente. Pour une photo, la question change : un nom, un visage ou une voix peut rendre quelqu’un identifiable même lorsque le document appartient au passé. La durée, la finalité et le niveau de détail doivent donc être examinés ensemble plutôt que traités comme des choix séparés.",
"Les deux opinions sur le suivi ajoutent le contrôle. Lina accepte de suivre certains usages si les personnes peuvent connaître les règles, contrôler des choix et voir ce que l’équipe cherche à montrer; elle refuse de cacher une expansion progressive. Marc répond qu’un client ne devrait pas devoir demander ce que le bureau sait déjà. Pour lui, le service doit répondre avant que l’utilisateur soit obligé de deviner. Les deux positions veulent une pratique compréhensible, mais elles placent différemment la charge de transparence et le moment du choix.",
"Le cas de la plateforme ajoute l’usage secondaire. Aider quelqu’un à chercher puis trouver un service ne donne pas automatiquement le droit de vendre les traces laissées. Le monde numérique relie facilement des sources qui étaient autrefois séparées; une politique doit donc demander si une nouvelle combinaison change le risque. Même lorsqu’une application sert à préparer une action autour de la mer ou de la terre, la finalité initiale continue à limiter ce qui peut être fait ensuite. Une donnée utile dans un contexte ne devient pas libre pour tous les autres.",
"La synthèse propose quatre questions. Que faut-il collecter pour que le service fonctionne ? Combien de temps l’information doit-elle rester ? Qui peut contrôler, demander une explication et obtenir une réponse ? Enfin, qu’est-ce qui se passe lorsque le service veut devenir plus ambitieux, connaître davantage, suivre plus longtemps ou vendre un résultat à un tiers ? Une politique robuste doit permettre de comprendre ces changements sans obliger la personne à croire une formule générale. Elle doit compter et montrer ce qui est nécessaire, expliquer ce qui peut sembler secondaire, continuer à réviser ses choix et rendre facile le fait de trouver la règle applicable."
],
'grammar':[{'id':'fr-b2-u06-privacy-synthesis','role':'review','description':'synthesize purpose, retention, identification, tracking, transparency and secondary-use conditions'}],
'discourse':[{'id':'fr-b2-u06-policy-synthesis','role':'review','description':'compare individual cases and paired opinions through control, burden of explanation and purpose limitation'}],
'items':[
('main_claim','Quelle méthode générale la synthèse propose-t-elle ?','Évaluer collecte, durée, identification, contrôle, transparence et usage secondaire selon la finalité du service.',['contrôler','compte']),
('argument_relation','Quel désaccord principal sépare Lina et Marc ?','Ils acceptent tous deux une certaine transparence, mais Lina met l’accent sur des contrôles visibles tandis que Marc veut que le service explique d’abord sans faire chercher le client.',['client','contrôler','chercher']),
('cross_text_synthesis','Quel lien unit récupération de compte et publication de photo ?','Dans les deux cas, une information peut être utile pour une fonction précise sans devoir être conservée ou exposée au maximum.',['compte','photo']),
('assumption','Pourquoi la finalité initiale limite-t-elle la vente ?','Parce que l’utilisation d’un service pour une tâche ne constitue pas automatiquement un accord à un usage commercial différent.',['vendre']),
('inference','Pourquoi la combinaison de sources augmente-t-elle parfois le risque ?','Parce que plusieurs éléments séparés peuvent ensemble permettre de connaître ou trouver plus facilement une personne.',['connaître','trouver']),
('reference_resolution','Dans « elles placent différemment la charge », à quoi renvoie « elles » ?','Aux deux positions de Lina et Marc.',['demander','répondre']),
('stance','Quelle position la synthèse adopte-t-elle envers une formule générale de confidentialité ?','Elle la juge insuffisante si elle oblige la personne à croire sans comprendre les pratiques concrètes.',['croire','comprendre']),
('vocabulary_in_context','Pourquoi « cacher » et « montrer » sont-ils opposés ?','Ils représentent deux manières de traiter les règles du système : les rendre invisibles ou les expliquer de façon vérifiable.',['cacher','montrer']),
('synthesis','Comment le temps intervient-il dans la confidentialité ?','Une pratique peut rester utile, devenir plus risquée ou continuer trop longtemps; la durée doit donc être révisée avec la finalité.',['rester','devenir','continuer']),
('summary','Résume l’unité en une phrase.','Du téléphone, compte, message et adresse à la photo, au nom, au visage et à la voix, puis au choix de contrôler, suivre, connaître ou cacher, une politique doit aider le client et le bureau à demander et répondre clairement avant de vendre, chercher ou trouver des traces dans un monde où les usages peuvent s’étendre.',['téléphone','compte','message','adresse','photo','nom','visage','voix','contrôler','suivre','connaître','cacher','client','bureau','demander','répondre','vendre','chercher','trouver','monde'])]}
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);text=text_of(s)
 return {'id':s['id'],'language':'fr','cefr':'B2','unit':6,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 06 guarded production batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 06: digital life and privacy.','Accepted B2 default four fresh targets per P01-P05; P06 zero new.','All services, organizations and scenarios are fictional/generic.']},'paired_text_group':s.get('pair'),'prerequisites':['French B2 Units 01-05 canonical and Unit05 frontier lock PASS'],'difficulty_notes_internal':'B2 privacy reasoning: purpose limitation, retention, identity exposure, paired opinions, control, transparency burden and secondary use.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b2_u06']}
def main():
 for lab,p in [('A1',A1),('A2',A2),('B1',B1),('B2',CANON)]:
  got=subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
  if got!=EXPECTED[lab]:raise AssertionError(f'{lab} blob drift: {got} != {EXPECTED[lab]}')
 lock=json.loads(LOCK.read_text(encoding='utf-8'));probe=json.loads(PROBE.read_text(encoding='utf-8'))
 if lock.get('status')!='PASS' or lock.get('canonical_blob')!=EXPECTED['B2'] or lock.get('last_sequence')!=30:raise AssertionError('Unit05 lock mismatch')
 if probe.get('status')!='PASS' or probe.get('b2_source_blob')!=EXPECTED['B2']:raise AssertionError('Unit06 probe stale')
 fresh={x['form'] for x in probe.get('fresh',[])}
 if any(f not in fresh for f in FORMS):raise AssertionError('selected target absent from fresh Unit06 probe')
 load=lambda p:[json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()];a1,a2,b1,b2=map(load,(A1,A2,B1,CANON));deck=base.deck();prior=base.prior(a1+a2+b1+b2);pid={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};pf={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 if len(b2)!=30 or b2[-1]['id']!='fr-b2-u05-p06':raise AssertionError('unexpected B2 frontier')
 unit=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,deck) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};unit.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,deck) for f in FORMS];ids={t['form']:t['id'] for t in reviews};unit.append(mk(CHECKPOINT,[],reviews,ids,True));V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));newids=[];newforms=[]
 if [r['sequence'] for r in unit]!=list(range(31,37)) or [r['id'] for r in unit]!=[f'fr-b2-u06-p{i:02d}' for i in range(1,7)]:raise AssertionError('Unit06 sequence/id failure')
 if unit[2]['paired_text_group']!=PAIR or unit[3]['paired_text_group']!=PAIR:raise AssertionError('Unit06 paired opinions linkage failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
  if not 350<=r['word_count']<=550:raise AssertionError(f"{r['id']}: word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  if r['sequence']<=35 and len(r['new_lexical_targets'])!=4:raise AssertionError(f"{r['id']}: expected four new")
  if r['sequence']==36 and r['new_lexical_targets']:raise AssertionError('P06 must have zero new')
  local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[])};amap={a['question_id']:a['id'] for a in r['answer_key']}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage failure")
  for t in r['new_lexical_targets']:
   src=deck.get(t['form'])
   if t['id'] in pid or t['form'] in pf or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: new target drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20:raise AssertionError('Unit06 target uniqueness failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b2+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':6,'theme':'digital life and privacy','b2_passages':36,'questions':60,'answers':60,'new_targets':20,'paired_group':PAIR,'word_counts':{r['id']:r['word_count'] for r in unit}},ensure_ascii=False))
if __name__=='__main__':main()
