#!/usr/bin/env python3
"""Create French B2 Unit 01 calibration (sequences 1-6).

Theme: science and society.  Four fresh deliberate targets per P01-P05 is a
conservative calibration choice inside the durable 4-8 B2 planning range; P06
has zero new targets.  Acceptance as the later B2 default requires a separate
post-calibration review.
"""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base

REPO=Path(__file__).resolve().parents[2]
A1=REPO/'reading/french/a1/passages.jsonl'; A2=REPO/'reading/french/a2/passages.jsonl'; B1=REPO/'reading/french/b1/passages.jsonl'
CANON=REPO/'reading/french/b2/passages.jsonl'; SCHEMA=REPO/'reading/schema/passage.schema.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca'}
FORMS=('supposer','cause','effet','preuve','sécurité','protéger','suffire','moyen','public','apporter','libre','accepter','tromper','certain','général','ressembler','apprécier','ainsi','valoir','intéresser')

SPECS=[
{
'id':'fr-b2-u01-p01','sequence':1,'ptype':'instructional','title':'Quand une association ne suffit pas à prouver une cause','genre':'popular science explanation','domains':['educational','public'],'topics':['science and society','causal inference','air-quality sensors'],'forms':['supposer','cause','effet','preuve'],'reviews':['contrôle','niveau','exemple','tort'],'paired':None,
'paragraphs':[
"Une ville fictive installe des capteurs près de plusieurs écoles pour suivre la qualité de l’air. Après quelques semaines, une classe remarque que les jours où la circulation est plus dense correspondent souvent à un niveau moins favorable sur les capteurs. Il serait tentant de supposer immédiatement que la circulation est la cause unique de chaque variation. Pourtant, une association entre deux observations n’est pas encore une preuve suffisante de causalité. La météo, la position du capteur, des travaux voisins ou même un défaut de contrôle peuvent aussi modifier les valeurs. Le premier enjeu scientifique consiste donc à distinguer ce que les données montrent directement de l’effet qu’on leur attribue.",
"L’enseignante construit un exemple simple. Si le niveau mesuré baisse après une journée de pluie, cela ne prouve pas que la pluie est toujours la cause de l’amélioration. Pour avancer, la classe compare plusieurs périodes, vérifie les capteurs et note les facteurs qui changent en même temps. Elle apprend à supposer une explication comme hypothèse de travail sans la présenter comme conclusion. Une hypothèse utile produit des attentes vérifiables : si la circulation joue un rôle important, certains effets devraient apparaître de manière cohérente lorsque d’autres conditions restent comparables. Une seule observation spectaculaire peut attirer l’attention, mais elle ne vaut pas à elle seule preuve générale.",
"Cette prudence ne signifie pas qu’il faut renoncer à parler de cause. Elle oblige plutôt à préciser la force de l’argument. Des observations répétées, des comparaisons adaptées et des mécanismes plausibles peuvent rendre une explication plus solide. Inversement, si plusieurs prédictions échouent, la classe doit accepter qu’elle avait peut-être tort sur une partie du modèle. Le mot effet demande lui aussi de la précision : il peut désigner une différence observée, mais attribuer cette différence à une cause précise exige un raisonnement supplémentaire. Camille résume la démarche en trois questions : qu’avons-nous observé, quelle cause voulons-nous tester, et quelle preuve pourrait réellement distinguer cette explication de ses alternatives ?",
"Le débat devient alors social autant que scientifique. Si la ville doit modifier une rue ou déplacer des horaires d’école, les habitants veulent savoir pourquoi. Dire simplement « les capteurs l’ont montré » cache les étapes du raisonnement. Expliquer ce qu’on peut supposer, les autres causes possibles, l’effet observé et le niveau de preuve rend la décision plus transparente. Une bonne communication scientifique ne promet pas une certitude inexistante ; elle montre comment une conclusion a été construite et à quel contrôle elle pourrait encore résister."
],
'grammar':[{'id':'fr-b2-u01-hypothesis-vs-claim','role':'new','description':'contrast conditional/hypothesis framing with categorical causal claims'}],
'discourse':[{'id':'fr-b2-u01-causal-evidence','role':'new','description':'separate observation, hypothesis, alternative causes, effect and evidential strength'}],
'items':[
('main_claim','Quelle thèse principale défend le texte ?','Une association observée peut justifier une hypothèse, mais elle ne suffit pas à établir une cause sans comparaisons et preuves supplémentaires.',['supposer','cause','preuve']),
('literal_detail','Quels facteurs autres que la circulation peuvent modifier les valeurs ?','La météo, la position du capteur, des travaux voisins ou un défaut de contrôle.',['contrôle']),
('argument_relation','Quel rôle joue l’exemple de la pluie ?','Il montre pourquoi une variation simultanée ne suffit pas à identifier la cause de l’effet observé.',['exemple','cause','effet']),
('vocabulary_in_context','Que signifie « supposer » dans la démarche scientifique décrite ?','Proposer provisoirement une explication à tester sans la présenter comme acquise.',['supposer']),
('vocabulary_in_context','Comment « preuve » se distingue-t-elle d’une observation isolée ?','La preuve doit soutenir une conclusion en distinguant l’hypothèse de ses explications concurrentes.',['preuve']),
('assumption','Quelle supposition doit être testée si l’on attribue les variations à la circulation ?','Que les effets liés à la circulation restent cohérents lorsque les autres conditions pertinentes sont comparables.',['supposer','effet']),
('inference','Pourquoi reconnaître qu’on avait tort peut-il renforcer l’analyse ?','Parce que cela permet de corriger le modèle lorsqu’une prédiction échoue au lieu de protéger une conclusion initiale.',['tort']),
('reference_resolution','Dans « cette prudence », à quoi renvoie « cette » ?','À la prudence qui consiste à ne pas confondre association observée et causalité prouvée.',['preuve']),
('stance','Quelle attitude envers l’incertitude l’autrice adopte-t-elle ?','Elle défend une incertitude explicite et testable plutôt qu’une certitude prématurée.',['preuve','supposer']),
('summary','Résume la méthode en une phrase.','On peut supposer une cause à partir d’un effet observé, mais une preuve exige contrôle, comparaison et possibilité de reconnaître qu’un exemple ou modèle avait tort.',['supposer','cause','effet','preuve','contrôle','exemple','tort'])]
},
{
'id':'fr-b2-u01-p02','sequence':2,'ptype':'reinforcement','title':'Protéger sans promettre une sécurité absolue','genre':'policy analysis','domains':['public','professional'],'topics':['science and society','risk policy','public safety'],'forms':['sécurité','protéger','suffire','moyen'],'reviews':['dangereux','risquer','prévoir','personnel'],'paired':None,
'paragraphs':[
"À partir du même projet fictif de capteurs, le conseil municipal envisage une zone où les voitures seraient limitées à certaines heures. Le débat se déplace : il ne s’agit plus seulement de mesurer, mais de décider quel moyen peut protéger les élèves sans prétendre produire une sécurité absolue. Certains élus affirment qu’une restriction forte suffit puisqu’elle réduit directement une source possible de pollution. D’autres rappellent qu’une mesure peut être utile tout en laissant subsister d’autres sources. La difficulté politique consiste à relier la force de l’action à la qualité des preuves, puis à expliquer quels risques elle réduit réellement et lesquels restent présents.",
"Le service technique propose donc plusieurs scénarios. Le premier limite la circulation, le second modifie les horaires de livraison, et le troisième combine ces deux moyens avec une nouvelle période de mesure. Le personnel doit prévoir comment observer les effets sans déplacer simplement le problème vers une rue voisine. Une politique conçue pour protéger un groupe peut créer une charge ailleurs ; elle doit donc examiner la distribution des bénéfices et des coûts. Le mot sécurité devient relatif à un risque défini : protéger contre une exposition donnée ne signifie pas garantir que toute situation deviendra sans danger. Une affirmation trop large risquerait de rendre le débat moins honnête.",
"L’analyse compare aussi ce qui peut suffire à différents objectifs. Pour tester une hypothèse, une mesure temporaire peut suffire ; pour modifier durablement l’espace urbain, le niveau de justification attendu est plus élevé. De même, un moyen peu coûteux peut être raisonnable comme première étape sans être le meilleur choix final. Les responsables doivent prévoir une révision si les résultats ne correspondent pas aux attentes. Cette possibilité de retour n’est pas un signe de faiblesse : elle reconnaît que l’action publique intervient souvent avant que toute incertitude ait disparu.",
"Camille observe que le vocabulaire change la manière dont le public comprend le projet. Dire « cette règle garantit la sécurité » ferme le débat, tandis que « cette mesure vise à protéger contre un risque précis » laisse visible la portée de la décision. Le conseil finit par retenir un essai limité dans le temps, accompagné d’indicateurs annoncés à l’avance. Le moyen choisi n’est ni présenté comme parfait ni comme inutile : il doit suffire à produire une comparaison informative tout en évitant de créer une situation plus dangereuse ailleurs."
],
'grammar':[{'id':'fr-b2-u01-sufficiency-scope','role':'new','description':'contrast sufficiency for a limited test with stronger sufficiency claims for long-term policy'}],
'discourse':[{'id':'fr-b2-u01-risk-scope','role':'new','description':'qualify policy claims by risk scope, distribution and reversible evaluation'}],
'items':[
('main_claim','Quel problème central l’analyse met-elle en évidence ?','Une politique peut protéger contre un risque précis sans garantir une sécurité absolue, et son moyen doit être proportionné à l’objectif et aux preuves.',['sécurité','protéger','moyen']),
('literal_detail','Quels trois scénarios le service technique compare-t-il ?','Limiter la circulation, modifier les horaires de livraison, ou combiner les deux avec une nouvelle période de mesure.',['moyen']),
('argument_relation','Pourquoi le texte distingue-t-il essai temporaire et modification durable ?','Parce que ce qui peut suffire à tester une hypothèse ne suffit pas nécessairement à justifier une politique permanente.',['suffire']),
('vocabulary_in_context','Que signifie « protéger » dans ce passage ?','Réduire un risque défini sans promettre l’élimination de tous les risques.',['protéger','sécurité']),
('vocabulary_in_context','Comment « moyen » est-il employé ?','Comme une méthode ou un instrument d’action parmi plusieurs options possibles.',['moyen']),
('inference','Pourquoi faut-il vérifier les rues voisines ?','Pour voir si la mesure réduit réellement le problème au lieu de le déplacer vers un autre groupe.',['protéger']),
('assumption','Quelle hypothèse serait cachée par l’expression « garantir la sécurité » ?','Que la mesure contrôle tous les risques pertinents, ce que l’analyse ne permet pas d’affirmer.',['sécurité']),
('stance','Quelle position le texte adopte-t-il sur les politiques révisables ?','Il les présente comme une réponse raisonnable à l’incertitude, à condition de prévoir des critères d’évaluation.',['prévoir']),
('cause_effect','Pourquoi une affirmation trop large peut-elle être dangereuse pour le débat ?','Parce qu’elle peut masquer les risques restants et empêcher une évaluation honnête de la mesure.',['dangereux','risquer']),
('summary','Résume l’analyse.','Un moyen peut suffire à tester une politique et protéger contre un risque précis, mais la sécurité doit être définie par portée, avec personnel et critères prévus pour éviter de risquer un déplacement du problème.',['moyen','suffire','protéger','sécurité','personnel','prévoir','risquer'])]
},
{
'id':'fr-b2-u01-p03','sequence':3,'ptype':'interleaved','title':'Point de vue A : ouvrir les observations au public','genre':'paired viewpoint A','domains':['public','educational'],'topics':['science and society','citizen science','open participation'],'forms':['public','apporter','libre','accepter'],'reviews':['journal','impression','liste','relation'],'paired':'fr-b2-u01-citizen-science-access',
'paragraphs':[
"Une chercheuse fictive, Nadia, défend l’idée d’ouvrir une partie du projet de capteurs au public. Selon elle, les habitants peuvent apporter des observations que les appareils fixes ne captent pas : travaux temporaires, circulation inhabituelle, odeurs ou changements d’usage d’une rue. Elle propose un formulaire libre d’accès dans lequel chacun peut signaler un événement, à condition d’accepter que le signalement soit vérifié avant d’être utilisé dans l’analyse. Son argument ne consiste pas à remplacer les mesures techniques par des témoignages, mais à élargir la liste des situations que l’équipe sait chercher.",
"Nadia insiste aussi sur la relation entre participation et confiance. Quand un journal local publie seulement le résultat final, le public peut avoir l’impression que les choix méthodologiques ont été faits hors de sa portée. Donner un accès libre aux protocoles, aux limites et à certaines données agrégées peut permettre aux habitants de comprendre comment une conclusion se construit. Cela peut aussi apporter des critiques utiles. Une personne qui vit près d’un carrefour connaît parfois un changement récent que la base de données officielle n’a pas encore intégré. Pour Nadia, accepter ces contributions ne signifie pas les croire automatiquement : cela signifie leur donner une voie explicite vers la vérification.",
"Elle reconnaît néanmoins deux conditions. D’abord, le public doit savoir ce qui sera conservé, publié ou rejeté ; ensuite, le projet doit expliquer pourquoi une contribution n’a pas été retenue. Un accès libre sans règles claires pourrait créer une nouvelle impression d’arbitraire. Nadia préfère donc un système où les critères d’acceptation sont visibles et où les corrections restent traçables. Dans son raisonnement, la transparence n’est pas seulement morale : elle améliore la possibilité de contrôler le processus et de découvrir des erreurs.",
"Son point de vue peut se résumer ainsi : la science citoyenne vaut surtout lorsqu’elle permet d’apporter des observations nouvelles tout en rendant plus compréhensible la relation entre données, critères et conclusions. Elle demande au projet d’accepter une participation structurée plutôt qu’une simple consultation symbolique. Le public n’est ni traité comme un capteur parfait ni comme un spectateur passif. L’accès libre devient un outil de coopération, à condition que chaque apport passe par les mêmes exigences de documentation que les autres sources."
],
'grammar':[{'id':'fr-b2-u01-open-condition','role':'new','description':'use conditional concessions and à condition de to delimit an argument in favor of openness'}],
'discourse':[{'id':'fr-b2-u01-view-a','role':'new','description':'build a pro-participation stance while acknowledging validation and transparency conditions'}],
'items':[
('main_claim','Quelle est la thèse de Nadia ?','Une participation publique structurée peut apporter des observations utiles et renforcer la compréhension du processus sans remplacer la validation scientifique.',['public','apporter','accepter']),
('literal_detail','Quel type de contribution les habitants pourraient-ils signaler ?','Des événements temporaires comme des travaux, une circulation inhabituelle, des odeurs ou des changements d’usage.',['apporter']),
('argument_relation','Quel rôle jouent les deux conditions du troisième paragraphe ?','Elles limitent l’argument en faveur d’un accès libre afin que la participation reste traçable et compréhensible.',['libre']),
('vocabulary_in_context','Que signifie « libre » dans « accès libre » ?','Accessible sans barrière inutile, tout en restant soumis à des règles explicites d’utilisation.',['libre']),
('vocabulary_in_context','Que signifie « accepter » les contributions ?','Les faire entrer dans une procédure de vérification, et non les considérer comme automatiquement vraies.',['accepter']),
('inference','Pourquoi Nadia distingue-t-elle témoignage et mesure technique ?','Pour défendre la complémentarité des sources plutôt que le remplacement d’une méthode par l’autre.',['apporter']),
('stance','Quel est le ton de Nadia envers la participation du public ?','Favorable mais conditionnel : elle valorise la participation seulement si les règles de validation sont visibles.',['public','libre']),
('reference_resolution','À quoi renvoie « cela » dans « Cela peut aussi apporter des critiques utiles » ?','Au fait de donner un accès plus libre aux protocoles, limites et données agrégées.',['apporter','libre']),
('argument_relation','Pourquoi l’exemple du journal local est-il utilisé ?','Pour montrer comment une communication seulement finale peut produire une impression de distance entre le public et la méthode.',['journal','impression']),
('summary','Résume le point de vue A.','Nadia veut un accès libre et structuré : le public peut apporter des observations, mais le projet ne doit accepter ces apports qu’après vérification et expliquer leur relation aux critères.',['public','apporter','libre','accepter','journal','impression','relation'])]
},
{
'id':'fr-b2-u01-p04','sequence':4,'ptype':'transfer','title':'Point de vue B : une participation visible peut encore tromper','genre':'paired viewpoint B','domains':['public','educational'],'topics':['science and society','citizen science','sampling bias'],'forms':['tromper','certain','général','ressembler'],'reviews':['détail','honnête','tort','intéressant'],'paired':'fr-b2-u01-citizen-science-access',
'paragraphs':[
"Un statisticien fictif, Marc, partage l’objectif de transparence mais conteste une partie de l’enthousiasme de Nadia. Selon lui, une plateforme ouverte peut tromper si le nombre de contributions est présenté comme l’image fidèle de toute la ville. Les personnes qui participent volontairement peuvent avoir un profil particulier : elles disposent de plus de temps, s’intéressent davantage au sujet ou vivent près des lieux les plus discutés. Un ensemble de signalements peut donc ressembler à une carte générale de l’expérience urbaine sans représenter chaque groupe avec la même précision. Ce détail n’annule pas les contributions, mais il change la conclusion qu’on peut en tirer.",
"Marc donne un exemple. Si un certain quartier produit cent signalements et un autre seulement dix, on ne peut pas conclure immédiatement que le premier connaît dix fois plus de problèmes. Il faut savoir combien de personnes avaient connaissance du projet, combien avaient accès au formulaire et comment les événements ont été définis. Une comparaison honnête exige donc un dénominateur ou au moins une discussion explicite des différences de participation. Sans cela, une carte très intéressante peut donner tort au lecteur qui suppose que chaque zone a été observée de la même façon.",
"Il ajoute qu’un résultat peut tromper même si aucune donnée n’est fausse. Une visualisation générale simplifie nécessairement, et deux quartiers qui semblent se ressembler sur une carte peuvent différer dans les conditions qui ont produit leurs points. Marc préfère publier séparément le nombre de participants, le nombre de signalements et les mesures des capteurs. Ainsi, le public peut voir que les trois indicateurs répondent à des questions différentes. Il ne demande pas d’abandonner la participation, mais de rendre visible l’incertitude sur sa représentativité.",
"Son contreargument vise donc la portée de l’inférence. Il est certain que les contributions peuvent révéler des événements utiles ; il est moins certain qu’elles permettent seules une conclusion générale sur la population. Pour Marc, la meilleure transparence ne consiste pas seulement à ouvrir les données, mais à montrer ce à quoi chaque donnée peut ou ne peut pas ressembler. Cette position complète plutôt qu’elle ne détruit celle de Nadia : tous deux veulent une participation honnête, mais Marc insiste sur le risque de tromper lorsque la visibilité d’un groupe est confondue avec son poids réel."
],
'grammar':[{'id':'fr-b2-u01-certainty-scope','role':'new','description':'contrast certain/moins certain and resemblance with representativeness claims'}],
'discourse':[{'id':'fr-b2-u01-view-b','role':'new','description':'construct a counterargument focused on sampling, denominator choice and inference scope'}],
'items':[
('main_claim','Quel contreargument Marc formule-t-il ?','Une participation ouverte peut être utile mais tromper si sa visibilité est confondue avec une représentation générale de toute la population.',['tromper','général']),
('literal_detail','Quels trois indicateurs Marc veut-il publier séparément ?','Le nombre de participants, le nombre de signalements et les mesures des capteurs.',['général']),
('argument_relation','Pourquoi l’exemple des cent signalements contre dix est-il important ?','Il montre qu’un nombre brut ne suffit pas sans information sur l’accès, la participation et la population observée.',['tromper']),
('vocabulary_in_context','Que signifie « ressembler » dans l’argument ?','Présenter une apparence similaire sans garantir une équivalence méthodologique ou représentative.',['ressembler']),
('vocabulary_in_context','Comment « certain » nuance-t-il la conclusion finale ?','Il distingue ce qui est bien soutenu — l’utilité possible des contributions — de ce qui l’est moins — leur représentativité générale.',['certain','général']),
('inference','Comment une visualisation peut-elle tromper sans contenir de données fausses ?','En simplifiant des conditions de collecte différentes au point de suggérer une comparaison plus forte que les données ne permettent.',['tromper']),
('stance','Marc rejette-t-il la science citoyenne ?','Non. Il l’accepte comme source utile mais demande de limiter les inférences et d’afficher les conditions de collecte.',['certain']),
('reference_resolution','À quoi renvoie « ce détail » dans le premier paragraphe ?','Au fait que les participants volontaires peuvent ne pas représenter tous les groupes de la ville de la même manière.',['détail']),
('argument_relation','En quoi le point de vue B complète-t-il le point de vue A ?','Il accepte l’ouverture mais ajoute une exigence de représentativité et de portée d’inférence.',['honnête','tort']),
('summary','Résume le point de vue B.','Marc estime qu’une carte peut ressembler à une image générale et pourtant tromper ; il est certain de l’utilité des contributions, mais demande une interprétation honnête de leurs limites.',['tromper','ressembler','général','certain','détail','honnête','tort','intéressant'])]
},
{
'id':'fr-b2-u01-p05','sequence':5,'ptype':'transfer','title':'Apprécier une politique : ce qui vaut l’effort et ce qui intéresse réellement','genre':'integrative analysis','domains':['public','professional'],'topics':['science and society','policy evaluation','public participation'],'forms':['apprécier','ainsi','valoir','intéresser'],'reviews':['relation','choix','décision','résultat'],'paired':None,
'paragraphs':[
"Après les deux points de vue, Camille doit préparer une note de synthèse pour le conseil municipal fictif. Son objectif n’est pas de choisir mécaniquement entre Nadia et Marc, mais d’apprécier la valeur de leurs arguments selon la décision à prendre. Elle distingue trois questions : quelles observations supplémentaires peuvent intéresser les chercheurs, quelles règles de participation valent l’effort administratif, et quelle relation existe entre les contributions du public et le résultat que la ville veut mesurer. Cette structure évite de traiter transparence et représentativité comme des objectifs opposés par nature.",
"Pour apprécier la première question, Camille examine le type d’information que les habitants peuvent apporter. Les événements temporaires difficiles à détecter par des capteurs fixes peuvent valoir une procédure de signalement, surtout si le coût de vérification reste raisonnable. En revanche, si la décision exige une estimation générale de fréquence, les contributions volontaires ne suffisent pas seules. Ainsi, la même donnée peut intéresser une équipe comme indice exploratoire tout en étant insuffisante pour une comparaison statistique. Le choix de méthode dépend donc de la fonction assignée à la donnée, et non de son caractère participatif ou institutionnel.",
"La deuxième question porte sur la gouvernance. Une procédure très complexe pourrait décourager le public ; une procédure trop libre pourrait rendre les validations impossibles à expliquer. Camille propose ainsi un compromis : quelques catégories de signalement bien définies, un espace de commentaire, des critères publics de validation et un tableau séparant contributions et mesures instrumentales. Cette solution peut valoir l’effort si elle produit un résultat que ni les capteurs seuls ni une consultation ponctuelle n’auraient fourni. Mais sa valeur doit être réévaluée après une période d’essai.",
"Enfin, Camille précise ce qui devrait intéresser le conseil lors de l’évaluation : diversité des participants, proportion de signalements vérifiables, nouveaux événements détectés, temps de traitement et influence réelle sur les décisions. Apprécier le projet signifie comparer ces dimensions sans réduire le succès au nombre total de clics. Ainsi, une forte participation qui ne change aucun choix peut avoir une valeur différente d’une participation plus petite qui révèle un problème important. La note conclut qu’une politique scientifique vaut surtout lorsqu’elle relie clairement la question posée, le moyen de collecte, le résultat obtenu et la décision qu’elle prétend éclairer."
],
'grammar':[{'id':'fr-b2-u01-evaluation-worth','role':'new','description':'use valoir, apprécier and ainsi to move from evidence to qualified evaluation'}],
'discourse':[{'id':'fr-b2-u01-synthesis','role':'new','description':'reconcile paired viewpoints by assigning different evidential functions and evaluation criteria'}],
'items':[
('main_claim','Quelle synthèse Camille propose-t-elle ?','La participation et les capteurs peuvent être combinés si chaque source reçoit une fonction claire et si la politique est évaluée selon la décision visée.',['apprécier','valoir']),
('literal_detail','Quels critères Camille propose-t-elle d’observer après l’essai ?','Diversité des participants, part de signalements vérifiables, nouveaux événements, temps de traitement et influence sur les décisions.',['intéresser']),
('cross_text_synthesis','Comment le texte réconcilie-t-il Nadia et Marc ?','Il conserve l’ouverture défendue par Nadia tout en séparant les fonctions des données et les limites de représentativité soulignées par Marc.',['apprécier']),
('vocabulary_in_context','Que signifie « apprécier » ici ?','Évaluer la valeur ou la qualité d’un argument ou d’un dispositif selon des critères explicites.',['apprécier']),
('vocabulary_in_context','Que signifie « valoir l’effort » ?','Avoir une valeur suffisante pour justifier le temps, le coût ou le travail demandé.',['valoir']),
('argument_relation','Quel rôle joue « ainsi » dans plusieurs paragraphes ?','Il introduit une conséquence ou une reformulation logique tirée du raisonnement précédent.',['ainsi']),
('inference','Pourquoi un grand nombre de clics n’est-il pas un résultat suffisant ?','Parce que la participation doit être reliée à la qualité des informations et à son influence réelle sur la décision.',['résultat','décision']),
('stance','Quelle attitude Camille adopte-t-elle envers le compromis ?','Elle le soutient comme hypothèse de politique à tester, non comme solution définitive.',['choix']),
('assumption','Qu’est-ce qui doit être vrai pour que la procédure vaille l’effort ?','Elle doit apporter une information ou une compréhension utile qui justifie son coût de validation et de gestion.',['valoir','apporter']),
('summary','Résume l’intégration.','Camille veut apprécier ce qui peut intéresser la recherche, montrer ainsi quels choix valent l’effort, puis relier chaque résultat à la décision et à la relation entre sources.',['apprécier','intéresser','ainsi','valoir','relation','choix','résultat','décision'])]
}
]

CHECKPOINT={
'id':'fr-b2-u01-p06','sequence':6,'ptype':'checkpoint','title':'Science et société : de l’hypothèse à la décision publique','genre':'B2 cumulative analytical checkpoint','domains':['educational','public','professional'],'topics':['science and society','causal inference','risk policy','citizen science','evaluation'],'paired':None,
'paragraphs':[
"L’unité commence par une distinction méthodologique. Observer une association permet de supposer une explication, mais identifier une cause exige davantage : il faut préciser l’effet, comparer des alternatives et chercher une preuve capable de les départager. Cette exigence ne disparaît pas lorsque la question devient politique. Une mesure de sécurité peut protéger contre un risque sans garantir une sécurité absolue ; le moyen retenu doit suffire à l’objectif défini et rester révisable si les observations changent. Dans les deux cas, l’argument gagne en force lorsque sa portée est visible plutôt que cachée derrière un vocabulaire trop certain.",
"Les deux textes appariés déplacent ensuite le problème vers la participation. Nadia veut que le public puisse apporter des observations grâce à un accès libre, à condition que le projet explique ce qu’il peut accepter et comment il vérifie chaque contribution. Marc partage l’objectif de transparence, mais avertit qu’une carte peut tromper si les participants visibles sont pris pour une image générale de la population. Deux quartiers peuvent se ressembler graphiquement tout en ayant été observés dans des conditions différentes. Il est donc certain que la participation peut révéler des événements ; il est moins certain qu’elle permette seule une estimation générale.",
"La synthèse refuse de choisir entre ouverture et prudence comme si l’une annulait l’autre. Pour apprécier une politique, Camille demande quelle fonction chaque source remplit. Une contribution peut intéresser la recherche parce qu’elle signale un événement inattendu ; une série de contributions peut valoir l’effort de validation sans devenir une estimation représentative. Ainsi, le même matériau peut être utile pour découvrir, expliquer ou décider à des degrés différents. Le raisonnement B2 consiste précisément à suivre ces changements de fonction, à relier les arguments entre paragraphes et à identifier la stance d’un auteur lorsqu’il limite ou renforce une affirmation.",
"Cette méthode prolonge les habitudes acquises en B1 — contrôle, niveau de preuve, exemple, choix, décision et résultat — mais elle ajoute une exigence : comparer des positions qui peuvent être partiellement compatibles. Une conclusion solide ne demande pas seulement « qui a raison ? ». Elle demande quelle proposition est soutenue, dans quelles conditions, par quel moyen, et pour quel usage. La science et la société se rencontrent alors dans un espace de décision où l’incertitude n’est ni ignorée ni utilisée comme excuse pour ne rien faire. Elle devient une information à communiquer, à tester et à réviser."
],
'grammar':[{'id':'fr-b2-u01-cumulative-scope','role':'integration','description':'integrate hypothesis, concession, sufficiency, certainty and evaluative consequence across the unit'}],
'discourse':[{'id':'fr-b2-u01-cumulative-argument','role':'integration','description':'synthesize causal evidence, policy scope, paired viewpoints and evaluative reconciliation'}],
'items':[
('main_claim','Quelle compétence B2 le checkpoint met-il au centre ?','Comparer la portée de plusieurs arguments, leurs conditions et leurs fonctions avant de tirer une conclusion ou une décision.',['preuve','moyen']),
('cause_effect','Pourquoi une association ne suffit-elle pas à établir une cause ?','Parce que plusieurs explications peuvent produire le même effet et qu’une preuve doit les distinguer.',['supposer','cause','effet','preuve']),
('argument_relation','Comment le paragraphe sur la sécurité prolonge-t-il le raisonnement causal ?','Il applique la même limitation de portée à l’action publique : un moyen peut protéger sans suffire à garantir toute sécurité.',['sécurité','protéger','suffire','moyen']),
('cross_text_synthesis','Quel désaccord réel sépare Nadia et Marc ?','Nadia insiste sur ce que le public peut apporter grâce à un accès libre et vérifié ; Marc insiste sur le risque de tromper si cette participation est interprétée comme représentative en général.',['public','apporter','libre','accepter','tromper','général']),
('vocabulary_in_context','Pourquoi « certain » et « ressembler » sont-ils importants dans le point de vue B ?','Ils permettent de distinguer le degré de certitude d’une conclusion et l’apparence de représentativité de sa réalité méthodologique.',['certain','ressembler']),
('argument_relation','Quel rôle joue « ainsi » dans la synthèse ?','Il relie des prémisses à une conséquence évaluative et montre comment une même donnée peut changer de fonction.',['ainsi']),
('stance','Quelle stance finale le checkpoint adopte-t-il face à l’incertitude ?','Il refuse à la fois la certitude excessive et l’inaction ; il traite l’incertitude comme une information à tester, communiquer et réviser.',['apprécier']),
('assumption','Qu’est-ce qui rend une participation publique acceptable selon l’ensemble de l’unité ?','Des règles visibles, une validation explicite, une interprétation limitée et une fonction claire dans la décision.',['accepter','public']),
('synthesis','Comment apprécier si une procédure vaut l’effort ?','En comparant ce qu’elle apporte, ce qui peut intéresser la recherche, son coût de validation et son influence réelle sur la décision.',['apprécier','valoir','intéresser']),
('summary','Résume l’unité en une phrase.','B2 demande de supposer sans confondre cause, effet et preuve, choisir un moyen qui peut suffire à protéger sans promettre toute sécurité, ouvrir le public à apporter sous accès libre et conditions acceptées, éviter qu’une image générale puisse tromper malgré ce qui semble certain ou se ressembler, puis apprécier ainsi ce qui vaut l’effort et peut intéresser la décision.',['supposer','cause','effet','preuve','sécurité','protéger','suffire','moyen','public','apporter','libre','accepter','tromper','certain','général','ressembler','apprécier','ainsi','valoir','intéresser'])]
}

def text_of(s): return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
    q,a=base.qa(s['items'],ids); text=text_of(s)
    return {'id':s['id'],'language':'fr','cefr':'B2','unit':1,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 01 calibration; production load not accepted until post-calibration review.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 01 calibration.','Science/society theme with paired viewpoints and conservative four-target calibration load.','Full language-wide final French audit remains deferred.']},'paired_text_group':s.get('paired'),'prerequisites':['French A1-A2-B1 generation-integrity PASS'],'difficulty_notes_internal':'B2 calibration: causal inference, policy scope, paired viewpoints, stance, counterargument, cohesion and synthesis.','reader_tags':['unit_role:'+s['ptype'],'calibration','french_b2_u01']}

def main():
    for label,path in [('A1',A1),('A2',A2),('B1',B1)]:
        got=subprocess.check_output(['git','hash-object',str(path)],text=True).strip()
        if got!=EXPECTED[label]: raise AssertionError(f'{label} blob drift: {got} != {EXPECTED[label]}')
    if CANON.exists() and CANON.read_text(encoding='utf-8').strip(): raise AssertionError('B2 canonical unexpectedly exists before Unit01 calibration')
    a1=[json.loads(x) for x in A1.read_text(encoding='utf-8').splitlines() if x.strip()]; a2=[json.loads(x) for x in A2.read_text(encoding='utf-8').splitlines() if x.strip()]; b1=[json.loads(x) for x in B1.read_text(encoding='utf-8').splitlines() if x.strip()]
    prior=base.prior(a1+a2+b1); deck=base.deck(); prior_ids={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; prior_forms={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
    bad=[]
    for f in FORMS:
        if f not in deck: bad.append(f+':missing_lexicon')
        elif base.tid(deck[f]['rank']) in prior_ids or f in prior_forms or prior.get(f): bad.append(f+':already_deliberate')
    if bad: raise AssertionError('B2 Unit01 candidate failures: '+', '.join(bad))
    rows=[]
    for s in SPECS:
        text=text_of(s); new=[base.nt(f,text,deck) for f in s['forms']]; reviews=[base.rev(f,prior) for f in s['reviews']]; ids={t['form']:t['id'] for t in new+reviews}; rows.append(mk(s,new,reviews,ids))
    reviews=[base.cur(f,deck) for f in FORMS]; ids={t['form']:t['id'] for t in reviews}; rows.append(mk(CHECKPOINT,[],reviews,ids,True))
    if [r['sequence'] for r in rows]!=list(range(1,7)) or [r['id'] for r in rows]!=[f'fr-b2-u01-p{i:02d}' for i in range(1,7)]: raise AssertionError('B2 Unit01 continuity failure')
    V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8'))); newids=[];newforms=[]
    for r in rows:
        errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
        if errs: raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
        if not 350<=r['word_count']<=550: raise AssertionError(f"{r['id']}: B2 word band {r['word_count']}")
        if len(r['questions'])!=10 or len(r['answer_key'])!=10: raise AssertionError(f"{r['id']}: assessment count")
        if r['sequence']<=5 and len(r['new_lexical_targets'])!=4: raise AssertionError(f"{r['id']}: calibration load must be 4")
        if r['sequence']==6 and r['new_lexical_targets']: raise AssertionError('B2 Unit01 P06 must have zero new targets')
        amap={a['question_id']:a['id'] for a in r['answer_key']}; local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
        for q in r['questions']:
            if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])): raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
        for t in r['new_lexical_targets']:
            src=deck.get(t['form'])
            if t['id'] in prior_ids or t['form'] in prior_forms or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']: raise AssertionError(f"{r['id']}: source/exposure/freshness drift {t}")
            newids.append(t['id']); newforms.append(t['form'])
        for t in r['review_lexical_targets']:
            if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1: raise AssertionError(f"{r['id']}: invisible review {t['form']}")
    if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20: raise AssertionError('B2 Unit01 lexical uniqueness failure')
    if rows[2]['paired_text_group']!='fr-b2-u01-citizen-science-access' or rows[3]['paired_text_group']!=rows[2]['paired_text_group']: raise AssertionError('paired viewpoint linkage failure')
    CANON.parent.mkdir(parents=True,exist_ok=True); CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in rows),encoding='utf-8')
    print(json.dumps({'status':'PASS','level':'B2','unit':1,'passages':6,'questions':60,'answers':60,'new_targets':20,'word_counts':{r['id']:r['word_count'] for r in rows},'paired_text_group':'fr-b2-u01-citizen-science-access','targets':[{'form':f,'rank':deck[f]['rank'],'id':base.tid(deck[f]['rank'])} for f in FORMS]},ensure_ascii=False))

if __name__=='__main__': main()
