#!/usr/bin/env python3
"""Append French A1 Unit 10 (sequences 55-60) and complete A1."""
from __future__ import annotations
import csv,json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[2]
CANON=ROOT/'reading/french/a1/passages.jsonl'; SCHEMA=ROOT/'reading/schema/passage.schema.json'; LEXICON=ROOT/'french_top1000.csv'
EXPECTED_BLOB='adfaabc9643545950000236c113975887d695523'
NEW_FORMS=('pluie','soleil','froid','chaud','acheter','prix','argent','vêtement','manteau','chaussure')

def lexicon():
 out={}
 with LEXICON.open(encoding='utf-8',newline='') as f:
  for row in csv.DictReader(f):
   x=(row.get('Front') or '').strip();b=row.get('Back') or ''
   a=re.search(r'Rank:\s*(\d+)',b);m=re.search(r'Meaning:\s*(.+)',b);p=re.search(r'Part of speech:\s*(.+)',b)
   if x and a and m and p:out[x]={'rank':int(a.group(1)),'sense':m.group(1).strip(),'pos':p.group(1).strip()}
 return out
def tid(r):return f'fr-rank-{r:04d}'
def count(text,f):return len(re.findall(rf'(?<!\w){re.escape(f)}(?!\w)',text,flags=re.I|re.UNICODE))
def prior(rows):
 d={}
 for r in rows:
  for t in r.get('new_lexical_targets',[]):
   if isinstance(t,dict) and t.get('form'):d.setdefault(t['form'],[]).append(t)
 return d
def nt(f,text,L):
 s=L[f];n=count(text,f)
 if n<1:raise AssertionError(f'{f}: invisible new target')
 return {'id':tid(s['rank']),'form':f,'lemma':f,'intended_sense':s['sense'],'part_of_speech':s['pos'],'register':'contemporary standard','variety':None,'context_strategy':['scenario_resolution'],'first_introduced':True,'exposures_in_text':n,'source_lexicon':'french_top1000.csv','source_rank':s['rank'],'beyond_base':False}
def rev(f,P):
 h=P.get(f,[])
 if len(h)!=1:raise AssertionError(f'{f}: expected one prior deliberate target, got {len(h)}')
 return {'id':h[0]['id'],'form':f,'review_stage':'R2','representation':'running_text','expected_exposure_number':None}
def cur(f,L):return {'id':tid(L[f]['rank']),'form':f,'review_stage':'R1','representation':'summary','expected_exposure_number':None}
def qa(items):
 q=[];a=[]
 for i,(ty,p,ans,ids) in enumerate(items,1):
  qi=f'q{i}';ai=f'a{i}';x={'id':qi,'type':ty,'prompt':p,'answer_id':ai}
  if ids:x['target_ids']=ids
  q.append(x);a.append({'id':ai,'question_id':qi,'answer':ans,'explanation':''})
 return q,a
def mk(pid,seq,ptype,title,genre,domains,topics,text,new,reviews,grammar,discourse,items,speed=False):
 q,a=qa(items)
 return {'id':pid,'language':'fr','cefr':'A1','unit':10,'sequence':seq,'revision':1,'title':title,'passage_type':ptype,'genre':genre,'domains':domains,'topics':topics,'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':grammar,'discourse_targets':discourse,'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'Generation-stage French A1 Unit 10; full multi-pass language audit deferred until the complete French corpus.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French A1 Unit 10 completion batch.','Schema, source identity, word band, linkage, local target declaration, visible review, continuity, and checkpoint invariants enforced.']},'paired_text_group':None,'prerequisites':['French A1 Units 01-09 canonical corpus'],'difficulty_notes_internal':'A1 capstone: weather, temperature, simple shopping, money, clothing, and cumulative daily-life communication.','reader_tags':['unit_role:'+ptype,'generation_batch','french_a1_u10']}
def build(rows,L):
 P=prior(rows)
 for f in NEW_FORMS:
  if f not in L:raise AssertionError(f'{f}: missing from french_top1000.csv')
  if P.get(f):raise AssertionError(f'{f}: already deliberately introduced')
 out=[]
 text='''Dimanche, Camille sort avec sa famille. Son père regarde le ciel avant de fermer la porte. La pluie commence doucement, mais un peu de soleil reste visible entre les nuages. La famille décide de prendre un parapluie. Après vingt minutes, la pluie devient plus faible et le soleil revient. Le père de Camille dit qu’ils peuvent continuer leur promenade. Camille observe le changement et comprend que la pluie et le soleil peuvent apparaître le même jour. Elle garde quand même le parapluie dans son sac, car le ciel est encore gris au loin.'''
 a,b=nt('pluie',text,L),nt('soleil',text,L)
 out.append(mk('fr-a1-u10-p01',55,'instructional','La pluie et le soleil','weather walk narrative',['personal','public'],['weather','family','outdoors'],text,[a,b],[rev('famille',P),rev('père',P)],[{'id':'fr-a1-pluie-weather','role':'new','description':'pluie as rain'},{'id':'fr-a1-soleil-weather','role':'new','description':'soleil as sun'}],[{'id':'fr-a1-weather-change','role':'new','description':'follow a simple weather change'}],[('gist','Quel changement de temps observe Camille ?','La pluie devient plus faible et le soleil revient.',[]),('literal_detail','Qui regarde le ciel ?','Son père.',[]),('vocabulary_in_context','Que signifie « pluie » ?','L’eau qui tombe des nuages.',[a['id']]),('vocabulary_in_context','Que signifie « soleil » ici ?','L’astre lumineux visible dans le ciel et sa lumière.',[b['id']]),('cause_effect','Pourquoi la famille prend-elle un parapluie ?','Parce que la pluie commence.',[]),('single_word_definition','Que signifie « pluie » ?','De l’eau qui tombe du ciel en gouttes.',[a['id']]),('grammar_category','Quel type de mot est « soleil » ?','Un nom.',[b['id']]),('contrast','Quand de l’eau tombe des nuages, lequel convient : « pluie » ou « soleil » ?','pluie',[a['id'],b['id']]),('cloze_transfer','Complète : Je prends un parapluie à cause de la _____.','pluie',[a['id']]),('cloze_transfer','Complète : Le _____ brille dans le ciel.','soleil',[b['id']])]))
 text='''Le lendemain matin, la mère de Camille accompagne un ami de la famille jusqu’à l’école. Il fait froid et Camille porte une veste. À midi, elle retrouve son ami Sami dans la cour. Le soleil est plus fort et il fait chaud. Camille enlève sa veste et la met dans son sac. Sa mère lui avait dit que la température pouvait changer pendant la journée. Camille comprend maintenant la différence : quand il fait froid, elle veut plus de chaleur ; quand il fait chaud, elle préfère un vêtement plus léger. Elle regarde donc la température et son activité avant de choisir ce qu’elle porte.'''
 a,b=nt('froid',text,L),nt('chaud',text,L)
 out.append(mk('fr-a1-u10-p02',56,'reinforcement','Froid le matin, chaud à midi','temperature narrative',['personal','educational'],['temperature','school','clothing'],text,[a,b],[rev('mère',P),rev('ami',P)],[{'id':'fr-a1-froid-temperature','role':'new','description':'froid for low temperature'},{'id':'fr-a1-chaud-temperature','role':'new','description':'chaud for high temperature'}],[{'id':'fr-a1-temperature-choice','role':'new','description':'connect temperature to a simple clothing choice'}],[('gist','Comment change la température ?','Il fait froid le matin puis chaud à midi.',[]),('literal_detail','Où Camille met-elle sa veste ?','Dans son sac.',[]),('vocabulary_in_context','Que signifie « froid » ici ?','Une température basse.',[a['id']]),('vocabulary_in_context','Que signifie « chaud » ?','Une température élevée.',[b['id']]),('cause_effect','Pourquoi Camille enlève-t-elle sa veste ?','Parce qu’il fait chaud à midi.',[]),('single_word_definition','Que signifie « froid » ?','Qui a une température basse.',[a['id']]),('grammar_category','Quel type de mot est « chaud » dans « il fait chaud » ?','Un adjectif.',[b['id']]),('contrast','Pour une température élevée, lequel convient : « chaud » ou « froid » ?','chaud',[a['id'],b['id']]),('cloze_transfer','Complète : En hiver, il fait souvent _____.','froid',[a['id']]),('cloze_transfer','Complète : Le thé est très _____.','chaud',[b['id']])]))
 text='''Après l’école, Camille veut acheter un livre simple pour un travail de classe. Elle entre dans une petite librairie près de l’école et regarde trois livres. Le premier a un prix bas, le deuxième est plus joli mais plus cher, et le troisième est trop difficile. Camille choisit le premier. Avant d’acheter, elle demande encore le prix au vendeur pour vérifier. Il lui répond clairement. Camille comprend qu’acheter signifie choisir un article et le payer, tandis que le prix indique combien l’article coûte. Elle garde le reçu dans son sac avec son livre et rentre commencer son travail.'''
 a,b=nt('acheter',text,L),nt('prix',text,L)
 out.append(mk('fr-a1-u10-p03',57,'interleaved','Choisir avant d’acheter','bookshop narrative',['public','educational'],['shopping','book','school'],text,[a,b],[rev('livre',P),rev('école',P)],[{'id':'fr-a1-acheter-purchase','role':'new','description':'acheter for purchasing'},{'id':'fr-a1-prix-cost','role':'new','description':'prix as an item cost'}],[{'id':'fr-a1-price-choice','role':'new','description':'compare simple prices before a purchase'}],[('gist','Pourquoi Camille va-t-elle à la librairie ?','Pour acheter un livre pour un travail de classe.',[]),('literal_detail','Quel livre choisit-elle ?','Le premier.',[]),('vocabulary_in_context','Que signifie « acheter » ?','Obtenir un article en le payant.',[a['id']]),('vocabulary_in_context','Que signifie « prix » ?','La somme demandée pour un article.',[b['id']]),('cause_effect','Pourquoi demande-t-elle encore le prix ?','Pour vérifier le coût avant de payer.',[]),('single_word_definition','Que signifie « prix » ?','Le coût d’un produit ou d’un service.',[b['id']]),('grammar_category','Quel type de mot est « acheter » ?','Un verbe.',[a['id']]),('contrast','Pour parler du coût, lequel convient : « prix » ou « acheter » ?','prix',[a['id'],b['id']]),('cloze_transfer','Complète : Je vais _____ un cahier.','acheter',[a['id']]),('cloze_transfer','Complète : Quel est le _____ de ce livre ?','prix',[b['id']])]))
 text='''Samedi, Camille prépare une activité à la maison. Près de la porte, elle pose une petite table avec les choses nécessaires. Elle doit apporter cinq euros, alors elle met l’argent dans une poche sûre. Elle prend aussi un vêtement léger parce que la salle de l’activité peut être froide. Avant de partir, Camille vérifie la table et la porte une dernière fois : son sac est prêt, l’argent est là et le vêtement est plié au-dessus des livres. Elle comprend que l’argent sert à payer, tandis qu’un vêtement est quelque chose que l’on porte sur le corps. Elle ferme ensuite la porte et part.'''
 a,b=nt('argent',text,L),nt('vêtement',text,L)
 out.append(mk('fr-a1-u10-p04',58,'transfer','Préparer l’argent et un vêtement','activity-preparation narrative',['personal'],['money','clothing','preparation'],text,[a,b],[rev('porte',P),rev('table',P)],[{'id':'fr-a1-argent-money','role':'new','description':'argent as money'},{'id':'fr-a1-vetement-clothing','role':'new','description':'vêtement as an item of clothing'}],[{'id':'fr-a1-needed-items','role':'new','description':'prepare simple needed items before leaving'}],[('gist','Que prépare Camille avant de partir ?','Son argent, un vêtement léger et son sac.',[]),('literal_detail','Combien d’euros doit-elle apporter ?','Cinq euros.',[]),('vocabulary_in_context','Que signifie « argent » ici ?','La monnaie utilisée pour payer.',[a['id']]),('vocabulary_in_context','Que signifie « vêtement » ?','Une pièce que l’on porte sur le corps.',[b['id']]),('cause_effect','Pourquoi prend-elle un vêtement léger ?','Parce que la salle peut être froide.',[]),('single_word_definition','Que signifie « argent » ?','De la monnaie ou des moyens de paiement.',[a['id']]),('grammar_category','Quel type de mot est « vêtement » ?','Un nom.',[b['id']]),('contrast','Pour quelque chose qu’on porte sur le corps, lequel convient : « vêtement » ou « argent » ?','vêtement',[a['id'],b['id']]),('cloze_transfer','Complète : Je garde mon _____ dans une petite poche.','argent',[a['id']]),('cloze_transfer','Complète : Cette veste est un _____.','vêtement',[b['id']])]))
 text='''Après son travail, Camille boit de l’eau puis rejoint sa famille devant un magasin. Il pleut encore et son petit frère a froid. Sa mère décide d’acheter un manteau simple pour lui. Dans le magasin, Camille regarde aussi une chaussure de sport, puis une autre. Elle n’a pas besoin de nouvelle chaussure aujourd’hui, donc elle ne l’achète pas. Son frère essaie le manteau et dit qu’il est chaud et confortable. La famille vérifie le prix avant de payer. En sortant, Camille prend encore un peu d’eau. La pluie continue, mais son frère est maintenant mieux protégé par son manteau.'''
 a,b=nt('manteau',text,L),nt('chaussure',text,L)
 out.append(mk('fr-a1-u10-p05',59,'integration','Un manteau pour la pluie','clothing-shopping narrative',['personal','public'],['clothing','weather','shopping'],text,[a,b],[rev('eau',P),rev('travail',P)],[{'id':'fr-a1-manteau-clothing','role':'new','description':'manteau as an outer coat'},{'id':'fr-a1-chaussure-footwear','role':'new','description':'chaussure as footwear'}],[{'id':'fr-a1-weather-clothing','role':'new','description':'choose clothing for simple weather needs'}],[('gist','Pourquoi la mère achète-t-elle un manteau ?','Parce qu’il pleut, il fait froid et le petit frère a besoin d’être mieux protégé.',[]),('literal_detail','Camille achète-t-elle une chaussure ?','Non.',[]),('vocabulary_in_context','Que signifie « manteau » ?','Un vêtement extérieur qui protège notamment du froid.',[a['id']]),('vocabulary_in_context','Que signifie « chaussure » ?','Un objet porté au pied.',[b['id']]),('cause_effect','Pourquoi Camille ne prend-elle pas de nouvelles chaussures ?','Parce qu’elle n’en a pas besoin aujourd’hui.',[]),('single_word_definition','Que signifie « chaussure » ?','Un objet que l’on porte au pied pour le protéger.',[b['id']]),('grammar_category','Quel type de mot est « manteau » ?','Un nom.',[a['id']]),('contrast','Pour protéger le haut du corps du froid, lequel convient : « manteau » ou « chaussure » ?','manteau',[a['id'],b['id']]),('cloze_transfer','Complète : Je mets mon _____ quand il fait froid.','manteau',[a['id']]),('cloze_transfer','Complète : Je mets une _____ à chaque pied.','chaussure',[b['id']])]))
 text='''À la fin du niveau A1, Camille peut gérer de nombreuses situations familières avec un français simple. Elle regarde la pluie ou le soleil et sait dire s’il fait froid ou chaud. Dans un magasin, elle peut demander un prix, décider d’acheter quelque chose et préparer l’argent nécessaire. Elle sait nommer un vêtement comme un manteau ou une chaussure. Avec les mots des unités précédentes, elle peut parler de sa famille, de son école, de son travail, de son quartier, de sa santé et de ses déplacements. Elle ne sait pas encore tout dire, mais elle peut déjà comprendre des informations simples, poser des questions et expliquer ses besoins essentiels.'''
 reviews=[cur(f,L) for f in NEW_FORMS]
 out.append(mk('fr-a1-u10-p06',60,'checkpoint','Ce que Camille sait faire en français','A1 capstone summary',['personal','public','educational'],['A1 capstone','daily life','communication'],text,[],reviews,[{'id':'fr-a1-u10-capstone','role':'integration','description':'integrate core A1 everyday vocabulary and simple structures'}],[{'id':'fr-a1-u10-practical-functions','role':'integration','description':'summarize practical A1 communicative abilities'}],[('gist','Quelle est l’idée principale du texte ?','Camille peut maintenant comprendre et communiquer dans de nombreuses situations familières avec un français simple.',[]),('literal_detail','Quels deux types de temps sont nommés ?','La pluie et le soleil.',[]),('vocabulary_in_context','Que signifie « prix » ici ?','Le coût d’un article.',[tid(L['prix']['rank'])]),('vocabulary_in_context','Que signifie « manteau » ?','Un vêtement extérieur.',[tid(L['manteau']['rank'])]),('inference','Pourquoi le texte dit-il que Camille « ne sait pas encore tout dire » ?','Parce qu’A1 est un niveau de base : elle gère des situations familières mais son français reste limité.',[]),('single_word_definition','Que signifie « argent » ?','De la monnaie ou un moyen de paiement.',[tid(L['argent']['rank'])]),('grammar_category','Quel type de mot est « acheter » ?','Un verbe.',[tid(L['acheter']['rank'])]),('contrast','Pour le pied, lequel convient : « chaussure » ou « manteau » ?','chaussure',[tid(L['chaussure']['rank']),tid(L['manteau']['rank'])]),('cloze_transfer','Complète : Quand il fait _____, je mets un manteau.','froid',[tid(L['froid']['rank'])]),('summary','Résume en une phrase ce que Camille peut faire à la fin du niveau A1.','Elle peut communiquer simplement sur sa vie quotidienne, ses déplacements, sa santé, la météo, les achats et ses relations.',[])],speed=True))
 return out

def main():
 blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if blob!=EXPECTED_BLOB:raise AssertionError(f'canonical blob drift: {blob} != {EXPECTED_BLOB}')
 rows=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(rows)!=54 or [r['sequence'] for r in rows]!=list(range(1,55)) or rows[-1]['id']!='fr-a1-u09-p06':raise AssertionError('expected exact 54-passage frontier through Unit 09')
 L=lexicon();unit=build(rows,L);V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));old={t['id'] for r in rows for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 if [r['sequence'] for r in unit]!=list(range(55,61)) or len({r['id'] for r in rows+unit})!=60:raise AssertionError('Unit10/A1 continuity failure')
 for r in unit:
  e=sorted(V.iter_errors(r),key=lambda x:list(x.path))
  if e:raise AssertionError(f"{r['id']}: schema {[x.message for x in e[:5]]}")
  if not 90<=r['word_count']<=140:raise AssertionError(f"{r['id']}: word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   s=L.get(t['form'])
   if t['id'] in old or not s or t['source_rank']!=s['rank'] or t['id']!=tid(s['rank']) or count(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: source/exposure/reintroduction drift {t}")
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and count(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if sum(len(r['new_lexical_targets']) for r in unit[:5])!=10 or unit[-1]['new_lexical_targets']!=[]:raise AssertionError('Unit10 lexical-cycle invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in rows+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','unit':10,'appended_passages':6,'a1_passages':60,'word_counts':{r['id']:r['word_count'] for r in unit},'new_targets':[{'form':f,'rank':L[f]['rank'],'id':tid(L[f]['rank'])} for f in NEW_FORMS],'checkpoint_new_targets':0,'questions':60,'answers':60},ensure_ascii=False))
if __name__=='__main__':main()
