#!/usr/bin/env python3
"""Generate Arabic A1 Unit 06: directions and local travel."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
P=ROOT/"reading"/"arabic"/"a1"/"passages.jsonl"; L=ROOT/"reading"/"lexicons"/"arabic.jsonl"
T={135:("طريق","road; way; route",["scenario_resolution"]),267:("نحو","toward; in the direction of",["scenario_resolution"]),170:("سيارة","car",["example_instance"]),317:("يصل","arrives; reaches",["scenario_resolution"]),264:("تحت","under; below",["contrast"]),391:("بعيد","far; distant",["contrast"]),361:("اذهب","go!",["scenario_resolution"]),447:("ينتظر","waits",["behavior_interpretation"]),488:("موقع","location; site; position",["scenario_resolution"]),491:("وسط","middle; center",["category_relation"])}
def qa(items):
 q=[];a=[]
 for i,(t,p,x,ids) in enumerate(items,1):
  z={"id":f"q{i}","type":t,"prompt":p,"answer_id":f"a{i}"};
  if ids:z["target_ids"]=ids
  q.append(z);a.append({"id":f"a{i}","question_id":f"q{i}","answer":x,"explanation":""})
 return q,a
R=[
{"id":"ar-a1-u06-p01","sequence":31,"title":"الطريق إلى المكتبة","passage_type":"instructional","genre":"route description","domains":["public"],"topics":["directions","library","walking"],"text":"تريد ليلى أن تذهب من المدرسة إلى المكتبة وحدها لأول مرة. تسأل المعلمة عن الطريق. تقول المعلمة: اخرجي من باب المدرسة، ثم امشي في الطريق الكبير نحو الحديقة. عند نهاية الحديقة سترين متجرًا صغيرًا. من هناك امشي نحو اليمين قليلًا، والمكتبة أمامك. تكرر ليلى الكلمات حتى تتذكرها. بعد المدرسة تبدأ المشي. ترى الحديقة وتسير نحوها، ثم تجد المتجر. تتوقف لحظة وتنظر أمامها، فترى المكتبة. تقول: الآن أعرف الطريق. لم يكن طويلًا، لكن معرفة الاتجاه جعلت الوصول أسهل.","new":[135,267],"reviews":[{"id":"ar-r106","form":"أين","review_stage":"R3","representation":"other"},{"id":"ar-r131","form":"أمام","review_stage":"R3","representation":"running_text"}],"grammar":[{"id":"ar-a1-route-noun","role":"new","description":"طريق in simple route descriptions"},{"id":"ar-a1-toward","role":"new","description":"نحو + place for direction"}],"discourse":[{"id":"a1-route-order","role":"new","description":"follow ordered route instructions"}],"qa":[("gist","ما الذي تتعلمه ليلى؟","الطريق من المدرسة إلى المكتبة.",None),("literal_detail","ما المكان الذي تمر به قبل المتجر؟","الحديقة.",None),("vocabulary_in_context","ماذا يعني «الطريق» هنا؟","المسار الذي تسلكه ليلى للوصول إلى المكتبة.",["ar-r135"]),("vocabulary_in_context","ماذا تعني «نحو» في «نحو الحديقة»؟","في اتجاه الحديقة.",["ar-r267"]),("sequence","ماذا تفعل ليلى بعد أن تجد المتجر؟","تمشي نحو اليمين قليلًا ثم ترى المكتبة.",None),("single_word_definition","ما معنى «طريق»؟","مسار أو سبيل نسير فيه للوصول إلى مكان.",["ar-r135"]),("single_word_definition","ما معنى «نحو» في الاتجاه؟","باتجاه شيء أو مكان.",["ar-r267"]),("contrast","إذا كنت أسير باتجاه الحديقة، أي عبارة مناسبة: «نحو الحديقة» أم «تحت الحديقة»؟","نحو الحديقة.",["ar-r267"]),("cloze_transfer","أكمل: هذا _____ قصير إلى السوق.","طريق",["ar-r135"]),("cloze_transfer","أكمل: مشيت _____ الباب.","نحو",["ar-r267"])]},
{"id":"ar-a1-u06-p02","sequence":32,"title":"بالسيارة إلى المركز","passage_type":"reinforcement","genre":"micro-story","domains":["personal","public"],"topics":["car","arrival","community center"],"text":"في صباح السبت تذهب ليلى مع أبيها إلى مركز قريب. المركز ليس بعيدًا جدًا، لكنهما يذهبان بالسيارة لأن معهما أشياء كثيرة. يضع الأب الحقائب في السيارة، ثم تجلس ليلى بجانبه. تقول: متى نصل؟ يقول: بعد عشر دقائق تقريبًا. تتحرك السيارة في طريق هادئ، ثم تتوقف عند إشارة. بعد قليل ترى ليلى بناء المركز وتقول: أظن أننا نصل الآن. يبتسم أبوها ويقول: نعم، وصلنا. عندما تصل السيارة إلى الموقف ينزلان ويحملان الحقائب إلى الداخل. تقول ليلى: كان الطريق قصيرًا، ووصلنا في الوقت.","new":[170,317],"reviews":[{"id":"ar-r135","form":"طريق","review_stage":"R1","representation":"running_text"},{"id":"ar-r267","form":"نحو","review_stage":"R1","representation":"other"}],"grammar":[{"id":"ar-a1-car","role":"new","description":"سيارة as everyday transport noun"},{"id":"ar-a1-arrive","role":"new","description":"يصل إلى + place"}],"discourse":[{"id":"a1-trip-arrival","role":"new","description":"track departure, movement, and arrival"}],"qa":[("literal_detail","لماذا يذهبان بالسيارة؟","لأن معهما أشياء كثيرة.",None),("literal_detail","كم يستغرق الطريق تقريبًا؟","عشر دقائق.",None),("vocabulary_in_context","ماذا تعني «السيارة»؟","المركبة التي يركبانها إلى المركز.",["ar-r170"]),("vocabulary_in_context","ماذا يعني «نصل» في «متى نصل؟»؟","متى نبلغ المكان المقصود.",["ar-r317"]),("sequence","ماذا يفعلان عندما تصل السيارة إلى الموقف؟","ينزلان ويحملان الحقائب إلى الداخل.",None),("single_word_definition","ما معنى «سيارة»؟","مركبة تسير على الطريق وتنقل الناس.",["ar-r170"]),("single_word_definition","ما معنى «يصل»؟","يبلغ المكان المقصود.",["ar-r317"]),("contrast","أيهما يدل على الوصول: «يصل» أم «يبدأ»؟","يصل.",["ar-r317"]),("cloze_transfer","أكمل: أبي يقود _____ إلى العمل.","السيارة",["ar-r170"]),("cloze_transfer","أكمل: القطار _____ إلى المحطة في الثامنة.","يصل",["ar-r317"])]},
{"id":"ar-a1-u06-p03","sequence":33,"title":"الممر تحت الجسر","passage_type":"interleaved","genre":"route micro-story","domains":["public"],"topics":["walking","distance","landmarks"],"text":"تمشي ليلى مع مريم إلى ملعب صغير في الحي. تقول مريم: الملعب بعيد قليلًا، لكن الطريق واضح. تسيران حتى تصلان إلى جسر. تقول مريم: لا نصعد إلى الجسر؛ الممر الذي نريده تحت الجسر. تنظر ليلى وترى الناس يمشون تحته. تعبران الممر ثم تريان مدرسة على اليمين. تسأل ليلى: هل الملعب ما زال بعيدًا؟ تقول مريم: لا، أصبح قريبًا. بعد خمس دقائق تصلان إليه. تقول ليلى: الآن أفهم. عندما يكون المكان بعيدًا نحتاج إلى وقت أكثر، وعندما نمر تحت الجسر نكون في الطريق الصحيح.","new":[264,391],"reviews":[{"id":"ar-r317","form":"يصل","review_stage":"R1","representation":"running_text"},{"id":"ar-r135","form":"طريق","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-under","role":"new","description":"تحت + noun for location"},{"id":"ar-a1-distance","role":"new","description":"بعيد versus قريب"}],"discourse":[{"id":"a1-landmark-route","role":"new","description":"use landmarks and distance in route comprehension"}],"qa":[("literal_detail","إلى أين تذهب ليلى ومريم؟","إلى ملعب صغير.",None),("literal_detail","أين الممر الذي تسلكانه؟","تحت الجسر.",["ar-r264"]),("vocabulary_in_context","ماذا تعني «تحت» في «تحت الجسر»؟","في المكان الأسفل من الجسر.",["ar-r264"]),("vocabulary_in_context","ماذا يعني «بعيد»؟","أن المكان يحتاج إلى مسافة أكبر للوصول إليه.",["ar-r391"]),("sequence","ماذا تريان بعد عبور الممر؟","مدرسة على اليمين.",None),("single_word_definition","ما معنى «تحت»؟","في مكان أسفل شيء آخر.",["ar-r264"]),("single_word_definition","ما معنى «بعيد»؟","غير قريب؛ تفصله مسافة كبيرة نسبيًا.",["ar-r391"]),("contrast","أيهما عكس «بعيد»: «قريب» أم «طويل»؟","قريب.",["ar-r391"]),("cloze_transfer","أكمل: الحقيبة _____ الكرسي.","تحت",["ar-r264"]),("cloze_transfer","أكمل: المدرسة ليست قريبة؛ هي _____.","بعيدة",["ar-r391"])]},
{"id":"ar-a1-u06-p04","sequence":34,"title":"انتظر عند الباب","passage_type":"transfer","genre":"short instruction scene","domains":["public","personal"],"topics":["meeting","waiting","directions"],"text":"تتفق ليلى مع هدى على اللقاء عند المركز. ترسل هدى رسالة: «اذهبي إلى الباب الكبير وانتظريني هناك. أنا قادمة بعد قليل.» تصل ليلى أولًا، لكنها ترى بابين. تسأل رجلًا عند المدخل: من فضلك، أي باب هو الكبير؟ يشير إلى الباب الذي أمام الشارع. تذهب ليلى إليه وتنتظر. بعد خمس دقائق لا ترى هدى، فتقرأ الرسالة مرة أخرى. تقرر أن تنتظر قليلًا آخر بدل أن تتحرك إلى مكان جديد. ثم ترى هدى قادمة نحوها. تقول هدى: شكرًا لأنك انتظرت. تقول ليلى: عندما تقولين لي أين أذهب وأين أنتظر، يكون اللقاء أسهل.","new":[361,447],"reviews":[{"id":"ar-r264","form":"تحت","review_stage":"R1","representation":"other"},{"id":"ar-r391","form":"بعيد","review_stage":"R1","representation":"other"},{"id":"ar-r106","form":"أين","review_stage":"R3","representation":"running_text"}],"grammar":[{"id":"ar-a1-go-imperative","role":"new","description":"اذهب/اذهبي as simple direction"},{"id":"ar-a1-wait","role":"new","description":"ينتظر at a meeting point"}],"discourse":[{"id":"a1-meeting-instruction","role":"new","description":"follow a place instruction and wait for another person"}],"qa":[("literal_detail","أين تطلب هدى من ليلى أن تنتظر؟","عند الباب الكبير.",None),("literal_detail","لماذا تسأل ليلى رجلًا عند المدخل؟","لأنها ترى بابين ولا تعرف أيهما الباب الكبير.",None),("vocabulary_in_context","ماذا يعني الأمر «اذهبي»؟","انتقلي أو سيري إلى المكان المطلوب.",["ar-r361"]),("vocabulary_in_context","ماذا يعني «تنتظر»؟","تبقى في المكان حتى يأتي الشخص أو يحين الوقت.",["ar-r447"]),("sequence","ماذا تفعل ليلى بعد أن تعرف الباب الكبير؟","تذهب إليه وتنتظر هدى.",None),("single_word_definition","ما معنى «اذهب»؟","تحرك إلى مكان آخر.",["ar-r361"]),("single_word_definition","ما معنى «ينتظر»؟","يبقى إلى أن يأتي شخص أو يحدث شيء.",["ar-r447"]),("contrast","إذا طلب منك شخص البقاء حتى يصل، هل «اذهب» أم «انتظر» أنسب؟","انتظر.",["ar-r361","ar-r447"]),("cloze_transfer","أكمل الأمر: _____ إلى الصف الآن.","اذهب",["ar-r361"]),("cloze_transfer","أكمل: سامر _____ الحافلة عند الباب.","ينتظر",["ar-r447"])]},
{"id":"ar-a1-u06-p05","sequence":35,"title":"في وسط الحي","passage_type":"checkpoint","genre":"simple map description","domains":["public"],"topics":["map","neighborhood","location"],"text":"في الصف يرسم المعلم خريطة بسيطة للحي. يضع دائرة في موقع المدرسة، ثم مربعًا في موقع المكتبة. يقول: الحديقة في وسط الخريطة، والمدرسة إلى يسارها، والمكتبة إلى يمينها. تنظر ليلى إلى الرسم وتسأل: أين موقع السوق؟ يرسم المعلم نجمة تحت المكتبة ويقول: هنا. ثم يسأل الطلاب عن مواقع أخرى. تقول ليلى: إذا عرفت موقع المكان على الخريطة، يمكنني أن أفهم الطريق إليه. بعد المدرسة تنظر إلى الحي الحقيقي وتلاحظ أن الحديقة فعلًا في وسط عدة أماكن تعرفها. تقول لمريم: الخريطة صغيرة، لكنها تساعدني على رؤية موقع كل مكان بالنسبة إلى الأماكن الأخرى.","new":[488,491],"reviews":[{"id":"ar-r361","form":"اذهب","review_stage":"R1","representation":"other"},{"id":"ar-r447","form":"ينتظر","review_stage":"R1","representation":"other"},{"id":"ar-r135","form":"طريق","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-location-noun","role":"new","description":"موقع for location on a map"},{"id":"ar-a1-middle","role":"new","description":"وسط for central position"}],"discourse":[{"id":"a1-map-reading","role":"integration","description":"relate map symbols to real locations"}],"qa":[("gist","ماذا يتعلم الطلاب من الخريطة؟","مواقع أماكن الحي وعلاقتها ببعضها.",None),("literal_detail","أين الحديقة في الخريطة؟","في وسط الخريطة.",["ar-r491"]),("vocabulary_in_context","ماذا يعني «موقع المدرسة»؟","المكان الذي تقع فيه المدرسة على الخريطة أو في الحي.",["ar-r488"]),("vocabulary_in_context","ماذا يعني «وسط» في «وسط الخريطة»؟","الجزء المركزي بين الجوانب.",["ar-r491"]),("cause_effect","كيف تساعد الخريطة ليلى؟","تساعدها على فهم الطريق وموقع كل مكان بالنسبة إلى غيره.",None),("single_word_definition","ما معنى «موقع»؟","مكان وجود شيء أو موضعه.",["ar-r488"]),("single_word_definition","ما معنى «وسط»؟","الجزء الذي يقع في المنتصف.",["ar-r491"]),("contrast","أيهما يعني المركز: «وسط» أم «بعيد»؟","وسط.",["ar-r491","ar-r391"]),("cloze_transfer","أكمل: ما _____ المدرسة على هذه الخريطة؟","موقع",["ar-r488"]),("cloze_transfer","أكمل: الشجرة في _____ الحديقة.","وسط",["ar-r491"])]},
{"id":"ar-a1-u06-p06","sequence":36,"title":"طريق واضح","passage_type":"fluency","genre":"connected route narrative","domains":["public"],"topics":["directions","travel","review"],"text":"تستطيع ليلى الآن أن تفهم طريقًا بسيطًا في حيها. إذا أرادت مكانًا جديدًا تنظر إلى موقعه وتسأل أين هو. قد تمشي نحو الحديقة أو السوق، وقد تركب السيارة إذا كان المكان بعيدًا أو كانت معها أشياء كثيرة. عندما ترى جسرًا تعرف أن الطريق قد يمر تحته، وعندما تصل إلى نقطة واضحة تنظر إلى ما حولها. إذا قالت لها صديقتها: اذهبي إلى الباب وانتظري هناك، تبقى في الموقع حتى تصل صديقتها. وتستطيع الخريطة أن تبين لها ما يوجد في وسط الحي وما يقع على الجوانب. بهذه الكلمات تعرف ليلى كيف تبدأ الطريق، وكيف تستمر فيه، وكيف تعرف أنها وصلت.","new":[],"reviews":[{"id":"ar-r135","form":"طريق","review_stage":"R2","representation":"running_text"},{"id":"ar-r267","form":"نحو","review_stage":"R2","representation":"running_text"},{"id":"ar-r170","form":"سيارة","review_stage":"R2","representation":"running_text"},{"id":"ar-r317","form":"يصل","review_stage":"R2","representation":"running_text"},{"id":"ar-r264","form":"تحت","review_stage":"R2","representation":"running_text"},{"id":"ar-r391","form":"بعيد","review_stage":"R2","representation":"running_text"},{"id":"ar-r361","form":"اذهب","review_stage":"R2","representation":"running_text"},{"id":"ar-r447","form":"ينتظر","review_stage":"R2","representation":"running_text"},{"id":"ar-r488","form":"موقع","review_stage":"R1","representation":"running_text"},{"id":"ar-r491","form":"وسط","review_stage":"R1","representation":"running_text"}],"grammar":[{"id":"ar-a1-u06-cumulative","role":"integration","description":"recycle route, direction, distance, waiting, and map location"}],"discourse":[{"id":"a1-route-fluency","role":"integration","description":"high-coverage cumulative route reading"}],"qa":[("gist","ما الفكرة الرئيسية في النص؟","ليلى تستطيع فهم الطرق البسيطة والوصول إلى أماكن الحي.",None),("literal_detail","متى قد تركب ليلى السيارة؟","إذا كان المكان بعيدًا أو كانت معها أشياء كثيرة.",["ar-r170","ar-r391"]),("literal_detail","ماذا تفعل إذا طلبت منها صديقتها الانتظار؟","تبقى في الموقع حتى تصل صديقتها.",["ar-r447","ar-r488"]),("reference_resolution","إلى ماذا يعود «تحته» عند ذكر الجسر؟","إلى الجسر.",["ar-r264"]),("summary","لخص طريقة ليلى في الوصول إلى مكان جديد.","تعرف موقعه واتجاهه، تتبع الطريق والعلامات، ثم تعرف متى وصلت.",None),("single_word_definition","ما معنى «نحو»؟","باتجاه.",["ar-r267"]),("single_word_definition","ما معنى «وسط»؟","المنتصف أو المركز.",["ar-r491"]),("contrast","أيهما يدل على الوصول: «يصل» أم «ينتظر»؟","يصل.",["ar-r317","ar-r447"]),("grammar_function","ماذا يحدد «تحت»؟","موقعًا أسفل شيء آخر.",["ar-r264"]),("contrast","أيهما مسافة كبيرة نسبيًا: «بعيد» أم «قريب»؟","بعيد.",["ar-r391"])]}
]
def lex():
 d={}
 for x in L.read_text(encoding="utf-8").splitlines():
  if x.strip():r=json.loads(x);d[r["rank"]]=r
 return d
def tar(n,text,d):
 f,s,c=T[n];r=d[n];return {"id":f"ar-r{n}","form":f,"lemma":f,"part_of_speech":r.get("part_of_speech_source"),"intended_sense":s,"register":"contemporary standard","variety":"MSA","context_strategy":c,"first_introduced":True,"exposures_in_text":max(1,text.count(f)),"source_lexicon":r.get("source_file"),"source_rank":n,"beyond_base":False}
def build(x,d):
 qs,ans=qa(x["qa"]);text=x["text"]
 return {"id":x["id"],"language":"ar","cefr":"A1","unit":6,"sequence":x["sequence"],"revision":1,"title":x["title"],"passage_type":x["passage_type"],"genre":x["genre"],"domains":x["domains"],"topics":x["topics"],"text":text,"word_count":len(text.split()),"sentence_count":max(1,len(re.findall(r"[.!؟](?:\s|$)",text))),"estimated_known_token_coverage":0,"new_lexical_targets":[tar(n,text,d) for n in x["new"]],"review_lexical_targets":x["reviews"],"grammar_targets":x["grammar"],"discourse_targets":x["discourse"],"questions":qs,"answer_key":ans,"speed_training":{"timed":x["passage_type"]=="fluency","benchmark_eligible":False,"comprehension_gate":0.8,"new_word_policy":"none" if x["passage_type"]=="fluency" else "controlled","notes":"Generation-stage passage; formal fluency/coverage decision deferred to final audit."},"quality":{"status":"draft","linguistic_review":"pending","pedagogical_review":"pending","coverage_check":"pending","answer_key_check":"pending","schema_check":"pending","fact_check":"not_required","notes":["High-quality generation-stage draft; formal audits deferred to the final multi-pass review phase."]},"paired_text_group":None,"prerequisites":[],"difficulty_notes_internal":None,"reader_tags":["unit_role:"+x["passage_type"],"generation_batch"],"complexity_profile":{"mean_sentence_length":None,"median_sentence_length":None,"clause_count":None,"subordination_count":None,"coordination_count":None,"connective_diversity":None,"lexical_diversity":None,"reference_chain_max_distance":None,"multiword_expression_count":None,"morphology_notes":"A1 generation-stage draft; transparent contemporary MSA.","inference_depth":"local"}}
def main():
 old=[json.loads(z) for z in P.read_text(encoding="utf-8").splitlines() if z.strip()];old=[x for x in old if x.get("unit")!=6];d=lex();new=[build(x,d) for x in R]
 if len(new)!=6 or any(len(x["questions"])!=10 or len(x["answer_key"])!=10 for x in new):raise SystemExit("Unit06 generation contract failed")
 rows=sorted(old+new,key=lambda x:(x.get("unit",0),x.get("sequence",0)));P.write_text("".join(json.dumps(x,ensure_ascii=False,sort_keys=True)+"\n" for x in rows),encoding="utf-8")
 print("generated Arabic A1 Unit 06: six passages, sixty questions, sixty answers")
if __name__=="__main__":main()
