#!/usr/bin/env python3
"""Generate Arabic C2 Unit 08: history and contested explanation using a fictional archive."""
from __future__ import annotations
import json,re,unicodedata
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'reading/arabic/c2/passages.jsonl';LEX=ROOT/'reading/lexicons/arabic.jsonl';DI=re.compile(r'[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]')
def n(s):return DI.sub('',unicodedata.normalize('NFC',str(s or '')).replace('ـ','').strip())
def lx():
 d={}
 for l in LEX.read_text(encoding='utf-8').splitlines():
  if l.strip():r=json.loads(l);d.setdefault(n(r.get('form','')),r)
 return d
def seen():
 z={}
 for lv in ('a1','a2','b1','b2','c1','c2'):
  p=ROOT/f'reading/arabic/{lv}/passages.jsonl'
  if p.exists():
   for l in p.read_text(encoding='utf-8').splitlines():
    if l.strip():
     r=json.loads(l)
     if r.get('cefr')=='C2' and r.get('unit')==8:continue
     for t in r.get('new_lexical_targets',[]):z.setdefault(n(t.get('form','')),[]).append(r.get('id'))
 return z
S={'طبعة':'edition','زعم':'claim; allege','عينة':'sample','ملموس':'tangible','ترميم':'restoration','شبيه':'similar; resembling','مرصد':'observation post; observatory','مانع':'obstacle; impediment','مسبوق':'preceded; having precedent','قطب':'axis; central pole'}
def tr(f,text,d):
 r=d[n(f)];return {'id':f"ar-r{r['rank']}",'form':f,'lemma':f,'part_of_speech':r.get('part_of_speech_source'),'intended_sense':S[f],'register':'historiographical/contemporary MSA','variety':'MSA','context_strategy':['source_critique','causal_comparison','historiographical_reconstruction'],'first_introduced':True,'exposures_in_text':max(1,text.count(f)),'source_lexicon':r.get('source_file'),'source_rank':r['rank'],'beyond_base':False}
def qs(pid,a,b):
 prompts=[('gist','ما القضية المنهجية المركزية؟','أن تفسير الماضي يحتاج إلى فحص كيفية صنع الأدلة وحدودها.'),('literal_detail','ما نوع الدليل الذي يفحصه النص؟','مصادر أو آثار من الأرشيف الخيالي.'),('inference','لماذا لا يكفي المصدر منفردًا؟','لأنه قد يعكس بقاءً أو اختيارًا أو تحريرًا أو وصولًا غير متساوٍ.'),('argument_relation','ما وظيفة المقارنة؟','اختبار تفسيرين أو أكثر أمام الأدلة نفسها.'),('main_claim','ما معيار التفسير الأقوى؟','أن يشرح الأدلة وحدودها بأقل افتراضات غير مدعومة.'),('contrast','ما الفرق بين وجود الدليل وسبب وجوده؟','الأول يصف ما بقي، والثاني يفسر عملية البقاء أو الاختيار.'),('inference','لماذا تهم الأدلة المضادة؟','لأنها تختبر ما إذا كان التفسير انتقائيًا.'),('summary','كيف يعالج النص الخلاف؟','يعيد بناء سلسلة المصدر ثم يقارن القدرة التفسيرية.'),('single_word_definition',f'ما معنى «{a}» في النص؟',S[a]),('single_word_definition',f'ما معنى «{b}» في النص؟',S[b])]
 q=[];ans=[]
 for i,(typ,p,x) in enumerate(prompts,1):
  q.append({'id':f'q{i}','type':typ,'prompt':p,'answer_id':f'a{i}','target_ids':[]});ans.append({'id':f'a{i}','question_id':f'q{i}','answer':x,'explanation':''})
 return q,ans
P=[
('p01','الطبعة اللاحقة ليست نافذة شفافة على النص الأول',['طبعة','زعم'],'وجد المؤرخون في أرشيف خيالي طبعتين من مذكرات موظف. الطبعة الأولى قصيرة، والثانية أضيف إليها بعد عشرين عامًا فصل يزعم أن قرارًا قديمًا كان متوقعًا منذ البداية. تعامل قارئ مع الإضافة كدليل مباشر على نية الموظف وقت الحدث. اعترضت المؤرخة: الطبعة اللاحقة دليل على ما أراد المؤلف قوله لاحقًا أيضًا، وربما تأثر بما عرفه بعد النتائج. قارنت العبارات المشتركة بين الطبعتين، وحددت المواضع المضافة، ثم سألت أي ادعاء يمكن دعمه من النسخة المبكرة وأي ادعاء يعتمد على الذاكرة اللاحقة. لم ترفض الفصل الجديد؛ استخدمته مصدرًا عن إعادة تفسير الماضي. وهكذا تغير السؤال من «هل المؤلف صادق؟» إلى «في أي زمن صيغ هذا الزعم، وما الذي كان متاحًا لصاحبه حين صاغه؟». الخلاف التاريخي لا يحل بحذف المصدر المتأخر، بل بوضعه في طبقته الزمنية الصحيحة.'),
('p02','العينة الباقية قد تجعل الاستثناء يبدو قاعدة',['عينة','ملموس'],'احتفظ مخزن خيالي بمئة رسالة تجارية، لكن معظمها جاءت من ثلاث شركات كبيرة لأن أوراقها خزنت في مبانٍ حجرية. وجد الباحث في العينة أن العقود مكتوبة بصيغة رسمية جدًا، فاستنتج أن التجارة كلها اتبعت هذا الأسلوب. سألت زميلته عن الشركات الصغيرة التي لم يبق منها أثر ملموس مماثل. غيابها من الأرشيف قد يعني أنها لم تكتب، وقد يعني ببساطة أن موادها لم تحفظ. بحث الفريق عن سجلات ضرائب وإشارات في رسائل الشركات الكبيرة، فظهرت أسماء تجار يستخدمون ترتيبات أقل رسمية. لم يعد الاستنتاج «كل التجارة رسمية»، بل «العينة المحفوظة تميل إلى المؤسسات الأقدر على الحفظ». هنا يصبح تاريخ الأرشيف جزءًا من تاريخ الظاهرة؛ ما بقي ليس اختيارًا عشوائيًا من الماضي.'),
('p03','الترميم قد يصنع أثرًا شبيهًا بما نحاول تفسيره',['ترميم','شبيه'],'عثر فريق على قاعة قديمة أُعيد ترميمها مرتين. لاحظ باحث زخارف متشابهة على الجدار والسقف، واستدل بها على أن البنائين الأوائل أرادوا توحيد المكان بصريًا. كشفت سجلات الصيانة أن زخارف السقف أضيفت في ترميم متأخر لتصبح شبيهة بالجدار. لو عوملت كل العناصر بوصفها من زمن واحد، يصبح قرار المرمم اللاحق دليلًا مزيفًا على قصد سابق. لم يحذف الباحث السقف من الدراسة؛ صار يسأل لماذا اختار المرممون محاكاة الجدار، وما الصورة التي كانوا يريدون صنعها عن الماضي. الترميم يحفظ أثرًا ويعيد تشكيله في الوقت نفسه، ولذلك يحتاج المؤرخ إلى فصل طبقات المادة قبل تحويل التشابه إلى حجة عن الأصل.'),
('p04','المرصد الذي يحدد ما يمكن رؤيته',['مرصد','مانع'],'في مدينة خيالية كتب الحراس يوميات من مرصد فوق البوابة. اعتمد تاريخ قديم على هذه اليوميات ليقول إن الاضطرابات كانت تأتي دائمًا من الطريق الشرقي. لكن موضع المرصد نفسه كان يطل على الشرق بوضوح ويحجبه جدار عن الحي الغربي؛ الجدار مانع بصري ومصدر تحيز في التسجيل. بحثت مؤرخة في شكاوى الأسواق وسجلات إصلاح الأبواب، فوجدت اضطرابات غربًا لم تظهر في يوميات الحراس. لا يعني ذلك أن اليوميات خاطئة؛ هي دقيقة في مجال رؤيتها. الخطأ هو تحويل مجال الرؤية إلى حدود للواقع. كل مصدر يملك موقعًا مؤسسيًا وماديًا: من يرى، من يكتب، ولأي غرض، وما الذي يمنعه التصميم أو الخوف أو الروتين من تسجيله؟'),
('p05','الحدث المسبوق لا يصبح قطب السرد تلقائيًا',['مسبوق','قطب'],'رتب مؤرخ خيالي أزمة طويلة حول يوم واحد أُعلن فيه قرار مشهور، وجعل ذلك اليوم قطب تفسيره. قالت باحثة أخرى إن القرار كان مسبوقًا بأشهر من نقص الموارد وتغير التحالفات، وإن بعض المناطق بدأت التكيف قبل الإعلان. لا يلغي ذلك أهمية اليوم؛ قد يكون لحظة تنسيق أو رمزًا جمع أحداثًا متفرقة. لكنها فرقت بين المركز السردي والسبب السببي. الحدث الذي يسهل تأريخه قد يصبح محور الكتاب لأنه واضح الوثيقة، بينما تعمل أسباب أبطأ بلا تاريخ واحد. أعادت الباحثة رسم خطين: خطًا لما تغير تدريجيًا، وخطًا للقرارات المعلنة. عند تقاطعهما ظهر أن الإعلان سرّع مسارًا قائمًا بدل أن يخلقه من الصفر. التاريخ المتنازع عليه يحتاج إلى اختبار ما إذا كان قطب السرد هو أيضًا قطب الآلية.'),
('p06','الماضي يصلنا عبر طبقات لا عبر نافذة واحدة',[],'في ختام الوحدة جمع المؤرخون خمسة تحذيرات. الطبعة المتأخرة قد تكشف إعادة تفسير بقدر ما تكشف الحدث، والزعم يحتاج إلى زمن صياغته. والعينة المحفوظة ليست عشوائية، لذلك يجب فهم لماذا بقي الأثر الملموس ولم يَبق غيره. ويمكن للترميم أن يجعل جزءًا متأخرًا شبيهًا بالأصل، فيتحول عمل الحفظ نفسه إلى طبقة تاريخية. كما أن المرصد يحدد مجال الرؤية، وقد يصبح المانع المادي تحيزًا في السجل. وأخيرًا قد يكون حدث مسبوق بعمليات طويلة قطب السرد لأنه سهل التأريخ، لا لأنه السبب الوحيد. لا يقود هذا إلى الشك في كل مصدر. بل إلى تحويل المصدر من «قطعة من الماضي» إلى أثر له تاريخ إنتاج وبقاء واستخدام. التفسير الأقوى يشرح الحدث ويشرح أيضًا لماذا وصلت إلينا الأدلة بهذه الصورة.')]
def build(i,t,d):
 pid,title,forms,text=t;targets=[tr(f,text,d) for f in forms];q,a=qs(pid,forms[0],forms[1]) if forms else qs(pid,'طبعة','زعم');
 if not forms:
  q=q[:8]+[{'id':'q9','type':'inference','prompt':'ما المهارة العامة؟','answer_id':'a9'},{'id':'q10','type':'summary','prompt':'ما الذي يجمع التحذيرات الخمسة؟','answer_id':'a10'}];a=a[:8]+[{'id':'a9','question_id':'q9','answer':'تفسير الحدث وتاريخ إنتاج الأدلة وبقائها معًا.','explanation':''},{'id':'a10','question_id':'q10','answer':'كلها ترفض التعامل مع المصدر كنافذة شفافة منفصلة عن شروط إنتاجه.','explanation':''}]
 ids={x['form']:x['id'] for x in targets}
 for x in q:
  x['target_ids']=[ids[f] for f in forms if f in x['prompt']]
 return {'id':f'ar-c2-u08-{pid}','language':'ar','cefr':'C2','unit':8,'sequence':36+i,'revision':1,'title':title,'text':text,'passage_type':['instructional','reinforcement','interleaved','transfer','integration','fluency'][i-1],'genre':['historiographical comparison','source critique','source critique','historiographical comparison','synthesis','C2 historical synthesis'][i-1],'domains':['history','historiography'],'topics':['sources','contested explanation'],'new_lexical_targets':targets,'review_lexical_targets':[] if forms else [{'id':f"ar-r{d[n(f)]['rank']}",'form':f,'review_stage':'R2','representation':'running_text'} for f in S],'grammar_targets':[{'id':f'ar-c2-u08-{pid}-g','role':'integration' if not forms else 'new','description':'فصل الحدث عن تاريخ إنتاج المصدر وبقائه واستخدامه'}],'discourse_targets':[{'id':f'c2-u08-{pid}-d','role':'integration' if not forms else 'new','description':'reconstruct contested historical explanations by modeling source production and survival'}],'questions':q,'answer_key':a,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!؟](?:\s|$)',text))),'estimated_known_token_coverage':0,'paired_text_group':None,'prerequisites':['Arabic A1-C1 generation corpus','Arabic C2 Units 01-07 generation corpus'],'difficulty_notes_internal':'C2 Unit 08 generation draft: historiographical comparison and source critique using fictional archives.','speed_training':{'timed':i==6,'benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'none' if i==6 else 'controlled','notes':'generation stage; formal audit deferred'},'quality':{'status':'draft','linguistic_review':'pending','pedagogical_review':'pending','coverage_check':'pending','answer_key_check':'pending','schema_check':'pending','fact_check':'not_required','notes':['All archives, events, editions, buildings, and institutions are fictional curriculum material.']},'reader_tags':['unit_role:'+['instructional','reinforcement','interleaved','transfer','integration','fluency'][i-1],'generation_batch','c2'],'complexity_profile':{'mean_sentence_length':None,'median_sentence_length':None,'clause_count':None,'subordination_count':None,'coordination_count':None,'connective_diversity':None,'lexical_diversity':None,'reference_chain_max_distance':None,'multiword_expression_count':None,'morphology_notes':'C2 historiographical MSA.','inference_depth':'cross_paragraph_argument_reconstruction'}}
def main():
 d=lx();s=seen();missing=[f for f in S if n(f) not in d]
 if missing:raise KeyError(missing)
 col={f:s[n(f)] for f in S if n(f) in s}
 if col:raise RuntimeError('C2 Unit 08 new-target collision: '+json.dumps(col,ensure_ascii=False,sort_keys=True))
 rows=[json.loads(l) for l in OUT.read_text(encoding='utf-8').splitlines() if l.strip()] if OUT.exists() else [];rows=[r for r in rows if not(r.get('cefr')=='C2' and r.get('unit')==8)];rows.extend(build(i,t,d) for i,t in enumerate(P,1));rows.sort(key=lambda r:r.get('sequence',0));OUT.write_text('\n'.join(json.dumps(r,ensure_ascii=False,sort_keys=True) for r in rows)+'\n',encoding='utf-8');print(f'wrote C2 Unit 08; total rows={len(rows)}; collisions=0')
if __name__=='__main__':main()
