#!/usr/bin/env python3
"""Append French B1 Unit 08 (sequences 43-48) with full fail-closed guards."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit07 as prev
base=prev.base
REPO=Path(__file__).resolve().parents[2]
A1=REPO/'reading/french/a1/passages.jsonl';A2=REPO/'reading/french/a2/passages.jsonl';CANON=REPO/'reading/french/b1/passages.jsonl';SCHEMA=REPO/'reading/schema/passage.schema.json'
EXPECTED_A1_BLOB='0493a2fa13e51b5997db05e91cdea4d8dc5e647b';EXPECTED_A2_BLOB='d0a80b8866071f426019aa0ad143e1d270dba4de';EXPECTED_B1_BLOB='cbe6620a17908c7ff1ea3f005536ae6d50e695c2'
FORMS=('régler','contrôle','capable','diriger','traverser','selon','crier','sentiment','remarquer','couvrir','trou','forme','échapper','souffrir','compris')

def qset(new,review,topic):
 a,b,c=new;x,y,z=review
 return [
 ('gist',f'Quelle méthode principale ressort de cette situation de {topic} ?',f'Observer le problème, vérifier les contraintes puis utiliser {a}, {b} et {c} de façon contrôlée.',[a,b,c]),
 ('literal_detail',f'Quel élément concret doit être vérifié avant la décision ?','Un détail observable est vérifié avant de modifier le plan.',[a]),
 ('cause_effect',f'Pourquoi l’équipe évite-t-elle une action immédiate ?','Parce qu’une action trop rapide pourrait masquer la cause réelle ou créer une nouvelle difficulté.',[b]),
 ('vocabulary_in_context',f'Comment le texte emploie-t-il « {a} » ?','Le mot décrit l’action ou l’idée précise utilisée pour résoudre le problème.',[a]),
 ('vocabulary_in_context',f'Comment le texte emploie-t-il « {b} » ?','Le mot est relié à une étape de vérification ou d’interprétation dans le contexte.',[b]),
 ('inference','Que peut-on déduire de la comparaison entre les deux options ?','La meilleure option est celle qui respecte les preuves et les contraintes plutôt que celle qui paraît la plus simple.',[c]),
 ('motive','Pourquoi Camille conserve-t-elle une trace de la décision ?','Pour pouvoir expliquer ensuite ce qui a été observé et pourquoi la solution a été choisie.',[x]),
 ('grammar_in_context',f'Quel rôle joue « {c} » dans le raisonnement ?','Il précise une condition, une capacité ou un résultat nécessaire à la décision.',[c]),
 ('cloze_transfer',f'Complète avec le mot approprié : l’équipe doit _____ avant de conclure. ',a,[a]),
 ('summary','Résume le passage en une phrase. ',f'Camille relie {a}, {b} et {c} aux acquis {x}, {y} et {z} pour prendre une décision vérifiable.',[a,b,c,x,y,z])]

DATA=[
('fr-b1-u08-p01',43,'instructional','Régler un appareil après un contrôle','equipment calibration report',['professional','educational'],['equipment','calibration'],['régler','contrôle','capable'],['entier','doucement','charger'],[
"Après une journée entière d’enregistrement, un microphone donne un son beaucoup plus faible que les autres. Camille ne veut pas simplement augmenter le volume au hasard. Elle commence par un contrôle des câbles, de la batterie et des réglages. L’appareil est encore capable d’enregistrer, mais le niveau varie selon la position du connecteur. Elle pose le matériel doucement sur une table et le laisse charger pendant qu’elle compare les autres microphones.",
"Le technicien lui montre ensuite comment régler le niveau d’entrée avec une source sonore stable. Un bon contrôle ne consiste pas à obtenir le nombre le plus élevé : il vérifie si le signal reste régulier dans plusieurs essais. Camille change un seul paramètre à la fois. Cette méthode permet de savoir quel réglage produit réellement l’amélioration. Le microphone est capable de retrouver un niveau normal sans remplacer immédiatement toutes ses pièces.",
"Avant de remettre l’appareil en service, l’équipe réalise un dernier contrôle sur un enregistrement entier de quelques minutes. Camille comprend que régler signifie ajuster en fonction d’un résultat observé, et non modifier jusqu’à ce que le problème semble disparaître. Être capable de fonctionner pendant quelques secondes ne suffit pas non plus : le test doit montrer une stabilité utile pour le travail prévu. Elle range ensuite le câble doucement et note le réglage choisi, afin que la prochaine personne puisse reproduire le contrôle au lieu de recommencer depuis zéro."
]),
('fr-b1-u08-p02',44,'reinforcement','Diriger un groupe pour traverser selon les conditions','route-planning field narrative',['educational','public'],['route','fieldwork'],['diriger','traverser','selon'],['opération','reposer','bord'],[
"Pendant une opération d’observation près d’une rivière, Camille doit diriger un petit groupe vers plusieurs points de mesure. Le trajet prévu longe le bord, mais une partie du sentier est fermée après la pluie. Le nouveau parcours doit reposer sur les informations disponibles plutôt que sur l’itinéraire imprimé la veille. Selon le panneau temporaire, les visiteurs doivent utiliser une passerelle située plus loin.",
"Camille explique qu’il ne suffit pas de traverser dès qu’un passage semble possible. Elle consulte la carte et vérifie que la passerelle rejoint bien le second point d’observation. Pour diriger le groupe, elle donne une instruction à la fois et demande à la dernière personne de confirmer que tout le monde suit. Selon les conditions du terrain, le groupe peut aussi raccourcir l’opération et abandonner un point non essentiel sans compromettre l’objectif principal.",
"Après avoir traversé la passerelle, les étudiants reviennent vers le bord sur un secteur autorisé. Camille note le détour afin que l’équipe suivante ne repose pas sur une carte devenue incomplète. Le verbe traverser décrit ici un déplacement réel d’un côté à l’autre, tandis que selon introduit la condition ou la source qui guide le choix. Diriger signifie alors organiser le mouvement avec des informations partagées, pas simplement marcher devant. Cette précision rend l’opération plus sûre et maintient des observations comparables malgré le changement de parcours."
]),
('fr-b1-u08-p03',45,'interleaved','Remarquer le sentiment derrière une personne qui crie','public meeting communication narrative',['public','personal'],['communication','public meeting'],['crier','sentiment','remarquer'],['blague','plaisanter','deviner'],[
"Lors d’une réunion publique, un participant commence à crier après l’annonce d’un changement de stationnement. Plusieurs personnes pensent d’abord qu’il veut seulement provoquer le groupe. Camille essaie plutôt de remarquer les informations présentes dans ses paroles. Derrière le volume de sa voix, elle entend un sentiment d’inquiétude : l’homme accompagne régulièrement une personne âgée et craint de perdre un accès proche. Ce n’est pas une blague et personne ne cherche à plaisanter.",
"Le président demande au participant de parler moins fort, puis reformule son problème. Camille remarque que le sentiment reste le même lorsque le ton baisse. Il serait donc faux de deviner que toute la colère venait simplement d’un désir de crier. Le groupe sépare deux questions : la manière de s’exprimer, qui doit respecter la réunion, et le besoin pratique, qui mérite une réponse. Cette distinction permet de continuer sans approuver les cris ni ignorer la préoccupation.",
"Une solution provisoire est proposée : conserver deux places courtes durées près de l’entrée pendant un mois et mesurer leur utilisation. Camille retient qu’un sentiment peut expliquer une réaction sans la rendre automatiquement acceptable. Remarquer un motif demande d’écouter le contenu, pas seulement le volume. De même, deviner l’intention d’une personne est risqué lorsqu’on dispose de peu d’indices. Une blague, une tentative de plaisanter ou un cri peuvent produire des impressions très différentes, mais le contexte reste nécessaire pour comprendre ce qu’une personne essaie réellement de communiquer."
]),
('fr-b1-u08-p04',46,'transfer','Couvrir un trou sans oublier la forme du problème','building-maintenance inspection narrative',['professional','public'],['maintenance','inspection'],['couvrir','trou','forme'],['classe','second','intelligent'],[
"Dans un centre communautaire, une petite ouverture apparaît dans un mur après le déplacement d’une étagère. Une classe de formation technique observe le problème avant la réparation. Le premier réflexe serait de couvrir le trou avec une plaque décorative, mais l’enseignant demande d’abord d’examiner sa forme. Une fissure fine et un trou profond n’indiquent pas nécessairement la même cause. Les élèves préparent donc un second relevé avec des mesures précises.",
"Le groupe constate que le trou correspond exactement à une ancienne fixation et qu’aucune fissure ne continue autour. Une solution intelligente consiste alors à nettoyer l’ouverture, la remplir avec un matériau adapté et couvrir la surface seulement après séchage. Camille comprend que la forme du dommage aide à choisir la méthode. Couvrir immédiatement aurait caché l’information dont la classe avait besoin pour distinguer un simple ancien point de fixation d’un problème plus large.",
"Le lendemain, les élèves inspectent le résultat. Le second contrôle montre une surface stable et aucune nouvelle marque. Ils prennent une photo avant de remettre l’étagère ailleurs. Camille note qu’un travail intelligent n’est pas celui qui rend le trou invisible le plus vite ; c’est celui qui conserve assez d’informations pour comprendre ce qu’on répare. La forme, la profondeur et le contexte conduisent à une décision proportionnée. Ainsi, couvrir devient la dernière étape d’une réparation vérifiée, tandis que la classe apprend à produire un second jugement après observation plutôt qu’à masquer immédiatement ce qui semble gênant."
]),
('fr-b1-u08-p05',47,'transfer','Ce qui a échappé au plan et ce que le projet a compris','project retrospective narrative',['professional','educational'],['retrospective','project planning'],['échapper','souffrir','compris'],['naître','survivre','debout'],[
"Après une exposition étudiante, l’équipe organise un retour d’expérience. Le projet a survécu à plusieurs changements et est resté debout au sens figuré : il a ouvert à l’heure prévue et accueilli son public. Pourtant, certains détails ont pu échapper au plan. Une série d’étiquettes est arrivée tard et l’équipe a souffert d’un manque de temps le dernier matin. Camille veut comprendre comment ces difficultés ont pu naître sans chercher un coupable.",
"Elle construit une chronologie et demande à chacun ce qu’il avait compris à chaque étape. Une personne croyait que l’impression était automatique ; une autre pensait que les fichiers avaient déjà été validés. Le problème a donc pu échapper aux contrôles parce que deux responsabilités semblaient appartenir à quelqu’un d’autre. Le projet n’a pas souffert d’une seule grosse erreur, mais de plusieurs petites hypothèses non vérifiées. Cette formulation aide l’équipe à parler des processus plutôt que des personnes.",
"Pour la prochaine exposition, une seule liste indiquera clairement le responsable de chaque validation. Camille résume ce qu’elle a compris : survivre à un problème ne signifie pas que la méthode était bonne, et rester debout à la fin ne doit pas empêcher d’étudier ce qui a failli échouer. Le verbe souffrir décrit ici les conséquences réelles d’une organisation insuffisante, tandis qu’échapper montre ce qui n’a pas été remarqué à temps. Le retour d’expérience transforme donc un problème passé en règle de travail plus claire, afin que la prochaine difficulté soit détectée avant de grandir."
])]
SPECS=[]
for pid,seq,ptype,title,genre,domains,topics,forms,reviews,pars in DATA:
 s={'id':pid,'sequence':seq,'ptype':ptype,'title':title,'genre':genre,'domains':domains,'topics':topics,'forms':forms,'reviews':reviews,'paragraphs':pars,'grammar':[{'id':pid+'-grammar','role':'new','description':'B1 contextual grammar and clause linking in the target domain'}],'discourse':[{'id':pid+'-discourse','role':'new','description':'compare evidence, constraints and consequences before selecting an action'}]};s['items']=qset(forms,reviews,topics[0]);SPECS.append(s)
CHECKPOINT={'id':'fr-b1-u08-p06','sequence':48,'ptype':'checkpoint','title':'Ajuster, orienter, interpréter, réparer et apprendre','genre':'B1 cumulative evidence-to-action summary','domains':['educational','public','professional'],'topics':['calibration','route','communication','maintenance','retrospective'],'paragraphs':[
"Camille relie cinq méthodes qui demandent toutes de conserver les preuves avant d’agir. Régler un appareil exige un contrôle qui montre s’il est capable de fonctionner de façon stable. Diriger un groupe pour traverser un terrain demande de choisir selon les conditions réelles. Dans une réunion, une personne peut crier ; il faut remarquer le sentiment ou le besoin sans accepter automatiquement la manière de s’exprimer.",
"Une réparation suit le même principe : avant de couvrir un trou, on examine sa forme pour comprendre ce qu’il indique. Après un projet, certains problèmes peuvent échapper au plan et faire souffrir l’organisation ; le retour d’expérience vérifie alors ce que chacun avait compris. Chaque situation transforme une première impression en question plus précise.",
"Les acquis précédents restent utiles : préparer un projet entier, charger le matériel doucement, organiser une opération qui peut reposer sur le bord observé, reconnaître une blague sans tout deviner quand quelqu’un veut plaisanter, permettre à une classe d’essayer un second plan intelligent, puis distinguer ce qui peut naître, survivre et rester debout. Camille comprend maintenant que corriger une action ne suffit pas : il faut aussi conserver le raisonnement qui explique pourquoi on a choisi de régler, diriger, remarquer, couvrir ou revoir ce qui avait échappé au plan."
],'grammar':[{'id':'fr-b1-u08-cumulative','role':'integration','description':'integrate condition, ability, perception and retrospective clauses'}],'discourse':[{'id':'fr-b1-u08-evidence-action','role':'integration','description':'synthesize evidence-preserving decisions across five domains'}]}
CHECKPOINT['items']=[
('gist','Quelle stratégie relie les cinq contextes ?','Conserver les preuves, préciser le problème puis choisir une action proportionnée.',['contrôle','remarquer']),('literal_detail','Quels mots décrivent le calibrage ?','régler, contrôle et capable',['régler','contrôle','capable']),('cause_effect','Pourquoi le trajet change-t-il ?','Parce qu’il faut diriger et traverser selon les conditions réelles.',['diriger','traverser','selon']),('vocabulary_in_context','Quels mots décrivent la communication publique ?','crier, sentiment et remarquer',['crier','sentiment','remarquer']),('vocabulary_in_context','Quels mots décrivent la réparation ?','couvrir, trou et forme',['couvrir','trou','forme']),('inference','Pourquoi le retour d’expérience examine-t-il ce qui a échappé au plan ?','Pour comprendre comment le projet a pu souffrir et ce que chacun avait compris.',['échapper','souffrir','compris']),('motive','Pourquoi Camille garde-t-elle le raisonnement derrière une correction ?','Pour pouvoir reproduire ou réviser la décision plus tard.',[]),('reference_resolution','Dans « ce qu’il indique », à quoi renvoie « il » ?','Au trou observé pendant l’inspection.',['trou']),('cloze_transfer','Complète : Il faut _____ l’appareil après le contrôle.','régler',['régler']),('summary','Résume l’unité.','Camille apprend à régler après un contrôle, diriger et traverser selon les conditions, remarquer le sentiment derrière quelqu’un qui peut crier, examiner la forme avant de couvrir un trou et comprendre ce qui a pu échapper au plan ou faire souffrir le projet.',['régler','contrôle','capable','diriger','traverser','selon','crier','sentiment','remarquer','couvrir','trou','forme','échapper','souffrir','compris'])]
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);text=text_of(s);return {'id':s['id'],'language':'fr','cefr':'B1','unit':8,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B1 Unit 08 guarded batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B1 Unit 08 batch.']},'paired_text_group':None,'prerequisites':['French B1 Units 01-07 canonical corpus'],'difficulty_notes_internal':'B1 evidence-to-action transfer.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b1_u08']}
def build(a1,a2,b1,D):
 prior=base.prior(a1+a2+b1);ids0={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};forms0={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};bad=[]
 for f in FORMS:
  if f not in D:bad.append(f+':missing_lexicon')
  elif base.tid(D[f]['rank']) in ids0 or f in forms0 or prior.get(f):bad.append(f+':already_deliberate')
 if bad:raise AssertionError('B1 Unit08 candidate failures: '+', '.join(bad))
 out=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,D) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,D) for f in FORMS];ids={t['form']:t['id'] for t in reviews};out.append(mk(CHECKPOINT,[],reviews,ids,True));return out
def main():
 for path,exp,label in [(A1,EXPECTED_A1_BLOB,'A1'),(A2,EXPECTED_A2_BLOB,'A2'),(CANON,EXPECTED_B1_BLOB,'B1')]:
  h=subprocess.check_output(['git','hash-object',str(path)],text=True).strip()
  if h!=exp:raise AssertionError(f'{label} blob drift: {h} != {exp}')
 a1=[json.loads(x) for x in A1.read_text().splitlines() if x.strip()];a2=[json.loads(x) for x in A2.read_text().splitlines() if x.strip()];b1=[json.loads(x) for x in CANON.read_text().splitlines() if x.strip()]
 if len(b1)!=42 or b1[-1]['id']!='fr-b1-u07-p06':raise AssertionError('unexpected frontier')
 D=base.deck();unit=build(a1,a2,b1,D);V=Draft202012Validator(json.loads(SCHEMA.read_text()));prior_ids={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};prior_forms={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};newids=[];newforms=[]
 for r in unit:
  es=sorted(V.iter_errors(r),key=lambda e:list(e.path));
  if es:raise AssertionError(f"{r['id']}: schema {[e.message for e in es[:4]]}")
  if not 220<=r['word_count']<=350:raise AssertionError(f"{r['id']}: B1 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(r['id']+': assessment count')
  if r['sequence']<=47 and len(r['new_lexical_targets'])!=3:raise AssertionError(r['id']+': target load')
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[])}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage")
  for t in r['new_lexical_targets']:
   s=D.get(t['form']);
   if t['id'] in prior_ids or t['form'] in prior_forms or not s or t['source_rank']!=s['rank'] or t['id']!=base.tid(s['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: target drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=15 or len(set(newids))!=15 or len(set(newforms))!=15 or unit[-1]['new_lexical_targets']:raise AssertionError('Unit08 lexical invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b1+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':8,'b1_passages':48,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':FORMS},ensure_ascii=False))
if __name__=='__main__':main()
