#!/usr/bin/env python3
"""Append French B2 Unit 03 (sequences 13-18): ethics and competing values.

Uses the accepted B2 default of four fresh deliberate targets in P01-P05;
P06 has zero new targets. Requires the exact Unit02 frontier lock and preserves
source/freshness, schema/linkage, B2 word-band and exact-review guards.
"""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base

REPO=Path(__file__).resolve().parents[2]
A1=REPO/'reading/french/a1/passages.jsonl'; A2=REPO/'reading/french/a2/passages.jsonl'; B1=REPO/'reading/french/b1/passages.jsonl'; CANON=REPO/'reading/french/b2/passages.jsonl'; SCHEMA=REPO/'reading/schema/passage.schema.json'; LOCK=REPO/'reading/audit/french_b2_unit02_frontier_lock.json'; PROBE=REPO/'reading/audit/french_b2_unit03_target_probe.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca','B2':'ff94113359f90b68032b2e2f92aaa1bf2b3ea923'}
FORMS=('juste','chance','groupe','réussir','permettre','refuser','accord','obliger','vérité','vrai','faux','mentir','victime','dommage','aider','difficile','garder','donner','loi','guerre')

SPECS=[
{
'id':'fr-b2-u03-p01','sequence':13,'ptype':'instructional','title':'Une sélection juste ne traite pas toujours chaque dossier de la même manière','genre':'argument','domains':['educational','public'],'topics':['ethics and competing values','fair opportunity','selection criteria'],'forms':['juste','chance','groupe','réussir'],'reviews':['promettre','décider','attendre','confiance'],'paragraphs':[
"Une fondation dispose de dix bourses pour trente candidats à une formation technique. Au premier regard, la règle la plus juste semble simple : classer uniquement les notes et financer les dix meilleurs dossiers. Un membre du jury défend cette méthode parce qu’elle applique le même calcul à tout le monde. Une autre membre répond que l’égalité de procédure ne garantit pas toujours une chance comparable. Certains candidats ont travaillé à temps partiel pendant leurs études, d’autres ont eu accès à des cours privés et à davantage de matériel. Le groupe doit donc décider ce que signifie ici une sélection juste sans promettre un résultat identique à chacun.",
"Le jury refuse pourtant de transformer chaque difficulté personnelle en avantage automatique. Il cherche des critères que tous peuvent comprendre et contester. Les notes restent importantes, mais le groupe ajoute deux éléments : la progression sur plusieurs années et la qualité d’un projet réalisé avec les ressources disponibles. Cette formule ne garantit pas à chacun de réussir, mais elle donne une chance d’être évalué sur plus d’un signal. Pour préserver la confiance, les critères sont publiés avant la décision. Les candidats n’ont pas à attendre la fin du processus pour découvrir qu’une règle cachée a modifié le classement.",
"Un désaccord demeure. Si le jury corrige trop fortement les différences de contexte, il risque de remplacer une inégalité par une autre. Si, au contraire, il ignore tout contexte, une personne ayant eu moins de possibilités peut être jugée comme si elle avait appartenu au même groupe de ressources qu’une autre. Le texte défend donc une idée limitée de la justice : une procédure juste doit traiter les différences seulement lorsqu’elles sont pertinentes pour la capacité future de réussir. Elle ne doit ni récompenser mécaniquement la difficulté ni supposer que les mêmes chiffres racontent toujours la même histoire.",
"La fondation adopte finalement un barème public avec trois composantes et prévoit un contrôle après la première année. Elle ne peut pas promettre que chaque bénéficiaire va réussir, mais elle peut décider de suivre les résultats pour vérifier si sa méthode ouvre réellement une chance raisonnable à plusieurs profils. Si les données montrent qu’un critère exclut systématiquement un groupe sans rapport avec l’objectif de la formation, le barème pourra être révisé. La confiance vient alors moins de l’idée d’une formule parfaite que de la possibilité d’expliquer pourquoi la règle est juste, où elle peut échouer et comment le jury répondra aux résultats."
],
'grammar':[{'id':'fr-b2-u03-fairness-condition','role':'new','description':'contrast equal treatment with conditionally relevant differences using si, lorsque and sans garantir'}],
'discourse':[{'id':'fr-b2-u03-procedural-fairness','role':'new','description':'define a fairness principle, test counterexamples, delimit scope and propose revision criteria'}],
'items':[
('main_claim','Quelle conception d’une sélection juste le texte défend-il ?','Une procédure transparente peut tenir compte de différences pertinentes sans promettre des résultats identiques ni corriger automatiquement toute difficulté.',['juste','promettre']),
('literal_detail','Quels éléments sont ajoutés aux notes ?','La progression sur plusieurs années et la qualité d’un projet réalisé avec les ressources disponibles.',['groupe']),
('argument_relation','Pourquoi le jury refuse-t-il à la fois le classement purement numérique et la correction automatique du contexte ?','Parce que l’un peut ignorer des différences pertinentes et l’autre peut créer une nouvelle inégalité sans lien avec la capacité à réussir.',['juste','réussir']),
('vocabulary_in_context','Que signifie « chance » dans ce passage ?','Une possibilité réelle d’être considéré ou de progresser, et non une garantie de succès.',['chance']),
('vocabulary_in_context','Que signifie « réussir » ici ?','Atteindre les objectifs de la formation après avoir obtenu la bourse.',['réussir']),
('assumption','Quelle hypothèse justifie l’usage du contexte dans le barème ?','Que certaines différences de ressources affectent la lecture des résultats sans déterminer à elles seules la capacité future.',['groupe','juste']),
('inference','Pourquoi publier les critères avant la décision renforce-t-il la confiance ?','Parce que les candidats peuvent comprendre la règle avant le résultat et ne découvrent pas après coup un critère caché.',['confiance','décider']),
('reference_resolution','Dans « elle ne doit ni récompenser », à quoi renvoie « elle » ?','À la procédure juste décrite dans le paragraphe.',['juste']),
('stance','Quelle position le texte adopte-t-il envers un barème définitif ?','Il préfère une règle explicable et révisable à une formule présentée comme parfaitement juste pour toujours.',['juste','attendre']),
('summary','Résume le compromis du jury.','Le groupe décide d’offrir une chance plus large de réussir grâce à un barème public, sans promettre l’égalité des résultats, puis attend des données de suivi pour préserver la confiance dans ce qu’il juge juste.',['groupe','décider','chance','réussir','promettre','attendre','confiance','juste'])]
},
{
'id':'fr-b2-u03-p02','sequence':14,'ptype':'reinforcement','title':'Consentir à une étude : permettre de participer implique aussi de pouvoir refuser','genre':'case','domains':['educational','professional'],'topics':['ethics and competing values','consent','voluntary participation'],'forms':['permettre','refuser','accord','obliger'],'reviews':['grave','calmer','choisir','problème'],'paragraphs':[
"Une école veut tester une nouvelle application de lecture pendant quatre semaines. L’équipe de recherche demande aux familles un accord écrit. La directrice pense que le projet peut aider les élèves et souhaite que toute la classe participe afin d’obtenir des données comparables. Un enseignant soulève cependant un problème : si l’activité est présentée comme une partie obligatoire du cours, les familles peuvent croire qu’elles n’ont pas le droit de refuser. Permettre une recherche utile ne suffit donc pas ; il faut aussi distinguer clairement l’enseignement normal de la participation volontaire et éviter d’obliger quelqu’un par la manière dont la demande est formulée.",
"L’équipe réécrit le formulaire. Elle explique l’objectif, les données recueillies, la durée et la possibilité de retirer son accord. Elle précise surtout que refuser n’aura aucun effet sur les notes, l’accès au matériel ou la relation avec l’école. Cette précision vise à calmer une pression implicite : un parent peut accepter simplement parce qu’il craint de créer un problème à son enfant. La directrice reconnaît qu’un consentement valable ne dépend pas seulement du mot « oui ». Il faut permettre une décision informée et créer des conditions où un « non » peut être exprimé sans conséquence punitive.",
"Un second débat apparaît lorsque plusieurs élèves souhaitent participer alors que leurs parents hésitent. L’école doit choisir une règle qui respecte les responsabilités des adultes tout en prenant au sérieux la voix des élèves. Le texte ne prétend pas résoudre tous les cas par une formule unique. Il distingue plutôt trois niveaux : l’information de l’élève, son accord adapté à son âge et l’autorisation requise du responsable légal. Dans une situation grave où un soin nécessaire serait en jeu, d’autres règles pourraient s’appliquer ; ici, il s’agit d’une étude facultative, ce qui renforce la nécessité de pouvoir refuser.",
"Finalement, l’école propose une activité équivalente aux élèves qui ne participent pas et interdit aux enseignants de savoir qui a refusé pendant l’évaluation scolaire. Cette séparation réduit le risque d’obliger indirectement les familles. Elle ne garantit pas que toute décision sera facile, mais elle rend le conflit de valeurs visible : la recherche peut aider le groupe, tandis que l’autonomie exige de permettre à chaque famille de refuser. L’accord devient alors un processus plutôt qu’une signature isolée. Pour le texte, choisir une procédure éthique consiste à favoriser un bénéfice collectif sans transformer l’autorité scolaire en moyen de pression."
],
'grammar':[{'id':'fr-b2-u03-consent-modality','role':'new','description':'express permission, refusal and coercion through permettre/refuser/obliger plus infinitive complements'}],
'discourse':[{'id':'fr-b2-u03-consent-scope','role':'new','description':'separate benefit, authority, voluntariness and exceptional cases when evaluating consent'}],
'items':[
('main_claim','Quelle condition rend l’accord éthique selon le texte ?','La personne doit recevoir l’information nécessaire et pouvoir refuser sans pression ni conséquence punitive.',['accord','refuser']),
('literal_detail','Quelle activité est prévue pour les non-participants ?','Une activité équivalente qui n’affecte pas leurs notes ni leur accès au matériel.',['permettre']),
('argument_relation','Pourquoi le bénéfice possible de l’étude ne suffit-il pas à obliger toute la classe ?','Parce qu’un bénéfice collectif ne supprime pas l’exigence de participation volontaire dans une étude facultative.',['obliger','problème']),
('vocabulary_in_context','Que signifie « permettre » dans ce cas ?','Créer réellement la possibilité d’un choix, et pas seulement annoncer qu’un choix existe.',['permettre']),
('vocabulary_in_context','Que signifie « refuser » ici ?','Choisir de ne pas participer sans subir de sanction scolaire.',['refuser']),
('assumption','Pourquoi cacher aux évaluateurs l’identité des familles ayant refusé est-il utile ?','Cela suppose que la connaissance du refus pourrait influencer consciemment ou non la relation d’évaluation.',['refuser','accord']),
('inference','Pourquoi le texte distingue-t-il une étude facultative d’une situation grave ?','Parce que l’urgence et la nécessité peuvent modifier la portée de l’autonomie, alors qu’ici le risque ne justifie pas de forcer la participation.',['grave','obliger']),
('reference_resolution','Dans « Cette séparation réduit le risque », quelle séparation est visée ?','La séparation entre la décision de participer et le travail des enseignants qui évaluent les élèves.',['accord']),
('stance','Quelle position le texte adopte-t-il envers l’autorité scolaire ?','Elle peut organiser et aider, mais elle ne doit pas être utilisée pour obliger indirectement des familles à participer.',['aider','obliger']),
('summary','Résume la procédure proposée.','L’école choisit de permettre une participation informée, d’obtenir un accord explicite, de rendre possible le fait de refuser et de calmer les pressions qui pourraient obliger les familles autour d’un problème non grave.',['choisir','permettre','accord','refuser','calmer','obliger','problème','grave'])]
},
{
'id':'fr-b2-u03-p03','sequence':15,'ptype':'interleaved','title':'Dire la vérité quand une explication complète peut aussi blesser','genre':'response','domains':['professional','educational'],'topics':['ethics and competing values','truthfulness','responsible disclosure'],'forms':['vérité','vrai','faux','mentir'],'reviews':['maintenir','simplement','secret','surtout'],'paragraphs':[
"Dans une association étudiante, une responsable découvre qu’une erreur de réservation a annulé une salle importante. Un collègue propose de dire simplement que « le lieu est devenu indisponible », sans préciser que l’équipe a envoyé le formulaire trop tard. Il affirme que cette phrase est techniquement vraie et qu’elle évitera d’humilier la personne qui a fait l’erreur. Une autre responsable répond qu’une phrase peut être vraie tout en donnant une impression fausse si elle retire volontairement l’information qui explique la situation. Le débat ne porte donc pas seulement sur la vérité de chaque mot, mais sur la différence entre protéger une personne et mentir au groupe par omission organisée.",
"L’équipe distingue d’abord ce qui doit rester secret de ce qui doit être communiqué. Le nom de la personne responsable n’est pas nécessaire pour expliquer le changement de salle ; le maintenir hors du message public peut protéger sa dignité. En revanche, cacher que l’erreur vient du processus interne empêcherait les membres de comprendre pourquoi une nouvelle procédure est proposée. Surtout, une formulation honnête peut reconnaître la faute sans désigner un coupable : « notre demande a été envoyée après la date limite ». Cette phrase dit la vérité pertinente, reste vraie même sans nommer quelqu’un et évite de créer un récit faux sur une décision extérieure.",
"Un membre objecte qu’il vaut mieux préserver l’unité du groupe que raconter chaque détail. Le texte accepte une partie de cet argument : la vérité n’oblige pas à rendre public tout ce que l’on sait. Mais il refuse l’idée qu’une information soit écartée simplement parce qu’elle est embarrassante. Pour décider quoi dire, l’équipe pose trois questions : l’information est-elle nécessaire pour comprendre la décision, risque-t-elle de causer un dommage sans utilité, et son omission ferait-elle croire quelque chose de faux ? Mentir commence ici non seulement avec une phrase inventée, mais aussi avec une stratégie destinée à faire adopter une représentation que l’on sait trompeuse.",
"Le message final explique donc l’erreur de procédure, annonce la nouvelle salle et décrit le contrôle qui sera ajouté au calendrier. Il ne révèle aucun nom. Cette solution cherche à maintenir deux valeurs en même temps : la vérité sur ce qui a affecté le groupe et la protection d’informations personnelles qui n’aident pas à corriger le problème. Le texte adopte une position exigeante mais limitée : être vrai ne signifie pas tout dire, garder un secret ne signifie pas nécessairement mentir, et une phrase littéralement vraie peut encore être éthiquement insuffisante si elle est conçue surtout pour produire une impression fausse."
],
'grammar':[{'id':'fr-b2-u03-truth-qualification','role':'new','description':'qualify truth claims with même si, sans, tout en and conditions on omission'}],
'discourse':[{'id':'fr-b2-u03-truth-vs-disclosure','role':'new','description':'distinguish truthfulness, privacy, omission and misleading implication through scoped counterargument'}],
'items':[
('main_claim','Quelle distinction centrale organise le texte ?','Dire la vérité n’exige pas de tout révéler, mais protéger une information ne doit pas servir à produire volontairement une impression fausse.',['vérité','faux']),
('literal_detail','Quelle formulation honnête l’équipe choisit-elle pour décrire l’erreur ?','Elle indique que la demande a été envoyée après la date limite sans nommer la personne responsable.',['vrai']),
('argument_relation','Pourquoi le texte accepte-t-il de garder un nom secret mais pas de cacher l’erreur de procédure ?','Le nom n’est pas nécessaire pour comprendre ou corriger le processus, tandis que l’erreur explique la décision et la nouvelle procédure.',['secret','vérité']),
('vocabulary_in_context','Que signifie « faux » dans l’expression « impression fausse » ?','Une représentation que les faits pertinents ne soutiennent pas, même si chaque mot isolé peut sembler exact.',['faux']),
('vocabulary_in_context','Que signifie « mentir » dans l’analyse ?','Chercher à faire croire une représentation que l’on sait trompeuse, par invention ou omission stratégique.',['mentir']),
('assumption','Quelle hypothèse justifie de ne pas publier le nom du collègue ?','Que l’identité de la personne n’est pas nécessaire pour comprendre le problème ni prévenir sa répétition.',['secret','maintenir']),
('inference','Pourquoi une phrase littéralement vraie peut-elle rester insuffisante ?','Parce que le choix de ce qu’elle omet peut être destiné surtout à conduire le lecteur vers une conclusion fausse.',['vrai','faux','surtout']),
('reference_resolution','Dans « il refuse l’idée », à quoi renvoie « il » ?','Au texte ou au raisonnement défendu dans le passage.',['vérité']),
('stance','Quelle position le texte adopte-t-il envers la transparence totale ?','Il la refuse : la vérité pertinente compte, mais certaines informations personnelles peuvent rester secrètes sans qu’il faille mentir.',['vérité','secret','mentir']),
('summary','Résume le compromis choisi.','L’équipe maintient le nom secret, dit la vérité pertinente sur son erreur, évite un récit faux et refuse de mentir simplement pour protéger son image, surtout lorsque l’omission empêcherait de corriger le processus.',['maintenir','secret','vérité','faux','mentir','simplement','surtout','vrai'])]
},
{
'id':'fr-b2-u03-p04','sequence':16,'ptype':'transfer','title':'Aider d’abord la personne la plus proche ou la victime la plus exposée ?','genre':'case analysis','domains':['public','professional'],'topics':['ethics and competing values','harm reduction','resource allocation'],'forms':['victime','dommage','aider','difficile'],'reviews':['ordre','lieu','doute','préférer'],'paragraphs':[
"Lors d’un exercice de sécurité fictif, une équipe doit répartir deux bénévoles entre trois personnes qui demandent de l’aide. La première se trouve juste à côté de la sortie et a une blessure légère. La deuxième est plus loin, ne peut pas marcher seule et risque un dommage plus important si personne ne l’accompagne. La troisième affirme aller bien mais semble désorientée. Le responsable doit mettre les priorités en ordre sans disposer d’un diagnostic complet. Le cas est difficile parce que la victime la plus visible n’est pas nécessairement celle qui subirait le plus grand dommage en attendant quelques minutes.",
"Une bénévole veut aider d’abord la personne la plus proche : elle peut être sortie rapidement, ce qui libère ensuite une ressource. Un autre préfère envoyer immédiatement quelqu’un vers la personne qui ne peut pas marcher. Il soutient qu’un même délai n’a pas le même effet pour chaque victime. Le responsable reconnaît les deux arguments et demande quel critère doit dominer : la vitesse totale, la réduction du dommage le plus sérieux ou l’ordre d’arrivée des demandes. Le lieu de chaque personne compte, mais il ne doit pas devenir une règle morale automatique. La proximité peut être utile sans être décisive.",
"Le groupe adopte une règle en deux étapes. Un bénévole vérifie rapidement la personne désorientée pendant que l’autre rejoint la victime qui ne peut pas marcher. Si la première vérification révèle un danger grave, l’ordre peut changer. Sinon, la personne proche de la sortie reçoit ensuite l’aide nécessaire. Le doute n’est donc pas supprimé ; il est géré par une action courte qui apporte de l’information. Le texte souligne qu’aider de façon équitable ne signifie pas nécessairement servir chacun selon l’ordre de demande. Il faut comparer la gravité probable du dommage et la possibilité de réduire ce dommage avec les ressources présentes.",
"Après l’exercice, les participants discutent de la règle. Certains la trouvent trop complexe pour une situation urgente. D’autres répondent qu’une règle simple comme « le plus proche d’abord » peut être plus facile mais produire un résultat difficile à défendre si elle ignore une victime beaucoup plus exposée. Le texte ne propose pas une formule universelle ; il préfère une priorité justifiée, révisable quand le doute change, et assez claire pour être appliquée dans le lieu réel. L’objectif moral n’est pas de compter seulement les interventions, mais d’aider là où une action disponible peut raisonnablement éviter le dommage le plus sérieux sans abandonner les autres."
],
'grammar':[{'id':'fr-b2-u03-priority-comparison','role':'new','description':'compare competing priorities with plus, le plus, selon and conditional reprioritization'}],
'discourse':[{'id':'fr-b2-u03-harm-prioritization','role':'new','description':'compare proximity, severity, information value and revisability in a constrained allocation case'}],
'items':[
('main_claim','Quelle règle de priorité le texte défend-il ?','Aider selon le dommage probable et la capacité d’une action à le réduire, tout en révisant l’ordre quand une vérification change l’information.',['aider','dommage','ordre']),
('literal_detail','Qui reçoit d’abord un accompagnement continu ?','La victime qui ne peut pas marcher seule.',['victime']),
('argument_relation','Pourquoi la proximité n’est-elle pas retenue comme critère unique ?','Parce qu’une personne proche peut subir moins de dommage qu’une personne plus éloignée qui ne peut pas attendre sans risque.',['lieu','dommage']),
('vocabulary_in_context','Que signifie « victime » dans ce scénario ?','Une personne exposée à un préjudice ou ayant besoin de protection dans l’exercice.',['victime']),
('vocabulary_in_context','Pourquoi le cas est-il qualifié de « difficile » ?','Parce que plusieurs critères moralement plausibles conduisent à des priorités différentes sous information incomplète.',['difficile']),
('assumption','Quelle hypothèse soutient la vérification rapide de la personne désorientée ?','Qu’une courte évaluation peut réduire le doute sans retarder excessivement l’aide la plus urgente.',['doute','aider']),
('inference','Pourquoi le texte accepte-t-il qu’une priorité change ?','Parce qu’une nouvelle information peut modifier l’estimation du dommage et donc l’ordre justifiable.',['dommage','ordre']),
('reference_resolution','Dans « il est géré par une action courte », à quoi renvoie « il » ?','Au doute concernant l’état et la priorité des personnes.',['doute']),
('stance','Quelle position le texte adopte-t-il envers les règles très simples ?','Il reconnaît leur utilité pratique mais préfère une règle qui reste sensible aux différences de dommage entre victimes.',['préférer','victime','dommage']),
('summary','Résume le compromis de l’équipe.','Dans un lieu où le doute demeure, l’équipe met les besoins en ordre, choisit d’aider la victime la plus exposée au dommage tout en vérifiant les autres, et préfère une règle révisable malgré son caractère difficile.',['lieu','doute','ordre','aider','victime','dommage','préférer','difficile'])]
},
{
'id':'fr-b2-u03-p05','sequence':17,'ptype':'integration','title':'Garder des lettres de guerre ou les donner à la famille : un musée face à deux responsabilités','genre':'argument and response','domains':['public','educational'],'topics':['ethics and competing values','archives','ownership and public interest'],'forms':['garder','donner','loi','guerre'],'reviews':['ramener','pareil','lumière','pousser'],'paragraphs':[
"Dans un cas fictif, un petit musée reçoit une boîte de lettres écrites pendant une guerre ancienne. Un collectionneur les a données au musée il y a plusieurs décennies, mais une famille affirme aujourd’hui que certaines lettres étaient personnelles et n’auraient jamais dû quitter ses archives. La direction voudrait garder l’ensemble parce qu’il peut mettre en lumière la vie quotidienne de l’époque. La famille demande au contraire de ramener les lettres privées chez elle. La loi applicable au don ancien semble permettre au musée de conserver les documents, mais l’équipe reconnaît qu’une réponse légalement possible n’est pas automatiquement la seule réponse éthique.",
"Une historienne soutient que garder les lettres ensemble protège leur contexte. Séparer les documents pourrait rendre plus difficile la compréhension de la guerre telle qu’elle apparaît dans les échanges familiaux. Un représentant de la famille répond que l’intérêt public ne donne pas au musée un droit illimité de publier des détails intimes. Il propose de donner au musée des copies de certaines pages et de récupérer les originaux les plus personnels. La situation n’est pas pareille pour chaque lettre : certaines décrivent des événements publics, d’autres parlent uniquement de santé, de conflits familiaux ou de sentiments qui n’ajoutent presque rien à l’exposition.",
"Le comité refuse de se laisser pousser vers une opposition totale entre « tout garder » et « tout donner ». Il classe les lettres selon leur intérêt historique, leur caractère privé et l’existence d’informations concernant encore des personnes identifiables. La loi fixe un minimum de ce que le musée peut faire ; elle ne détermine pas seule ce qu’il devrait faire. Pour mettre davantage de lumière sur son raisonnement, le musée invite la famille à examiner les catégories et accepte qu’une partie reste fermée au public pendant une période définie. Il peut ainsi garder l’intégrité de l’archive sans supposer que toute possession juridique justifie toute utilisation.",
"L’accord final prévoit trois traitements : exposition de quelques lettres à forte valeur historique, consultation restreinte d’un second groupe et restitution de documents purement privés. Le musée accepte donc de donner certains originaux à la famille, même si la loi ne l’y oblige pas clairement. Cette décision ne cherche pas à effacer la guerre du récit ni à ramener toutes les pièces à un statut pareil. Elle reconnaît plutôt deux responsabilités : garder des sources qui éclairent une histoire collective et limiter l’usage d’éléments dont la valeur publique est faible face à l’atteinte privée. Le texte défend ainsi une réponse graduée plutôt qu’un principe absolu de propriété ou d’accès."
],
'grammar':[{'id':'fr-b2-u03-legal-ethical-modality','role':'new','description':'contrast what law permits with what an actor should choose, using pouvoir/devoir-style ethical modality'}],
'discourse':[{'id':'fr-b2-u03-law-vs-ethics','role':'new','description':'distinguish legal permission, public value, privacy harm and graduated remedies in an archive dispute'}],
'items':[
('main_claim','Quelle différence centrale le passage établit-il entre la loi et l’éthique ?','La loi peut définir ce que le musée a le droit de garder, tandis que l’éthique demande encore comment équilibrer intérêt public et vie privée.',['loi','garder']),
('literal_detail','Quels trois traitements sont finalement prévus ?','Exposition de quelques lettres, consultation restreinte d’un second groupe et restitution des documents purement privés.',['donner']),
('argument_relation','Pourquoi le comité refuse-t-il les solutions « tout garder » et « tout donner » ?','Parce que les lettres n’ont pas toutes le même intérêt public ni le même degré de caractère privé.',['garder','donner','pareil']),
('vocabulary_in_context','Quel sens prend « garder » dans le passage ?','Conserver matériellement ou institutionnellement des documents dans l’archive du musée.',['garder']),
('vocabulary_in_context','Quel rôle joue le mot « guerre » dans le dilemme ?','Il désigne le contexte historique qui donne à certaines lettres une valeur collective au-delà de leur caractère privé.',['guerre']),
('assumption','Quelle hypothèse permet de restituer certaines lettres sans détruire la valeur de l’ensemble ?','Que les documents purement privés contribuent peu à la compréhension historique et que le contexte essentiel peut être préservé autrement.',['donner','guerre']),
('inference','Pourquoi le musée accepte-t-il une restriction plus forte que ce que la loi exige clairement ?','Parce qu’une permission juridique ne résout pas à elle seule le conflit entre intérêt historique et atteinte privée.',['loi']),
('reference_resolution','Dans « elle ne détermine pas seule », à quoi renvoie « elle » ?','À la loi qui fixe le minimum juridique applicable au musée.',['loi']),
('stance','Quelle position le texte adopte-t-il envers la propriété juridique ?','Il la considère pertinente mais insuffisante pour décider seule de l’usage éthique de documents sensibles.',['loi','garder']),
('summary','Résume la solution graduée.','Le musée refuse de garder ou donner toutes les lettres de façon pareille : il utilise la loi comme limite, ramène certains documents à la famille, garde ceux qui mettent en lumière la guerre et résiste à la pression qui pourrait le pousser vers une solution absolue.',['garder','donner','loi','guerre','pareil','ramener','lumière','pousser'])]
}
]

CHECKPOINT={
'id':'fr-b2-u03-p06','sequence':18,'ptype':'checkpoint','title':'Comparer des valeurs sans transformer un principe en réponse automatique','genre':'B2 cumulative ethics checkpoint','domains':['educational','public','professional'],'topics':['ethics and competing values','fairness','consent','truthfulness','harm','law'],'paragraphs':[
"Les cinq cas de l’unité montrent qu’une décision juste ne se réduit pas à appliquer le même geste partout. Pour les bourses, donner à chaque groupe une chance réelle de réussir exige de définir quelles différences sont pertinentes. La règle doit rester explicable : une procédure peut être juste sans garantir le même résultat à chacun. Le point important n’est pas d’inventer une faveur, mais de montrer pourquoi un critère sert l’objectif annoncé et comment il pourrait être révisé si ses effets excluent un groupe sans raison suffisante. Une chance équitable est donc une possibilité structurée, non une promesse de réussir.",
"Le cas de la recherche ajoute l’autonomie. Permettre à une personne de participer implique aussi de permettre de refuser. Un accord n’est pas réellement volontaire si l’autorité peut obliger indirectement celui qui hésite. Le cas de la communication ajoute une autre limite : dire la vérité ne signifie pas révéler tout détail, mais une phrase vraie peut rester trompeuse si elle est conçue pour produire une impression fausse. Mentir peut prendre la forme d’une invention, mais aussi d’une omission organisée lorsque l’objectif est de faire croire ce que l’on sait inexact.",
"Le scénario d’aide rappelle ensuite que les valeurs entrent parfois en conflit sous contrainte. Une victime proche n’est pas toujours celle qu’il faut aider en premier si une autre risque un dommage beaucoup plus sérieux. Une décision peut être difficile précisément parce que plusieurs critères paraissent défendables. Il faut alors expliciter la priorité, vérifier ce qui peut changer l’évaluation et accepter de la réviser. Dans l’archive fictive, la loi joue un rôle comparable : elle fixe ce qui est permis, mais ne répond pas seule à la question de savoir s’il faut garder un document ou le donner lorsqu’un intérêt historique rencontre une atteinte privée.",
"La synthèse n’ordonne donc pas les valeurs de manière définitive. Elle propose une méthode : identifier qui peut subir un dommage, demander quelle règle est en jeu, préciser ce qu’un accord autorise réellement, distinguer le vrai du faux, puis expliquer pourquoi une exception éventuelle reste limitée. Même un contexte de guerre ne rend pas tout intérêt public supérieur à toute vie privée. De même, vouloir aider ne justifie pas d’ignorer l’autonomie. Une décision éthique cherche à rendre visibles ses raisons, ses limites et la personne qui supporte le coût du choix, plutôt qu’à cacher le conflit derrière un mot unique comme justice, sécurité ou efficacité."
],
'grammar':[{'id':'fr-b2-u03-ethical-synthesis','role':'review','description':'synthesize permission, obligation, comparison, condition and qualified principle statements'}],
'discourse':[{'id':'fr-b2-u03-value-conflict-synthesis','role':'review','description':'compare five cases through stakeholder harm, scope, exception, counterargument and revisability'}],
'items':[
('main_claim','Quelle méthode générale la synthèse recommande-t-elle ?','Identifier les valeurs et personnes affectées, préciser la portée des règles, comparer les dommages et justifier les exceptions plutôt que d’appliquer un principe automatiquement.',['juste','dommage','loi']),
('argument_relation','Comment le cas du consentement et celui de la vérité se ressemblent-ils ?','Tous deux montrent qu’une forme extérieure — un oui ou une phrase vraie — peut être insuffisante si le contexte produit une pression ou une impression trompeuse.',['accord','vrai','faux']),
('cross_text_synthesis','Quel principe commun relie la sélection de bourses et l’aide aux victimes ?','Traiter équitablement ne signifie pas toujours faire exactement la même chose : les différences pertinentes peuvent modifier une priorité justifiable.',['juste','chance','victime','aider']),
('assumption','Quelle hypothèse soutient la possibilité d’exceptions limitées ?','Qu’une règle générale sert une valeur identifiable et peut devoir céder lorsque son application produit un dommage contraire à cette valeur.',['dommage','loi']),
('inference','Pourquoi une décision difficile n’est-elle pas nécessairement une mauvaise décision ?','Parce que la difficulté peut venir d’un conflit réel entre plusieurs valeurs légitimes plutôt que d’un manque de raisonnement.',['difficile']),
('reference_resolution','Dans « elle fixe ce qui est permis », à quoi renvoie « elle » ?','À la loi dans le cas fictif de l’archive.',['loi']),
('stance','Quelle position la synthèse adopte-t-elle envers les principes absolus ?','Elle s’en méfie lorsque leur application automatique masque les personnes affectées, les dommages ou la portée réelle d’un accord.',['accord','dommage']),
('vocabulary_in_context','Pourquoi « mentir » dépasse-t-il ici l’invention d’une phrase fausse ?','Parce que le texte inclut aussi l’omission organisée destinée à produire volontairement une croyance trompeuse.',['mentir','faux']),
('synthesis','Comment autonomie et aide peuvent-elles entrer en tension ?','Aider peut viser un bénéfice réel, mais obliger quelqu’un au nom de ce bénéfice peut supprimer la possibilité de refuser.',['aider','obliger','refuser']),
('summary','Résume l’unité en une phrase.','Une décision juste donne une chance de réussir sans garantir le résultat, peut permettre ou refuser selon un accord sans obliger, cherche la vérité en distinguant vrai et faux sans mentir, compare le dommage subi par chaque victime avant d’aider dans un cas difficile, et utilise la loi pour décider quoi garder ou donner même lorsque la guerre donne aux documents une valeur collective.',['juste','chance','réussir','permettre','refuser','accord','obliger','vérité','vrai','faux','mentir','victime','dommage','aider','difficile','garder','donner','loi','guerre','groupe'])]
}

def text_of(s): return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids); text=text_of(s)
 return {'id':s['id'],'language':'fr','cefr':'B2','unit':3,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 03 guarded production batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 03: ethics and competing values.','Accepted B2 default of four fresh targets per P01-P05; P06 zero new.','All scenarios are fictional or generic; no external factual claim is required.']},'paired_text_group':None,'prerequisites':['French B2 Units 01-02 canonical and Unit02 frontier lock PASS'],'difficulty_notes_internal':'B2 ethical reasoning: competing values, scope, exceptions, stakeholder harm, counterargument and revisability.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b2_u03']}

def build(a1,a2,b1,b2,deck):
 prior=base.prior(a1+a2+b1+b2); prior_ids={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; prior_forms={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; bad=[]
 for f in FORMS:
  if f not in deck: bad.append(f+':missing_lexicon')
  elif base.tid(deck[f]['rank']) in prior_ids or f in prior_forms or prior.get(f): bad.append(f+':already_deliberate')
 if bad: raise AssertionError('B2 Unit03 candidate failures: '+', '.join(bad))
 out=[]
 for s in SPECS:
  text=text_of(s); new=[base.nt(f,text,deck) for f in s['forms']]; reviews=[base.rev(f,prior) for f in s['reviews']]; ids={t['form']:t['id'] for t in new+reviews}; out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,deck) for f in FORMS]; ids={t['form']:t['id'] for t in reviews}; out.append(mk(CHECKPOINT,[],reviews,ids,True)); return out

def main():
 for label,path in [('A1',A1),('A2',A2),('B1',B1),('B2',CANON)]:
  got=subprocess.check_output(['git','hash-object',str(path)],text=True).strip()
  if got!=EXPECTED[label]: raise AssertionError(f'{label} blob drift: {got} != {EXPECTED[label]}')
 if not LOCK.exists(): raise AssertionError('Unit02 frontier lock missing')
 lock=json.loads(LOCK.read_text(encoding='utf-8'))
 if lock.get('status')!='PASS' or lock.get('canonical_blob')!=EXPECTED['B2'] or lock.get('last_sequence')!=12: raise AssertionError('Unit02 frontier lock mismatch')
 if not PROBE.exists(): raise AssertionError('Unit03 target probe artifact missing')
 probe=json.loads(PROBE.read_text(encoding='utf-8'))
 if probe.get('status')!='PASS' or probe.get('b2_source_blob')!=EXPECTED['B2']: raise AssertionError('Unit03 target probe stale')
 fresh={x['form'] for x in probe.get('fresh',[])}
 if any(f not in fresh for f in FORMS): raise AssertionError('selected Unit03 target absent from fresh probe')
 a1=[json.loads(x) for x in A1.read_text(encoding='utf-8').splitlines() if x.strip()]; a2=[json.loads(x) for x in A2.read_text(encoding='utf-8').splitlines() if x.strip()]; b1=[json.loads(x) for x in B1.read_text(encoding='utf-8').splitlines() if x.strip()]; b2=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(b2)!=12 or b2[-1]['id']!='fr-b2-u02-p06': raise AssertionError('unexpected B2 prerequisite frontier')
 deck=base.deck(); unit=build(a1,a2,b1,b2,deck); V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')))
 prior_ids={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; prior_forms={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; newids=[];newforms=[]
 if [r['sequence'] for r in unit]!=list(range(13,19)) or [r['id'] for r in unit]!=[f'fr-b2-u03-p{i:02d}' for i in range(1,7)]: raise AssertionError('B2 Unit03 sequence/id continuity failure')
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs: raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
  if not 350<=r['word_count']<=550: raise AssertionError(f"{r['id']}: B2 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10: raise AssertionError(f"{r['id']}: assessment count")
  if r['sequence']<=17 and len(r['new_lexical_targets'])!=4: raise AssertionError(f"{r['id']}: accepted B2 default load must be 4")
  if r['sequence']==18 and r['new_lexical_targets']: raise AssertionError('B2 Unit03 P06 must have zero new targets')
  amap={a['question_id']:a['id'] for a in r['answer_key']}; local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])): raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   src=deck.get(t['form'])
   if t['id'] in prior_ids or t['form'] in prior_forms or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']: raise AssertionError(f"{r['id']}: source/exposure/freshness drift {t}")
   newids.append(t['id']); newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1: raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20: raise AssertionError('B2 Unit03 lexical uniqueness failure')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b2+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','level':'B2','unit':3,'theme':'ethics and competing values','appended_passages':6,'b2_passages':18,'questions':60,'answers':60,'new_targets':20,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':[{'form':f,'rank':deck[f]['rank'],'id':base.tid(deck[f]['rank'])} for f in FORMS]},ensure_ascii=False))

if __name__=='__main__': main()
