#!/usr/bin/env python3
"""Append French A2 Unit 03 (sequences 13-18) as one guarded batch."""
from __future__ import annotations
import csv,json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator

ROOT=Path(__file__).resolve().parents[2]
A1=ROOT/'reading/french/a1/passages.jsonl'
CANON=ROOT/'reading/french/a2/passages.jsonl'
SCHEMA=ROOT/'reading/schema/passage.schema.json'
LEX=ROOT/'french_top1000.csv'
EXPECTED_BLOB='1606e3a560c830855d3c2a10d1d027cbab564b14'
FORMS=('oublier','clé','perdre','retrouver','recevoir','envoyer','vérifier','payer','numéro','carte')
REVIEW_PAIRS=(('raison','résultat'),('décision','information'),('important','différent'),('habitude','expérience'),('choix','idée'))

def deck():
 out={}
 with LEX.open(encoding='utf-8',newline='') as f:
  for row in csv.DictReader(f):
   form=(row.get('Front') or '').strip();b=row.get('Back') or ''
   mr=re.search(r'Rank:\s*(\d+)',b);mm=re.search(r'Meaning:\s*(.+)',b);mp=re.search(r'Part of speech:\s*(.+)',b)
   if form and mr and mm and mp:out[form]={'rank':int(mr.group(1)),'sense':mm.group(1).strip(),'pos':mp.group(1).strip()}
 return out
def tid(r):return f'fr-rank-{r:04d}'
def cnt(text,f):return len(re.findall(rf'(?<!\w){re.escape(f)}(?!\w)',text,flags=re.I|re.UNICODE))
def prior(rows):
 d={}
 for r in rows:
  for t in r.get('new_lexical_targets',[]):
   if isinstance(t,dict) and t.get('form'):d.setdefault(t['form'],[]).append(t)
 return d
def nt(f,text,D):
 s=D[f];n=cnt(text,f)
 if n<1:raise AssertionError(f'{f}: no exact new-target exposure')
 return {'id':tid(s['rank']),'form':f,'lemma':f,'intended_sense':s['sense'],'part_of_speech':s['pos'],'register':'contemporary standard','variety':None,'context_strategy':['scenario_resolution'],'first_introduced':True,'exposures_in_text':n,'source_lexicon':'french_top1000.csv','source_rank':s['rank'],'beyond_base':False}
def rev(f,P):
 h=P.get(f,[])
 if len(h)!=1:raise AssertionError(f'{f}: expected one prior deliberate target, got {len(h)}')
 return {'id':h[0]['id'],'form':f,'review_stage':'R2','representation':'running_text','expected_exposure_number':None}
def cur(f,D):return {'id':tid(D[f]['rank']),'form':f,'review_stage':'R1','representation':'summary','expected_exposure_number':None}
def qa(items,ids):
 q=[];a=[]
 for i,(typ,prompt,answer,forms) in enumerate(items,1):
  qi=f'q{i}';ai=f'a{i}';x={'id':qi,'type':typ,'prompt':prompt,'answer_id':ai}
  if forms:x['target_ids']=[ids[f] for f in forms]
  q.append(x);a.append({'id':ai,'question_id':qi,'answer':answer,'explanation':''})
 return q,a
def mk(s,new,reviews,ids,speed=False):
 q,a=qa(s['items'],ids);text=s['text']
 return {'id':s['id'],'language':'fr','cefr':'A2','unit':3,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'Generation-stage French A2 Unit 03; final language-wide audit deferred.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French A2 Unit 03 generation batch.','A1+A2 freshness, source identity, A2 word band, exact review visibility, local target linkage, continuity and zero-new checkpoint are enforced.']},'paired_text_group':None,'prerequisites':['French A2 Units 01-02 canonical corpus'],'difficulty_notes_internal':'A2 practical problems and information handling with explicit cause/effect and reference chains.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_a2_u03']}

def specs():
 return [
 {'id':'fr-a2-u03-p01','sequence':13,'ptype':'instructional','title':'La clé restée à la maison','genre':'routine problem narrative','domains':['personal','public'],'topics':['forgotten item','key','problem solving'],'forms':['oublier','clé'],'reviews':['raison','résultat'],'text':'''Mardi matin, Camille quitte son appartement en pensant à son cours. Arrivée au coin de la rue, elle touche la petite poche de son sac et comprend qu’elle vient d’oublier sa clé sur la table. La raison est simple : elle a changé de sac la veille et n’a pas suivi sa routine habituelle. Elle hésite à retourner chez elle, car elle ne veut pas arriver en retard. Elle appelle donc sa mère, qui est encore dans l’immeuble. Celle-ci descend avec la clé cinq minutes plus tard. Le résultat est meilleur que Camille ne le craignait : elle récupère la clé et atteint l’arrêt avant le prochain bus. Le soir, elle choisit une poche fixe pour cet objet et place une courte note près de la porte. Elle ne pense pas qu’une note empêchera toujours d’oublier quelque chose, mais elle veut réduire les oublis quand sa routine change.''','grammar':[{'id':'fr-a2-u03-venir-de','role':'new','description':'use venir de + infinitive for a recent realization'}],'discourse':[{'id':'fr-a2-u03-cause-action-result','role':'new','description':'connect reason, chosen action and observed result'}],'items':[('gist','Quel problème Camille découvre-t-elle dans la rue ?','Elle a oublié sa clé à la maison.',['oublier','clé']),('literal_detail','Qui lui apporte la clé ?','Sa mère.',['clé']),('sequence','Que fait Camille après avoir compris le problème ?','Elle appelle sa mère.',[]),('cause_effect','Quelle raison explique l’oubli ?','Elle a changé de sac et n’a pas suivi sa routine habituelle.',['raison','oublier']),('vocabulary_in_context','Que signifie « oublier » ici ?','Partir sans prendre quelque chose qu’on devait emporter.',['oublier']),('vocabulary_in_context','Que désigne la « clé » ?','L’objet utilisé pour ouvrir la porte de son appartement.',['clé']),('reference_resolution','Dans « celle-ci descend », à qui renvoie « celle-ci » ?','À la mère de Camille.',[]),('inference','Pourquoi choisit-elle une poche fixe le soir ?','Pour réduire le risque d’oublier sa clé quand sa routine change.',['oublier','clé']),('cloze_transfer','Complète : Je suis parti sans mon cahier ; j’ai dû l’_____.','oublier',['oublier']),('cloze_transfer','Complète : Je ne peux pas ouvrir cette porte sans la _____.','clé',['clé'])]},
 {'id':'fr-a2-u03-p02','sequence':14,'ptype':'reinforcement','title':'Le cahier perdu','genre':'lost-and-found narrative','domains':['educational','personal'],'topics':['lost item','search','information'],'forms':['perdre','retrouver'],'reviews':['décision','information'],'text':'''Après le cours, Camille veut relire ses notes, mais son cahier bleu n’est plus dans son sac. Elle pense qu’elle a pu le perdre pendant la journée. Avant de prendre une décision, elle rassemble l’information dont elle se souvient : elle avait le cahier en classe, puis à la bibliothèque, mais pas au café. Sami propose de retourner directement dans tous ces lieux. Camille préfère d’abord demander au bureau des objets trouvés. La responsable écoute sa description et sort un cahier bleu d’une boîte. Camille reconnaît son nom et peut enfin retrouver ses notes. Cette information confirme qu’une autre personne avait rapporté le cahier peu après le déjeuner. Camille est soulagée, mais elle réfléchit aussi à sa méthode. Chercher partout aurait été possible ; décrire précisément l’objet et demander au bon service a simplement rendu la recherche plus rapide. Elle ajoute ensuite son numéro de téléphone à l’intérieur du cahier.''','grammar':[{'id':'fr-a2-u03-avoir-pu','role':'new','description':'use avoir pu + infinitive for a plausible past possibility'}],'discourse':[{'id':'fr-a2-u03-search-evidence','role':'new','description':'use remembered information to choose a search strategy'}],'items':[('gist','Quel objet Camille cherche-t-elle ?','Son cahier bleu.',[]),('literal_detail','Où le retrouve-t-elle ?','Au bureau des objets trouvés.',['retrouver']),('sequence','Que fait-elle avant de demander au bureau ?','Elle rassemble les informations sur les endroits où elle avait le cahier.',['information']),('cause_effect','Pourquoi choisit-elle le bureau des objets trouvés ?','Parce qu’elle veut utiliser une recherche plus ciblée avant de parcourir tous les lieux.',[]),('vocabulary_in_context','Que signifie « perdre » ici ?','Ne plus savoir où se trouve un objet qu’on avait.',['perdre']),('vocabulary_in_context','Que signifie « retrouver » ?','Trouver de nouveau un objet qui avait été perdu.',['retrouver']),('reference_resolution','Dans « cette information confirme », que désigne « cette information » ?','Le fait qu’une autre personne avait rapporté le cahier.',[]),('inference','Pourquoi ajoute-t-elle son numéro dans le cahier ?','Pour faciliter son retour si elle le perd encore.',['perdre']),('cloze_transfer','Complète : Je ne trouve plus mon portefeuille ; je crois l’avoir _____.','perdu',['perdre']),('cloze_transfer','Complète : Après la recherche, j’espère _____ mon livre.','retrouver',['retrouver'])]},
 {'id':'fr-a2-u03-p03','sequence':15,'ptype':'interleaved','title':'Le fichier manquant','genre':'digital communication narrative','domains':['educational','personal'],'topics':['sending','receiving','verification'],'forms':['recevoir','envoyer'],'reviews':['important','différent'],'text':'''Vendredi, Sami doit envoyer à Camille un fichier pour leur projet. Le document est important parce qu’ils doivent le présenter le lendemain. Sami utilise d’abord l’application habituelle, mais Camille ne reçoit rien. Ils essaient alors un moyen différent : le courriel. Cette fois, Camille peut recevoir le message, mais la pièce jointe manque. Elle répond immédiatement et Sami vérifie ce qu’il a envoyé. Il comprend qu’il a sélectionné le mauvais brouillon. Il doit donc envoyer un nouveau message avec le bon fichier. Quelques secondes plus tard, Camille confirme qu’elle a pu le recevoir et l’ouvrir. Les deux élèves décident ensuite d’utiliser des noms de fichiers plus précis et de demander une confirmation quand un document est important. Ils constatent qu’un problème d’envoi n’exige pas toujours une solution compliquée : il faut parfois changer de méthode, puis vérifier ce qui a réellement été reçu.''','grammar':[{'id':'fr-a2-u03-devoir-infinitive','role':'new','description':'use devoir + infinitive for necessary corrective action'}],'discourse':[{'id':'fr-a2-u03-message-repair','role':'new','description':'follow failed transmission, feedback and successful retry'}],'items':[('gist','Quel problème Sami et Camille résolvent-ils ?','Le bon fichier n’arrive pas correctement.',[]),('literal_detail','Quelle méthode différente utilisent-ils ?','Le courriel.',['différent']),('sequence','Que remarque Camille après avoir reçu le premier courriel ?','La pièce jointe manque.',['recevoir']),('cause_effect','Pourquoi Sami envoie-t-il un nouveau message ?','Parce qu’il avait choisi le mauvais brouillon.',['envoyer']),('vocabulary_in_context','Que signifie « envoyer » ici ?','Faire parvenir un message ou un fichier à quelqu’un.',['envoyer']),('vocabulary_in_context','Que signifie « recevoir » ?','Obtenir un message ou un fichier envoyé par quelqu’un.',['recevoir']),('reference_resolution','Dans « ce qu’il a envoyé », à qui renvoie « il » ?','À Sami.',['envoyer']),('inference','Pourquoi demandent-ils une confirmation pour les documents importants ?','Pour savoir si le destinataire a réellement reçu et ouvert le bon fichier.',['important','recevoir']),('cloze_transfer','Complète : Je vais _____ le fichier par courriel.','envoyer',['envoyer']),('cloze_transfer','Complète : Dis-moi quand tu vas _____ mon message.','recevoir',['recevoir'])]},
 {'id':'fr-a2-u03-p04','sequence':16,'ptype':'transfer','title':'Vérifier avant de payer','genre':'practical purchase narrative','domains':['public','personal'],'topics':['checking','payment','routine'],'forms':['vérifier','payer'],'reviews':['habitude','expérience'],'text':'''Samedi, Camille retourne à l’atelier de réparation avec une habitude nouvelle : elle lit le reçu avant de sortir sa carte. Son expérience précédente lui a montré qu’une petite erreur peut changer le total. Cette fois, le technicien lui présente le prix d’une pièce et le coût du travail. Camille prend une minute pour vérifier chaque ligne avant de payer. Elle remarque qu’un service supplémentaire apparaît alors qu’elle ne l’a pas demandé. Le technicien vérifie le dossier et confirme qu’il a été ajouté par erreur. Il corrige le reçu, puis Camille peut payer le montant exact. Elle ne considère pas cette vérification comme un signe de méfiance ; pour elle, c’est simplement une étape pratique. Le technicien est d’accord et lui conseille de garder le reçu. Camille repart en pensant qu’une bonne habitude se construit souvent après une expérience concrète, surtout quand elle permet d’éviter une confusion sans créer de conflit.''','grammar':[{'id':'fr-a2-u03-avant-de','role':'new','description':'use avant de + infinitive to order practical actions'}],'discourse':[{'id':'fr-a2-u03-check-correct-pay','role':'new','description':'follow check, discrepancy, correction and payment'}],'items':[('gist','Pourquoi Camille lit-elle le reçu avant de payer ?','Pour vérifier que les informations et le total sont corrects.',['vérifier','payer']),('literal_detail','Quelle anomalie trouve-t-elle ?','Un service supplémentaire qu’elle n’a pas demandé.',[]),('sequence','Que fait le technicien après sa remarque ?','Il vérifie le dossier et corrige le reçu.',['vérifier']),('cause_effect','Pourquoi le total change-t-il ?','Parce qu’un service avait été ajouté par erreur.',[]),('vocabulary_in_context','Que signifie « vérifier » ici ?','Examiner les informations pour contrôler qu’elles sont correctes.',['vérifier']),('vocabulary_in_context','Que signifie « payer » ?','Donner la somme demandée pour un bien ou un service.',['payer']),('grammar_in_context','Dans « avant de payer », quelle action doit arriver d’abord ?','La vérification du reçu.',['payer']),('inference','Pourquoi Camille ne voit-elle pas la vérification comme de la méfiance ?','Parce qu’elle la considère comme une étape pratique normale.',[]),('cloze_transfer','Complète : Je veux _____ le total avant de sortir ma carte.','vérifier',['vérifier']),('cloze_transfer','Complète : Après le repas, nous allons _____ l’addition.','payer',['payer'])]},
 {'id':'fr-a2-u03-p05','sequence':17,'ptype':'integration','title':'Le bon numéro sur la carte','genre':'appointment information narrative','domains':['public','personal'],'topics':['appointment','number','card'],'forms':['numéro','carte'],'reviews':['choix','idée'],'text':'''Lundi, Camille arrive dans un centre où plusieurs services utilisent la même carte d’accueil. Elle a le choix entre deux files et demande une idée à l’employée près de l’entrée. Celle-ci lui explique qu’il faut d’abord regarder le numéro de dossier sur sa carte. Camille lit le premier numéro qu’elle voit, mais il correspond au bâtiment, pas à son dossier. L’employée lui montre un second numéro imprimé sous son nom. Avec ce numéro, elle retrouve immédiatement le rendez-vous de Camille dans le système. Camille comprend alors pourquoi plusieurs numéros peuvent apparaître sur une même carte : chacun sert à une fonction différente. Elle prend une photo du numéro utile et garde la carte dans une poche précise de son portefeuille. Son choix de file devient ensuite évident. Cette petite situation lui rappelle qu’une bonne idée ne suffit pas toujours ; il faut aussi identifier exactement l’information demandée avant d’agir.''','grammar':[{'id':'fr-a2-u03-chacun','role':'new','description':'use chacun to refer back to multiple items individually'}],'discourse':[{'id':'fr-a2-u03-reference-disambiguation','role':'new','description':'distinguish several reference numbers on one document'}],'items':[('gist','Quelle information Camille doit-elle trouver ?','Le bon numéro de dossier sur sa carte.',['numéro','carte']),('literal_detail','À quoi correspond le premier numéro qu’elle lit ?','Au bâtiment.',['numéro']),('sequence','Que fait l’employée après que Camille lit le mauvais numéro ?','Elle lui montre le numéro imprimé sous son nom.',['numéro']),('cause_effect','Pourquoi le rendez-vous apparaît-il ensuite dans le système ?','Parce que l’employée utilise le bon numéro de dossier.',['numéro']),('vocabulary_in_context','Que signifie « numéro » ici ?','Une suite de chiffres utilisée pour identifier un dossier.',['numéro']),('vocabulary_in_context','Que désigne la « carte » ?','Le document d’accueil qui contient plusieurs informations.',['carte']),('reference_resolution','Dans « chacun sert à une fonction différente », à quoi renvoie « chacun » ?','À chacun des numéros.',['numéro']),('inference','Pourquoi Camille photographie-t-elle le numéro utile ?','Pour pouvoir retrouver rapidement l’information plus tard.',['numéro']),('cloze_transfer','Complète : Quel est votre _____ de dossier ?','numéro',['numéro']),('cloze_transfer','Complète : Je garde cette _____ dans mon portefeuille.','carte',['carte'])]}
 ]

def checkpoint():
 return {'id':'fr-a2-u03-p06','sequence':18,'ptype':'checkpoint','title':'Contrôler l’information utile','genre':'cumulative practical-strategy summary','domains':['personal','educational','public'],'topics':['problem solving','information','verification'],'text':'''Dans les situations récentes, Camille apprend à traiter les petits problèmes de façon plus organisée. Si elle risque d’oublier une clé, elle choisit un endroit fixe pour la ranger. Quand elle pense perdre un objet, elle décrit ce qu’elle cherche afin de pouvoir le retrouver. Pour un projet, elle peut envoyer un fichier et demander à l’autre personne de confirmer qu’elle a pu le recevoir. Avant un achat ou un service, Camille préfère vérifier les informations avant de payer. Lorsqu’un accueil lui demande un numéro, elle regarde attentivement quel numéro se trouve sur la bonne carte. Ces actions ont un point commun : Camille ne réagit plus seulement à la première impression. Elle identifie d’abord l’information utile, choisit une action, puis contrôle le résultat. Cette méthode ne supprime pas tous les problèmes, mais elle réduit les erreurs et l’aide à expliquer plus clairement pourquoi une solution a fonctionné dans une situation précise.''','grammar':[{'id':'fr-a2-u03-condition-purpose-review','role':'integration','description':'integrate conditional and purpose expressions'}],'discourse':[{'id':'fr-a2-u03-identify-act-check','role':'integration','description':'summarize identify-act-check as a practical problem-solving cycle'}],'items':[('gist','Quelle méthode générale Camille développe-t-elle ?','Elle identifie l’information utile, agit, puis contrôle le résultat.',[]),('literal_detail','Que fait-elle pour une clé qu’elle risque d’oublier ?','Elle choisit un endroit fixe pour la ranger.',['oublier','clé']),('vocabulary_in_context','Que signifie « retrouver » dans ce résumé ?','Trouver de nouveau un objet qu’on ne trouvait plus.',['retrouver']),('vocabulary_in_context','Que signifie « recevoir » ici ?','Obtenir un fichier envoyé par une autre personne.',['recevoir','envoyer']),('cause_effect','Pourquoi vérifie-t-elle avant de payer ?','Pour réduire le risque d’une information ou d’un montant incorrect.',['vérifier','payer']),('single_word_definition','Que signifie « perdre » ici ?','Ne plus savoir où se trouve un objet qu’on avait.',['perdre']),('reference_resolution','Dans « quel numéro se trouve sur la bonne carte », quel élément doit-elle identifier ?','Le numéro utile demandé par le service.',['numéro','carte']),('contrast','Lequel décrit l’action de faire partir un fichier : « envoyer » ou « recevoir » ?','envoyer',['envoyer','recevoir']),('cloze_transfer','Complète : Avant de _____, je contrôle le total.','payer',['payer']),('summary','Résume le cycle de résolution présenté.','Identifier l’information utile, choisir une action, puis vérifier ce qui s’est produit.',[])]}

def build(a1,a2,D):
 P=prior(a1+a2);fail=[]
 for f in FORMS:
  if f not in D:fail.append(f'{f}:missing_lexicon')
  if P.get(f):fail.append(f'{f}:already_scheduled')
 if fail:raise AssertionError('freshness/source failures: '+', '.join(fail))
 out=[]
 for s in specs():
  new=[nt(f,s['text'],D) for f in s['forms']];reviews=[rev(f,P) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};out.append(mk(s,new,reviews,ids))
 cp=checkpoint();reviews=[cur(f,D) for f in FORMS];ids={t['form']:t['id'] for t in reviews};out.append(mk(cp,[],reviews,ids,True));return out

def main():
 blob=subprocess.check_output(['git','hash-object',str(CANON)],text=True).strip()
 if blob!=EXPECTED_BLOB:raise AssertionError(f'A2 canonical blob drift: {blob} != {EXPECTED_BLOB}')
 a1=[json.loads(x) for x in A1.read_text(encoding='utf-8').splitlines() if x.strip()];a2=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(a1)!=60 or a1[-1]['id']!='fr-a1-u10-p06':raise AssertionError('unexpected A1 prerequisite state')
 if len(a2)!=12 or [r['sequence'] for r in a2]!=list(range(1,13)) or a2[-1]['id']!='fr-a2-u02-p06':raise AssertionError('expected exact A2 Unit02 frontier')
 D=deck();unit=build(a1,a2,D);V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));old={t['id'] for r in a1+a2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict) and t.get('id')}
 if [r['sequence'] for r in unit]!=list(range(13,19)) or [r['id'] for r in unit]!=[f'fr-a2-u03-p{i:02d}' for i in range(1,7)]:raise AssertionError('Unit03 continuity failure')
 newids=[]
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:6]]}")
  if not 140<=r['word_count']<=220:raise AssertionError(f"{r['id']}: A2 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: assessment count")
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
  for t in r['new_lexical_targets']:
   s=D.get(t['form'])
   if t['id'] in old or not s or t['source_rank']!=s['rank'] or t['id']!=tid(s['rank']) or cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: source/exposure/reintroduction drift {t}")
   newids.append(t['id'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=10 or len(set(newids))!=10 or unit[-1]['new_lexical_targets']!=[]:raise AssertionError('Unit03 lexical-cycle invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in a2+unit),encoding='utf-8')
 print(json.dumps({'status':'PASS','level':'A2','unit':3,'appended_passages':6,'a2_passages':18,'word_counts':{r['id']:r['word_count'] for r in unit},'new_targets':[{'form':f,'rank':D[f]['rank'],'id':tid(D[f]['rank'])} for f in FORMS],'questions':60,'answers':60,'p06_new_targets':0},ensure_ascii=False))
if __name__=='__main__':main()
