#!/usr/bin/env python3
"""Append French B2 Unit 02 (sequences 7-12): decision under uncertainty.

Uses the accepted B2 default of four fresh deliberate targets in P01-P05;
P06 has zero new targets. All source/freshness, schema/linkage, word-band and
exact-review guards remain fail-closed.
"""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base

REPO=Path(__file__).resolve().parents[2]
A1=REPO/'reading/french/a1/passages.jsonl'; A2=REPO/'reading/french/a2/passages.jsonl'; B1=REPO/'reading/french/b1/passages.jsonl'; CANON=REPO/'reading/french/b2/passages.jsonl'; SCHEMA=REPO/'reading/schema/passage.schema.json'
EXPECTED={'A1':'0493a2fa13e51b5997db05e91cdea4d8dc5e647b','A2':'d0a80b8866071f426019aa0ad143e1d270dba4de','B1':'4a2cd9ff30c3cea58caf20fca2822b06200622ca','B2':'1ba43c900ad64ff9359264e743470138ce25a9c5'}
FORMS=('promettre','avenir','attendre','confiance','grave','calmer','solution','responsabilité','partager','opinion','secret','surtout','ordre','lieu','coût','préférer','ramener','pareil','lumière','pousser')

SPECS=[
{
'id':'fr-b2-u02-p01','sequence':7,'ptype':'instructional','title':'Promettre une date quand l’avenir dépend encore d’un fournisseur','genre':'decision memo','domains':['professional','public'],'topics':['decision under uncertainty','forecasting','commitment'],'forms':['promettre','avenir','attendre','confiance'],'reviews':['supposer','cause','effet','preuve'],'paragraphs':[
"Une association prépare l’ouverture d’un atelier public, mais une pièce essentielle doit encore arriver d’un fournisseur. Le comité de communication veut annoncer une date ferme afin de rassurer les participants. Camille propose de distinguer trois choses : ce que l’équipe espère, ce qu’elle peut promettre et ce qu’elle devra peut-être attendre. Le fournisseur annonce une livraison « probablement mardi », sans garantie contractuelle. Supposer que cette date sera respectée peut être raisonnable pour organiser le travail interne, mais ce n’est pas encore une preuve suffisante pour promettre au public une ouverture mercredi. La cause d’un éventuel retard peut en outre se trouver hors du contrôle de l’association.",
"Le directeur craint qu’une formulation prudente réduise la confiance. Camille répond que l’effet inverse est possible : annoncer une certitude fragile peut produire davantage de déception si la date change. Elle propose donc deux niveaux d’engagement. L’équipe peut annoncer son objectif pour l’avenir — ouvrir dans la seconde moitié du mois — puis promettre une date précise seulement après réception et test de la pièce. Entre-temps, elle peut préparer le reste du matériel au lieu d’attendre sans agir. Cette stratégie ne supprime pas l’incertitude ; elle évite simplement de la transformer en promesse.",
"Le comité examine ensuite un scénario plus favorable et un scénario moins favorable. Si la pièce arrive mardi et passe le test, l’ouverture peut être confirmée immédiatement. Si elle arrive plus tard, l’association conserve quelques jours de marge. La confiance repose alors sur une règle explicite : chaque annonce correspond au niveau de preuve disponible au moment où elle est faite. Camille insiste sur le fait que promettre n’est pas synonyme de prévoir. Une prévision décrit ce qui semble probable ; une promesse crée une attente envers les autres et augmente la responsabilité de celui qui parle.",
"La note finale recommande donc une communication en deux étapes. Elle explique la cause possible du décalage sans accuser le fournisseur, précise l’effet qu’aurait un retard sur le calendrier et indique la preuve attendue avant confirmation. Le public n’a pas besoin de connaître chaque détail logistique, mais il doit pouvoir comprendre pourquoi l’association préfère attendre une vérification avant de promettre. Pour Camille, protéger la confiance dans l’avenir ne consiste pas à paraître certain plus tôt ; cela consiste à rendre visible le moment où une hypothèse devient un engagement."
],
'grammar':[{'id':'fr-b2-u02-promise-vs-forecast','role':'new','description':'contrast forecast language with promise/commitment and conditional future scenarios'}],
'discourse':[{'id':'fr-b2-u02-commitment-threshold','role':'new','description':'separate forecast, evidence threshold and public commitment under uncertain timing'}],
'items':[
('main_claim','Quelle règle principale le mémo recommande-t-il ?','Ne promettre une date précise qu’une fois le seuil de preuve atteint, tout en communiquant honnêtement l’objectif futur.',['promettre','preuve','avenir']),
('literal_detail','Quelle information le fournisseur donne-t-il ?','Une livraison probablement mardi, sans garantie contractuelle.',['attendre']),
('argument_relation','Pourquoi le texte oppose-t-il prévision et promesse ?','Une prévision décrit ce qui paraît probable, tandis qu’une promesse crée une attente et un engagement envers les autres.',['promettre']),
('vocabulary_in_context','Que signifie « confiance » dans ce passage ?','La fiabilité que le public attribue aux annonces et engagements de l’association.',['confiance']),
('vocabulary_in_context','Que signifie « attendre » dans la stratégie proposée ?','Retarder une promesse précise jusqu’à la vérification, sans cesser les autres préparatifs.',['attendre']),
('assumption','Quelle supposition rendrait l’annonce de mercredi prématurée ?','Supposer que la livraison annoncée comme probable aura nécessairement lieu mardi et que la pièce passera le test.',['supposer']),
('inference','Pourquoi une formulation prudente peut-elle renforcer la confiance ?','Parce qu’elle réduit le risque de devoir retirer une promesse présentée trop tôt comme certaine.',['confiance','promettre']),
('reference_resolution','Dans « l’effet inverse est possible », quel effet est visé ?','La perte de confiance provoquée par une certitude fragile qui doit ensuite être corrigée.',['effet','confiance']),
('stance','Quelle position le texte adopte-t-il envers l’incertitude de calendrier ?','Il défend une communication graduée : agir et prévoir dès maintenant, mais attendre la preuve avant de promettre précisément.',['attendre','preuve']),
('summary','Résume la décision en une phrase.','L’association peut supposer un scénario pour préparer l’avenir, mais elle préfère attendre une preuve avant de promettre afin de préserver la confiance et de limiter l’effet d’un retard dont la cause reste incertaine.',['supposer','avenir','attendre','preuve','promettre','confiance','effet','cause'])]
},
{
'id':'fr-b2-u02-p02','sequence':8,'ptype':'reinforcement','title':'Un incident grave : calmer avant de choisir une solution','genre':'incident response analysis','domains':['professional','public'],'topics':['decision under uncertainty','incident response','reversibility'],'forms':['grave','calmer','solution','responsabilité'],'reviews':['sécurité','protéger','suffire','moyen'],'paragraphs':[
"Dans un centre sportif, une alarme signale une fuite d’eau près d’un local technique. Personne ne sait encore si la fuite touche une conduite principale ou un équipement secondaire. Le responsable ferme l’accès à la zone, mais refuse de qualifier immédiatement la situation de catastrophe. Elle peut être grave, car l’eau se rapproche d’installations électriques, sans que l’étendue du problème soit encore connue. Sa première responsabilité est de protéger les usagers et le personnel. Il cherche donc un moyen de sécuriser la zone avant de choisir une solution de réparation.",
"Une collègue propose de couper toute l’eau du bâtiment. Cette action pourrait suffire à arrêter la fuite, mais elle interromprait aussi les douches, les sanitaires et plusieurs activités. Un technicien suggère au contraire d’isoler d’abord le secteur concerné. Le responsable demande quelques minutes pour calmer le groupe et vérifier le plan des conduites. Calmer ne signifie pas minimiser un incident grave ; cela signifie réduire le bruit décisionnel afin que les informations puissent être comparées. L’équipe cherche une option réversible : si l’isolement local fonctionne, elle évite une interruption générale ; sinon, la coupure complète reste disponible.",
"Le technicien localise finalement une vanne de secteur et ferme la conduite concernée. La fuite ralentit immédiatement. Cette solution ne règle pas encore la cause, mais elle protège assez la zone pour permettre une inspection. Le responsable explique pourquoi il n’a pas choisi le moyen le plus radical dès le départ. Lorsque le temps le permet, une décision réversible conserve des options : elle peut suffire à réduire le risque tout en laissant possible une intervention plus forte. En revanche, si l’eau avait déjà atteint un équipement électrique, la sécurité aurait pu justifier une coupure plus large sans attendre davantage.",
"L’analyse après incident distingue donc gravité et certitude. Un problème peut être grave parce que ses conséquences possibles sont importantes, même si sa cause exacte reste inconnue. La responsabilité consiste alors à agir sur ce qui est suffisamment établi — protéger les personnes, limiter l’exposition — tout en gardant la solution proportionnée à l’information disponible. Camille retient qu’il n’existe pas toujours un moyen unique de décider sous incertitude. Il faut parfois calmer, choisir une première action réversible, puis renforcer la réponse si les nouvelles données montrent qu’elle ne peut pas suffire."
],
'grammar':[{'id':'fr-b2-u02-reversible-escalation','role':'new','description':'contrast reversible first action with conditional escalation using si/sinon and modal sufficiency'}],
'discourse':[{'id':'fr-b2-u02-gravity-certainty','role':'new','description':'separate consequence severity from diagnostic certainty and assign responsibility accordingly'}],
'items':[
('main_claim','Quelle méthode de réponse le texte défend-il ?','Protéger d’abord, calmer le processus décisionnel puis choisir une solution proportionnée et réversible quand le temps le permet.',['protéger','calmer','solution']),
('literal_detail','Quelle première action technique est finalement choisie ?','Fermer la vanne du secteur concerné pour isoler localement la fuite.',['solution']),
('argument_relation','Pourquoi la coupure générale n’est-elle pas choisie immédiatement ?','Elle pourrait suffire, mais son coût opérationnel est plus élevé et une solution locale réversible peut d’abord protéger la zone.',['suffire','moyen']),
('vocabulary_in_context','Que signifie « grave » ici ?','Capable d’avoir des conséquences importantes, même si la cause exacte reste incertaine.',['grave']),
('vocabulary_in_context','Que signifie « responsabilité » dans l’analyse ?','L’obligation d’agir sur les risques établis tout en justifiant la portée de la réponse.',['responsabilité']),
('assumption','Quelle condition rend l’isolement local raisonnable ?','Que l’équipe dispose de quelques minutes pour vérifier la zone et que la sécurité immédiate ne nécessite pas encore une coupure générale.',['sécurité']),
('inference','Pourquoi une action réversible est-elle utile sous incertitude ?','Elle réduit le risque tout en conservant la possibilité d’une intervention plus forte si elle ne suffit pas.',['suffire','solution']),
('reference_resolution','Dans « elle protège assez la zone », à quoi renvoie « elle » ?','À la solution d’isolement local de la conduite.',['solution','protéger']),
('stance','Quelle position le texte adopte-t-il envers les réponses radicales ?','Elles peuvent être nécessaires si la sécurité l’exige, mais ne doivent pas être choisies automatiquement lorsqu’un moyen plus proportionné suffit.',['sécurité','moyen']),
('summary','Résume l’analyse.','Face à un incident grave, la responsabilité est de calmer sans minimiser, protéger la sécurité, tester une solution réversible et n’élargir le moyen d’action que si la première réponse ne peut pas suffire.',['grave','responsabilité','calmer','protéger','sécurité','solution','moyen','suffire'])]
},
{
'id':'fr-b2-u02-p03','sequence':9,'ptype':'interleaved','title':'Partager une information sans transformer une opinion en secret','genre':'public information ethics analysis','domains':['public','educational'],'topics':['decision under uncertainty','information ethics','preliminary findings'],'forms':['partager','opinion','secret','surtout'],'reviews':['public','apporter','libre','accepter'],'paragraphs':[
"Une équipe universitaire termine une enquête préliminaire sur les habitudes de déplacement dans une ville. Les résultats définitifs ne sont pas prêts, mais un journaliste demande déjà un commentaire. Certains chercheurs veulent partager les tendances principales afin que le public comprenne les questions étudiées. D’autres craignent qu’une donnée provisoire soit reprise comme conclusion certaine. Le désaccord porte surtout sur la manière de communiquer sous incertitude : faut-il attendre, ou partager avec des limites explicites ? Le projet est financé publiquement, mais cela ne signifie pas que chaque fichier de travail doit devenir immédiatement libre d’accès.",
"Camille propose de séparer trois catégories. Les méthodes et les questions peuvent être partagées sans difficulté. Les résultats agrégés peuvent aussi être présentés s’ils sont clairement qualifiés de provisoires. En revanche, certaines réponses individuelles doivent rester confidentielles. Elles ne constituent pas un secret au sens d’une information cachée pour protéger le projet ; elles sont protégées parce que les participants ont accepté une condition de confidentialité. Cette distinction est importante : appeler toute information non publiée « secret » peut laisser croire que l’équipe refuse le contrôle public, alors que certaines limites servent à protéger les personnes.",
"Le groupe discute ensuite de l’opinion des chercheurs. Une scientifique peut avoir une opinion sur l’explication la plus plausible, surtout lorsqu’elle connaît bien le terrain. Mais son expertise n’autorise pas à présenter cette opinion comme un résultat déjà démontré. Elle peut apporter une interprétation au débat à condition d’indiquer ce qui vient des données et ce qui reste une lecture personnelle. Le public peut alors accepter ou contester l’argument sans confondre le statut des énoncés. Une communication honnête ne rend pas chaque phrase également incertaine ; elle classe les affirmations selon la force de leur soutien.",
"La réponse au journaliste suit cette structure. L’équipe choisit de partager les objectifs, la méthode et deux tendances agrégées, tout en expliquant que l’analyse continue. Elle ne publie aucun dossier individuel et précise que les commentaires des chercheurs expriment encore une opinion. Camille conclut que l’ouverture ne s’oppose pas automatiquement à la retenue. Une information peut être librement discutée sans que toute donnée devienne publique, et une donnée peut rester protégée sans être un secret arbitraire. Surtout, décider quoi partager exige de distinguer la valeur scientifique, le droit des participants et le risque de créer une certitude prématurée."
],
'grammar':[{'id':'fr-b2-u02-information-status','role':'new','description':'contrast reporting verbs and qualification markers for data, opinion and confidential material'}],
'discourse':[{'id':'fr-b2-u02-disclosure-status','role':'new','description':'classify information by evidential status, privacy obligation and public communicability'}],
'items':[
('main_claim','Quelle distinction principale organise la politique de communication ?','Il faut séparer ce qui peut être partagé publiquement, ce qui relève d’une opinion provisoire et ce qui reste protégé par confidentialité.',['partager','opinion','secret','public']),
('literal_detail','Quelles informations l’équipe décide-t-elle de partager avec le journaliste ?','Les objectifs, la méthode et deux tendances agrégées provisoires.',['partager']),
('argument_relation','Pourquoi le texte refuse-t-il d’appeler toute donnée non publiée un « secret » ?','Parce que certaines informations sont retenues pour protéger les participants, non pour éviter le contrôle public.',['secret','protéger']),
('vocabulary_in_context','Que signifie « opinion » dans le texte ?','Une interprétation ou position du chercheur qui doit être distinguée d’un résultat démontré.',['opinion']),
('vocabulary_in_context','Quel rôle joue « surtout » ?','Il met l’accent sur le point le plus important de la décision de communication.',['surtout']),
('assumption','Quelle condition permet de partager des résultats provisoires ?','Leur statut provisoire et leurs limites doivent être indiqués clairement au public.',['partager','public']),
('inference','Pourquoi l’expertise ne suffit-elle pas à transformer une opinion en résultat ?','Parce que l’expérience peut apporter une interprétation sans remplacer les preuves nécessaires à une conclusion.',['opinion','apporter']),
('reference_resolution','Dans « elles sont protégées », à quoi renvoie « elles » ?','Aux réponses individuelles des participants.',['secret']),
('stance','Quelle position le texte adopte-t-il envers l’ouverture des données ?','Il soutient une ouverture structurée : partager ce qui peut l’être, accepter le contrôle public, mais préserver les obligations de confidentialité.',['libre','accepter','public']),
('summary','Résume la décision.','L’équipe choisit de partager ce qui peut apporter une compréhension au public, distingue l’opinion du résultat, réserve le mot secret aux bons contextes et insiste surtout sur les limites acceptées de confidentialité et d’accès libre.',['partager','apporter','public','opinion','secret','surtout','accepter','libre'])]
},
{
'id':'fr-b2-u02-p04','sequence':10,'ptype':'transfer','title':'Mettre les options en ordre sans croire qu’un seul lieu est certain','genre':'operations planning analysis','domains':['professional','public'],'topics':['decision under uncertainty','event planning','resource allocation'],'forms':['ordre','lieu','coût','préférer'],'reviews':['tromper','certain','général','ressembler'],'paragraphs':[
"Une organisation doit choisir le lieu d’une conférence dont le nombre de participants reste incertain. Trois salles sont disponibles : une petite salle peu coûteuse, une salle moyenne facile d’accès et un grand espace plus cher situé plus loin. Le comité veut mettre les critères en ordre avant de discuter des préférences individuelles. Camille propose de comparer capacité, transport, coût d’annulation et possibilité de modifier la réservation. Le but n’est pas de trouver un lieu « certain », mais de choisir une option qui reste acceptable dans plusieurs scénarios plausibles.",
"Un tableau général peut pourtant tromper s’il réduit chaque critère à une seule note. Deux lieux peuvent se ressembler par leur capacité mais avoir des règles d’annulation très différentes. Le comité distingue donc coût fixe, coût par participant et coût de changement. Certains membres préfèrent la petite salle parce qu’elle paraît financièrement prudente ; d’autres préfèrent la salle moyenne car elle garde davantage de marge. Camille demande à chacun de préciser la condition sous laquelle sa préférence changerait. Cette question transforme une préférence en règle de décision plutôt qu’en simple goût.",
"L’équipe met ensuite les scénarios en ordre : faible participation, participation moyenne, forte participation. Aucun scénario n’est certain, mais certains sont mieux soutenus par les inscriptions actuelles. Si le groupe choisit la salle moyenne, le coût est légèrement supérieur dans le scénario faible, mais le lieu reste utilisable dans le scénario moyen et peut encore être annulé à faible coût. La grande salle n’est avantageuse que si les inscriptions augmentent fortement. Le comité reconnaît ainsi qu’une option peut être dominante dans un scénario sans être la meilleure dans tous.",
"Camille recommande finalement la salle moyenne et explique la logique au lieu de présenter le choix comme évident. Elle préfère payer un coût modéré pour conserver une possibilité d’adaptation. Le raisonnement évite deux illusions : croire qu’un classement général garantit le meilleur résultat, ou croire que deux options qui se ressemblent sur un critère sont réellement pareilles. Sous incertitude, mettre les critères et scénarios en ordre permet de voir ce qui est certain, ce qui ne l’est pas et quel lieu offre le meilleur équilibre entre coût, flexibilité et risque de changement."
],
'grammar':[{'id':'fr-b2-u02-preference-condition','role':'new','description':'express conditional preference and scenario-dependent ranking rather than categorical choice'}],
'discourse':[{'id':'fr-b2-u02-scenario-ranking','role':'new','description':'rank criteria and scenarios, distinguish fixed/variable switching costs, and justify a robust option'}],
'items':[
('main_claim','Comment le texte recommande-t-il de choisir le lieu ?','En mettant critères et scénarios en ordre puis en préférant l’option qui reste acceptable dans plusieurs situations plausibles.',['ordre','lieu','préférer']),
('literal_detail','Quels coûts le comité distingue-t-il ?','Le coût fixe, le coût par participant et le coût de changement ou d’annulation.',['coût']),
('argument_relation','Pourquoi la petite salle n’est-elle pas automatiquement la plus prudente ?','Son faible coût initial peut être compensé par un manque de capacité ou une moindre flexibilité si les inscriptions augmentent.',['coût']),
('vocabulary_in_context','Que signifie « mettre en ordre » dans cette analyse ?','Classer critères et scénarios de façon à rendre les comparaisons explicites.',['ordre']),
('vocabulary_in_context','Que signifie « préférer » ici ?','Choisir une option selon des critères et conditions explicites plutôt que par simple goût.',['préférer']),
('assumption','Quelle hypothèse rend la salle moyenne attrayante ?','Que la flexibilité a une valeur suffisante pour justifier un coût modérément plus élevé dans certains scénarios.',['coût','préférer']),
('inference','Pourquoi deux lieux qui se ressemblent peuvent-ils mener à des décisions différentes ?','Parce que des critères moins visibles, comme l’annulation ou l’accès, changent leur robustesse sous incertitude.',['ressembler']),
('reference_resolution','Dans « certains sont mieux soutenus », à quoi renvoie « certains » ?','À certains scénarios de participation parmi ceux mis en ordre.',['certain','ordre']),
('stance','Quelle position le texte adopte-t-il envers un classement général unique ?','Il le juge potentiellement trompeur s’il masque les conditions qui font varier le meilleur choix.',['général','tromper']),
('summary','Résume la décision.','Le comité met scénarios et critères en ordre, compare le coût de chaque lieu, refuse qu’un tableau général puisse tromper sur ce qui est certain ou seulement ressemblant, puis choisit de préférer la salle moyenne pour sa flexibilité.',['ordre','coût','lieu','général','tromper','certain','ressembler','préférer'])]
},
{
'id':'fr-b2-u02-p05','sequence':11,'ptype':'transfer','title':'Ramener les plantes au même endroit avant de décider ce qui les fait pousser','genre':'experimental decision analysis','domains':['educational'],'topics':['decision under uncertainty','plant experiment','reversibility'],'forms':['ramener','pareil','lumière','pousser'],'reviews':['apprécier','ainsi','valoir','intéresser'],'paragraphs':[
"Une classe étudie de jeunes plantes placées sous différentes conditions de lumière. Après une semaine, un groupe semble pousser plus vite près d’une fenêtre. Plusieurs élèves veulent conclure immédiatement que davantage de lumière explique toute la différence. Camille propose d’apprécier d’abord la qualité de l’expérience. Les pots n’ont pas tous reçu exactement la même quantité d’eau et deux plantes ont été déplacées pendant le nettoyage. Avant de décider si le résultat vaut une conclusion forte, il faut demander si les groupes étaient assez comparables.",
"La classe décide de ramener les pots à un protocole plus régulier. Elle ne peut pas effacer la première semaine, mais elle peut contrôler la suivante : même volume d’eau, même type de pot, horaires fixes et positions définies. « Pareil » devient un mot méthodologique plutôt qu’une impression visuelle. Deux plantes peuvent paraître pareilles sans avoir reçu les mêmes conditions. La lumière reste la variable qui intéresse le groupe, mais son effet ne peut être isolé que si les autres différences sont mieux contrôlées. Ainsi, l’incertitude conduit à améliorer l’essai plutôt qu’à choisir trop tôt une explication.",
"Une difficulté supplémentaire apparaît : faut-il ramener toutes les plantes au même endroit ? Ce choix rendrait les conditions plus uniformes, mais il supprimerait aussi la différence de lumière que l’expérience cherche à tester. Camille distingue donc uniformiser les facteurs secondaires et conserver la variation d’intérêt. Pour faire pousser les plantes dans des conditions comparables, on ne veut pas rendre tout pareil ; on veut rendre pareils les éléments qui ne sont pas la question étudiée. Cette nuance vaut plus qu’une règle mécanique du type « tout doit être identique ».",
"Après une seconde semaine, la différence existe encore mais elle est plus petite. Les élèves ne cherchent pas à sauver la première conclusion. Ils comparent les deux périodes et expliquent ce qui a changé. Camille trouve ce résultat particulièrement intéressant parce qu’il montre la valeur d’une décision réversible : ramener le protocole vers un état plus contrôlé permet de recueillir une nouvelle preuve sans détruire l’expérience. La lumière peut continuer à intéresser la classe, et le fait de pousser plus vite peut rester un indice, mais apprécier le résultat demande de distinguer ce qui vaut comme observation de ce qui vaut comme explication. Ainsi, attendre une meilleure comparaison devient une action scientifique, pas une absence de décision."
],
'grammar':[{'id':'fr-b2-u02-same-vs-controlled','role':'new','description':'contrast pareil/equivalent appearance with controlled sameness and preserved experimental variation'}],
'discourse':[{'id':'fr-b2-u02-reversible-experiment','role':'new','description':'use reversible protocol correction to reduce uncertainty without erasing the variable of interest'}],
'items':[
('main_claim','Quelle stratégie expérimentale Camille recommande-t-elle ?','Ramener les facteurs secondaires à des conditions comparables sans supprimer la variation de lumière que l’on veut étudier.',['ramener','pareil','lumière']),
('literal_detail','Quelles différences compliquent la première semaine ?','Les quantités d’eau ne sont pas identiques et deux plantes ont été déplacées.',['pareil']),
('argument_relation','Pourquoi mettre toutes les plantes au même endroit serait-il une mauvaise correction ?','Cela rendrait la lumière pareille pour tous les groupes et supprimerait précisément la variable étudiée.',['lumière','pareil']),
('vocabulary_in_context','Que signifie « ramener » dans le protocole ?','Rétablir ou remettre les conditions secondaires vers un état défini et comparable.',['ramener']),
('vocabulary_in_context','Que signifie « pousser » ici ?','Grandir, en parlant des plantes observées.',['pousser']),
('assumption','Quelle condition doit être approximativement pareille pour attribuer une différence à la lumière ?','Les facteurs secondaires pertinents, comme l’eau, le pot et l’horaire, doivent être suffisamment comparables.',['pareil','lumière']),
('inference','Pourquoi la seconde semaine, même moins spectaculaire, peut-elle être plus informative ?','Parce qu’elle repose sur un protocole mieux contrôlé et réduit plusieurs explications concurrentes.',['apprécier']),
('reference_resolution','Dans « cette nuance vaut plus qu’une règle mécanique », quelle nuance est visée ?','La distinction entre rendre comparables les facteurs secondaires et conserver la variable que l’on veut tester.',['valoir']),
('stance','Quelle position le texte adopte-t-il envers l’attente ?','Il la présente comme une action justifiée lorsqu’elle permet d’obtenir une comparaison plus informative avant de conclure.',['ainsi']),
('summary','Résume l’expérience.','La classe choisit de ramener les conditions secondaires vers un protocole pareil, garde la lumière comme variable qui peut intéresser, observe comment les plantes peuvent pousser, puis apprend à apprécier ce qui vaut comme observation et ce qui vaut comme explication.',['ramener','pareil','lumière','pousser','intéresser','apprécier','valoir','ainsi'])]
}
]

CHECKPOINT={
'id':'fr-b2-u02-p06','sequence':12,'ptype':'checkpoint','title':'Décider sans prétendre connaître tout l’avenir','genre':'B2 cumulative uncertainty checkpoint','domains':['educational','public','professional'],'topics':['decision under uncertainty','commitment','incident response','information ethics','planning','experiment'],'paragraphs':[
"Décider sous incertitude ne signifie ni attendre toujours ni agir comme si l’avenir était déjà connu. Dans un calendrier, une organisation peut vouloir promettre une date, mais elle doit distinguer ce qu’elle prévoit de ce qu’elle est prête à garantir. Attendre une preuve avant un engagement précis peut préserver la confiance sans empêcher les autres préparatifs. Dans un incident grave, l’équipe doit parfois agir plus vite : calmer le processus, protéger les personnes, choisir une solution réversible et assumer la responsabilité d’élargir la réponse si les nouvelles informations montrent qu’elle ne suffit pas.",
"La communication ajoute une autre difficulté. Une équipe peut partager des résultats provisoires sans transformer une opinion en conclusion ni qualifier de secret toute information non publiée. Surtout, le statut de chaque énoncé doit rester visible. De même, choisir un lieu sous demande incertaine exige de mettre scénarios et critères en ordre, d’examiner le coût du changement et de préciser pourquoi l’on peut préférer une option flexible à une option simplement moins chère. L’objectif n’est pas de découvrir une réponse certaine, mais de reconnaître quelles décisions restent acceptables dans plusieurs futurs plausibles.",
"L’expérience sur les plantes montre enfin pourquoi la réversibilité compte. Ramener les facteurs secondaires vers des conditions comparables ne signifie pas rendre toute chose pareille. Il faut conserver la différence de lumière que l’on veut étudier et observer ce qui fait pousser les plantes. Une bonne décision peut ainsi être celle qui améliore l’information disponible avant de fermer les autres possibilités. Cette logique prolonge l’unité précédente : on peut supposer une cause à partir d’un effet, mais une preuve doit distinguer les alternatives ; un moyen peut protéger sans garantir toute sécurité ; le public peut apporter des informations sous accès libre et règles acceptées ; une image générale peut tromper même si elle semble certaine ou ressemble à une représentation complète ; enfin, il faut apprécier ce qui peut intéresser la décision et ce qui peut valoir l’effort.",
"Camille résume quatre questions. Premièrement, quelle information manque encore ? Deuxièmement, quel est le coût d’attendre par rapport au coût d’agir maintenant ? Troisièmement, la décision est-elle réversible, ou crée-t-elle une promesse, une responsabilité ou une perte difficile à corriger ? Quatrièmement, quel résultat futur ferait changer la préférence actuelle ? Ces questions ne donnent pas une formule automatique. Elles mettent cependant l’incertitude en ordre : elles montrent ce qui est connu, ce qui dépend d’une opinion, ce qui doit rester protégé ou secret, et quel prochain pas peut ramener la décision vers davantage de confiance plutôt que simplement pousser le groupe vers une conclusion prématurée."
],
'grammar':[{'id':'fr-b2-u02-cumulative-uncertainty','role':'integration','description':'integrate future commitment, conditional escalation, information status, scenario preference and reversibility'}],
'discourse':[{'id':'fr-b2-u02-cumulative-decision','role':'integration','description':'synthesize uncertainty as a structured comparison of missing information, waiting cost, reversibility and decision thresholds'}],
'items':[
('main_claim','Quelle méthode générale le checkpoint propose-t-il ?','Structurer l’incertitude en comparant l’information manquante, le coût d’attendre, la réversibilité et les conditions qui feraient changer la décision.',['attendre','coût','ordre']),
('argument_relation','Comment le cas de la promesse se distingue-t-il du cas de l’incident grave ?','La promesse peut souvent attendre une preuve, tandis qu’un incident grave peut exiger une solution immédiate et proportionnée sous responsabilité.',['promettre','preuve','grave','solution','responsabilité']),
('cause_effect','Pourquoi calmer le processus peut-il aider sans minimiser le danger ?','Parce que calmer réduit le bruit décisionnel et permet de choisir une action qui protège sans dépasser inutilement l’information disponible.',['calmer','protéger']),
('vocabulary_in_context','Quels mots organisent le problème de communication ?','partager, opinion, secret et surtout',['partager','opinion','secret','surtout']),
('vocabulary_in_context','Quels mots organisent la décision de lieu ?','ordre, lieu, coût et préférer',['ordre','lieu','coût','préférer']),
('synthesis','Pourquoi la réversibilité relie-t-elle plusieurs passages ?','Elle permet d’agir maintenant tout en conservant la possibilité de corriger la décision lorsque de nouvelles preuves arrivent.',['ramener','solution']),
('assumption','Quelle condition rend l’attente raisonnable plutôt que passive ?','Attendre doit avoir une chance réelle d’apporter une information susceptible de changer la décision, sans créer un coût supérieur au bénéfice attendu.',['attendre','apporter']),
('reference_resolution','Dans « elle met cependant l’incertitude en ordre », à quoi renvoie « elle » ?','À la série des quatre questions utilisées pour structurer la décision.',['ordre']),
('stance','Quelle position finale le texte adopte-t-il envers l’incertitude ?','Il refuse à la fois la paralysie et la fausse certitude ; il recommande des décisions proportionnées, explicites et révisables lorsque c’est possible.',['confiance']),
('summary','Résume l’unité en une phrase.','Décider sous incertitude consiste à savoir quand promettre ou attendre pour préserver la confiance, traiter un problème grave avec une solution et une responsabilité proportionnées, partager opinion et secret surtout selon leur statut, mettre coût et lieu en ordre pour préférer une option robuste, puis ramener ce qui doit être pareil tout en gardant lumière et conditions nécessaires pour faire pousser l’information plutôt que la certitude.',['promettre','attendre','confiance','grave','solution','responsabilité','partager','opinion','secret','surtout','ordre','coût','lieu','préférer','ramener','pareil','lumière','pousser'])]
}

def text_of(s): return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
    q,a=base.qa(s['items'],ids); text=text_of(s)
    return {'id':s['id'],'language':'fr','cefr':'B2','unit':2,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B2 Unit 02 guarded production batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B2 Unit 02: decision under uncertainty.','Accepted B2 default of four fresh targets per P01-P05; P06 zero new.']},'paired_text_group':None,'prerequisites':['French B2 Unit 01 accepted calibration'],'difficulty_notes_internal':'B2 uncertainty reasoning: commitment thresholds, severity vs certainty, information status, scenario robustness and reversible experimental decisions.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b2_u02']}

def build(a1,a2,b1,b2,deck):
    prior=base.prior(a1+a2+b1+b2); prior_ids={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; prior_forms={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; bad=[]
    for f in FORMS:
        if f not in deck: bad.append(f+':missing_lexicon')
        elif base.tid(deck[f]['rank']) in prior_ids or f in prior_forms or prior.get(f): bad.append(f+':already_deliberate')
    if bad: raise AssertionError('B2 Unit02 candidate failures: '+', '.join(bad))
    out=[]
    for s in SPECS:
        text=text_of(s); new=[base.nt(f,text,deck) for f in s['forms']]; reviews=[base.rev(f,prior) for f in s['reviews']]; ids={t['form']:t['id'] for t in new+reviews}; out.append(mk(s,new,reviews,ids))
    reviews=[base.cur(f,deck) for f in FORMS]; ids={t['form']:t['id'] for t in reviews}; out.append(mk(CHECKPOINT,[],reviews,ids,True)); return out

def main():
    for label,path in [('A1',A1),('A2',A2),('B1',B1),('B2',CANON)]:
        got=subprocess.check_output(['git','hash-object',str(path)],text=True).strip()
        if got!=EXPECTED[label]: raise AssertionError(f'{label} blob drift: {got} != {EXPECTED[label]}')
    a1=[json.loads(x) for x in A1.read_text(encoding='utf-8').splitlines() if x.strip()]; a2=[json.loads(x) for x in A2.read_text(encoding='utf-8').splitlines() if x.strip()]; b1=[json.loads(x) for x in B1.read_text(encoding='utf-8').splitlines() if x.strip()]; b2=[json.loads(x) for x in CANON.read_text(encoding='utf-8').splitlines() if x.strip()]
    if len(b2)!=6 or b2[-1]['id']!='fr-b2-u01-p06': raise AssertionError('unexpected B2 prerequisite frontier')
    deck=base.deck(); unit=build(a1,a2,b1,b2,deck); V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')))
    prior_ids={t.get('id') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; prior_forms={t.get('form') for r in a1+a2+b1+b2 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}; newids=[];newforms=[]
    if [r['sequence'] for r in unit]!=list(range(7,13)) or [r['id'] for r in unit]!=[f'fr-b2-u02-p{i:02d}' for i in range(1,7)]: raise AssertionError('B2 Unit02 sequence/id continuity failure')
    for r in unit:
        errs=sorted(V.iter_errors(r),key=lambda e:list(e.path))
        if errs: raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:8]]}")
        if not 350<=r['word_count']<=550: raise AssertionError(f"{r['id']}: B2 word band {r['word_count']}")
        if len(r['questions'])!=10 or len(r['answer_key'])!=10: raise AssertionError(f"{r['id']}: assessment count")
        if r['sequence']<=11 and len(r['new_lexical_targets'])!=4: raise AssertionError(f"{r['id']}: accepted B2 default load must be 4")
        if r['sequence']==12 and r['new_lexical_targets']: raise AssertionError('B2 Unit02 P06 must have zero new targets')
        amap={a['question_id']:a['id'] for a in r['answer_key']}; local={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
        for q in r['questions']:
            if amap.get(q['id'])!=q['answer_id'] or any(tid not in local for tid in q.get('target_ids',[])): raise AssertionError(f"{r['id']} {q['id']}: linkage/target declaration")
        for t in r['new_lexical_targets']:
            src=deck.get(t['form'])
            if t['id'] in prior_ids or t['form'] in prior_forms or not src or t['source_rank']!=src['rank'] or t['id']!=base.tid(src['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']: raise AssertionError(f"{r['id']}: source/exposure/freshness drift {t}")
            newids.append(t['id']); newforms.append(t['form'])
        for t in r['review_lexical_targets']:
            if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1: raise AssertionError(f"{r['id']}: invisible review {t['form']}")
    if len(newids)!=20 or len(set(newids))!=20 or len(set(newforms))!=20: raise AssertionError('B2 Unit02 lexical uniqueness failure')
    CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b2+unit),encoding='utf-8')
    print(json.dumps({'status':'PASS','level':'B2','unit':2,'appended_passages':6,'b2_passages':12,'questions':60,'answers':60,'new_targets':20,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':[{'form':f,'rank':deck[f]['rank'],'id':base.tid(deck[f]['rank'])} for f in FORMS]},ensure_ascii=False))

if __name__=='__main__': main()
