#!/usr/bin/env python3
"""Generate Arabic A1 Unit 09: leisure and simple preferences."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];P=ROOT/"reading"/"arabic"/"a1"/"passages.jsonl";L=ROOT/"reading"/"lexicons"/"arabic.jsonl"
T={200:("كرة","ball",["example_instance"]),296:("لاعب","player",["category_relation"]),180:("مباراة","match; game",["scenario_resolution"]),174:("نادي","club",["category_relation"]),480:("أصدقاء","friends",["example_instance"]),205:("سعيد","happy; pleased",["behavior_interpretation"]),340:("فرصة","opportunity; chance",["scenario_resolution"]),304:("مشاركة","participation; sharing",["behavior_interpretation"]),242:("هدف","goal; target",["scenario_resolution"]),290:("فوز","win; victory",["cause_consequence"])}
def qa(items):
 qs=[];ans=[]
 for i,(t,p,a,ids) in enumerate(items,1):
  q={"id":f"q{i}","type":t,"prompt":p,"answer_id":f"a{i}"};
  if ids:q["target_ids"]=ids
  qs.append(q);ans.append({"id":f"a{i}","question_id":f"q{i}","answer":a,"explanation":""})
 return qs,ans
R=[
{"id":"ar-a1-u09-p01","sequence":49,"title":"كرة بعد المدرسة","passage_type":"instructional","genre":"park micro-story","domains":["personal","public"],"topics":["leisure","ball game","park"],"text":"بعد المدرسة تذهب ليلى مع مريم إلى الحديقة. ترى مجموعة من الأطفال يلعبون بكرة صغيرة. يقول طفل: نحتاج إلى لاعب آخر، هل تريدان اللعب؟ تبتسم مريم وتقول: نعم. تمسك ليلى الكرة أولًا ثم ترسلها إلى مريم. لا تعرف ليلى كل قواعد اللعبة، لكن أحد الأطفال يشرحها ببساطة. تقول ليلى: لست لاعبة جيدة بعد، لكنني أحب الحركة واللعب مع الآخرين. بعد عشر دقائق تصبح أسرع في إرسال الكرة. عندما يحين وقت العودة تقول: كان من الممتع أن أكون لاعبة في المجموعة، حتى لو كنت أتعلم اللعبة لأول مرة.","new":[200,296],"reviews":[{"id":"ar-r124","form":"يحب","review_stage":"R3","representation":"running_text"},{"id":"ar-r327","form":"قوة","review_stage":"R3","representation":"other"}],"grammar":[{"id":"ar-a1-ball","role":"new","description":"كرة as a common play object"},{"id":"ar-a1-player","role":"new","description":"لاعب/لاعبة as a person who plays"}],"discourse":[{"id":"a1-join-game","role":"new","description":"follow joining a simple group game"}],"qa":[("gist","ماذا تفعل ليلى بعد المدرسة؟","تنضم إلى لعبة بالكرة في الحديقة.",None),("literal_detail","لماذا يحتاج الأطفال إلى ليلى أو مريم؟","لأنهم يحتاجون إلى لاعب آخر.",["ar-r296"]),("vocabulary_in_context","ماذا تعني «كرة»؟","الشيء المستدير الذي يلعب به الأطفال.",["ar-r200"]),("vocabulary_in_context","ماذا يعني «لاعب»؟","شخص يشارك في لعبة أو رياضة.",["ar-r296"]),("cause_effect","لماذا تتحسن ليلى بعد عشر دقائق؟","لأنها تتدرب وتفهم اللعبة أكثر.",None),("single_word_definition","ما معنى «كرة»؟","جسم مستدير يستخدم في ألعاب كثيرة.",["ar-r200"]),("single_word_definition","ما معنى «لاعب»؟","شخص يلعب لعبة أو رياضة.",["ar-r296"]),("contrast","أيهما شخص: «لاعب» أم «كرة»؟","لاعب.",["ar-r296","ar-r200"]),("cloze_transfer","أكمل: رميت _____ إلى صديقي.","الكرة",["ar-r200"]),("cloze_transfer","أكمل: سامر _____ في الفريق.","لاعب",["ar-r296"])]},
{"id":"ar-a1-u09-p02","sequence":50,"title":"مباراة في النادي","passage_type":"reinforcement","genre":"community event narrative","domains":["public","personal"],"topics":["sports","club","match"],"text":"في نهاية الأسبوع تذهب ليلى مع أبيها إلى نادي الحي. يوجد في النادي ملعب صغير، واليوم توجد مباراة بين مجموعتين من الشباب. لا تلعب ليلى؛ تجلس مع أبيها وتشاهد. قبل بداية المباراة يتحدث المدرب مع اللاعبين. ثم تبدأ المباراة ويجري اللاعبون خلف الكرة. تسأل ليلى: هل هذا النادي للرياضة فقط؟ يقول أبوها: لا، فيه أيضًا أنشطة قراءة واجتماعات صغيرة. بعد انتهاء المباراة يمشيان داخل النادي ويريان غرفة للكتب. تقول ليلى: أحب أن يكون في المكان أكثر من نشاط. يمكنني أن أشاهد مباراة اليوم، وأعود إلى النادي في يوم آخر للقراءة.","new":[180,174],"reviews":[{"id":"ar-r200","form":"كرة","review_stage":"R1","representation":"running_text"},{"id":"ar-r296","form":"لاعب","review_stage":"R1","representation":"running_text"},{"id":"ar-r128","form":"يعمل","review_stage":"R3","representation":"other"}],"grammar":[{"id":"ar-a1-match","role":"new","description":"مباراة as an organized game"},{"id":"ar-a1-club","role":"new","description":"نادي as a community/sports club"}],"discourse":[{"id":"a1-event-place","role":"new","description":"connect an event to the place that hosts it"}],"qa":[("literal_detail","أين تقام المباراة؟","في نادي الحي.",["ar-r174"]),("literal_detail","ماذا يوجد أيضًا في النادي؟","أنشطة قراءة واجتماعات صغيرة وغرفة للكتب.",None),("vocabulary_in_context","ماذا تعني «مباراة»؟","لعبة منظمة بين مجموعتين أو لاعبين.",["ar-r180"]),("vocabulary_in_context","ماذا يعني «نادي»؟","مكان يجتمع فيه الناس لأنشطة مثل الرياضة أو القراءة.",["ar-r174"]),("sequence","ماذا تفعل ليلى بعد انتهاء المباراة؟","تمشي داخل النادي وترى غرفة الكتب.",None),("single_word_definition","ما معنى «مباراة»؟","منافسة أو لعبة منظمة بين طرفين.",["ar-r180"]),("single_word_definition","ما معنى «نادي»؟","مكان أو جماعة لأنشطة مشتركة.",["ar-r174"]),("contrast","أيهما حدث: «مباراة» أم «نادي»؟","مباراة.",["ar-r180","ar-r174"]),("cloze_transfer","أكمل: شاهدنا _____ كرة في المساء.","مباراة",["ar-r180"]),("cloze_transfer","أكمل: أذهب إلى _____ القراءة يوم الخميس.","نادي",["ar-r174"])]},
{"id":"ar-a1-u09-p03","sequence":51,"title":"وقت مع الأصدقاء","passage_type":"interleaved","genre":"leisure narrative","domains":["personal"],"topics":["friends","leisure","happiness"],"text":"في عصر الجمعة تلتقي ليلى ثلاثة من أصدقائها في الحديقة. لا يقررون نشاطًا واحدًا من البداية. تقول مريم: أريد أن ألعب بالكرة. يقول سامر: وأنا أفضل أن أمشي قليلًا أولًا. تتفق المجموعة على المشي، ثم اللعب، ثم الجلوس قرب الأشجار. أثناء المشي يتحدث الأصدقاء عن المدرسة وخطط الأسبوع القادم. بعد ذلك يلعبون بالكرة مدة قصيرة. في النهاية يجلسون ويشربون الماء. تقول ليلى: أنا سعيدة لأننا لم نحتج إلى نشاط كبير؛ الوقت مع الأصدقاء نفسه جميل. تقول مريم: وأنا سعيدة لأن كل شخص اختار جزءًا يحبه.","new":[480,205],"reviews":[{"id":"ar-r180","form":"مباراة","review_stage":"R1","representation":"other"},{"id":"ar-r174","form":"نادي","review_stage":"R1","representation":"other"},{"id":"ar-r124","form":"يحب","review_stage":"R3","representation":"running_text"}],"grammar":[{"id":"ar-a1-friends-plural","role":"new","description":"أصدقاء as plural friend noun"},{"id":"ar-a1-happy","role":"new","description":"سعيد/سعيدة + reason"}],"discourse":[{"id":"a1-shared-choice","role":"new","description":"combine different preferences into a shared leisure plan"}],"qa":[("gist","كيف يقضي الأصدقاء وقتهم؟","يمشون ويلعبون ثم يجلسون معًا.",None),("literal_detail","ما النشاط الذي يفضله سامر أولًا؟","المشي قليلًا.",None),("vocabulary_in_context","من هم «الأصدقاء»؟","الأشخاص الذين تلتقي بهم ليلى وتقضي معهم وقتها.",["ar-r480"]),("vocabulary_in_context","ماذا تعني «سعيدة»؟","تشعر بالفرح والرضا.",["ar-r205"]),("cause_effect","لماذا ليلى سعيدة؟","لأنها قضت وقتًا جميلًا مع أصدقائها من دون حاجة إلى نشاط كبير.",None),("single_word_definition","ما معنى «أصدقاء»؟","أشخاص تجمعهم علاقة صداقة.",["ar-r480"]),("single_word_definition","ما معنى «سعيد»؟","فرح أو مسرور.",["ar-r205"]),("contrast","أيهما يصف شعورًا إيجابيًا: «سعيد» أم «بعيد»؟","سعيد.",["ar-r205"]),("cloze_transfer","أكمل: ألعب مع _____ بعد المدرسة.","أصدقائي",["ar-r480"]),("cloze_transfer","أكمل: أنا _____ لأن صديقي جاء.","سعيد",["ar-r205"])]},
{"id":"ar-a1-u09-p04","sequence":52,"title":"فرصة للمشاركة","passage_type":"transfer","genre":"club announcement narrative","domains":["educational","public"],"topics":["club","participation","choice"],"text":"يعلن نادي المدرسة عن نشاط جديد يوم الأربعاء. يمكن للطلاب أن يقرؤوا قصة قصيرة أو يرسموا صورة أو يساعدوا في ترتيب الغرفة. تقول المعلمة: هذه فرصة للمشاركة، وليس المطلوب أن يفعل الجميع الشيء نفسه. تفكر ليلى في الخيارات. تحب القراءة، لكنها تريد تجربة شيء مختلف. تقول: سأشارك في ترتيب الكتب ثم أقرأ مع المجموعة. تسأل مريم: هل المشاركة واجبة؟ تقول المعلمة: لا، لكنها فرصة جيدة لمن يريد أن يجرب نشاطًا. في يوم النشاط تأتي ليلى مبكرًا وتساعد في ترتيب المكان. بعد ذلك تجلس مع الآخرين وتقرأ. تقول: أعجبتني المشاركة لأنني فعلت شيئًا مع المجموعة وليس وحدي.","new":[340,304],"reviews":[{"id":"ar-r480","form":"أصدقاء","review_stage":"R1","representation":"other"},{"id":"ar-r205","form":"سعيد","review_stage":"R1","representation":"other"},{"id":"ar-r174","form":"نادي","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-opportunity","role":"new","description":"فرصة لـ + activity"},{"id":"ar-a1-participation","role":"new","description":"مشاركة in a group activity"}],"discourse":[{"id":"a1-voluntary-activity","role":"new","description":"distinguish an opportunity from an obligation"}],"qa":[("literal_detail","ما الخيارات التي يقدمها النادي؟","القراءة أو الرسم أو المساعدة في ترتيب الغرفة.",None),("literal_detail","ماذا تختار ليلى؟","ترتيب الكتب ثم القراءة مع المجموعة.",None),("vocabulary_in_context","ماذا تعني «فرصة»؟","إمكان مناسب لفعل شيء أو تجربته.",["ar-r340"]),("vocabulary_in_context","ماذا تعني «المشاركة»؟","أن تدخل ليلى في النشاط وتفعله مع الآخرين.",["ar-r304"]),("contrast","هل المشاركة واجبة في هذا النشاط؟","لا، هي اختيار وفرصة.",None),("single_word_definition","ما معنى «فرصة»؟","وقت أو إمكان مناسب لفعل شيء.",["ar-r340"]),("single_word_definition","ما معنى «مشاركة»؟","القيام بنشاط مع الآخرين أو أخذ جزء فيه.",["ar-r304"]),("contrast","أيهما يعني الانضمام إلى النشاط: «مشاركة» أم «انتظار»؟","مشاركة.",["ar-r304"]),("cloze_transfer","أكمل: عندي _____ لزيارة المكتبة اليوم.","فرصة",["ar-r340"]),("cloze_transfer","أكمل: أحب _____ في أنشطة الصف.","المشاركة",["ar-r304"])]},
{"id":"ar-a1-u09-p05","sequence":53,"title":"هدف صغير","passage_type":"checkpoint","genre":"simple game narrative","domains":["personal","public"],"topics":["game","goal","winning"],"text":"في الحديقة يلعب الأطفال مباراة قصيرة بالكرة. قبل البداية يقول سامر: هدفنا أن نمرر الكرة جيدًا ونستمتع، وليس الفوز فقط. تبدأ المباراة. في الدقائق الأولى يحرز الفريق الآخر هدفًا. تستمر ليلى في اللعب وتحاول أن ترسل الكرة إلى زملائها. بعد قليل يحرز فريقها هدفًا أيضًا. في نهاية الوقت يسجل فريق ليلى هدفًا آخر ويحقق فوزًا صغيرًا. يفرح اللاعبون، لكن سامر يقول: الفوز جميل، والأجمل أننا لعبنا معًا. تقول ليلى: كان عندنا هدف في النتيجة، وكان عندنا هدف آخر هو اللعب بطريقة جيدة. هذا يجعل الفوز ممتعًا من غير أن يكون الشيء الوحيد المهم.","new":[242,290],"reviews":[{"id":"ar-r340","form":"فرصة","review_stage":"R1","representation":"other"},{"id":"ar-r304","form":"مشاركة","review_stage":"R1","representation":"running_text"},{"id":"ar-r200","form":"كرة","review_stage":"R2","representation":"running_text"},{"id":"ar-r296","form":"لاعب","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-goal","role":"new","description":"هدف as game score and simple purpose"},{"id":"ar-a1-win","role":"new","description":"فوز as successful game result"}],"discourse":[{"id":"a1-result-purpose","role":"integration","description":"distinguish a game goal from a broader activity goal"}],"qa":[("gist","ما الفكرة التي يتعلمها الأطفال؟","أن اللعب الجيد معًا مهم إلى جانب الفوز.",None),("literal_detail","كم هدفًا يسجل فريق ليلى في النص؟","هدفين.",["ar-r242"]),("vocabulary_in_context","ماذا يعني «هدف» في نتيجة المباراة؟","إدخال الكرة بطريقة تزيد نتيجة الفريق.",["ar-r242"]),("vocabulary_in_context","ماذا يعني «فوز»؟","أن ينتهي اللعب بنتيجة أفضل لفريق ليلى.",["ar-r290"]),("cause_effect","لماذا يفرح اللاعبون في النهاية؟","لأن فريقهم حقق الفوز ولعبوا معًا جيدًا.",None),("single_word_definition","ما معنى «هدف»؟","نتيجة مقصودة؛ وفي اللعبة نقطة أو إصابة تسجل للفريق.",["ar-r242"]),("single_word_definition","ما معنى «فوز»؟","النجاح على الطرف الآخر في مباراة أو منافسة.",["ar-r290"]),("contrast","أيهما نتيجة نهائية للمباراة: «فوز» أم «فرصة»؟","فوز.",["ar-r290","ar-r340"]),("cloze_transfer","أكمل: سجل الفريق _____ في الشوط الأول.","هدفًا",["ar-r242"]),("cloze_transfer","أكمل: انتهت المباراة ب_____ فريقنا.","فوز",["ar-r290"])]},
{"id":"ar-a1-u09-p06","sequence":54,"title":"وقت الفراغ","passage_type":"fluency","genre":"connected leisure narrative","domains":["personal","public"],"topics":["leisure","friends","sport","review"],"text":"في وقت الفراغ تحب ليلى أن تختار نشاطًا بسيطًا مع أصدقائها. أحيانًا يحملون كرة إلى الحديقة ويصبح كل شخص لاعبًا في لعبة قصيرة. وأحيانًا يذهبون إلى النادي لمشاهدة مباراة أو للقراءة. لا تحتاج ليلى إلى الفوز في كل مرة كي تكون سعيدة؛ تحب أن تكون مع أصدقائها وأن تجرب أشياء مختلفة. إذا وجدت فرصة لنشاط جديد تفكر هل تريد المشاركة فيه. وفي اللعب تعرف أن الهدف قد يكون تسجيل نقطة، لكنه قد يكون أيضًا التعلم أو قضاء وقت جميل مع المجموعة. الفوز يسعدها، لكنه ليس السبب الوحيد الذي يجعل وقت الفراغ جيدًا.","new":[],"reviews":[{"id":"ar-r200","form":"كرة","review_stage":"R2","representation":"running_text"},{"id":"ar-r296","form":"لاعب","review_stage":"R2","representation":"running_text"},{"id":"ar-r180","form":"مباراة","review_stage":"R2","representation":"running_text"},{"id":"ar-r174","form":"نادي","review_stage":"R2","representation":"running_text"},{"id":"ar-r480","form":"أصدقاء","review_stage":"R2","representation":"running_text"},{"id":"ar-r205","form":"سعيد","review_stage":"R2","representation":"running_text"},{"id":"ar-r340","form":"فرصة","review_stage":"R2","representation":"running_text"},{"id":"ar-r304","form":"مشاركة","review_stage":"R2","representation":"running_text"},{"id":"ar-r242","form":"هدف","review_stage":"R1","representation":"running_text"},{"id":"ar-r290","form":"فوز","review_stage":"R1","representation":"running_text"}],"grammar":[{"id":"ar-a1-u09-cumulative","role":"integration","description":"recycle leisure, sport, friendship, opportunity, participation, goals and results"}],"discourse":[{"id":"a1-leisure-fluency","role":"integration","description":"high-coverage cumulative leisure reading"}],"qa":[("gist","ما الفكرة الرئيسية في النص؟","ليلى تستمتع بوقت الفراغ من خلال أنشطة وأصدقاء مختلفة، لا من خلال الفوز فقط.",None),("literal_detail","أين قد تذهب ليلى لمشاهدة مباراة؟","إلى النادي.",["ar-r174","ar-r180"]),("literal_detail","مع من تحب ليلى النشاط؟","مع أصدقائها.",["ar-r480"]),("cause_effect","لماذا يمكن أن تكون ليلى سعيدة من دون فوز؟","لأنها تستمتع بالأصدقاء والتجربة والوقت نفسه.",["ar-r205","ar-r290"]),("summary","لخص ما تحبه ليلى في وقت الفراغ.","تحب الألعاب والنادي والأصدقاء والمشاركة في أنشطة جديدة.",None),("single_word_definition","ما معنى «فرصة»؟","إمكان مناسب لفعل شيء.",["ar-r340"]),("single_word_definition","ما معنى «مشاركة»؟","الدخول في نشاط مع الآخرين.",["ar-r304"]),("contrast","أيهما شخص يلعب: «لاعب» أم «كرة»؟","لاعب.",["ar-r296","ar-r200"]),("grammar_function","ماذا يعني «هدف» خارج نتيجة المباراة أيضًا؟","غاية أو شيء يريد الشخص الوصول إليه.",["ar-r242"]),("contrast","أيهما نتيجة ناجحة في مباراة: «فوز» أم «نادي»؟","فوز.",["ar-r290","ar-r174"])]}
]
def lex():
 d={}
 for x in L.read_text(encoding="utf-8").splitlines():
  if x.strip():r=json.loads(x);d[r["rank"]]=r
 return d
def tar(n,text,d):
 f,s,c=T[n];r=d[n];return {"id":f"ar-r{n}","form":f,"lemma":f,"part_of_speech":r.get("part_of_speech_source"),"intended_sense":s,"register":"contemporary standard","variety":"MSA","context_strategy":c,"first_introduced":True,"exposures_in_text":max(1,text.count(f)),"source_lexicon":r.get("source_file"),"source_rank":n,"beyond_base":False}
def build(x,d):
 qs,ans=qa(x["qa"]);text=x["text"];return {"id":x["id"],"language":"ar","cefr":"A1","unit":9,"sequence":x["sequence"],"revision":1,"title":x["title"],"passage_type":x["passage_type"],"genre":x["genre"],"domains":x["domains"],"topics":x["topics"],"text":text,"word_count":len(text.split()),"sentence_count":max(1,len(re.findall(r"[.!؟](?:\s|$)",text))),"estimated_known_token_coverage":0,"new_lexical_targets":[tar(n,text,d) for n in x["new"]],"review_lexical_targets":x["reviews"],"grammar_targets":x["grammar"],"discourse_targets":x["discourse"],"questions":qs,"answer_key":ans,"speed_training":{"timed":x["passage_type"]=="fluency","benchmark_eligible":False,"comprehension_gate":0.8,"new_word_policy":"none" if x["passage_type"]=="fluency" else "controlled","notes":"Generation-stage passage; formal fluency/coverage decision deferred to final audit."},"quality":{"status":"draft","linguistic_review":"pending","pedagogical_review":"pending","coverage_check":"pending","answer_key_check":"pending","schema_check":"pending","fact_check":"not_required","notes":["High-quality generation-stage draft; formal audits deferred to the final multi-pass review phase."]},"paired_text_group":None,"prerequisites":[],"difficulty_notes_internal":None,"reader_tags":["unit_role:"+x["passage_type"],"generation_batch"],"complexity_profile":{"mean_sentence_length":None,"median_sentence_length":None,"clause_count":None,"subordination_count":None,"coordination_count":None,"connective_diversity":None,"lexical_diversity":None,"reference_chain_max_distance":None,"multiword_expression_count":None,"morphology_notes":"A1 generation-stage draft; transparent contemporary MSA.","inference_depth":"local"}}
def main():
 old=[json.loads(z) for z in P.read_text(encoding="utf-8").splitlines() if z.strip()];old=[x for x in old if x.get("unit")!=9];d=lex();new=[build(x,d) for x in R]
 if len(new)!=6 or any(len(x["questions"])!=10 or len(x["answer_key"])!=10 for x in new):raise SystemExit("Unit09 generation contract failed")
 rows=sorted(old+new,key=lambda x:(x.get("unit",0),x.get("sequence",0)));P.write_text("".join(json.dumps(x,ensure_ascii=False,sort_keys=True)+"\n" for x in rows),encoding="utf-8");print("generated Arabic A1 Unit 09: six passages, sixty questions, sixty answers")
if __name__=="__main__":main()
