#!/usr/bin/env python3
"""Generate Arabic C2 Unit 07: culture, translation, and interpretation.
All source texts/cultures are fictional curriculum constructions."""
from __future__ import annotations
import json,re,unicodedata
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'reading/arabic/c2/passages.jsonl';LEX=ROOT/'reading/lexicons/arabic.jsonl'
AR_DIAC=re.compile(r'[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]')
def norm(s):return AR_DIAC.sub('',unicodedata.normalize('NFC',str(s or '')).replace('ـ','').strip())
def lexicon():
 d={}
 for l in LEX.read_text(encoding='utf-8').splitlines():
  if l.strip():r=json.loads(l);d.setdefault(norm(r.get('form','')),r)
 return d
def prior_new():
 seen={}
 for level in ('a1','a2','b1','b2','c1','c2'):
  p=ROOT/f'reading/arabic/{level}/passages.jsonl'
  if not p.exists():continue
  for l in p.read_text(encoding='utf-8').splitlines():
   if not l.strip():continue
   rec=json.loads(l)
   if rec.get('cefr')=='C2' and rec.get('unit')==7:continue
   for t in rec.get('new_lexical_targets',[]):
    f=norm(t.get('form',''))
    if f:seen.setdefault(f,[]).append(rec.get('id'))
 return seen
def row(f,d):
 r=d.get(norm(f))
 if not r:raise KeyError(f);return r
 return r
SENSE={'مقصود':'intended meaning; purpose','فصيح':'eloquent; fluent standard expression','قارن':'compare','يقين':'certainty','ناقد':'critic','أسطورة':'myth; legend','محدث':'modern; updated','بصمة':'imprint; distinctive trace','مسموع':'audible; heard','سماع':'hearing; listening'}
def target(f,text,d):
 r=row(f,d);return {'id':f"ar-r{r['rank']}",'form':f,'lemma':f,'part_of_speech':r.get('part_of_speech_source'),'intended_sense':SENSE[f],'register':'translation-cultural criticism/contemporary MSA','variety':'MSA','context_strategy':['translation_choice','cultural_interpretation','comparative_reading'],'first_introduced':True,'exposures_in_text':max(1,text.count(f)),'source_lexicon':r.get('source_file'),'source_rank':r['rank'],'beyond_base':False}
def review(f,s,rep,d):
 r=row(f,d);return {'id':f"ar-r{r['rank']}",'form':f,'review_stage':s,'representation':rep}
def qa(items,ids):
 q=[];a=[]
 for i,(typ,p,ans,f) in enumerate(items,1):
  z={'id':f'q{i}','type':typ,'prompt':p,'answer_id':f'a{i}'}
  if f:z['target_ids']=[ids[f]]
  q.append(z);a.append({'id':f'a{i}','question_id':f'q{i}','answer':ans,'explanation':''})
 return q,a
R=[
('p01','الكلمة الصحيحة قد لا تحمل المقصود نفسه','instructional','comparative criticism',['مقصود','فصيح'],'ترجم فريق خيالي عبارة ترحيب من لغة متخيلة إلى العربية. أعطى القاموس معنى حرفيًا قريبًا من «اجلس تحت سقفنا»، فكتب مترجم: «تفضل بالجلوس في منزلنا». رأى آخر أن المقصود أوسع: العبارة الأصلية تقال أيضًا لمن يبقى دقائق عند الباب، ووظيفتها إعلان الأمان لا وصف مكان الجلوس. اقترح صياغة فصيحة: «أنت في ضيافتنا». لم يزعم أنها أقرب كلمة بكلمة، بل أقرب في الفعل الاجتماعي الذي تؤديه العبارة. اعترض طالب بأن الترجمة يجب أن تحافظ على الصورة. رد الفريق بأن الصورة نفسها قد تكون جزءًا من المعنى إذا كانت مألوفة ومقصودة، وقد تصبح تشويشًا إذا فهمها القارئ الجديد حرفيًا. لذلك قارنوا ثلاث طبقات: المرجع الحرفي، المقصود في الموقف، والأثر الأسلوبي. لا توجد قاعدة تجعل طبقة واحدة تربح دائمًا. الترجمة الدقيقة تعلن ما الذي حافظت عليه وما الذي غيرته ولماذا.',['ضيافة'],[('gist','ما المشكلة في الترجمة الحرفية؟','قد تحفظ الكلمات ولا تحفظ الفعل الاجتماعي المقصود.',None),('literal_detail','ما الصياغة البديلة؟','«أنت في ضيافتنا».',None),('inference','لماذا قد تكون الصورة مهمة أحيانًا؟','إذا كانت مألوفة ومقصودة وتحمل أثرًا أسلوبيًا يمكن نقله.',None),('argument_relation','ما وظيفة الطبقات الثلاث؟','فصل المرجع الحرفي عن المقصود والأثر الأسلوبي.',None),('main_claim','كيف يبرر المترجم اختياره؟','يحدد ما الذي حافظ عليه وما الذي ضحى به ولماذا.',None),('contrast','ما الفرق بين صحة الكلمة ودقة الترجمة؟','صحة الكلمة معجمية، ودقة الترجمة تتعلق بوظيفة العبارة في السياق.',None),('inference','متى تشوش الصورة الأصلية؟','عندما يفهمها الجمهور الجديد حرفيًا بطريقة تخالف وظيفتها.',None),('summary','ما أبعاد المقارنة؟','الحرف والمعنى المقصود والأثر الأسلوبي.',None),('single_word_definition','ما معنى «مقصود»؟','المعنى أو الغرض الذي يراد إيصاله في السياق.','مقصود'),('single_word_definition','ما معنى «فصيح» هنا؟','مصوغ بلغة سليمة وطبيعية وذات بيان مناسب.','فصيح')]),
('p02','المقارنة لا تمنح يقينًا آليًا','reinforcement','essay',['قارن','يقين'],'وجدت باحثة نسختين مترجمتين من رسالة خيالية. الأولى تقول «أرجو أن تنظر في الأمر»، والثانية «أطلب منك مراجعة الأمر». قارن الطلاب النبرتين؛ بدت الأولى ألطف والثانية أكثر مؤسسية. لكن الباحثة حذرت من تحويل الفرق إلى يقين بشأن شخصية الكاتب الأصلي. قد يكون الاختلاف من المترجم، أو من زمن الترجمة، أو من جمهور النشر. استعانت بسطر آخر يظهر فيه فعل طلب مباشر، فصار تفسير الرسمية أقوى لكنه لم يصبح محسومًا. ثم قارنت مقدمة كل نسخة وهوامشها، فاكتشفت أن الأولى موجهة لقراء عامين والثانية لملف إداري. هنا تغير السؤال: بدل «أي ترجمة تكشف الكاتب؟» أصبح «أي عوامل في سلسلة النقل يمكن أن تفسر الاختلاف؟». المقارنة الجيدة تزيد البدائل قبل أن تستبعدها. واليقين لا ينتج من كثرة الفروق، بل من قدرة دليل مستقل على تمييز تفسير عن آخر.',['توثيق'],[('gist','لماذا لا يكشف اختلاف الترجمتين شخصية الكاتب مباشرة؟','لأن المترجم والزمن والجمهور قد يصنعون الفرق.',None),('literal_detail','ما الفرق بين الصياغتين؟','إحداهما ألطف والأخرى أكثر مؤسسية.',None),('inference','لماذا فادت المقدمة والهوامش؟','لأنها كشفت اختلاف الجمهور والغرض من النسختين.',None),('argument_relation','ما وظيفة السطر الإضافي؟','تقديم دليل مستقل نسبيًا يختبر تفسير الرسمية.',None),('main_claim','متى تزداد قوة تفسير ما؟','عندما تميزه أدلة مستقلة عن البدائل المنافسة.',None),('contrast','ما الفرق بين المقارنة واليقين؟','المقارنة تكشف فروقًا، واليقين يحتاج إلى استبعاد بدائل تفسيرية.',None),('inference','لماذا توسع الباحثة البدائل أولًا؟','حتى لا تنسب كل فرق إلى الكاتب قبل فحص سلسلة النقل.',None),('summary','كيف تغير سؤال البحث؟','انتقل من البحث عن شخصية الكاتب إلى تحليل عوامل الترجمة والجمهور.',None),('single_word_definition','ما معنى «قارن»؟','وضع شيئين أو أكثر جنبًا إلى جنب لفحص أوجه الشبه والاختلاف.','قارن'),('single_word_definition','ما معنى «يقين»؟','درجة عالية من الثقة أو غياب الشك المعقول.','يقين')]),
('p03','الناقد لا يختصر الأسطورة إلى رسالة واحدة','interleaved','comparative criticism',['ناقد','أسطورة'],'قرأ ناقد حكاية خيالية عن طائر يعود كل جيل إلى شجرة محترقة. وصفها قارئ بأنها أسطورة عن الوفاء، ووصفها آخر بأنها تحذير من تكرار الماضي. رفض الناقد اختيار معنى واحد قبل فحص بنية الحكاية. في النسخة الأولى يعود الطائر رغم وجود أشجار جديدة، فيبدو الاختيار مقصودًا. وفي نسخة شفوية أخرى يعود لأنه لا يرى غير الشجرة القديمة في الضباب. التفصيل الصغير يغير مقدار المسؤولية الذي تنسبه القراءة إلى الطائر. كما أن الجمهور داخل القصة يختلف: كبار القرية يمدحون العودة، بينما الأطفال يسألون لماذا لا يزرع أحد شجرة جديدة. قال الناقد إن الأسطورة لا تصبح عميقة لمجرد قدمها أو غرابتها؛ قوتها هنا في أنها توزع مواقف متعارضة داخل صورة واحدة. التفسير الجيد يبين أي عناصر تدعم قراءة الوفاء وأيها تدعم نقد التكرار، ثم يوضح لماذا قد يبقى التوتر بدل أن يحوله إلى شعار.',['عميق'],[('gist','لماذا يرفض الناقد رسالة واحدة؟','لأن تفاصيل النسخ وأصوات الشخصيات تدعم قراءات متعارضة.',None),('literal_detail','ما الفرق بين النسختين؟','في الأولى يختار الطائر الشجرة، وفي الثانية يحد الضباب خياراته.',None),('inference','كيف يغير الضباب القراءة؟','يقلل مقدار الاختيار والمسؤولية المنسوبين للطائر.',None),('argument_relation','ما وظيفة اختلاف الكبار والأطفال؟','إدخال تفسيرين داخل الحكاية نفسها.',None),('main_claim','ما الذي يجعل التفسير أقوى؟','أن يربط كل قراءة بتفاصيلها ويعترف بالتوتر المتبقي.',None),('contrast','ما الفرق بين الرمز والشعار؟','الرمز قد يحمل توترًا وطبقات، والشعار يختصره إلى رسالة واحدة.',None),('inference','لماذا لا يكفي قدم الحكاية؟','لأن القيمة التفسيرية تحتاج إلى بنية وأدلة لا إلى قدم الشكل.',None),('summary','ما القراءتان الرئيسيتان؟','الوفاء للماضي ونقد تكراره.',None),('single_word_definition','ما معنى «ناقد»؟','قارئ أو باحث يحلل العمل ويقيم تفسيراته وحججه.','ناقد'),('single_word_definition','ما معنى «أسطورة»؟','حكاية رمزية أو موروثة تتجاوز التقرير الواقعي المباشر.','أسطورة')]),
('p04','النص المحدث يحتفظ ببصمة ولا ينسخ الأصل','transfer','reflection',['محدث','بصمة'],'أعاد مسرح خيالي تقديم قصة قديمة في نسخة محدثة تدور في محطة قطار بدل قصر. اتهم بعض الجمهور العرض بأنه فقد الثقافة الأصلية لأن الملابس والأثاث تغيرت. رأى المخرج أن البصمة الأهم ليست الأشياء بل شبكة العلاقات: ضيف لا يعرف القواعد، مضيف يملك سلطة المكان، ووعد يختبر عند لحظة الخطر. احتفظ العرض بهذه البنية لكنه غير إشارات كثيرة حتى يستطيع الجمهور الجديد فهم التوتر من دون شرح طويل. اعترض ناقد آخر بأن بعض التغييرات ليست محايدة؛ نقل الحدث إلى محطة عامة يقلل سلطة المضيف مقارنة بمكان خاص. وافق المخرج، وقال إن التحديث ليس حفظًا كاملًا بل تفسيرًا معلنًا. لذلك أرفق البرنامج ملاحظات تشرح ما نُقل وما استُبدل. السؤال ليس هل النسخة مطابقة، بل أي بصمة من الأصل تدعي المحافظة عليها، وكيف تغير البيئة الجديدة معنى تلك البصمة.',['مظهر'],[('gist','كيف يبرر المخرج التحديث؟','يحافظ على شبكة علاقات أساسية مع تغيير الإشارات لتناسب جمهورًا جديدًا.',None),('literal_detail','ما البنية التي احتفظ بها؟','ضيف وقواعد ومضيف ذو سلطة ووعد يختبر عند الخطر.',None),('inference','لماذا يغير المكان معنى القصة؟','لأن مقدار سلطة المضيف يختلف بين القصر والمحطة العامة.',None),('argument_relation','ما وظيفة ملاحظات البرنامج؟','إعلان اختيارات التكييف بدل إخفائها كأنها نقل محايد.',None),('main_claim','ما معنى التحديث هنا؟','تفسير يعيد بناء العمل لجمهور جديد مع اختيار ما يحفظه وما يغيره.',None),('contrast','ما الفرق بين المطابقة والبصمة؟','المطابقة تنسخ التفاصيل، والبصمة تشير إلى نمط أو أثر مميز يمكن أن يستمر مع تغيرها.',None),('inference','لماذا لا تكون كل التغييرات محايدة؟','لأن البيئة الجديدة تغير علاقات القوة والدلالة.',None),('summary','كيف يقيم النص النسخة الجديدة؟','يسأل ما الذي حافظت عليه وكيف غير السياق معنى ما بقي.',None),('single_word_definition','ما معنى «محدث»؟','معدل أو معاد تقديمه بصيغة أحدث أو سياق جديد.','محدث'),('single_word_definition','ما معنى «بصمة» هنا؟','أثر أو سمة مميزة تبقى قابلة للتعرف رغم تغير التفاصيل.','بصمة')]),
('p05','ما ينجح مكتوبًا قد يفشل حين يصبح مسموعًا','integration','essay',['مسموع','سماع'],'أعد فريق ترجمة نصًا خياليًا لعرض صوتي. كانت النسخة المكتوبة تحتوي جملًا طويلة يستطيع القارئ الرجوع إلى أولها، لكن النص المسموع يمر مرة واحدة في الزمن. في أول تجربة سماع ضاع المشاركون عند سلسلة من أربعة أسماء وضمائر. لم تكن الكلمات صعبة؛ المشكلة أن المرجع لا يبقى أمام العين. قسم المترجم الجملة إلى وحدتين وكرر اسم الشخصية مرة، فعدّ محرر ذلك تكرارًا زائدًا وفق معيار الكتابة. أظهر الاختبار أن التكرار هنا يؤدي وظيفة في الذاكرة السمعية. واجه الفريق مشكلة أخرى في لعبة لفظية تعتمد على شكل كلمتين متشابهتين على الصفحة ولا تتشابهان كثيرًا في الصوت. اختار المترجم تعويضها بتقابل صوتي مختلف، وشرح في الهامش الرقمي سبب التغيير. خلص الفريق إلى أن الترجمة بين وسيطين ليست نقل كلمات فقط؛ إمكان الرجوع، وسرعة الفهم، وما هو مسموع أو مرئي كلها شروط تغير ما يحتاجه النص ليؤدي الوظيفة نفسها.',['محرر'],[('gist','لماذا احتاج النص الصوتي إلى تعديل؟','لأن السماع يفرض ذاكرة خطية ولا يتيح الرجوع البصري نفسه.',None),('literal_detail','ما التعديل في سلسلة الأسماء؟','قسمت الجملة وكرر اسم الشخصية.',None),('inference','لماذا لا يعد التكرار عيبًا هنا؟','لأنه يساعد المستمع على تثبيت المرجع في الذاكرة.',None),('argument_relation','ما وظيفة مثال اللعبة اللفظية؟','إظهار أن التحول من المرئي إلى المسموع قد يغير مادة الأثر نفسه.',None),('main_claim','ما الذي يجب أن تحافظ عليه ترجمة الوسيط؟','وظيفة النص ضمن شروط الإدراك الجديدة لا عدد الكلمات نفسه.',None),('contrast','ما الفرق بين القراءة والسماع هنا؟','القارئ يستطيع الرجوع بصريًا، والمستمع يتلقى تسلسلًا زمنيًا عابرًا.',None),('inference','لماذا شرح الفريق التعويض؟','لجعل خسارة الأصل والاختيار البديل قابلين للمراجعة.',None),('summary','ما عاملان يغيرهما الوسيط؟','إمكان الرجوع وسرعة تتبع المراجع والأثر الصوتي أو البصري.',None),('single_word_definition','ما معنى «مسموع»؟','ما يصل إلى المتلقي عن طريق الصوت ويمكن سماعه.','مسموع'),('single_word_definition','ما معنى «سماع»؟','فعل تلقي الأصوات أو الاستماع إليها.','سماع')]),
('p06','الترجمة تفسير مقيد لا نسخة شفافة','fluency','C2 translation synthesis',[],'تجمع الوحدة بين خمسة اختبارات. يسأل المترجم عن المقصود لا عن المقابل الحرفي فقط، ويختار تعبيرًا فصيحًا من دون الادعاء أن السلاسة تمحو كل خسارة. ويقارن النسخ لكنه لا يحول الفرق إلى يقين قبل فحص الجمهور والزمن وسلسلة النقل. ويعامل الناقد الأسطورة بوصفها بنية قد تحتمل قراءات متنافسة لا وعاءً لرسالة واحدة. أما النص المحدث فيحمل بصمة يختار المكيف ما الذي يحفظه منها، ولذلك يصبح التحديث تفسيرًا مسؤولًا لا استنساخًا. وعندما ينتقل النص من المرئي إلى المسموع تتغير شروط الذاكرة؛ قد يصبح التكرار ضروريًا، ويحتاج السماع إلى روابط لا يحتاجها القارئ الذي يستطيع العودة إلى الصفحة. لا تعني هذه المرونة أن كل ترجمة صحيحة. القيود باقية: السياق، الوظيفة، الأدلة، والجمهور. لكن الأمانة لا تعني التطابق الميكانيكي؛ تعني أن يعرف المترجم والناقد أين تغير النص، وما الغرض من التغيير، وما البدائل التي كانت ممكنة.',['مقصود','فصيح','قارن','يقين','ناقد','أسطورة','محدث','بصمة','مسموع','سماع'],[('gist','ما الفكرة العامة؟','أن الترجمة تفسير مقيد بالوظيفة والسياق والأدلة وليست نسخًا شفافًا.',None),('literal_detail','ما الاختبارات الخمسة؟','المقصود والأسلوب، مقارنة النسخ، قراءة الأسطورة، التحديث، وتحول الوسيط.',None),('inference','لماذا لا تعني المرونة صحة كل ترجمة؟','لأن الاختيارات ما زالت مقيدة بالسياق والوظيفة والأدلة.',None),('argument_relation','ما وظيفة جمع الكتابة والصوت؟','إظهار أن الوسيط نفسه يغير شروط ما يعد نقلًا ناجحًا.',None),('main_claim','ما معنى الأمانة وفق الخاتمة؟','معرفة ما تغير ولماذا وما البدائل، لا التطابق الميكانيكي وحده.',None),('contrast','ما الفرق بين التفسير الحر والتفسير المقيد؟','الحر لا يلتزم بأدلة الأصل، والمقيد يبرر تغيراته بوظيفة وسياق.',None),('inference','لماذا يجب إعلان الخسارة؟','حتى تصبح مفاضلات الترجمة قابلة للفحص بدل أن تبدو محايدة.',None),('summary','ما المهارة العامة؟','مقارنة اختيارات الترجمة والتكييف بحسب معناها ووظيفتها ووسيطها.',None),('inference','كيف يتغير اليقين عبر المقارنة؟','يزداد فقط عندما تستبعد أدلة مستقلة البدائل المنافسة.',None),('inference','لماذا تبقى البصمة مهمة؟','لأنها تحدد ما تدعي النسخة المحدثة الحفاظ عليه عبر تغير التفاصيل.',None)])]
def build(t,d):
 pid,title,ptype,genre,targets,text,reviews,items=t;ts=[target(f,text,d) for f in targets];ids={x['form']:x['id'] for x in ts};q,a=qa(items,ids);return {'id':f'ar-c2-u07-{pid}','language':'ar','cefr':'C2','unit':7,'sequence':30+int(pid[1:]),'revision':1,'title':title,'text':text,'passage_type':ptype,'genre':genre,'domains':['culture','translation','interpretation'],'topics':['translation','interpretation'],'new_lexical_targets':ts,'review_lexical_targets':[review(f,'R2' if ptype=='fluency' else 'R4','running_text',d) for f in reviews],'grammar_targets':[{'id':f'ar-c2-u07-{pid}-grammar','role':'integration' if ptype=='fluency' else 'new','description':'تحليل العلاقة بين الصياغة والسياق والوسيط والتأويل'}],'discourse_targets':[{'id':f'c2-u07-{pid}-discourse','role':'integration' if ptype=='fluency' else 'new','description':'compare translation and interpretation choices under explicit contextual constraints'}],'questions':q,'answer_key':a,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!؟](?:\s|$)',text))),'estimated_known_token_coverage':0,'paired_text_group':None,'prerequisites':['Arabic A1-C1 generation corpus','Arabic C2 Units 01-06 generation corpus'],'difficulty_notes_internal':'C2 Unit 07 generation draft: culture, translation, and interpretation through equivalence, register, adaptation, and medium.','speed_training':{'timed':ptype=='fluency','benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'none' if ptype=='fluency' else 'controlled','notes':'generation stage; formal audit deferred'},'quality':{'status':'draft','linguistic_review':'pending','pedagogical_review':'pending','coverage_check':'pending','answer_key_check':'pending','schema_check':'pending','fact_check':'not_required','notes':['All cultures, works, translations, and examples are fictional curriculum material; formal audit battery deferred.']},'reader_tags':['unit_role:'+ptype,'generation_batch','c2'],'complexity_profile':{'mean_sentence_length':None,'median_sentence_length':None,'clause_count':None,'subordination_count':None,'coordination_count':None,'connective_diversity':None,'lexical_diversity':None,'reference_chain_max_distance':None,'multiword_expression_count':None,'morphology_notes':'C2 translation-critical MSA.','inference_depth':'cross_paragraph_argument_reconstruction'}}
def main():
 d=lexicon();prior=prior_new();forms=[f for t in R for f in t[4]]+[f for t in R for f in t[6]];missing=sorted({f for f in forms if norm(f) not in d});
 if missing:raise KeyError('missing cleared forms: '+str(missing))
 collisions={f:prior[norm(f)] for t in R for f in t[4] if norm(f) in prior}
 if collisions:raise RuntimeError('C2 Unit 07 new-target collision: '+json.dumps(collisions,ensure_ascii=False,sort_keys=True))
 rows=[json.loads(l) for l in OUT.read_text(encoding='utf-8').splitlines() if l.strip()] if OUT.exists() else [];rows=[r for r in rows if not(r.get('cefr')=='C2' and r.get('unit')==7)];rows.extend(build(t,d) for t in R);rows.sort(key=lambda r:r.get('sequence',0));OUT.write_text('\n'.join(json.dumps(r,ensure_ascii=False,sort_keys=True) for r in rows)+'\n',encoding='utf-8');print(f'wrote 6 Arabic C2 Unit 07 passages; total C2 rows={len(rows)}; prior-target collisions=0')
if __name__=='__main__':main()
