#!/usr/bin/env python3
"""Append French B1 Unit 07 (sequences 37-42) as one guarded transfer batch."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit06 as prev
base=prev.base
REPO=Path(__file__).resolve().parents[2]
A1=REPO/'reading'/'french'/'a1'/'passages.jsonl'; A2=REPO/'reading'/'french'/'a2'/'passages.jsonl'; CANON=REPO/'reading'/'french'/'b1'/'passages.jsonl'; SCHEMA=REPO/'reading'/'schema'/'passage.schema.json'
EXPECTED_A1_BLOB='0493a2fa13e51b5997db05e91cdea4d8dc5e647b'; EXPECTED_A2_BLOB='d0a80b8866071f426019aa0ad143e1d270dba4de'; EXPECTED_B1_BLOB='916c7ec05861f7a6ffce2352dd1bc78d88f1bf7a'
FORMS=('entier','doucement','charger','opération','reposer','bord','blague','plaisanter','deviner','classe','second','intelligent','naître','survivre','debout')
SPECS=[
{'id':'fr-b1-u07-p01','sequence':37,'ptype':'instructional','title':'Charger doucement le matériel avant une journée entière','genre':'equipment-preparation narrative','domains':['educational','professional'],'topics':['equipment','preparation','procedure'],'forms':['entier','doucement','charger'],'reviews':['signer','règle','témoin'],'paragraphs':[
"Pour une journée de collecte sonore, une classe emprunte plusieurs enregistreurs à la bibliothèque. Le projet doit durer un jour entier, alors Camille prépare le matériel la veille. La règle du prêt indique qu’il faut vérifier chaque appareil avant de signer la fiche de sortie. Un témoin du service confirme seulement le numéro et l’état de l’équipement. Camille commence par charger les batteries et pose les câbles doucement afin de ne pas tordre les connecteurs.",
"Elle ne se contente pas de voir une icône verte. Après avoir laissé charger les appareils, elle les allume un par un et enregistre quelques secondes. Un appareil s’éteint rapidement malgré l’indicateur. Camille le met de côté et reprend la procédure avec une autre batterie. Elle explique à la classe qu’une journée entière exige une marge : si un appareil semble prêt seulement quelques minutes, il vaut mieux le tester maintenant. La règle devient ainsi une méthode de préparation plutôt qu’une formalité à signer.",
"Le matin suivant, tous les appareils fonctionnent. Camille range doucement les microphones dans des pochettes séparées et distribue les rôles. Le témoin vérifie une dernière fois la liste, puis chaque groupe peut signer pour son matériel. L’expérience montre qu’il faut charger assez tôt pour avoir le temps de détecter un problème. « Entier » ne signifie pas qu’un appareil doit fonctionner sans pause ni vérification ; cela décrit la durée du projet que l’équipe doit pouvoir couvrir. En préparant doucement chaque pièce et en laissant une trace claire, la classe commence la journée avec moins d’incertitude."
],'grammar':[{'id':'fr-b1-u07-entier-duration','role':'new','description':'use entier with a time period and infinitive sequencing to plan full-duration readiness'}],'discourse':[{'id':'fr-b1-u07-prep-margin','role':'new','description':'connect charging, testing and documentation to readiness over a whole work period'}],'items':[
('gist','Pourquoi Camille prépare-t-elle le matériel la veille ?','Pour pouvoir charger et tester les appareils avant une journée entière de collecte.',['charger','entier']),('literal_detail','Que confirme le témoin ?','Le numéro et l’état du matériel.',['témoin']),('cause_effect','Pourquoi un appareil est-il mis de côté ?','Parce qu’il s’éteint rapidement malgré son indicateur.',['charger']),('vocabulary_in_context','Que signifie « entier » dans « un jour entier » ?','La totalité de la journée prévue pour le projet.',['entier']),('vocabulary_in_context','Pourquoi « doucement » est-il utilisé ?','Pour indiquer une manipulation soigneuse des câbles et microphones.',['doucement']),('inference','Pourquoi l’icône verte ne suffit-elle pas ?','Parce qu’un test réel peut révéler un problème que l’indicateur ne montre pas.',['charger']),('motive','Pourquoi la règle est-elle relue avant de signer ?','Pour transformer la procédure en préparation comprise plutôt qu’en formalité.',['règle','signer']),('grammar_in_context','Quel rôle joue « entier » dans la planification ?','Il fixe la durée que le matériel doit pouvoir couvrir.',['entier']),('cloze_transfer','Complète : Camille doit _____ les batteries avant la sortie.','charger',['charger']),('summary','Résume la préparation.','Pour couvrir un jour entier, Camille suit la règle avant de signer, laisse un témoin confirmer le matériel, prend le temps de charger les batteries et manipule doucement les appareils.',['entier','règle','signer','témoin','charger','doucement'])]},
{'id':'fr-b1-u07-p02','sequence':38,'ptype':'reinforcement','title':'Une opération qui repose sur l’observation du bord','genre':'shoreline restoration planning narrative','domains':['educational','public'],'topics':['environment','fieldwork','planning'],'forms':['opération','reposer','bord'],'reviews':['dangereux','surveiller','risquer'],'paragraphs':[
"Une équipe étudiante prépare une opération de nettoyage et d’observation le long d’un petit lac. Le plan repose sur une idée simple : retirer les déchets visibles sans déranger les zones fragiles. Avant de commencer, la responsable montre le bord sur une carte et indique les secteurs qui doivent seulement être observés. Certaines parties sont glissantes ; il serait dangereux de s’y approcher sans équipement adapté. Camille aide donc à surveiller les limites marquées depuis le sentier.",
"L’opération comporte deux groupes. Le premier ramasse les déchets accessibles près du bord. Le second note les plantes et photographie les changements depuis des points fixes. Camille explique que l’étude doit reposer sur des observations comparables. Si chaque personne change constamment de position, l’équipe risque de confondre une différence de vue avec une différence réelle dans le milieu. Surveiller les mêmes points permet de réduire ce risque sans entrer dans une zone dangereuse.",
"À la fin, les étudiants réunissent les sacs et les fiches. Ils constatent qu’une bonne opération ne repose pas sur la quantité maximale de terrain parcouru. Elle dépend plutôt d’un objectif clair et de limites respectées. Le bord du lac devient à la fois un lieu d’action et une frontière méthodologique : certains secteurs peuvent être nettoyés, d’autres seulement observés. Camille retient qu’on peut risquer de perdre la qualité des données en voulant tout couvrir. Surveiller une limite n’est donc pas un obstacle au travail ; c’est parfois ce qui rend l’opération plus sûre et ses résultats plus comparables."
],'grammar':[{'id':'fr-b1-u07-reposer-sur','role':'new','description':'use reposer sur to state the basis of a plan or conclusion'}],'discourse':[{'id':'fr-b1-u07-shoreline-boundary','role':'new','description':'connect operational boundaries to safety and comparable observation'}],'items':[
('gist','Sur quoi repose le plan de l’équipe ?','Sur un nettoyage limité aux zones accessibles et une observation comparable du bord.',['reposer','bord','opération']),('literal_detail','Que fait le second groupe ?','Il note les plantes et photographie les changements depuis des points fixes.',['opération']),('cause_effect','Pourquoi certains secteurs sont-ils seulement observés ?','Parce qu’ils sont fragiles ou dangereux à approcher.',['dangereux','bord']),('vocabulary_in_context','Que signifie « opération » ici ?','L’action organisée de nettoyage et d’observation.',['opération']),('vocabulary_in_context','Que signifie « reposer sur » ?','Être fondé sur une méthode ou un principe.',['reposer']),('inference','Pourquoi les points fixes améliorent-ils les données ?','Ils évitent de confondre un changement de point de vue avec un changement réel.',['surveiller']),('motive','Pourquoi surveiller les limites ?','Pour réduire le risque et protéger les zones dangereuses ou fragiles.',['surveiller','risquer']),('grammar_in_context','Dans « le plan repose sur une idée », quel rapport est exprimé ?','L’idée constitue la base du plan.',['reposer']),('cloze_transfer','Complète : L’équipe observe le _____ du lac depuis des points définis.','bord',['bord']),('summary','Résume la méthode.','L’opération repose sur une observation contrôlée du bord : l’équipe surveille les limites, évite le dangereux et ne veut pas risquer la qualité des données.',['opération','reposer','bord','surveiller','dangereux','risquer'])]},
{'id':'fr-b1-u07-p03','sequence':39,'ptype':'interleaved','title':'Deviner une blague n’est pas la même chose que comprendre pourquoi on plaisante','genre':'communication workshop narrative','domains':['educational','personal'],'topics':['humor','communication','interpretation'],'forms':['blague','plaisanter','deviner'],'reviews':['journal','impression','signifier'],'paragraphs':[
"Dans un atelier de communication, l’enseignante montre deux courts messages tirés d’un faux journal interne. Le premier annonce sérieusement un changement d’horaire. Le second contient une blague sur une imprimante qui « demande des vacances ». Plusieurs élèves ont d’abord l’impression que les deux messages donnent une information pratique. L’enseignante leur demande de deviner lequel cherche surtout à faire sourire et d’expliquer quels indices peuvent le signifier.",
"Camille remarque que la blague utilise une situation impossible et un ton exagéré. Pourtant, elle ajoute qu’on ne peut pas toujours deviner l’intention d’une personne uniquement à partir d’une phrase. Dans une conversation orale, la voix ou le contexte peut montrer qu’elle veut plaisanter ; dans un message écrit, ces indices sont parfois absents. L’atelier compare donc l’impression initiale avec le but du texte et avec l’endroit où il est publié dans le journal.",
"Le groupe écrit ensuite ses propres exemples. Une règle apparaît : plaisanter peut créer une relation détendue, mais une blague placée dans une consigne urgente peut aussi créer de la confusion. Camille décide qu’il faut parfois indiquer clairement le changement de ton au lieu de demander au lecteur de tout deviner. Le mot « blague » décrit le contenu humoristique, tandis que « plaisanter » décrit l’action ou l’intention de parler sans sérieux. L’exercice lui apprend qu’un signe peut signifier l’humour sans le garantir. Pour comprendre un message, elle doit donc vérifier le contexte plutôt que rester seulement avec sa première impression."
],'grammar':[{'id':'fr-b1-u07-deviner-lequel','role':'new','description':'use deviner + indirect question to infer an intended interpretation'}],'discourse':[{'id':'fr-b1-u07-humor-context','role':'new','description':'compare tone, context and placement when interpreting humor in written communication'}],'items':[
('gist','Quelle distinction l’atelier enseigne-t-il ?','Il distingue la blague, l’action de plaisanter et la nécessité de vérifier le contexte plutôt que seulement deviner.',['blague','plaisanter','deviner']),('literal_detail','Quelle image humoristique apparaît dans le second message ?','Une imprimante qui demande des vacances.',['blague']),('cause_effect','Pourquoi l’humour écrit peut-il être ambigu ?','Parce que les indices de voix et de contexte peuvent manquer.',['deviner']),('vocabulary_in_context','Que signifie « plaisanter » ?','Parler ou écrire avec une intention humoristique plutôt que sérieuse.',['plaisanter']),('vocabulary_in_context','Que signifie « deviner » ici ?','Inférer une intention à partir d’indices sans la connaître directement.',['deviner']),('inference','Pourquoi la place du message dans le journal compte-t-elle ?','Elle donne un contexte qui peut changer l’impression sur son but.',['journal','impression']),('motive','Pourquoi Camille veut-elle parfois annoncer le changement de ton ?','Pour éviter que le lecteur doive tout deviner dans une situation importante.',['deviner']),('reference_resolution','Dans « ces indices », à quoi renvoie « ces » ?','À la voix et au contexte qui peuvent montrer qu’une personne veut plaisanter.',['plaisanter']),('cloze_transfer','Complète : Une _____ peut être drôle sans être adaptée à une consigne urgente.','blague',['blague']),('summary','Résume l’atelier.','Une blague peut donner une impression particulière dans un journal, mais pour deviner ce qu’elle veut signifier et savoir si quelqu’un veut plaisanter, il faut examiner le contexte.',['blague','impression','journal','deviner','signifier','plaisanter'])]},
{'id':'fr-b1-u07-p04','sequence':40,'ptype':'transfer','title':'Une classe cherche un second plan plus intelligent','genre':'classroom design project narrative','domains':['educational'],'topics':['classroom project','iteration','planning'],'forms':['classe','second','intelligent'],'reviews':['personnel','mission','prévoir'],'paragraphs':[
"Une classe doit concevoir un petit espace de lecture mobile pour la bibliothèque de l’école. Le premier dessin prévoit une grande structure difficile à déplacer. Camille rappelle que la mission est de créer un meuble que le personnel puisse utiliser dans plusieurs salles. La classe décide donc de préparer un second dessin avant de construire quoi que ce soit. Elle veut trouver une solution plus intelligente, c’est-à-dire mieux adaptée aux contraintes réelles plutôt que simplement plus compliquée.",
"Dans le second plan, les élèves séparent la structure en modules légers. Le personnel peut en déplacer un seul ou plusieurs selon la taille de la salle. Pour prévoir les livres lourds, la classe garde une base stable et place les étagères les plus solides en bas. Un élève propose d’ajouter un écran, mais le groupe demande si cet ajout aide réellement la mission. Il conclut qu’une solution intelligente peut aussi consister à ne pas ajouter une fonction inutile.",
"La classe construit ensuite un modèle en carton et demande au personnel de le tester. Les remarques conduisent à un second ajustement : les poignées doivent être plus hautes. Camille comprend que « second » n’est pas seulement un numéro ; dans un processus de conception, il représente la possibilité de corriger une première idée. Le mot intelligent ne décrit pas une machine qui pense. Ici, il qualifie une décision qui relie clairement le besoin, la mission et les contraintes. En apprenant à prévoir un test avant la construction finale, la classe transforme son second plan en solution plus simple et plus utile."
],'grammar':[{'id':'fr-b1-u07-second-iteration','role':'new','description':'use ordinal second to structure iterative design and comparison'}],'discourse':[{'id':'fr-b1-u07-smart-by-fit','role':'new','description':'define an intelligent design choice by fit with mission and constraints rather than added complexity'}],'items':[
('gist','Pourquoi la classe prépare-t-elle un second plan ?','Pour mieux adapter la conception à la mission et au personnel qui devra la déplacer.',['classe','second','mission','personnel']),('literal_detail','Que change le second plan ?','Il sépare la structure en modules plus légers.',['second']),('cause_effect','Pourquoi l’écran n’est-il pas ajouté ?','Parce qu’il ne soutient pas assez la mission pour justifier la complexité.',['intelligent','mission']),('vocabulary_in_context','Que signifie « intelligent » pour la solution ?','Bien adaptée aux besoins et contraintes plutôt que simplement complexe.',['intelligent']),('vocabulary_in_context','Que signifie « classe » ici ?','Le groupe d’élèves qui réalise le projet.',['classe']),('inference','Pourquoi le test en carton est-il utile ?','Il permet de prévoir des corrections avant de construire la version finale.',['prévoir']),('motive','Pourquoi consulter le personnel ?','Parce qu’il utilisera réellement le meuble et peut identifier des contraintes pratiques.',['personnel']),('grammar_in_context','Quel rôle joue « second » dans le récit ?','Il marque une nouvelle version créée après l’évaluation de la première.',['second']),('cloze_transfer','Complète : La _____ prépare un second dessin avant de construire.','classe',['classe','second']),('summary','Résume la conception.','La classe prépare un second plan plus intelligent en reliant la mission au personnel, en essayant de prévoir les contraintes et en supprimant les fonctions inutiles.',['classe','second','intelligent','mission','personnel','prévoir'])]},
{'id':'fr-b1-u07-p05','sequence':41,'ptype':'transfer','title':'Comment un jeune arbre peut naître, survivre et rester debout','genre':'urban ecology observation narrative','domains':['educational','public'],'topics':['urban trees','ecology','long-term observation'],'forms':['naître','survivre','debout'],'reviews':['discuter','colère','souhaiter'],'paragraphs':[
"Dans un parc urbain, un groupe suit plusieurs jeunes arbres plantés après une tempête. L’animatrice explique qu’un arbre peut naître d’une graine dans une pépinière, mais que sa survie en ville dépend ensuite de nombreuses conditions. Les élèves observent un arbre encore debout malgré une branche cassée. Certains souhaitent immédiatement retirer toutes les branches abîmées ; d’autres veulent discuter d’abord avec le service des parcs afin de comprendre ce qui est recommandé.",
"L’animatrice montre les fiches de suivi. Un arbre peut survivre à un épisode difficile sans retrouver tout de suite sa forme précédente. Rester debout ne prouve pas non plus qu’il est en parfaite santé. Le groupe apprend donc à distinguer trois questions : comment l’arbre a pu naître et être planté, quelles conditions l’aident à survivre, et quels signes montrent qu’il peut rester debout en sécurité. Une discussion calme évite que la colère contre les dégâts de la tempête conduise à une décision trop rapide.",
"Les élèves mesurent l’ombre, observent le sol et notent les interventions déjà réalisées. Ils souhaitent que le parc reste accueillant, mais ils comprennent qu’un souhait doit être relié à des observations. Camille propose de discuter des résultats lors de la prochaine visite plutôt que de décider maintenant de l’avenir de chaque arbre. L’histoire d’un arbre ne s’arrête donc ni au moment où il peut naître ni au fait qu’il soit encore debout. Pour survivre longtemps, il dépend d’un entretien adapté et d’un environnement changeant. Cette perspective transforme la tempête en étude de continuité plutôt qu’en simple image de destruction."
],'grammar':[{'id':'fr-b1-u07-naître-survivre','role':'new','description':'contrast event verb naître with duration/state verb survivre and adverb debout'}],'discourse':[{'id':'fr-b1-u07-tree-lifecycle','role':'new','description':'separate origin, survival and visible standing condition in long-term ecological reasoning'}],'items':[
('gist','Quelles trois étapes le groupe distingue-t-il ?','Comment l’arbre peut naître, quelles conditions l’aident à survivre et ce que signifie rester debout.',['naître','survivre','debout']),('literal_detail','Quel dommage l’arbre observé a-t-il subi ?','Une branche cassée.',['debout']),('cause_effect','Pourquoi rester debout ne suffit-il pas ?','Parce qu’un arbre peut rester debout tout en ayant besoin de soins ou d’une évaluation.',['debout','survivre']),('vocabulary_in_context','Que signifie « survivre » ici ?','Continuer à vivre malgré des conditions difficiles.',['survivre']),('vocabulary_in_context','Que signifie « naître » dans ce contexte ?','Commencer sa vie, ici à partir d’une graine avant la plantation.',['naître']),('inference','Pourquoi le groupe reporte-t-il certaines décisions ?','Pour discuter des observations et éviter de suivre seulement un souhait ou une réaction émotionnelle.',['discuter','souhaiter']),('motive','Pourquoi parler de la colère liée à la tempête ?','Pour montrer qu’une émotion compréhensible ne doit pas remplacer l’évaluation des arbres.',['colère']),('reference_resolution','Dans « il dépend d’un entretien adapté », à quoi renvoie « il » ?','À l’arbre qui doit survivre longtemps.',['survivre']),('cloze_transfer','Complète : Même après la tempête, l’arbre est encore _____.','debout',['debout']),('summary','Résume l’observation.','Le groupe étudie comment un arbre peut naître, survivre et rester debout, puis choisit de discuter avant d’agir malgré la colère et ce que chacun peut souhaiter.',['naître','survivre','debout','discuter','colère','souhaiter'])]}
]
CHECKPOINT={'id':'fr-b1-u07-p06','sequence':42,'ptype':'checkpoint','title':'Préparer, observer, interpréter et corriger','genre':'B1 cumulative iteration summary','domains':['educational','public','professional'],'topics':['preparation','environment','communication','design','ecology'],'paragraphs':[
"Camille apprend qu’un projet entier devient plus fiable lorsqu’on prépare les détails assez tôt. On peut charger le matériel et le manipuler doucement avant une sortie. Une opération sur le terrain peut reposer sur des observations faites au bord d’une zone fragile. Dans une conversation, une blague peut être difficile à interpréter : il faut parfois deviner si une personne veut plaisanter en regardant le contexte.",
"La même logique vaut pour la conception et l’écologie. Une classe peut produire un second plan plus intelligent après un test. Un arbre peut naître, survivre à une tempête et rester debout sans que ces trois faits signifient exactement la même chose. Dans chaque cas, la correction dépend d’une distinction précise entre l’objectif, les indices et la prochaine action.",
"Les acquis de l’unité précédente restent actifs. Camille peut signer après avoir compris une règle, avec un témoin limité au processus ; surveiller un signal dangereux sans risquer une intervention inutile ; lire un journal au-delà de sa première impression pour comprendre ce qu’un détail peut signifier ; prévoir le personnel selon sa mission ; puis discuter malgré la colère de ce que chacun peut souhaiter. Elle relie maintenant ces méthodes à l’itération : préparer le projet entier, charger doucement, définir une opération qui repose sur le bord observé, reconnaître une blague sans devoir tout deviner, laisser une classe essayer un second choix intelligent, et suivre ce qui peut naître, survivre et rester debout."
],'grammar':[{'id':'fr-b1-u07-cumulative-iteration','role':'integration','description':'integrate sequence, basis, inference and lifecycle contrasts across five transfer contexts'}],'discourse':[{'id':'fr-b1-u07-prepare-observe-revise','role':'integration','description':'synthesize preparation, observation, interpretation and revision as a general B1 strategy'}],'items':[
('gist','Quelle stratégie générale apparaît dans les cinq situations ?','Préparer, observer les indices, interpréter prudemment puis corriger la prochaine action.',['entier','reposer']),('literal_detail','Quels mots décrivent la préparation du matériel ?','entier, doucement et charger',['entier','doucement','charger']),('cause_effect','Pourquoi l’opération est-elle limitée au bord observé ?','Parce qu’elle repose sur des limites qui rendent le travail plus sûr et comparable.',['opération','reposer','bord']),('vocabulary_in_context','Quels mots appartiennent à l’atelier sur l’humour ?','blague, plaisanter et deviner',['blague','plaisanter','deviner']),('vocabulary_in_context','Quels mots décrivent l’itération de la classe ?','classe, second et intelligent',['classe','second','intelligent']),('inference','Pourquoi naître, survivre et être debout ne sont-ils pas équivalents ?','Ils décrivent l’origine, la continuité de la vie et un état visible différent.',['naître','survivre','debout']),('motive','Pourquoi Camille conserve-t-elle les méthodes de l’unité précédente ?','Parce qu’elles l’aident à vérifier les conditions et les preuves avant de corriger une décision.',['surveiller','prévoir']),('reference_resolution','Dans « ces trois faits », quels faits sont visés ?','Naître, survivre à une tempête et rester debout.',['naître','survivre','debout']),('cloze_transfer','Complète : Un projet peut _____ sur plusieurs observations comparables.','reposer',['reposer']),('summary','Résume l’unité en une phrase.','Camille apprend à préparer un projet entier en chargeant doucement, organiser une opération qui peut reposer sur le bord observé, reconnaître une blague et deviner quand plaisanter, faire produire à une classe un second plan intelligent, puis distinguer naître, survivre et rester debout.',['entier','charger','doucement','opération','reposer','bord','blague','deviner','plaisanter','classe','second','intelligent','naître','survivre','debout'])]}
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);text=text_of(s);return {'id':s['id'],'language':'fr','cefr':'B1','unit':7,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B1 Unit 07 guarded transfer batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B1 Unit 07 transfer batch.']},'paired_text_group':None,'prerequisites':['French B1 Units 01-06 canonical corpus'],'difficulty_notes_internal':'B1 iteration transfer across equipment, fieldwork, humor, design and ecology.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b1_u07']}
def build(a1,a2,b1,D):
 prior=base.prior(a1+a2+b1);bad=[];prior_ids={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};prior_forms={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)}
 for f in FORMS:
  if f not in D:bad.append(f+':missing_lexicon')
  elif base.tid(D[f]['rank']) in prior_ids or f in prior_forms or prior.get(f):bad.append(f+':already_deliberate')
 if bad:raise AssertionError('B1 Unit07 candidate failures: '+', '.join(bad))
 rs=[['signer','règle','témoin'],['dangereux','surveiller','risquer'],['journal','impression','signifier'],['personnel','mission','prévoir'],['discuter','colère','souhaiter']];out=[]
 for s,rfs in zip(SPECS,rs):
  text=text_of(s);new=[base.nt(f,text,D) for f in s['forms']];reviews=[base.rev(f,prior) for f in rfs];ids={t['form']:t['id'] for t in new+reviews};out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,D) for f in FORMS];ids={t['form']:t['id'] for t in reviews};out.append(mk(CHECKPOINT,[],reviews,ids,True));return out
def main():
 for path,expected,label in [(A1,EXPECTED_A1_BLOB,'A1'),(A2,EXPECTED_A2_BLOB,'A2'),(CANON,EXPECTED_B1_BLOB,'B1')]:
  blob=subprocess.check_output(['git','hash-object',str(path)],text=True).strip();
  if blob!=expected:raise AssertionError(f'{label} blob drift: {blob} != {expected}')
 a1=[json.loads(x) for x in A1.read_text().splitlines() if x.strip()];a2=[json.loads(x) for x in A2.read_text().splitlines() if x.strip()];b1=[json.loads(x) for x in CANON.read_text().splitlines() if x.strip()]
 if len(b1)!=36 or b1[-1]['id']!='fr-b1-u06-p06':raise AssertionError('unexpected prerequisite frontier')
 D=base.deck();unit=build(a1,a2,b1,D);V=Draft202012Validator(json.loads(SCHEMA.read_text()));prior_ids={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};prior_forms={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};newids=[];newforms=[]
 for r in unit:
  errs=sorted(V.iter_errors(r),key=lambda e:list(e.path));
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:4]]}")
  if not 220<=r['word_count']<=350:raise AssertionError(f"{r['id']}: B1 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(r['id']+': assessment count')
  if r['sequence']<=41 and len(r['new_lexical_targets'])!=3:raise AssertionError(r['id']+': load')
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for fld in ('new_lexical_targets','review_lexical_targets') for t in r.get(fld,[]) if isinstance(t,dict)}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage")
  for t in r['new_lexical_targets']:
   s=D.get(t['form']);
   if t['id'] in prior_ids or t['form'] in prior_forms or not s or t['source_rank']!=s['rank'] or t['id']!=base.tid(s['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: source/exposure/freshness drift {t}")
   newids.append(t['id']);newforms.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(newids)!=15 or len(set(newids))!=15 or len(set(newforms))!=15 or unit[-1]['new_lexical_targets']!=[]:raise AssertionError('Unit07 lexical invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b1+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':7,'b1_passages':42,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':FORMS},ensure_ascii=False))
if __name__=='__main__':main()
