#!/usr/bin/env python3
"""Generate French C1 Unit05: scientific uncertainty and communication."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit10 as u10
base=u10.base
R=Path(__file__).resolve().parents[2];C1=R/'reading/french/c1/passages.jsonl';B2=R/'reading/french/b2/passages.jsonl';SCHEMA=R/'reading/schema/passage.schema.json';LOCK=R/'reading/audit/french_c1_unit04_frontier_lock.json';PLAN=R/'reading/audit/french_c1_unit05_plan.json';SEL=R/'reading/audit/french_c1_unit05_target_selection.json'
USE={
'sûrement':'« Sûrement » signale ici un haut degré de confiance exprimé par le locuteur; le lecteur doit vérifier si les données justifient réellement ce niveau d’assurance.',
'absolument':'« Absolument » représente une formulation sans réserve; dans une communication scientifique, son emploi exige des conditions particulièrement fortes ou doit être reformulé pour conserver l’incertitude.',
'paraître':'« Paraître » distingue l’apparence initiale d’un résultat de ce que l’analyse permet d’établir après contrôle des mesures et des explications concurrentes.',
'assez':'« Assez » pose une question de suffisance : assez de données, assez de précision ou assez de cohérence pour soutenir quelle conclusion exactement ?',
'sauf':'« Sauf » rend visible une exception; une exception pertinente peut limiter la portée d’une règle générale ou révéler un mécanisme différent.',
'premier':'« Premier » situe une observation dans une séquence : un premier résultat peut orienter la suite sans être traité comme conclusion définitive.',
'finir':'« Finir » une collecte ou un essai suppose un critère d’arrêt annoncé; sinon le moment de fin peut être choisi après avoir vu les résultats.',
'moins':'« Moins » exprime une comparaison de magnitude; communiquer un effet moindre exige de préciser la référence et l’incertitude autour de l’écart.',
'blanc':'« Blanc » sert d’exemple de catégorie visuelle codée; l’analyse vérifie si la frontière de codage est stable et pertinente pour la question scientifique.',
'rouge':'« Rouge » montre la même difficulté : une catégorie apparemment évidente peut dépendre d’un seuil, d’un instrument ou de conditions d’observation.',
'espèce':'« Espèce » illustre une catégorie scientifique dont la définition doit être explicitée lorsque des critères différents produisent des regroupements différents.',
'papier':'Un « papier » scientifique est un objet de communication soumis à des choix de méthode, de sélection de résultats et de présentation; sa publication ne transforme pas automatiquement chaque phrase en fait établi.',
'ressentir':'« Ressentir » décrit une expérience rapportée par une personne; cette donnée est réelle comme expérience mais ne mesure pas nécessairement le même phénomène qu’un indicateur physiologique ou comportemental.',
'craindre':'« Craindre » révèle une perception du risque qui peut influencer les décisions; l’analyse compare cette perception avec fréquence, gravité et incertitude plutôt que de la confondre avec la probabilité mesurée.',
'mort':'La « mort » représente un résultat grave et irréversible; même rare, un tel dommage peut modifier le seuil de précaution et la manière de communiquer l’incertitude.',
'blesser':'« Blesser » permet de distinguer présence d’un dommage, gravité du dommage et probabilité qu’il survienne; ces dimensions ne doivent pas être compressées en un seul mot comme « dangereux ».',
'américain':'« Américain » sert ici à marquer une population ou un contexte d’étude précis; un résultat obtenu dans ce cadre ne doit pas être généralisé sans examiner les différences pertinentes.',
'partout':'« Partout » représente une généralisation maximale; une affirmation scientifique doit montrer quelles données autorisent réellement cette portée géographique ou institutionnelle.',
'cours':'L’expression « au cours de » situe un changement dans une période; elle aide à distinguer tendance temporelle, événement ponctuel et simple ordre narratif.',
'fond':'Le « fond » désigne ici le niveau de base ou le contexte sur lequel un signal est interprété; sans cette référence, une variation apparente peut être trompeuse.'
}
EXTRA=[
"La communication de l’incertitude ne consiste pas à ajouter une formule prudente à la fin d’un texte. Elle relie chaque degré de confiance à une source d’information, une hypothèse et une possibilité de révision. Le lecteur peut ainsi distinguer ce qui est bien établi, ce qui reste plausible et ce qui dépend fortement d’un choix méthodologique.",
"Le contreargument le plus utile demande quelle autre explication produirait les mêmes observations. Une analyse C1 ne se contente pas de citer cette possibilité : elle indique quel test, quelle population ou quelle mesure permettrait de départager les hypothèses et comment le résultat modifierait la conclusion.",
"La portée doit également être traitée comme un résultat. Une étude peut être précise dans son propre échantillon et fragile lorsqu’on change d’âge, de pays, d’institution ou de période. Le résumé scientifique conserve donc les conditions qui rendent le transfert raisonnable au lieu de transformer une moyenne locale en vérité universelle.",
"Enfin, la règle de révision est explicite. Une nouvelle mesure, une réplication ou une observation contradictoire n’oblige pas toujours à abandonner toute la conclusion; elle peut réduire la confiance, restreindre la portée ou déplacer le mécanisme proposé. Cette gradation évite l’alternative trompeuse entre certitude totale et ignorance complète."
]
def h(p):return subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
def fit(paras,lo,hi):
 p=list(paras);text='\n\n'.join(p);i=0
 while len(text.split())<lo and i<len(EXTRA):p[-1]+=' '+EXTRA[i];i+=1;text='\n\n'.join(p)
 if len(text.split())<lo:raise AssertionError(f'Unit05 below C1 minimum {len(text.split())} < {lo}')
 if len(text.split())>hi:raise AssertionError(f'Unit05 above C1 maximum {len(text.split())} > {hi}')
 return p,text
def review_bridge(forms):return 'Révision du registre précédent : '+', '.join(f'« {x} »' for x in forms)+'. Ces formes servent de rappel contrôlé du travail sur langage et identité.'
def qa_items(spec,forms):
 return [('main_claim',spec['qclaim'],spec['aclaim'],[forms[0]]),('inference',spec['qinfer'],spec['ainfer'],[forms[1]]),('assumption',spec['qassume'],spec['aassume'],[forms[2]]),('argument_relation',spec['qrelation'],spec['arelation'],[forms[3]]),('stance','Quelle position méthodologique l’auteur adopte-t-il ?',spec['astance'],[forms[0],forms[3]]),('summary','Résume la logique du passage en une phrase.',spec['asummary'],[forms[1],forms[2]])]+[('vocabulary_in_context',f'Quel rôle joue « {f} » ici ?',USE[f],[f]) for f in forms]
def row(spec,forms,reviews,prior,deck,lo,hi,theme):
 paras=list(spec['paras']);paras[1]+=' '+' '.join(USE[f] for f in forms);paras[2]+=' '+review_bridge(reviews);paras,text=fit(paras,lo,hi);P=base.prior(prior);new=[base.nt(f,text,deck) for f in forms];rev=[base.rev(f,P) for f in reviews];ids={t['form']:t['id'] for t in new+rev};q,a=base.qa(qa_items(spec,forms),ids)
 return {'id':spec['id'],'language':'fr','cefr':'C1','unit':5,'sequence':spec['seq'],'revision':1,'title':spec['title'],'passage_type':'instructional','genre':spec['genre'],'domains':spec['domains'],'topics':[theme]+spec['topics'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”\"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':rev,'grammar_targets':[{'id':spec['id']+'-g1','role':'new','description':'qualify confidence, exceptions, magnitude and transfer conditions'}],'discourse_targets':[{'id':spec['id']+'-d1','role':'new','description':'separate observation, inference, uncertainty, competing explanation and revision condition'}],'questions':q,'answer_key':a,'speed_training':{'timed':False,'benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'controlled','notes':'C1 Unit05 scientific-uncertainty analysis.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Generated against exact Unit04 lock.']},'paired_text_group':None,'prerequisites':['French C1 Unit04'],'difficulty_notes_internal':'C1 scientific uncertainty and communication.','reader_tags':['unit_role:instructional','generation_batch','french_c1_u05']}
def specs():
 return [
 {'id':'fr-c1-u05-p01','seq':25,'title':'Dire ce que l’on sait sans fabriquer de certitude','genre':'research summary','domains':['educational','professional'],'topics':['confidence','uncertainty language'],'paras':["Un résultat peut être robuste sans être certain au sens absolu. Le problème de communication commence lorsque des formulations de confiance sont utilisées comme décor rhétorique plutôt que comme résumé d’éléments précis. Ce dossier propose de relier chaque mot d’assurance à la qualité des mesures, à la cohérence des réplications et aux hypothèses encore nécessaires.","Les auteurs comparent plusieurs manières de présenter le même effet. Ils distinguent la direction de l’effet, sa magnitude, l’incertitude autour de l’estimation et la probabilité qu’une autre explication soit encore compatible avec les observations. Le vocabulaire de certitude devient ainsi une conséquence de l’analyse, pas son point de départ.","Le principal contreargument affirme qu’un langage trop prudent peut rendre une information inutilisable pour le public. Le dossier répond que la solution n’est pas de supprimer l’incertitude, mais de préciser ce qui reste stable malgré elle : par exemple la direction d’un effet peut être claire alors que sa taille exacte reste ouverte.","La conclusion recommande une hiérarchie explicite des affirmations et une règle de révision. Une formulation forte doit pouvoir devenir plus faible si une réplication indépendante échoue ou si une hypothèse critique se révèle fausse."],'qclaim':'Quelle thèse organise le passage ?','aclaim':'Le niveau de confiance exprimé doit être relié aux preuves et aux hypothèses, non choisi pour rendre le message plus convaincant.','qinfer':'Que refuse le texte à propos des mots de certitude ?','ainfer':'Il refuse qu’ils remplacent l’analyse de la précision, de la réplication et des explications concurrentes.','qassume':'Quelle hypothèse sous-tend une formulation très forte ?','aassume':'Que les mesures, la méthode et les réplications rendent suffisamment improbables les explications concurrentes importantes.','qrelation':'Comment le texte répond-il à l’objection sur un langage trop prudent ?','arelation':'Il conserve l’incertitude tout en identifiant les éléments qui restent stables et utiles pour la décision.','astance':'Calibrer explicitement le langage de confiance aux preuves disponibles.','asummary':'Communiquer scientifiquement consiste à dire avec quelle force une conclusion est soutenue, pourquoi, et ce qui ferait changer cette force.'},
 {'id':'fr-c1-u05-p02','seq':26,'title':'Quand arrêter une étude et que faire des exceptions','genre':'critique','domains':['educational','professional'],'topics':['stopping rules','exceptions'],'paras':["Une étude peut produire une conclusion différente selon le moment où l’on décide de regarder définitivement les données. Pour éviter que la fin soit choisie parce qu’un résultat devient favorable, le protocole doit annoncer un critère d’arrêt ou expliquer clairement pourquoi il a changé.","Le dossier examine aussi les exceptions. Une observation atypique peut être une erreur, un cas rare ou le signal d’un mécanisme absent du modèle principal. L’exclure sans justification rend la conclusion artificiellement propre; la traiter comme représentative de tous les cas serait l’erreur inverse.","Le contreargument soutient qu’aucun protocole réel ne peut prévoir chaque événement. La critique accepte cette limite, mais exige une trace des décisions prises après coup et une analyse montrant si elles modifient substantiellement l’estimation. La transparence remplace alors l’illusion d’un plan parfaitement immuable.","La recommandation distingue enfin analyse principale et analyses de sensibilité. Le lecteur voit quelles conclusions survivent aux choix raisonnables de fin, d’exclusion et de comparaison, et lesquelles dépendent d’une décision particulière."],'qclaim':'Pourquoi le critère d’arrêt est-il important ?','aclaim':'Parce qu’un arrêt choisi après observation des résultats peut modifier la conclusion et doit donc être annoncé ou justifié.','qinfer':'Comment le texte traite-t-il une exception ?','ainfer':'Comme une observation à diagnostiquer, ni automatiquement supprimée ni automatiquement généralisée.','qassume':'Que suppose une exclusion pour être défendable ?','aassume':'Qu’un critère indépendant du résultat explique pourquoi l’observation ne répond pas à la même question que les autres.','qrelation':'Comment la critique répond-elle à l’impossibilité de tout prévoir ?','arelation':'Elle accepte les changements mais exige leur traçabilité et une analyse de sensibilité.','astance':'Préférer des règles explicites, des exceptions justifiées et des conclusions testées contre les choix analytiques.','asummary':'La robustesse dépend moins d’un protocole prétendument parfait que de la visibilité des décisions qui pourraient changer le résultat.'},
 {'id':'fr-c1-u05-p03','seq':27,'title':'Catégories, couleurs et publication : quand le codage devient une hypothèse','genre':'research summary','domains':['educational','professional'],'topics':['classification','publication'],'paras':["Classer des observations paraît parfois purement descriptif. Pourtant, la frontière entre deux catégories peut changer un résultat, surtout lorsqu’elle dépend d’un seuil visuel, d’un instrument ou d’une convention. Ce passage examine la classification comme partie de la méthode plutôt que comme étape neutre.","Les chercheurs comparent plusieurs codages et demandent si la relation principale persiste lorsque les frontières changent raisonnablement. Ils documentent aussi les cas difficiles et la concordance entre observateurs. Une catégorie utile n’est donc pas seulement facile à nommer : elle doit produire une distinction stable et pertinente pour le mécanisme étudié.","Le dossier critique ensuite le rôle de la publication. Un article peut présenter le codage final sans rendre visibles toutes les décisions intermédiaires. Le contreargument affirme qu’un texte ne peut contenir chaque détail; la réponse est de distinguer ce qui doit être dans le résumé, ce qui appartient aux méthodes et ce qui doit rester accessible dans des matériaux complémentaires.","La conclusion refuse de confondre publication et validation définitive. Le papier rend une méthode examinable par d’autres; il ne supprime ni l’incertitude du codage ni la nécessité de réplications avec des critères comparables."],'qclaim':'Pourquoi le codage est-il traité comme une hypothèse méthodologique ?','aclaim':'Parce que le choix des frontières peut modifier le résultat et doit être testé pour stabilité et pertinence.','qinfer':'Que signifie une forte concordance entre observateurs ?','ainfer':'Qu’une règle de codage est appliquée de manière relativement stable, pas nécessairement qu’elle représente parfaitement le phénomène.','qassume':'Que faut-il supposer pour interpréter une catégorie comme scientifiquement utile ?','aassume':'Que sa frontière correspond à une différence pertinente et reproductible plutôt qu’à une convention arbitraire.','qrelation':'Comment le texte répond-il à l’impossibilité de publier chaque détail ?','arelation':'Il hiérarchise les informations tout en exigeant que les décisions importantes restent accessibles et examinables.','astance':'Traiter classification et publication comme des choix méthodologiques transparents et révisables.','asummary':'Un résultat classé et publié reste dépendant de définitions qui doivent pouvoir être inspectées, testées et reproduites.'},
 {'id':'fr-c1-u05-p04','seq':28,'title':'Risque ressenti, dommage mesuré et communication publique','genre':'journalistic analysis','domains':['public','educational'],'topics':['risk communication','harm'],'paras':["Le public ne rencontre pas le risque sous la forme d’une seule probabilité. Il reçoit des récits, des images, des expériences personnelles et des chiffres parfois difficiles à comparer. Une communication responsable doit donc distinguer perception du danger, fréquence observée et gravité possible.","Le dossier compare des témoignages à des données de dommages. Les expériences rapportées ne sont pas rejetées : elles indiquent ce que les personnes vivent et ce qui influence leurs décisions. Mais elles ne remplacent pas une mesure de fréquence lorsque la question porte sur la probabilité d’un événement dans une population.","Le contreargument rappelle qu’un dommage rare mais irréversible peut justifier une forte attention. Le texte l’accepte et refuse une lecture où seule la fréquence compte. Il propose de présenter séparément probabilité, gravité, réversibilité et incertitude, puis d’indiquer comment ces dimensions influencent une recommandation.","La conclusion demande enfin de tester la communication elle-même. Si une formulation réduit la compréhension ou conduit systématiquement certains publics à surestimer ou sous-estimer un danger, le message doit être révisé même si les chiffres sous-jacents restent identiques."],'qclaim':'Quelle distinction centrale organise la communication du risque ?','aclaim':'La perception, la fréquence, la gravité et l’incertitude sont des dimensions liées mais distinctes qui ne doivent pas être compressées en un seul jugement de danger.','qinfer':'Pourquoi les témoignages restent-ils utiles ?','ainfer':'Ils documentent l’expérience et les facteurs qui orientent les décisions, même s’ils ne mesurent pas seuls la fréquence populationnelle.','qassume':'Pourquoi un risque rare peut-il rester important ?','aassume':'Parce que la gravité et l’irréversibilité peuvent modifier le seuil de précaution indépendamment de la seule fréquence.','qrelation':'Comment le texte traite-t-il le contreargument sur les dommages rares ?','arelation':'Il l’intègre en séparant probabilité et gravité puis en expliquant leur rôle distinct dans la décision.','astance':'Présenter les composantes du risque séparément et tester la compréhension produite par le message.','asummary':'Une bonne communication du risque rend visibles à la fois ce qui est mesuré, ce qui est ressenti, la gravité possible et l’incertitude.'},
 {'id':'fr-c1-u05-p05','seq':29,'title':'Un résultat local peut-il voyager ?','genre':'journalistic analysis','domains':['public','educational'],'topics':['generalization','transfer'],'paras':["Un résultat obtenu dans une population précise peut être très bien mesuré et pourtant se transférer mal ailleurs. La question n’est pas de savoir si les personnes d’un autre pays sont « différentes » en général, mais si les variables qui font fonctionner le mécanisme changent entre les contextes.","Le dossier examine des différences d’âge, d’institution, de période et d’exposition de fond. Il demande lesquelles sont liées au mécanisme proposé et lesquelles sont seulement descriptives. La généralisation devient ainsi une comparaison structurée plutôt qu’un saut de l’échantillon vers le monde entier.","Le contreargument affirme qu’exiger une réplication dans chaque contexte rendrait toute connaissance trop locale. L’analyse répond que le transfert peut être gradué : certaines composantes du mécanisme sont très générales, tandis que l’amplitude ou les conditions pratiques demandent une validation supplémentaire.","La conclusion recommande de communiquer la portée avec le résultat. Au lieu de dire qu’un effet existe partout ou nulle part, le résumé précise où les données sont directes, où l’inférence est raisonnable et où une nouvelle étude pourrait réellement changer la décision."],'qclaim':'Comment le passage définit-il une généralisation défendable ?','aclaim':'Comme un transfert fondé sur la comparaison des mécanismes et conditions pertinentes entre contextes, pas sur une ressemblance globale.','qinfer':'Pourquoi une étude locale peut-elle rester utile ailleurs ?','ainfer':'Parce que certaines composantes du mécanisme peuvent se transférer même si l’amplitude ou les conditions pratiques changent.','qassume':'Quelle hypothèse doit être vérifiée avant de transférer un résultat ?','aassume':'Que les variables qui soutiennent le mécanisme restent suffisamment comparables dans le nouveau contexte.','qrelation':'Comment le texte répond-il à l’objection qu’on ne peut répliquer partout ?','arelation':'Il propose un transfert gradué et cible les nouvelles études sur les conditions réellement susceptibles de changer l’inférence.','astance':'Communiquer explicitement les niveaux de preuve directe, d’inférence et d’incertitude de transfert.','asummary':'La portée d’un résultat doit voyager avec ses conditions de validité, et non être ajoutée implicitement après coup.'}
 ]
def checkpoint(groups,deck,lo,hi,theme):
 forms=[f for k in ['p01','p02','p03','p04','p05'] for f in groups[k]];rev=[base.cur(f,deck) for f in forms];ids={t['form']:t['id'] for t in rev};g=[groups[f'p0{i}'] for i in range(1,6)]
 paras=[f"Le checkpoint de « {theme} » commence par la force du langage. « {g[0][0]} », « {g[0][1]} », « {g[0][2]} » et « {g[0][3]} » obligent à relier assurance, apparence et suffisance aux preuves qui les soutiennent plutôt qu’à l’effet rhétorique recherché.",f"La méthode ajoute ensuite des règles de décision. « {g[1][0]} », « {g[1][1]} », « {g[1][2]} » et « {g[1][3]} » rappellent qu’une exception, un ordre temporel, une fin de collecte ou une différence de magnitude peuvent modifier l’inférence si leur traitement est choisi après observation du résultat.",f"La classification et la publication deviennent elles-mêmes analysables avec « {g[2][0]} », « {g[2][1]} », « {g[2][2]} » et « {g[2][3]} ». Les catégories doivent être reproductibles et pertinentes, tandis que le texte publié doit rendre accessibles les décisions qui pourraient changer l’interprétation.",f"Le risque ajoute une dimension normative. « {g[3][0]} », « {g[3][1]} », « {g[3][2]} » et « {g[3][3]} » distinguent expérience, perception, fréquence et gravité. Enfin, « {g[4][0]} », « {g[4][1]} », « {g[4][2]} » et « {g[4][3]} » imposent de communiquer les conditions de transfert dans le temps et entre contextes. La conclusion C1 reste révisable : une meilleure mesure, une réplication ou un changement de contexte peut modifier force, portée ou mécanisme sans transformer toute connaissance précédente en erreur."]
 paras,text=fit(paras,lo,hi)
 items=[('main_claim','Quelle règle générale clôt l’unité ?','Relier chaque affirmation scientifique à sa force de preuve, sa méthode, sa portée et une règle explicite de révision.',[g[0][0],g[4][1]]),('inference','Pourquoi incertitude et utilité ne s’opposent-elles pas ?','Parce qu’une conclusion peut guider une décision tout en conservant des limites précises sur sa magnitude, sa portée ou son mécanisme.',[g[0][2]]),('assumption','Que faut-il vérifier avant de généraliser ?','Que les conditions qui soutiennent le mécanisme restent comparables dans le nouveau contexte.',[g[4][0],g[4][3]]),('argument_relation','Comment l’unité traite-t-elle les contrearguments ?','Elle les transforme en tests, analyses de sensibilité, conditions de transfert ou règles de révision.',[g[1][0],g[2][3]]),('stance','Quelle position adopte le checkpoint sur la communication scientifique ?','Une communication précise, graduée, transparente sur les méthodes et explicitement révisable.',[g[0][1],g[3][1]]),('cause_effect','Pourquoi une règle d’arrêt mal définie peut-elle biaiser un résultat ?','Parce que choisir la fin après avoir vu les données peut favoriser une conclusion particulière.',[g[1][2]]),('cross_text_synthesis','Comment catégories et risque posent-ils une difficulté commune ?','Dans les deux cas, une étiquette simple peut cacher plusieurs dimensions qu’il faut mesurer et communiquer séparément.',[g[2][2],g[3][2]]),('vocabulary_in_context','Pourquoi les vingt formes sont-elles regroupées ?','Elles structurent confiance, méthode, classification, risque et transfert.',g[0]),('synthesis','Quand une conclusion doit-elle être révisée plutôt qu’abandonnée ?','Quand de nouvelles données changent sa force, sa portée ou son mécanisme sans invalider toutes les observations précédentes.',[g[0][3],g[4][2]]),('summary','Résume le checkpoint.','La maîtrise C1 de l’incertitude scientifique consiste à calibrer les mots, rendre visibles les choix méthodologiques, séparer les dimensions du risque et annoncer les limites de transfert.',forms)];q,a=base.qa(items,ids)
 return {'id':'fr-c1-u05-p06','language':'fr','cefr':'C1','unit':5,'sequence':30,'revision':1,'title':f'Checkpoint C1 Unit05 — {theme}','passage_type':'checkpoint','genre':'research summary','domains':['educational','professional'],'topics':[theme,'C1 Unit05','checkpoint'],'text':text,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”\"])?',text))),'estimated_known_token_coverage':0,'new_lexical_targets':[],'review_lexical_targets':rev,'grammar_targets':[{'id':'fr-c1-u05-g-checkpoint','role':'review','description':'review calibrated certainty, comparison and transfer language'}],'discourse_targets':[{'id':'fr-c1-u05-d-checkpoint','role':'review','description':'synthesize uncertainty, method, risk and generalization'}],'questions':q,'answer_key':a,'speed_training':{'timed':False,'benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'none','notes':'C1 Unit05 checkpoint.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Zero-new C1 Unit05 checkpoint.']},'paired_text_group':None,'prerequisites':['French C1 Unit05 P01-P05'],'difficulty_notes_internal':'C1 scientific uncertainty checkpoint.','reader_tags':['unit_role:checkpoint','generation_batch','french_c1_u05']}
def main():
 lock=json.loads(LOCK.read_text(encoding='utf-8'));plan=json.loads(PLAN.read_text(encoding='utf-8'));sel=json.loads(SEL.read_text(encoding='utf-8'));c1blob=h(C1);b2blob=h(B2)
 if lock.get('status')!='PASS' or lock.get('last_sequence')!=24 or lock.get('c1_canonical_blob')!=c1blob or lock.get('b2_canonical_blob')!=b2blob:raise AssertionError('Unit04 lock/live mismatch')
 if plan.get('status')!='PASS' or plan.get('c1_source_blob')!=c1blob or sel.get('status')!='PASS' or sel.get('c1_source_blob')!=c1blob:raise AssertionError('Unit05 plan/selection stale')
 prior=[json.loads(x) for x in C1.read_text(encoding='utf-8').splitlines() if x.strip()]
 if len(prior)!=24:raise AssertionError('Unit05 requires exactly 24 prior C1 rows')
 groups=sel['passage_groups'];reviews=lock['unit04_target_groups'];deck=base.deck();lo,hi=plan['c1_word_min'],plan['c1_word_max'];theme=plan['theme'];unit=[]
 for s in specs():unit.append(row(s,groups[s['id'][-3:]],reviews[s['id'][-3:]],prior,deck,lo,hi,theme))
 unit.append(checkpoint(groups,deck,lo,hi,theme));V=Draft202012Validator(json.loads(SCHEMA.read_text(encoding='utf-8')));selected={x['form'] for x in sel['selected']};new=[]
 for r in unit:
  errs=list(V.iter_errors(r))
  if errs:raise AssertionError(f"{r['id']}: schema {[e.message for e in errs[:6]]}")
  if not lo<=r['word_count']<=hi or r['word_count']!=len(r['text'].split()):raise AssertionError(f"{r['id']}: word count {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(f"{r['id']}: Q/A count")
  local={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[])};amap={a['question_id']:a['id'] for a in r['answer_key']}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in local for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} linkage")
  for t in r.get('new_lexical_targets',[]):
   if base.cnt(r['text'],t['form'])!=t['exposures_in_text'] or t['exposures_in_text']<1:raise AssertionError(f"{r['id']} exposure {t['form']}")
   new.append(t)
  for t in r.get('review_lexical_targets',[]):
   if base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']} review {t['form']}")
 if len(new)!=20 or {t['form'] for t in new}!=selected or len({t['id'] for t in new})!=20:raise AssertionError('Unit05 target mismatch')
 if unit[-1]['new_lexical_targets']:raise AssertionError('Unit05 checkpoint new target')
 with C1.open('a',encoding='utf-8') as f:
  for r in unit:f.write(json.dumps(r,ensure_ascii=False)+'\n')
 print(json.dumps({'status':'PASS','c1_passages':30,'unit05_word_counts':[r['word_count'] for r in unit],'unit05_targets':sorted(selected)},ensure_ascii=False))
if __name__=='__main__':main()
