#!/usr/bin/env python3
"""Append French B1 Unit 10 (sequences 55-60), the B1 closeout unit."""
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
from jsonschema import Draft202012Validator
import generate_french_b1_unit09 as prev
base=prev.base
REPO=Path(__file__).resolve().parents[2];A1=REPO/'reading/french/a1/passages.jsonl';A2=REPO/'reading/french/a2/passages.jsonl';CANON=REPO/'reading/french/b1/passages.jsonl';SCHEMA=REPO/'reading/schema/passage.schema.json'
EXPECTED_A1_BLOB='0493a2fa13e51b5997db05e91cdea4d8dc5e647b';EXPECTED_A2_BLOB='d0a80b8866071f426019aa0ad143e1d270dba4de';EXPECTED_B1_BLOB='7e181bae59cf892d6d49534818cce134ce4bdfd6'
FORMS=('monstre','ridicule','innocent','vide','débarrasser','centre','bain','toilette','baisser','peau','nez','vêtement','couleur','énorme','traîner')

def qa(forms,reviews,label):
 a,b,c=forms;x,y,z=reviews
 return [('gist',f'Quelle idée guide cette situation de {label} ?',f'Camille compare les indices avant d’interpréter {a}, {b} et {c}.',[a,b,c]),('literal_detail','Quel détail concret est observé ?','Un détail précis est comparé avant la conclusion. ',[a]),('cause_effect','Pourquoi la première solution n’est-elle pas acceptée immédiatement ?','Parce qu’elle pourrait masquer une contrainte ou une interprétation différente. ',[b]),('vocabulary_in_context',f'Que signifie « {a} » dans le passage ?',f'« {a} » prend le sens montré par les actions et les indices du contexte.',[a]),('vocabulary_in_context',f'Que signifie « {b} » dans le passage ?',f'« {b} » est utilisé dans son sens concret ou évaluatif présenté dans le texte.',[b]),('inference','Que peut-on déduire de la comparaison ?','La conclusion doit rester proportionnée à ce qui a réellement été observé. ',[c]),('motive','Pourquoi Camille garde-t-elle une trace du choix ?','Pour pouvoir expliquer et vérifier la décision plus tard. ',[x]),('grammar_in_context',f'Quel rôle joue « {c} » dans la phrase cible ?','Il complète le raisonnement en précisant un état, une propriété ou une évolution. ',[c]),('cloze_transfer','Complète avec le premier mot cible.',a,[a]),('summary','Résume le passage. ',f'Camille utilise {a}, {b} et {c} tout en réactivant {x}, {y} et {z} pour arriver à une conclusion vérifiable.',[a,b,c,x,y,z])]
DATA=[
('fr-b1-u10-p01',55,'instructional','Un monstre ridicule peut rester innocent dans l’histoire','storytelling interpretation narrative',['educational','personal'],['storytelling','interpretation'],['monstre','ridicule','innocent'],['nettoyer','niveau','atteindre'],[
"Dans un atelier d’écriture, les élèves lisent une histoire où un village accuse un monstre d’avoir détruit un jardin. Le dessin le rend énorme et inquiétant, mais Camille demande de revenir aux faits du récit. Les traces montrent surtout que des branches sont tombées pendant la nuit. Avant d’atteindre la conclusion que le monstre est coupable, la classe doit nettoyer son raisonnement des détails décoratifs et distinguer le niveau de preuve du niveau d’émotion.",
"Un passage plus loin révèle que le monstre dormait dans une grotte au moment des dégâts. L’accusation devient alors presque ridicule, mais Camille évite de se moquer des personnages. Ils ont interprété trop vite une apparence impressionnante. Le monstre peut être innocent de cet événement sans devenir automatiquement gentil dans toute l’histoire. Le mot innocent répond seulement à l’accusation examinée. Cette précision permet aux élèves d’atteindre une conclusion limitée : le dessin et la peur ne suffisent pas à prouver la responsabilité.",
"Les élèves réécrivent ensuite la scène du point de vue d’un témoin. Certains choisissent un ton comique et rendent la rumeur volontairement ridicule. Camille leur demande pourtant de conserver la distinction entre plaisanter sur une erreur et transformer le monstre en personnage sans complexité. Le travail devient un exemple de lecture critique : nettoyer une hypothèse signifie retirer ce qui n’est pas soutenu, vérifier le niveau de certitude et atteindre seulement la conclusion permise. Dans ce cadre, « monstre », « ridicule » et « innocent » ne sont pas des étiquettes interchangeables ; chacun décrit une partie différente du récit."
]),
('fr-b1-u10-p02',56,'reinforcement','Un espace vide au centre aide à se débarrasser du désordre','storage reorganization narrative',['professional','public'],['storage','organization'],['vide','débarrasser','centre'],['forcer','coincer','remonter'],[
"Dans la réserve d’un centre communautaire, des boîtes empêchent l’accès au matériel de saison. Camille propose d’abord de créer un espace vide au centre de la pièce. Il ne s’agit pas de se débarrasser de tout ce qui est ancien, mais de pouvoir déplacer les objets sans les forcer entre deux étagères. Une caisse commence justement à coincer sous une tablette parce qu’elle a été rangée trop haut.",
"L’équipe retire la caisse et la pose dans l’espace vide. Au lieu de forcer, elle vérifie son contenu puis décide quels objets doivent remonter sur les étagères et lesquels peuvent être donnés. Se débarrasser signifie ici retirer ce qui n’a plus d’usage pour le centre, pas jeter au hasard. Camille place les objets les plus souvent utilisés près du centre de la zone accessible et garde les réserves lourdes plus bas. Le nouvel espace vide sert temporairement de zone de tri.",
"À la fin, aucune boîte ne bloque le passage. Camille remarque que remonter un objet n’est utile que si son emplacement reste sûr et accessible. Une boîte qui peut coincer indique que l’organisation doit changer ; la pousser avec force aurait seulement caché le problème. Le centre conserve une liste des dons et des objets déplacés. L’objectif n’était donc pas de produire le maximum de vide, mais de se débarrasser du désordre qui empêchait le travail. En gardant un espace libre au centre, l’équipe peut vérifier chaque choix avant de remplir de nouveau les étagères."
]),
('fr-b1-u10-p03',57,'interleaved','Baisser la consommation entre bain et toilette','public facility conservation report',['public','educational'],['water conservation','facilities'],['bain','toilette','baisser'],['quartier','magasin','silence'],[
"Une maison de quartier examine sa consommation d’eau après une hausse inhabituelle. Le bâtiment comprend des douches, une petite salle familiale avec bain et plusieurs espaces de toilette. Camille compare les relevés horaires plutôt que de supposer qu’un seul équipement explique tout. La nuit, lorsque le magasin voisin est fermé et que le quartier est presque en silence, le compteur continue de tourner lentement. L’équipe cherche donc une fuite possible.",
"Un contrôle montre qu’une toilette laisse couler un filet d’eau en permanence. Le bain n’est presque jamais utilisé pendant cette période, donc le fermer ne ferait pas beaucoup baisser la consommation. Camille fait réparer le mécanisme de la toilette puis compare le compteur pendant deux nuits. La consommation baisse nettement. Elle explique que baisser décrit ici une évolution mesurée : le nombre descend après une intervention précise. Le silence du bâtiment facilite aussi l’écoute de petits bruits d’écoulement.",
"La maison de quartier affiche ensuite des conseils simples : signaler une toilette qui coule, remplir un bain seulement au niveau nécessaire et vérifier les robinets après les activités. Le but n’est pas de culpabiliser les visiteurs ni le magasin voisin. Il est de relier chaque recommandation à une cause observée. Camille retient qu’un quartier peut baisser sa consommation en corrigeant d’abord les pertes continues. Comparer bain, toilette et compteur évite une conclusion basée seulement sur l’équipement qui semble consommer le plus à première vue."
]),
('fr-b1-u10-p04',58,'transfer','Peau, nez et vêtement : trois indices différents','biology and clothing observation narrative',['educational'],['biology','observation'],['peau','nez','vêtement'],['exemple','tort','intéressant'],[
"Dans un atelier sur l’adaptation au froid, les élèves observent des photographies d’animaux et de personnes équipées pour l’hiver. Un élève donne l’exemple d’un manteau très épais et affirme que tout ce qui protège du froid fonctionne de la même manière. Camille trouve l’idée intéressante mais trop large. La peau d’un animal, le nez exposé au vent et un vêtement ajouté par une personne ne jouent pas exactement le même rôle.",
"La classe compare plusieurs images. Une couche de fourrure peut protéger la peau, tandis qu’un nez reste souvent plus exposé. Un vêtement peut être ajouté, retiré ou changé selon l’activité. L’élève reconnaît qu’il avait tort de traiter ces éléments comme une seule catégorie. Son exemple reste pourtant utile : il permet de demander quelles propriétés réduisent réellement la perte de chaleur et lesquelles dépendent du comportement. Camille note que l’observation de la peau seule ne suffit pas à décrire tout l’organisme.",
"Les élèves construisent ensuite un tableau avec trois colonnes : structure du corps, partie exposée et équipement externe. Ils placent peau, nez et vêtement dans des colonnes différentes avant de comparer leurs fonctions. Camille trouve ce classement intéressant parce qu’il évite de transformer une ressemblance visuelle en identité fonctionnelle. Avoir tort sur la première classification a rendu l’exemple plus instructif. Le passage du dessin au tableau montre ainsi une pratique générale : préciser ce qu’on compare avant d’expliquer pourquoi deux formes de protection semblent similaires."
]),
('fr-b1-u10-p05',59,'transfer','Une couleur énorme ne doit pas faire traîner tout le projet','community event production narrative',['public','professional'],['event production','design'],['couleur','énorme','traîner'],['merveilleux','surprendre','radio'],[
"Une équipe prépare l’affiche d’un festival de quartier diffusé aussi par une petite radio locale. Le premier projet utilise une couleur rouge très vive sur un titre énorme. Plusieurs bénévoles trouvent l’effet merveilleux, tandis que d’autres craignent qu’il soit difficile à lire sur un petit écran. Camille propose un test avant de laisser la discussion traîner pendant toute la réunion. L’équipe imprime trois tailles et compare la lecture à différentes distances.",
"Le résultat va surprendre certains participants : le titre énorme attire bien l’attention sur le grand panneau, mais il laisse trop peu de place aux informations pratiques. Une couleur légèrement moins intense reste visible et améliore le contraste. La radio n’a évidemment pas besoin de la couleur ; elle doit plutôt reprendre oralement le nom, l’heure et le lieu. Camille explique que faire traîner le choix sans nouveau test n’ajouterait aucune information. Il faut décider à partir du support réel.",
"Le groupe choisit finalement deux versions coordonnées. Le grand panneau garde un titre important mais moins énorme, et la version mobile simplifie encore la mise en page. La même couleur sert de repère visuel. Camille conserve les résultats du test pour expliquer le choix aux bénévoles absents. Elle retient qu’un élément merveilleux dans un contexte peut surprendre négativement dans un autre. Une radio, un panneau et un téléphone imposent des contraintes différentes. Pour éviter de faire traîner les décisions, l’équipe doit définir ce qu’elle cherche à mesurer puis accepter qu’une couleur ou une taille soit adaptée à un support sans l’être partout."
])]
SPECS=[]
for pid,seq,ptype,title,genre,domains,topics,forms,reviews,pars in DATA:
 s={'id':pid,'sequence':seq,'ptype':ptype,'title':title,'genre':genre,'domains':domains,'topics':topics,'forms':forms,'reviews':reviews,'paragraphs':pars,'grammar':[{'id':pid+'-grammar','role':'new','description':'B1 contrast, qualification and causal reasoning'}],'discourse':[{'id':pid+'-discourse','role':'new','description':'revise an interpretation by separating labels, evidence and functional constraints'}]};s['items']=qa(forms,reviews,topics[0]);SPECS.append(s)
CHECKPOINT={'id':'fr-b1-u10-p06','sequence':60,'ptype':'checkpoint','title':'B1 : préciser les mots, les preuves et les fonctions','genre':'B1 cumulative level checkpoint','domains':['educational','public','professional'],'topics':['interpretation','organization','conservation','observation','production'],'paragraphs':[
"Dans cette dernière unité B1, Camille continue à limiter chaque conclusion à ce que les preuves permettent. Un monstre peut sembler ridicule tout en étant innocent d’une accusation précise. Dans une réserve, un espace vide au centre peut aider à se débarrasser du désordre sans jeter ce qui reste utile. Dans un bâtiment public, comparer bain et toilette permet de voir quelle intervention fait réellement baisser la consommation.",
"L’observation biologique demande la même précision : peau, nez et vêtement sont trois éléments différents, même s’ils peuvent tous être liés au froid. Dans la production d’un événement, une couleur ou un titre énorme peut fonctionner sur un support et faire traîner la décision s’il n’existe aucun critère de test. Le rôle du lecteur est donc de distinguer apparence, fonction et mesure.",
"Les méthodes de l’unité précédente renforcent cette conclusion. Camille sait nettoyer jusqu’au bon niveau et atteindre la zone pertinente ; éviter de forcer ce qui peut coincer ou demander de remonter ; comprendre le silence entre un quartier et un magasin ; utiliser un exemple intéressant pour reconnaître qu’une idée avait tort ; et laisser une radio surprendre sans qualifier automatiquement tout résultat de merveilleux. Elle termine B1 avec une méthode stable : définir le problème, observer les indices, vérifier le sens exact des mots, comparer plusieurs explications, puis résumer la décision sans dépasser ce qui a été établi."
],'grammar':[{'id':'fr-b1-u10-cumulative','role':'integration','description':'integrate qualification, contrast and evidence-limited conclusions across the final B1 checkpoint'}],'discourse':[{'id':'fr-b1-u10-b1-closeout','role':'integration','description':'synthesize B1 interpretation, functional comparison and evidence-limited summary skills'}]}
CHECKPOINT['items']=[('gist','Quelle méthode clôt le niveau B1 ?','Définir le problème, observer les indices, vérifier le sens, comparer les explications et limiter la conclusion.',['vide','exemple']),('literal_detail','Quels mots appartiennent au récit ?','monstre, ridicule et innocent',['monstre','ridicule','innocent']),('cause_effect','Pourquoi créer un espace vide ?','Pour se débarrasser du désordre et rendre le centre de la réserve accessible.',['vide','débarrasser','centre']),('vocabulary_in_context','Quels mots décrivent la conservation d’eau ?','bain, toilette et baisser',['bain','toilette','baisser']),('vocabulary_in_context','Quels mots décrivent l’observation du froid ?','peau, nez et vêtement',['peau','nez','vêtement']),('inference','Pourquoi la couleur ou la taille doit-elle être testée selon le support ?','Parce qu’une couleur ou un titre énorme peut fonctionner à un endroit mais faire traîner une décision sans critère.',['couleur','énorme','traîner']),('motive','Pourquoi Camille limite-t-elle ses conclusions ?','Pour ne pas présenter comme établi ce que les observations ne permettent pas de soutenir.',[]),('reference_resolution','Dans « ils peuvent tous être liés au froid », à quoi renvoie « ils » ?','À la peau, au nez et au vêtement.',['peau','nez','vêtement']),('cloze_transfer','Complète : Une réparation utile peut faire _____ la consommation.','baisser',['baisser']),('summary','Résume l’unité.','Camille distingue monstre, ridicule et innocent ; utilise vide, débarrasser et centre pour organiser ; compare bain, toilette et baisser ; sépare peau, nez et vêtement ; puis teste couleur et énorme pour éviter de faire traîner le projet.',['monstre','ridicule','innocent','vide','débarrasser','centre','bain','toilette','baisser','peau','nez','vêtement','couleur','énorme','traîner'])]
def text_of(s):return '\n\n'.join(s['paragraphs'])
def mk(s,new,reviews,ids,speed=False):
 q,a=base.qa(s['items'],ids);t=text_of(s);return {'id':s['id'],'language':'fr','cefr':'B1','unit':10,'sequence':s['sequence'],'revision':1,'title':s['title'],'passage_type':s['ptype'],'genre':s['genre'],'domains':s['domains'],'topics':s['topics'],'text':t,'word_count':len(t.split()),'sentence_count':max(1,len(re.findall(r'[.!?](?:[»”"])?',t))),'estimated_known_token_coverage':0,'new_lexical_targets':new,'review_lexical_targets':reviews,'grammar_targets':s['grammar'],'discourse_targets':s['discourse'],'questions':q,'answer_key':a,'speed_training':{'timed':speed,'benchmark_eligible':speed,'comprehension_gate':0.8,'new_word_policy':'none' if speed else 'controlled','notes':'French B1 Unit 10 closeout batch.'},'quality':{'status':'draft','schema_check':'pending','linguistic_review':'pending','pedagogical_review':'pending','answer_key_check':'pending','coverage_check':'pending','fact_check':'not_required','notes':['Guarded French B1 Unit 10 closeout batch.']},'paired_text_group':None,'prerequisites':['French B1 Units 01-09 canonical corpus'],'difficulty_notes_internal':'B1 closeout transfer and synthesis.','reader_tags':['unit_role:'+s['ptype'],'generation_batch','french_b1_u10']}
def build(a1,a2,b1,D):
 prior=base.prior(a1+a2+b1);ids0={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};forms0={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};bad=[]
 for f in FORMS:
  if f not in D:bad.append(f+':missing_lexicon')
  elif base.tid(D[f]['rank']) in ids0 or f in forms0 or prior.get(f):bad.append(f+':already_deliberate')
 if bad:raise AssertionError('B1 Unit10 candidate failures: '+', '.join(bad))
 out=[]
 for s in SPECS:
  text=text_of(s);new=[base.nt(f,text,D) for f in s['forms']];reviews=[base.rev(f,prior) for f in s['reviews']];ids={t['form']:t['id'] for t in new+reviews};out.append(mk(s,new,reviews,ids))
 reviews=[base.cur(f,D) for f in FORMS];ids={t['form']:t['id'] for t in reviews};out.append(mk(CHECKPOINT,[],reviews,ids,True));return out
def main():
 for path,exp,label in [(A1,EXPECTED_A1_BLOB,'A1'),(A2,EXPECTED_A2_BLOB,'A2'),(CANON,EXPECTED_B1_BLOB,'B1')]:
  h=subprocess.check_output(['git','hash-object',str(path)],text=True).strip();
  if h!=exp:raise AssertionError(f'{label} blob drift: {h} != {exp}')
 a1=[json.loads(x) for x in A1.read_text().splitlines() if x.strip()];a2=[json.loads(x) for x in A2.read_text().splitlines() if x.strip()];b1=[json.loads(x) for x in CANON.read_text().splitlines() if x.strip()]
 if len(b1)!=54 or b1[-1]['id']!='fr-b1-u09-p06':raise AssertionError('unexpected frontier')
 D=base.deck();unit=build(a1,a2,b1,D);V=Draft202012Validator(json.loads(SCHEMA.read_text()));prior_ids={t.get('id') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};prior_forms={t.get('form') for r in a1+a2+b1 for t in r.get('new_lexical_targets',[]) if isinstance(t,dict)};ni=[];nf=[]
 for r in unit:
  es=sorted(V.iter_errors(r),key=lambda e:list(e.path));
  if es:raise AssertionError(f"{r['id']}: schema {[e.message for e in es[:4]]}")
  if not 220<=r['word_count']<=350:raise AssertionError(f"{r['id']}: B1 word band {r['word_count']}")
  if len(r['questions'])!=10 or len(r['answer_key'])!=10:raise AssertionError(r['id']+': assessment count')
  if r['sequence']<=59 and len(r['new_lexical_targets'])!=3:raise AssertionError(r['id']+': target load')
  amap={a['question_id']:a['id'] for a in r['answer_key']};decl={t['id'] for f in ('new_lexical_targets','review_lexical_targets') for t in r.get(f,[])}
  for q in r['questions']:
   if amap.get(q['id'])!=q['answer_id'] or any(x not in decl for x in q.get('target_ids',[])):raise AssertionError(f"{r['id']} {q['id']}: linkage")
  for t in r['new_lexical_targets']:
   s=D.get(t['form']);
   if t['id'] in prior_ids or t['form'] in prior_forms or not s or t['source_rank']!=s['rank'] or t['id']!=base.tid(s['rank']) or base.cnt(r['text'],t['form'])!=t['exposures_in_text']:raise AssertionError(f"{r['id']}: target drift {t}")
   ni.append(t['id']);nf.append(t['form'])
  for t in r['review_lexical_targets']:
   if t['representation'] in {'running_text','summary'} and base.cnt(r['text'],t['form'])<1:raise AssertionError(f"{r['id']}: invisible review {t['form']}")
 if len(ni)!=15 or len(set(ni))!=15 or len(set(nf))!=15 or unit[-1]['new_lexical_targets']:raise AssertionError('Unit10 lexical invariant')
 CANON.write_text(''.join(json.dumps(r,ensure_ascii=False,sort_keys=True)+'\n' for r in b1+unit),encoding='utf-8');print(json.dumps({'status':'PASS','unit':10,'b1_passages':60,'word_counts':{r['id']:r['word_count'] for r in unit},'targets':FORMS},ensure_ascii=False))
if __name__=='__main__':main()
