#!/usr/bin/env python3
"""Generate Arabic A1 Unit 08: health and basic needs."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];P=ROOT/"reading"/"arabic"/"a1"/"passages.jsonl";L=ROOT/"reading"/"lexicons"/"arabic.jsonl"
T={216:("يشعر","feels; senses",["behavior_interpretation"]),211:("مشكلة","problem; issue",["cause_consequence"]),349:("حاجة","need; necessity",["cause_consequence"]),258:("مساعدة","help; assistance",["scenario_resolution"]),397:("يد","hand",["example_instance"]),319:("رأس","head",["example_instance"]),446:("قلب","heart",["category_relation"]),479:("سالم","safe; sound; unharmed",["contrast"]),465:("حاول","tried; attempted",["behavior_interpretation"]),327:("قوة","strength; energy",["cause_consequence"])}
def qa(items):
 qs=[];ans=[]
 for i,(t,p,a,ids) in enumerate(items,1):
  q={"id":f"q{i}","type":t,"prompt":p,"answer_id":f"a{i}"};
  if ids:q["target_ids"]=ids
  qs.append(q);ans.append({"id":f"a{i}","question_id":f"q{i}","answer":a,"explanation":""})
 return qs,ans
R=[
{"id":"ar-a1-u08-p01","sequence":43,"title":"ليلى لا تشعر جيدًا","passage_type":"instructional","genre":"home micro-story","domains":["personal"],"topics":["health","feelings","rest"],"text":"تعود ليلى من المدرسة وتجلس بهدوء. تسألها أمها: هل أنت بخير؟ تقول ليلى: لا أشعر أنني بخير تمامًا. أشعر بالتعب ولا أريد أن أخرج اليوم. تلمس أمها جبينها ثم تقول: اجلسي قليلًا واشربي ماءً. تقول ليلى: ليست عندي مشكلة كبيرة، لكنني أحتاج إلى الراحة. تضع حقيبتها جانبًا وتستلقي على الأريكة. بعد فترة تقول: أشعر أفضل قليلًا. تقول أمها: جيد، المهم أن تخبريني عندما تشعرين أن عندك مشكلة بدل أن تواصلي يومك وكأن شيئًا لم يحدث.","new":[216,211],"reviews":[{"id":"ar-r150","form":"يحتاج","review_stage":"R3","representation":"running_text"},{"id":"ar-r111","form":"يبدو","review_stage":"R3","representation":"other"}],"grammar":[{"id":"ar-a1-feel","role":"new","description":"يشعر بـ / يشعر أن for basic physical state"},{"id":"ar-a1-problem","role":"new","description":"مشكلة for an everyday difficulty"}],"discourse":[{"id":"a1-health-state","role":"new","description":"identify a simple problem and response"}],"qa":[("gist","ما الذي يحدث لليلى؟","تشعر بالتعب وتقرر أن ترتاح في البيت.",None),("literal_detail","ماذا تشرب ليلى؟","الماء.",None),("vocabulary_in_context","ماذا يعني «أشعر بالتعب»؟","أن ليلى تحس بالتعب في جسمها.",["ar-r216"]),("vocabulary_in_context","ماذا تعني «مشكلة» هنا؟","حالة أو أمر غير جيد يحتاج إلى الانتباه.",["ar-r211"]),("cause_effect","لماذا لا تخرج ليلى؟","لأنها تشعر بالتعب وتحتاج إلى الراحة.",None),("single_word_definition","ما معنى «يشعر»؟","يحس بحالة جسدية أو نفسية.",["ar-r216"]),("single_word_definition","ما معنى «مشكلة»؟","أمر صعب أو غير جيد يحتاج إلى حل أو انتباه.",["ar-r211"]),("contrast","أيهما يصف إحساسًا: «يشعر» أم «يصل»؟","يشعر.",["ar-r216"]),("cloze_transfer","أكمل: سامر _____ بالتعب بعد يوم طويل.","يشعر",["ar-r216"]),("cloze_transfer","أكمل: لا أجد كتابي؛ عندي _____.","مشكلة",["ar-r211"])]},
{"id":"ar-a1-u08-p02","sequence":44,"title":"أحتاج إلى مساعدة","passage_type":"reinforcement","genre":"school support scene","domains":["educational","personal"],"topics":["help","need","school"],"text":"في اليوم التالي تشعر ليلى أفضل وتذهب إلى المدرسة. في الحصة تحمل مجموعة من الكتب إلى الطاولة، لكن الكتب كثيرة. تقول لمريم: عندي حاجة إلى مساعدة؛ لا أستطيع حمل كل هذه الكتب وحدي. تقول مريم: بالطبع، سأساعدك. تحمل مريم نصف الكتب، وتحمل ليلى الباقي. بعد ذلك يرى المعلم ما تفعلان ويقول: طلب المساعدة جيد عندما تكون المهمة أكبر من شخص واحد. تقول ليلى: كنت أظن أنني أستطيع حملها كلها، لكنني احتجت إلى مساعدة. عندما تضعان الكتب على الطاولة تشكر ليلى مريم، وتشعر أن العمل أصبح أسهل.","new":[349,258],"reviews":[{"id":"ar-r216","form":"يشعر","review_stage":"R1","representation":"running_text"},{"id":"ar-r211","form":"مشكلة","review_stage":"R1","representation":"other"},{"id":"ar-r442","form":"مهمة","review_stage":"R3","representation":"running_text"}],"grammar":[{"id":"ar-a1-need-noun","role":"new","description":"حاجة إلى + noun"},{"id":"ar-a1-help-noun","role":"new","description":"مساعدة in requests and responses"}],"discourse":[{"id":"a1-request-help","role":"new","description":"recognize a need and request help"}],"qa":[("literal_detail","لماذا تطلب ليلى المساعدة؟","لأن الكتب كثيرة ولا تستطيع حملها وحدها.",None),("literal_detail","ماذا تفعل مريم؟","تحمل نصف الكتب.",None),("vocabulary_in_context","ماذا تعني «حاجة إلى مساعدة»؟","أن ليلى تحتاج إلى أن يساعدها شخص آخر.",["ar-r349"]),("vocabulary_in_context","ماذا تعني «مساعدة»؟","عمل يخفف المهمة عن شخص أو يعينه عليها.",["ar-r258"]),("cause_effect","كيف أصبح العمل أسهل؟","لأن مريم شاركت ليلى في حمل الكتب.",None),("single_word_definition","ما معنى «حاجة»؟","شيء مطلوب أو ضروري.",["ar-r349"]),("single_word_definition","ما معنى «مساعدة»؟","عون يقدمه شخص لآخر.",["ar-r258"]),("contrast","إذا كان العمل أكبر من شخص واحد، هل نطلب «مساعدة» أم «موقعًا»؟","مساعدة.",["ar-r258"]),("cloze_transfer","أكمل: عندي _____ إلى ماء.","حاجة",["ar-r349"]),("cloze_transfer","أكمل: طلبت _____ من صديقتي.","مساعدة",["ar-r258"])]},
{"id":"ar-a1-u08-p03","sequence":45,"title":"يدي ورأسي","passage_type":"interleaved","genre":"basic body-description lesson","domains":["educational","personal"],"topics":["body","movement","classroom"],"text":"في حصة اللغة يراجع الطلاب كلمات عن الجسم. يقول المعلم: ارفعوا يدًا واحدة. ترفع ليلى يدها اليمنى. ثم يقول: ضعوا اليد على الرأس. تضع ليلى يدها فوق رأسها وتضحك لأن الجميع يفعل الشيء نفسه. يسأل المعلم: ماذا نستخدم اليد لفعل أشياء كثيرة؟ تقول مريم: نكتب بها ونحمل الأشياء. ثم يسأل: وأين العينان؟ يشير سامر إلى رأسه. يقول المعلم: جيد. بعد الحصة تقول ليلى: عندما أعرف أسماء أجزاء الجسم أستطيع أن أشرح بسهولة إذا كانت عندي مشكلة في يدي أو رأسي.","new":[397,319],"reviews":[{"id":"ar-r349","form":"حاجة","review_stage":"R1","representation":"other"},{"id":"ar-r258","form":"مساعدة","review_stage":"R1","representation":"other"},{"id":"ar-r211","form":"مشكلة","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-hand","role":"new","description":"يد and simple possessive forms"},{"id":"ar-a1-head","role":"new","description":"رأس and simple possessive forms"}],"discourse":[{"id":"a1-body-reference","role":"new","description":"follow simple body-part instructions"}],"qa":[("literal_detail","أي يد ترفع ليلى؟","يدها اليمنى.",["ar-r397"]),("literal_detail","أين تضع ليلى يدها؟","فوق رأسها.",["ar-r397","ar-r319"]),("vocabulary_in_context","ماذا تعني «يد»؟","جزء الجسم الذي نكتب ونحمل به أشياء.",["ar-r397"]),("vocabulary_in_context","ماذا يعني «رأس»؟","جزء الجسم الذي توجد فيه العينان والوجه.",["ar-r319"]),("cause_effect","لماذا تريد ليلى معرفة أسماء أجزاء الجسم؟","حتى تستطيع أن تشرح المشكلة بسهولة.",None),("single_word_definition","ما معنى «يد»؟","جزء الجسم في نهاية الذراع.",["ar-r397"]),("single_word_definition","ما معنى «رأس»؟","الجزء الأعلى من الجسم وفيه الوجه.",["ar-r319"]),("contrast","أيهما نكتب به عادة: اليد أم الرأس؟","اليد.",["ar-r397","ar-r319"]),("cloze_transfer","أكمل: أمسك القلم ب_____.","يدي",["ar-r397"]),("cloze_transfer","أكمل: أضع القبعة على _____.","رأسي",["ar-r319"])]},
{"id":"ar-a1-u08-p04","sequence":46,"title":"فحص بسيط في المدرسة","passage_type":"transfer","genre":"school wellness scene","domains":["educational","personal"],"topics":["body","safety","wellness"],"text":"في المدرسة يوجد يوم بسيط للتعرف إلى الجسم والصحة. تجلس ليلى مع ممرضة المدرسة. تضع الممرضة جهازًا صغيرًا على إصبعها وتشرح أن القلب يعمل طوال الوقت. ثم تطلب من ليلى أن تسمع صوت قلبها بعد حركة قصيرة. تمشي ليلى بسرعة دقيقة، ثم تجلس. تقول: الآن أشعر أن قلبي أسرع. تشرح الممرضة أن الجسم يتغير مع الحركة ثم يهدأ. تسأل ليلى: هل كل شيء سالم؟ تقول الممرضة: هذا نشاط تعليمي بسيط، وأنت الآن مرتاحة. بعد ذلك تعود ليلى إلى الصف وهي تعرف أن كلمة «قلب» اسم لجزء مهم من الجسم، وأن «سالم» يمكن أن يعني أن الشيء لم يصبه ضرر.","new":[446,479],"reviews":[{"id":"ar-r397","form":"يد","review_stage":"R1","representation":"other"},{"id":"ar-r319","form":"رأس","review_stage":"R1","representation":"other"},{"id":"ar-r216","form":"يشعر","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-heart","role":"new","description":"قلب as a basic body-part noun"},{"id":"ar-a1-safe-sound","role":"new","description":"سالم for unharmed/sound in simple contexts"}],"discourse":[{"id":"a1-observe-body-change","role":"new","description":"notice a simple before/after bodily change"}],"qa":[("gist","ما موضوع النشاط؟","التعرف إلى بعض وظائف الجسم بصورة بسيطة.",None),("literal_detail","ماذا يحدث لقلب ليلى بعد الحركة؟","تشعر أنه أسرع.",["ar-r446"]),("vocabulary_in_context","ماذا يعني «قلب» في النص؟","جزء من الجسم يعمل ويُسمع نبضه.",["ar-r446"]),("vocabulary_in_context","ماذا يعني «سالم» في السؤال؟","غير متضرر أو بخير.",["ar-r479"]),("sequence","ماذا تفعل ليلى قبل أن تجلس مرة أخرى؟","تمشي بسرعة لمدة دقيقة.",None),("single_word_definition","ما معنى «قلب»؟","عضو في الجسم يضخ الدم.",["ar-r446"]),("single_word_definition","ما معنى «سالم»؟","بخير أو غير مصاب بضرر.",["ar-r479"]),("contrast","أيهما جزء من الجسم: «قلب» أم «مساعدة»؟","قلب.",["ar-r446"]),("cloze_transfer","أكمل: أشعر بنبض _____ بعد الجري.","قلبي",["ar-r446"]),("cloze_transfer","أكمل: سقط الكتاب لكنه بقي _____.","سالمًا",["ar-r479"])]},
{"id":"ar-a1-u08-p05","sequence":47,"title":"العودة إلى النشاط","passage_type":"checkpoint","genre":"recovery micro-story","domains":["personal"],"topics":["rest","effort","strength"],"text":"بعد يوم من الراحة تشعر ليلى أن عندها قوة أكثر. تريد أن تعود إلى مشيها المعتاد، لكنها لا تبدأ بمسافة طويلة. تقول لأمها: سأحاول أن أمشي عشر دقائق فقط، ثم أرى كيف أشعر. تخرج معها أمها. في البداية تمشي ليلى ببطء. بعد خمس دقائق تقول: أشعر جيدًا، ويمكنني أن أكمل. عندما تنتهي العشر دقائق تعود إلى البيت ولا تحاول أن تفعل أكثر من خطتها. تقول أمها: جيد أنك حاولت بهدوء. تقول ليلى: عندما لا تكون عندي قوة كافية أرتاح، وعندما أشعر أفضل أحاول من جديد خطوة صغيرة. بهذه الطريقة لا أحول الراحة أو النشاط إلى مشكلة.","new":[465,327],"reviews":[{"id":"ar-r446","form":"قلب","review_stage":"R1","representation":"other"},{"id":"ar-r479","form":"سالم","review_stage":"R1","representation":"other"},{"id":"ar-r216","form":"يشعر","review_stage":"R2","representation":"running_text"}],"grammar":[{"id":"ar-a1-try","role":"new","description":"حاول أن + verb"},{"id":"ar-a1-strength","role":"new","description":"قوة for physical energy/strength"}],"discourse":[{"id":"a1-gradual-action","role":"integration","description":"follow a small attempt and response to how one feels"}],"qa":[("gist","كيف تعود ليلى إلى النشاط؟","بمشي قصير وهادئ ثم تلاحظ كيف تشعر.",None),("literal_detail","كم دقيقة تخطط للمشي؟","عشر دقائق.",None),("vocabulary_in_context","ماذا يعني «أحاول»؟","أقوم بمحاولة لفعل الشيء دون ضمان النتيجة.",["ar-r465"]),("vocabulary_in_context","ماذا تعني «قوة» في النص؟","الطاقة أو القدرة الجسدية التي تساعدها على الحركة.",["ar-r327"]),("cause_effect","لماذا لا تبدأ ليلى بمسافة طويلة؟","لأنها عائدة بعد الراحة وتريد أن تبدأ بهدوء.",None),("single_word_definition","ما معنى «حاول»؟","بذل جهدًا لفعل شيء.",["ar-r465"]),("single_word_definition","ما معنى «قوة»؟","قدرة أو طاقة تساعد على الفعل.",["ar-r327"]),("contrast","عندما لا تكون عندها قوة كافية، هل ترتاح أم تزيد المشي؟","ترتاح.",["ar-r327"]),("cloze_transfer","أكمل: _____ أن أقرأ الصفحة وحدي.","سأحاول",["ar-r465"]),("cloze_transfer","أكمل: بعد النوم عندي _____ أكثر.","قوة",["ar-r327"])]},
{"id":"ar-a1-u08-p06","sequence":48,"title":"أفهم حاجتي","passage_type":"fluency","genre":"connected self-care narrative","domains":["personal"],"topics":["health","needs","help","review"],"text":"تعرف ليلى الآن كلمات تساعدها على وصف احتياجات بسيطة. إذا شعرت بالتعب تقول كيف تشعر بدل أن تخفي المشكلة. وإذا كانت عندها حاجة إلى شيء تطلبه، وإذا كان العمل صعبًا تطلب مساعدة. تعرف أسماء أجزاء بسيطة من جسمها مثل اليد والرأس والقلب، فتستطيع أن تشير إلى المكان الذي تتحدث عنه. وهي تعرف أن كلمة «سالم» تصف شيئًا لم يصبه ضرر. بعد الراحة لا تحاول أن تفعل كل شيء دفعة واحدة؛ تبدأ قليلًا وترى هل عندها قوة كافية. بهذه الطريقة تستطيع ليلى أن تتحدث بوضوح عن حالتها واحتياجاتها، وأن تطلب المساعدة عندما تحتاج إليها.","new":[],"reviews":[{"id":"ar-r216","form":"يشعر","review_stage":"R2","representation":"running_text"},{"id":"ar-r211","form":"مشكلة","review_stage":"R2","representation":"running_text"},{"id":"ar-r349","form":"حاجة","review_stage":"R2","representation":"running_text"},{"id":"ar-r258","form":"مساعدة","review_stage":"R2","representation":"running_text"},{"id":"ar-r397","form":"يد","review_stage":"R2","representation":"running_text"},{"id":"ar-r319","form":"رأس","review_stage":"R2","representation":"running_text"},{"id":"ar-r446","form":"قلب","review_stage":"R2","representation":"running_text"},{"id":"ar-r479","form":"سالم","review_stage":"R2","representation":"running_text"},{"id":"ar-r465","form":"حاول","review_stage":"R1","representation":"running_text"},{"id":"ar-r327","form":"قوة","review_stage":"R1","representation":"running_text"}],"grammar":[{"id":"ar-a1-u08-cumulative","role":"integration","description":"recycle feeling, need, help, body parts, simple safety, effort and strength"}],"discourse":[{"id":"a1-needs-fluency","role":"integration","description":"high-coverage cumulative needs reading"}],"qa":[("gist","ما الفكرة الرئيسية في النص؟","ليلى تعرف كيف تصف احتياجاتها وحالتها وتطلب المساعدة.",None),("literal_detail","متى تطلب ليلى مساعدة؟","عندما يكون العمل صعبًا أو تحتاج إليها.",["ar-r258"]),("literal_detail","ما أجزاء الجسم المذكورة؟","اليد والرأس والقلب.",["ar-r397","ar-r319","ar-r446"]),("cause_effect","لماذا تعرف ليلى أسماء أجزاء الجسم؟","حتى تستطيع أن تشير إلى المكان الذي تتحدث عنه.",None),("summary","لخص ما تعلمته ليلى عن احتياجاتها.","تصف ما تشعر به، تحدد حاجتها، وتطلب مساعدة وتبدأ النشاط بهدوء.",None),("single_word_definition","ما معنى «مشكلة»؟","أمر يحتاج إلى انتباه أو حل.",["ar-r211"]),("single_word_definition","ما معنى «سالم»؟","غير متضرر أو بخير.",["ar-r479"]),("contrast","أيهما يعني العون: «مساعدة» أم «قوة»؟","مساعدة.",["ar-r258","ar-r327"]),("grammar_function","ماذا يصف «يشعر»؟","إحساس الشخص بحالة جسدية أو نفسية.",["ar-r216"]),("contrast","أيهما فعل محاولة: «حاول» أم «حاجة»؟","حاول.",["ar-r465","ar-r349"])]}
]
def lex():
 d={}
 for x in L.read_text(encoding="utf-8").splitlines():
  if x.strip():r=json.loads(x);d[r["rank"]]=r
 return d
def tar(n,text,d):
 f,s,c=T[n];r=d[n];return {"id":f"ar-r{n}","form":f,"lemma":f,"part_of_speech":r.get("part_of_speech_source"),"intended_sense":s,"register":"contemporary standard","variety":"MSA","context_strategy":c,"first_introduced":True,"exposures_in_text":max(1,text.count(f)),"source_lexicon":r.get("source_file"),"source_rank":n,"beyond_base":False}
def build(x,d):
 qs,ans=qa(x["qa"]);text=x["text"];return {"id":x["id"],"language":"ar","cefr":"A1","unit":8,"sequence":x["sequence"],"revision":1,"title":x["title"],"passage_type":x["passage_type"],"genre":x["genre"],"domains":x["domains"],"topics":x["topics"],"text":text,"word_count":len(text.split()),"sentence_count":max(1,len(re.findall(r"[.!؟](?:\s|$)",text))),"estimated_known_token_coverage":0,"new_lexical_targets":[tar(n,text,d) for n in x["new"]],"review_lexical_targets":x["reviews"],"grammar_targets":x["grammar"],"discourse_targets":x["discourse"],"questions":qs,"answer_key":ans,"speed_training":{"timed":x["passage_type"]=="fluency","benchmark_eligible":False,"comprehension_gate":0.8,"new_word_policy":"none" if x["passage_type"]=="fluency" else "controlled","notes":"Generation-stage passage; formal fluency/coverage decision deferred to final audit."},"quality":{"status":"draft","linguistic_review":"pending","pedagogical_review":"pending","coverage_check":"pending","answer_key_check":"pending","schema_check":"pending","fact_check":"not_required","notes":["High-quality generation-stage draft; formal audits deferred to the final multi-pass review phase."]},"paired_text_group":None,"prerequisites":[],"difficulty_notes_internal":None,"reader_tags":["unit_role:"+x["passage_type"],"generation_batch"],"complexity_profile":{"mean_sentence_length":None,"median_sentence_length":None,"clause_count":None,"subordination_count":None,"coordination_count":None,"connective_diversity":None,"lexical_diversity":None,"reference_chain_max_distance":None,"multiword_expression_count":None,"morphology_notes":"A1 generation-stage draft; transparent contemporary MSA.","inference_depth":"local"}}
def main():
 old=[json.loads(z) for z in P.read_text(encoding="utf-8").splitlines() if z.strip()];old=[x for x in old if x.get("unit")!=8];d=lex();new=[build(x,d) for x in R]
 if len(new)!=6 or any(len(x["questions"])!=10 or len(x["answer_key"])!=10 for x in new):raise SystemExit("Unit08 generation contract failed")
 rows=sorted(old+new,key=lambda x:(x.get("unit",0),x.get("sequence",0)));P.write_text("".join(json.dumps(x,ensure_ascii=False,sort_keys=True)+"\n" for x in rows),encoding="utf-8");print("generated Arabic A1 Unit 08: six passages, sixty questions, sixty answers")
if __name__=="__main__":main()
