#!/usr/bin/env python3
"""Generate Arabic C2 Unit 09: technology, ethics, and future uncertainty. Fictional systems only."""
from __future__ import annotations
import json,re,unicodedata
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'reading/arabic/c2/passages.jsonl';LEX=ROOT/'reading/lexicons/arabic.jsonl';D=re.compile(r'[\u0610-\u061a\u064b-\u065f\u0670\u06d6-\u06ed]')
def n(s):return D.sub('',unicodedata.normalize('NFC',str(s or '')).replace('ـ','').strip())
def lx():
 d={}
 for l in LEX.read_text(encoding='utf-8').splitlines():
  if l.strip():r=json.loads(l);d.setdefault(n(r.get('form','')),r)
 return d
def prior():
 z={}
 for lv in ('a1','a2','b1','b2','c1','c2'):
  p=ROOT/f'reading/arabic/{lv}/passages.jsonl'
  if p.exists():
   for l in p.read_text(encoding='utf-8').splitlines():
    if l.strip():
     r=json.loads(l)
     if r.get('cefr')=='C2' and r.get('unit')==9:continue
     for t in r.get('new_lexical_targets',[]):z.setdefault(n(t.get('form','')),[]).append(r.get('id'))
 return z
S={'تيسير':'facilitation','هيمنة':'control; dominance','خارطة':'map','تصاعد':'escalation; increase','منفرد':'single; acting alone','إدراك':'perception; recognition','مرسل':'transmitter; sender','أوقع':'bring about; cause','مشاورة':'consultation; deliberation','مهلة':'grace period; extension; time window'}
def t(f,text,d):
 r=d[n(f)];return {'id':f"ar-r{r['rank']}",'form':f,'lemma':f,'part_of_speech':r.get('part_of_speech_source'),'intended_sense':S[f],'register':'technology-ethics/contemporary MSA','variety':'MSA','context_strategy':['future_scenario','ethical_tradeoff','uncertainty_analysis'],'first_introduced':True,'exposures_in_text':max(1,text.count(f)),'source_lexicon':r.get('source_file'),'source_rank':r['rank'],'beyond_base':False}
def QA(a,b):
 xs=[('gist','ما المشكلة المركزية؟','اتخاذ قرار تقني أخلاقي تحت عدم يقين مع فصل الأداة عن سلطة القرار.'),('literal_detail','ما المفاضلة التي يعرضها النص؟','فائدة تشغيلية تقابلها مخاطرة أو قيد أو فقدان خيار.'),('inference','لماذا لا تكفي دقة النظام وحدها؟','لأن القرار يعتمد أيضًا على أثر الخطأ وتوزيعه وإمكان المراجعة.'),('argument_relation','ما وظيفة السيناريو البديل؟','اختبار ما إذا كانت الحجة تصمد عندما تتغير الافتراضات.'),('main_claim','ما معيار القرار الأقوى؟','ربط التوقع بحجم الضرر وقابلية الرجوع وآلية المساءلة.'),('contrast','ما الفرق بين التنبؤ والقرار؟','التنبؤ يصف احتمالًا أو مخرجًا، والقرار يختار فعلًا مع تبعات.'),('inference','لماذا تهم قابلية الرجوع؟','لأن الخطأ القابل للعكس يختلف أخلاقيًا وتشغيليًا عن الخطأ الدائم.'),('summary','كيف يتعامل النص مع عدم اليقين؟','يعلن الافتراضات ويقارن السيناريوهات ويحدد من يتحمل أثر الخطأ.'),('single_word_definition',f'ما معنى «{a}»؟',S[a]),('single_word_definition',f'ما معنى «{b}»؟',S[b])]
 q=[];ans=[]
 for i,(typ,p,x) in enumerate(xs,1):q.append({'id':f'q{i}','type':typ,'prompt':p,'answer_id':f'a{i}','target_ids':[]});ans.append({'id':f'a{i}','question_id':f'q{i}','answer':x,'explanation':''})
 return q,ans
P=[
('p01','حين يتحول التيسير إلى هيمنة',['تيسير','هيمنة'],'صممت مؤسسة خيالية مساعدًا آليًا لتيسير توزيع المواعيد. في البداية يقترح النظام أوقاتًا ويترك للموظف الاختيار. بعد أشهر جعلت الإدارة الاقتراح الافتراضي نافذًا ما لم يعترض الموظف خلال دقيقة، فارتفعت السرعة وانخفضت المراجعة. قالت اللجنة إن الفرق ليس تقنيًا صغيرًا: انتقل النظام من تيسير القرار إلى قدر من الهيمنة على مساره، لأن كلفة الاعتراض أصبحت أعلى من كلفة القبول. لا يعني ذلك أن كل اختيار افتراضي غير أخلاقي؛ قد يكون مفيدًا عندما يكون الخطأ منخفض الضرر وقابلًا للتصحيح. لكن كلما ارتفعت كلفة الاعتراض أو صعب الرجوع، وجب فحص من يملك القرار فعلًا لا من يظهر اسمه في الواجهة. اقترحت اللجنة قياس نسبة التعديلات بعد التنفيذ، ووقت الاعتراض، والفئات التي تتحمل أخطاء الجدولة أكثر. السؤال ليس «هل النظام أسرع؟» فقط، بل «كيف أعاد توزيع السلطة والاحتكاك؟».'),
('p02','خارطة السيناريو ليست تنبؤًا بتصاعد واحد',['خارطة','تصاعد'],'أنتج فريق خيالي خارطة لثلاثة مسارات محتملة لاستهلاك شبكة رقمية: استقرار، نمو بطيء، وتصاعد سريع. اختار المدير المسار الأعلى وقال إنه «التوقع الآمن». رد المحلل بأن السيناريو ليس تنبؤًا له احتمال محدد؛ إنه طريقة لاختبار القرار إذا تغيرت الشروط. إذا بنينا كل البنية على التصاعد الأعلى فقد نهدر موارد كثيرة، وإذا تجاهلناه قد نفشل عند ضغط مفاجئ. لذلك بحث الفريق عن قرار يعمل بصورة مقبولة في أكثر من مسار: توسعة صغيرة الآن مع مساحة جاهزة للتوسع لاحقًا. قيمة الخارطة ليست أنها تخبر المستقبل، بل أنها تكشف أي قرار يعتمد بشدة على قصة واحدة. وعندما تظهر بيانات جديدة يمكن تحديث المسارات بدل إعلان أن النموذج «أصاب» أو «أخطأ» كأنه توقع واحد.'),
('p03','المراجع المنفرد لا يضمن إدراك الخطر',['منفرد','إدراك'],'وضعت شركة خيالية شرطًا أن يراجع موظف منفرد كل قرار آلي عالي الأثر. بدا الشرط ضمانة بشرية قوية، لكن الاختبار كشف أن المراجع يرى النتيجة النهائية من دون معلومات كافية عن سببها، فيوافق غالبًا لأن النظام أسرع منه. قالت الباحثة إن وجود إنسان لا يساوي إدراكًا فعليًا للخطر. يحتاج المراجع إلى وقت ومعلومات وسلطة رفض ومعيار يبين متى يتدخل. وفي بعض الحالات يكون فريق صغير أفضل من فرد واحد لأن الأخطاء تمس خبرات مختلفة؛ وفي حالات أخرى يزيد عدد المراجعين المسؤولية الموزعة ويجعل كل شخص يتوقع أن غيره سيلتقط المشكلة. لذلك لا يوجد عدد سحري من البشر. السؤال هو: ما المعلومات التي تصل إليهم، وما الخطأ الذي يستطيعون اكتشافه، وما الذي يحدث بعد اعتراضهم؟'),
('p04','المُرسل لا يحمل وحده مسؤولية ما أوقعه النظام',['مرسل','أوقع'],'في نظام خيالي يرسل جهاز استشعار تحذيرًا إلى منصة، ثم ترتب المنصة الأولويات، ثم يختار فريق بشري الاستجابة. حدث خطأ أوقع تأخيرًا كبيرًا. اتهم كل طرف الحلقة التالية: المرسل قال إن بياناته صحيحة، والمنصة قالت إنها طبقت القاعدة، والفريق قال إنه رأى أولوية منخفضة. أعادت اللجنة سلسلة القرار. اكتشفت أن كل مكون عمل وفق مواصفاته، لكن لا أحد كان مسؤولًا عن اختبار أثر اجتماع المكونات. المسؤولية هنا لا تختفي لأنها موزعة؛ يجب تحديد مالك للنظام الكلي يراقب التفاعلات، مع إبقاء مسؤوليات محلية واضحة. كما فرقت اللجنة بين سبب الخطأ وواجب الإصلاح: قد لا يكون فريق واحد سببًا منفردًا، ومع ذلك تحتاج المؤسسة إلى جهة تستطيع وقف النظام وتنسيق التصحيح.'),
('p05','المشاورة والمهلة كخيار احتياطي',['مشاورة','مهلة'],'أرادت هيئة خيالية إطلاق تقنية جديدة في جميع الفروع دفعة واحدة لأنها واعدة في اختبار محدود. اقترحت لجنة مشاورة قصيرة مع المستخدمين ومهلة قبل التعميم. اتهمها المدير بتأخير الفائدة بسبب مخاطر نظرية. ردت اللجنة بأن قيمة المهلة تعتمد على قابلية القرار للعكس. إذا كان الإطلاق سهل التراجع، قد يكون التعلم من الاستخدام أسرع من نقاش طويل. أما إذا كان سيغير بيانات قديمة أو عقودًا أو بنية لا يمكن الرجوع عنها بسهولة، تصبح المشاورة خيارًا يشتري معلومات قبل فقدان البدائل. اقترحت اللجنة تجربة في فرعين مع شروط توقف معلنة. ليست المهلة فضيلة في ذاتها؛ قد تتحول إلى تسويف. لكنها تكون ذات قيمة عندما تزيد المعلومات قبل قرار يصعب التراجع عنه، وتكون أقل قيمة عندما يمكن التجربة والتصحيح بتكلفة منخفضة.'),
('p06','المستقبل لا يبرر قرارًا بلا شروط',[],'تجمع الوحدة خمس أفكار. قد يبدأ النظام بتيسير العمل ثم يكتسب هيمنة عندما تصبح مقاومة اقتراحه مكلفة. والخارطة الجيدة تعرض مسارات متعددة بدل أن تحول تصاعدًا واحدًا إلى مستقبل مؤكد. ووجود مراجع منفرد لا يضمن إدراك الخطر ما لم تصله المعلومات والسلطة المناسبة. كما أن المرسل أو المكون الواحد لا يفسر كل ما أوقعه نظام موزع؛ المسؤولية تحتاج إلى مستوى كلي ومحلي معًا. وأخيرًا تمنح المشاورة والمهلة قيمة حين تشتريان معلومات قبل قرار يصعب عكسه، لا حين تكونان طقسًا يؤجل كل تغيير. الأخلاق التقنية هنا ليست قائمة محظورات، بل تحليل لهيكل القرار: من يختار، ما الذي يعرفه، من يتحمل الخطأ، هل يمكن الرجوع، وما المعلومات التي ستغير القرار لو ظهرت غدًا؟')]
def build(i,p,d):
 pid,title,fs,text=p;targets=[t(f,text,d) for f in fs];q,a=QA(fs[0],fs[1]) if fs else QA('تيسير','هيمنة')
 if not fs:q=q[:8]+[{'id':'q9','type':'inference','prompt':'ما المهارة العامة؟','answer_id':'a9','target_ids':[]},{'id':'q10','type':'summary','prompt':'ما الأسئلة التي يجب طرحها قبل قرار تقني؟','answer_id':'a10','target_ids':[]}];a=a[:8]+[{'id':'a9','question_id':'q9','answer':'تحليل القرار التقني من حيث السلطة والمعلومات والضرر وقابلية الرجوع.','explanation':''},{'id':'a10','question_id':'q10','answer':'من يختار، ماذا يعرف، من يتحمل الخطأ، وهل يمكن الرجوع وما المعلومات الحاسمة.','explanation':''}]
 ids={x['form']:x['id'] for x in targets}
 for x in q:x['target_ids']=[ids[f] for f in fs if f in x['prompt']]
 role=['instructional','reinforcement','interleaved','transfer','integration','fluency'][i-1]
 return {'id':f'ar-c2-u09-{pid}','language':'ar','cefr':'C2','unit':9,'sequence':42+i,'revision':1,'title':title,'text':text,'passage_type':role,'genre':'advanced analysis' if i<6 else 'C2 technology synthesis','domains':['technology','ethics','future uncertainty'],'topics':['uncertainty','responsibility','reversibility'],'new_lexical_targets':targets,'review_lexical_targets':[] if fs else [{'id':f"ar-r{d[n(f)]['rank']}",'form':f,'review_stage':'R2','representation':'running_text'} for f in S],'grammar_targets':[{'id':f'ar-c2-u09-{pid}-g','role':'integration' if i==6 else 'new','description':'ربط التوقع بالقرار والضرر وقابلية الرجوع والمسؤولية'}],'discourse_targets':[{'id':f'c2-u09-{pid}-d','role':'integration' if i==6 else 'new','description':'evaluate future-facing technology decisions through explicit uncertainty and reversibility'}],'questions':q,'answer_key':a,'word_count':len(text.split()),'sentence_count':max(1,len(re.findall(r'[.!؟](?:\s|$)',text))),'estimated_known_token_coverage':0,'paired_text_group':None,'prerequisites':['Arabic A1-C1 generation corpus','Arabic C2 Units 01-08 generation corpus'],'difficulty_notes_internal':'C2 Unit 09 generation draft: technology, ethics, and future uncertainty using fictional systems.','speed_training':{'timed':i==6,'benchmark_eligible':False,'comprehension_gate':0.8,'new_word_policy':'none' if i==6 else 'controlled','notes':'generation stage; formal audit deferred'},'quality':{'status':'draft','linguistic_review':'pending','pedagogical_review':'pending','coverage_check':'pending','answer_key_check':'pending','schema_check':'pending','fact_check':'not_required','notes':['All systems, organizations, forecasts, and deployments are fictional curriculum scenarios.']},'reader_tags':['unit_role:'+role,'generation_batch','c2'],'complexity_profile':{'mean_sentence_length':None,'median_sentence_length':None,'clause_count':None,'subordination_count':None,'coordination_count':None,'connective_diversity':None,'lexical_diversity':None,'reference_chain_max_distance':None,'multiword_expression_count':None,'morphology_notes':'C2 technology-ethics MSA.','inference_depth':'cross_paragraph_argument_reconstruction'}}
def main():
 d=lx();z=prior();missing=[f for f in S if n(f) not in d]
 if missing:raise KeyError(missing)
 col={f:z[n(f)] for f in S if n(f) in z}
 if col:raise RuntimeError('C2 Unit 09 new-target collision: '+json.dumps(col,ensure_ascii=False,sort_keys=True))
 rows=[json.loads(l) for l in OUT.read_text(encoding='utf-8').splitlines() if l.strip()] if OUT.exists() else [];rows=[r for r in rows if not(r.get('cefr')=='C2' and r.get('unit')==9)];rows.extend(build(i,p,d) for i,p in enumerate(P,1));rows.sort(key=lambda r:r.get('sequence',0));OUT.write_text('\n'.join(json.dumps(r,ensure_ascii=False,sort_keys=True) for r in rows)+'\n',encoding='utf-8');print(f'wrote C2 Unit 09; total rows={len(rows)}; collisions=0')
if __name__=='__main__':main()
