import json,re
from pathlib import Path
p=Path(__file__).resolve().parents[2]/'reading/french/a1/passages.jsonl'
rows=[json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x]
new=json.loads(r'''{"fr-a1-u01-p01":"Camille est dans un nouvel appartement avec sa m\u00e8re. Sa m\u00e8re dit : \u00ab Nous sommes ici maintenant. \u00bb Camille regarde une fen\u00eatre et un livre. Elle dit : \u00ab Je veux travailler ici. \u00bb Sa m\u00e8re va vers la porte et demande : \u00ab Tu veux venir avec moi ? \u00bb Camille vient avec elle. Puis elles retournent pr\u00e8s de la fen\u00eatre. Camille sourit et dit : \u00ab J\u2019aime cet appartement. Je veux rester ici un peu. \u00bb","fr-a1-u01-p02":"Le matin, Camille regarde l\u2019heure. Quand il est presque huit heures, sa m\u00e8re dit : \u00ab Nous allons \u00e0 l\u2019\u00e9cole. \u00bb Alors Camille prend un livre et sort avec elle. Devant l\u2019\u00e9cole, Sami vient vers Camille. Ils entrent ensemble. Quand les cours sont finis, Camille va \u00e0 son appartement. Alors elle met son livre pr\u00e8s de la fen\u00eatre. Sa m\u00e8re demande : \u00ab Tu es ici maintenant ? \u00bb Camille r\u00e9pond oui. Quand sa m\u00e8re arrive, elles parlent un peu. Alors la journ\u00e9e d\u2019\u00e9cole est finie."}''')
patch=json.loads(r'''{"fr-a1-u01-p01":{"prompts":["Que d\u00e9couvre Camille ?","Avec qui Camille est-elle dans l\u2019appartement ?","Que signifie \u00ab ici \u00bb dans \u00ab Nous sommes ici maintenant \u00bb ?","Quand la m\u00e8re demande \u00ab Tu veux venir avec moi ? \u00bb, que propose-t-elle ?","Compl\u00e8te : Je suis dans cette pi\u00e8ce ; je vais lire _____ un moment."],"answers":["Elle d\u00e9couvre son nouvel appartement.","Avec sa m\u00e8re.","dans cet endroit","de l\u2019accompagner","ici"],"types":["gist","literal_detail","vocabulary_in_context","vocabulary_in_context","cloze_transfer"]},"fr-a1-u01-p02":{"prompts":["Que fait Camille apr\u00e8s que sa m\u00e8re dit qu\u2019il est presque huit heures ?","Qui vient vers Camille devant l\u2019\u00e9cole ?","Dans le texte, que signifie \u00ab quand \u00bb ?","Que montre \u00ab alors \u00bb apr\u00e8s l\u2019annonce de l\u2019heure ?","Compl\u00e8te : _____ la porte s\u2019ouvre, nous entrons ; _____ nous nous asseyons."],"answers":["Elle prend un livre et sort avec sa m\u00e8re.","Sami.","le moment o\u00f9 une action arrive","l\u2019action qui suit cette information","Quand ; alors"],"types":["sequence","literal_detail","vocabulary_in_context","vocabulary_in_context","cloze_transfer"],"sense":{"alors":"then; so; at that point"}}}''')
for r in rows:
 if r['id'] not in new: continue
 r['text']=new[r['id']]; r['word_count']=len(re.findall(r'\S+',r['text'])); r['estimated_known_token_coverage']=0
 prompts=patch[r['id']]['prompts']; answers=patch[r['id']]['answers']; types=patch[r['id']]['types']
 r['questions']=[{'id':f'q{i}','type':types[i-1],'prompt':prompts[i-1],'answer_id':f'a{i}'} for i in range(1,6)]
 r['answer_key']=[{'id':f'a{i}','question_id':f'q{i}','answer':answers[i-1],'explanation':''} for i in range(1,6)]
 for x in r.get('new_lexical_targets',[]):
  if x.get('form') in patch[r['id']].get('sense',{}): x['intended_sense']=patch[r['id']]['sense'][x['form']]
 r['quality']['coverage_check']='pending'; r['quality']['answer_key_check']='pass'; r['quality']['status']='draft'
p.write_text('\n'.join(json.dumps(x,ensure_ascii=False,sort_keys=True) for x in rows)+'\n',encoding='utf-8')
