#!/usr/bin/env python3
"""Advance durable project state to C1 Unit03 from the sealed Unit02 frontier."""
from __future__ import annotations
import json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[2];C1=R/'reading/french/c1/passages.jsonl';B2=R/'reading/french/b2/passages.jsonl';LOCK=R/'reading/audit/french_c1_unit02_frontier_lock.json';PLAN3=R/'reading/audit/french_c1_unit03_plan.json';PROBE3=R/'reading/audit/french_c1_unit03_target_probe.json';STATUS=R/'reading/STATUS.json';TASKS=R/'reading/TASKS.md';HANDOFF=R/'reading/AGENT_HANDOFF.md'
def show(v):return v if isinstance(v,str) else json.dumps(v,ensure_ascii=False,sort_keys=True)
def main():
 lock=json.loads(LOCK.read_text(encoding='utf-8'));plan=json.loads(PLAN3.read_text(encoding='utf-8'));probe=json.loads(PROBE3.read_text(encoding='utf-8'));c1blob=subprocess.check_output(['git','hash-object',str(C1)],text=True).strip();b2blob=subprocess.check_output(['git','hash-object',str(B2)],text=True).strip()
 if lock.get('status')!='PASS' or lock.get('last_sequence')!=12 or lock.get('c1_canonical_blob')!=c1blob or lock.get('b2_canonical_blob')!=b2blob:raise AssertionError('C1 Unit02 lock/live mismatch')
 if plan.get('status')!='PASS' or plan.get('c1_source_blob')!=c1blob or probe.get('status')!='PASS' or probe.get('c1_source_blob')!=c1blob:raise AssertionError('C1 Unit03 plan/probe stale')
 theme=show(plan.get('theme'));genres=show(plan.get('genres'));default=lock['accepted_c1_default_new_targets_per_standard_passage'];lo,hi=plan['c1_word_min'],plan['c1_word_max']
 s=json.loads(STATUS.read_text(encoding='utf-8'));fr=s['french'];fr['canonical_passages']=252;fr['questions']=2520;fr['answers']=2520;fr.setdefault('levels',{})['c1']=12;c=fr.setdefault('c1_generation',{});c.update({'status':'unit02_generation_pass','passages':12,'questions':120,'answers':120,'completed_units':[1,2],'last_sequence':12,'canonical_blob':c1blob,'unit02_theme':lock.get('unit02_theme'),'unit02_genres':lock.get('unit02_genres'),'unit02_word_band':lock.get('unit02_word_band'),'unit02_word_counts':lock.get('unit02_word_counts'),'unit02_frontier_lock':'reading/audit/french_c1_unit02_frontier_lock.json','unit02_generation_review':'reading/audit/french_c1_unit02_generation_review.json','accepted_default_new_targets_per_standard_passage':default,'accepted_default_is_hard_quota':False,'unit03_plan':'reading/audit/french_c1_unit03_plan.json','unit03_target_probe':'reading/audit/french_c1_unit03_target_probe.json'});fr['next_target']=f'Generate French C1 Unit 03 / sequences 13-18 against exact C1 blob {c1blob}. Canonical theme: {theme}; genres: {genres}. Use calibrated default {default} fresh targets per P01-P05 unless canonical policy/discourse load supports more; P06 zero-new. Preserve word band {lo}-{hi}, 10 linked Q/A, exact review forms, source identity/exposures and C1 reasoning.';s['phase']='Arabic remains sealed. French A1-B2 generation integrity is sealed; C1 Units 01-02 are canonical and guarded. C1 Unit03 is next.';s['updated']='2026-08-17';s['next_actions']=['keep Arabic sealed unless canonical Arabic changes','generate French C1 Unit03 against exact Unit02 frontier lock','preserve calibrated C1 default as a default, not quota','continue C1 generation-first through Unit10, then C2','defer final whole-French multi-pass audit until C2 generation completes']
 for p in ['reading/audit/french_c1_unit02_generation_review.json','reading/audit/french_c1_unit02_frontier_lock.json','reading/audit/french_c1_unit03_plan.json','reading/audit/french_c1_unit03_target_probe.json']:
  if p not in s.setdefault('important_files',[]):s['important_files'].append(p)
 STATUS.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 t=TASKS.read_text(encoding='utf-8');block=f'''\n\n#### C1 Unit 02 — COMPLETE / GENERATION PASS\n- [x] Sequences 7–12 canonical; 6 passages / 60 Q / 60 A.\n- [x] Strict Unit02 generation review PASS; P06 zero-new.\n- [x] Canonical C1 blob after Unit02: `{c1blob}`.\n- [x] Frontier lock `reading/audit/french_c1_unit02_frontier_lock.json` = PASS.\n\n#### C1 Unit 03 — IMMEDIATE NEXT\n- Theme: **{theme}**.\n- Genres: **{genres}**.\n- [ ] Generate sequences 13–18 against exact C1 blob `{c1blob}`.\n- [ ] Default `{default}` fresh targets per P01–P05, not a hard quota; P06 zero-new.\n- [ ] Preserve `{lo}–{hi}` words and 10 linked Q/A per passage.\n- [ ] Fail closed on source/blob drift, target collisions, source/exposure identity, exact reviews, schema/linkage or C1 reasoning quality.\n'''
 if '#### C1 Unit 02 — COMPLETE / GENERATION PASS' not in t:
  marker='## Urdu — QUEUED';t=t.replace('\n'+marker,block+'\n'+marker,1) if marker in t else t+block
 TASKS.write_text(t,encoding='utf-8')
 h=HANDOFF.read_text(encoding='utf-8')
 if '## French C1 Unit 02 — COMPLETE / CURRENT LOCK' not in h:h+=f'''\n\n## French C1 Unit 02 — COMPLETE / CURRENT LOCK\n\n- Canonical C1 blob `{c1blob}`.\n- 12 total C1 passages / 120 questions / 120 answers.\n- Unit02 strict review and frontier lock PASS.\n- calibrated default remains `{default}` new targets per standard passage, not a hard quota.\n\n### Immediate frontier — French C1 Unit 03\nTheme: **{theme}**. Genres: **{genres}**. Generate sequences 13–18 against `{c1blob}` with `{lo}–{hi}` words, 10 linked Q/A, exact source/review guards, P06 zero-new and full C1 reasoning requirements.\n'''
 HANDOFF.write_text(h,encoding='utf-8');print(json.dumps({'status':'PASS','french_passages':252,'c1_passages':12,'c1_blob':c1blob,'next':'C1 Unit03','theme':theme,'genres':genres,'fresh_remaining':probe.get('fresh_count')},ensure_ascii=False))
if __name__=='__main__':main()
