#!/usr/bin/env python3
"""Sync durable project state only after the full C1 integrity seal passes."""
from __future__ import annotations
import json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[2];C1=R/'reading/french/c1/passages.jsonl';B2=R/'reading/french/b2/passages.jsonl';LOCK=R/'reading/audit/french_c1_unit10_frontier_lock.json';INTEG=R/'reading/audit/french_c1_generation_integrity.json';STATUS=R/'reading/STATUS.json';TASKS=R/'reading/TASKS.md';HANDOFF=R/'reading/AGENT_HANDOFF.md'
def h(p):return subprocess.check_output(['git','hash-object',str(p)],text=True).strip()
def main():
 lock=json.loads(LOCK.read_text(encoding='utf-8'));integ=json.loads(INTEG.read_text(encoding='utf-8'));c1=h(C1);b2=h(B2)
 if lock.get('status')!='PASS' or lock.get('last_sequence')!=60 or lock.get('c1_canonical_blob')!=c1 or lock.get('b2_canonical_blob')!=b2:raise AssertionError('C1 Unit10 lock/live mismatch')
 if integ.get('status')!='PASS' or integ.get('canonical_blob')!=c1 or integ.get('passages')!=60 or integ.get('questions')!=600 or integ.get('answers')!=600 or integ.get('unique_new_target_ids')!=200:raise AssertionError('C1 integrity/live mismatch')
 s=json.loads(STATUS.read_text(encoding='utf-8'));fr=s['french'];fr['canonical_passages']=300;fr['questions']=3000;fr['answers']=3000;fr.setdefault('levels',{})['c1']=60;c=fr.setdefault('c1_generation',{});c.update({'status':'GENERATED_INTEGRITY_PASS_NOT_FINAL_AUDITED','passages':60,'questions':600,'answers':600,'completed_units':list(range(1,11)),'last_sequence':60,'canonical_blob':c1,'unit10_frontier_lock':'reading/audit/french_c1_unit10_frontier_lock.json','unit10_generation_review':'reading/audit/french_c1_unit10_generation_review.json','generation_integrity_status':'PASS','generation_integrity_artifact':'reading/audit/french_c1_generation_integrity.json','unique_new_targets':200,'checkpoint_sequences_zero_new':[6,12,18,24,30,36,42,48,54,60],'accepted_default_new_targets_per_standard_passage':4,'accepted_default_is_hard_quota':False});fr['next_target']=f'Prepare French C2 Unit 01 calibration from sealed C1 blob {c1}. Resolve exact C2 standard and matrix node first; use validated top-3000 continuation rather than forcing unused top-1000 function-word leftovers.';s['phase']='Arabic remains sealed. French A1-C1 generation integrity is sealed; French C2 Unit 01 calibration is next. Final whole-French multi-pass audit remains deferred until C2 generation completes.';s['updated']='2026-08-17';s['next_actions']=['keep Arabic sealed unless canonical Arabic changes','prepare exact French C2 readiness and Unit01 calibration from the sealed C1 integrity artifact','use source-backed top-3000 continuation for advanced C2 vocabulary where appropriate','calibrate C2 lexical load conservatively; planning band is a maximum, not quota','defer final whole-French multi-pass audit until C2 generation completes']
 for p in ['reading/audit/french_c1_unit10_generation_review.json','reading/audit/french_c1_unit10_frontier_lock.json','reading/audit/french_c1_generation_integrity.json']:
  if p not in s.setdefault('important_files',[]):s['important_files'].append(p)
 STATUS.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 t=TASKS.read_text(encoding='utf-8');key='#### French C1 — COMPLETE / GENERATION INTEGRITY PASS'
 if key not in t:
  block=f'''\n\n{key}\n- [x] 60 passages / 600 Q / 600 A canonical.\n- [x] 200 unique deliberate C1 targets; zero prior-level collisions.\n- [x] All ten P06 checkpoints zero-new; schema/linkage/source/exposure/review/word-band integrity PASS.\n- [x] Canonical C1 blob `{c1}`.\n- [ ] Final whole-French multi-pass audit remains deferred through C2 generation.\n\n#### French C2 Unit 01 — IMMEDIATE NEXT\n- [ ] Resolve exact C2 standard + `levels.C2[0]` matrix node against sealed C1.\n- [ ] Probe validated top-3000 continuation and calibrate C2 lexical load conservatively.\n- [ ] Preserve 10 linked Q/A, exact source/exposure/review guards, advanced C2 discourse, and zero-new P06.\n''';marker='## Urdu — QUEUED';t=t.replace('\n'+marker,block+'\n'+marker,1) if marker in t else t+block
 TASKS.write_text(t,encoding='utf-8')
 htxt=HANDOFF.read_text(encoding='utf-8');key2='## French C1 — COMPLETE / GENERATION INTEGRITY LOCK'
 if key2 not in htxt:htxt+=f'''\n\n{key2}\n- 60 C1 passages / 600 Q / 600 A; canonical blob `{c1}`.\n- Full C1 generation-integrity artifact PASS with 200 unique new targets and ten zero-new checkpoints.\n- This is not final French approval; final language-wide review waits for C2.\n\n### Immediate frontier — French C2 Unit 01\nResolve C2 standards and exact matrix node from canonical policy, then calibrate against the sealed C1 blob. Prefer validated top-3000 continuation over leftover top-1000 grammar/interjection tokens.\n'''
 HANDOFF.write_text(htxt,encoding='utf-8');print(json.dumps({'status':'PASS','c1_blob':c1,'french_passages':300,'french_questions':3000,'next':'C2 Unit01 calibration'},ensure_ascii=False))
if __name__=='__main__':main()
